### ISSUE TITLE
PermissionsEx Problem

### ISSUE THREAD

**Issue by valkyrienyanko** [PEXPlugins/PermissionsEx#1200]
```
users:
  username:
    - valkyrienyanko
    group:
    - Owner
```

**Comment by valkyrienyanko** [comment]
Could someone please delete this issue or delete the comment sent by @Fate-Kun above? It contains my real name and I'd like it to be removed.

**Comment by zml2008** [comment]
Should be updated to use your current username and the previous revision deleted -- let me know if you are able to view anything from the past.

**Comment by valkyrienyanko** [comment]
I cannot view any history of the previous changes, thank you!
