### ISSUE TITLE
Change name of groups MySQL

### ISSUE THREAD

**Issue by osky1998** [PEXPlugins/PermissionsEx#159]
I use MySQL for my permissions.
I made one group , Admins
But later on when I had gived all perms .
I wanted to change the name to Admin instead of Admins
because I´m just one Admin and not more.

I think:
/pex group <group> name set <name>
or something like that.

Thanks for reading !

**Comment by jomo** [comment]
Here's how to do this manually with SQL:
```SQL
UPDATE permissions             SET name   = "newname" WHERE name   = "oldname";
UPDATE permissions_entity      SET name   = "newname" WHERE name   = "oldname";
UPDATE permissions_inheritance SET child  = "newname" WHERE child  = "oldname";
UPDATE permissions_inheritance SET parent = "newname" WHERE parent = "oldname";
```

Don't forget to run `/pex reload`!
