### ISSUE TITLE
/reload broke PeX

### ISSUE THREAD

**Issue by RootBeerTF** [PEXPlugins/PermissionsEx#1611]
So long story short, I have Pex linked to an external database (phpMyAdmin) and it was working fine. Permissions were added through console then showed up in the database, group prefixes, etc.

When the /reload command was used, it completely broke. Didnt change anything in the config, etc., it just simply does not work. When adding a permission via console for example, it no longer shows up in the database. People originally in the groups are now disconnected, no name prefix  like before, etc.

No Pex errors in console either.

Help is greatly appreciated.
Thanks in advance.

**Comment by MattCowley** [comment]
Regarding the external db, what does your config look like, as I've added what I think is right, but no tables were created in the db. Do I actually need to switch to the sql backend for the tables to be created?
