### ISSUE TITLE
Default Rank Being Removed When Added To Another Group

### ISSUE THREAD

**Issue by Therobodavo** [PEXPlugins/PermissionsEx#1612]
So, I have been talking on the forums a lot lately about this issue, and we realized this must be a bug.

So, the issue is when a user joins the server, and are the default rank, and then added to a donator rank, they lose their default rank. To have this make more sense, All users have a rank from A - Z (then free and citizen), while they can also have a donor/staff rank. The Normal Ranks give a prefix, and the others give a suffix. I also have given all my ranks that matter here a weight, which does work in all cases but this one.

Let's say a use joins the server, he is moved to the default A group. Then, he goes and buys a rank, which launches the command /pex user (name) group add (rank). When this happens, only when the user is the default rank, his groups goes from 

Group:
    - A

to 

Group:
    - (Donor Rank)

Also, if I have them rankup to B, the groups change as follows

 Group:
    - B

to 

Group:
    - B
    - (Donor Rank)

After doing many tests, I noticed that the rank is removed, the user can't do any commands from the letter rank they had, and when I do /pex user (name) they only have the donor rank. Again, this only happens when they have the default A rank, and the console gives no errors from what I've seen. This is an issue because if they donate when they first join, it messes up ther ranks, and also I can't reset my server and reset ranks since they can't have the default rank and a donor rank for some reason. I have made it so I can have the default rank and donor rank, but I hae to add them to the default group and then remove the donor rank. The thing is, this doesn't always work so I have really no clue what is happening. To add on to this, when the user has a donor rank but no other letter rank, and I add them to A (default rank), it adds them to B and A for some reason. Please try to figure out the issue as I have no clue how this plugin works code wise and I just really want to get my server up.

**Comment by zml2008** [comment]
This is by design -- make the groups  you add inherit from the default group

**Comment by LemADEC** [comment]
If it's by design, what's the point of having multiple ladders in the first place ?!?

**Comment by YepImRobbie** [comment]
Agreed, it's a pain in the ass when someone donates on my prison server at rank A, because they are pushed off the A - Z rankup ladder and get stuck. It's pathetic and this should not be by design, since it is not ideal for prison servers.

**Comment by macdja38** [comment]
The idea is their is a default rank everyone one the server get's one with the ability to talk or build if you would like those abilities

Possible problem
----------------------
The thing that seems to confuse people most is players are not added to the default rank per say. They simple are considered as part of it if they do not have another rank. This means if you change the default rank all players who have not had their rank explicitly set well be considered part of the new default rank. It also means when you "add" a rank to a player they are no longer considered part of default rank.

Solution
----------
On a server where you want to add a donator rank but still want the player to maintain their default rank run:
###Solution A:
`pex user {name} group add default` // if possible check to see if they have been promoted to a non default rank first and only run this command if not, if they currently have been promoted from the default rank then you will have an extra rank that does nothing cluttering stuff.
###Solution B:
`pex promote {name}`
`pex demote {name}`
This would make them explicitly be declared as a part of the default group
then you can run
`pex user {name} group add Donator`

**Comment by superzyr** [comment]
It's an odd thing, but I think setting the default group with quotations works.

By default it looks like this:
default: true

But after adding quotations, I believe the issue was resolved:
default: 'true'

**Comment by jomo** [comment]
unless the YAML parser has bugs, setting to `true` or `yes` should work. `'true'` would be a string, not a boolean.

**Comment by superzyr** [comment]
Well this is the result of issuing the command:
/pex set default group <group> true

Once I issued this command I headed over to the config to see what changed and noticed the quotations.

This is just my 2 cents, I would very much like to be challenged if this possible solution does not work for others.
