### ISSUE TITLE
error pex reload

### ISSUE THREAD

**Issue by alexandrage** [PEXPlugins/PermissionsEx#1671]
При каждой команде pex reload сервер(Cauldron 1.7.10) отжирает все больше и больше cpu процессора, пока сервер совсем не зависнет и всех игроков не кикнет с сервера!
Поизучав код я определил что проблема кроется где то в методах
uninjectPermissible, injectPermissible

**Comment by zml2008** [comment]
Unfortunately I cannot read russian. Hopefully this issue has been resolved by someone since.
