### ISSUE TITLE
PEX Multiverse need relog for right perms.

### ISSUE THREAD

**Issue by Ungarth** [PEXPlugins/PermissionsEx#1678]
Hi there in the Forum he ask that i make a ticket for it.

I have a Bukkit server with the Multiverse worlds: 
Abbauwelt: Everyone can do anything. for farming and mining.
Baurin: Only within the Townys players may build / dismantle Tutorial: Only interact is possible And some more but not important for the problem.

The Permissions all work. The problem lies in the fact that if a player is in the "Abbauwelt" logs on and then yourself home portet in the "Baurin" world, he still has the permissions of the mining world and thus could reduce over all everything. Same problem, conversely, the player moves from "Baurin" in the "Abbauwelt" to farm but can not use anything. The Permissions are reloaded only by relog of the player or / pex reload.

Currently, a autorun Command plugin that every minute the command / pex reload trumpeted out. But since reload commands are tricky in Bukkit be the player after about 30 minutes thrown from the server and must be new the LOG.

See Permissions. http://pastebin.com/UYu8QeWs

Same issue in Bukkitpermissions. Seems to be a Superperm issue.

(When you give a player a new rang he have to relog. When a player change world with other permissions, he have to relog. (for the specific world permissions) Why?)
They have same issue http://www.minecraftforum.net/forums/support/server-support/server-administration/1938445-permissionsex-players-have-to-relog-to-use

Thx for reading
at your service
Ungarth Lord of Nothingelse

**Comment by zml2008** [comment]
Unfortunately fixing the root cause of this issue is not worth the effort in my opinion with sponge coming up. However, I will look at fixing /pex reload to keep working, so you can more reliably use your workaround.
