### ISSUE TITLE
SuperpermsListener causing onPlayerLogin lag

### ISSUE THREAD

**Issue by mllnd** [PEXPlugins/PermissionsEx#1684]
Hey,
I've come across an issue where the SuperpermsListner causes lagspikes/delays when a player logins. The joining player either suffers from a long login time or eventually gets a timeout.
I've included the timings report as well.

![Timings report](http://i.gyazo.com/a0a0924b44c15c7d3375ef350d358069.png)

**Comment by rlf** [comment]
Seeing this
http://timings.aikar.co/?url=12792792

On 1.23.3

**Comment by JANEXLEBJAKOT** [comment]
Same as rlf.
http://timings.aikar.co/?url=13209806
