### ISSUE TITLE
Decrease dependence on bukkit

### ISSUE THREAD

**Issue by yawkat** [PEXPlugins/PermissionsEx#1688]
Lowering general use of bukkit APIs allows developers to port PEX to other platforms easier and with less follow-up maintainance. It also allows for more wide-spread testing.

Ideally, most code should be refactored to a different (maven?) module which can be used without depending on bukkit.

**Comment by zml2008** [comment]
This might be more work to do in sponge because of how well Sponge's interfaces integrate with PEX's new design

**Comment by zml2008** [comment]
The new Sponge version has Sponge-specific code almost completely isolated -- I'm closing this.
