### ISSUE TITLE
MySQL connection failure

### ISSUE THREAD

**Issue by humroben** [PEXPlugins/PermissionsEx#1690]
prior to updating my spigot server to use the 1.8 patch I have been able to use the MySQL function for a couple of years.

However, PEX is unable to retrieve read or write permissions from the MySQL server.

I know that the login that PEX uses has read and write permissions for the tables, as I have multiple plugins that take use of the same database.

I deleted the permission tables, to see if PEX could generate new ones. Instead, it gave me a similar permission error.

Server: spigot-1.7.10 (#1649) - latest spigot 1.8 patch

Here is my PEX configuration
Plugin: PEX
Configuration: http://pastebin.com/DNpHBeMh

Here is a configuration of another one of my plugins that has database perms
Plugin: LogBlock
Configuration: http://pastebin.com/ajxxQfSc

I can't produce a log without crashing my server, and java using 100% of all 4 of my servers physical CPU Cores.

I'm using the file based system for the time being, until I am able to sort out this issue in some way.

**Comment by zml2008** [comment]
Make sure you're running the mysql 5.6+ (I'll try to work around this issue in a future version)
