### ISSUE TITLE
PEX mysql error

### ISSUE THREAD

**Issue by vitaxa** [PEXPlugins/PermissionsEx#1691]
Hi, i have problem with mysql config pex. 
permissions:
  basedir: plugins/PermissionsEx
  backend: sql
  backends:
    sql:
      uri: mysql://77.37.140.106/minecraft3
      user: hgfdh
      password: ************
      type: sql
  superperms: {}
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  informplayers:
    changes: false
multiserver:
  use-netevents: true
updater: true
alwaysUpdate: false

When i start server PEX shows error: ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'.

I tried to update mysq to 5.6 version. And tried to delete all pevious tables(permissions, permissions_entity, permissions_inheritance) from database.

Server version cauldron-1.7.10-1.1231.04.209

**Comment by zml2008** [comment]
I will look at improving backwards compatibility in the next PEX version
