### ISSUE TITLE
pex error 

### ISSUE THREAD

**Issue by tijmengraftdijk** [PEXPlugins/PermissionsEx#1696]
mij pex werkt niet meer.
maar ik wie wil een code met speler, proef-mod, mod, admin, hoofd-admin, mede-eigenaar, eigenaar, beheerder, youtuber, en VIP, MVP.
als je een website hebt geef die dan al staat er niet alles bij wat ik wil maakt niet uit!
en dit is mij pex code nu:
groups:
  Default:
    permissions:
    - modifyworld.*
    - essentails.msg
    - essentials.tpa
    - essentials.balance
    - essentials.pay
    - essentials.afk
    - essentials.list
    - essentials.realname
    - essentials.delhome
    - essentials.sethome
    - essentials.home
    - essentials.tpaccept
    - essentials.help
    - essentials.suicide
    - essentials.motd
    - essentials.spawn
    - multiverse.portal.access.Survival
    - essentials.rules
    - essentials.back
    - plotme.info
    - plotme.auto.1
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    options:
      rank: '1000'
      build: true
      prefix: '&7[&7Speler&7] &7'
      default: true
  VIP:
    inheritance:
    - Default
    permissions:
    - essentials.fly
    - plotme.info
    - plotme.auto.2
    - essentails.msg
    - essentials.tpa
    - essentials.balance
    - essentials.pay
    - essentials.afk
    - essentials.list
    - essentials.realname
    - essentials.spawn
    - essentials.delhome
    - essentials.sethome.multiple.3
    - essentials.home
    - essentials.tpaccept
    - essentials.help
    - essentials.suicide
    - essentials.motd
    - multiverse.portal.access.Survival
    - essentials.rules
    - essentials.back
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    options:
      build: true
      rank: '900'
      prefix: '&6[&6V.I.P.&6] &6'
  MVP:
    permissions:
    - essentials.fly
    - plotme.info
    - plotme.auto.2
    - essentails.msg
    - essentials.tpa
    - essentials.balance
    - essentials.pay
    - essentials.afk
    - essentials.list
    - essentials.realname
    - essentials.spawn
    - essentials.delhome
    - essentials.sethome.multiple.3
    - essentials.home
    - essentials.tpaccept
    - essentials.help
    - essentials.suicide
    - essentials.motd
    - multiverse.portal.access.Survival
    - essentials.rules
    - essentials.back
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    options:
      build: true
      rank: '800'
      prefix: '&a[M.V.P.] '
  ProefMod:
    permissions:
    - modifyworld.*
    - essentials.spawn
    - essentails.msg
    - essentials.tpa
    - essentials.kick.notify
    - essentials.ban.notify
    - essentials.balance
    - essentials.pay
    - essentials.afk
    - essentials.list
    - essentials.realname
    - essentials.delhome
    - essentials.sethome
    - essentials.home
    - essentials.tpaccept
    - essentials.help
    - essentials.gamemode
    - essentials.fly
    - essentials.ban
    - essentials.kick
    - essentials.clearinventory
    - essentials.vanish
    - essentials.jail
    - essentials.invsee
    - essentials.kill
    - essentials.mute
    - essentials.tempban
    - essentials.unban
    - essentials.unbanip
    - essentials.tpo
    - essentials.tp
    - essentials.tptoggle
    - coreprotect.*
    - coreprotect.inspect
    - coreprotect.lookup
    - coreprotect.restore
    - coreprotect.purge
    - coreprotect.reload
    - coreprotect.help
    - essentials.suicide
    - essentials.motd
    - essentials.back
    - worldedit.*
    - essentials.rules
    - multiverse.portal.access.Survival
    - plotme.*
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    options:
      build: true
      rank: '700'
      prefix: '&3[&3Proef-Mod&3] &3'
  Mod:
    inheritance:
    - ProefMod
    permissions:
    - modifyworld.*
    - essentials.spawn
    - essentails.msg
    - essentials.tpa
    - essentials.balance
    - essentials.pay
    - essentials.afk
    - essentials.list
    - essentials.realname
    - essentials.delhome
    - essentials.sethome
    - essentials.home.10
    - essentials.tpaccept
    - essentials.help
    - essentials.gamemode
    - essentials.fly
    - essentials.ban.offline
    - essentials.kick
    - essentials.banip
    - essentials.clearinventory
    - essentials.jail
    - essentials.invsee
    - essentials.kill
    - essentials.mute
    - essentials.tempban
    - essentials.unban
    - essentials.unbanip
    - essentials.tpo
    - essentials.tptoggle
    - coreprotect.*
    - coreprotect.inspect
    - coreprotect.lookup
    - coreprotect.rollback
    - coreprotect.restore
    - coreprotect.purge
    - coreprotect.reload
    - coreprotect.help
    - essentials.suicide
    - essentials.motd
    - essentials.back
    - multiverse.portal.access.Survival
    - worldedit.*
    - essentials.rules
    - essentials.kick.notify
    - essentials.ban.notify
    - plotme.*
    - essentials.spawn
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    options:
      build: true
      rank: '600'
      prefix: '&8[&5Mod&8] &5'
  Admin:
    permissions:
    - '*'
    options:
      build: true
      rank: '500'
      prefix: '&8[&9Admin&8] &9'
  HoofdAdmin:
    inheritance:
    - Admin
    options:
      build: true
      rank: '400'
      prefix: '&8[&2Hoofd-Admin&8] &2'
  Co-Owner:
    inheritance:
    - Admin
    options:
      build: true
      rank: '300'
      prefix: '&8[&cMede-Eigenaar&8] &c'
  Owner:
    permissions:
    - '*'
    inheritance:
    - Admin
    options:
      build: true
      rank: '200'
      prefix: '&8[&4Eigenaar&8]/&8[&fYou&4tube&8] &4'
  Beheerder:
    permissions:
    - '*'
    options:
      build: true
      rank: '100'
      prefix: '&8[&6Beheerder&8]

  Youtube:
    inheritance:
    - ProefMod
    permissions:
    - modifyworld.*
    - essentials.spawn
    - essentails.msg
    - essentials.tpa
    - essentials.balance
    - essentials.pay
    - essentials.afk
    - essentials.list
    - essentials.realname
    - essentials.delhome
    - essentials.sethome
    - essentials.home.10
    - essentials.tpaccept
    - essentials.help
    - essentials.gamemode
    - essentials.fly
    - essentials.ban.offline
    - essentials.kick
    - essentials.banip
    - essentials.clearinventory
    - essentials.jail
    - essentials.invsee
    - essentials.kill
    - essentials.mute
    - essentials.tempban
    - essentials.unban
    - essentials.unbanip
    - essentials.tpo
    - essentials.tptoggle
    - coreprotect.*
    - coreprotect.inspect
    - coreprotect.lookup
    - coreprotect.rollback
    - coreprotect.restore
    - coreprotect.purge
    - coreprotect.reload
    - coreprotect.help
    - essentials.suicide
    - essentials.motd
    - essentials.back
    - multiverse.portal.access.Survival
    - worldedit.*
    - essentials.rules
    - essentials.kick.notify
    - essentials.ban.notify
    - plotme.*
    - essentials.spawn
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    options:
      build: true
      rank: '600'
      prefix: '&8[&fYou$4tube&8] &4'
alles iemand een oplosing heeft zeg het dan!!
(alles je help krijg je nog iest)

**Comment by zml2008** [comment]
Not sure exactly what's wrong, but you may want to take a look at the quoting in the admin group.
