### ISSUE TITLE
Feature Request: Self-Promotion Node

### ISSUE THREAD

**Issue by jmromrell** [PEXPlugins/PermissionsEx#1706]
Please create a node:
permissions.user.selfpromote

that allows a user to promote themselves, or others, to a higher rank than they are.

This would be an extremely useful feature for admins who already are at the highest rank but who want to be able to demote themselves to lower ranks for regular play, only to later promote themselves again.

I want a set up like the following:

  player:
    options:
      default: true
      rank: '300'
    permissions:
      #basic permissions list here here

  playerx: #admins can use this to behave as a regular player but with the ability to promote themselves back
    options:
      rank: '200'
    permissions:
      - permissions.manage
      - permissions.user.promote
      - permissions.user.selfpromote

  admin:
    options:
      rank: '100'
    permissions:
      #admin permissions here

**Comment by zml2008** [comment]
Will probably only be integrated in Sponge, but it's on my list now.

**Comment by zml2008** [comment]
Because of the command permissions system used, this will be included once promotion commands are reimplemented.
