### ISSUE TITLE
Giving forge mod fake-player permissions won't work

### ISSUE THREAD

**Issue by Tsugaga** [PEXPlugins/PermissionsEx#1708]
In a recent BuildCraft update, quarries were given a blockBreakEvent so now they act as a player. Modifyworld prevents quarries from breaking blocks. I'm using the latest PermissionsEx. The fake-player name is [BuildCraft]. I've tried BuildCraft, [BuildCraft], [[BuildCraft]], '[BuildCraft]', and '[[BuildCraft]]'. Disabling Modifyworld allows the quarry to mine, so I know it's a permissions issue. [BuildCraft] is the correct fake-player name.

**Comment by Cronosus** [comment]
hello
similar problem on mod littlemaidmobx
server see it (i can see nick and uuid in usercache.json) and i can OP it, but i still can't grant any permissions to interact in inventory. :(
i welcome any help  :+1: 

thanks in advance

**Comment by BlackAce21** [comment]
I wrote a quick 10 second plugin that fixes this issue using the highest priority Event type in Bukkit to override all other plugins and allow the quarry to break all blocks. This will allow it to be used in all worlds and it will bypass all protections with this plugin so use it at your own risk. This will fix quarries and mining wells though until a better fix can be made. I could make it more modular if someone really needs it so you can add "fakeplayer" names a list to check against the events for other mods. I am not going to add anything more specific though so please don't ask =P I don't have the time honestly.

Hope it helps.

https://www.dropbox.com/s/2g3kued8420l6g4/FakePlayerFix.jar?dl=0

**Comment by PsychoLynx** [comment]
The above plugin works for the Quarry, but not the Builder when Modifyworld is installed. I found an alternative solution, namely manually editing the UUID of [BuildCraft] in the ops.json file to 77456a1f-b9f9-3f84-8863-ddef5b8e2209

**Comment by BlackAce21** [comment]
Update to this issue since it is still relevant, I spent time to write a more updated version of this plugin which is more inclusive and fixes the builder problem mentioned above, it works on fake players and can be used to give super bypass to normal players as well. This uses the player name so use it at your own risk! It will let all fake players bypass all protections.

https://www.dropbox.com/s/e5mbj6gxiysf05k/FakePlayerFix_2.0.jar?dl=0

**Comment by tenten8401** [comment]
Yo @zml2008 please fix this eventually

**Comment by zml2008** [comment]
Cauldron is no longer maintained and no longer available, so I don't have the tools to fix this issue even if it were a priority. The only supported way to use PEX with Forge mods is Sponge with PEX2.0 dev builds -- if you come across an issue there I'll take a look at it and can probably get it sorted.

**Comment by lipiglesias** [comment]
@BlackAce21 Dude, you rock, solved my problem in the easiest way ever.
Nice, simple, useful, plugin.

IT WORKS!

**Comment by Silverseppel** [comment]
can i use this fox for the autonomous activator

**Comment by BlackAce21** [comment]
it works for the autonomous activator yes, just use the fake player name
[CoFH]

**Comment by BlackAce21** [comment]
also as an update to this, the developer of the new Cauldron extension
(named Thermos) claims some optimizations for fake player handling of some
kind. I am not sure of the details nor have I tested this since we still
include my plugin in our standard server build but its worth looking into
if you don't know about it yet, there are a lot of performance tweaks
included as well

**Comment by Zendrex** [comment]
@BlackAce21 Would this work with thaumcraft golems? It seems world edit has a pissy fit with any mod that tries to left click or right click. (at least when using pex mysql)

Stack:

![image] https://i.gyazo.com/3c4206efc65894d68cc504d5ec7cbbf0.png

**Comment by BlackAce21** [comment]
yes, you just have to find the thaumcraft fakeplayer name assigned to
golems and add it to the list, I used to know it but I forget what it is. A
quick google search should find it or if your handy with a decompiler you
can pull it off the source code.

**Comment by Stuart74** [comment]
I know this is closed i am hoping BlackAce21  would read this and  be able to update the fixfakeplayer  for the latest version of Kcauldron 1614 I am prepared to pay for his time just not sure how else to get in contact with him

**Comment by BlackAce21** [comment]
https://www.dropbox.com/s/lldeof1q131727v/FakePlayerFix_2.1.jar?dl=0

This version is compiled against Spigot 1.7.10-R0.1 SnapshotBuild 1566 which I believe should be compatible with the latest thermos version for Forge 1614. If you have other questions about it, or need me to add/change functionality let me know. If this still doesn't work I might be able to help you sort out the problem, just let me know how I might contact you or you can email me at the1blackace21@gmail.com good luck

**Comment by Stuart74** [comment]
Thank you very much for taking the time on doing this it is appreciated i let you know how it goes.

**Comment by Stuart74** [comment]
Still having problems i have emailed you the information :+1:

**Comment by rohappy2421** [comment]
@BlackAce21 Hello I need you help Please

**Comment by BlackAce21** [comment]
What do you need?

**Comment by BlackAce21** [comment]
I should have done this a long time ago but I am doing it now. Further inquiries into my plugin that helps deal with this should be directed to the plugins github page at https://github.com/BlackAce21/FakePlayerFix I will no longer respond to messages made on this post as it is very dated and not even my git page. Please use the link or email me at the1blackace21@gmail.com Thank you for understanding.

**Comment by zml2008** [comment]
looks like they deleted their message -- but still, gonna lock this issue. PEX v1 is unsupported and that was quite the necrobump.
