### ISSUE TITLE
Server freezes on adding perms!

### ISSUE THREAD

**Issue by mikemy** [PEXPlugins/PermissionsEx#1746]
The server has been around quite a long time and the pex file is very large, There is no inheritance in the file! On adding a perm to a player, a group or even adding a player to a group the server freezes for up to 2 seconds . Any fixes?

**Comment by buddyte** [comment]
เปิดเซิฟไงครับ

**Comment by zml2008** [comment]
This issue is being combined into #1824 for further tracking. I have some ideas on how to improve the locking issues.
