### ISSUE TITLE
[Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 279.439ms!

### ISSUE THREAD

**Issue by NoHoPeLess** [PEXPlugins/PermissionsEx#1756]
Hello i have an issue:

[Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 279.439ms!

It spams the whole server log extremly...

We switch from PermissionsEx v1.19.6 to PermissionsEx v1.22.6

And before we use flatfile (its actually not working because we use bungee) and now we use mysql

Config: http://pastie.org/9778191

Permissions: http://pastebin.com/pMtaLZ6K

We dont use netevents

Any help would be nice

**Comment by jomo** [comment]
[Here is a crash log](https://gist.githubusercontent.com/jomo/370d5fa278673dc6dbc1/raw/74914c54d8f02639bc279b05a67f836477a50b8e/gistfile1), apparently it's hanging on a MySQL query?

**Comment by zml2008** [comment]
This issue is being combined into issue #1824 for future resolution
