### ISSUE TITLE
Server crash after many /pex reload

### ISSUE THREAD

**Issue by Hermiten** [PEXPlugins/PermissionsEx#1762]
Hi !

I have a problem with my server.
Some server have to execute all 15 minutes: /pex reload.
I use this because the documentation of NetEvent is really bad and don't work so when a player have a new permission in my server (It's a hub with many server. I use MySQL to sync PEX but I only execute pex command in my lobby, not all the server)

An another dev found this problem and made this:
https://github.com/fubira/PermissionsEx/commit/bea4e71ac4e4203d792b4c47417429a34c446676

I have a report:
http://pastebin.com/hciigUDg

Thanks in advance !
I use PEX 1.22.x (1, 2 ... have the same problem) and spigot patched to support 1.8 player. But same problem with previous version of spigot for 1.7.x only !

**Comment by zml2008** [comment]
I'll take a look at the issue mentioned in that commit you provided! Thanks for linking to actual code that resolves the issue (even tho the dev acknowledged it as a workaround)
