### ISSUE TITLE
[Suggestion] Scale PEX, performance boost for large server

### ISSUE THREAD

**Issue by Minecraftly** [PEXPlugins/PermissionsEx#1774]
I've been using PEX for 3 years on many large servers, and I've always been preferring flatfile over MySQL. It is so simple and easy to use. However, there's a performance issue with PEX when both of these things happen:

- When there are lots of players currently playing. (Around 150 to 300)
- When there are lots of player entries inside permissions.yml file (Usually 15,000 or more)

The server starts to slow down at that time, and when there are PEX command being excecuted, either automatic (vote rewards) or by admin, the server pauses for about 0.5 to 1.5 second. It is mostly due to lots of entries inside the permissions.yml file.

My suggestion is to have an option for seperated UUID.yml file for each player in the uuid folder. This idea is not new, it's being used by Essentials and it can handle millions of players just fine. It might not matter for small server, but for big server, it is a great thing and will surely boost server performance.

Thank you for reading this.

**Comment by zml2008** [comment]
Hopefully some of the performance issues should be resolved with recent commits. Look at #1824 to track the status of this
