### ISSUE TITLE
mysql manual creation

### ISSUE THREAD

**Issue by LukeXF** [PEXPlugins/PermissionsEx#1803]
Hey there, I need to generate the PermissionsEx mySQL structure manually. The feedback messages tell me to look for mysql.mysql but there is no mysql file there ready for me to import into my database.

I know mysql well and I just need to get the code inside the mysql file, if anyone has it so I can structure my database and tables it would be much appreciated.

**Comment by LukeXF** [comment]
Yes Thanks!

**Comment by Stormbow** [comment]
Excellent.  :dart:
