### ISSUE TITLE
Permissions Ex Error On Console.

### ISSUE THREAD

**Issue by JJLM1** [PEXPlugins/PermissionsEx#1808]
### Description ###

Server won't load PermissionsEx

Console:

01.01 01:18:06 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/OkMdeg. Full error:
01.01 01:18:06 [Server] INFO java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
01.01 01:18:06 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.&lt;init&gt;(RegExpMatcher.java:17)
01.01 01:18:06 [Server] INFO at ru.tehkode.permissions.PermissionManager.&lt;init&gt;(PermissionManager.java:58)
01.01 01:18:06 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
01.01 01:18:06 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
01.01 01:18:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
01.01 01:18:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
01.01 01:18:06 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
01.01 01:18:06 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
01.01 01:18:06 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
01.01 01:18:06 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
01.01 01:18:06 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
01.01 01:18:06 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
01.01 01:18:06 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
01.01 01:18:06 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by Skin0x** [comment]
Same problem !! :x

**Comment by Stormbow** [comment]
Don't use PermissionsEx 1.23, which is //only// for 1.8 bukkit servers, on your 1.7.x server.
