### ISSUE TITLE
Can someone help? I get this error when loading PEX on 1.7.9 

### ISSUE THREAD

**Issue by epicdemon99** [PEXPlugins/PermissionsEx#1810]
01.01 10:30:51 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
01.01 10:30:51 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436)
01.01 10:30:51 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182)
01.01 10:30:51 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282)
01.01 10:30:51 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326)
01.01 10:30:51 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352)
01.01 10:30:51 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:389)
01.01 10:30:51 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:455)
01.01 10:30:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
01.01 10:30:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
01.01 10:30:51 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
01.01 10:30:51 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
01.01 10:30:51 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
01.01 10:30:51 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
01.01 10:30:51 [Server] INFO java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;

**Comment by Stormbow** [comment]
Don't use PermissionsEx 1.23, which is //only// for 1.8 bukkit servers, on your 1.7.x server.
