### ISSUE TITLE
PEX error

### ISSUE THREAD

**Issue by Fragziz** [PEXPlugins/PermissionsEx#1811]
ERROR]: [PermissionsEx] Error occurred with PermissionsEx!
Edit: I see a few plugins are disabled that I didn't notice. Probably outdated Ill remove them and see if that helps it

Fk Im stupid I have GM running too oops didn't notice until in made the folder again...

[Is available here](https://gist.github.com/4e707bcbef3aa82c281a)

**Comment by Fragziz** [comment]
I downgraded one version of pex and now I can you pex commands but none of the ranks suffixs' are showing up now would I have to redo the permission files I am reading that it has changed

**Comment by Fragziz** [comment]
Okay so what I found out is that I had to down grade my PEX version as well as remove a few plugins that were not compatible with my version.  It runs fine on PEX v1.22.6 but on on 1.23 I must have to update my spigot for it to work Sorry if I wasted your time.

**Comment by Stormbow** [comment]
No sweat.  :)  I'm actually glad you are smart enough to see that yourself.  (Many here are not.)
