### ISSUE TITLE
PermissionEx for Craftbukkit 1.7.2 - BUG

### ISSUE THREAD

**Issue by Itay080** [PEXPlugins/PermissionsEx#1815]
Hello, I am using PermissionsEx for craftbukkit 1.7.2, and everytime I try to /clean my inventory, it says that I don't have a permission, OP doesn't help, adding permission doesn't help..
I'd be happy to get some help.
I can list my plugins if needed.

**Comment by Stormbow** [comment]
Which plugin is supposed to give you a "/clean" command?

If you are refering to "/clear inventory" (which is a known as a [vanilla permission](http://wiki.bukkit.org/Vanilla_permissions)), the permission node is **bukkit.command.clear**

**Comment by Itay080** [comment]
Essentials is supposed to, I guess.
But it's PermissionsEX fault, because even when I am OP, I can't use /clear.

**Comment by zml2008** [comment]
run /pex toggle debug, then check which permissions are actually checked -- they are printed to the console when you run the command.

**Comment by Itay080** [comment]
04.01 07:36:42 [Server] INFO User AgentItay checked for permission 'ironelevators.use', regex-matched a value of true from ironelevators.use (CACHE MISS)
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.fly.safelogin', regex-matched a value of true from cache.
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.fly.safelogin', regex-matched a value of true from essentials.* (CACHE MISS)
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.mail', regex-matched a value of true from cache.
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.mail', regex-matched a value of true from essentials.* (CACHE MISS)
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.motd', regex-matched a value of true from cache.
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.motd', regex-matched a value of true from essentials.* (CACHE MISS)
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.sleepingignored', regex-matched a value of true from cache.
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'essentials.sleepingignored', regex-matched a value of true from essentials.* (CACHE MISS)
04.01 07:36:41 [Server] INFO User AgentItay checked for permission 'vault.update', regex-matched a value of true from vault.update (CACHE MISS)
04.01 07:36:41 [Multicraft] AgentItay ran command Message of the Day

**Comment by Stormbow** [comment]
Ok, you need the permission node **essentials.clearinventory** to use the command **/clearinventory username** (alias **/ci username**, **/clean username**, and **/clearinvent username**) according to the [Essentials Command Reference page](http://wiki.ess3.net/wiki/Command_Reference).

**Comment by Itay080** [comment]
Doesn't work.

**Comment by Stormbow** [comment]
Have you actually downloaded the Essentials package and extracted all of the files to your server plugins folder?

Post 3 [Pastebin](http://pastebin.com) links for:
• Your full server startup log.
• Your permissions.yml file.
• Your Essentials\config.yml file.

**Comment by Stormbow** [comment]
[11:26:25 INFO]: Stormbow issued server command: /clear stormbow
[11:26:25 INFO]: [PermissionsEx] User Stormbow checked for permission 'bukkit.command.clear', regex-matched a value of true from cache.
[11:26:25 INFO]: Stormbow: Cleared the inventory of Stormbow, removing 2304 items

**Comment by Itay080** [comment]
Full server startup log: http://pastebin.com/kaCQ2SpH
permissions.yml file: http://pastebin.com/YTPEA2Yn
Where can I find the full users list? Although, I don't think it's needed as the server is closed to the public yet and I only got 4 players.
Essentials/config.yml file: http://pastebin.com/AD7ty254
No, I only extracted the files: "Essentials, Essentials Chat and Essentials Spawn".
Somehow, the /clear CMD works now.
This is the debug log:

05.01 09:03:08 [Server] INFO AgentItay: Cleared the inventory of AgentItay, removing 0 items
05.01 09:03:08 [Server] INFO User AgentItay checked for permission 'bukkit.broadcast.admin', regex-matched a value of true from cache.
05.01 09:03:08 [Server] INFO User AgentItay checked for permission 'bukkit.command.clear', regex-matched a value of true from cache.

Maybe you can tell me if you know what was the problem so I can take care of it if it appears once again?

**Comment by Stormbow** [comment]
It's probably just a matter of you not having the correct permissions initially, and the permissions.yml that was being used by the server (in memory) hadn't updated after you changed the groups to add the permission.

Be sure to follow [this example(http://pastebin.com/8ZSHxauG) as you are setting up your permissions.yml file.

**Comment by Itay080** [comment]
Alright, thanks for your help.
Also,  if I don't have the plugin modifyworld, and juft permissiosnsEX, can I remove the modifyworld's permissions?

**Comment by Stormbow** [comment]
Yes, you can remove those if you're not using it.  (It doesn't hurt anything to leave it in there, at the moment.  Just remember, every unnecessary line and user in the permissions.yml will add up over time and can have an impact on the server months or years later depending on how many people visit the server even one time.)
