### ISSUE TITLE
Zaje*****

### ISSUE THREAD

**Issue by razors132** [PEXPlugins/PermissionsEx#1817]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/b80cd8711d526e4e6c31)

**Comment by Stormbow** [comment]
PermissionsEx 1.23 is not for 1.7.2 servers.  You will need to [download PEX 1.21.3](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/30-permissions-ex-v1-21-3/).
