### ISSUE TITLE
PermissionsEx Error

### ISSUE THREAD

**Issue by fallwithus25** [PEXPlugins/PermissionsEx#1818]
### Description ###

PermissionsEx is not working it has an error i dont know what it is

### Detailed Information ###

[Is available here](https://gist.github.com/d7e028e0a7f7beb171b0)

**Comment by Stormbow** [comment]
PermissionsEx 1.23 is not for 1.7.10 servers.  You will need to [download v1.22.6](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/38-permissions-ex-v1-22-6/).
