### ISSUE TITLE
I don't know how to make a title for my ticket.  -.-; ] Edit by Stormbow [

### ISSUE THREAD

**Issue by nerv23** [PEXPlugins/PermissionsEx#1819]
### Description ###

 java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder; 	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17) 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58) 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164) 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:442) 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:376) 	at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:344) 	at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:319) 	at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:275) 	at net.minecraft.server.v1_7_R2.Dedicat

### Detailed Information ###

[Is available here](https://gist.github.com/0733c5d8960a6152d590)

**Comment by Stormbow** [comment]
You are trying to use PEX 1.23 for a 1.7.5 server.  Download a different version of PEX and read the release notes to make sure it is useable on a 1.7.5 server.  (1.23 tells you that 1.23 is only for 1.8 bukkit servers, which includes Spigot.)
