### ISSUE TITLE
Pex Error

### ISSUE THREAD

**Issue by henderry2019** [PEXPlugins/PermissionsEx#1821]
### Description ###

Whenever I load up my server (using PEX), PEX does not work. I have not edited any of the files, only downloaded the plugin and ran it in my server.
### Detailed Information ###
The error that I get is:

[Is available here](https://gist.github.com/043be26e50426fd32339)
![bandicam 2015-01-04 14-00-50-994](https://cloud.githubusercontent.com/assets/10392434/5607278/25cde89e-941a-11e4-8a19-cccf7d3c396f.jpg)

**Comment by Stormbow** [comment]
PermissionsEx 1.23 is not for your server version.  Download a different version of PEX that is for your 1.7.x server.  (Read the release notes.)
