### ISSUE TITLE
Unexpectedly high delays when querying permissions

### ISSUE THREAD

**Issue by zml2008** [PEXPlugins/PermissionsEx#1824]
This is the source of the Essentials lag notices.
Caused by excessive lock contention in backends

**Comment by zml2008** [comment]
The last commit in master (mentioning this issue) should help with performance. Testing would be appreciated.

**Comment by mibby** [comment]
Sweet! I always see the Essentials lag notice on my large server with ~100,000 grouped users. Since the jenkins is down, I suppose I shall compile the source to test. :)

**Comment by mibby** [comment]
For what it's worth, I still seem to be getting the slow permissions message from Essentials with the source compiled.

```
	Line 461: [08:09:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 27.848ms!
	Line 551: [08:13:51] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 68.259ms!
	Line 613: [08:17:01] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 43.603ms!
	Line 892: [08:30:31] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 26.347ms!
	Line 1018: [08:36:08] [Async Chat Thread - #1/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 105.626ms!
	Line 2154: [09:20:51] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 78.028ms!
	Line 2862: [09:49:19] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.477ms!
	Line 3311: [10:01:24] [Async Chat Thread - #5/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 138.142ms!
	Line 3334: [10:03:54] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 46.521ms!
	Line 3486: [10:10:39] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.065ms!
	Line 5013: [11:02:19] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 68.595ms!
	Line 5158: [11:09:31] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 224.558ms!
	Line 5191: [11:10:53] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 27.101ms!
	Line 6121: [11:50:12] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.274ms!
	Line 6135: [11:50:42] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 55.866ms!
	Line 6778: [12:12:26] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 123.99ms!
	Line 6915: [12:18:16] [Async Chat Thread - #19/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 319.025ms!
	Line 7275: [12:32:16] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 41.94ms!
	Line 8708: [13:13:44] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.072ms!
	Line 10168: [14:32:20] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 42.656ms!
	Line 10578: [14:45:47] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 52.664ms!
	Line 10666: [14:48:15] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 26.141ms!
	Line 10693: [14:49:25] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 28.869ms!
	Line 10727: [14:51:00] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 92.643ms!
	Line 10971: [14:59:34] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.555ms!
	Line 11083: [15:05:09] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 58.632ms!
	Line 11170: [15:08:46] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 44.594ms!
	Line 12340: [16:17:56] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 402.451ms!
	Line 13547: [17:24:38] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.221ms!
	Line 14598: [17:55:48] [Async Chat Thread - #62/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 43.553ms!
	Line 14746: [17:59:53] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 136.879ms!
	Line 14780: [18:00:19] [Async Chat Thread - #62/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 160.648ms!
	Line 15340: [18:14:18] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 67.344ms!
	Line 15711: [18:26:50] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 118.086ms!
	Line 16872: [19:03:11] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 83.141ms!
	Line 16935: [19:04:49] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 30.287ms!
	Line 17474: [19:18:13] [Async Chat Thread - #77/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 102.608ms!
	Line 17978: [19:31:28] [Async Chat Thread - #78/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 101.556ms!
	Line 18186: [19:37:24] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.1ms!
	Line 18582: [19:48:10] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.718ms!
	Line 18756: [19:53:38] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 67.996ms!
```

**Comment by zml2008** [comment]
fuck. any chance you could get attach warmroast to your server, let it
run for a few hours, and give me the report from it? that'd help most to
track this down

**Comment by mibby** [comment]
I'm not sure how effective it'll be since I run two servers and BungeeCord on the same node. I also have my server automatically restart after every so many hours, so not sure if it would affect the readings. In addition, I'd have to install java JDK since I usually compile locally and only require JRE on the server. But, if it is necessary, I can look into setting it up tomorrow.

**Comment by zml2008** [comment]
It'd be great if you could try -- a profiler is really the only way to
get concrete data on live servers (which makes fixing performance issues
more than a stab in the dark)

**Comment by AwaaX** [comment]
I have a freeze too when I type /pex and the Essentials lag notice alert for permissionex

**Comment by orkun1675** [comment]
You need to login via SSH with the user that you are running the server on, in order for Warm Roast to properly function.

**Comment by mibby** [comment]
Heh, of course. I've been operating a linux server for years, no need to tell me. I run my server as root user and ran WarmRoast as root user via ssh.

**Comment by orkun1675** [comment]
I got the same error, and solved it like this. Just saying.

**Comment by TheOnlyRealTGS** [comment]
Getting this too:
_[16:29:33 INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 64.631ms!
_

**Comment by LemADEC** [comment]
Is this still present? is there an simple way to reproduce it?

**Comment by TheOnlyRealTGS** [comment]
Have a big perm file, and many perm checks i guess?

**Comment by LemADEC** [comment]
How groups per players? how many perms to go through? how many players registered?
Using SQL or flat file?

**Comment by TheOnlyRealTGS** [comment]
Flat file, 6.9k lines, around 27 groups in total, 1 ladder & can't say how many players.

**Comment by mibby** [comment]
Here's my statistics for whatever it is worth, all on PermissionsEx 1.23.1.
* Flat file
* 46,000 lines
* 26 groups
* 5 ladders
* Can't exactly say how many users, but quite a bit. Same with the number of permissions in each group and some users having individual perm nodes.

Random response times I pulled from the console within the last 5 minutes.
```
Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 406.935ms!
Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 282.826ms!
Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 26.342ms!
```

**Comment by Stormbow** [comment]
Mibby desperately needs to run the cleanup command on the groups.  With 46,000 lines, there must be thousands and thousands of users listed which are never coming back to the server and can be removed.

But that's just my 2 cents.

**Comment by mibby** [comment]
That's not entirely true. I operate a fairly large network. 

Newly joined users are not grouped by default. Those that join have to pass a quiz to be ranked as a member - leaving a majority of users who would've joined to otherwise leave shortly after not spend the effort to get grouped in the first place. About 2/3 of my grouped users are players who have achieved builder ranks or purchased a donation rank. The rest would be users with a staff position or grouped as a member. If I purged members whom have not been on in the last say 3 months, they would be upset they have to take the quiz again if/when they come back, plus they would be outside the quiz zone.

**Comment by Stormbow** [comment]
Actually, every single user that joins a PEX-using server is added to the user list with no group specified.  This is because if the server owner ever changed which group is "default: true", there would be hundreds or thousands of users to manually move from the old default group to the new.  Every single user still has an entry for personal permissions, prefixes, and suffixes.

There's no way you have 46,000 lines of permissions.  If you do, you're definitely doing something wrong insofar as inheritance is concerned.  (i.e., not using it at all)

And, reminder, selling in-game benefits (donor ranks and items) that affect gameplay on a minecraft server is [not allowed](https://mojang.com/2014/06/lets-talk-server-monetisation/).

**Comment by mibby** [comment]
That is not true. If this is set in the config, users are not added to the permissions file unless they are grouped outside the 'default' group. Even with player logging enabled.

```
  createUserRecords: false
```

https://github.com/PEXPlugins/PermissionsEx/commit/6e361c364c6525815f2b7383a1e7cfc5e7ab6fdb
https://github.com/PEXPlugins/PermissionsEx/issues/1639

As I have said, I have been running my server for more than 4 years. I do know what I am doing and don't need someone telling me otherwise that I am "doing something wrong insofar as inheritance is concerned". I am utilizing permission inheritance correctly and yes, the majority of the 46,000 lines are grouped users. 

I suggest you do a little research about PermissionsEx before providing advice to others. And yes, I am aware of the EULA. My network is 100% EULA compliant.

**Comment by LemADEC** [comment]
I've a 1MB ~53k lines permission flat file spanning 5 ladders, 700+ lines of permissions definition, 7000+ users.
Due to another issue in pex with ladders, we need all players to be logged in the permission file.

Does anyone have same issue with the SQL backend?

**Comment by AwaaX** [comment]
Is the problem in advance? : /

**Comment by TheOnlyRealTGS** [comment]
This is beginning to spam my console a lot now.

**Comment by smmalloy** [comment]
Hey Any news on this issue? I am having this!! 

Server] INFO Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 1,775.711ms!

Using MySQL backend.

**Comment by zml2008** [comment]
I'm not sure there's anything else I can do to resolve this. I'm going to close this now -- I will only accept performance issues on the new Sponge architecture.

**Comment by mibby** [comment]
@zml2008 I've compiled the 1.23.x branch to test the reverted commit. Essentials still reports erratic lag from PermissionsEx. Is there any further tweaking that can be done or has development shifted entirely to Sponge from here on out?

```
	Line 1262: [13:30:43] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 35.18ms!
	Line 1787: [13:48:40] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 244.489ms!
	Line 5437: [16:36:33] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.598ms!
	Line 6964: [17:26:53] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 26.889ms!
	Line 9063: [18:40:15] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 78.186ms!
	Line 9158: [18:45:41] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 25.229ms!
	Line 11348: [19:57:18] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 41.074ms!
	Line 11483: [20:00:41] [Server thread/INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 36.721ms!
```

**Comment by TNTUP** [comment]
Still occuring on my end... s

15:28:43 Essentials: Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 605.641ms!

using 1.23.2 version on spigot 1.8.7-r0.1

**Comment by Samistine** [comment]
:(
