### ISSUE TITLE
[PermissionsEx] Error 

### ISSUE THREAD

**Issue by iraden** [PEXPlugins/PermissionsEx#1825]
### Description ###

10:57:49 java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
10:57:49 	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
10:57:49 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
10:57:49 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
10:57:49 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
10:57:49 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
10:57:49 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
10:57:49 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
10:57:49 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
10:57:49 	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
10:57:49 	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
10:57:49 	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
10:57:49 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
10:57:49 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)

**Comment by Stormbow** [comment]
Don't use PEX 1.23 on 1.7.x servers.
