### ISSUE TITLE
PermissionsEx Error

### ISSUE THREAD

**Issue by LucaXD8** [PEXPlugins/PermissionsEx#1826]
net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
05.01 13:08:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
05.01 13:08:16 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
05.01 13:08:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
05.01 13:08:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
05.01 13:08:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
05.01 13:08:16 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
05.01 13:08:16 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
05.01 13:08:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
05.01 13:08:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
05.01 13:08:16 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
05.01 13:08:16 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
05.01 13:08:16 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
05.01 13:08:16 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
05.01 13:08:16 [Server] INFO java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
05.01 13:08:16 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/wIi1RA. Full error:

**Comment by Stormbow** [comment]
Don't use PEX 1.23 on 1.7.x servers.
