### ISSUE TITLE
Ditch NetEvents

### ISSUE THREAD

**Issue by BeastsMC** [PEXPlugins/PermissionsEx#1829]
Please, for the love of god, ditch netevents. It's a bad, broken plugin. It works 10% of the time and can rarely even establish a connection to the other servers. Please, just use Bukkit's builtin plugin message channel system and add builtin support for permission syncing in PEX. The current method is old, buggy, and broken.

**Comment by zml2008** [comment]
Uh, bukkit's plugin channel system doesn't work across servers, and bungee's hack to forward plugin messages only works when players are connected to all servers (and is specific to bungee -- some of our users use lillypad)
In addition, you may want to try a potentially improved development build of NetEvents from https://drone.io/github.com/zml2008/netevents/files/target/netevents-1.1-SNAPSHOT.jar to check for improvements.

If you still don't like netevents, don't use it and just cron a /pex reload every 5 minutes (as of 1.23.1 dev builds).

**Comment by BeastsMC** [comment]
Alright, I guess I'll go with cron and a newer build. By the way your build site is hard to locate and seems to be currently offline.

**Comment by zml2008** [comment]
Yeah, we don't normally recommend using dev builds. However, for now the current PEX dev build is available at http://get.your.minions.at.aoeu.xyz/PermissionsEx-1.23.1-SNAPSHOT.jar
