### ISSUE TITLE
NoSuchMethodError (?)

### ISSUE THREAD

**Issue by SaintFlareGhost** [PEXPlugins/PermissionsEx#1832]
### Description ###
Everytime i open my server i get the same error:
http://gyazo.com/84dc5ddd61a3d14ce0e1b803830cd038
I've tried re-installing PEX and still not working...
please help

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/3706227476dee4b95a88)

**Comment by Stormbow** [comment]
PEX 1.23 is not for 1.7.10 servers.  Download a different version; read the release notes.
