### ISSUE TITLE
Issue D:

### ISSUE THREAD

**Issue by xXTheBetXx** [PEXPlugins/PermissionsEx#1833]
### Description ###

Don't load PEX
### Detailed Information ###

[Is available here](https://gist.github.com/bc8a552c3daf6e54dc31)

**Comment by Stormbow** [comment]
PEX 1.23 is not for 1.7.10 servers.  Download a different version; read the release notes.

**Comment by xXTheBetXx** [comment]
1.7.10 -.- It's the Spigot Update for 1.8

**Comment by xXTheBetXx** [comment]
The Changelog says that was tested with Spigot Update for 1.8 or something like this.

**Comment by Stormbow** [comment]
Your [Detailed Information]9https://gist.github.com/bc8a552c3daf6e54dc31} says you are running 1.7.10, which is not compatible with PEX 1.23.

**Comment by xXTheBetXx** [comment]
But it's 1.8

**Comment by xXTheBetXx** [comment]
Vault works correctly and it's for 1.8
Vault 1.5.0 is for ONLY 1.8

**Comment by xXTheBetXx** [comment]
And in older versions of PEX shows me the same error
:/

**Comment by Stormbow** [comment]
As far as I know, the Detailed Information link doesn't display false server version info.
You'll have to wait for zml to look at this ticket.

**Comment by Stormbow** [comment]
It should be noted you're haven't posted any "good" information about the problem you're experiencing either.  "Don't load PEX" doesn't tell anyone absolutely anything.

**Comment by xXTheBetXx** [comment]
But I cannot stop loading the console, when finish loading server, I cannot go too many up to read the message again. And!!!! THAT ISN'T THE WRONG VERSION BECAUSE with old versions shows me the same :P

**Comment by Stormbow** [comment]
And you still have not posted any error messages.

**Comment by Stormbow** [comment]
The ONLY thing you should be adding to this ticket right now is what I told you is "good" information.

**Comment by Stormbow** [comment]
Not arguments about how you did it right.  Obviously, you have not.

**Comment by xXTheBetXx** [comment]
OK, let's try again!!!!! I'll stop the console and I will post here a photo of the error message. You want?

**Comment by xXTheBetXx** [comment]
With Lightshot I can stop the screen and take a photo of a selected region

**Comment by xXTheBetXx** [comment]
I will upload the photo, and I will post here the link

**Comment by xXTheBetXx** [comment]
Ok?

**Comment by xXTheBetXx** [comment]
I'll try with the older version than that.

**Comment by xXTheBetXx** [comment]
Hey, you'll stay here for an hour aprox.? I have to go. I'll be here for an hour. Goodbye

**Comment by Stormbow** [comment]
Waiting for zml to look at this ticket.

**Comment by zml2008** [comment]
You aren't using the actual 1.8 server, you're using the 1.8 protocol hack.
