### ISSUE TITLE
Faild to Load on Dragonet/Glowstone server

### ISSUE THREAD

**Issue by DefinitlyEvil** [PEXPlugins/PermissionsEx#1834]
### Description ###
I am using a Bukkit API implementation called Dragonet which is based on Glowstone. 

### Detailed Information ###

[Is available here](https://gist.github.com/cec2bb208871fc8194f5)
.

**Comment by zml2008** [comment]
Your minecraft server did not update its guava, so you should be using PEX 1.22.6.

**Comment by DefinitlyEvil** [comment]
@zml2008 Thanks, I got it! :)
