### ISSUE TITLE
PEX Prefix error?

### ISSUE THREAD

**Issue by Jdawgs88** [PEXPlugins/PermissionsEx#1835]
When i use pex i try to put a prefix on a group but it didn't work i tried all groups but it still didn't put the prefix on for the group i also tried changing my user prefix it still doesn't apply the prefix, so i please need help! Thanks.

**Comment by Stormbow** [comment]
Be sure you are following the [Prefix/Suffix Guide](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-help-my-prefix-suffix-doesnt-work-111-1-1/?unread) on how to use those.
