### ISSUE TITLE
API for groups?

### ISSUE THREAD

**Issue by Kyle1264x** [PEXPlugins/PermissionsEx#1838]
Im making a plugin now, for Pex All groups, Like a way to add a permission to every group given in a list, Im deciding against inheritance for the record, something conflicts in my server with it. But is there something a part of the API for groups, Sort of like <group name>.addPermission("permission"); is there anythning like that?

**Comment by zml2008** [comment]
with a PermissionGroup object, the addPermission method exists. You can get all registered groups through the PermissionManager as well.
