### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by KeeganFourie** [PEXPlugins/PermissionsEx#1839]
### Description ###

[Insert description of issue here]
### Detailed Information ###

09.01 23:36:44 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/7Ucxww. Full error:
09.01 23:36:43 [Server] INFO Checking for Updates ... 
09.01 23:36:43 [Server] Startup Done (3.719s)! For help, type "help" or "?"
09.01 23:36:43 [Server] INFO ^
09.01 23:36:43 [Server] INFO .* Admin: options: prefix: '&amp;0(&amp;4Admin&amp;0 ... 
09.01 23:36:43 [Server] INFO in "&lt;reader&gt;", line 8, column 11:
09.01 23:36:43 [Server] INFO could not found expected ':'
09.01 23:36:43 [Server] INFO ^
09.01 23:36:43 [Server] INFO modifyworld
09.01 23:36:43 [Server] INFO in "&lt;reader&gt;", line 7, column 1:
09.01 23:36:43 [Server] WARN Server permissions file permissions.yml is not valid YAML: while scanning a simple key
09.01 23:36:42 [Server] INFO [Vault][Permission] PermissionsEx hooked.
09.01 23:36:42 [Server] INFO WEPIF: Using the Bukkit Permissions API.
09.01 23:36:42 [Server] INFO WEPIF: Using the Bukkit Permissions API.
09.01 23:36:42 [Server] INFO Disabling PermissionsEx v1.23
09.01 23:36:42 [Server] INFO Enabling PermissionsEx v1.23

[Is available here](https://gist.github.com/558abf377434d12934ac)

**Comment by Stormbow** [comment]
You're missing a colon at the end of the prefix for your group named "Admin", I do believe.  Post a pastebin link to your permissions.yml file and I can confirm that guess.

**Comment by zml2008** [comment]
The permissions.yml mentioned in this error is the Bukkit server permissions.yml, not the PEX permissions.yml. We only support configuration through PEX.
