### ISSUE TITLE
Load On Startup Failure

### ISSUE THREAD

**Issue by ChaoticMC** [PEXPlugins/PermissionsEx#1844]
8:51:38 AM [ERROR] [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/4jYhqA. Full error:
8:51:38 AM java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
8:51:38 AM at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
8:51:38 AM at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
8:51:38 AM at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
8:51:38 AM at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
8:51:38 AM at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
8:51:38 AM at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
8:51:38 AM at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
8:51:38 AM at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
8:51:38 AM at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
8:51:38 AM at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
8:51:38 AM at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
8:51:38 AM at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
8:51:38 AM at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
8:51:38 AM at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by zml2008** [comment]
I always like people who can read release notes. Shame you aren't one
of them.
