### ISSUE TITLE
pex crush /maclarenss /my database mysql and crush log

### ISSUE THREAD

**Issue by maclarens** [PEXPlugins/PermissionsEx#1847]
-permissionSex base mysql
-------------------------

-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u1
-- http://www.phpmyadmin.net
--
-- name: localhost
-- Creation time: Янв 13 2015 г., 19:55
-- Version of the server: 5.5.40
-- Version  PHP: 5.4.36-0+deb7u1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `mine001`
--

-- --------------------------------------------------------

--
-- Structure of the table `permissions`
--

CREATE TABLE IF NOT EXISTS `permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `type` tinyint(1) NOT NULL,
  `permission` text NOT NULL,
  `world` varchar(50) NOT NULL,
  `value` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user` (`name`,`type`),
  KEY `world` (`world`,`name`,`type`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=123 ;

--
-- Dump of data of the table `permissions`
--

INSERT INTO `permissions` (`id`, `name`, `type`, `permission`, `world`, `value`) VALUES
(1, 'system', 2, 'schema_version', '', '2'),
(2, 'default', 0, 'essentials.afk.auto', '', ''),
(3, 'default', 0, 'default', '', 'true'),
(4, 'default', 0, 'essentials.afk', '', ''),
(5, 'default', 0, 'essentials.me', '', ''),
(6, 'default', 0, 'essentials.msg', '', ''),
(7, 'default', 0, 'essentials.clearinventory', '', ''),
(8, 'default', 0, 'essentials.home', '', ''),
(9, 'default', 0, 'essentials.sethome', '', ''),
(10, 'default', 0, 'essentials.spawn', '', ''),
(11, 'default', 0, 'essentials.tpa', '', ''),
(12, 'default', 0, 'essentials.tpaccept', '', ''),
(13, 'default', 0, 'essentials.tpdeny', '', ''),
(14, 'default', 0, 'essentials.warp', '', ''),
(15, 'default', 0, 'essentials.warp.list', '', ''),
(16, 'default', 0, 'essentials.geoip.show', '', ''),
(17, 'default', 0, 'essentials.heal', '', ''),
(18, 'default', 0, 'essentials.recipe', '', ''),
(20, 'default', 0, 'coreprotect.inspect', '', ''),
(21, 'default', 0, 'essentials.kit', '', ''),
(22, 'default', 0, 'essentials.ban.notify', '', ''),
(23, 'default', 0, 'essentials.kick.notify', '', ''),
(24, 'default', 0, 'essentials.mute.notify', '', ''),
(25, 'default', 0, 'essentials.delhome', '', ''),
(26, 'default', 0, 'essentials.rules', '', ''),
(27, 'default', 0, 'essentials.signs.create.balance', '', ''),
(28, 'default', 0, 'essentials.signs.break.balance', '', ''),
(29, 'default', 0, 'essentials.signs.use.balance', '', ''),
(30, 'default', 0, 'essentials.signs.use.warp', '', ''),
(31, 'default', 0, 'essentials.signs.use.buy', '', ''),
(32, 'default', 0, 'essentials.signs.use.sell', '', ''),
(33, 'default', 0, 'essentials.signs.use.disposal', '', ''),
(34, 'default', 0, 'essentials.signs.create.disposal', '', ''),
(35, 'default', 0, 'essentials.signs.break.disposal', '', ''),
(36, 'default', 0, 'lokipost.annoyme', '', ''),
(37, 'default', 0, 'simpleclans.mod.verify', '', ''),
(38, 'admin', 0, '*', '', ''),
(74, '920c79d8-a1ca-3c23-8b42-dadfe7a301f4', 1, 'last-logout-time', '', '1419450569'),
(80, 'default', 0, 'essentials.help', '', ''),
(81, 'default', 0, 'random.teleport', '', ''),
(82, 'baryga', 0, 'essentials.sell', '', ''),
(83, 'baryga', 0, 'essentials.worth', '', ''),
(84, 'baryga', 0, 'essentials.kits.baryga', '', ''),
(85, 'vip', 0, 'essentials.kits.vip', '', ''),
(86, 'svip', 0, 'essentials.kits.svip', '', ''),
(87, 'baryga', 0, 'essentials.sethome.multiple.baryga', '', ''),
(88, 'baryga', 0, 'essentials.home.others', '', ''),
(89, 'baryga', 0, 'BlockDisguise.disguise', '', ''),
(90, 'baryga', 0, 'repairchest.create', '', ''),
(91, 'baryga', 0, 'repairchest.use', '', ''),
(92, 'baryga', 0, 'repairchest.destroy', '', ''),
(93, 'baryga', 0, 'scavenger.scavenge', '', ''),
(94, 'baryga', 0, 'easyjetpack.standard', '', ''),
(95, 'baryga', 0, 'easyjetpack.fallboots', '', ''),
(98, '920c79d8-a1ca-3c23-8b42-dadfe7a301f4', 1, 'last-login-time', '', '1420572327'),
(99, 'baryga', 0, 'essentials.home.bed', '', ''),
(100, 'baryga', 0, 'essentials.sethome.bed', '', ''),
(101, 'default', 0, 'essentials.back', '', ''),
(102, 'default', 0, 'essentials.help', '', ''),
(116, 'default', 0, 'essentials.ignore', '', ''),
(122, '920c79d8-a1ca-3c23-8b42-dadfe7a301f4', 1, 'group-baryga-until', '', '1421971484');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

---------------------------------------
-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u1
-- http://www.phpmyadmin.net
--
-- Хост: localhost
-- Creation time: Янв 13 2015 г., 19:56
-- Version of the server: 5.5.40
-- version PHP: 5.4.36-0+deb7u1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `mine001`
--

-- --------------------------------------------------------

--
-- Structure of the table `permissions_entity`
--

CREATE TABLE IF NOT EXISTS `permissions_entity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `type` tinyint(1) NOT NULL,
  `default` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`,`type`),
  KEY `default` (`default`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=12 ;

--
-- Dump of data of the table `permissions_entity`
--

INSERT INTO `permissions_entity` (`id`, `name`, `type`, `default`) VALUES
(1, 'default', 0, 1),
(2, 'baryga', 0, 0),
(3, 'vip', 0, 0),
(4, 'svip', 0, 0),
(5, 'moder', 0, 0),
(6, 'admin', 0, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
--------------------
-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u1
-- http://www.phpmyadmin.net
--
-- Хост: localhost
-- Creation time: Янв 13 2015 г., 19:56
-- Version of the server: 5.5.40
-- Version PHP: 5.4.36-0+deb7u1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `mine001`
--

-- --------------------------------------------------------

--
-- Structure of the table `permissions_inheritance`
--

CREATE TABLE IF NOT EXISTS `permissions_inheritance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `child` varchar(50) NOT NULL,
  `parent` varchar(50) NOT NULL,
  `type` tinyint(1) NOT NULL,
  `world` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `child` (`child`,`parent`,`type`,`world`),
  KEY `child_2` (`child`,`type`),
  KEY `parent` (`parent`,`type`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=10 ;

--
-- Dump of data of the table `permissions_inheritance`
--

INSERT INTO `permissions_inheritance` (`id`, `child`, `parent`, `type`, `world`) VALUES
(9, '920c79d8-a1ca-3c23-8b42-dadfe7a301f4', 'baryga', 1, NULL),
(1, 'baryga', 'default', 0, NULL),
(2, 'moder', 'default', 0, NULL),
(4, 'svip', 'vip', 0, NULL),
(3, 'vip', 'default', 0, NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
------------
and crush page log      http://pastebin.com/4chwfrnJ

**Comment by maclarens** [comment]
12hours works with new PermissionsEx-1.23.1-SNAPSHOT.jar , there was no falling yet.... we test further :) :+1:

**Comment by zml2008** [comment]
Great! I'll close this now, but if the issue comes back up just comment on this and I'll reopen.

**Comment by maclarens** [comment]
yep!and ty so much!///

**Comment by maclarens** [comment]
add uniqueness indexes to your table PErmissions, without them the server brakes and at the end breaks, here!

this cool work:


CREATE TABLE IF NOT EXISTS `permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `type` tinyint(1) NOT NULL,
  `permission` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `world` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `value` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique` (`name`,`permission`,`world`,`type`),
  KEY `user` (`name`,`type`),
  KEY `world` (`world`,`name`,`type`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
