### ISSUE TITLE
debug spam removal

### ISSUE THREAD

**Issue by chillerkraft** [PEXPlugins/PermissionsEx#1848]
is there any way i can make the pex debug not show certain perm checks, so i don't have to look through a whole bunch of spam to see what i want to see?
or is there a better double jump plugin then this, with a toggle command, and no annoying pex debug spam 10 times a second?
http://dev.bukkit.org/bukkit-plugins/betterdoublejump/

**Comment by Stormbow** [comment]
Turn on debug just before you use a command or try to do something (opening a door, breaking a block, etc), and turn it off immediately after (and the fastest way to do that is hit enter, hit the up arrow until you see the debug command you'd typed, and hit enter again).  This regularly limits the "spam" to less than 20 permissions checks total.  Of course, prevent yourself from doing a dozen unrelated things when debugging.  (Don't walk, talk, move around, etc. and don't run debug for more than 5-10 seconds when all you're checking is a block break, for example.)

"Why doublejump at all when you can fly?" is my question. ;)

**Comment by zml2008** [comment]
Also, if you use any sort of terminal multiplexer like tmux you can grep through the permissions checks.

If you aren't, you can grep through your server logs too to find the relevant permissions!

**Comment by chillerkraft** [comment]
i wont be letting players fly in some of the worlds on my server. they wont be able to build, so i want to let them double jump so they can get out of ravines easily and 3 block high holes etc.
i will check n see if turning off double jumping for my player stops the perm checks, then i can use pex debug when other players aren't online at least.
i'm running my server with a host so i don't think i can use "tmux" can i?
any other comments or suggestions at all about anything here are welcome. ty for the help all

**Comment by zml2008** [comment]
We don't particularly care about servers without shell access because
that's fucking stupid. Get a better server host.

**Comment by Stormbow** [comment]
And as I said, don't toggle debug mode for the entire server.  You only need to toggle it for whoever is having permissions problems, and only for a few seconds.

pex user name toggle debug
do something
pex user name toggle debug

Problem solved.

**Comment by chillerkraft** [comment]
a better server host?? :/ i thought i was with the best..
is hosthorde not one of the best? what's shell access? :S

**Comment by chillerkraft** [comment]
i don't debug non stop lol, i turn it on and do the action quick then turn it off
but with the spam im talking about, sometimes 5 seconds has already filled the console,
even for one person
i think i was just wondering if i could remove certain checks from showing in the console,
like mainly from just the doublejump plugin i was talking about.

**Comment by Stormbow** [comment]
Sorry, no.
