### ISSUE TITLE
How to create groups via PermissionBackend?

### ISSUE THREAD

**Issue by Baba43** [PEXPlugins/PermissionsEx#1849]
Hey, after updating to the latest version I have some conflicts in my plugin.

The createGroup()-method seems to be gone and I can not find any replacement for it.

Can you tell me if it still posible to create groups (programmatically) or what to do otherwise?

Thanks for your great work!

**Comment by Baba43** [comment]
Found it.

PermissionManager.getGroup("bla").save();
PermissionManager.getGroup("bla").remove();

**Comment by Stormbow** [comment]
Excellent!
