### ISSUE TITLE
You don't have permissions for colors

### ISSUE THREAD

**Issue by Dino-SherComp** [PEXPlugins/PermissionsEx#1851]
I have Essentials,NoCheatPlus,PermissionsEx 1.23.
I have added nocheatplus.checks.chat.color and essentials.chat.color
everytime it says you don't have permissions for colors!
I just installed Vault to, and I saw PermissionsEx_Chat hooked!
I Think it Pex!
I removed Essentials and NoCheatPlus and I still don't have permissions! 
when I remove PermissionsEx , and I add Essentials and NCP I don't have any problems!

(I cant find any Permission for PermissionsEx_chat.)

Fix it. its very annoying!
SherComp.

Picture :
![permissionsex](https://cloud.githubusercontent.com/assets/6769455/5765076/fb601a06-9cf6-11e4-8bb9-a5e6b0b59144.PNG)

**Comment by Stormbow** [comment]
This is the 2nd time I'm seeing PermissionsEx_Chat and I have no idea where that's coming from either.

**Comment by Dino-SherComp** [comment]
Maybe its Vault??
But i don't think so.
Please fix this because i can't chat with colors anymore!

**Comment by zml2008** [comment]
PermissionsEx_Chat is vault's abstraction around PEX's chat-related API methods -- it's just an internal thing really.

Run /pex toggle debug to look at the permissions being checked when you chat to make sure there isn't something else stripping out colors by permission.

**Comment by Dino-SherComp** [comment]
![capture](https://cloud.githubusercontent.com/assets/6769455/5788008/3ef404c2-9dd2-11e4-84fa-0f6f87e68f4f.PNG)

All matched, i don't now it whats wrong:(

**Comment by Stormbow** [comment]
What exactly are you typing to create colored text?

**Comment by Dino-SherComp** [comment]
&5Check
or &4Check

**Comment by Albioncode** [comment]
> I have Essentials,NoCheatPlus,PermissionsEx 1.23.

It looks like you're being checked for the appropriate permissions but you haven't actually said whether EssentialsChat is installed or not. I'm unfamiliar with NoCheatPlus so if that's the chat manager you're trying to use then do ignore this.

**Comment by Dino-SherComp** [comment]
well, 
i removed NoCheatPlus! 
But the error still comes up when i try to send colored text into chat!
I installed essentials chat!
When i remove essentials, the error still comes up
when i remove Pex it gone!

but how come?

**Comment by Albioncode** [comment]
@Dino-SherComp you're referring to an error? Is this your problem or do you mean a physical error? If a physical error then care to elaborate?

**Comment by zml2008** [comment]
This is probably a weird interaction with the two plugins -- since the permissions check looked like they returned correctly, it's probably an issue with something else.
