### ISSUE TITLE
MySQL connection

### ISSUE THREAD

**Issue by FehrenLP** [PEXPlugins/PermissionsEx#1853]
Hey, I use PEX with MySQL backend but the connection to the Database disconnect after a few hours if no player connects to the Server. Is there a way to perform any MySQL action with a command or with the API that the connection won't disconnect? I hope you could help me

~ Felix

**Comment by zml2008** [comment]
In recent versions of PEX the connection pool should take care of restoring connections. Which version of PEX are you using?

**Comment by FehrenLP** [comment]
I am using version 1.20.4 should I update it?

**Comment by zml2008** [comment]
Yeah, as long as you're not using an ancient version of MC (<1.7.5) you should be good.
