### ISSUE TITLE
Crash : /pex import file!

### ISSUE THREAD

**Issue by Dino-SherComp** [PEXPlugins/PermissionsEx#1855]
i use Java 7 x64.
XAMPP MySQL
Windows Server 2008 Enterprise x64.

sometimes when I type  /pex import file the server crashes sometimes! , it is usually after about 10 minutes if the server is running and I type that command, it crashes !
How can this because once I do it right at the beginning it works fine !

maybe its a Bug in Spigot 1.8.
but other plugins are running good!
sometimes Essentials says Slow Permissions System.

Thanks!

**Comment by zml2008** [comment]
The import from file operation sometimes takes a long time, locking up the server for a while. Spigot prints an error if the server is stuck on one operation for too long (but if the operation is supposed to take that long, this is expected), but it's not an actual crash.
