### ISSUE TITLE
Crash on Reload Spigot 1.8

### ISSUE THREAD

**Issue by Dino-SherComp** [PEXPlugins/PermissionsEx#1857]
Hello,
Everytime when i do /reload the server crashes.
its PermissionsEx.

Crash log : 
http://pastebin.com/ApjgF8tr

**Comment by Stormbow** [comment]
The /reload command is a vanilla command which has been broken for more than 4 years.

Don't use it.  Reload plugins individually as needed.  /pex reload, /ess reload, etc.
