### ISSUE TITLE
Config file not appearing

### ISSUE THREAD

**Issue by Hestand** [PEXPlugins/PermissionsEx#1860]
After installing permissionsex on multicraft through the bukkit plugins then manually, the permissionsex files are not appearing. I when to the config files for permissionsex and there was none. In game the /pex shows up and says i have it...I have essentials, essentials chat and essentials spawn installed, along with permissionsex tab color and setrankpex. I cant add groups or anything without the config! Any help please

**Comment by Stormbow** [comment]
What version is your server and what version of PEX are you using?

**Comment by Hestand** [comment]
My server is bukkit 1.7.9 and i was using the latest permissions ex on the
bukkit page through multicraft

**Comment by Stormbow** [comment]
You don't know the version number of PEX that you're using?
