### ISSUE TITLE
Some sort of SQL error? Odd

### ISSUE THREAD

**Issue by Joannou1** [PEXPlugins/PermissionsEx#1861]
### Description ###

PEX works fine, but sometimes spams this error at random.
Gist says a lot of the plugins are 'disabled', but I think this was during plugin loading.. As all of them work great.

### Detailed Information ###

[Is available here](https://gist.github.com/8c1a87159411c3628294)

**Comment by zml2008** [comment]
Manually change the value column in the row where ``` `permission`="schema-version" ``` to 2.
