### ISSUE TITLE
Prefix's don't work/help

### ISSUE THREAD

**Issue by EggPersonWhoNeedsHelp** [PEXPlugins/PermissionsEx#1864]
Permissions work until we add the chatmanager, then nothing works! Please help.

**Comment by Stormbow** [comment]
What version is the server?
What version of PEX are you using?
Post a [Pastebin](http://pastebin.com) link to your permissions.yml file.

**Comment by zml2008** [comment]
Which chat plugin are you using? We do not support PEX ChatManager anymore.

**Comment by Stormbow** [comment]
Doh!  How did I miss the "chatmanager" mention?  That would definitely be the problem.
