### ISSUE TITLE
Pex 1.22.5 make somes freeze

### ISSUE THREAD

**Issue by AwaaX** [PEXPlugins/PermissionsEx#1866]
Hello, 
I have a very important problem who happen when I execute any /pex command.
For example, when I type /pex user it cause an important freeze on my server.
And essentials spam "[Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 224.558ms!"

A little more precision : This lag occurs since when I have turn bungeecord false to true at the config.yml from spigot.

But I must to stay bungeecord to true for important security reason.
Please need help :)

Bye, and i'm french, i don't speak english very good.

**Comment by mikemy** [comment]
Try pex 1.22.7 I remember seeing a commit about this I think

**Comment by AwaaX** [comment]
Ok i will test.
But why zml is not responding ?

**Comment by zml2008** [comment]
Because I'm not always around. As @mikemy said, you want to upgrade to 1.22.7. Also re-enable your autoupdater.
