### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Moehritz** [PEXPlugins/PermissionsEx#1868]
https://gist.github.com/64ce4c90aafc34fc68b5

During /pex user <name> group set <group>

**Comment by Stormbow** [comment]
Do you get the same error when using the correct command of **/pex user Stormbow group set Potato**?

**Comment by Moehritz** [comment]
Yeah the command was correct... I shortened it fpr this issue. I could NOT reproduce it, it was just happening when setting a group

**Comment by Stormbow** [comment]
That command isn't used to "set up" a group, but it's good you got it working.  :)
