### ISSUE TITLE
Timed add not working

### ISSUE THREAD

**Issue by IrParadox** [PEXPlugins/PermissionsEx#1869]
Cannot get timed add to work, using latest version of Pex with CraftBukkit 1.8 Spigot build.

The permission does not add to permissions.yml file, it becomes active if player is online but not added to perms file. When player logs out and back in they no longer have the permission. for example issuing ' /pex user <UserName> timed add essentials.fly 86400 "" ' to give them fly for a day, it registers that the permission was added and it gives them fly but when they logout and back in they no longer have fly. I also used variants at the end for world such as *, world and using nothing. All the same results. Has something changed in the way this command is used and I am doing it wrong or do we have other issues here?

Edit: No commands to add any permissions are working. I usually manually edit my permissions file. I have recently found a need to use commands and in an attempt to find a work around I have found that nothing is working. My permissions file loads up fine, no issues there. If I add permissions or groups, they work. Promote and group add and set work. But nothing along the lines of adding permissions.

**Comment by zml2008** [comment]
Timed permissions have always been transient (not saved to the permissions file). You may want to use timed groups instead for things that are expected to last beyond a single server invocation.
