### ISSUE TITLE
Can only create 1 rank

### ISSUE THREAD

**Issue by Dandiestdog** [PEXPlugins/PermissionsEx#1870]
So I pay for a hosted server through Multicraft and I installed PermissionsEx and started creating ranks. The first default rank works great until I add anymore ranks, that's when both the default and the next rank up doesn't work at all. It takes away all permissions and prefixes as if there are no ranks at all. When oped I can't even use the PermissionsEx commands while there is more than one rank saved in the permissions.yml. To sum it all up, the plugin works great when there is only one rank in the permissions.yml, if there is more than one rank the plugin than it doesn't work at all. 

This is a pastebin of my ranks when its working and when it isn't from the permissions.yml file.

Working:
http://pastebin.com/dWMRSVqF

Not working:
http://pastebin.com/cD39kmga

**Comment by Stormbow** [comment]
in your "Not working" permissions.yml file:
• Line 24: Missing a space between - and "default"
• Line 36: Missing a space between - and "default"

If you're using Minecraft 1.7.9+, your permissions.yml file should also follow [this example](http://pastebin.com/8ZSHxauG) or you will run into problems, especially with your prefixes and suffixes not working.
