### ISSUE TITLE
Lag with PEX

### ISSUE THREAD

**Issue by orkun1675** [PEXPlugins/PermissionsEx#1871]
Hi,

I am experiencing some performance issues with PEX 1.23.1 on Spigot 1.8. I am using MySQL backend. Here are my timings: http://timings.aikar.co/?url=9820648

It doesn't actually cause lag, but i want still want to improve performance on my server for smooth PvP'ing. I was hopping you could help. Thank you for your time in advance.

Sincerely,
orkun1675

**Comment by zml2008** [comment]
So are you actually experiencing issues with performance?

**Comment by orkun1675** [comment]
Exactly. Just like #1824

**Comment by zml2008** [comment]
That's not how you answer a yes or no question...

**Comment by Stormbow** [comment]
"Exactly. Just like #1824." ...then shouldn't you do some of what #1824 said-- run warmroast and provide a log?  ;p

**Comment by orkun1675** [comment]
Well I didn't se #1824 before I opened this post. So I thought zml would go ahead and close/merge this with the already existing issue.

I will run warmroast for a few hours tonight.

**Comment by orkun1675** [comment]
Here is the WarmRoast result during peak time: https://www.dropbox.com/s/vsrhpeat2yqs6kn/WarmRoast.html?dl=0

**Comment by zml2008** [comment]
I've looked at that and it looks like PEX is barely even showing up on the timings. The big things you might want to look at are dropped items and spigot's activation range settings.

On the PEX side, it looks like player-specific debug mode is the most performance-intensive feature, but it's not a big factor, so I don't plan on fixing that in the Bukkit version of PEX.

**Comment by orkun1675** [comment]
I still don't understand why timings say that PEX is using 5% of servers resources: http://timings.aikar.co/?url=10325194

Can you look once more into this please?
