### ISSUE TITLE
PermissionsEx ranks are not working

### ISSUE THREAD

**Issue by Dandiestdog** [PEXPlugins/PermissionsEx#1872]
I was making ranks for my server and I had this issue that when I add more than the default rank permissionsex and ranks for players stops working completely. I am not sure what I am doing wrong, I am running off of spigot 1.7.10.

This is my permissions.yml:
 http://pastebin.com/j45jejZW

Thanks for the help.

**Comment by zml2008** [comment]
Look for syntax errors from: http://yaml-online-parser.appspot.com
fix your syntax errors. also do not spam us with new issues, comment on your existing issue.

**Comment by Stormbow** [comment]
Also, be sure your permissions.yml file follows [this example](http://pastebin.com/8ZSHxauG) because the yaml checker can miss many things.
