### ISSUE TITLE
Pex bugging out on my host with modpack/mcpc+ server

### ISSUE THREAD

**Issue by Kvixen** [PEXPlugins/PermissionsEx#1873]
### Description ###

So, I've even went so far to make a private server on multiple computers to test my config out. It's working everywhere except when I upload it to my hosts FTP server. There is a default group. There's no error in the other servers. 
### Detailed Information ###

It's pretty much explained above. I test my config out and it's working. Then I upload it to my hosts FTP server and it gives me errors. 

This is my config:
http://pastebin.com/AEQ34vJZ
(W.I.P. I just wanted it to work after 24hours of testing on servers and sending it to all of my friends for them to test out. What am I doing wrong?) 
Oh, the thing is that I play on a modpack, and we use MCPC+ to have configs. Should it be able to have PEX? :/

(https://gist.github.com/6e148e27a820eeb94d63)

**Comment by Stormbow** [comment]
• Line 6: Missing apostrophes to close the open set.

Check out [this example](http://pastebin.com/8ZSHxauG) for formatting.  (Or you can delete line 6 entirely.)
