### ISSUE TITLE
Still having issues.

### ISSUE THREAD

**Issue by Kvixen** [PEXPlugins/PermissionsEx#1874]
### Description ###

I fixed  my config and copied a bit of Stormbow's example file (http://pastebin.com/8ZSHxauG).
This was my last request and I fixed the config to mirror the example file. I even switched "default: 'true'" to be on top of the "rank: 'x'"
### Detailed Information ###

It's pretty much detailed in the description. Same error. "No default group". I can't do the ingame commands and there's no permissions set up.

Config file: http://pastebin.com/4XtY9tua

 (https://gist.github.com/2087482741bc75b93137)

Sorry to bother you.. And sorry if I sounded angry. :|

**Comment by Stormbow** [comment]
Don't open new tickets for existing issues.
