### ISSUE TITLE
CME on Timed Permissions

### ISSUE THREAD

**Issue by drtshock** [PEXPlugins/PermissionsEx#1875]
Pex version: 1.22.7-SNAPSHOT
[08:08:02 INFO]: This server is running CraftBukkit version git-Spigot-d0d1d87-bc03b6f (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

We're getting a CME with our timed permissions https://gist.github.com/drtshock/33b3904050bfe73119b5

Command used to add timed group: /pex user {username} group add WorldEdit "" 21600

I'm not exactly a pex expert, let me know any further information you need :)

**Comment by zml2008** [comment]
I've heard this issue a few times before, but the fix is non-obvious so it might be a little while since my main focus is getting PEX for Sponge ready.

**Comment by drtshock** [comment]
Awesome, thanks!
