### ISSUE TITLE
just a bug, for now.

### ISSUE THREAD

**Issue by chillerkraft** [PEXPlugins/PermissionsEx#1876]
when i'm setting prefixes, i have to type the set prefix command twice before it actually sets the prefix i wanted instead of for some reason setting it as the prefix i set the group before as ..
sorry if you don't understand i can clarify.

**Comment by chillerkraft** [comment]
update: everytime i go to set a prefix to another group via command, it first says that it set the prefix as the prefix i had set the very first group to. it's once i type that command a second time that it says that it set the prefix as what i wanted it to be. deffinitly a bug, but not a big deal at this time functionality wise

**Comment by Stormbow** [comment]
Include your server version and PEX version in this thread.

**Comment by chillerkraft** [comment]
spigot-1.8.1-20150113a.jar
PermissionsEx 1.23.1

not sure exactly what the version is for spigot or how to find it or if the jar file name tells you exactly which one it is, here's some clips from my console if it helps

31.01 16:00:17 [Multicraft] Loaded config for "Mod: Spigot 1.8.1 (2015-01-13-a)"

31.01 16:00:26 [Server] INFO Starting minecraft server version 1.8

31.01 16:00:26 [Server] INFO This server is running CraftBukkit version git-Spigot-c46583f-e6f9fd4 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by Stormbow** [comment]
Sorry for the slow response.  Take a look at the [Prefix Tutorial](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-help-my-prefix-suffix-doesnt-work-111-1-1/?unread) to be sure you have the correct files and are using the correct commands.

Another thing to keep in mind is that after you make a change to a user or group, you also have to **/pex reload** to get the changes into the live server.  Have you been doing that also?

**Comment by chillerkraft** [comment]
all im saying is
when i go to prefix multiple groups one after another with the command,
the first one works fine, but every prefix set after that needs to be typed twice because the first prefix i set gets set the first time i use the command on the next groups i want to prefix
sorry this might be confusing, heres an example, btw this isnt a big deal but it is a bug.
pex group default prefix set example
default prefix set to example
pex group vip prefix set example2
vip prefix set to example
pex group vip prefix set example2
vip prefix set to example2
see how it set vip to example the first time i set it's prefix to example2
i had to type in the command again to get it to work
yea, i know, this sounds rediculous like why am i ticketing this.
but, idk, it might be useful info i hope

another thing i wanna mention is
if i negate a permission in my perms, and don't add it nonnegated anywhere else, is it at all possible to still allow ops to have this permission?
i noticed for example if i do -bukkit.* to default, then ops don't get any of these commands, i need to go and add this somewhere else nonnegated to get those commands

**Comment by Stormbow** [comment]
All I'm saying is that it's a bug only you are experiencing (I've been at this a long time and I've never encountered this "bug" from any other of the hundreds of users I've helped) and I can not recreate it.

What version is your server and what version of PEX are you using?

I recommend to everyone that they never use Op.  (There are always ways around it.)  It tends to screw with one's perception of which addons' permissions are setup correctly and which are not.  Op was intended for vanilla servers, not modified servers that use plugins (and especially not servers using permissions plugins).  The bukkit.* permissions-- likely because they are vanilla permissions --seem especially sensitive when it comes to using Ops.

**Comment by chillerkraft** [comment]
i already told you which versions im using

**Comment by chillerkraft** [comment]
ican make a little video of what im talking about

**Comment by chillerkraft** [comment]
i can't replicate this bug now lol, will update this later if i find it again.

**Comment by Stormbow** [comment]
LOL
