### ISSUE TITLE
"/pex import sql" time out

### ISSUE THREAD

**Issue by BlackBeltPanda** [PEXPlugins/PermissionsEx#1877]
PermissionsEx version: v1.23.1
Spigot version: fa7cbf9-00eba53

Using PermissionsEx with a SQL server and everything's working. Needed to manually edit the permissions (lots of changes to make).

I switched my backend to "file" so I can import the permissions from my SQL database and edit them manually. Restarted the server so the changed would take affect. Verified the backend properly changed to "file".

When I try to run "/pex import sql", the server times out.

Here's the error: http://pastebin.com/raw.php?i=hXcG5sSU

**Comment by zml2008** [comment]
It doesn't time out -- just wait longer and the import will go through. That is just a warning printed

Large databases can take large fractions of an hour to convert to SQL.

**Comment by BlackBeltPanda** [comment]
I can't wait longer, though, since the server times out and stops.

**Comment by zml2008** [comment]
There's an option in spigot to disable the timeouts.
