### ISSUE TITLE
I don't know if it's a bug, but.

### ISSUE THREAD

**Issue by Itay080** [PEXPlugins/PermissionsEx#1878]
Well, I am using pex for craftbukkit 1.7.2, I have just removed myself from the Owner group in order to test something, and as a regular member I was able to use all of the cheats, such as, /fly /gamemode etc.. I have logged out of the server and then logged in again, as a regular member and I did not have permissions to use those commands anymore, is it a bug? Or just because I removed myself from a group who has permissions for every single command in the server?
Thanks in advance.

**Comment by Stormbow** [comment]
1. Make sure you are not OP'd.  Being an Op can really screw up your perception of what's programmed properly in PEX and what is not.

2. What HeroCC said: Make sure you **/pex reload** if you've changed any user or group permissions.  Moving a user from one group to another, or adding a 2nd, 3rd, etc. group to a user does not require a **/pex reload**.
