### ISSUE TITLE
Getting Config and Permissionsfile

### ISSUE THREAD

**Issue by WilliamTheCoder** [PEXPlugins/PermissionsEx#1879]
Ive downloaded Pex and I had problems getting the config.yml and permissions.yml when I run the server but it dosent. Anybody got ideas what I could have done wrong? (ps. The Plugin is installed correctly since /help PermissionseX does work)
Can I make my own folders and if yes is the anything I have to keep in while making them?
Thanks for Reading :D

**Comment by Stormbow** [comment]
Make sure your server version and the version of PEX you're using are made for each other.  (Read the release notes.)  HUNDREDS of people are using incorrect versions of PEX on their servers lately, and PEX doesn't load at all.  (This would cause no folder and no config files to be created on a fresh install.)

You should not have to create a pex folder; the permissionsex.jar file goes into the plugins folder for your server, and on first run (compatible versions, see above), PEX will create it's folder containing the config.yml and permissions.yml files.

You can not rename that PermissionsEx folder (which PEX creates) or the config.yml file, and renaming the permissions.yml file (inside the config.yml and in the PermissionsEx folder that contains the config.yml and permissions.yml files) is just asking for problems.  I recommend against it.
