### ISSUE TITLE
1.8 startup error

### ISSUE THREAD

**Issue by xX99oddXx** [PEXPlugins/PermissionsEx#1882]
### Description ###
I'm not exactly sure what is happening or if I did something wrong. The plugins and groups were working before I updated, I updated to Spigot 1.8 and tried the plugin on Bukkit and the one on Spigot's Jenkins. 
### Detailed Information ###

The error message is here: http://pastebin.com/T54WeWfE

My permissions file is here if it helps:
http://pastebin.com/HiVXH9zN

**Comment by Stormbow** [comment]
What version of PEX are you using?

You cut out most of the error message, so it doesn't really help me at all.

**Comment by xX99oddXx** [comment]
I will post the log. The version is 1.23.1.

**Comment by xX99oddXx** [comment]
I re installed pex with a clean install and it worked fine thanks for your time.

**Comment by Stormbow** [comment]
Excellent.
