### ISSUE TITLE
Question about Multiworld Permissions

### ISSUE THREAD

**Issue by chillerkraft** [PEXPlugins/PermissionsEx#1883]
in a plugin i use that creates many different worlds all the time,
would it be possible to give permissions to all of these worlds?
theres name go like world_1, world_2, world_3 and so on. infinitly
could i do wildcard characters in worldnames? (world_* for example), thats all ican think of,
besides giving the permissions to everywhere by default and then taking them away from where i dont want them to be
except,
theres other worlds also being created lobby_1,lobby_2 and so on, where i dont want some of the perms active :/
actually now that i think about it, they seem to have made block targetting etc totally disabled in the lobby world, so maybe i could do what i last said.. but still,
just thought id shoot this at u guys briefly. ty for ur time

**Comment by mmatis** [comment]
You can do this already! Just put "(*)" after the part you want to match. For example, if you have Essentials installed and you have a slew of pvp worlds, you can give access to all of them, and any that are added later as long as the world name prefixed with "pvp_":

`- essentials.worlds.pvp_(*)`

or in your case:

`- plugin.permission.world_(*)`

The above will match /anything/ after "world_". If you want to limit it to just digits, do:
`- plugin.permission.world_(0-999)`

(Note, I figured the "(*)" trick out through trial and error. It should really be added to the wiki!)

**Comment by chillerkraft** [comment]
i need to have the permission node worldguard.build.* in the world_# worlds
i was wondering if i can put a * for the worldgroup name or anything like that so that i can give that permission node to the everchanging world names (world_14, world_15, world_16 and so on)

**Comment by chillerkraft** [comment]
for example

groups
  default
    permissions
    blahblahspawnnode
    bahblahother nodes but not build nodes because building isnt allowed insome worlds
    world_*:           <----------------------
      worldguard.build.*

idk , is there anything like that?

**Comment by mmatis** [comment]
Ah, I see. I haven't tried that. I don't know if this will work, but assuming the principle is same, try this:

```
groups:
    default:
        options:
            default: true
        permissions:
            - some.nodes.here
        worlds:
            world_(0-999):     <Or, try (*) instead>
                permissions:
                - worldguard.build.*
```

I'm not one of the devs, so I can't say for sure if this will work. Only way to know is to try it out!

**Comment by chillerkraft** [comment]
that doesnt work :(

**Comment by Stormbow** [comment]
I'm assuming the plugin you're using isn't creating temporary worlds on the fly that are deleted or something as soon as no one is in them.  Am I right?

If I am right and your worlds are permanent, you would have to program for each world, using the [PEX Multiworld documentation](https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#pex-multiworld).

**Comment by chillerkraft** [comment]
its a skywars plugin, it makes a lobby_# when the queue is filled and people get teleported to it to vote for the map, and then an arena map gets made arenaname_# and players get teleported there. when these worlds are done being used they are deleted and next time, it makes a new _# for them 
i actually stopped using this plugin because multiverse was always asking about these new worlds, worldguard keeps making new worldspecific config files for each new world made, and i can not add permissions to these worlds except for the perms i give serverwide.

**Comment by chillerkraft** [comment]
for example, during the 6th skywars game played on the server, the maps would be called lobby_5 and arena_5, (assuming first one is just lobby and arena) and the 10th game would be lobby_10 and arena_10

**Comment by Stormbow** [comment]
If the worlds are automatically generated, PEX will not write permissions for them.  In a similar fashion, PEX will not delete all of the permissions for those worlds when the worlds are deleted from the server.

If the world names were reused by the skywars plugin each time a match was started, you could pre-establish the permissions of those worlds by way of the PEX Multiworld permissions system.  (Permissions can exist without anyone actually in a group, actually playing in a world, and even for a user who has not yet joined the server.)

**Comment by chillerkraft** [comment]
idk what to tell you, i'm still kind of curious to know if i can have any wildcard characters in worldnames for when worlds are autogenerated with a new # at the end every time, but i'm not using that skywars plugin anymore because it causes too many problems with worldguard and multiverse and permissions and other plugins, with it creating new worlds all of the time and me not being able to find tune those worlds specifically without making serverwide default arrangements for those worlds. you can close this ticket whenever

**Comment by chillerkraft** [comment]
o sorry, i didnt realize its already closed, i thought you added the waiting for info label and i wasnt sure what u were wanting info for, but as i look closer i see it says you closed it and removed the waiting for info label. ty for ur help. btw, so, it's not possible to wildcard characters in world names? or anything like that? just curious

**Comment by Stormbow** [comment]
Nope, sorry.  No wildcards in world names.
