### ISSUE TITLE
Crashes!

### ISSUE THREAD

**Issue by iMinecraftGuy** [PEXPlugins/PermissionsEx#1885]
### Description ###
Crashes.
[Insert description of issue here]
### Detailed Information ###
20:52:36 [ERROR] [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/NsAd. Full error:
20:52:36 java.lang.StackOverflowError
20:52:36 at java.util.Collections$UnmodifiableCollection.<init>(Unknown Source)
20:52:36 at java.util.Collections$UnmodifiableList.<init>(Unknown Source)
20:52:36 at java.util.Collections$UnmodifiableRandomAccessList.<init>(Unknown Source)
20:52:36 at java.util.Collections.unmodifiableList(Unknown Source)
20:52:36 at ru.tehkode.permissions.PermissionEntity.getOwnParentIdentifiers(PermissionEntity.java:823)
20:52:36 at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:843)
20:52:36 at ru.tehkode.permissions.PermissionEntity$6.fetchLocal(PermissionEntity.java:840)
20:52:36 at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:70)
20:52:36 at ru.tehkode.permissions.PermissionEntity.getParentsInternal(PermissionEntity.java:856)
20:52:36 at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831)
20:52:36 at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77)
20:52:36 at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402)
20:52:36 at ru.tehkode.permissions.PermissionEntity.getOptionInteger(PermissionEntity.java:443)
20:52:36 at ru.tehkode.permissions.PermissionGroup.getWeight(PermissionGroup.java:58)
20:52:36 at ru.tehkode.permissions.PermissionGroup.compareTo(PermissionGroup.java:300)
20:52:36 at ru.tehkode.permissions.PermissionGroup.compareTo(PermissionGroup.java:28)
20:52:36 at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source)
20:52:36 at java.util.ComparableTimSort.sort(Unknown Source)
20:52:36 at java.util.ComparableTimSort.sort(Unknown Source)
20:52:36 at java.util.Arrays.sort(Unknown Source)
20:52:36 at java.util.Collections.sort(Unknown Source)
20:52:37 at ru.tehkode.permissions.PermissionEntity.getParentsInternal(PermissionEntity.java:857)
20:52:37 at ru.tehkode.permissions.PermissionEntity.getParents(PermissionEntity.java:831)
20:52:37 at ru.tehkode.permissions.HierarchyTraverser.traverse(HierarchyTraverser.java:77)
20:52:37 at ru.tehkode.permissions.PermissionEntity.getOption(PermissionEntity.java:402)
20:52:37 at ru.tehkode.permissions.PermissionEntity.getOptionInteger(PermissionEntity.java:443)
20:52:37 at ru.tehkode.permissions.PermissionGroup.getWeight(PermissionGroup.java:58)
20:52:37 at ru.tehkode.permissions.PermissionGroup.compareTo(PermissionGroup.java:300)
20:52:37 at ru.tehkode.permissions.PermissionGroup.compareTo(PermissionGroup.java:28)
20:52:37 at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source)
20:52:37 at java.util.ComparableTimSort.sort(Unknown Source)
20:52:37 at java.util.ComparableTimSort.sort(Unknown Source)
20:52:37 at java.util.Arrays.sort(Unknown Source)
20:52:37 at java.util.Collections.sort(Unknown Source)

] Edit by Stormbow: Wall of text removed; Error repeats 78 more times from original post. [

[Is available here](https://gist.github.com/75c6af0dfb5c4ac28248)

**Comment by zml2008** [comment]
You have circular inheritance present in your permissions setup. Check your inheritance configuration to make sure nothing is present.
