### ISSUE TITLE
Server in loop - PermissionsEx problem

### ISSUE THREAD

**Issue by lnze** [PEXPlugins/PermissionsEx#1886]
My server is in a loop, creating a bunch of this error:

11.02 21:10:01 [Server] INFO at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:190) ~[spigot18.jar:git-Spigot-29dbaa7-262c777]

and then shutting down, and turning back on. 

Here is my permissions.yml file: http://pastebin.com/hVS8xYMu

Can anyone help me?

**Comment by Stormbow** [comment]
Why'd you close the ticket?  Did you figure out what was causing the loop?  (It would be nice of you to post the solution in case others find this ticket because they also have that problem.)
