### ISSUE TITLE
I broke PEX on my server.

### ISSUE THREAD

**Issue by Fightr2021** [PEXPlugins/PermissionsEx#1887]
No joke, I joined my server and the PermissionsEx plugin was broken, when I did /plugins it was in red, which obviously means it's disabled, and I have no clue why.
My log file: http://pastebin.com/jsypRUfU

Thanks,

Fightface.

EDIT: I know why it's being disabled, but I never even touched my Permissions file or messed with it the day it broke, and it was woring fine before.
Permissions File: http://pastebin.com/TRLGDA1r

**Comment by Stormbow** [comment]
PEX 1.20.4 is for your 1.6.4 server.  Start by downloading that [here](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/24-permissions-ex-v1-20-4/).

**Comment by Fightr2021** [comment]
This didn't work, I followed everything you said.

**Comment by Stormbow** [comment]
Post pastebin links to the new startup console log and your permissions.yml file.

**Comment by Fightr2021** [comment]
Permissions: http://pastebin.com/aiQPLNxK
Logs: http://pastebin.com/WpgKARH4

**Comment by Stormbow** [comment]
Pastebin link for your PermissionsEx\config.yml too please.

**Comment by Stormbow** [comment]
Delete line 208 from your permissions.yml file.

**Comment by Fightr2021** [comment]
Config: http://pastebin.com/2Bfb5rgm

**Comment by Stormbow** [comment]
Corrected permissions.yml file: http://pastebin.com/zib7Y1jC
Replace your file with the download (don't just copy and paste) of that link.

**Comment by Fightr2021** [comment]
Thank you a lot for helping me out with this, it's working fully now.

**Comment by Stormbow** [comment]
Excellent.  :)  You're welcome.

**Comment by Fightr2021** [comment]
Now whenever I add a permission, it breaks, do you know why?

**Comment by Stormbow** [comment]
Considering you haven't given me anything to work with about why-- no.

**Comment by Fightr2021** [comment]
I just would add a single permission and the permissions would break.
"Broken" permissions file: http://pastebin.com/XypMuem3

**Comment by Stormbow** [comment]
Correct the spacing on all of your group's prefixes.

Also, remove all of the lines with &f:

**Comment by Stormbow** [comment]
Your file should follow [this example](http://pastebin.com/8ZSHxauG).
