### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by RollOver** [PEXPlugins/PermissionsEx#1888]
### Description ###

12.02 23:52:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
12.02 23:52:00 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
12.02 23:52:00 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:301)
12.02 23:52:00 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:866)
12.02 23:52:00 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
12.02 23:52:00 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
12.02 23:52:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
12.02 23:52:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
12.02 23:52:00 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
12.02 23:52:00 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:803)
12.02 23:52:00 [Server] INFO at org.dynmap.bukkit.permissions.PEXPermissions.create(PEXPermissions.java:24)
12.02 23:52:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
12.02 23:52:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
12.02 23:52:00 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
12.02 23:52:00 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
12.02 23:52:00 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12.02 23:52:00 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
12.02 23:52:00 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:194)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
12.02 23:52:00 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:188)
12.02 23:52:00 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
12.02 23:52:00 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/N4DV. Full error:
12.02 23:51:59 [Server] INFO Successfully connected to SQL database
12.02 23:51:59 [Multicraft] Skipped 119 lines due to rate limit (30/s)
12.02 23:51:58 [Server] INFO Loaded configuration for world 'Con_Amore'
12.02 23:51:58 [Server] INFO (Con_Amore) Fire spread is UNRESTRICTED.
12.02 23:51:58 [Server] INFO (Con_Amore) Lava fire is blocked.
12.02 23:51:58 [Server] INFO (Con_Amore) Lighters are PERMITTED.
12.02 23:51:58 [Server] INFO (Con_Amore) TNT ignition is PERMITTED.
12.02 23:51:58 [Server] INFO Loaded configuration for world 'ConAmore_the_end'
12.02 23:51:58 [Server] INFO (ConAmore_the_end) Fire spread is UNRESTRICTED.
12.02 23:51:58 [Server] INFO (ConAmore_the_end) Lava fire is blocked.
12.02 23:51:58 [Server] INFO (ConAmore_the_end) Lighters are PERMITTED.
12.02 23:51:58 [Server] INFO (ConAmore_the_end) TNT ignition is PERMITTED.
12.02 23:51:58 [Server] INFO Loaded configuration for world 'ConAmore_nether'
12.02 23:51:58 [Server] INFO (ConAmore_nether) Fire spread is UNRESTRICTED.
12.02 23:51:58 [Server] INFO (ConAmore_nether) Lava fire is blocked.
12.02 23:51:58 [Server] INFO (ConAmore_nether) Lighters are PERMITTED.
12.02 23:51:58 [Server] INFO (ConAmore_nether) TNT ignition is PERMITTED.
12.02 23:51:58 [Server] INFO Loaded configuration for world 'ConAmore'
12.02 23:51:58 [Server] INFO (ConAmore) Fire spread is UNRESTRICTED.
12.02 23:51:58 [Server] INFO (ConAmore) Lava fire is blocked.
12.02 23:51:58 [Server] INFO (ConAmore) Lighters are PERMITTED.
12.02 23:51:58 [Server] INFO (ConAmore) TNT ignition is PERMITTED.
12.02 23:51:58 [Server] INFO Enabling WorldGuard v5.9
12.02 23:51:58 [Server] INFO MyHome 2.3.1 enabled
12.02 23:51:58 [Server] INFO Access Control: Using Vault v1.5.0-b28
12.02 23:51:58 [Server] INFO Using localization: English (en)
12.02 23:51:58 [Server] INFO 0 homes loaded
12.02 23:51:58 [Server] INFO Enabling MyHome v2.3.1
12.02 23:51:58 [Server] INFO [Vault][Permission] PermissionsEx hooked.
12.02 23:51:58 [Server] INFO WEPIF: Using the Bukkit Permissions API.
12.02 23:51:58 [Server] INFO WEPIF: Using the Bukkit Permissions API.
12.02 23:51:58 [Server] INFO Disabling PermissionsEx v1.22.6
12.02 23:51:56 [Server] INFO Successfully connected to SQL database
12.02 23:51:55 [Server] INFO No updates found!
12.02 23:51:55 [Server] INFO Initializing sql backend
12.02 23:51:55 [Server] INFO Enabling PermissionsEx v1.22.6

What is the reason of this warns?
How I can fix them?]

### Detailed Information ###

[Is available here](https://gist.github.com/9be3f3f72a356161215c)

**Comment by zml2008** [comment]
1. Update to 1.22.7
2. It doesn't look like you've imported anything into your database. If this is true, delete your database and let PEX create a new one (in 1.22.7). Otherwise, you may have to manually set the schema version to whatever is appropriate.
