### ISSUE TITLE
Reloading PEX breaks PEX

### ISSUE THREAD

**Issue by wesley27** [PEXPlugins/PermissionsEx#1891]
My server uses MCMA to manage ranks. Anytime there is a change in MCMA ranks and it exports to PEX and reloads it, or when any other plugin reloads PEX, PEX stops working. All groups and permissions break and don't work, as if they don't exist. I have to restart the server to fix it. 

There is never a console stack trace or error, but I have evidence that this happens. This is obviously a major issue as many plugins and MCMA need to export/reload PEX without any issues.

http://pastebin.com/1evAnBjn

You can see in that console log that players ranks and perms were working, then I changed a rank in MCMA, it exported and reloaded PEX, and then ranks and permissions stopped working.

I know there isn't a stack trace so you may not know where to start, but I can tell you that this issue started occurring when we updated from PEX v1.21.4 to v1.22. So, something changed between 1.21.4 and 1.22 that is altering what happens when PEX is reloaded by another plugin/source, because before v1.22 this issue didn't happen.

**Comment by Stormbow** [comment]
If you're using the /reload command, yes, it breaks everything actually.  That's actually a vanilla command which Mojang is responsible for fixing, and they couldn't care less about it.  (It's been broken for years.)

The /pex reload command should work fine for ... reloading PEX.  *gasps*

**Comment by wesley27** [comment]
I'm sorey

**Comment by wesley27** [comment]
I'm sorey

**Comment by wesley27** [comment]
Sorry, I'm on my phone and Github is glitching like crazy..

Anyhow

**Comment by xsmokingbenx** [comment]
Hi,

For information I have a seems-like similar issue: When I add/remove a user from any group, I loose prefix & colors from PermissionsEX for all groups & players, and I have to restart the server to fix it, 

I confirm that the issue appears without using /reload command, it appears when PermissionsEX updates itself when we change the group of any user.

Thanks,

Smoke

**Comment by xsmokingbenx** [comment]
![pex](https://cloud.githubusercontent.com/assets/1022163/6203076/746536c4-b50d-11e4-8b91-a20cc3ef3424.png)

Here is a screenshot for further informations: 

1. testing a chat entry, all OK
2. Changing group of player, testing a chat entry, Pex config is now not taken in consideration
3. testing /pex reload, nothing change
4. restarting the complete server: Pex config is correct

The issue reappears everytime we change a user's group

**Comment by wesley27** [comment]
Yes, that's exactly what happens to me, with permissions not working at all in addition to prefixes being gone.

**Comment by Stormbow** [comment]
Sassy?  How's this for sassy?
