### ISSUE TITLE
Prefix + Permissions

### ISSUE THREAD

**Issue by BaZeMC** [PEXPlugins/PermissionsEx#1893]
I have some problems with the prefix and also with permissions. I put the prefix and in the server doesn´t appear and I also put the permissions from the plugin SurvivalGames and also does´t work. When we try to join the arena, it says: "You don´t have permission to join 1(arena)"

**Comment by CullanP** [comment]
Try reloading Pex. I've been having a ton of issues with the latest pex. So bad that I won't even use the newest version. Pretty much any plugins hooked into pex that are grabbing groups has broke for me. Permissions seem to take awhile to also show up unless you do /pex reload

**Comment by Stormbow** [comment]
Post a pastebin link to your permissions.yml file, include your server and PEX versions in the post.  I'll figure out what you're doing wrong.
