### ISSUE TITLE
Wrong permission attatchment (UUID's causing this?)

### ISSUE THREAD

**Issue by MithrandirCraft** [PEXPlugins/PermissionsEx#1894]
This has happened to me a few times (my server is offline mode btw):

Some of my moderators changed their names, so I deleted their moderator ranks from their old name, and re-added them to their new name whith /pex user <user> group set <group>

When re-setting the group, I check the permissions.yml file, and I see the permission has not been applied to the correct player, instead, it reapplies to his old name.

Lets say that Nizzoch recently changed his premium name to Notch. After doing this, I move his corresponding rank to Notch, but when I do, it gets applied to Nizzotch again, his old name.

**Comment by Stormbow** [comment]
Unfortunately (for you), PEX does not support OFFLINE MODE, so there's nothing I can do to help you there.

**Comment by MithrandirCraft** [comment]
Why all the hate towards offline mode servers? :/

This issue could also be affecting full premium servers, solving it is necesary both for ME, and other server owners.

**Comment by MithrandirCraft** [comment]
I found a way around this issue, it's up to you If you think It's worth excluding a bug, just because an offline-mode server reported it.
