### ISSUE TITLE
Default group set to "[]"

### ISSUE THREAD

**Issue by WASasquatch** [PEXPlugins/PermissionsEx#1895]
Default group is being set to "[]" for new users and permissions are not applying for them. For example, during testing on a normal acc, no permissions would work until I forced the user into the 'default' group. 

I did remove default and have a "builder" group, but I removed it and put back in the default group. But default is set. Could it be from removing the group initially before restoring it? If so would i have to restore a fresh install of the plugin?

**Comment by Stormbow** [comment]
Members of the "default: true" group should not have a group listed in the users list.  This is intentional.  Something is messed up in your permissions.yml file if they are not getting permissions.

Post a pastebin link to your permissions.yml file and I can take a look at it to find out where you went wrong.  Include your server version and PEX version in the post containing the link to pastebin.

**Comment by WASasquatch** [comment]
Why do they get permissions AFTER adding them to the default group then?
That would indicate there is nothing wrong the permissions but the plugin
loading the default permissions.

On Sun, Feb 15, 2015 at 6:24 PM, Stormbow <notifications@github.com> wrote:

> Members of the "default: true" group should not have a group listed in the
> users list. This is intentional. Something is messed up in your
> permissions.yml file if they are not getting permissions.
>
> Post a pastebin link to your permissions.yml file and I can take a look at
> it to find out where you went wrong. Include your server version and PEX
> version in the post containing the link to pastebin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PEXPlugins/PermissionsEx/issues/1895#issuecomment-74452100>
> .
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by WASasquatch** [comment]
PEX could not access the files correctly becasue someone edited them as
another acc on debian and they were not chowned correctly. Fixed. If anyone
else has this problem, be sure to run `chown -R minecraft_acc_user
/path/to/minecraft/server`

On Tue, Feb 17, 2015 at 11:37 AM, Jordan Thompson <jordanslost@gmail.com>
wrote:

> Why do they get permissions AFTER adding them to the default group then?
> That would indicate there is nothing wrong the permissions but the plugin
> loading the default permissions.
>
> On Sun, Feb 15, 2015 at 6:24 PM, Stormbow <notifications@github.com>
> wrote:
>
>> Members of the "default: true" group should not have a group listed in
>> the users list. This is intentional. Something is messed up in your
>> permissions.yml file if they are not getting permissions.
>>
>> Post a pastebin link to your permissions.yml file and I can take a look
>> at it to find out where you went wrong. Include your server version and PEX
>> version in the post containing the link to pastebin.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PEXPlugins/PermissionsEx/issues/1895#issuecomment-74452100>
>> .
>>
>
>
>
> --
> Sincerely,
> *Jordan S. C. Thompson *
> *Web Development & Design Coordinator*
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
