### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jan-Poeppel** [PEXPlugins/PermissionsEx#1896]
### Error ###

[By starting the server this Error appear]
### Detailed Information ###

[Is available here](https://gist.github.com/b236a74ddf525622ddbc)

**Comment by Europia79** [comment]
PEX v1.22.x are not compatible with Spigot 1.8 because spigot updated Guava from 10 to 17.

For Spigot 1.8, you have to use PEX v1.23.x

**Comment by Stormbow** [comment]
What he ^ said.
