### ISSUE TITLE
Reload issue

### ISSUE THREAD

**Issue by wesley27** [PEXPlugins/PermissionsEx#1897]
I'll start off by saying I'm sorry for whatever offensive comment I made, and that wasn't the intent. 

I know you don't get paid, and respect what you do, and I wouldn't have wasted your time(and mine) creating an issue if I didn't positively believe it was a PEX related issue. After hours of testing, I can positively say I'm not doing anything wrong.

I've literally weeks trying to isolate what was causing all the perms on my server to break. As I know you spend countless hours trying to make your plugin better, I know you can respect that I do the same for mine and my server. Don't you think it's reasonable to at least look in to this? I'm trying to work with you here, about an issue that resulted from a change in PEX, that effects many people.

McMyAdmin(MCMA) is a server management console that many people use to easily manage their servers. MCMA hooks into whatever perm plugin you use(in this case PEX) and automatically exports to the permissions plugin and reloads it everytime a change is made to perms/groups in MCMA. This is a quick, efficient way to manage groups.

Prior to PEX v1.22, this worked fine. We've been using MCMA and PEX for years and never had an problem. However, something in the PEX code that changed between v1.21 and v1.22+ broke this. Now, when MCMA reloads PEX, all perms and prefixes break. I am not the only person who has reported this issue with the same evidence. After hours of testing, I am certain that some change between those versions is causing this issue. I'm not doing anything wrong, I've tested every possibility.

I really hope that you will take the time to look into this, as it is a problem that effects a considerable number of people.

**Comment by zml2008** [comment]
Maybe because the location of prefixes changed and MCMA did not update its permissions config generation code?

**Comment by wesley27** [comment]
Wouldn't that only break prefixes though? I'm asking, I don't know how PEX fully works on that end. From the little that I know, I would think that changing the location of prefixes in PEX would only break prefixes/suffixes when MCMA exports? Shouldn't the rest of the permissions still work? Or am I wrong in that assumption?

**Comment by wesley27** [comment]
If you'd be willing to read the last two posts on this thread (report of this to MCMA) here: http://forums.cubecoders.com/default.aspx?g=posts&t=468#post953

That may explain why I'm led to believe that this issue is actually PEX. MCMA exports and rewrites the Permissions.yml fine. But when pex reloads to update and enact the changes that were made, it's as if it breaks and while pex cmds still work in game, no perms or groups show up. Then, if you restart the server, it all works again, including the changes that were made.

With that being said, it seems as though PEX isn't reading it's permissions.yml file after MCMA edits it and reloads it.

**Comment by AaronL98** [comment]
I can vouch for this. I'm having issues with pex reloading. Currently, only restarting the server fixes it.
When I try to reload pex, all group names lose their casing. Meaning all ranks will become lowercase. I have 26 different alphabetical ranks named A-rank to Z-rank. Upon a reload of pex, players will lose their permissions. I believe this is due to their rank not being found. As I do /pex user <name> to get the groups the player is in, it returns the rank names, BUT it returns them in full lower case (e.g. t-rank NOT T-rank). This happens to all ranks except the last one, Z-rank, which has the lowest weight.  I'm trying to provide as much information as I can here, and hope that this gets sorted or at least worked on.

**Comment by zml2008** [comment]
yeah, all entities are lowercased to improve lookup performance. group names are not the place for prettines (that's the prefix/suffix you're looking for)
