### ISSUE TITLE
Error occurred with PermissionsEx

### ISSUE THREAD

**Issue by woeterman94** [PEXPlugins/PermissionsEx#1898]
2:02:27 PM [SEVERE] [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/N9gd. Full error:
2:02:27 PM java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
2:02:27 PM 	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
2:02:27 PM 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
2:02:27 PM 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
2:02:27 PM 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
2:02:28 PM 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
2:02:28 PM 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
2:02:28 PM 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341)
2:02:28 PM 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313)
2:02:28 PM 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394)
2:02:28 PM 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362)
2:02:28 PM 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317)
2:02:28 PM 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190)
2:02:28 PM 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484)
2:02:28 PM 	at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
Guava needs to be updated.  Use PEX 1.23.
