### ISSUE TITLE
console says i'm Admin when in group called owner

### ISSUE THREAD

**Issue by chillerkraft** [PEXPlugins/PermissionsEx#1903]
is this a special feature, if a group is called owner then it assumes the player is an Admin and shows
[Server] INFO Admins: myname
in the console? where can i find more information on this? it's something i've been wondering about for a while, i thought it only show's Admins: playername for people who are opped?
if i have a group called owner, do those players in it get any other differences then people in groups named differently? or is it just the way it's displayed in console that changes

**Comment by macdja38** [comment]
I believe you are using essentials, essentials config file will allow you to customize what ranks name's it groups into what categories in the config file.

**Comment by chillerkraft** [comment]
o okay so it's not pex that makes it say Admin:? k ty

**Comment by Stormbow** [comment]
Check out the [Prefix / Suffix Tutorial](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/?unread) too.  It'll show you which lines in Essentials' config.yml you have to change to get the chat system working the way you like it.
