### ISSUE TITLE
Help me please i really need help of some one who knows this 

### ISSUE THREAD

**Issue by hamsterfat** [PEXPlugins/PermissionsEx#1906]
i got 1.8 spigot (dev) server and i put PEX plugins (1.23.1) so i can cotroll others commands but it doesnt work
and this is what in the console

org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [Spigot%201.8%20(Dev.).jar:git-Spigot-"606148f"]
23.02 02:34:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [Spigot%201.8%20(Dev.).jar:git-Spigot-"606148f"]
23.02 02:34:48 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [Spigot%201.8%20(Dev.).jar:git-Spigot-"606148f"]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:176) [PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.7.0_75]
23.02 02:34:48 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_75]
23.02 02:34:48 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_75]
23.02 02:34:48 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_75]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:122) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:383) ~[PermissionsEx-1.23.1.jar:?]
23.02 02:34:48 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
23.02 02:34:48 [Server] INFO =======================================================
23.02 02:34:48 [Server] INFO Details: Error loading permissions file!
23.02 02:34:48 [Server] INFO Your configuration must be fixed before PEX will enable
23.02 02:34:48 [Server] INFO ========== UNABLE TO LOAD PERMISSIONS BACKEND =========

**Comment by iaxedu** [comment]
You have a typo/ mistake in your permissions file. Not a pex issue just a bad configuaration.

**Comment by Stormbow** [comment]
Use PEX 1.23, not 1.23.1.
