### ISSUE TITLE
HELP : USER ARE NOT IN THIS LADDER

### ISSUE THREAD

**Issue by hamsterfat** [PEXPlugins/PermissionsEx#1908]
I GOT A PROBLEM WHEN I DO /pex promote hamsterfat1 Member IM OPPED USING USERNAME HAMSTERFAT BUT IT SAYS USER ARE NOT IN THIS LADDER help me please  this is MY PERMISSIONS.YML PLEASE HELP ME I NEED SOMEONE WHO CAN FIX THIS

] Edit by Stormbow: Moved wall of text to Pastebin: http://pastebin.com/ASRAqxDj [

**Comment by Stormbow** [comment]
1. Don't use Op.  Ever.

2. The command is **/pex promote <user> [ladder]** (not /pex promote <user> [group] as you attempted) or **/pex user <user> group set <group> [world]**.
