### ISSUE TITLE
PermissionsEx

### ISSUE THREAD

**Issue by Shadowhackercz** [PEXPlugins/PermissionsEx#1909]
Hi..

The error in the log is [Here](http://pastebin.com/vubTmJfj)

Should i create new columns? It happens with "prefix" too, but when i created new column called "prefix" - this error came up too.. So.. But PEX are working normally, prefix, suffix is ok, they're saved in table "permissions" and it's allright..

So? What i can do to fix that? I don't like it! :o But it's working.. 

So - it's the answer to create columns (with some specific datatype?) ?

**Comment by benjabvb** [comment]
maybe post you're permissions yml file

**Comment by Shadowhackercz** [comment]
Permissions.yml file? Are you sure? I'm using PEX on MySQL, that's why im getting this error, no? 

But in my permissions.yml file is just this..

"groups:
  default:
    options:
      default: 'true'
    permissions:
    - modifyworld.*
schema-version: 1
users:"

**Comment by Stormbow** [comment]
I think this is a matter of you having 2 "schema" version lines in your SQL.  schema-version: 1 is the correct one, I do believe.

**Comment by Shadowhackercz** [comment]
Hmm.. What? 2x schema-version lines? Where? I see only one.

**Comment by zml2008** [comment]
you'll have to update the schema-version's value to 1 more than what you currently have it set to. that should fix your issue.
