### ISSUE TITLE
Permissionsex not working!

### ISSUE THREAD

**Issue by Jack10310** [PEXPlugins/PermissionsEx#1910]
The 2nd post. The first one: https://github.com/PEXPlugins/PermissionsEx/issues/1905#issuecomment-75537139

permissions; http://pastebin.com/sAV07wFk

config file: http://pastebin.com/EhybzTSd

**Comment by Jack10310** [comment]
I added rank option also but i didn't add it ^^

**Comment by benjabvb** [comment]
I think i found an anwser for you're problem, whate program are you using to edit the yml files?
(download notepad++)
I ran you're permissions on a test server.
When i copied you perm file i found an error at line 75: "prefix: &1[&2Owner&1]" (it's in red!!!)
So just go to that line and rewrite the prefix, do not use tab!!!
Normally this will solve you're problem :)

**Comment by Jack10310** [comment]
http://prntscr.com/69rcxt

**Comment by Jack10310** [comment]
http://prntscr.com/69rf9j

**Comment by Jack10310** [comment]
And i do use notepad++

**Comment by benjabvb** [comment]
sorry, man i'm not the expert here.
i just tried it and it worked for me

**Comment by Stormbow** [comment]
You did not have to start a 2nd ticket to continue the problems the first one was having.  "Closed" means it's not anything the programmers/Zml has to worry about.

Locked means go back to your original ticket #1905  and post there.
