### ISSUE TITLE
PEX related crash

### ISSUE THREAD

**Issue by ayeelanaa** [PEXPlugins/PermissionsEx#1911]
Hi,
my server crashed earlier today and pex is mentioned a lot in the stacktrace
http://pastebin.com/WhkRHrnX

**Comment by Stormbow** [comment]
And which version of PEX are you using?  (Hint: Your answer should be "[1.23](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/39-permissions-ex-v1-23/)".)

**Comment by ayeelanaa** [comment]
Yes it is 1.23.1

**Comment by Stormbow** [comment]
Unfortunately, 1.23.1 and 1.23 are not the same thing.  1.23.1 is for 1.8 servers which have not updated Guava.  Use 1.23 (linked above) and see if the error remains.

**Comment by zml2008** [comment]
Looks like there's probably some timeout happening. Adjust the server timeout in the spigot config so the server doesn't kill itself so quickly
