### ISSUE TITLE
PermissionsEx - Set group as default, but when a new player joins, he is not given the rank.

### ISSUE THREAD

**Issue by ProMiner10000** [PEXPlugins/PermissionsEx#1912]
I set the default rank to "Stowaway" and when a new player joins, he is not given the rank, can someone help me? Here is whats inside the permissions.yml file.

https://www.dropbox.com/s/dawhky3exx2uhwo/permissions.yml?dl=0

**Comment by MCSulphate** [comment]
Go on to the server and type /pex set default group <group> true <world>
That should work.

**Comment by MCSulphate** [comment]
replace group with your group you want

**Comment by Stormbow** [comment]
Deleted 2 comments by McSulphate which were incorrect information.

The correct command to set the default group for a server is **/pex set default group groupname [world]**.

**Comment by Stormbow** [comment]
ProMiner10000: What -exactly- do you mean by "his is not given the rank"?

**Comment by ProMiner10000** [comment]
I'm not sure what happened, but, when I went to bed last night, woke up, I went on an alternative account, and the user was immediately given the Stowaway rank, so it is now fixed, and for the Captain group, that user has the rank because I did "/pex user {USER} group set Captain" just to see the prefix, and make sure that the permissions were working, thank you for your help.
