### ISSUE TITLE
Server Hang on Offline Player Lookup

### ISSUE THREAD

**Issue by NathanWolf** [PEXPlugins/PermissionsEx#1913]
I can reliably cause a Spigot 1.8 server to hang with the following set up:

- WorldGuard is installed
- PreciousStones is installed
- I set off TNT near a protection field of an offline player

The resulting hang log is here:

http://pastebin.com/tNc5aDx7

**Comment by zml2008** [comment]
I suggest getting a better internet connection. That hang is in Mojang code, not PEX code.
