### ISSUE TITLE
Promotion error: Promoter don't have high enough rank to change ....

### ISSUE THREAD

**Issue by MCSulphate** [PEXPlugins/PermissionsEx#1914]
Happens nearly everytime, the other times it says Promotion error: User are not in this ladder. I have the 'Default' group set to rank 700 and 'Helper' group set to rank 600. I am trying to promote from 'Co-Owner' which is set at rank 200, but it won't let me.

**Comment by Stormbow** [comment]
More than likely, you're using the wrong command.  (I've solved the same problem for another person recently.)

Post a [Pastebin](http://pastebin.com) link to your permissions.yml file and tell me which command (exactly) you've been trying to use and on which person(s)/group(s) you're trying to use it.

**Comment by zml2008** [comment]
It's been a month with no response, closing.
