### ISSUE TITLE
Pex Spigot 1.8 Update not working

### ISSUE THREAD

**Issue by j3lackstar** [PEXPlugins/PermissionsEx#1917]
Hello,

I use the newest 1.8 Spigot Version from http://getspigot.org/ .
I use the this http://dev.bukkit.org/bukkit-plugins/permissionsex/files/41-permissions-ex-v1-23-1/    (PermissionsEx v1.23.1)

And on my Server Pex dont working, when i write something, i dont see the prefix and i dont have permissions

**Comment by Stormbow** [comment]
Did you read the release notes for PEX 1.23.1?

**Comment by cwstra** [comment]
I have that same problem, J3lackstar

**Comment by j3lackstar** [comment]
I found the problem, you must use https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/ (Essentials.2Snapshot)

**Comment by zml2008** [comment]
Great that you figured that out
