### ISSUE TITLE
Group Change Event

### ISSUE THREAD

**Issue by nfell2009** [PEXPlugins/PermissionsEx#1920]
Heya,

I'm currently making an addon for Skript (http://dev.bukkit.org/bukkit-plugins/skript/) called Umbaska (http://dev.bukkit.org/bukkit-plugins/umbaska/). I have managed to hook into Vault and do some cool stuff with permissions, however, many people have requested a group change event. The Vault team have said it isn't doable by them due to how Vault works, so I am asking if it would be possible for the PEX team to do so. If this exists then please point me in the right direction.

Thanks,
nfell2009

**Comment by zml2008** [comment]
The [PermissionsEntityEvent](https://github.com/PEXPlugins/PermissionsEx/blob/1.23.x/src/main/java/ru/tehkode/permissions/events/PermissionEntityEvent.java) should cover what you want to track.

**Comment by nfell2009** [comment]
Thank you! :)
