### ISSUE TITLE
Groups changing after reload of plugin

### ISSUE THREAD

**Issue by ZFERRELL** [PEXPlugins/PermissionsEx#1927]
I posted this on the PEX forum a couple days ago:

"I am working on my ranking system right now. I have been testing it all day today by myself and with a friend. For some reason, at random times after reloading the plugin, the group I am in will randomly change to a different group without me changing it with a command. About ten minutes ago it happened. I was adding some permissions to a group my friend was in to test out a new plugin I installed. He was in a group called [A]Private, and then all of a sudden he was in a group called [M]Private after I reloaded it. I also noticed I went from the [Owner] group to the [A]Private group. As I'm sure you know, this is not a good thing at all. If this happens to players it would be a major problem. Has this happened to anyone else and is there a fix for this?"

Here is the link to it: http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/76041-groups-changing-after-reload/#p3

I got a reply from Stormbow to come here and submit a ticket to ask if this is a plugin issue or a hosting issue. It just happened again a few minutes ago. I made a new group for some builders on my server. I uploaded the file to Filezilla, reloaded it, and put myself into the new Builders group to test it out (I was previously in the "Owner" group). I then quickly edited the file again, reuploaded, and reloaded the plugin, and for some reason I was now in a completely different group without putting myself in it, and it wasn't a group I was in previously. Obviously this would be a huge problem for players. I can't have their ranks randomly changing, that would be a total nightmare. Please help!

**Comment by ZFERRELL** [comment]
I just took a video of me adding something to the file, uploading it back to Filezilla, and reloading Pex. You can clearly see the group changes after reloading to the console without me changing it.

https://www.youtube.com/watch?v=lZtk0ltpSPc&feature=youtu.be&hd=1

**Comment by zml2008** [comment]
Are you sure there were no changes to the remote file from the time you downloaded it to edit to when you reuploaded it? Because I can't reproduce this one.

**Comment by ZFERRELL** [comment]
I'm pretty sure I didn't change anything, all I did was open the file in notepad++ and edit it, then save it and reupload it. After I reloaded it would change my group, but it hasn't happened in quite a while. I really have no idea what could have been causing it. I am editing the permissions file today, so I will do a little testing again and see if it does it again.

**Comment by ZFERRELL** [comment]
Nevermind it is still doing it. When I make a change in the file with Notepad++ and reupload it (I'm uploading it through FTP on my server host) and then do /pex reload, it keeps sending me back to the default rank. I don't know why. If you want you can come on my server and see, or get on skype and I could show you. It's definitely a major problem for me, because when I have players on, if I make any changes to the file and reload, it might change everyone's ranks and that will be a super pain.

**Comment by jolbol1** [comment]
Happening to me, Whenever the file is edited and reloaded, It deranks everyone.

**Comment by ZFERRELL** [comment]
Jolbol1 I'm glad it's not just me it's happening to. I feel it's a /pex reload problem or something. I even changed from 1.23.1 to 1.23 and it still happens. I can't figure out if it's a Filezilla thing or the reload thing but it's really annoying me.

**Comment by TNTUP** [comment]
Happened on me too, I'm using Autorank too for rankups, on next server reboot the players who got ranked are downgraded to the last rank

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
