### ISSUE TITLE
Remove autocomplete for usernames

### ISSUE THREAD

**Issue by ItsHarry** [PEXPlugins/PermissionsEx#1931]
Why does this feature still exist? It does nothing but cause trouble, especially for Buycraft installations.

Buycraft executes this command:
```java
pex user itsharry add essentials.fly
```

Permission is added to the user itsharry_123 instead of itsharry.

**Comment by macdja38** [comment]
I find this Feature very helpful when manually managing ranks on my server and enjjin has no problems with the Feature. It still exists because it's helpful to people...

**Comment by zml2008** [comment]
This is why there is this thing called an API that buycraft might perhaps be able to use like any other plugin that wants to programatically modify permissions. The devs of buycraft could also read the documentation and see that prefixing a name with # will use exact resolution. There's two whole options for them.
