### ISSUE TITLE
PermissionEx MYSQL

### ISSUE THREAD

**Issue by V0rki** [PEXPlugins/PermissionsEx#1934]
09.03 17:23:08 [Server] INFO Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
09.03 17:23:08 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
09.03 17:23:08 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
09.03 17:23:08 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
09.03 17:23:08 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
09.03 17:23:08 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
09.03 17:23:08 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
09.03 17:23:08 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
09.03 17:23:08 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
09.03 17:23:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
09.03 17:23:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
09.03 17:23:08 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
09.03 17:23:08 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
09.03 17:23:08 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
09.03 17:23:08 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
09.03 17:23:08 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:193)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
09.03 17:23:08 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:187)
09.03 17:23:08 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
09.03 17:23:08 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/pcYd. Full error:
09.03 17:23:08 [Server] WARN An update to PermissionsEx version 1.23.1 is available to download from http://dev.bukkit.org/bukkit-plugins/permissionsex/. Please review the changes and update as soon as possible!

**Comment by zml2008** [comment]
Go take a look at the last line of that error message. It suggests that you upgrade -- you'll want 1.22.7 for your server version.
