### ISSUE TITLE
PermissionsEx Error! [Log]

### ISSUE THREAD

**Issue by chaotiic123** [PEXPlugins/PermissionsEx#1939]
### Description ###

i get an error every time i do this command

pex user chaotiic123 group add owner " lifetime

i do this on console by the way
### Detailed Information ###

[Is available here](https://gist.github.com/aea79dca151c5d15d05d)

**Comment by Stormbow** [comment]
The word "lifetime" is not part of the command.  You replace that with a value, a number of seconds.
