### ISSUE TITLE
Perms broken?

### ISSUE THREAD

**Issue by UnlightedTeam** [PEXPlugins/PermissionsEx#1940]
my host tryed to tell me that something was wrong with my perms that is causing issues on my server and im curious to see if i can get some clarification on that here. I updated everything i could to try and fix this issue.
permissions:
http://pastebin.com/FUCF5303
Startup log:
http://pastebin.com/pPNBvYh4
Startup log new (warn messages only):
http://pastebin.com/40TEBrUq
Plugins:
http://prntscr.com/6f864u

**Comment by zml2008** [comment]
What is the issue you're having?

**Comment by UnlightedTeam** [comment]
well right now its been narrowed down to just about one thing. my bukkit op command is not working and i have it set in the users section that i can just /op myself even when im de-op it worked before but for some reason it doesnt now and im not sure why

**Comment by zml2008** [comment]
Well, you haven't included any of your users section in this config, so not too sure how much I can do to help you unless you add that.

**Comment by UnlightedTeam** [comment]
http://pastebin.com/35AvgJhQ newer permissions files has a few things changed but still not fixed of course

**Comment by zml2008** [comment]
well, take a look at http://wiki.bukkit.org/CraftBukkit_commands. It looks like you got the permissions wrong for the op command.
