### ISSUE TITLE
error

### ISSUE THREAD

**Issue by H1t1** [PEXPlugins/PermissionsEx#1942]
title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+performing+PEX+check%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.NullPointerException%0A%09at+ru.tehkode.permissions.backends.file.FileEntity.getNode%28FileEntity.java%3A48%29%0A%09at+ru.tehkode.permissions.backends.file.FileEntity.%3Cinit%3E%28FileEntity.java%3A42%29%0A%09at+ru.tehkode.permissions.backends.file.FileUser.%3Cinit%3E%28FileUser.java%3A39%29%0A%09at+ru.tehkode.permissions.backends.FileBackend.getUser%28FileBackend.java%3A111%29%0A%09at+ru.tehkode.permissions.PermissionManager.getUser%28PermissionManager.java%3A116%29%0A%09at+ru.tehkode.permissions.PermissionManager.getUser%28PermissionManager.java%3A135%29%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.getUser%28PermissionsEx.java%3A201%29%0A%09at+ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.performCheck%28PermissiblePEX.java%3A150%29%0A%09at+ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.checkPermission%28PermissiblePEX.java%3A125%29%0A%09at+ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.hasPermission%28PermissiblePEX.java%3A116%29%0A%09at+org.bukkit.craftbukkit.v1_7_R4.entity.CraftHumanEntity.hasPermission%28CraftHumanEntity.java%3A111%29%0A%09at+com.TeamNovus.AutoMessage.Tasks.BroadcastTask.run%28BroadcastTask.java%3A29%29%0A%09at+org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run%28CraftTask.java%3A71%29%0A%09at+org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat%28CraftScheduler.java%3A350%29%0A%09at+net.minecraft.server.v1_7_R4.MinecraftServer.v%28MinecraftServer.java%3A641%29%0A%09at+net.minecraft.server.v1_7_R4.DedicatedServer.v%28DedicatedServer.java%3A289%29%0A%09at+net.minecraft.server.v1_7_R4.MinecraftServer.u%28MinecraftServer.java%3A584%29%0A%09at+net.minecraft.server.v1_7_R4.MinecraftServer.run%28MinecraftServer.java%3A490%29%0A%09at+net.minecraft.server.v1_7_R4.ThreadServerApplication.run%28SourceFile%3A628%29%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0A%23+%0A%23+This+configuration+file+created+by+FrosT.Original+page%3A+http%3A%2F%2Fwww.rubukkit.org%2Fthreads%2Fsurvival-pvp-%25D0%25A1%25D1%2582%25D0%25B0%25D0%25B1%25D0%25B8%25D0%25BB%25D1%258C%25D0%25BD%25D0%25B0%25D1%258F-%25D1%2581%25D0%25B1%25D0%25BE%25D1%2580%25D0%25BA%25D0%25B0-%25D0%25BE%25D1%2582-frost-spigot-1-5-2-1-6-4-1-7-2-linux-win-mac-v-3-6-2.47901%2F%0A%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0D%0A++default%3A%0D%0A++++options%3A%0D%0A++++++default%3A+true%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%263%C3%90%C2%98%C3%90%C2%B3%C3%91%C2%80%C3%90%C2%BE%C3%90%C2%BA%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++permissions%3A%0D%0A++++-+multiverse.portal.access.dupe%0D%0A++++-+multiverse.access.dupe%0D%0A++++-+multiverse.portal.access.hard%0D%0A++++-+multiverse.access.hard%0D%0A++++-+multiverse.portal.access.creative%0D%0A++++-+multiverse.access.creative%0D%0A++++-+UralClans.warm.ignore%0D%0A++++-+UralClans.create%0D%0A++++-+UralClans.delete%0D%0A++++-+UralClans.info%0D%0A++++-+UralClans.invite%0D%0A++++-+UralClans.kick%0D%0A++++-+UralClans.list%0D%0A++++-+UralClans.leave%0D%0A++++-+UralClans.welcome%0D%0A++++-+UralClans.leader%0D%0A++++-+UralClans.home%0D%0A++++-+UralClans.sethome%0D%0A++++-+UralClans.removehome%0D%0A++++-+UralClans.tag%0D%0A++++-+UralClans.msg%0D%0A++++-+UralClans.online%0D%0A++++-+UralClans.addmoder%0D%0A++++-+UralClans.delmoder%0D%0A++++-+essentials.eco.loan%0D%0A++++-+-essentials.me%0D%0A++++-+-essentials.eco%0D%0A++++-+chatmanager.chat.global%0D%0A++++-+essentials.balance%0D%0A++++-+essentials.build%0D%0A++++-+essentials.home%0D%0A++++-+essentials.sethome%0D%0A++++-+essentials.delhome%0D%0A++++-+essentials.pay%0D%0A++++-+essentials.help.worldedit%0D%0A++++-+essentials.warp%0D%0A++++-+essentials.balancetop%0D%0A++++-+essentials.buy%0D%0A++++-+essentials.rules%0D%0A++++-+essentials.spawn%0D%0A++++-+essentials.home%0D%0A++++-+essentials.tpaccept%0D%0A++++-+essentials.tpdeny%0D%0A++++-+essentials.ignore%0D%0A++++-+essentials.home%0D%0A++++-+essentials.signs.use.sell%0D%0A++++-+essentials.signs.use.buy%0D%0A++++-+essentials.signs.use.repair%0D%0A++++-+essentials.help%0D%0A++++-+essentials.tpa%0D%0A++++-+essentials.signs.use.warp%0D%0A++++-+essentials.signs.use.repair%0D%0A++++-+essentials.warp.list%0D%0A++++-+essentials.kit%0D%0A++++-+essentials.kits.Home%0D%0A++++-+essentials.kits.Start%0D%0A++++-+essentials.help%0D%0A++++-+essentials.motd%0D%0A++++-+essentials.msg%0D%0A++++-+essentials.rules%0D%0A++++-+essentials.spawn%0D%0A++++-+essentials.tpaccept%0D%0A++++-+essentials.tpdeny%0D%0A++++-+essentials.tpa%0D%0A++++-+worldguard.region.wand%0D%0A++++-+worldguard.region.select.own.*%0D%0A++++-+worldedit.selection.hpos%0D%0A++++-+worldedit.selection.pos%0D%0A++++-+worldedit.wand%0D%0A++++-+worldedit.selection.expand%0D%0A++++-+worldguard.region.claim%0D%0A++++-+worldguard.region.remove.own.*%0D%0A++++-+worldguard.region.info%0D%0A++++-+worldguard.region.info.own%0D%0A++++-+worldguard.region.info.member%0D%0A++++-+worldguard.region.addowner.own.*%0D%0A++++-+worldguard.region.removeowner.own.*%0D%0A++++-+worldguard.region.addmember.own.*%0D%0A++++-+worldguard.region.removemember.own.*%0D%0A++++-+worldguard.region.list%0D%0A++++-+jobs.join.*%0D%0A++++-+-authme.unregister%0D%0A++++-+authme.register%0D%0A++++-+authme.login%0D%0A++++-+authme.l%0D%0A++++-+authme.changepassword%0D%0A++++-+worldguard.region.flag.flags.pvp.*%0D%0A++++-+automessage.receive.default%0D%0A++++-+-bukkit.command.*%0D%0A++++worlds%3A%0D%0A++++++dupe%3A%0D%0A++++++++permissions%3A%0D%0A++++++++-+essentials.more%0D%0A++++++hard%3A%0D%0A++++++++permissions%3A%0D%0A++++++++-+-worldguard.*%0D%0A++++++++-+-essentials.sethome%0D%0A++++++++-+-essentials.tpa%0D%0A++++++++-+-essentials.tpaccept%0D%0A++++++++-+-essentials.kits.Start%0D%0A++++++++-+-essentials.kits.Home%0D%0A++++++++-+-essentials.home%0D%0A++++++++-+-worldguard.region.wand%0D%0A++Creative%3A%0D%0A++++options%3A%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%26d%C3%90%C2%BA%C3%91%C2%80%C3%90%C2%B5%C3%90%C2%B0%C3%91%C2%82%C3%90%C2%B8%C3%90%C2%B2%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++++default%3A+false%0D%0A++++inheritance%3A%0D%0A++++-+default%0D%0A++++permissions%3A%0D%0A++++-+multiverse.portal.access.build%0D%0A++++-+multiverse.access.build%0D%0A++++-+essentials.gamemode%0D%0A++++-+essentials.clear%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.ban.exempt%0D%0A++++-+bukkit.command.time.set%0D%0A++++-+bukkit.command.weather%0D%0A++++worlds%3A%0D%0A++++++build%3A%0D%0A++++++++permissions%3A%0D%0A++++++++-+worldedit.region.replace%0D%0A++++++++-+worldedit.selection.expand%0D%0A++++++++-+worldedit.region.set%0D%0A++++++++-+worldedit.region.walls%0D%0A++++++++-+worldedit.history.redo%0D%0A++++++++-+worldedit.history.undo%0D%0A++++++++-+worldedit.generation.pyramid%0D%0A++++++++-+worldedit.generation.hsphere%0D%0A++++++++-+worldedit.generation.sphere%0D%0A++++++++-+worldedit.clipboard.copy%0D%0A++++++++-+worldedit.clipboard.rotate%0D%0A++++++++-+worldedit.fixwater%0D%0A++++++++-+worldedit.fixlava%0D%0A++++++++-+worldedit.brush.gravity%0D%0A++++++++-+worldedit.brush.cylinder%0D%0A++++++++-+worldedit.brush.sphere%0D%0A++Premium%3A%0D%0A++++options%3A%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%26c%C3%90%C2%BF%C3%91%C2%80%C3%90%C2%B5%C3%90%C2%BC%C3%90%C2%B8%C3%91%C2%83%C3%90%C2%BC%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++++default%3A+false%0D%0A++++inheritance%3A%0D%0A++++-+default%0D%0A++++permissions%3A%0D%0A++++-+multiverse.portal.access.donat%0D%0A++++-+multiverse.access.donat%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.sethome.multiple.Premium%0D%0A++++-+essentials.kits.Premium%0D%0A++++-+essentials.repair%0D%0A++++-+essentials.heal%0D%0A++++-+essentials.god%0D%0A++++-+essentials.ban.exempt%0D%0A++++-+bukkit.command.weather%0D%0A++++-+bukkit.command.time.set%0D%0A++Vip%3A%0D%0A++++inheritance%3A%0D%0A++++-+premium%0D%0A++++-+default%0D%0A++++options%3A%0D%0A++++++default%3A+false%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%266%C3%90%C2%B2%C3%90%C2%B8%C3%90%C2%BF%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++permissions%3A%0D%0A++++-+multiverse.portal.access.donat%0D%0A++++-+multiverse.access.donat%0D%0A++++-+essentials.hat%0D%0A++++-+essentials.kits.Vip%0D%0A++++-+essentials.time.set%0D%0A++++-+essentials.msg.color%0D%0A++++-+essentials.weather%0D%0A++++-+essentials.back%0D%0A++++-+essentials.joinfullserver%0D%0A++++-+essentials.setwarp%0D%0A++++-+essentials.msg.*%0D%0A++++-+essentials.ban.exempt%0D%0A++++-+bukkit.command.time.set%0D%0A++++-+essentials.sethome.multiple.Vip%0D%0A++Emerald%3A%0D%0A++++options%3A%0D%0A++++++default%3A+false%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%267%C3%90%C2%AD%C3%90%C2%BC%C3%90%C2%B5%C3%91%C2%80%C3%90%C2%B0%C3%90%C2%BB%C3%91%C2%8C%C3%90%C2%B4%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++inheritance%3A%0D%0A++++-+vip%0D%0A++++-+default%0D%0A++++permissions%3A%0D%0A++++-+multiverse.portal.access.donat%0D%0A++++-+multiverse.access.donat%0D%0A++++-+essentials.feed%0D%0A++++-+essentials.tppos%0D%0A++++-+essentials.teleport.hidden%0D%0A++++-+essentials.kits.Emerald%0D%0A++++-+essentials.invsee.preventmodify%0D%0A++++-+essentials.heal.cooldown.bypass%0D%0A++++-+essentials.firework%0D%0A++++-+essentials.nocommandcost.all%0D%0A++++-+essentials.gamemode%0D%0A++++-+essentials.afk.kickexempt%0D%0A++++-+essentials.nick%0D%0A++++-+essentials.nick.color%0D%0A++++-+essentials.nick.format%0D%0A++++-+essentials.nick.magic%0D%0A++++-+essentials.vanish%0D%0A++++-+essentials.exp%0D%0A++++-+essentials.exp.others%0D%0A++++-+essentials.ban.exempt%0D%0A++++-+bukkit.command.time.set%0D%0A++++-+essentials.sethome.multiple.Emerald%0D%0A++Oper%3A%0D%0A++++options%3A%0D%0A++++++default%3A+false%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%262%C3%90%C2%B0%C3%90%C2%B4%C3%90%C2%BC%C3%90%C2%B8%C3%90%C2%BD%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++inheritance%3A%0D%0A++++-+default%0D%0A++++-+vip%0D%0A++++-+Premium%0D%0A++++-+Emerald%0D%0A++++-+Creative%0D%0A++++-+mod%0D%0A++++permissions%3A%0D%0A++++-+multiverse.portal.access.*%0D%0A++++-+multiverse.access.*%0D%0A++++-+essentials.exp%0D%0A++++-+essentials.xp%0D%0A++++-+essentials.tp%0D%0A++++-+chatmanager.chat.color%0D%0A++++-+essentials.ban.exempt%0D%0A++++-+bukkit.command.time.set%0D%0A++++-+worldguard.region.flag.flags.+*%0D%0A++++-+worldguard.region.flag.regions.own.+*%0D%0A++++-+essentials.sethome.multiple.Oper%0D%0A++Mod%3A%0D%0A++++inheritance%3A%0D%0A++++-+default%0D%0A++++-+oper%0D%0A++++options%3A%0D%0A++++++default%3A+false%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%26d%C3%90%C2%BC%C3%90%C2%BE%C3%90%C2%B4%C3%90%C2%B5%C3%91%C2%80%C3%90%C2%B0%C3%91%C2%82%C3%90%C2%BE%C3%91%C2%80%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++permissions%3A%0D%0A++++-+myworlds.portal.enter.creative%0D%0A++++-+myworlds.world.enter.creative%0D%0A++++-+myworlds.portal.enter.hard%0D%0A++++-+myworlds.world.enter.hard%0D%0A++++-+myworlds.portal.enter.donat%0D%0A++++-+myworlds.world.enter.donat%0D%0A++++-+essentials.ban%0D%0A++++-+essentials.banip%0D%0A++++-+essentials.broadcast%0D%0A++++-+essentials.kick%0D%0A++++-+essentials.mute%0D%0A++++-+essentials.god%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.sethome.multiple.mod%0D%0A++++-+essentials.heal%0D%0A++++-+essentials.unban%0D%0A++++-+essentials.ban.notify%0D%0A++++-+essentials.delwarp%0D%0A++++-+essentials.invsee%0D%0A++++-+essentials.tp%0D%0A++++-+essentials.joinfullserver%0D%0A++++-+essentials.gamemode%0D%0A++++-+essentials.give%0D%0A++++-+essentials.kit.*%0D%0A++++-+essentials.exp.set%0D%0A++++-+essentials.exp.give%0D%0A++++-+essentials.kill%0D%0A++++-+essentials.clearinventory%0D%0A++++-+essentials.clearinventory.others%0D%0A++++-+essentials.repair.all%0D%0A++++-+essentials.ban.exempt%0D%0A++++-+chatmanager.chat.color%0D%0A++++-+worldguard.region.flag.flags.+*%0D%0A++++-+worldguard.region.flag.regions.own.+*%0D%0A++OP%3A%0D%0A++++options%3A%0D%0A++++++default%3A+false%0D%0A++++++prefix%3A+%27%268%C3%A2%C2%95%C2%90%C3%A2%C2%95%C2%AC%26c%26l%C3%91%C2%81%C3%90%C2%BE%C3%90%C2%B7%C3%90%C2%B4%C3%90%C2%B0%C3%91%C2%82%C3%90%C2%B5%C3%90%C2%BB%C3%91%C2%8C%268%C3%A2%C2%95%C2%AC%26b%C3%A2%C2%97%C2%8F%C3%A2%C2%96%C2%BA%27%0D%0A++++++suffix%3A+%27%263%27%0D%0A++++permissions%3A%0D%0A++++-+%27*%27%0D%0A%60%60%60%0A§r. Full error:

**Comment by Stormbow** [comment]
Try again.
