### ISSUE TITLE
Can't Promote Players

### ISSUE THREAD

**Issue by marioandluigi878** [PEXPlugins/PermissionsEx#1944]
im trying to promote players but for some reason i cant promote them it says "Ranking Error <UUID/IGN>: User are not in this ladder I dont know what that means but I believe they are 

Pastebin to Permissions: http://pastebin.com/BEWUB5NY
if you need anything else let me know

**Comment by Stormbow** [comment]
Using the wrong command.

**PermissionsEx Promote/Demote Commands**
/pex promote <user> [ladder]
    Promotes <user> to next group on [ladder]
/pex demote <user> [ladder]
    Demotes <user> to previous group or [ladder]

/promote <user>
    Promotes <user> to next group *if no rank-ladder is used*
/demote <user>
    Demotes <user> to previous group *if no rank-ladder is used*

**Comment by marioandluigi878** [comment]
ok thxs but now i have another problem when i was working on the permissions my friend decided to crash my server and now i cant interact with anything or talk in chat 

Pastebin UPDATED: http://pastebin.com/vrhRa48Y

**Comment by Stormbow** [comment]
• Delete line 74. (I think this is why the server is crashing.)
• Make sure you are not using quotation marks in your prefixes.  (Example: Lines 137, 144, 155 and there may be more)

**Comment by Stormbow** [comment]
You can still reply to this ticket.  Closed just means Zml doesn't have to worry about it.

**Comment by marioandluigi878** [comment]
the thing is that its not the problem i was able to still chat before the server crashed when that happened ok how do i explain it my friend decided to place a bunch of tnt minecrafts while i was editing things and testing things out and apparently caused the server to crash after rebooting it i found that i could not do anything from chatting to interacting with the terrain

**Comment by Stormbow** [comment]
Check your chat management plugin (Essentials?) for config or jar file corruption.

**Comment by Stormbow** [comment]
I'm hoping your whole world wasn't ruined; that's what setting off too much TNT usually does-- literally destroys the server.

**Comment by marioandluigi878** [comment]
well i transfered it to my friends server and it works on there so only mines is glitched lucky me

**Comment by marioandluigi878** [comment]
the thing is also what im doing is for him since hes setting up a server for his viewers

**Comment by marioandluigi878** [comment]
but anyways i think we can offically close this

**Comment by Stormbow** [comment]
It's closed. :)  And you're welcome.
