### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by zml2008** [PEXPlugins/PermissionsEx#1945]
PEX2 needs a slightly different command structure due to important functionality differences.

Here's thoughts:
- `/pex [--transient] <user|group|etc> <name> <subcommand>  --context-type=context-name`

subcommands:
- `parent(s)?`
  - `<add|remove> <subject>`
- `option(s)?`
 - `set <key> <value>`
 - `unset <key>`
- `perm(ission(s)?)?`
 - `set <node> <true|false|t|f|int val>`
 - `unset <node>`

**Comment by zml2008** [comment]
Writing out permissions as I go:

- `permissionsex.reload`: Reload the plugin
- `permissionsex.debug`: Toggle debug mode
- `permissionsex.option.set.<subject>`: Set a subject's option
- `permissionsex.permission.set.<subject>`: Set a subject's permission
- `permissionsex.parent.add.<subject>`: Add a parent to a subject
- `permissionsex.parent.remove.<subject>`: Remove a parent from a subject 
- `permissionsex.info.<subject>`: View information about a subject

where <subject> is `<type>.<identifier>`. `own` is checked if the subject is the command executor and can also give access to the command.

**Comment by zml2008** [comment]
Commands are more or less implemented. They'll probably be tweaked over time though.

**Comment by Rentai** [comment]
Pex reload is given to everyone by default.

**Comment by hunter688** [comment]
Howto set default group for players?

**Comment by RunningBuff21** [comment]
Hi, I was wondering if you could explain more into the parents and inheriting commands portion of this plugin.  How is this done and what is the command breakdown

**Comment by sibomots** [comment]
Initial setup document / sample .conf ?

I haven't had much success in finding some sample config files

Just a typical server admin structure
Server with admins, moderators and players
Each with a set of permissions, the higher permissions inheriting from the lower levels

I've used PEX in the Cauldron era, but I think the config file format changed substantially.

**Comment by TypicalDarkness** [comment]
How can I make players be part of a default group when they join for the first time?

**Comment by hunter688** [comment]
https://forums.spongepowered.org/t/guide-pex-quick-command-reference/8738

**Comment by Favorlock** [comment]
Are you supposed to be able to do "pex user Favorlock parent add <somerandomword> admin"? All the examples I've seen use "group" for "<somerandomword", but yet I notice that you can use anything for "<somerandomword".

**Comment by xion87** [comment]
how i remove groups?

**Comment by Stormbow** [comment]
`/pex group <group> delete`

**Comment by yololetsplay** [comment]
Is it possible to set permission for "join" and "leave" specific group?

Like Tester123 is allowed to join (set himself) group "newbie" and is also allwowed to leave (remove himself) the group "newbie".

Like current config the following perms should be needed:

                        "permissionsex.parent.add.newbie.user.xxx-xxxx-xxxx-xxxx-xxxx": 1,
                        "permission.parent.add.newbie.own": 1,

Currently that does not work :/

Greetz,
Hannes

Btw. perfect for roleplay servers if working, like an officer is on duty and off duty.
