### ISSUE TITLE
plugin.yml

### ISSUE THREAD

**Issue by MCTyler** [PEXPlugins/PermissionsEx#1946]
Forgive my ignorance but the latest build does not include the plugin.yml. Where may I obtain this file?

**Comment by Stormbow** [comment]
Where'd you get a download that doesn't have the plugin.yml file?

**Comment by MCTyler** [comment]
I forked your source....

**Comment by zml2008** [comment]
2.0 is for Sponge. Sponge does not use the plugin.yml...

**Comment by MCTyler** [comment]
Ahhhh...Thank you very much! I look forward to your Spigot release then.
