### ISSUE TITLE
MySQL Help

### ISSUE THREAD

**Issue by HuliPvP** [PEXPlugins/PermissionsEx#1947]
I need help setting up Pex with MySQL, I do not know how to create a database and I do not know how to make pex support MySQL. I am making a bungee cord network, and need help with global ranking setup with pex, because I heard that if you have pex with the same database on all servers, the ranks are the same on all servers.

**Comment by HuliPvP** [comment]
I figured it out, but I read in the wiki that a permissions.db file was supposed to be created, it is not there. How do I get it?

**Comment by zml2008** [comment]
permissions.db is only for H2/sqlite, not mysql. You shouldn't have it.
