### ISSUE TITLE
pex error after updating spigot

### ISSUE THREAD

**Issue by worldmc** [PEXPlugins/PermissionsEx#1948]
### Description ###

updated spigot to newest stable build as of 22/3/2015
pex runs 1.23.1 

error happens on startup. does not seem to affect the working of the plugin
```
[19:37:11 INFO]: This server is running CraftBukkit version git-Spigot-"606148f" (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
```
### Detailed Information ###

Is available here:(https://gist.github.com/worldmc/9e5273a1c3b86e8ea26f)
Xed out pass and host.

**Comment by Stormbow** [comment]
That's not an error message.

**Comment by worldmc** [comment]
hey mister, 

there clearly is an error in the gist, it cant find an coloumn in the database. so either this is something wrong with the conversion of the database or something is setup wrong in the code. 

it told me to post the error here. so i did.
