### ISSUE TITLE
Cyrillic characters issue

### ISSUE THREAD

**Issue by zuzzas** [PEXPlugins/PermissionsEx#1952]
Hello.

I have a problem with PermissionsEx. When I try to alter prefix or suffix of a group or a player and use cyrillic characters an absolute garbage gets inserted into a MySQL table. What follows is an excerpt from a binary log:

```
# at 1883
#150326 21:46:48 server id 1  end_log_pos 2150 	Query	thread_id=48	exec_time=0	error_code=0
SET TIMESTAMP=1427402808/*!*/;
INSERT INTO `permissions` (`name`, `type`, `permission`, `world`, `value`) VALUES ('fd8d1ce4-a387-3da8-a13b-6f131d23cc99', 1, 'prefix', '', '[????]') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)
```

As you can see the value of the column "value" is already malformed (it should've been "[Тест]", which stands for "[Test]" in Russian) when it comes from a JDBC connection and is not damaged by having an improper encoding set in the database. It didn't happen when I had a file backend, so I assume that there must be something wrong with data being sent to the database.

**Comment by zml2008** [comment]
My best guess is that this is an issue with the MySQL jdbc connector? Make sure you're running the latest version of MySQL on your server. If that doesn't help, try setting the `character_set_server=utf8mb4` option on your mysql server (I'm going off of https://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-troubleshooting.html#qandaitem-15-1-15)

**Comment by zuzzas** [comment]
That was an issue. Thank you very much.
