### ISSUE TITLE
Removed plugin.yml

### ISSUE THREAD

**Issue by LefsFlare** [PEXPlugins/PermissionsEx#1953]
## Is plugin.yml removed?
Alright, so I have this problem where I've linked my 1.23.1 version of PEX to a remote MySQL and some commands apparently cause my whole server to crash from lag-out. I tried linking this repository to my own Jenkins server since I can't find the official one for this and tried building it.

So with the new build, apparently there isn't a plugin.yml?

**Comment by Stormbow** [comment]
This was covered in another ticket recently.

**Comment by LefsFlare** [comment]
Apparently so, is there still a branch for Spigot left?

**Comment by zml2008** [comment]
version 1.23.1 is the latest Bukkit version. I suggest that you do not use a remote mysql database because that increases latency.
