### ISSUE TITLE
Spigot 1.8.3 Issue

### ISSUE THREAD

**Issue by DeadIntermediate** [PEXPlugins/PermissionsEx#1955]
I am not sure if it's me. But seems like PEX is a little buggy with 1.8.3. Is there is going to be a compatible version?

Because I have a prison server and it seems like the commands doesnt want to still to the player.

**Comment by zml2008** [comment]
use /pex reload after changing things?

**Comment by zml2008** [comment]
The latest version is 1.8.3 compatible. I'm not sure if you have any specific complaint here, so I'm going to close this. If you feel like you have an actual issue you can explain, open another issue.
