### ISSUE TITLE
Group Set/Remove/Add not working properly in 1.23.1

### ISSUE THREAD

**Issue by DeadIntermediate** [PEXPlugins/PermissionsEx#1957]
I am using Spigot 1.8.3 as of 3/28/2015 and using PermissionsEX 1.23.1 with other plugins with the latest version of Vault.

I have a prison server and I use a plugin for ranking up players. But let me get to the point.

Players rank up when they have the money which executes the command to remove and add the the proper groups. So I it wasn't quite working.

So I thought, I'll ask a player to see whats causing it. So here is the list of commands of me running it.

DeadIntermeidate is rank A.

/pex user DeadIntermediate group remove A
/pex user DeadIntermediate group add B

Rank A and B permissions are no different, as Rank A have all of the basic permissions and B just has like 5 more permissions nodes.

Player try to execute command as Rank B should have, but doesn't. So player logs off the server. Logs back on, now has the Rank B rank and can use commands.

I hope that this gets fixed soon.

**Comment by PikachuEXE** [comment]
This might be fixed in new version 1.23.2
I am still testing

**Comment by iaxedu** [comment]
Not fixed yet just tested it. Same issue is still there.

**Comment by zml2008** [comment]
The CachingData changes have been reverted as of 1.22.9 and 1.23.3. This issue should be fixed.
