### ISSUE TITLE
Lag/Crash whenever certain commands are executed

### ISSUE THREAD

**Issue by LefsFlare** [PEXPlugins/PermissionsEx#1958]
I run a medium sized Minecraft server with PEX on and the one thing I noticed is that whenever I execute a command like adding a rank parent, there's a chance that it will lag so bad that my server crashes. I am using a remote SQL database, is that the cause of the problem?

**Comment by zml2008** [comment]
Yes. Use a local sql database or get a better internet connection between your MC server and your SQL server.

**Comment by LefsFlare** [comment]
Both servers are hooked up to T1-2 datacenters, both of them have a stable connection. I think a bigger problem is how PEX does not thread it's backend thread, resulting in the server waiting for PEX to be done first.

**Comment by zml2008** [comment]
yeah, well I'm in the process of rewriting PEX for Sponge with a better internal architecture so you can deal with the old codebase until the rewrite is done and all the plugins you want work with Sponge/forge

**Comment by LefsFlare** [comment]
zml, are you giving up on Bukkit? To no offense, your attitude towards this whole thing... it's really a turn-off.

**Comment by zml2008** [comment]
I've spent the past year putting bandaids on the problems in the Bukkit implementation and it hasn't gotten far enough.

Do note that the new codebase is designed so the core is entirely abstracted from Sponge, meaning I could write the necessary hooks to create a Bukkit plugin with the new architecture, which is something I am considering (but also something anybody with the free time could do)

**Comment by LefsFlare** [comment]
Okay, first up, I apologize for my previous little reply, it was a little rude and it probably was not appreciated. If I could, I definitely would not mind taking over the Bukkit branch on my own but obviously, my skills can never hope to match yours.

On to the second thing, if you still can get it hooked up to the Bukkit version, I'm sure a few thousand PEX users will definitely appreciate it as well. I'm not too knowledgeable about Sponge so I probably shouldn't make any comments first.

**Comment by LefsFlare** [comment]
zml,

Can I kindly request that as you work on PEX 2.0, you will also at the very least, continue the Bukkit part of it. Generally, at this point in time, if you were to finally make the Bukkit hooks, I don't want to find out that my current MySQL architecture to be completely different and result in me having to do up the entire permission system again.

On top of that, with the last stable Bukkit PEX version, is there a way to migrate SQL to file? Considering that the current code does not favor SQL backends too well when the database in question is remote.

**Comment by zml2008** [comment]
you invent human cloning, I get my clone to focus on the Bukkit version. How's that? 

On the topic of migrating SQL to file, set the backend to file then `/pex import sql`

**Comment by LefsFlare** [comment]
Well... I'll get back to you on that but it's hard finding a surrogate mother that don't mind raising a cloned zml with an equally bad attitude :D

With that, I ran that command for a good 30 minutes but it takes way too long...
