### ISSUE TITLE
Rankup plugin (Using Ezrankslite)

### ISSUE THREAD

**Issue by xXBlazeCraftXx** [PEXPlugins/PermissionsEx#1959]
My pex glitched and when someone ranks up they aren't ranked, so unless the config is reloaded they'll stay stucked in that rank. So whenever they rankup pex needs to be reloaded in order to be applied. I'm using PermissionsEx-1.22.7 please help!

**Comment by zml2008** [comment]
Can you test with [PEX 1.22.8](https://github.com/PEXPlugins/PermissionsEx/releases/tag/STABLE-1.22.8)?

**Comment by zml2008** [comment]
The CachingData changes have been reverted as of 1.22.9 and 1.23.3. This issue should be fixed, though no response was received.
