### ISSUE TITLE
Error Report.

### ISSUE THREAD

**Issue by ZachryWilsn** [PEXPlugins/PermissionsEx#1961]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[19:49:51 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/veOMr. Full error:
java.util.ConcurrentModificationException
>       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
>       at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
>       at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
>       at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:247)
>       at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
>       at org.bukkit.craftbukkit.v1_8_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
>       at me.clip.deluxechat.DeluxeChat.getPlayerFormat(DeluxeChat.java:467)
>       at me.clip.deluxechat.listeners.AsyncPlayerChatListener.onChat(AsyncPlayerChatListener.java:52)
>       at sun.reflect.GeneratedMethodAccessor411.invoke(Unknown Source)
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>       at java.lang.reflect.Method.invoke(Method.java:497)
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
>       at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1036)
>       at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:975)
>       at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
>       at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47)
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       at java.lang.Thread.run(Thread.java:745)
[Is available here](https://gist.github.com/a9acf008fb35bbf90e27)

**Comment by zml2008** [comment]
This should be fixed once I get 1.23.2 out. I'm just waiting for one PR to be fixed up before that happens.

**Comment by ZachryWilsn** [comment]
Thanks, Looking forward to it. Also willing to support this plugin again if needed.
Just let me know. I sent some in the past. I really love the plugin as do many others.
