### ISSUE TITLE
Timed group membership overrides primary groups

### ISSUE THREAD

**Issue by EvilOlaf** [PEXPlugins/PermissionsEx#1964]
Spigot 1.8 (not 1.8.3) @ PEX 1.23.1

By default all player have a primary group called `Player`.
Players can buy additional timed permissions and to keep them while they're offline an additional group membership is necessary.
So this command will be executed to give a player an additional group: 
`pex user <player> group add newgroup "" 3600`

My problem is, that the player does not belong any longer to the group `Player`, so he does not have any permissions of this group anymore.
This should probably the case if I would use `group set` instead of `group add`.

Adding an additional group to a player without world and time parameters works perfectly. The user has the permission nodes of both groups;.

Thanks for reading.

**Comment by zml2008** [comment]
make your new group inherit from player. Otherwise, default group membership will not be preserved. This changes in PEX 2.0 with the new defaults structure.

**Comment by EvilOlaf** [comment]
Thanks for the answer.
So in PEX 2.0 the behaviour would be as described above without needing inherits?
