### ISSUE TITLE
PEX not adding players to permissions.yml

### ISSUE THREAD

**Issue by DeadIntermediate** [PEXPlugins/PermissionsEx#1966]
I have a BungeeCord Server now and when a player logs in, it normally adds the UUID and name and player. But it's not. 

Here is my Permission.yml

http://pastebin.com/u7qFVNLU

**Comment by zml2008** [comment]
is createUserRecords or something similar enabled in your config.yml?

**Comment by DeadIntermediate** [comment]
I will post my config as a pastebin. Here.

http://pastebin.com/Gx6V1hJC

**Comment by zml2008** [comment]
createUserRecords should be true, not false.
