### ISSUE TITLE
Prevent UUID-Convertion?

### ISSUE THREAD

**Issue by Bronzeteufel** [PEXPlugins/PermissionsEx#1968]
Hey pex team,
i'm currently running version 1.19.6 with spigot 1.8.3 in offline mode, which is stable atm. But now it's time to say goodbye to 1.19.6, I need to update to 1.23.1. 
But I'm afraid of the UUID convertion, because other names got other md5 hashes in offline mode. 
So I will be VIP with "User", but not with "user", if you know what i mean, because "User" got another UUID than "user".
Any useful advices for me? Can I prevent the UUID-Convertion? :(

**Comment by zml2008** [comment]
Switch to online mode.

**Comment by Bronzeteufel** [comment]
Thank you for this very useful advice ^^
