### ISSUE TITLE
PEX not setting new users to default group

### ISSUE THREAD

**Issue by DeadIntermediate** [PEXPlugins/PermissionsEx#1969]
I have a bungee server. I got one problem fixed but now it's not setting them to default rank. Which is called default.

Here is my config and permissions.

Config: http://pastebin.com/hesiVen5
Permissions: http://pastebin.com/4G6ZQnSx

**Comment by zml2008** [comment]
A user with an empty groups list is automatically in the default group.

Also, your default group is configured incorrectly. The `default: true` line should be in the `options:` section.
