### ISSUE TITLE
Weird Server Synchronisation Issue

### ISSUE THREAD

**Issue by dwilson390** [PEXPlugins/PermissionsEx#1974]
Hi there,

I have a weird issue with PEX. I have 2 servers (excluding the Bungee)(One Survival, One Creative). If a players rank is changed on the Survival server, it immediately changes on the Creative one too however if a players rank is changed on the Creative server, you need to use /pex reload on the Survival server for it to update.

Both servers /PermissionsEx/config.yml are the same and both connected to the same database.

Any ideas as to why this is happening?
Thanks.

**Comment by zml2008** [comment]
PEX caches data. Updates happening immediately is not at all guaranteed across multiple servers. The NetEvents plugin can trigger events across servers though to perform reloads when changes happen.
