### ISSUE TITLE
Broadcasting Group Add/Remove

### ISSUE THREAD

**Issue by UnlightedTeam** [PEXPlugins/PermissionsEx#1977]
How can i get the server to stop broadcasting to everyone that a user was add/remove from a group?
This is a real inconvenience as it can be very spam like for larger servers. I looked through the GitHub but couldnt find a way to disable it.

**Comment by zml2008** [comment]
there's a broadcastChanges (or something like that) option in the config. Change that to false.

**Comment by UnlightedTeam** [comment]
this is all i see
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: true
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false
