### ISSUE TITLE
Config ignored

### ISSUE THREAD

**Issue by UnlightedTeam** [PEXPlugins/PermissionsEx#1978]
So in my config i have
  informplayers:
    changes: false
but i notice that it is partially ignoring this because the server is still showing people as being removed and added from groups but the promote and demote are not. is there something i can do to fix it where they cannot see people being added and removed from groups?
plugins: http://prntscr.com/6sqmvb
Spigot/Permissions Versions:
http://prntscr.com/6sqnu3

**Comment by zml2008** [comment]
Only the command executor sees a response to a user being added or removed from a group. The target does not see the message unless that config option is enabled.

**Comment by UnlightedTeam** [comment]
if thats true then why are they able to see it?
