### ISSUE TITLE
Server lock

### ISSUE THREAD

**Issue by SnowBlitzz** [PEXPlugins/PermissionsEx#1979]
I've been using version 1.22.6 since many months ago with no problem ago on my 1.7.10 cauldron server. Yesterday, the after a server restart, the server got 'locked' or in a way, it was online but nobody could join since they get timed out; console commands also don't work. Only found out the cause was Pex since I manually remove plugins one by one and found out pex was causing it. So I went to the page and updated to 1.22.7 but the same thing happens. Deleted pex permissions.yml and config.yml and started fresh with 1.22.7 as a test but still doesn't work. Tried going back to previous 1.22.x versions but none works. Tried to do /pex reload on the console on 1.22.7 but nothing happens. How do I fix this?

**Comment by zml2008** [comment]
once the server locks up, type ctrl+backslash and give us a pastebin of everything that is output.

**Comment by SnowBlitzz** [comment]
what does ctrl+backslash even do. Nothing for me

**Comment by zml2008** [comment]
tells you what command is executing

**Comment by SnowBlitzz** [comment]
nothing really happens. When it's 'locked' I can't even execute any commands.

**Comment by zml2008** [comment]
well, it tells you what methods are being executed in the server thread, so whatever game activity is occurring is recorded.

**Comment by SnowBlitzz** [comment]
For more info, I'm running pex 1.22.8 on cauldron 1.7.10. I wonder if pex even supports cauldron. This lockup has been long already. ctrl + blackslash doesnt do anything for me, im using multicraft btw if thats a problem.

**Comment by zml2008** [comment]
ctrl+backslash won't work unless you're in the real server console you get from directly running the jar. if you're using a wrapper like multicraft you're on your own for figuring out how to get a stack dump (try talking to the multicraft folks). We simply can't support all the non-standard things wrappers do.
