### ISSUE TITLE
Unknown column 'prefix' in 'field list'

### ISSUE THREAD

**Issue by iAmGuus** [PEXPlugins/PermissionsEx#1981]
### Description ###

Every time I start up my server using the MySQL backend, it gives me this stacktrace.
### Detailed Information ###
I am using PEX version 1.22.7 with Spigot build #1649 
https://gist.github.com/iAmGuus/426e381d2a85f14f7348

**Comment by Stormbow** [comment]
I think this is caused by your SQL having 2 "schema-version" lines.  Keep the line which has a value of 1.

**Comment by zml2008** [comment]
If you don't have multiple schema-version lines, just set the line you do have to 1.
