### ISSUE TITLE
Translation to other languages?

### ISSUE THREAD

**Issue by lifehome** [PEXPlugins/PermissionsEx#1983]
Is it possible for us to translate PermissionsEx? like a strings.yml?

**Comment by zml2008** [comment]
This has been implemented in PEX2.0 for Sponge already. Let me know if you're interested in working on translating PEX to any specific language and I'll get you set up. PEX uses gettext's po format for translations, which is pretty standard and has a lot of editors available.

**Comment by lifehome** [comment]
Humm, sponge, I still dunno how to set it up....
Anyway, I would like a zh_HK. ;)

**Comment by zml2008** [comment]
Ok, I've created a file for zh_HK. It's in the src/main/po folder of this repository. That's the file you'll edit to do translations.

Sponge is installed as a forge mod. Get a forge installation from files.minecraftforge.net. Then get a sponge dev build from https://repo.spongepowered.org/maven/org/spongepowered/sponge/ (go with the latest one) and copy it into forge's mods folder.

You can copy your plugins/ folder from Bukkit into the server root and PEX will copy its config from bukkit (but none of your bukkit plugins will load).

So you can test the translations, I recommend forking this repository and making edits locally. Unless you are already familiar with git, the simplest way to do this is:
1) Install Github for windows/mac
2) Fork this repository and clone in in the github desktop app
3) Install Maven (this is the tool we use to build PEX)
4) Perform translations, editing the zh_HK file either by hand or with a po editor (http://poedit.org seems ok, I do it by hand -- you can do whatever you prefer)
5) Run the command `mvn clean install` in terminal. This will give you a compiled permissionsex jar  as `target/permissionsex-2.0-SNAPSHOT.jar`. You can copy this into your mods/ folder in your server root.
6) Test the new translations, let me know if there's anything that is broken in the code or is difficult to translate, and once you are done, make a pull request to this repository.

Any amount of work helps!

**Comment by lifehome** [comment]
Oh great, maven huh? :laughing: 
Will get you back the file after my busy weekend ;)

**Comment by zml2008** [comment]
Awesome! Thanks so much for your help

**Comment by lifehome** [comment]
@zml2008 Humm, how could I resolve this?
https://gist.github.com/lifehome/2a96954af9af1d668964

**Comment by lifehome** [comment]
@zml2008 now I ran into missing xgettext...

**Comment by zml2008** [comment]
Your first issue is just from java being a bit funky about connecting to https urls -- so the sponge repo was having issues.

xgettext is included as part of the gettext distribution. On windows this seems to only be available through cygwin, on os x through homebrew, or on linux through your package manager.

**Comment by lifehome** [comment]
So I still can't get through that xgettext thing, and I have brewed the gettext...

**Comment by zml2008** [comment]
Whoops, I got kinda busy there. Latest dev build is available at http://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/lastSuccessfulBuild/artifact/target/permissionsex-2.0-SNAPSHOT.jar. However, you will need to have a working dev environment set up to be able to test changes currently (However, I'm looking into a different gettext plugin that does not require external dependencies for going po->resourcebundle)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
