### ISSUE TITLE
Pex is not recognising my default group and is coming up with an error

### ISSUE THREAD

**Issue by Maeghs** [PEXPlugins/PermissionsEx#1987]
Here is the error I get when a player joins 

19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:118)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.ProxyPermissionUser.initialize(ProxyPermissionUser.java:42)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:51)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:53)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:294)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:130)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionUser.getGroups(PermissionUser.java:219)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:284)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:295)
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.getDefaultGroup(FileBackend.java:138)
19.04 00:56:13 [Server] INFO java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property
19.04 00:56:13 [Server] ERROR Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F7aa4789bad9f2ae8f554%29%0A. Full error:
19.04 00:56:13 [Server] INFO at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:587) [craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit_beta.jar:git-Bukkit-1.7.2-R0.2-b2974jnks]
19.04 00:56:13 [Server] INFO at com.earth2me.essentials.EssentialsPlayerListener$2.run(EssentialsPlayerListener.java:235) ~[?:?]
19.04 00:56:13 [Server] INFO at com.earth2me.essentials.User.setDisplayNick(User.java:354) ~[?:?]
19.04 00:56:13 [Server] INFO at com.earth2me.essentials.User.getNick(User.java:318) ~[?:?]
19.04 00:56:13 [Server] INFO at com.earth2me.essentials.perm.PermissionsHandler.getPrefix(PermissionsHandler.java:80) ~[?:?]
19.04 00:56:13 [Server] INFO at com.earth2me.essentials.perm.PermissionsExHandler.getPrefix(PermissionsExHandler.java:75) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:118) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.ProxyPermissionUser.initialize(ProxyPermissionUser.java:42) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:51) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:53) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:294) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:130) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionUser.getGroups(PermissionUser.java:219) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:284) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:295) ~[?:?]
19.04 00:56:13 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.getDefaultGroup(FileBackend.java:138) ~[?:?]
19.04 00:56:13 [Server] INFO java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property

**Comment by iaxedu** [comment]
19.04 00:56:13 [Server] INFO java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property

**Comment by zml2008** [comment]
Try using something that is not an extremely outdated version of both Bukkit and PEX. Then we might be able to help you.

**Comment by Maeghs** [comment]
@zml2008
I have to use these versions as my server is on 1.7.2 because the online hosts I use have not made it possible for me to use craftbukkit 1.8 yet. Thankyou for your rude comment. I sorted this out about an hour ago anyway and it had nothing to do with what versions I was using. Thankyou so much for your help, dick.

**Comment by zml2008** [comment]
Not my problem that you have a shitty host.
