### ISSUE TITLE
PEX not updating new information without /pex reload

### ISSUE THREAD

**Issue by Krater107a** [PEXPlugins/PermissionsEx#1989]
Hello PEX Team. Just wanted to say GREAT plugin. I have used PEX since 2013 and have never looked to another permissions plugin as PEX has never let me down..... However....

I run a very small but active server from a desktop computer in my home. The concept is pretty simple; the longer people play the more land they can claim. I rely on a plugin called "ontime" to keep track of players play time and to promote them when appropriate. Unfortunately, PEX doesn't seem to be working correctly. When ever someone is promoted either through the "ontime" plugin or if I do it directly with a "/pex user Krater group set Member" nothing will happen. There rank remains the same as well as there original set of permissions. (even the permissions.yml file remains unchanged) It is only if the player leaves and reconnects or server restarts or I do a "/pex reload" will PEX update it's information and give the correct rank. This problem is occurring with PEX version 1.23.1 and 1.23.2. However PEX version 1.23  *is* working exactly as I need, with no problems. Players are ranked up on the fly with no intervention from me in 1.23. I am running a version of spigot 1.8.3 that I compiled as of 04/20/15. I have also been running an older version of spigot (1.8.1) with the same issues. Other plugins I am using: Ontime, WorldGuard, WorldEdit, ProtectionStones, RankPrefixPlus, Vault, WorldBorder, CS_CoreLib. Again the whole system works perfectly with PEX version 1.23.. It's just any higher version is consistently problematic.

Thanks for your time.

**Comment by nightmarex** [comment]
Having the same problem.

**Comment by extendedclip** [comment]
I am also experiencing this issue with any version above 1.23.

**Comment by zml2008** [comment]
The CachingData changes have been reverted as of 1.22.9 and 1.23.3. This issue should be fixed.

**Comment by extendedclip** [comment]
Great! Will be waiting to test the update when it is released! Has the update already been submitted? If not when can we expect it?
