### ISSUE TITLE
Error with MySQL

### ISSUE THREAD

**Issue by Jubby11** [PEXPlugins/PermissionsEx#1990]
Each time we start the server this error pops up. 

http://pastebin.com/UhvyrvHg <-------Thats the error

[Is available here](https://gist.github.com/a78c5722a0b05aaaf28f)

**Comment by Quezler** [comment]
It seems that the mysql connection is fine, there is a PermissionsEx database, there are PermissionsEx tables, but it is looking for the column called "prefix" the table called "field list", could you supply your PermissionsEx config here, and also the structure of your database?

**Comment by zml2008** [comment]
set the value column to 2 where the permission column is schema-version in the permissions table.
