### ISSUE TITLE
PermissionsEx not loading at all

### ISSUE THREAD

**Issue by tinlonchiu** [PEXPlugins/PermissionsEx#1993]
To be honest, I am a noob at plugins so when I got PEX, I tried and tried to look for how to make it load. 
My startup: http://pastebin.com/dcmgxcy8
My config: http://pastebin.com/k12iMgM8
My permissions: http://pastebin.com/BDXYRDpS

**Comment by Stormbow** [comment]
Doublecheck your permissions.yml file.  You have a massive amount of duplicate permissions in there.  (For example, look at lines 126 through 152; you do that same sort of thing in other groups as well.)

Consider using (https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#permissions-inheritance-top)[inheritance] to shorten your permissions.yml file.  You don't need to give every group the same exact permissions (like you repeatedly give lines 126 through 152 to several groups).  You can have latter groups inherit those permissions from the former groups.
