### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by bubu1428** [PEXPlugins/PermissionsEx#1995]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/af248543aa10099d60ca)

**Comment by Stormbow** [comment]
Looks like SQL is not properly setup.  You'll need zml to tell you for sure.

**Comment by Quezler** [comment]
According to the error log, it seems that in the database called "4" there are no PermissionsEx tables, so something is wrong with your setup.

**Comment by zml2008** [comment]
You are most likely encountering an issue that has been fixed in non-ancient versions of PEX. Please upgrade to the latest version of PEX. 1.20.4 is like over a year old and not at all supported.
