### ISSUE TITLE
Update rank and node error!

### ISSUE THREAD

**Issue by rwmtigewr** [PEXPlugins/PermissionsEx#1996]
every time i update someone rank or node. it crash and i end up reloading server. this is a problem see i need it fully work for auto ranking. i hope you code editor can fix this bug soon. thank you!

**Comment by zml2008** [comment]
what error did you get?

**Comment by rwmtigewr** [comment]
not sure. it dont show on console. i do know this. as soon i update rank or node on McMyAdmin. Rank text go missing. protect on command stop working till reload... i am running most update PermissionsEX

**Comment by zml2008** [comment]
If you're using the MCMA interface to edit permissions, you're going to have to talk to them first. We can't support anything but using the PEX commands.

**Comment by rwmtigewr** [comment]
it within that game as well. not just McMyAdmin. if i do /pex any command. i end up finding my self to reload...
