### ISSUE TITLE
PermissionsEx mysql structure

### ISSUE THREAD

**Issue by Quezler** [PEXPlugins/PermissionsEx#1998]
I'm planning to develop a better PermissionsEx webinterface compared to those currently existing.

I was wondering if there is some sort of "developer documentation" for the way PermissionsEx stores its content into the database.

If it does not exist, i'l figure it out myself, but i'd like to hear if it exists or not.

**Comment by zml2008** [comment]
no, the database schema is changing so it's not worth writing a web interface at the moment. currently looking at using an ORM for the 2.0 database, which will make it easier to do a java-powered web app that works with a PEX structure.

**Comment by Quezler** [comment]
Thanks for the info, is it already known when to expect version 2.0? it might be worth my efforts if its far from release :)

**Comment by zml2008** [comment]
it's a month or two out, and will be only for Sponge.

**Comment by Quezler** [comment]
to be honest, i think quite a lot of servers will stick with bukkit until the comunity dies completely, and i can easily create a webgui that can support multiple database types :)

thanks for your time.
