### ISSUE TITLE
PermissionsEx Error

### ISSUE THREAD

**Issue by BenyWolf** [PEXPlugins/PermissionsEx#1999]
### Description ###

This error is unknown to me
### Detailed Information ###

[Is available here](https://gist.github.com/bb1d254c8d1ee4eb6ebe)

**Comment by Stormbow** [comment]
I'm about 90% sure this is a "Guava needs to be updated" error message.

**Comment by zml2008** [comment]
yeah, either need to use 1.8 spigot or pex 1.22.8
