### ISSUE TITLE
Error on enable

### ISSUE THREAD

**Issue by Sindresgaming** [PEXPlugins/PermissionsEx#2001]
I put the plugin on the server (CraftBukkit version git-Spigot-d0d1d87-bc03b6f (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

### Detailed Information ###

[Is available here](https://gist.github.com/ebd5681516453105f3fd)

**Comment by zml2008** [comment]
running PEX 1.22 (version for 1.7.x) on a 1.8 server. read the version compatibility list.
