### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by TWSSYesterday** [PEXPlugins/PermissionsEx#2002]
https://github.com/drtshock/Essentials/issues/25
Related to PermissionsEx, not Essentials, this occurs on the latest PermissionsEx with the latest EssentialsX and Spigot.

**Comment by zml2008** [comment]
PermissionsEx does not actually do any formatting of names. Bring this up with the appropriate chat plugin. However, the issue is probably the fact that there is a maximum length of 16 characters for names in certain places, and adding color codes may cause that limit to be reached.

**Comment by TWSSYesterday** [comment]
I have done this, it's not an issue there, it happens in tab too.

**Comment by zml2008** [comment]
Well PEX doesn't actually apply prefixes, so this is not an issue with PEX.
