### ISSUE TITLE
[QUESTION] PomData error?

### ISSUE THREAD

**Issue by RobertHerhold** [PEXPlugins/PermissionsEx#2006]
So I see in the main  [plugin](https://github.com/PEXPlugins/PermissionsEx/blob/master/src/main/java/ninja/leaping/permissionsex/sponge/PermissionsExPlugin.java#L101) class, you're using the PomData variables, whose values are injected in from the maven template plugin. I'm currently using the same setup, but I can't get rid of the error (both Eclipse and IntelliJ) saying "PomData cannot be resolved to a variable". Did you find any way to fix this, or are you just ignoring it?

**Comment by zml2008** [comment]
PomData is a generated class. You'll have to build once with maven itself, then add the target/generated-sources folder to your IDE's source roots list.
