### ISSUE TITLE
Brackets.. + EssentialsChat

### ISSUE THREAD

**Issue by iHolden** [PEXPlugins/PermissionsEx#2007]
I do not know if this is posted in the right area. I've been trying for hours and looked up every possible way but I still do not know how to get rid of the annoying brackets (<>) when you type in chat. 

Here's my permissions file:
http://pastebin.com/zJ0G95aU

Here's my config.yml for essentials:
http://pastebin.com/Q0tVtSp5

Please help asap..

**Comment by Stormbow** [comment]
I can tell you that the <> you're referring to isn't actually from PEX or EssentialsChat; it has to do with some other plugin you're using.  Look through your other plugin config.yml files extremely closely and you'll find the cause.  For example, plugins like Multiverse and one for Skyblock (SkyWars?) set prefixes also.

**Comment by Stormbow** [comment]
Note: The ticket is closed so zml doesn't have to worry about it; you can still comment here.
