### ISSUE TITLE
Error in Multicraft console log - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Rocologo** [PEXPlugins/PermissionsEx#2011]
### Description ###
I found this error in my server console log. Im using Votifier and CommandListener to give the players permission to some groups when they vote for my server on up to 5 "minecraft server sites" 

This is the configuration file for the commandListener:

http://pastebin.com/KcPfy8EW

The error happened when I was voting for my server (mc.lindegaard.tk) my self (Gabriel333), on more sites ("http://minecraft-mp.com/server-s74163", "http://topg.org/server-the-universe-of-lindegaard-id399642", "http://minecraft-server-list.com/server/281825/", "http://minecraftservers.org/server/194879") 

[Insert description of issue here]
### Detailed Information ###

[Is available here]
https://gist.github.com/a7d1671e5e746d0df34d
http://pastebin.com/WSFPiHuE

**Comment by zml2008** [comment]
We don't support running PEX commands from anything but the main thread. Your votifier plugin is broken -- it should be scheduling command execution to occur on the main thread.

**Comment by Rocologo** [comment]
Well after your latest update of PEX everything was as it should.
