### ISSUE TITLE
Reimplement SQL backend

### ISSUE THREAD

**Issue by zml2008** [PEXPlugins/PermissionsEx#2014]
add compat with other databases
possibly using ORM?

**Comment by DarkArc** [comment]
Just saw this, consider jOOQ
http://www.jooq.org/

**Comment by zml2008** [comment]
On March 31, 2016 7:16:41 PM PDT, Wyatt Childers <notifications@github.com> wrote:
>Just saw this, consider jOOQ
>http://www.jooq.org/
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PEXPlugins/PermissionsEx/issues/2014#issuecomment-204211326

I have, it's huge
