### ISSUE TITLE
Easy GroupManager migration path

### ISSUE THREAD

**Issue by zml2008** [PEXPlugins/PermissionsEx#2015]
This needs

- Take a look at GM's command structure -> http://wiki.ess3.net/wiki/Group_Manager/Commands -- we need to simplify commands a bit

- A good format converter from the GM bukkit format 
- Be able to handle world inheritance/world-specific stuff in a way compatible to what GM had

**Comment by necrodoom** [comment]
For second part: http://convert2gm.chrisgward.com has a converter from PEX to GM, could it be reverse engineered?

**Comment by zml2008** [comment]
well, the 2.0 format is fairly different. I'm probably going to do the conversion mostly by looking at existing files

**Comment by zml2008** [comment]
The GM compatibility interface is being worked on in the [extrabackends repository](https://github.com/PEXPlugins/extrabackends)

Useful reference is http://wiki.ess3.net/wiki/Group_Manager/Config

GM appears to handle worlds entirely differently from how PEX both does now and used to do, so that should be taken into account.

**Comment by zml2008** [comment]
With latest commits to PEX and ExtraBackends, GM import is supported. However, due to the fact that GM structures its data quite differently from PEX, users will still have to do some minor changes to the structure of the permissions file to make everything work best with PEX.

There is the possibility of possibly improving the conversion to at least support the default world, which would help a lot of cases.
