### ISSUE TITLE
Why are all getGroups() and setGroups(); in the class PermissionUser deprecated?

### ISSUE THREAD

**Issue by MrEminent42** [PEXPlugins/PermissionsEx#2017]
I'm just wondering why they are deprecated? Are they being removed? Are developers not supposed to use them? What should I use instead?

Thanks,
MrEminent42

**Comment by zml2008** [comment]
Replaced with getParents() and setParents()

**Comment by MrEminent42** [comment]
If you see this, how can I get the main group the player is in? The one with the most weight?

**Comment by zml2008** [comment]
get(0)?

**Comment by MrEminent42** [comment]
So I can use 
p.getParents(0);
?

**Comment by zml2008** [comment]
p.getParents().get(0)
