### ISSUE TITLE
PEX WONT START!!

### ISSUE THREAD

**Issue by BiastGaming** [PEXPlugins/PermissionsEx#2019]
### Description ###

PEX WONT START
### Detailed Information ###
ERROR: http://gyazo.com/36692913be03bd2d1afcb206cb2d95ad

[Is available here](https://gist.github.com/79aa20ca40f9768cf880)

**Comment by zml2008** [comment]
Then maybe you shouldn't be using an outdated version of the 1.8 update on a 1.7 server? Instead, get the latest 1.22.x from the BukkitDev downloads page
