### ISSUE TITLE
permission.yml split

### ISSUE THREAD

**Issue by Coolechriz** [PEXPlugins/PermissionsEx#2021]
Dear reader,

I pass regularly to permissions.yml because I find this easier than working through the commands. especially when I have to adjust multiple permissions at the same time.

When players in the meantime received a rank or promoted and I reload the plug-in they lose their rank. it is possible to split the permissions.yml in two separate files:
groups.yml
users.yml

In this way it is also easier when you are editing something.

Sincerely.

Sorry for my English, this is not my main language.

**Comment by zml2008** [comment]
I'm afraid new features are not being accepted for the old 1.x version of PEX. However, I plan to make this possible in the 2.x version for Sponge.
