### ISSUE TITLE
Errors with Essentials

### ISSUE THREAD

**Issue by Agazed** [PEXPlugins/PermissionsEx#2024]
Getting these errors with essentials: http://pastebin.com/in0pTSLu

Not sure if you have heard of this issue, but I don't know where to report this bug for essentials. Looks like the code has something to do with your plugin and the Essentials plugin.

**Comment by Stormbow** [comment]
VTeam City is --not-- a legitimate source for the Essentials plugin.  Everything listed with VTeam City causes problems that can't be fixed as far as I know.  Download the official (http://dev.bukkit.org/bukkit-plugins/essentials/)[Essentials] package and I bet the error goes away.
