### ISSUE TITLE
Permission name cannot be null

### ISSUE THREAD

**Issue by AgentLV** [PEXPlugins/PermissionsEx#2025]
### Description ###

http://hastebin.com/vocurolinu.avrasm
### Detailed Information ###
Sry but I don't know what caused this. I see it in my Logs every now and then.

[Is available here](https://gist.github.com/e1cc2363e700007d6863)

**Comment by zml2008** [comment]
This could be an essentials bug, but since you're running Spigot's essentials fork you'll have to talk to the spigot folks about it.
