### ISSUE TITLE
"Prestige" plugin / PEX not adding players to group?

### ISSUE THREAD

**Issue by rewtie** [PEXPlugins/PermissionsEx#2026]
I have a prison server and I'm trying to set up prestiging after recently updating to 1.8.1. Incase you're not familiar with "prestiging", basically the plugin executes commands in console when the player uses the command "/prestige". They are only able to use it when they are the highest rank (which is Infamous). So, when they reach the highest rank, they use the command to prestige and go back to the 1st rank, which is Prisoner.

When they prestige, it does these commands: http://pastebin.com/xYDu2d2z

It executes all of the commands, but for some reason it does not put them in the prisoner or inmate groups, but only puts them into the prestige group.

Console when prestiging: http://pastebin.com/2nGWfTDM

User info after prestiging (/pex user {name}): http://prntscr.com/78c9zr

List of groups and weights (not sure if useful or not): http://pastebin.com/b6L1La5t

This is a big part of my server and I would appreciate any help possible. If you have any questions then feel free to ask and I will respond ASAP.

I'm running spigot 1.8.1 and the latest version of PEX.

**Comment by rewtie** [comment]
Please help? This is urgent

**Comment by iaxedu** [comment]
This is a common problem with pex 1.23.1 and 1.23.2. You could try 1.23 it works for my prison server I hope zml finds some time to work on the bukkit version of pex we need some love.

**Comment by Stormbow** [comment]
We have a 2nd case, similar to this that has reached the help forums; [posted by xAcrosonicx](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/techhelp/79548-pex-and-ezprestige/)

**Comment by rewtie** [comment]
zml, please respond. It's been 29 days and this issue is still not fixed. My server 100% relies on PEX to function properly, and this is causing some players to leave because their rank is being reset.

**Comment by zml2008** [comment]
I think this is an issue with the caching data changes I made -- some people have reported success with a version of PEX that reverts the changes -- I just finished some big changes in the 2.x branch so I should be able to put out a new version

**Comment by zml2008** [comment]
The CachingData changes have been reverted as of 1.22.9 and 1.23.3. This issue should be fixed.
