### ISSUE TITLE
Without permits in the entire server.

### ISSUE THREAD

**Issue by Errorpermisionsex** [PEXPlugins/PermissionsEx#2028]
Without permits in the entire server.

Console : 

>pex user KotteLGMc group set Usuario
[13:20:47 INFO]: Error occurred with PermissionsEx! Please post it to https://gi
thub.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%
23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%2
3%23%23%0A%0A**Reason%3A**+While+CONSOLE+was+executing+%2Fpex%0A%0A**Stacktrace%
3A**%0A%60%60%60%0Ajava.lang.RuntimeException%3A+java.lang.NullPointerException%
0D%0A%09at+ru.tehkode.permissions.commands.CommandsManager.execute%28CommandsMan
ager.java%3A121%29%0D%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.onComm
and%28PermissionsEx.java%3A159%29%0D%0A%09at+org.bukkit.command.PluginCommand.ex
ecute%28PluginCommand.java%3A44%29%0D%0A%09at+org.bukkit.command.SimpleCommandMa
p.dispatch%28SimpleCommandMap.java%3A196%29%0D%0A%09at+org.bukkit.craftbukkit.v1
_7_R1.CraftServer.dispatchCommand%28CraftServer.java%3A542%29%0D%0A%09at+org.buk
kit.craftbukkit.v1_7_R1.CraftServer.dispatchServerCommand%28CraftServer.java%3A5
29%29%0D%0A%09at+net.minecraft.server.v1_7_R1.DedicatedServer.aw%28DedicatedServ
er.java%3A286%29%0D%0A%09at+net.minecraft.server.v1_7_R1.DedicatedServer.u%28Ded
icatedServer.java%3A251%29%0D%0A%09at+net.minecraft.server.v1_7_R1.MinecraftServ
er.t%28MinecraftServer.java%3A545%29%0D%0A%09at+net.minecraft.server.v1_7_R1.Min
ecraftServer.run%28MinecraftServer.java%3A457%29%0D%0A%09at+net.minecraft.server
.v1_7_R1.ThreadServerApplication.run%28SourceFile%3A617%29%0D%0ACaused+by%3A+jav
a.lang.NullPointerException%0D%0A%09at+ru.tehkode.permissions.backends.FileBacke
nd.getRegisteredUsers%28FileBackend.java%3A196%29%0D%0A%09at+ru.tehkode.permissi
ons.PermissionBackend.getUsers%28PermissionBackend.java%3A203%29%0D%0A%09at+ru.t
ehkode.permissions.PermissionManager.getUsers%28PermissionManager.java%3A144%29%
0D%0A%09at+ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoComplet
ePlayerName%28PermissionsCommand.java%3A106%29%0D%0A%09at+ru.tehkode.permissions
.bukkit.commands.PermissionsCommand.autoCompletePlayerName%28PermissionsCommand.
java%3A73%29%0D%0A%09at+ru.tehkode.permissions.bukkit.commands.UserCommands.user
SetGroup%28UserCommands.java%3A520%29%0D%0A%09at+sun.reflect.NativeMethodAccesso
rImpl.invoke0%28Native+Method%29%0D%0A%09at+sun.reflect.NativeMethodAccessorImpl
.invoke%28Unknown+Source%29%0D%0A%09at+sun.reflect.DelegatingMethodAccessorImpl.
invoke%28Unknown+Source%29%0D%0A%09at+java.lang.reflect.Method.invoke%28Unknown+
Source%29%0D%0A%09at+ru.tehkode.permissions.commands.CommandsManager%24CommandBi
nding.call%28CommandsManager.java%3A252%29%0D%0A%09at+ru.tehkode.permissions.com
mands.CommandsManager.execute%28CommandsManager.java%3A114%29%0D%0A%09...+10+mor
e%0D%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermi
ssions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+perm
issions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+databas
e+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0D%0A++Usuario%3A%0D%0A++++default%3A+tr
ue%0D%0A++++permissions%3A%0D%0A++++-+essentials.mail%0D%0A++++-+scs.use%0D%0A++
++-+essentials.msg%0D%0A++++-+1vs1.arena.*%0D%0A++++-+authme.login%0D%0A++++-+au
thme.register%0D%0A++++-+authme.logout%0D%0A++++-+authme.unregister%0D%0A++++-+a
uthme.changepassword%0D%0A++++-+tntrun.game%0D%0A++++-+-bukkit.command.plugins%0
D%0A++++-+-bukkit.command.help%0D%0A++++-+-playerheads.canbehead%0D%0A++++-+-pla
yerheads.canlosehead%0D%0A++++-+-playerheads.canbeheadmob%0D%0A++++-+essentials.
sethome%0D%0A++++-+essentials.delhome%0D%0A++++-+essentials.home%0D%0A++++-+esse
ntials.warp*%0D%0A++++-+essentials.spawn%0D%0A++++-+essentials.warp%0D%0A++++-+e
ssentials.warps%0D%0A++++-+essentials.pay%0D%0A++++-+essentials.tpa*%0D%0A++++-+
essentials.balance%0D%0A++++-+essentials.balance.others%0D%0A++++-+essentials.ba
lancetop%09%0D%0A++++-+essentials.eco%0D%0A++++-+essentials.pay%0D%0A++++-+essen
tials.pay.multiple%0D%0A++++-+essentials.sell%0D%0A++++-+essentials.setworth%0D%
0A++++-+plotme.use.claim%0D%0A++++-+plotme.use.auto%0D%0A++++-+plotme.use.home%0
D%0A++++-+plotme.use.biome%0D%0A++++-+plotme.use.clear%0D%0A++++-+plotme.use.add
%0D%0A++++-+plotme.use.remove%0D%0A++++-+plotme.limit.1%0D%0A++++-+plotme.use%0D
%0A++++build%3A+true%0D%0A++++prefix%3A+%27%26b%27%0D%0A++Creador%3A%0D%0A++++pr
efix%3A+%27%26f%5B%264%26lSupremo%26f%5D+%26c%27%0D%0A++++Suffix%3A+%27%26a%27%0
D%0A++++inheritance%3A%0D%0A++++-+Miembro%0D%0A++++permissions%3A%0D%0A++++-+%27
*%27%0D%0A++Admin%3A%0D%0A++++prefix%3A+%27%26f%5B%264Admin%26f%5D+%26c%27%0D%0A
++++Suffix%3A+%27%26c%27%0D%0A++++inheritance%3A%0D%0A++++-+Miembro%0D%0A++++per
missions%3A%0D%0A++++-+Essentials.*%0D%0A++++-+worldguard.*%0D%0A++++-+WorldEdit
.*%0D%0A++++-+lagg.*%0D%0A++++-+frame.*%0D%0A++++-+lotme.*%0D%0A++++-+nametag.gr
oup.Admin%0D%0A++Moderador%3A%0D%0A++++prefix%3A+%27%26f%5B%266%26lModerador%26f
%5D+%266%27%0D%0A++++Suffix%3A+%27%26e%27%0D%0A++++inheritance%3A%0D%0A++++-+Mie
mbro%0D%0A++++permissions%3A%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.msg
.color%0D%0A++++-+essentials.chat.color%0D%0A++++-+essentials.signs.color%0D%0A+
+++-+essentials.chat.magic%0D%0A++++-+essentials.chat.format%0D%0A++++-+essentia
ls.helpop.receive%0D%0A++++-+essentials.kick%0D%0A++++-+essentials.kick.exempt%0
D%0A++++-+essentials.kick.notify%0D%0A++++-+essentials.kickall%0D%0A++++-+essent
ials.ban%0D%0A++++-+essentials.hat%0D%0A++++-+essentials.nick%0D%0A++++-+essenti
als.repair%0D%0A++++-+essentials.firework%0D%0A++++-+essentials.firework.fire%0D
%0A++++-+essentials.unban%0D%0A++++-+nametag.group.Mod%0D%0A++VIPiron%3A%0D%0A++
++prefix%3A+%27%26a%5B%262VIP+%267Iron%26a%5D+%26a%27%0D%0A++++Suffix%3A+%27%26b
%27%0D%0A++++inheritance%3A%0D%0A++++-+Miembro%0D%0A++++permissions%3A%0D%0A++++
-+essentials.hat%0D%0A++++-+essentials.msg.color%0D%0A++++-+essentials.chat.magi
c%0D%0A++++-+essentials.chat.format%0D%0A++++-+essentials.chat.color%0D%0A++++-+
essentials.signs.color%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.sethome.4
%0D%0A++++-+plotme.limit.2%0D%0A++++-+nametag.group.Vip1%0D%0A++++-+essentials.k
its.vip%0D%0A++++-+essentials.afk%0D%0A++VIPgold%3A%0D%0A++++prefix%3A+%27%26a%5
B%262VIP+%266Gold%26a%5D+%26a%27%0D%0A++++Suffix%3A+%27%26b%27%0D%0A++++inherita
nce%3A%0D%0A++++-+Miembro%0D%0A++++permissions%3A%0D%0A++++-+essentials.hat%0D%0
A++++-+essentials.nick%0D%0A++++-+essentials.msg.color%0D%0A++++-+essentials.cha
t.magic%0D%0A++++-+essentials.chat.format%0D%0A++++-+essentials.chat.color%0D%0A
++++-+essentials.signs.color%0D%0A++++-+essentials.sethome.6%0D%0A++++-+plotme.l
imit.3%0D%0A++++-+nametag.group.Vip2%0D%0A++++-+essentials.kits.vip2%0D%0A++++-+
essentials.afk%0D%0A++VIPdiamond%3A%0D%0A++++prefix%3A+%27%26b%5B%262VIP+%263DIA
MOND%26b%5D+%26b%27%0D%0A++++Suffix%3A+%27%26b%27%0D%0A++++inheritance%3A%0D%0A+
+++-+Miembro%0D%0A++++permissions%3A%0D%0A++++-+essentials.hat%0D%0A++++-+essent
ials.heal%0D%0A++++-+essentials.nick%0D%0A++++-+essentials.msg.color%0D%0A++++-+
essentials.chat.magic%0D%0A++++-+essentials.chat.format%0D%0A++++-+essentials.ch
at.color%0D%0A++++-+essentials.signs.color%0D%0A++++-+essentials.fly%0D%0A++++-+
essentials.repair%0D%0A++++-+essentials.sethome.8%0D%0A++++-+plotme.limit.4%0D%0
A++++-+nametag.group.Vip3%0D%0A++++-+essentials.kits.vip3%0D%0A++++-+essentials.
afk%0D%0A++Eventovip%3A%0D%0A++++prefix%3A+%27%26b%5BVIP+Supremo%26b%5D+%26b%27%
0D%0A++++Suffix%3A+%27%26b%27%0D%0A++++inheritance%3A%0D%0A++++-+Miembro%0D%0A++
++permissions%3A%0D%0A++++-+essentials.hat%0D%0A++++-+essentials.heal%0D%0A++++-
+essentials.nick%0D%0A++++-+essentials.msg.color%0D%0A++++-+essentials.chat.magi
c%0D%0A++++-+essentials.chat.format%0D%0A++++-+essentials.chat.color%0D%0A++++-+
essentials.signs.color%0D%0A++++-+essentials.fly%0D%0A++++-+essentials.repair%0D
%0A++++-+essentials.repair.all%0D%0A++++-+essentials.repair.armor%0D%0A++++-+ess
entials.repair.enchanted%0D%0A++++-+essentials.sethome.10%0D%0A++++-+plotme.limi
t.5%0D%0A++++-+nametag.group.Vip4%0D%0A++++-+essentials.kits.eventvip%0D%0A++++-
+essentials.afk%0D%0A++YouTuber%3A%0D%0A++++prefix%3A+%27%266%5BYT%5D+%266%27%0D
%0A++++inheritance%3A%0D%0A++++-+Miembro%0D%0A++++permissions%3A%0D%0A++++-+esse
ntials.msg.color%0D%0A++++-+essentials.chat.magic%0D%0A++++-+essentials.chat.for
mat%0D%0A++++-+essentials.chat.color%0D%
[13:20:47 INFO]: 0A++++-+essentials.signs.color%0D%0A++++-+nametag.group.YouTube
r%0D%0A%60%60%60%0A. Full error:
java.lang.RuntimeException: java.lang.NullPointerException
        at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManag
er.java:121)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.j
ava:159)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:19
6)
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServe
r.java:542)
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchServerCommand(Craf
tServer.java:529)
        at net.minecraft.server.v1_7_R1.DedicatedServer.aw(DedicatedServer.java:
286)
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:2
51)
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:5
45)
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java
:457)
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:6
17)
Caused by: java.lang.NullPointerException
        at ru.tehkode.permissions.backends.FileBackend.getRegisteredUsers(FileBa
ckend.java:196)
        at ru.tehkode.permissions.PermissionBackend.getUsers(PermissionBackend.j
ava:203)
        at ru.tehkode.permissions.PermissionManager.getUsers(PermissionManager.j
ava:144)
        at ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoComplet
ePlayerName(PermissionsCommand.java:106)
        at ru.tehkode.permissions.bukkit.commands.PermissionsCommand.autoComplet
ePlayerName(PermissionsCommand.java:73)
        at ru.tehkode.permissions.bukkit.commands.UserCommands.userSetGroup(User
Commands.java:520)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(C
ommandsManager.java:252)
        at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManag
er.java:114)

Help!
----------------------------------------------
When he went in also it is the same.

**Comment by zml2008** [comment]
Update to the latest version of PEX.
