### ISSUE TITLE
Timed Permissions

### ISSUE THREAD

**Issue by CreepyCrawlers** [PEXPlugins/PermissionsEx#2029]
I am currently trying to set up a Towny server with a few permissions for staff, etc and things like that but I can't seem to add Timed permissions. Well, I can add them, They work, but when the person logs off, the permission goes away and when they log back on, they can't do that command anymore. Is this a glitch or a bug or am I just not doing them correctly? I enter the timed permission and it works, until they log out. Could I have some help with this?

**Comment by zml2008** [comment]
Timed permissions are intentionally transient. What you are probably looking for are timed groups -- those are stored but expire after a certain amount of time as well.

**Comment by CreepyCrawlers** [comment]
What I am trying to do is like, Lets say someone donates, They get /pet for 30 days, How can I do that?

**Comment by zml2008** [comment]
Create a group that has the permission for pet, then add the player to that group for 30 days. Take a look at the command reference for more information on the specific command arguments.

**Comment by CreepyCrawlers** [comment]
I have and I don't see anywhere where I could add a player to a group for a certain amount of time? I would have to keep tally of who I added, When I added them, and what I added them too.

**Comment by CreepyCrawlers** [comment]
Is there a way I can add a player to a group for 30 days and it removes them automatically?

**Comment by CreepyCrawlers** [comment]
I see where we can add timed permissions to groups but that won't do me any good.

**Comment by zml2008** [comment]
`pex user <user> group add <group> [world] [lifetime]`

lifetime is the duration

**Comment by CreepyCrawlers** [comment]
Ahh... Thanks.

**Comment by CreepyCrawlers** [comment]
Okay, So is that lifetime in Seconds, I tried to do 30 seconds to test it and it gave me 1432507403 seconds. I tried to calculate what that was but it gave me a weird number. Sorry for all the questions. I just need this to work.

**Comment by zml2008** [comment]
That's the time from the epoch to when the group expires in seconds

**Comment by CreepyCrawlers** [comment]
Okay because I typed 30 and it gave me that weird number.

**Comment by CreepyCrawlers** [comment]
Okay. I use your permission and it gives me the 1432507403 number for that many seconds when I do 30. Why does it do that?

**Comment by CreepyCrawlers** [comment]
Here is a clear overview of what I am trying to do. I am trying to give a donator rank, /pet. I only want them to have it for 30 days. I can't seem to get it where that one rank only has it for 30 days and another rank has it for 60 days. Could I get help on that?

**Comment by zml2008** [comment]
This explains what that time means: https://en.wikipedia.org/wiki/Unix_time

create more groups

**Comment by CreepyCrawlers** [comment]
Okay. I'll just tally and do all of that. That stuff is confusing me and it's really making me mad. Thanks anyway.

**Comment by CreepyCrawlers** [comment]
Well, Let me ask this. It would make me understand it more.

If I am entering this into my commands, pex user Greatoz05 group add Pet New 2592000

What would I enter so I could give this person the pet command for 30 days?
