### ISSUE TITLE
Pex doesnt add Users to the file

### ISSUE THREAD

**Issue by Alakryn** [PEXPlugins/PermissionsEx#2030]
So I have a Server and downloaded the latest version of pex. Everything works perfectly except of one thing. New Users are not able to find in the permissions.yml in the plugin folder. Their prefix from their group is in the chat but they dont have the rights of the group that is displayed. 
Normally when a new User joines the server the plugin must add this:

  cb4544c6-9bff-4741-9f99-a7fd560a719e (Minecraft UUID):
    group:
    - default
    options:
      name: Minecraftname

But this doesnt happen.
I must search every users UUID by myself and add them in the permissions.yml file manually.
Please help me to solve this problem.

**Comment by zml2008** [comment]
use the ingame commands to edit user permissions

**Comment by Alakryn** [comment]
i dont want to edit the user permissions. i want that users were added automatically to the user list.

**Comment by Stormbow** [comment]
If your permissions.yml file contains a group which is "default: true", all users joining the server will be put into that group.

NOTE: The permissions.yml file is not going to show the user on the users list with the default: true group listed.  This is working as intended.  It is so you (server owners) do not have to manually move hundreds or thousands of users to a different group if the "default: true" group ever changes.
