### ISSUE TITLE
Pex doing http lookups for UUID on main thread

### ISSUE THREAD

**Issue by PhanaticD** [PEXPlugins/PermissionsEx#2031]
http://pastebin.com/XFcyyL2u

Server was having a network outage, due to bungee being on another box normally this wouldn't be a problem but when adding a player to a group it crashed the server, also pretty sure this shouldn't generally be done anyway

**Comment by zml2008** [comment]
```
@zml	PhanaticD: that is unfortunately a limitation of the API CraftBukkit exposes to us in looking up player names. 
```
This is no longer an issue in the PEX for Sponge -- we only look up against cached names there.
