### ISSUE TITLE
https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2Fb37f4ae37f301df2cf65%29%0A

### ISSUE THREAD

**Issue by Fefko** [PEXPlugins/PermissionsEx#2035]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/b37f4ae37f301df2cf65)

**Comment by nikosgram13** [comment]
What is the version of PEX?

BTW nice title. :+1: ^^

**Comment by nikosgram13** [comment]
You are using GroupManager and PEX together.

If you want to running normally your server, remove one of them. Select or PEX or GroupManager.

**Comment by nikosgram13** [comment]
BTW nice title! :+1:

**Comment by zml2008** [comment]
You are also using extremely outdated versions of both Bukkit and PermissionsEx. These versions are no longer supported, so please upgrade.

Your main issue with PEX specifically is that your groups section has to start with `groups:`, not `Groups:`
