### ISSUE TITLE
Switching to SQL Backend Fails [Follow up of Issue #2022]

### ISSUE THREAD

**Issue by willies952002** [PEXPlugins/PermissionsEx#2038]
Hello again,
  After extending the watchdog timeout to a value of 300, I am now getting the following error: http://paste.ubuntu.com/11448006/

  There are other plugins on the same server that are connecting to the same database that are working fine and what is getting me confused is the fact that PermissionsEx is the only plugin that is having issues.

  PermissionsEx Configuration (backend set back to "file"): http://paste.ubuntu.com/11448024/

Thank you in advanced.
~ willies952002 ~

**Comment by zml2008** [comment]
That error is from a connection timeout, which is not something PEX has control over. Make sure your database address, username, and password are correct.
