### ISSUE TITLE
Player having '*' permission after joining

### ISSUE THREAD

**Issue by Flexo013** [PEXPlugins/PermissionsEx#2039]
### Description ###

Somehow a new player who joined the server got the '*' permission once he joined. The name of the player is question is The_Tauren
### Detailed Information ###

The only error we got [Is available here](https://gist.github.com/fb81ed485d78716da36a)

**Comment by Stormbow** [comment]
You have no users in your permissions.yml file named "The_Tauren".

**Comment by Flexo013** [comment]
I have figured out the issue. The player spawned in a command block containing the command `/pex user The_Tauren add *` and activated it. Somehow this did not show up in console logs.

It is also possible that this error was caused by our bungee sync plugin, that did a promotion twice at almost the same moment.

**Comment by zml2008** [comment]
oh that sounds dangerous :/ unfortunately unless you switch to Sponge (where command blocks can get permissions like a user), command blocks can't really be restricted. However, seems like a good warning to have somewhere.

**Comment by Flexo013** [comment]
The easy fix is to just disable command-blocks in the server.properties, until this issue is fixed. I'm not sure, but it might already be fixed in one of the recent security updates that Mojang did. The server was running 1.8 when this occurred, not 1.8.1 or higher. So maybe this is no longer an issue.

**Comment by zml2008** [comment]
Hopefully the mojang stuff fixes this, though I think most of those security fixes were related to signs.
