### ISSUE TITLE
pex unable

### ISSUE THREAD

**Issue by snive1501** [PEXPlugins/PermissionsEx#2040]
what should I do , he says this ?

**Comment by snive1501** [comment]
[16:01:37 INFO]: [PermissionsEx] Initializing file backend
[16:01:37 ERROR]: [PermissionsEx]
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================

**Comment by snive1501** [comment]
groups:
default:
options:
default: false
permissions:
- modifyworld.*
visitor:
default: true
prefix: '&a(visitor)&f'
inheritance:
- default
permissions:
- essentials.spawn
- essentials.seen
- essentials.list
- essentials.tpa
- essentials.tpahere
- essentials.tpaccept
- essentials.tpdeny
- essentials.msg
- essentials.signs.use.warp
- essentials.afk.kickexempt
- essentials.balance
- essentials.helpop
- essentials.ban.notify
- essentials.back
- essentials.signs.use.heal
options:
rank: ''
recoder:
default: false
prefix: '&e(recoder)&f'
inheritance:
- visitor
permissions:
- essentials.fly
options:
rank: ''
moderator:
default: false
prefix: '&b(moderator)&f
inheritance:
- visitor
- recoder
permissions:
- essentials.ban
- essentials.tempban
- essentials.mute
- essentials.kick
- essentials.afk
- chatmanagerplus.mute
- chatmanagerplus.clearchat.all
- chatmanagerplus.broadcast
options:
rank: ''
admin:
default: false
prefix: '&a(admin)&f'
permissions:
- '*'
options:
rank: ''
owner:
default: false
prefix: '&4(owner)&f'
permissions:
- '*'
options:
rank: ''

**Comment by snive1501** [comment]
What am I doing wrong ?

**Comment by Stormbow** [comment]
Use [Pastebin](http://pastebin.com to post your permissions.yml file.

After you post that, I will take a look at it for errors.

**Comment by zml2008** [comment]
Closing due to no response after a month.
