### ISSUE TITLE
It says, "An internal error occurred while attempting to perform this command." Could you help?

### ISSUE THREAD

**Issue by Nebulix1** [PEXPlugins/PermissionsEx#2042]
When I do /commandstore, it does not work.

01.06 08:00:07 [Server] INFO ... 15 more
01.06 08:00:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at com.sevlon.PurchaseCommands.PurchaseCommands.onCommand(PurchaseCommands.java:113) ~[?:?]
01.06 08:00:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:135) ~[?:?]
01.06 08:00:07 [Server] INFO at org.bukkit.permissions.PermissibleBase.isPermissionSet(PermissibleBase.java:50) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO Caused by: java.lang.IllegalArgumentException: Permission name cannot be null
01.06 08:00:07 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]
01.06 08:00:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70]
01.06 08:00:07 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'commandstore' in plugin PurchaseCommands v0.1
### Detailed Information ###

[Is available here](https://gist.github.com/2c8da2629e0ddcb604c6)

**Comment by Stormbow** [comment]
Delete the empty "suffix" settings.

Delete Essentials VTeam City.  Only use the [official Essentials](http://dev.bukkit.org/bukkit-plugins/essentials/) download.

Which plugin exactly is "/commandstore" from?

**Comment by Nebulix1** [comment]
The plugin that /commandstore is from is Purchase Commands.

**Comment by zml2008** [comment]
Purchase Commands is broken -- it's checking a null permission.
