### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by BossfighterHD** [PEXPlugins/PermissionsEx#2045]
Ich habe ein Probelem.Bei mir erscheint wenn ich /pl eingebe das Plugin rot.Ich kann auch nichts mit den plugin machen

**Comment by BossfighterHD** [comment]
Ich habe ein Probelem.Bei mir erscheint wenn ich /pl eingebe das Plugin rot.Ich kann auch nichts mit den plugin machen

**Comment by Stormbow** [comment]
I tried to Google Translate this.  It did not go well.  (Though I can see it's a programming problem of some sort.)

English please?

**Comment by zml2008** [comment]
Original msg translated:
> I have a problem. When I run /pl the plugin comes up red. I also can't do anything with the plugin

I've got a bit of german, it's not great but I'll try to respond:

Tut mir leid, mein Deutsch is nicht so gut, aber vielleicht kann ich Ihnen helfen. Sie haben wahrscheinlich ein Fehler in Ihrer Konfiguration. Gebe das `permissions.yml` an http://yaml-online-parser.appspot.com. Wenn es einen Fehler in ihrer Server-Log gibt, dann können wir das auch ansehen, wenn Sie es hier kopieren (benutze bitte gist.github.com).

**Comment by zml2008** [comment]
No reply in a month, closing.
