### ISSUE TITLE
pex user <player> parent add group <group>

### ISSUE THREAD

**Issue by trorojoro** [PEXPlugins/PermissionsEx#2048]
When i use said command, the user is added to the group, but the new permissions doesn't seem to be available. I check the console, and this is what appears:

pex user trorojoro parent add group admin
[16:03:35] [Server thread/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.Sp
ongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:03:35] [Server thread/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.Sp
ongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:03:35] [Server thread/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.Sp
ongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:03:35] [Server thread/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.Sp
ongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:03:35] [Server thread/INFO]: Added parent group admin for subject user 1138e
445-ea7c-47dd-aea7-257bb0ae4aca/trorojoro in Global context

**Comment by trorojoro** [comment]
This also goes for when adding permission nodes through commands:

pex group admin perm test.permission true
[16:20:21] [pool-2-thread-6/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.
SpongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:20:21] [pool-2-thread-6/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.
SpongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:20:21] [pool-2-thread-6/INFO] [STDOUT]: [ninja.leaping.permissionsex.sponge.
SpongeMessageFormatter$PEXTranslation:get:161]: Getting for locale:no_NO
[16:20:21] [pool-2-thread-6/INFO]: Set permission test.permission=1 for subject
group admin in Global context

**Comment by zml2008** [comment]
So when you do /pex user trorojoro info or /pex group admin info, the changes do not appear?

**Comment by trorojoro** [comment]
Tested the rest of the commands as well. The permissions.json is updated, but the changes doesn't seem to take effect.

**Comment by trorojoro** [comment]
Not even when i give myself as user (instead of group) the perm "permissionsex.reload": -1

**Comment by zml2008** [comment]
just to confirm, you are using the latest build of PEX (from http://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/), yes?

**Comment by trorojoro** [comment]
Indeed. There is but one bit that seems to give/take permissions:
    "systems": {
        "default": [ {
            "permissions-default": 1
        } ]
    },
Setting this one to -1 seems to take away my vanilla permissions.

**Comment by zml2008** [comment]
yes, that is what that option does. I haven't experienced any issues with this on my side -- could you pastebin your entire permissions.json file?

**Comment by trorojoro** [comment]
Here you go:
http://pastebin.com/1GbWjnhF

**Comment by zml2008** [comment]
So I am not sure where you are getting your permissions from. PEX2 doesn't use the .* -- just the plain node does the same thing that used to (so giving `some.perm` now is the same as giving `some.perm` and `some.perm.*` in the past). Also, WE for Forge does not use Sponge permissions and not sure if pixelmon does.

The permissions-default setting doesn't go under permissions -- use the command /pex <user|group> <name> def true

-1/false explicitly sets to false, 1/true explicitly sets to true, 0 sets to none.

**Comment by trorojoro** [comment]
Well then. My bad for mixing those up. 
Thank you for taking the time to help me adress my problem!

**Comment by zml2008** [comment]
np, the kinds of questions you and other early users ask will help to create documentation to help the rest of the users to switch over from Bukkit PEX.
