### ISSUE TITLE
Maven Dependency 1.23.2-SNAPSHOT

### ISSUE THREAD

**Issue by Lightoner** [PEXPlugins/PermissionsEx#2050]
Hi,
When I try to get  the dependency of pex 1.23.2-SNAPSHOT it's say missing artifact:
```
<repository>
        <id>pex-repo</id>
        <url>http://pex-repo.aoeu.xyz/</url>
</repository>
<dependency>
      <groupId>ru.tehkode</groupId>
      <artifactId>PermissionsEx</artifactId>
      <version>1.23.2-SNAPSHOT</version>
</dependency>
```
But when I switch to the version 1.23.1-SNAPSHOT, it's work perfectly.
Thanks,

**Comment by zml2008** [comment]
Don't use PEX as a dependency, instead use Vault.

**Comment by Lightoner** [comment]
Is it possible to check if an offlineplayer has a permissions with uuid wth vault ? If it possible how ?

**Comment by nikosgram13** [comment]
@Lightoner you can use a OfflinePlayer as (UUID Data) in Vault.
