### ISSUE TITLE
User timed permissions reset on relog.

### ISSUE THREAD

**Issue by TWSSYesterday** [PEXPlugins/PermissionsEx#2057]
PermissionsEx v1.23.2
Vault 1.5.3-b37
Timed permissions for users work until they relog.
I saw an issue closed because groups were working, I don't want to and can't use group time permissions due to it being per user. 

Please let me know how fixing this goes :)

**Comment by zml2008** [comment]
Use timed groups -- a user can have multiple groups, just create a single timed group and add it to the user.

**Comment by TWSSYesterday** [comment]
Why is it not working for users? Surely that would be a much better way to do it...

**Comment by zml2008** [comment]
That's how it has always been. I think when I reimplement timed stuff in PEX2.0 it'll be for users too, but I'm not willing to make the major changes to the legacy 1.x codebase necessary for that feature.
