### ISSUE TITLE
New users don't get default permissions on server join

### ISSUE THREAD

**Issue by Cormso131** [PEXPlugins/PermissionsEx#2058]
I updated pex from bukkit 1.7.9 to spigot 1.8.7 and ever since new players on my server or players with no rank don't get the permissions in the deault group.

My permissions file: http://pastebin.com/sEDztJEL

**Comment by zml2008** [comment]
`default` should go under `options`

**Comment by Cormso131** [comment]
can't believe i missed that thanks!
