### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by raum266** [PEXPlugins/PermissionsEx#2059]
### Description ###

Getting an error during startup - The error requested I post it here. The plugin works just fine aside from the startup error. The only info I can find regarding this states that there was an 'incomplete update' to the database ... But we've only just started using this plugin.

[12:00:20] [pool-13-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vLCZJ. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'

### Detailed Information ###

http://pastebin.com/qYWtx98q

**Comment by Stormbow** [comment]
Your permissions.yml/SQL has 2 schema-version lines.  Keep only the line which is "schema-version: 1".

**Comment by Stormbow** [comment]
You gonna go cry to mommy on this site too?  LMFAO
