### ISSUE TITLE
permissionex error help

### ISSUE THREAD

**Issue by d4rkm4ster** [PEXPlugins/PermissionsEx#2061]
### Description ###

17:41:54 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
17:41:54 	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:266)
17:41:54 	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:226)
17:41:54 	at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:689)
17:41:54 	at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:671)
17:41:54 	at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:747)
17:41:54 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:72)
17:41:54 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:157)
17:41:54 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
17:41:54 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
17:41:54 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
17:41:54 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:442)
17:41:54 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:376)
17:41:54 	at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:344)
17:41:54 	at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:319)
17:41:54 	at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:275)
17:41:54 	at net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:175)
17:41:54 	at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:426)
17:41:54 	at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
17:41:54 Caused by: java.lang.reflect.InvocationTargetException
17:41:54 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
17:41:54 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
17:41:54 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
17:41:54 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
17:41:54 	at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:251)
17:41:54 	... 17 more
17:41:54 Caused by: ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
17:41:54 	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:261)
17:41:54 	at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:71)
17:41:54 	... 22 more
17:41:54 Caused by: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
17:41:54 found character 	'\t' that cannot start any token
17:41:54  in "<string>", line 5, column 1:
17:41:54     ^
17:41:54 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
17:41:55 	at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:44)
17:41:55 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149)
17:41:55 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:114)
17:41:55 	at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:24)
17:41:55 	at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:251)
17:41:55 	... 23 more
17:41:55 Caused by: while scanning for the next token
17:41:55 found character 	'\t' that cannot start any token
17:41:55  in "<string>", line 5, column 1:
17:41:55     ^
17:41:55 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
17:41:55 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
17:41:55 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:591)
17:41:55 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
17:41:55 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
17:41:55 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
17:41:55 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
17:41:55 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
17:41:55 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
17:41:55 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
17:41:55 	... 28 more

### Detailed Information ###

[Is available here](https://gist.github.com/65ac83d66fa3c98ac621)

**Comment by zml2008** [comment]
Syntax error in your permissions.yml -- you can't have tab characters anywhere -- replace them with 4 spaces. Check your configuration at http://yaml-online-parser.appspot.com
