### ISSUE TITLE
Major performance drop in 1.23.3

### ISSUE THREAD

**Issue by iaxedu** [PEXPlugins/PermissionsEx#2068]
Pex 1.23.3 on Spigot 1.8.3

Performance is horrible:
http://timings.aikar.co/?url=11756899

**Comment by zml2008** [comment]
1.23.3 removes a performance fix that some people were having issues with. If 1.23.2 worked better for you, feel free to downgrade (and disable the autoupdater in config.yml) -- reverting that performance fix was the only change in 1.23.3.

**Comment by iaxedu** [comment]
No version of PEX ever worked good for me sadly
