### ISSUE TITLE
/pex user <user> group set <group> SomeWorld Problem...

### ISSUE THREAD

**Issue by xiurobert** [PEXPlugins/PermissionsEx#2069]
Hey guys,
I saw on the PeX wiki that `/pex user <user> group set <group>` removes all other groups that user is in, but what if I add a world? Would it just remove all the groups the user is in __that particular world__ or would it remove all the groups __globally__? Please help!

**Comment by zml2008** [comment]
It'd just remove other groups in that world -- but world-specific groups override global groups when there is a difference in options/permissions given.

**Comment by xiurobert** [comment]
Ok. Thanks
