### ISSUE TITLE
NullPointerException on "/pex user <player>"

### ISSUE THREAD

**Issue by BlackBeltPanda** [PEXPlugins/PermissionsEx#2071]
### Description ###

A player complained about not having some of their permissions. When I tried to lookup the player up, I received an error.

### Detailed Information ###

[Is available here](https://gist.github.com/187b6d4fb97ce46ce76d)

**Comment by zml2008** [comment]
This happens sometimes  when commands are run on offline players, but I haven't been able to track it down. See if looking up the user by UUID works better.

**Comment by BlackBeltPanda** [comment]
It seems to have corrected itself after a server restart.
