### ISSUE TITLE
High timings

### ISSUE THREAD

**Issue by SecretlyJealous** [PEXPlugins/PermissionsEx#2072]
I'm wondering why my PCT tick is so high, I've got around 430/430 on my server and my permissions.yml file has nearly 6000 lines if that helps.
![pextimings](https://cloud.githubusercontent.com/assets/10485646/8336003/3b4cbcf8-1a99-11e5-8e66-cc4fd7a5c614.png)

**Comment by zml2008** [comment]
PEX precalculates a lot of things when the player logs in and occasionally has to write data, so login can take a longer time. To make this any faster requires more extensive changes to PEX's internal structure that are only practical in the rewrite for Sponge (which is in progress with mostly functional dev builds)
