### ISSUE TITLE
Bug SQL

### ISSUE THREAD

**Issue by ph1823** [PEXPlugins/PermissionsEx#2074]
Hello, error log : http://pastebin.com/EuVmLprD But another waiter(server) has the same configuration as that of this waiter(server) and the problem is not present. Thank your recipe. And sorry my english.

**Comment by zml2008** [comment]
Is the other server at a remote location? This looks like talking to the SQL database took too long, which is not controlled by PEX

btw: your english is fine, but waiter and server are only the same like in a restaurant, for computers it's just server (yeah, english is weird)

**Comment by ph1823** [comment]
It would thus come connection has the base(basis) of datum? And a part(party) of my translation is made by Reverso Thus sorry my english.. Here is my confiruation:
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: true
  createUserRecords: false
  backend: sql
  informplayers:
    changes: true
  basedir: plugins/PermissionsEx
  backends:
    sql:
      uri: mysql://mutu-315225.onet.domains/redbucke_site
      user: redbucke
      password: lLlb5BI@ENl!
      type: sql
updater: true
alwaysUpdate: false


And I delete(eliminate) the configuration his(her,its) fact the same thing. Allors that it is the basic(basal) dePermissionsEx configuration, but his(her,its) not crash not he(she,it) makes that read timed out at the end of 10min. Thank Your your recipe.

**Comment by zml2008** [comment]
Yeah, your sql connection is probably the problem here. If it's on some other server, that adds the time to get data from that location on the internet to the time it takes to get permissions.
