### ISSUE TITLE
Prefix don't work

### ISSUE THREAD

**Issue by stefvanschie** [PEXPlugins/PermissionsEx#2078]
For a long time we've had awesome prefixes on our server with permisionsex, but now the don't work, I tried reloading permissionsex, re-configuring it, but nothing works. Any solution?

**Comment by MrEminent42** [comment]
Post your permissions.yml and I can take a look.

**Comment by zml2008** [comment]
You've got a chat plugin installed, right? PEX is just data storage, you need a chat plugin to actually display the prefixes.

**Comment by budopey** [comment]
I have the same issue and using Towny Chat hooked with DeluxeChat and can't seem to get any placeholder to display a prefix. I even tried using Simple Prefix but it kept saying PermissionEx_Chat is using Vault for prefixes and is using that for prefix's. I didn't know there was a Pex_Chat? What is that about?

**Comment by zml2008** [comment]
you have to make the other groups inherit from the default group for prefixes to work.

`PermissionsEx_Chat` is how vault handles the chat options from PEX -- it's just an internal thing that still refers to PermissionsEx
