### ISSUE TITLE
Can't load PEX - Tried from 1.2.0 to 1.23 non works

### ISSUE THREAD

**Issue by VisualTech48** [PEXPlugins/PermissionsEx#2080]
30.06 22:22:42 [Server] INFO No new version available
30.06 22:22:41 [Server] INFO Checking for Updates ... 
30.06 22:22:41 [Server] INFO (database saving will now commence which might lock the server for a while)
30.06 22:22:41 [Server] INFO ... done!
30.06 22:22:41 [Server] INFO Post update factions_mplayer. Took 0ms. 0/0 changed.
30.06 22:22:41 [Server] INFO Pre update factions_mplayer.
30.06 22:22:41 [Server] INFO Upgrading from player name to player uuid...
30.06 22:22:41 [Server] INFO Saving Cachefile...
30.06 22:22:41 [Server] INFO Skipping Dbmojangapi datas since offline mode...
30.06 22:22:41 [Server] INFO Loading Registry datas...
30.06 22:22:41 [Server] INFO Loading Onlineplayer datas...
30.06 22:22:41 [Server] INFO Loading Cachefile datas...
30.06 22:22:41 [Server] Startup Done (2.495s)! For help, type "help" or "?"
30.06 22:22:41 [Multicraft] Skipped 47 lines due to rate limit (30/s)
30.06 22:22:40 [Server] INFO (world_the_end) Lava fire is blocked.
30.06 22:22:40 [Server] INFO (world_the_end) Lighters are PERMITTED.
30.06 22:22:40 [Server] INFO (world_the_end) TNT ignition is PERMITTED.
30.06 22:22:40 [Server] INFO Loaded configuration for world 'world_nether'
30.06 22:22:40 [Server] INFO (world_nether) Fire spread is UNRESTRICTED.
30.06 22:22:40 [Server] INFO (world_nether) Lava fire is blocked.
30.06 22:22:40 [Server] INFO (world_nether) Lighters are PERMITTED.
30.06 22:22:40 [Server] INFO (world_nether) TNT ignition is PERMITTED.
30.06 22:22:40 [Server] INFO Loaded configuration for world 'world'
30.06 22:22:40 [Server] INFO (world) Fire spread is UNRESTRICTED.
30.06 22:22:40 [Server] INFO (world) Lava fire is blocked.
30.06 22:22:40 [Server] INFO (world) Lighters are PERMITTED.
30.06 22:22:40 [Server] INFO (world) TNT ignition is PERMITTED.
30.06 22:22:40 [Server] INFO Enabling WorldGuard v5.9
30.06 22:22:40 [Server] INFO [Vault][Permission] PermissionsEx hooked.
30.06 22:22:40 [Server] INFO WEPIF: Using the Bukkit Permissions API.
30.06 22:22:40 [Server] INFO WEPIF: Using the Bukkit Permissions API.
30.06 22:22:40 [Server] INFO Disabling PermissionsEx v1.23.3
30.06 22:22:40 [Server] ERROR =================================================================================
30.06 22:22:40 [Server] ERROR As of version 1.23, PEX is only compatible with versions of Minecraft 1.8 or greater. Please downgrade to the most recent 1.22.x series version of PEX to continue.
30.06 22:22:40 [Server] ERROR =================================================================================
30.06 22:22:40 [Server] INFO Enabling PermissionsEx v1.23.3
30.06 22:22:40 [Server] ERROR Aborting enable!
30.06 22:22:40 [Server] ERROR Detected Bukkit build [v1_7_R4], but requires version [1.8] or greater!
30.06 22:22:40 [Server] INFO Version 1.8.19 is being enabled!  Yay!  (Core version 1.3.5)
30.06 22:22:40 [Server] INFO Enabling Lockette v1.8.19
30.06 22:22:40 [Server] INFO GetStaff successfully enabled.
30.06 22:22:40 [Server] INFO Enabling GetStaff v1.0
30.06 22:22:40 [Server] INFO Using com.sk89q.worldedit.bukkit.adapter.impl.CraftBukkit_v1_7_R4 as the Bukkit adapter
30.06 22:22:40 [Server] INFO WEPIF: Using the Bukkit Permissions API.
30.06 22:22:40 [Server] INFO Enabling WorldEdit v6.0;3342-78f975b9
30.06 22:22:40 [Server] INFO Preparing start region for level 2 (Seed: -516555792384317264)
30.06 22:22:39 [Server] INFO Preparing start region for level 1 (Seed: -1173211328039643144)
30.06 22:22:39 [Server] INFO Preparing start region for level 0 (Seed: -516555792384317264)
30.06 22:22:39 [Multicraft] Skipped 135 lines due to rate limit (30/s)
30.06 22:22:38 [Server] INFO Set PluginClassLoader as parallel capable
30.06 22:22:38 [Server] INFO ... 6 more
30.06 22:22:38 [Server] INFO Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
30.06 22:22:38 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
30.06 22:22:38 [Server] ERROR Could not load 'plugins/antiddos.jar' in folder 'plugins'
30.06 22:22:38 [Server] INFO ... 6 more
30.06 22:22:38 [Server] INFO Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
30.06 22:22:38 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-1649]
30.06 22:22:38 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
30.06 22:22:38 [Server] ERROR Could not load 'plugins/nohack.jar' in folder 'plugins'
30.06 22:22:38 [Server] INFO Starting Minecraft server on 85.114.128.116:25644
30.06 22:22:38 [Server] INFO Generating keypair
30.06 22:22:38 [Server] INFO Debug logging is disabled
30.06 22:22:38 [Server] INFO Using 4 threads for Netty based IO
30.06 22:22:38 [Server] INFO Server Ping Player Sample Count: 12
30.06 22:22:38 [Server] INFO This server is running CraftBukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
30.06 22:22:38 [Server] INFO Default game type: SURVIVAL
30.06 22:22:38 [Server] INFO Loading properties
30.06 22:22:38 [Server] INFO Starting minecraft server version 1.7.10
30.06 22:22:25 [Server] INFO The server will start in 10 seconds!
30.06 22:22:25 [Server] INFO You will get no support with this build unless you update from http://ci.md-5.net/job/Spigot/
30.06 22:22:25 [Server] INFO WARNING: This build is more than 2 days old and there are likely updates available!
30.06 22:22:25 [Server] INFO *** Any bug reports not running the very latest versions of these softwares will be ignored ***
30.06 22:22:25 [Server] INFO Please report any such issues to http://www.spigotmc.org/, stating your client, server, and if applicable BungeeCord versions.
30.06 22:22:25 [Server] INFO *** It is imperative that backups be taken before running this build on your server! ***
30.06 22:22:25 [Server] INFO This Spigot build supports Minecraft clients both of versions 1.7.x and of 1.8.x.
30.06 22:22:25 [Multicraft] Loaded config for "Mod: Spigot"
30.06 22:22:25 [Multicraft] Starting server!
30.06 22:22:25 [Multicraft] Loading server properties
30.06 22:22:25 [Multicraft] Server stopped
30.06 22:22:25 [Multicraft] Server shut down
30.06 22:22:24 [Server] INFO Stopping server
30.06 22:22:24 [Server] INFO Saving chunks for level 'world_the_end'/The End
30.06 22:22:24 [Server] INFO Saving chunks for level 'world_nether'/Nether
30.06 22:22:24 [Server] INFO Saving chunks for level 'world'/Overworld
30.06 22:22:24 [Server] INFO Saving worlds
30.06 22:22:24 [Server] INFO Saving players
30.06 22:22:24 [Server] INFO Disabling WorldEdit v6.0;3342-78f975b9
30.06 22:22:24 [Server] INFO GetStaff successfully disabled.
30.06 22:22:24 [Server] INFO Disabling GetStaff v1.0
30.06 22:22:24 [Server] INFO Disabled
30.06 22:22:24 [Server] INFO Deactivated integration with Vault
30.06 22:22:24 [Server] INFO Disabling MassiveCore v2.7.5
30.06 22:22:24 [Server] INFO Disabling Vault v1.5.3-b37
30.06 22:22:24 [Server] INFO Disabling Lockette v1.8.19
30.06 22:22:24 [Server] INFO Permissions file successfully reloaded
30.06 22:22:24 [Server] INFO [Vault][Chat] PermissionsEx_Chat un-hooked.
30.06 22:22:24 [Server] INFO [Vault][Permission] PermissionsEx un-hooked.
30.06 22:22:24 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
30.06 22:22:24 [Server] INFO Disabling PermissionsEx v1.20.3
30.06 22:22:24 [Server] INFO Disabling WorldGuard v5.9
30.06 22:22:24 [Server] INFO EditableSign version 1.2.7 is Disabled
30.06 22:22:24 [Server] INFO Disabling EditableSign v1.2.7
30.06 22:22:24 [Server] INFO Disabling ChestShop v3.8.7
30.06 22:22:24 [Server] INFO Disabling AuthMe v3.5-SNAPSHOT
30.06 22:22:24 [Server] INFO Disabled
30.06 22:22:24 [Server] INFO Disabling Factions v2.7.5
30.06 22:22:24 [Server] INFO Stopping server
30.06 22:22:24 [Server] INFO CONSOLE: Stopping the server..
30.06 22:22:24 [Server] INFO CONSOLE: Forcing save..

**Comment by zml2008** [comment]
>Disabling PermissionsEx v1.23.3
>30.06 22:22:40 [Server] ERROR =================================================================================
>30.06 22:22:40 [Server] ERROR As of version 1.23, PEX is only compatible with versions of Minecraft 1.8 or greater. Please downgrade to the most recent 1.22.x series version of PEX to continue.
30.06 22:22:40 [Server] ERROR =======================================

reading is a useful skill

**Comment by VisualTech48** [comment]
Yea if only that worked. I tied all the 1.22 versions
