### ISSUE TITLE
Timed Permissions Expire on reload

### ISSUE THREAD

**Issue by CaptAdric** [PEXPlugins/PermissionsEx#2082]
I've had a look around an it seems issues like this have happened before but I can't see anything that fixes the issue for me. here is some details

Pex version: 1.23.3

the commands for the timed permission is run from the console and restart the server the user no longer has the permissions.

is there anyfix or way around this issue that can be done on a paid hosting server on multicraft. 

thanks

**Comment by VisualTech48** [comment]
I'm using Multicraft too. Go to your console and see if PEX has loaded at all

**Comment by zml2008** [comment]
Timed permissions are only stored in-memory. If you want something that is saved, use timed groups.
