### ISSUE TITLE
PermissionsEx 1.8 bukkit won't work

### ISSUE THREAD

**Issue by ipauploader** [PEXPlugins/PermissionsEx#2084]
So I filled everything out I eve got chat manager and tryed multiple of them and countless times made new permission files and it still wont work 

http://pastebin.com/bM9isisH  

I try to see if it was just the prefixs not showing up but when my friend tryed a default command it still would say you can't do this command.

**Comment by zml2008** [comment]
run /pex report and paste the link it gives you here.

**Comment by ipauploader** [comment]
I don't have access because I don't have enough permissions but I am the owner.

**Comment by zml2008** [comment]
run it from console

**Comment by ipauploader** [comment]
I did it says I need a github account

**Comment by zml2008** [comment]
well you have a github account, because you are commenting here, but that's not necessary -- just paste the link...

**Comment by ipauploader** [comment]
the problem is i'm not hosting the server cubed host is so I think thats why i'm trying to put the same plugins and permission file on a server on my computer.

**Comment by ipauploader** [comment]
on second thought its taking a long time to download.

**Comment by zml2008** [comment]
or you could just paste the link it gives you...

**Comment by ipauploader** [comment]
wow sorry I just found out it gave me a link after sorry about that 01.07 21:21:41 [Server] INFO Fill in the information at http://git.io/vtA7C

**Comment by ipauploader** [comment]
Here is the link sorry https://gist.github.com/652255ed11d2d6026904)

**Comment by zml2008** [comment]
Looks like you don't have any inheritance set up, and your default group has only modifyworld permissions. You'd have to add inheritance (look at the wiki for information how). Make sure you have a chat plugin that can get data from PEX -- essentialschat does this, probably others.

**Comment by ipauploader** [comment]
can't find essentialschat for bukkit

**Comment by zml2008** [comment]
then look harder
