### ISSUE TITLE
PEX MySQL Unicode Problem

### ISSUE THREAD

**Issue by BlackBeltPanda** [PEXPlugins/PermissionsEx#2086]
PermissionsEx version: 1.23.3
Spigot version: 1.8.3

Steps to reproduce the problem:
1. Setup PEX to use MySQL as backend
2. Change your prefix with command "/pex user <your username> prefix "&c★Mod★"
3. Execute command "/pex reload" or relog.

What happens:
Prefix "&c★Mod★" is changed to "&c?Mod?". The change occurs in the MySQL database.

After changing prefix: http://i.gyazo.com/7023b5e685d0bec82c575e0ec0acb8c5.png
After relogging/reload PEX: http://i.gyazo.com/96429e9d984268114180135782a2f6f7.png
Database entry: http://i.gyazo.com/675bd7992b82cf40d34f8951ca27668a.png

**Comment by zml2008** [comment]
This is most likely a configuration problem on your mysql sever. Make sure the connection encoding is properly set to utf-8 in your my.cnf.
