### ISSUE TITLE
Per Server permission nodes

### ISSUE THREAD

**Issue by macdja38** [PEXPlugins/PermissionsEx#2087]
you currently have per world permission nodes which come in incredibly useful however in my server network I would like to use one SQL database for all my servers which is usually fine as I can add permissions for a map called spleef without problems. The feature I'm looking for would involve each server receiving a unique name in it's config file that would allow you to do per server permissions that are active on that server but not others. I believe this would be useful most of your larger users.

**Comment by zml2008** [comment]
This is already supported in PEX2.0 with the `server-tags` context type. These are tags that can be applied to a set of permissions to control when they take effect (essential a more generalized form of per-world permissions). Documentation will be coming soon
