### ISSUE TITLE
PEX & MySQL Database Issue 

### ISSUE THREAD

**Issue by Bihukabazi** [PEXPlugins/PermissionsEx#2089]
Hello,

In consideration of an elaborately created post I made in permissionsex forum, I show the link here, in hope of getting any informations or help from experienced users/developers.

http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/techhelp/80839-pex-mys-ql-database-issue/

thanks in advance.

**Comment by zml2008** [comment]
The id is handled internally by your database -- we don't really control it. Since all of the database handling is being rewritten for PEX2, this isn't really something I'm too worried about (unless it is causing issues for you).

**Comment by Bihukabazi** [comment]
Thanks for the reply master! I will just handle it by dropping permission files from my database when they stack to high and import the permissions again from .yml... At least it caused no noticeable trouble yet.
