### ISSUE TITLE
Can't kick Co-Owner

### ISSUE THREAD

**Issue by TheMagicDar** [PEXPlugins/PermissionsEx#2091]
Help I'm having a problem with PEX. I am the owner of the server and I tried to kick the Co-Owner as a test and it won't let me.
Here is my permissions.yml file:

] Edit by Stormbow: moved wall of text to Pastebin: http://pastebin.com/5veqrS8w Link will be active for one month. [

**Comment by macdja38** [comment]
This is probably not the right place for this but since you asked, give the people you want to be able to kick people essentials.kick so... In this case give that to yourself. You can also give yourself essentials.* if you want all essentials permissions

**Comment by Stormbow** [comment]
First and foremost, your permissions.yml file is formatted incorrectly.  Follow [this example](http://pastebin.com/8ZSHxauG).

As to kicking the Co-Owner, you've exempted them from being able to be kicked by giving them the wildcard '*' node.  You will have to negate the exemption above the wildcard with - -essentials.kick.exempt.  (And probably - -essentials.afk.kickexempt so they can be auto-kicked by the server for being AFK too long.)
