### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Agazed** [PEXPlugins/PermissionsEx#2093]
How do you convert last login time to the actual date?

last-login-time: '1436847683'

**Comment by Stormbow** [comment]
I __THINK__ that's recorded in milliseconds, like timed permissions are recorded in PEX, so 1436847683 milliseconds would be 16.6302 days ago.

You'd need zml to verify that though.

**Comment by macdja38** [comment]
I think that's a count in seconds starting from a very very long time ago. To use it you need to subtract it from the current "time" log in then out yourself and compare it to that lastloggin time.

**Comment by zml2008** [comment]
yeah, it's seconds since the epoch/UNIX time -- http://www.epochconverter.com/ should handle conversion for you as well.
