### ISSUE TITLE
[Feature Request] Conditional/dependent group based permissions

### ISSUE THREAD

**Issue by Kerrus** [PEXPlugins/PermissionsEx#2094]
Something that's come up recently on a server I work with is the lack of ability to easily set up conditional permissions.

I want to be able to flag a permission in a group as being dependent on another group- so for example:

John is in a group called 'Knight' and a group called 'faction1'. Several permissions in 'faction1' are dependent on their user being in a specific rank ranging from 'knight', 'cleric', 'fighter', to 'wizard'. 

If John is in 'knight and 'faction1' then the knight-specific permissions in faction1 are enabled for him. But if another user, say, Mary, is in 'faction2' and 'knight', she doesn't have identical permissions to John because faction2's dependent permissions are different. 

With such a system it would be a lot easier to handle rpg style advancement on a server because we can set prerequisites for permissions- you must be in rank X, AND in rank Z to have this permission.

Thoughts, criticisms, feasibility?

**Comment by Stormbow** [comment]
You could easily define them all as groups and have the users in different multiple groups.
```
groups:
  default:
    permissions:[]
    options:
      defult: 'true'
  knight:
    permissions:
    - -stuff.negated.nodes
    - stuff.*
  faction1:
    permissions:
    - -otherstuff.negated.nodes
    - otherstuff.*
  faction2:
    permissions:
    - -stillotherstuff.negated.nodes
    - stillotherstuff.*
schema-version: 1
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: John
    group:
    - Knight
    - Faction1
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: Mary
    group:
    - Knight
    - Faction2

**Comment by zml2008** [comment]
Additionally, you can have groups that inherit from both groups which you assign to players.

I'm not sure it would be possible to actually have permissions be given by a combination of groups -- you'd run into the issue of yet another potentially infinite loop of calculations, and make calculations even more expensive than they already are.

I think the solutions presented here are reasonable workarounds, so I'm going to close this.
