### ISSUE TITLE
Can't Break/Place Blocks

### ISSUE THREAD

**Issue by RoBaMe** [PEXPlugins/PermissionsEx#2095]
HI! I'm a server Admin and we have a problem. Pex Preventing Players from placing and breaking block. here our permission.yml:

] Edit by Stormbow: Removed permissions.yml paste since the formatting was ruined anyway. Please post it to [Pastebin](http://pastebin.com) and leave a link in this thread. [

**Comment by Stormbow** [comment]
actually, your file doesn't work at all because of several major errors in the formatting.  (And use Pastebin to post your file contents.  The formatting is ruined by posting it here.)

• Schema-version line goes above the "users:" section.  This is the more important of the 2 errors mentioned here.

• Empty permission sets should be "permissions: []" not what you have shown above.

Once you've corrected these 3 errors (Pastebin being important too), I can look at your file for additional errors, but I'm fairly certain fixing the 2 bullet points above will solve your problem.

**Comment by RoBaMe** [comment]
@Stormbow ok thx but what about the main problem?

**Comment by Stormbow** [comment]
Fix the errors mentioned above.  Does the "main problem" still exist?  ;)

**Comment by Stormbow** [comment]
You can also reference [this example](http://pastebin.com/8ZSHxauG) of a "proper"/"full" permissions.yml file.

**Comment by RoBaMe** [comment]
@Stormbow i fixed the problems and its still does that heres the paste.bin link : http://pastebin.com/1D1GsbSp

**Comment by Stormbow** [comment]
Ok, permissions.yml file is fixed.  Pastebin your server.properties file for me next please.  (Can be opened in Notepad to copy and paste over to Pastebin.)

**Comment by RoBaMe** [comment]
@Stormbow heres the server properties (removed ip and port sorry XD) http://pastebin.com/WLycKv7S

**Comment by RoBaMe** [comment]
@Stormbow I don't have modifyworld.jar, what it is? and where do i get it?

**Comment by Stormbow** [comment]
That would be the problem. :)  You gave the first group "modifyworld.*" and you don't even have a plugin that requires that permission? heh

[Modifyworld](http://dev.bukkit.org/bukkit-plugins/modifyworld/)

**Comment by RoBaMe** [comment]
@Stormbow i thought i was part of  Pex XD

**Comment by Stormbow** [comment]
Also, change your spawn-protection from 16 to 0.  That's more of a vanilla/no plugins server setting that interferes with custom servers.

**Comment by RoBaMe** [comment]
@Stormbow it still not working, i downloaded the Modifyworld plugin and i still can break/place blocks

**Comment by Stormbow** [comment]
"Can"  break/place is what you "do" want.  Isn't it?  The original post of this thread implied "can not" break/place...

**Comment by RoBaMe** [comment]
can't* sorry

**Comment by RoBaMe** [comment]
@Stormbow i've noticed something weird, when i restart the server and join it, i can't break any blocks, but when i reload, i can.

**Comment by Stormbow** [comment]
Well, when you stop the server entirely, it reloads everything when restarted.  ;p

So, problem solved?

**Comment by RoBaMe** [comment]
@Stormbow no it;s still don't

**Comment by Stormbow** [comment]
Ok, time to debug.

While in-game, type: /pex user RoBaMe toggle debug
Without moving or doing anything else, attempt to break a block
Type the above command again to turn off debugging
Look in your console and copy from when you turned on debug to where you turned it off
Pastebin that mess; leave the link in this thread

**Comment by RoBaMe** [comment]
im uploading a gif for you to see what's happaning

**Comment by RoBaMe** [comment]
@Stormbow heres the pastebin

**Comment by Stormbow** [comment]
No link

**Comment by RoBaMe** [comment]
@Stormbow there is

**Comment by Stormbow** [comment]
There's nothing clickable above this.

**Comment by RoBaMe** [comment]
@Stormbow  http://pastebin.com/RCAkqD9u

**Comment by Stormbow** [comment]
The debug shows you successfully broke a bunch of different leaves blocks.

Which version of Minecraft are you using?
Which version of PEX are you using?
Pastebin your server console startup log (from the moment you begin starting the server thru the point where the console says "done!")

**Comment by RoBaMe** [comment]
@Stormbow http://pastebin.com/KkHgq5uC

**Comment by Stormbow** [comment]
That's not a full server startup log...  O_o;  It doesn't show you have PermissionsEx or Modifyworld installed.

**Comment by RoBaMe** [comment]
it is +_+, and this is the reload log : http://pastebin.com/UK40khJm

**Comment by RoBaMe** [comment]
@Stormbow look this is what happaning - http://makeagif.com/t7nQCX

**Comment by Stormbow** [comment]
This is my server log: http://pastebin.com/H8HTuGBm

**Comment by Stormbow** [comment]
YOU'RE VANISHED!

**Comment by Stormbow** [comment]
Of course you can't interact with any blocks!

**Comment by RoBaMe** [comment]
@Stormbow OOPS!!! XD MY BAD LOLOL

**Comment by Stormbow** [comment]
LOL  Make sure your group (or you're user) gets - -vanish.silentjoin and a couple other vanish-related permissions negated, and make sure those negations are -above- the wildcard '*' for the group.

**Comment by RoBaMe** [comment]
ok THX for the HELP!!! REALLY!

**Comment by Stormbow** [comment]
You're welcome. :)

**Comment by Stormbow** [comment]
These are all the negations I use on my server:

    - -vanish.effects.smoke
    - -vanish.effects.explode
    - -vanish.effects.lightning
    - -vanish.effects.flames
    - -vanish.effects.bats
    - -vanish.silentjoin
    - -vanish.silentquit
