### ISSUE TITLE
Groups inheritance by world doens't work

### ISSUE THREAD

**Issue by idkw** [PEXPlugins/PermissionsEx#2098]
Groups don't inherits permissions in inherted worlds.

Small setup to reproduce
===

Create a server with two worlds : `world1` and `world2`
Make `world2` inherits from `world1`
Create group `User`
Create group `Admin` which inhertis from User
Add permission node `minecraft.command.op` to `User` group in `world1`
Set the group of a player `user` to `User`
Set the group of a player `admin` to `Admin`

What's happening : 
===

As expected, the player `user` can `/op` himself in `world1` and `world2` because `world2` inherits from `world1`
However the player `admin` doens't have acces to `/op` command neither in `world1` or `world2`

What I expected (inheritance) : 
=== 
Because the player `admin` inherits from the group `User` and the group `User` has access to `/op` in `world1`, any user in group `Admin` should have access to `/op` in `world1`. Furthermore because `world2` inherits from `world1`, `admin` could also `/op` himself in `world2`. This is only simple inheritance logic.

Conclusion
===

It is really an annoying issue, because when I add a permission to a low level group in a specific world, I have to add the same permission in the same specific world to other groups that inherit from that first group.

The logical inheritance behavior in my opinion would be that a group also inherits the worlds permissions from its parents groups.

Thank you

**Comment by danielhobby** [comment]
Could you add a comment with your permissions file as I think this would supply clarity.

**Comment by idkw** [comment]
I am using the SQL backend. It's a bit hard to show you that.
I'll do some testing again.

**Comment by danielhobby** [comment]
Ahh right, from what you wrote it confused me a little. You wrote: 

*Create group Admin 
Create group User which inhertis from Admin*

Which would mean User inherits from Admin. 
Which means User gets all of the same permissions as Admin. Surely you would want this the other way around? Admin inheriting from User. Meaning an Admin can do everything a User can and then you add permissions that you only want an admin to use.

Forgive me if i'm spelling out the obvious. :smile:

**Comment by idkw** [comment]
Yes , you're right. Admin inherits from User

**Comment by danielhobby** [comment]
That's unrelated to your problem though?

**Comment by idkw** [comment]
I'm going to check that tonight, I'll get back to you. Maybe it's a mistake of mine.

**Comment by Stormbow** [comment]
User error is almost always the cause of problems. ;)
