### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by zml2008** [PEXPlugins/PermissionsEx#2099]
I'd like to have a common graphical interface across implementations. This would allow easier editing of permissions data.

Implementations to look at:
- [ ] [MCMyAdmin/AMP](http://cubecoders.com/AMP)
- [ ] Sponge GUI API (far off)
- [ ] JavaFX
- [ ] [Metawidget](metawidget.sourceforge.net)/[WebConsole](https://github.com/zml2008/WebConsole)

**Comment by Stormbow** [comment]
*LIKE*
