### ISSUE TITLE
Prefixes don't work

### ISSUE THREAD

**Issue by RoBaMe** [PEXPlugins/PermissionsEx#2100]
Hi! i have a server and i want to make prefixes, i already wrote them, but the don't work. probably blocked by other plugin, the problem is i don't know what plugin is it. so can someone help me?
here's our pex permissions.yml file : http://pastebin.com/qZn37jSu 
and this is out plugins : 
CoreProtect
DoubleJump (custom plugin by me XD)
Essentials-2.x-SNAPSHOT
HolographicDisplays
Modifyworld
Multiverse-Core
Multiverse-Inventories
PerWorldPlugins
PermissionsEx (Of course XD)
VanishNoPacket
WorldEdit

**Comment by RoBaMe** [comment]
Anyone?

**Comment by Cammo009** [comment]
i seem to have the same issue on my server too? worked while my server was 1.7.10 but now i upgrade my jar to 1.8 and now running 1.8.7 spigot. Prefix doesnt work. i tryed removing a plugins just leaving PermissionsEx on but still nothing.

**Comment by RoBaMe** [comment]
solved it, essentials blocked it
