### ISSUE TITLE
Permissionsex API dev

### ISSUE THREAD

**Issue by coco5843** [PEXPlugins/PermissionsEx#2101]
### Description ###

When I try to give a player permission with vault or your api I get this error (last permissionsex)

### Detailed Information ###

http://pastebin.com/mNN03Q8x

**Comment by Stormbow** [comment]
Which permission are you trying to grant and which commands and plugins are you trying to use to accomplish this task?

**Comment by zml2008** [comment]
Seems like you have some null entries in a user's permissions list. You might want to go through your permissions.yml and make sure nothing there is null.

**Comment by coco5843** [comment]
okay i'm sorry , I set a null String :S
