### ISSUE TITLE
[Enhancement] - Remove empty indices in the permissions yml file.

### ISSUE THREAD

**Issue by Pieter12345** [PEXPlugins/PermissionsEx#2102]
When using '/pex user <user> prefix "" ', the users prefix is cleared, but the 'prefix' index in the yml file is not removed. I would like pex to remove the prefix/suffix/options indices when they are empty.

**Comment by Stormbow** [comment]
Open the file in Notepad and delete them.  They don't harm anything by being empty sets within the file.

**Comment by Pieter12345** [comment]
@Stormbow This is not what I asked. I could indeed write something that cleans up the file every once in a while but this request is to implement that into the plugin. Implementing it should not be too hard and it would look better in the file.
