### ISSUE TITLE
Very very laggy

### ISSUE THREAD

**Issue by Toshka17** [PEXPlugins/PermissionsEx#2103]
[13:48:18 INFO]: [Essentials] Lag Notice - Slow Permissions System (PermissionsEx) Response - Request took over 400.59ms!

Timings: http://timings.aikar.co/?url=11929723

TPS = 3, When 50 players

pex uses mysql database it on another server.

Server OVH 32Gb, Intel Core i7-4790K

I do not know what to do, so as not to lag?

**Comment by zml2008** [comment]
```
pex uses mysql database it on another server.
```
There's your problem. If the mysql database is remote, there's a lot more overhead involved.
