### ISSUE TITLE
pex

### ISSUE THREAD

**Issue by xDraagon** [PEXPlugins/PermissionsEx#2104]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/af210e42936444195733)

**Comment by zml2008** [comment]
Since it seems someone forgot to give us our telepathy hats, I'm afraid you're going to have to actually explain what your issue is.

**Comment by macdja38** [comment]
It's on I have two, but one always lies... 
Is this the problem:
permissions:
    - <permission>

**Comment by macdja38** [comment]
On > ok

**Comment by Stormbow** [comment]
Your permissions.yml file should look [like this](http://pastebin.com/8ZSHxauG), not like the file you have on your server.

**Comment by zml2008** [comment]
If you aren't going to explain your error any further, just gonna close this.
