### ISSUE TITLE
Server Lag with latest version.

### ISSUE THREAD

**Issue by sharkybushbaby** [PEXPlugins/PermissionsEx#2105]
Please bare with me . I haven't touch permissionsex since i first started my server 4 years ago.
So now ive gone 1.8.7 i was updating some plugins. One was Citizens Sentry. where i was finding the npcs were no longer attacking. 
Anyway I googled , and found that to update vault and permissions plugin would solve this problem.
Which i did. now the npcs were doing what they were supposed to But there was some serious lag. 
and the console telling me all kinds of issues regarding 

"  [Server thread/WARN]: Invalid statistic in ./world/stats/ccdc0993-55e5-23f0-86bd-2e1eda65f94f.json: Don't know what stat.useItem.20 is " over and over.

The server was non responsive due to large lags. 

I looked into perms yml found that players names were now UUID (which complicates things) 

Is it a case I need to try another version?
or
stick to the old version and have unresponsive npcs? 

Thanks for any help

**Comment by zml2008** [comment]
The "Invalid statistic" issue is not related to PEX -- you'll have to look somewhere else to fix that. 

You'll want to check something like [WarmRoast](http://github.com/sk89q/WarmRoast) or Akar's timings (on spigot -- take a look at their wiki for how to get that set up) to pin down what's causing the lag. Also you might want to try 1.23.2 on your server (disabling autoupdate) -- 1.23.3 reverts a change that improved performance for some people but caused the cache to not update correctly for others, so one of the two might work best.

**Comment by sharkybushbaby** [comment]
Cheers. Thanks for your time
