### ISSUE TITLE
Pex Import File Permission

### ISSUE THREAD

**Issue by NitroxydeX** [PEXPlugins/PermissionsEx#2106]
Hey Guys,

the wiki says permissions.manage.dump ist the perm for the /pex import file command, but it's not working. Something changed?

**Comment by zml2008** [comment]
The permission is permissions.dump it looks like.

**Comment by NitroxydeX** [comment]
Uhm. Doesen't work either. :(

**Comment by zml2008** [comment]
What error are you getting? Did you actually set the permission so it takes effect on the appropriate user?

**Comment by NitroxydeX** [comment]
Yeah I set it. It says "You do not have enough permissions"

**Comment by NitroxydeX** [comment]
No Idea @zml2008?
