### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by marik2003** [PEXPlugins/PermissionsEx#2108]
### Description ###

[i tried to add new ranks but it bugged out and broke the plugin what to do?]
### Detailed Information ###

[Is available here](https://gist.github.com/f10eb81d34c02eb8c2ed)

**Comment by Stormbow** [comment]
You're using the wrong version of PEX (1.20.4) for that version of Minecraft (1.8.7).  Get 1.23.3 [here](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/).
