### ISSUE TITLE
PermissionsEx Group Add/Remove Issues.

### ISSUE THREAD

**Issue by D-ouglas** [PEXPlugins/PermissionsEx#2110]
Hello.
Over the time I have been using PermissionsEx I have found a few issues.
The issue that I want to assess is to do with adding/removing multiple groups.
Issue:
Sometimes when a user ranks up, their groups are not added/removed, instead permissionsEx only executes one of the commands (either adding another group the user, or removing one of their groups) and the user is reverted back to the default group (a).
I think I may have found the cause, (it's not to do with weight).
When multiple PermissionsEx groups are added/removed from multiple users at the same time, I think the plugin is having issues writing to the file.
I have made the issue much less common with a custom cool-down plugin for the /rankup command.
What used to happen before we had this cool-down command is that two users would rankup right after one another, and one users would either have an extra group added to their info, or have their primary group removed, although the other user would be fine.

It seems to be very hard to reproduce this.
One thing I have noticed is that the permissions.yml file is around 6mb perhaps causing write issues.

I know I'm not very good at explaining the situation, but if you could respond back to me whenever so we can discuss the issue and hopefully resolve it, I would be immensely appreciative.

Thank you so much for your time,
with regards,
Dug.

**Comment by zml2008** [comment]
What version of PEX are you using? The most recent version of PEX may be better at handling conflicts like this.

**Comment by D-ouglas** [comment]
I'm currently using 1.22.8, I have also tried 1.22.9, and many other previous version.
The server is running 1.7.10 protocol patch.

**Comment by GangSterFlexx** [comment]
@D-ouglas, I would recommend you to upgrade to 1.8.* as the plugin is updating to latest version (Fixing problems and stuff)

**Comment by D-ouglas** [comment]
We've updated to the latest version and the issue seems to have been resolved.
Thanks for your time.

**Comment by GangSterFlexx** [comment]
No problem @D-ouglas.

@zml2008, you can close this now.
