### ISSUE TITLE
Per-World permission bug

### ISSUE THREAD

**Issue by mario-assassino** [PEXPlugins/PermissionsEx#2111]
We're running a Multiworld-Server running on Java 8 and spigot 1.8.7
We're using PEX with SQL-Backend and never had a Problem so far.
Yesterday we updated from Java 7 to Java 8.
We've got a plot-world on our server where our players have fly-permissions.
Today we realized, that our users can do /fly in the plotworld (as intended) and after teleporting/warping to a different world they still can fly (what shouldn't be). 
In the past the fly-mode was diasbled each time they warped/teleported to another world. Now it stays active.
We don't know if this behaviour was caused by the Java-update or if the users found it out accidently.

**Comment by zml2008** [comment]
The java update would most likely not change this. Check with the dev of whatever plugin you use to control flight to make sure it handles world changes properly.

**Comment by mario-assassino** [comment]
As we're using the Spigot-version of essentials for flying this might be a little bit of a problem. I don't know where I could post a ticket there.
