### ISSUE TITLE
wondering were i can get a version of pex for 1.7 

### ISSUE THREAD

**Issue by weltandmelt** [PEXPlugins/PermissionsEx#2112]
I tried looking on the bucket post and couldn't find it, but I'm running a server on 1.7 and was wondering were I could find a 1.7 minecraft version of pex

**Comment by weltandmelt** [comment]
never mind, I was able to find a previous version on my old harddrive

**Comment by Stormbow** [comment]
All of the PEX releases are [right here](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/).

**Comment by weltandmelt** [comment]
ok ty, but none of them say for 1.7.10 will the ones for 1.7.9 work?

**Comment by zml2008** [comment]
The latest 1.22.x version is compatible with 1.7.5-1.7.10

**Comment by weltandmelt** [comment]
i tried putting in PermissionsEx v1.22.9 and it wouldn't load in, do I need another plugin installed for it to work?

**Comment by zml2008** [comment]
Well yes you need bukkit... but if there are any errors read the release notes for the different versions on dev.bukkit.org which have information on the appropriate versions.
