### ISSUE TITLE
Guava Error

### ISSUE THREAD

**Issue by SBMous** [PEXPlugins/PermissionsEx#2114]
I have been trying to fix various errors with my PermissionsEx for a while now over on the forums and me an Stormbow (Mainly the Latter) have systematically fixed all the issues with my Config and Permissions YML's only to be left with a Guava error.

Stormbow sent me here to deal with that. Here is all the info you should need.

The Forum Post: http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/techhelp/81886-permissions-file-empty/#p8

The Crash: http://pastebin.com/NTcPHzVd

Also the YML's and a previous crash (I fixed line 5): http://pastebin.com/9VuKrj3k

**Comment by zml2008** [comment]
You need a version of Essentials that is updated for spigot 1.8. EssentialsX is probably the most actively updated fork -- take a look for it on the Spigot resources site.
