### ISSUE TITLE
error when trying to use pex

### ISSUE THREAD

**Issue by caudy** [PEXPlugins/PermissionsEx#2115]
05.08 22:46:41 [Server] INFO Error: Default user group is not defined. Please select one using the "default: true" property
05.08 22:46:41 [Multicraft] Skipped 3 lines due to rate limit (30/s)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:252)
05.08 22:46:35 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497)
05.08 22:46:35 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05.08 22:46:35 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05.08 22:46:35 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.bukkit.commands.PromotionCommands.promoteUser(PromotionCommands.java:80)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:118)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.ProxyPermissionUser.initialize(ProxyPermissionUser.java:42)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionUser.initialize(PermissionUser.java:51)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:53)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:294)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionUser.getOption(PermissionUser.java:130)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionUser.getGroups(PermissionUser.java:219)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:284)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:295)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.getDefaultGroup(FileBackend.java:138)
05.08 22:46:35 [Server] INFO Caused by: java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property
05.08 22:46:35 [Server] INFO at java.lang.Thread.run(Thread.java:745)
05.08 22:46:35 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
05.08 22:46:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
05.08 22:46:35 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
05.08 22:46:35 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473)
05.08 22:46:35 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697)
05.08 22:46:35 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
05.08 22:46:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
05.08 22:46:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:165)
05.08 22:46:35 [Server] INFO at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:121)
05.08 22:46:35 [Server] INFO java.lang.RuntimeException: java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property
05.08 22:46:35 [Server] INFO Error occurred with PermissionsEx! Please post it to   title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F65ec418824c1162cacbc%29%0A. Full error

**Comment by zml2008** [comment]
Try not using an ancient version of PEX.
