### ISSUE TITLE
UUIDs in commands

### ISSUE THREAD

**Issue by B3stcraft** [PEXPlugins/PermissionsEx#2118]
Hi, 

is there a way to execute a command using directly the uuid instead of the player name?

I am using Buycraft to set server donation system this way:

Initial command (when player purchase): pex user {name} group add hero
Expiry commands (when the time has end): pex user {name} group remove hero

So if a player change his name after buying the vip hero, buycraft wont be able to remove that group after the time ends...

**Comment by zml2008** [comment]
Yes, just use the uuid (with dashes) in place of the player name and it'll work.
