### ISSUE TITLE
ERROR Error occurred with PermissionsEx! Please post it to http://git.io/v33jG. Full error:

### ISSUE THREAD

**Issue by Antdog319** [PEXPlugins/PermissionsEx#2122]
INFO at java.lang.Thread.run(Unknown Source)
10.08 19:05:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503)
10.08 19:05:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235)
10.08 19:05:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
10.08 19:05:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
10.08 19:05:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
10.08 19:05:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
10.08 19:05:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
10.08 19:05:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
10.08 19:05:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
10.08 19:05:02 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
10.08 19:05:02 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
10.08 19:05:02 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
10.08 19:05:02 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
10.08 19:05:02 [Server] java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
