### ISSUE TITLE
Cannot import backend - Backend file was unable to load due to user configuration error

### ISSUE THREAD

**Issue by Dakotaa** [PEXPlugins/PermissionsEx#2124]
I'm using mySQL as my backend and trying to import my file backend into mySQL but getting this error everytime I try /pex import file http://pastebin.com/6T1DbwjW

**Comment by zml2008** [comment]
Not much I can do to help you because you're using a broken server panel that strips out log lines with important details. Make sure you permissions file is valid yaml, and you may find more info in your full server log file.
