### ISSUE TITLE
PEX MySQL Syncing problem

### ISSUE THREAD

**Issue by CHarrisMedia** [PEXPlugins/PermissionsEx#2125]
I run a network and all servers run PEX with the same config, all connecting to a global MySQL database. Theoretically, this should mean all ranks, permissions etc are synced across the server, right? They don't. For some unknown reason, I can set my rank in hub, hop into creative and not get the rank, even after /pex reload(ing).

**Comment by GangSterFlexx** [comment]
MySQL version?

**Comment by CHarrisMedia** [comment]
I believe i'm running the latest version, alongside phpMyAdmin. I read somewhere that the issue is with the plugins PEX & zPermissions, where they will not sync across servers well, the only alternative I currently see is SQLPerms but i'd much prefer to use PEX.

**Comment by Snipershotmaster** [comment]
do /Pex backend does it say in the output "backend=sql"? If not you are not using mysql, do /pex backend sql to use mysql. If that does not work you have not synced your ranks well. https://www.spigotmc.org/threads/pex-mysql-rank-sync.87618/#post-965105 on the first page there is a small (shitty) tutorial i made about syncing ranks but not their permissions across all servers.

**Comment by zml2008** [comment]
Make sure you're connecting to the same database across all the servers.

PEX will cache user data so that changes may not take effect until a reload or server relaunch by default. The plugin NetEvents can be used to remedy this in some cases.
