### ISSUE TITLE
Missing <pluginManagement> tag in Sponge's POM

### ISSUE THREAD

**Issue by nalimleinad** [PEXPlugins/PermissionsEx#2126]
In Sponge's POM is missing <pluginManagement> tag which is needed by Eclipse (http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin) so Eclipse throws errors.

**Comment by zml2008** [comment]
Fix your broken IDE. Shouldn't need to add ide-specific stuff to my pom.

If you can't fix it, add a local profile in your ~/.m2/settings.xml with the necessary additions.
