### ISSUE TITLE
PEX 1.8.X dont Work

### ISSUE THREAD

**Issue by DOCPLAY** [PEXPlugins/PermissionsEx#2133]
Hey
Every plugin on my server is working, but when i put pex (newest version) on the server nobody can chat or build, /pl show pex in grenn.
What can i do?

**Comment by zml2008** [comment]
You have some plugin on your server that is blocking chat or build. If you have modifyworld, you probably want to give your default group modifyworld.* then remove permissions individually. Otherwise, you'll have to go through your plugins and see what each one does.
