### ISSUE TITLE
[SQL QUESTION] About PermissionEx performance

### ISSUE THREAD

**Issue by Darkool** [PEXPlugins/PermissionsEx#2136]
Hello, I would like to know how permissionex works, I mean if permissions using mysql, execute query every time that I request or on join It store player's permissiones on cache, for example I would like use getplayerprefix trought vault to display it on my chat, then Permissionex will execute query to get prefix every time that a player talk?, thanks a lot for your time.

**Comment by zml2008** [comment]
User sql data is cached, so it is only calculated the first time it's gotten for each world and after certain updates.
