### ISSUE TITLE
Groups not working! PLEASE HELP

### ISSUE THREAD

**Issue by skorponok27** [PEXPlugins/PermissionsEx#2137]
Hi! Im not sure what is wrong but I wrote out all my ranks in the yml file and it "should" work perfectly. Whenever I reload the server and go into the game I do not have my permissions when I set my rank. Is it where i have my permissions.yml file located? Its in the permissions folder in plugins. Im kind of confused please help. You are also aloud to join my server to help if you would like. If you would like to ill give u the ip.

THE YML FILE

groups:
  Player:
    permissions:
    - modifyworld.*
    - multiverse.portal.access.
    options:
      prefix: '&6'
      default: true
  Builder:
    permissions:
    - worldedit.fill
    - bukkit.command.gamemode
    - minecraft.command.gamemode
    - echopet.pet.*
    - echopet.pet.type.*
    - echopet.pet.type.(type).*
    - echopet.pet.ride.*
    - echopet.pet.hat.*
    - echopet.pet.default.*
    - echopet.pet.default.set.type.*
    - playerparticles.*
    inheritance:
    - Player
    options:
  Helper:
    inheritance:
    - Player
    options:
      prefix: '&e[Helper] &f'
  Moderator:
    permissions:    inheritance:
    - Player
    options:
      prefix: '&b[Mod] &f'
  Admin:
    permissions:
    - echopet.pet.*
    - echopet.pet.type.*
    - echopet.pet.type.(type).*
    - echopet.pet.ride.*
    - echopet.pet.hat.*
    - echopet.pet.default.*
    - echopet.pet.default.set.type.*
    - playerparticles.*

    options:
      prefix: '&c[Admin] &f'
  Co-Owner:
    permissions:
    - worldedit.*
    - bukkit.command.kick
    inheritance:
    - Builder
  Owner:
    permissions:
    - '*'
    options:
      prefix:

**Comment by Stormbow** [comment]
Make sure your permissions.yml file looks more like [this example](http://pastebin.com/8ZSHxauG).  Notice there are no blank lines between groups, no empty sets (like your "Co-Owner" group's prefix"), the schema-version line comes between the "groups:" and "users:" sections (you have no schema and no user sections).

**Comment by skorponok27** [comment]
I tried to fix it.. It still does not work. I do not have the  permissions to do /pex user <user> group set (group). So when i do it in the console it says it works but the player that i just promoted doesnt have any comands or nothing. Can you help or join my server or ANYTHING. Am i typing the wrong command? Please help!!

GROUPS FOR PEX


groups:
  Guest:
    options:
      default: 'true'
      build: 'true'
      rank: '1000'
      rank-ladder: Main
      weight: '7'
    - multiverse.portal.access.
  Member:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Member '
      suffix: ' the Regular'
      rank: '900'
      rank-ladder: Main
      weight: '6'
    inheritance:
    - Guest
    permissions:
    - modifyworld.*
    - echopet.pet.*
    - echopet.pet.type.*
    - echopet.pet.type.(type).*
    - echopet.pet.ride.*
    - echopet.pet.hat.*
    - echopet.pet.default.*
    - echopet.pet.default.set.type.*
    - playerparticles.*
  Mod:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Mod '
      suffix: ' the Scary'
      rank: '200'
      rank-ladder: Main
      weight: '5'
    inheritance:
    - Member
    permissions:
    - bukkit.command.gamemode
    - minecraft.command.gamemode
    - modifyworld.*
    - echopet.pet.*
    - echopet.pet.type.*
    - echopet.pet.type.(type).*
    - echopet.pet.ride.*
    - echopet.pet.hat.*
    - echopet.pet.default.*
    - echopet.pet.default.set.type.*
    - playerparticles.*
  Builder:
    options:
      default: 'false'
      rank: '150'
      rank-ladder: Main
      weight: '4'
      inheritance:
      - Guest
      permissions:
    - worldedit.fill
    - bukkit.command.gamemode
    - minecraft.command.gamemode
    - echopet.pet.*
    - echopet.pet.type.*
    - echopet.pet.type.(type).*
    - echopet.pet.ride.*
    - echopet.pet.hat.*
    - echopet.pet.default.*
    - echopet.pet.default.set.type.*
    - playerparticles.*
  Admin:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Admin '
      suffix: ' the Benevolent'
      rank: '100'
      rank-ladder: Main
      weight: '3'
    inheritance:
    - Mod
    permissions:
    - bukkit.command.gamemode
    - minecraft.command.gamemode
    - modifyworld.*
    - echopet.pet.*
    - echopet.pet.type.*
    - echopet.pet.type.(type).*
    - echopet.pet.ride.*
    - echopet.pet.hat.*
    - echopet.pet.default.*
    - echopet.pet.default.set.type.*
    - playerparticles.*
  CoOwner:
    options:
      default: 'false"
      build: 'true'
      rank: '2'
      rank-ladder: Main
      weight: '1'
      permissions:
      - bukkit.command.gamemode
      - minecraft.command.gamemode
      - modifyworld.*
      - echopet.pet.*
      - echopet.pet.type.*
      - echopet.pet.type.(type).*
      - echopet.pet.ride.*
      - echopet.pet.hat.*
      - echopet.pet.default.*
      - echopet.pet.default.set.type.*
      - playerparticles.*
  Owner:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Owner '
      suffix: ' the Almighty'
      rank: '1'
      rank-ladder: Main
      weight: '1'
    permissions:
    - -negated.nodes.go.above.wildcard
    - '*'
schema-version: 1
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: BrandonODST
    group:
    - Owner
      name: lanibear2539
    group:
    - CoOwner
