### ISSUE TITLE
pex problem with deafult group

### ISSUE THREAD

**Issue by onardox** [PEXPlugins/PermissionsEx#2138]
### working on config and an error ###

[Is available here](https://gist.github.com/d3edf1a54ef0591d7997)

**Comment by Stormbow** [comment]
Don't use vTeamCity plugins.  They always-always-always cause problems.  Only use official downloads for [Essentials](dev.bukkit.org/bukkit-plugins/).

Your permissions.yml file should look much more like [this example](http://pastebin.com/8ZSHxauG).  Notice there is no empty set for "Worlds: []".  Multiworld permissions go under the "permissions:" section, not out on their own as you have them.

**Comment by zml2008** [comment]
The main issue here is that you're using a version of PEX that is 2 years old with a modern configuration file. That's the big issue

Also for spigot currently the recommended fork of essentials is EssentialsX, available on spigot resources.
