### ISSUE TITLE
Pex Crash

### ISSUE THREAD

**Issue by xTwistedMelonx** [PEXPlugins/PermissionsEx#2140]
Not really sure what happened here. Pex went red in ./pl
Here's the permission.yml, see any errors?

groups:
  default:
    permissions:
    - essentials.warp.list
    - essentials.warp
    - essentials.spawn
    - essentials.afk
    - essentials.balance
    - essentials.pay
    - essentials.msg
    - essentials.rules
    - essentials.ignore
    - essentials.list
    - essentials.motd
    - essentials.kit
    - essentials.kit.fight
    options:
      prefix: '&8[&7Default&8]&7 '
      default: true
  Builder:
    permissions:
    - essentials.feed
    - essentials.heal
    - essentials.gamemode
    - worldedit.*
    options:
      prefix: '&c[&1Builder&c]'
    inheritance:
    - default
  Technician:
    permissions:
    - Bukkit.command.plugins
    - Bukkit.command.reload
    options:
      prefix: '&c[&9Technician&c]'
    inheritance:
    - default
   Helper:
    permissions:
    - essentials.kick
    - essentials.thru
    - essentials.jail
    - essentials.fly
    inheritance:
    - default
    options:
      prefix: '&c[&aHelper&c]'
  Moderator:
    permissions:
    - essentials.kick
    - essentials.tempban
    - essentials.thru
    - essentials.jail
    - essentials.fly
    inheritance:
    - Helper
    options:
      prefix: '&c[&eMod&c]'
  Admin:
    options:
      prefix: '&e[&a&lAdmin&e]'
    inheritance:
    - Moderator
  Manager:
    permissions:
    - '*'
    - permissions.*
    options:
      prefix: '&e[&4Manager&e] '
  ExecutiveAdmin:
    permissions:
    - *
    - permissions.*
    options:
      prefix: '&e[&c&k;;;&b&lExecutive&c&l-&b&lAdmin&c&k;;;&e] '
  HeadAdmin:
    permissions:
    - essentials.gamemode
    - essentials.jail
    - essentials.thru
    - essentials.unban
    - essentials.ban
    - essentials.tempban
    - essentials.kick
    options:
      prefix: '&e[&5&lHead&d&l-&5&lAdmin&e] '
    inheritance:
    - Admin
  Spy:
     permissions:
    - *
    options:
      prefix: '&8[&7Default&8]'
schema-version: 1

**Comment by Stormbow** [comment]
You made many mistakes which I have corrected for you [here](http://pastebin.com/edit.php?i=8TnFS4Cg}.
