### ISSUE TITLE
Connection SQL (probably something I'm doing)

### ISSUE THREAD

**Issue by OurSickStory** [PEXPlugins/PermissionsEx#2141]
Config: http://pastebin.com/UXZ6P2Jw
Error: http://pastebin.com/UE9ft0Pu

**Comment by Snipershotmaster** [comment]
Caused by: java.sql.SQLException: Access denied for user 'databaseuser'@'localhost' (using password: YES)

Check your mysql config

**Comment by OurSickStory** [comment]
The database is created "pex" and the password is 100% correct.

**Comment by zml2008** [comment]
then the username might be wrong. or the privilege grants might be wrong. not our problem.
