### ISSUE TITLE
Error during add pex group set

### ISSUE THREAD

**Issue by olegempty** [PEXPlugins/PermissionsEx#2144]
25.08 15:27:57 [Server] INFO Unable to load ForZen.dat...  Creating file!
25.08 15:27:57 [Multicraft] ForZen ran command Сообщение дня
25.08 15:27:57 [Connect] User ForZen, IP 89.149.103.200
25.08 15:26:08 [Server] INFO ? [��ப] olegempty1996 ? d
25.08 15:26:08 [Multicraft] Skipped 1019 lines due to rate limit (30/s)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionGroup.getOption(PermissionGroup.java:651)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionGroup.getOption(PermissionGroup.java:678)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionGroup.getParentGroups(PermissionGroup.java:233)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionManager.getGroup(PermissionManager.java:227)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.ProxyPermissionGroup.initialize(ProxyPermissionGroup.java:43)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionGroup.initialize(PermissionGroup.java:42)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionEntity.initialize(PermissionEntity.java:53)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionEntity.getOptionBoolean(PermissionEntity.java:294)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionGroup.getOption(PermissionGroup.java:651)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.PermissionGroup.getOption(PermissionGroup.java:655)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.ProxyPermissionGroup.getOwnOption(ProxyPermissionGroup.java:102)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.backends.file.FileEntity.getOption(FileEntity.java:126)
25.08 15:25:51 [Server] INFO at org.bukkit.configuration.MemorySection.getString(MemorySection.java:281)
25.08 15:25:51 [Server] INFO at org.bukkit.configuration.MemorySection.get(MemorySection.java:215)
25.08 15:25:51 [Server] INFO at org.bukkit.configuration.MemorySection.getConfigurationSection(MemorySection.java:675)
25.08 15:25:51 [Server] INFO at org.bukkit.configuration.MemorySection.get(MemorySection.java:209)
25.08 15:25:51 [Server] INFO Caused by: java.lang.StackOverflowError
25.08 15:25:51 [Server] INFO at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
25.08 15:25:51 [Server] INFO at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:415)
25.08 15:25:51 [Server] INFO at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:483)
25.08 15:25:51 [Server] INFO at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:241)
25.08 15:25:51 [Server] INFO at net.minecraft.server.v1_6_R3.DedicatedServer.as(DedicatedServer.java:276)
25.08 15:25:51 [Server] INFO at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchServerCommand(CraftServer.java:519)
25.08 15:25:51 [Server] INFO at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:532)
25.08 15:25:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
25.08 15:25:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:165)
25.08 15:25:51 [Server] INFO at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:121)
25.08 15:25:51 [Server] INFO java.lang.RuntimeException: java.lang.StackOverflowError
25.08 15:25:51 [Server] INFO Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F6c57dc3ddf417e682e9b%29%0A. Full error:
25.08 15:25:24 [Server] INFO Using external NmsBlock for this version: CBXNmsBlock_164

**Comment by zml2008** [comment]
You have circular inheritance somewhere in your permissions setup. Fix that.
