### ISSUE TITLE
Players without perms can do /gmc and ignore regions

### ISSUE THREAD

**Issue by booksaw** [PEXPlugins/PermissionsEx#2145]
there are the perms i have:
![image](https://cloud.githubusercontent.com/assets/13976636/9487124/eb4f5422-4bc6-11e5-9a0d-be6c9e401d08.png)
![image](https://cloud.githubusercontent.com/assets/13976636/9487135/fcd414a8-4bc6-11e5-8e4b-da4135891753.png)
but when i do /gms or /gmc this happerns:
![image](https://cloud.githubusercontent.com/assets/13976636/9487164/1d4ca222-4bc7-11e5-95b9-5d9723510e44.png)
can someone please help because i need this to work as otherwise my server can't run!
![image](https://cloud.githubusercontent.com/assets/13976636/9487232/a5bab072-4bc7-11e5-96eb-7788e78f6539.png)
the pex version is at the bottom of CMD

**Comment by zml2008** [comment]
1) pex toggle debug, make sure permissions are actually being checked (ess may just use op or something)

2) run /pex report and give the link it provides you.

**Comment by booksaw** [comment]
I will

**Comment by zml2008** [comment]
So the permissions that you showed in your screenshot are not at all what PEX is actually using for you. Your permission file shows that your user is in the owner group, which has all permissions, which is why you'd have permissions overridden.
