### ISSUE TITLE
Rollbacks?

### ISSUE THREAD

**Issue by NeturonicAngelz** [PEXPlugins/PermissionsEx#2146]
Hello,

We've recently been experience some issues with PermissionsEX where the file sometimes doesn't save/rollsback users after initiating a /pex reload command.

We have the following server:
http://www.soyoustart.com/us/offers/e3-ssd-3.xml // Centos 6
Multicraft Preview14 installed on the box

PermissionsEX Version:
V1.23.3

ChatEX Version:
V1.2.0

What does this occur?:
Almost everytime I /pex reload, initially it was not loading the data until I /pex reload'd twice in a row, now its rolling back data whenever I even /pex reload once, or even restart the server. It seems like PEX just isn't saving the data correctly.

Server IP:
mc.Imprisoned.me

What plugins do I have on the server?:
https://gyazo.com/f32c6c00f443c3cd8dbe5000f1b66378
There's a bit of custom plugins on the server, if you need any information on any of them feel free to ask.

Groups:
http://pastebin.com/5dgSQQEw

Users:
http://pastebin.com/61pAbZiZ

The Chmod of the server:
https://gyazo.com/72d8d80c7aaf959ff40c2365e6f23a06

Just in case you need this:
https://gist.github.com/anonymous/712a7b4401fcf4c6c217

**Comment by zml2008** [comment]
This seems like it's happening because a reload is triggered before a save is complete. Unfortunately because PEX1.x isn't really designed to make async saving easy, this issue won't be resolved easily without finishing up PEX2
