### ISSUE TITLE
HELP! ASAP

### ISSUE THREAD

**Issue by skorponok27** [PEXPlugins/PermissionsEx#2148]
Someone helped me earlier (the author)I tried to fix it.. It still does not work. I do not have the permissions to do /pex user group set (group). So when i do it in the console it says it works but the player that i just promoted doesnt have any comands or nothing. Can you help or join my server or ANYTHING. Am i typing the wrong command? Please help!!

UPDATED GROUPS FOR PEX
```
groups:
Guest:
options:
default: 'true'
build: 'true'
rank: '1000'
rank-ladder: Main
weight: '7'
- multiverse.portal.access.
Member:
options:
default: 'false'
build: 'true'
prefix: 'Member '
suffix: ' the Regular'
rank: '900'
rank-ladder: Main
weight: '6'
inheritance:
- Guest
permissions:
- modifyworld.*
- echopet.pet.*
- echopet.pet.type.*
- echopet.pet.type.(type).*
- echopet.pet.ride.*
- echopet.pet.hat.*
- echopet.pet.default.*
- echopet.pet.default.set.type.*
- playerparticles.*
Mod:
options:
default: 'false'
build: 'true'
prefix: 'Mod '
suffix: ' the Scary'
rank: '200'
rank-ladder: Main
weight: '5'
inheritance:
- Member
permissions:
- bukkit.command.gamemode
- minecraft.command.gamemode
- modifyworld.*
- echopet.pet.*
- echopet.pet.type.*
- echopet.pet.type.(type).*
- echopet.pet.ride.*
- echopet.pet.hat.*
- echopet.pet.default.*
- echopet.pet.default.set.type.*
- playerparticles.*
Builder:
options:
default: 'false'
rank: '150'
rank-ladder: Main
weight: '4'
inheritance:
- Guest
permissions:
- worldedit.fill
- bukkit.command.gamemode
- minecraft.command.gamemode
- echopet.pet.*
- echopet.pet.type.*
- echopet.pet.type.(type).*
- echopet.pet.ride.*
- echopet.pet.hat.*
- echopet.pet.default.*
- echopet.pet.default.set.type.*
- playerparticles.*
Admin:
options:
default: 'false'
build: 'true'
prefix: 'Admin '
suffix: ' the Benevolent'
rank: '100'
rank-ladder: Main
weight: '3'
inheritance:
- Mod
permissions:
- bukkit.command.gamemode
- minecraft.command.gamemode
- modifyworld.*
- echopet.pet.*
- echopet.pet.type.*
- echopet.pet.type.(type).*
- echopet.pet.ride.*
- echopet.pet.hat.*
- echopet.pet.default.*
- echopet.pet.default.set.type.*
- playerparticles.*
CoOwner:
options:
default: 'false"
build: 'true'
rank: '2'
rank-ladder: Main
weight: '1'
permissions:
- bukkit.command.gamemode
- minecraft.command.gamemode
- modifyworld.*
- echopet.pet.*
- echopet.pet.type.*
- echopet.pet.type.(type).*
- echopet.pet.ride.*
- echopet.pet.hat.*
- echopet.pet.default.*
- echopet.pet.default.set.type.*
- playerparticles.*
Owner:
options:
default: 'false'
build: 'true'
prefix: 'Owner '
suffix: ' the Almighty'
rank: '1'
rank-ladder: Main
weight: '1'
permissions:
- -negated.nodes.go.above.wildcard
- '*'
schema-version: 1
users:
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
options:
name: BrandonODST
group:
- Owner
name: lanibear2539
group:
- CoOwner
```

**Comment by zml2008** [comment]
uh your permissions file doesn't have any indentation, fix your permissions file.

Also you seem to have duplicated the EchoPet stuff in pretty much every group, might want to use inheritance for that instead.

**Comment by skorponok27** [comment]
Ok well If you dont reply im gonna write another ticket/issue.

HI. Ive been helped twice but nothing will still work. So I have my permissions finished (pastebin link below). If there is something wrong then tell me what it is or please fix it. When ever I go in game (OPPED) i type /pl. Permissionsex is green. When I type /pex user BrandonODST group set Owner - it says in red text "you do not have permission to use this command" or something like that. So of course I go into console. I type - pex user BrandonODST group set Owner - then it says User Groups Set! When I go back into the game I type /pex help, and it says the SAME thing. I deop my self and try again and it still does the same thing. I tried promoting to of my staff members to admin and they didnt have any permissions either. Please help. You are welcome to join my server as well if you need to.

PERMISSIONS

http://pastebin.com/8an6HXW7

**Comment by zml2008** [comment]
Looks like you've got something going on in the users section with having merged a few users together -- try fixing that.

**Comment by skorponok27** [comment]
How do I fix that? Please help.

**Comment by zml2008** [comment]
you delete the misplaced lines?

**Comment by skorponok27** [comment]
I am so sorry, but I think all the lines are placed correctly. In the users, what did I mess up?

**Comment by skorponok27** [comment]
?

**Comment by zml2008** [comment]
take a look at the example file for what a user section should look like: https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup#if-you-do-not-have-access-to-the-console-top

**Comment by zml2008** [comment]
Oh also your permissions file is invalid yaml -- check it at https://yaml-online-parser.appspot.com/

**Comment by skorponok27** [comment]
Thanks i really appreciate the links. Im sure they will help improve my understanding of pex by a lot. But one question. The yaml thing. I paste ny perms into the converter and copy the yaml parsed version and paste it into my permissions.yml file correct?
