### ISSUE TITLE
I NEED HELP!

### ISSUE THREAD

**Issue by skorponok27** [PEXPlugins/PermissionsEx#2149]
HI. Ive been helped twice but nothing will still work. So I have my permissions finished (pastebin link below). If there is something wrong then tell me what it is or please fix it. When ever I go in game (OPPED) i type /pl. Permissionsex is green. When I type /pex user BrandonODST group set Owner - it says in red text "you do not have permission to use this command" or something like that. So of course I go into console. I type - pex user BrandonODST group set Owner - then it says User Groups Set! When I go back into the game I type /pex help, and it says the SAME thing. I deop my self and try again and it still does the same thing. I tried promoting to of my staff members to admin and they didnt have any permissions either. Please help. You are welcome to join my server as well if you need to. 

PERMISSIONS

http://pastebin.com/8an6HXW7

**Comment by zml2008** [comment]
don't create more issues, comment on the existing issue.
