### ISSUE TITLE
Vault support for PEX 2.0

### ISSUE THREAD

**Issue by mibby** [PEXPlugins/PermissionsEx#2150]
Just thought I'd create a ticket so this isn't forgotten to be implemented in PermissionsEx 2.0. :)

**Comment by Stormbow** [comment]
PEX 2.0 isn't coming (as far as I recall) since Bukkit/Craftbukkit is no longer under development and Sponge is taking over.

**Comment by zml2008** [comment]
I've got a PEX2 for spigot still, since it's pretty easy to maintain. Conveniently, I just added vault support, so as of b9bd7ffcf23cc0cb3e1183265344a76a6e540235 vault support has been added.

**Comment by mibby** [comment]
Great, thanks zml! Time to get testing. :)
