### ISSUE TITLE
Maven Intergration not working.. Can't use with PEX 1.23.3

### ISSUE THREAD

**Issue by poncethecat** [PEXPlugins/PermissionsEx#2153]
Yea.. Maven just won't work, here's my POM.xml, it builds fine without PEX :)
POM.XML:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.poncethecat</groupId>
    <artifactId>CuboidChat</artifactId>
    <version>1.0-SNAPSHOT</version>

        <repositories>
            <repository>
                <id>spigot-repo</id>
                <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
            </repository>
            <repository>
                <id>pex-repo</id>
                <url>http://pex-repo.aoeu.xyz</url>
            </repository>
        </repositories>

        <dependencies>
            <dependency>
                <groupId>org.spigotmc</groupId>
                <artifactId>spigot-api</artifactId>
                <version>1.8.8-R0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.bukkit</groupId>
                <artifactId>bukkit</artifactId>
                <version>1.8.8-R0.1-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>ru.tehkode</groupId>
                <artifactId>PermissionsEx</artifactId>
                <version>1.23.3</version>
            </dependency>
        </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>

**Comment by zml2008** [comment]
Use vault
