### ISSUE TITLE
Server Crashes upon GamePreInitializationEvent

### ISSUE THREAD

**Issue by humroben** [PEXPlugins/PermissionsEx#2154]
I am certain that this is an issue with PermissionsEx.

Sponge loads by itself perfectly fine, but when trying to load/construct PermissionsEx, the server crashes with this error:

<code>java.lang.NoClassDefFoundError: org/spongepowered/api/event/game/state/GamePreInitializationEvent </code>

Here is a link to the server crash report: https://www.dropbox.com/s/8qkkku3a7swm4en/crash-2015-09-04_09.33.46-server.txt?dl=1

Environment:

Sponge version: 591
Pex Version: 86/88

**Comment by zml2008** [comment]
PEX has been updated for changes in the SpongeAPI that the sponge implementation has not yet been updated for. Use an older build of PEX or wait a few days for Sponge to be updated.
