### ISSUE TITLE
Higher rank prefix priority (Suggestion)

### ISSUE THREAD

**Issue by MithrandirCraft** [PEXPlugins/PermissionsEx#2157]
Hello. First of all, I appologize if this feature is already implemented.
I already opened a ticket on this a long time ago, but I do not remember the outcome of it. (I think I never got a response.)

-----------------------------------------------------------------------------------------------------------------------

Disclaimers aside, this is my suggestion:

I think higher ranked groups should have higher prefix/sufix priority display.

Example:

Basic:
    options:
      prefix: '&eBasic &f'
    rank: '100'
VIP:
    options:
      prefix: '&4VIP &f'
    rank: '200'

Lets say that user Steve is in both these groups.

VIP rank is higher than Basic rank, therefore, ingame chat should ALWAYS display VIP over Basic prefix.

The issue here is that if user Steve was first a VIP, and somehow he then got the Basic group, the Basic prefix will be displayed with priority over the VIP group prefix, because Basic was the last group he recieved entrance to.

Solution: Higher ranked groups should have higher prefix and sufix display priority on ingame chat.
Solution2: Prefix priority sistem based on numbers similar to rank.
                 Example:
                   options:
                     prefixpriority: 1

**Comment by zml2008** [comment]
Use the `weight` option to control this -- take a look at the wiki to see how it works.

**Comment by MithrandirCraft** [comment]
Thank you @zml2008
