### ISSUE TITLE
SQL Backend

### ISSUE THREAD

**Issue by RustyDesigns** [PEXPlugins/PermissionsEx#2160]
Ok, So this is extremely frustrating.... I've setup MySQL on my server, and created the database PermissionsEX, but when I migrate to SQL with all the details in the config, it throws this error at me.

Error: http://pastebin.com/p49zr2hJ
Config: http://pastebin.com/mNKjq6f9

**Comment by zml2008** [comment]
You conveniently dropped off a large chunk of the error message, will need that to tell you much useful. Make sure the connection info is correct and your mysql server is configured correctly too.

**Comment by juju790** [comment]
Put your server's IP instead of "localhost" like this : mysql://1.2.3.4:3306/PermissionsEX

It should work :)

**Comment by MCTyler** [comment]
Upvote...^^^^^^That URL prob doesn't exist.

**Comment by RustyDesigns** [comment]
Thanks, it got fixed.
