### ISSUE TITLE
Split permissions.yml

### ISSUE THREAD

**Issue by Snipershotmaster** [PEXPlugins/PermissionsEx#2162]
For me mysql is too slow for syncing ranks (simply takes bout 2-3 hr) and i would like to try a new method. However for this method i need to split permissions.yml into two different files... A permissions.yml file (for storing ONLY ranks and permissions) and a Users.yml (for storing player related data). Can u please add such thing?

**Comment by zml2008** [comment]
PEX1 will not be getting any new features, but a way to split backends will be supported for PEX2

**Comment by Snipershotmaster** [comment]
Where can i get PEX2?

**Comment by zml2008** [comment]
the future.
