### ISSUE TITLE
Server crashes on launch after installing PEX

### ISSUE THREAD

**Issue by SilentDeathTheSeal** [PEXPlugins/PermissionsEx#2165]
After I put pex into my mods folder and launch my server this is what happens:
https://gyazo.com/b047c0731c02b1ef797f38a32b66b1d9

Crash report: http://pastebin.com/FryGS6D6

And here's a pic of my mod folder:
https://gyazo.com/1244e08484d5d1c8e63ee95080239fec

**Comment by zml2008** [comment]
Update your PEX build.
