### ISSUE TITLE
New Permission . permissionex Disables.

### ISSUE THREAD

**Issue by sharkybushbaby** [PEXPlugins/PermissionsEx#2169]
This may be a Very Simple thing , But i have never come across it before. and ive been running this for a few years.
It could very well be me poorly writing the perms. 

Currently everything works fine regarding Permissions. and plugins. But NOW, when i add a new permission to a group. Permissionex disables. and obviously All Perms and classes fail. 

any one able to help out ?

**Comment by zml2008** [comment]
Then there's a syntax error in your permissions file. Check it at http://yaml-online-parser.appspot.com.
