### ISSUE TITLE
Garbage in the database

### ISSUE THREAD

**Issue by Sitmobedaf** [PEXPlugins/PermissionsEx#2176]
Very difficult to work with the database when there is so much garbage.

Example: http://pastebin.com/8YqZeiba

**Comment by Stormbow** [comment]
Those look like UUIDs of users that have no permissions, no special anything about them.  i.e., people who joined the server, did nothing, and never came back.  Delete them and cleanup your user list:

/pex users cleanup <group> [threshold]
    Clean users of specified group, which last login was before threshold (in days).
