### ISSUE TITLE
Permission updating issues with inheritances

### ISSUE THREAD

**Issue by EvilOlaf** [PEXPlugins/PermissionsEx#2183]
Hello,

I set up various user groups with inheritances.
- Guest as some basic permissions
- User has some additional permissions and inheritance Guest
- AdvancedUser has some additional permissions and inheritance User (and automatically inheritances Guest too)

and so on.

If I add a permission node to Guest for example, this takes effect for users in group Guest immediately. Unfortunately users in the group User or AdvancedUser have to relog till they have access to their new permission.
Is there a way to flush the permission cache for all online users when a change happens?

PEX1.23.3
Spigot 1.8.8

Thanks for reading.

Best regards
Olaf

**Comment by zml2008** [comment]
PEX2.x (still in development) fixes caching issues, but until that's ready you'll want to just /pex reload

**Comment by EvilOlaf** [comment]
Aight, thanks.
