### ISSUE TITLE
1

### ISSUE THREAD

**Issue by MrNanox** [PEXPlugins/PermissionsEx#2186]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/e6a127fbd6cd1bec6f1c)

**Comment by Stormbow** [comment]
I believe that means you've got 2 schema-version lines in your SQL database. Keep the schema-version: 1 entry, delete the other.

**Comment by MrNanox** [comment]
Thank you.
