### ISSUE TITLE
Pex

### ISSUE THREAD

**Issue by chipydamunk** [PEXPlugins/PermissionsEx#2189]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/8208bf6cb1a918ed959b)

6:24:45 AM java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
6:24:45 AM 	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
6:24:45 AM 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
6:24:45 AM 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
6:24:45 AM 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
6:24:45 AM 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
6:24:45 AM 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
6:24:45 AM 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
6:24:45 AM 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
6:24:45 AM 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
6:24:45 AM 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
6:24:45 AM 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
6:24:45 AM 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235)
6:24:45 AM 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504)
6:24:45 AM 	at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
I think that means you're using the wrong version of Guava, bad build of Spigot or somesuch.

**Comment by zml2008** [comment]
Yeah, you're using a 1.7 version of PEX on a 1.8 server.
