### ISSUE TITLE
All Groups Default

### ISSUE THREAD

**Issue by RustyDesigns** [PEXPlugins/PermissionsEx#2191]
Help!
My server runs off of PEX with mysql backend, all groups are set to default, enabling players to set their own group. Not Good! How can I fix this! Please Help!

**Comment by Stormbow** [comment]
Follow the [Basic PEX Tutorial](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69393-basic-permissions-ex-tutorial/#p1) about how to make only one group the default.
