### ISSUE TITLE
SQL Error that someone else also posted.

### ISSUE THREAD

**Issue by piratYT** [PEXPlugins/PermissionsEx#2193]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/62963962d5e855280584)

**Comment by CzEMC** [comment]
According to line of the the pex stack trace:
`ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'`

Try backing up data then dropping all tables that pex is related to. Let pex rebuild them. Then, re upload only the SQL data to the database.

Hope this helps.

**Comment by Stormbow** [comment]
This is a common error for databases which have 2 lines of "schema-version: 1" when there should be only 1.  Remove one.  The problem goes away.
