### ISSUE TITLE
Pex problems/SQL/Some features requested

### ISSUE THREAD

**Issue by James-Inglis** [PEXPlugins/PermissionsEx#2195]
Hello,

I love using PEX as it is one of the best Permissions plugins and the only one I like using. However, when I made my server a Bungeecord server I started having problems.

If you change someone's group it doesn't sync correctly across all the other servers. You have to do /pex reload (which crashes/holds the server for about 10 seconds meaning everyone freezes and the only thing that works in the chat but not commands) every single time and even sometimes that doesn't work. I have set it up to a SQL Database and put the plugin on every server to read from the database.

Features I would love to see and make the plugin more helpful/easier to use:

Better SQL support: Some how better syncing or something along them lines.

Server permissions: As well as having world permissions server permissions will make this plugin so much better and easier to use. It will also help cut down on size of the file/database. One each server that you install PEX to you give the server a name in the config which you will name in the permissions file. (Like bungeeperms).

Import file: When you import the file onto the SQL database it will save everything onto the database. But I think you should be able to import it again, and It will overwrite/delete the perms that have changed so it doesn't stack the permissions.
 
Thank you

**Comment by zml2008** [comment]
Per-server permissions are already supported in PEX 2.0. (However, SQL has not yet been implemented, which is an issue I guess)

SQL in PEX 2.0 will have a more reliable syncing method hopefully (I still have to look into how this would work)
