### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by RebelLP** [PEXPlugins/PermissionsEx#2196]
Hello, For your plugin error occurred. Vic here >> http://pastebin.com/UcVt4ya5. I'll be glad when I help you correct the error.

**Comment by Stormbow** [comment]
I believe you have 2 schema-version lines in your database.  Remove one, keep schema-version: 1 as the correct entry.

**Comment by RebelLP** [comment]
Oh I do not understand you very much. Could not you send me a version already set as config. Because I do not know much advice was repeated.
