### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by RebelLP** [PEXPlugins/PermissionsEx#2198]
Hello,

I would have to ask a favor. Could you tell me to create a plugin. Where would the tab, it showed its prefix and chat and even next to nick players? The point is that we had no plugin also found. And could you add it to your plugin Permissions Ex.Oh, and could you have for ex Permissions remove witch you should visit was not to chat're adding permisse?

**Comment by Stormbow** [comment]
Sorry, this isn't the place to learn programming.  Try YouTube and Google for tutorials.
