### ISSUE TITLE
SQL wont import users

### ISSUE THREAD

**Issue by Mikgreg** [PEXPlugins/PermissionsEx#2199]
Hi, 

I'm trying to move some of my servers over to use a MySQL backend as our file is growing rather large & laggy. I've followed the steps listed & connected PEX to my DB, then I run

/pex import file

The server freezes up for a bit, and SOME users get converted, and the majority of users do not appear in the database.

As well as this, the users who WERE converted lose all their permissions when they join the server.

Any idea how I can fix this?

**Comment by zml2008** [comment]
Disable any sort of server watchdog that will stop the server if it doesn't advance -- because of how PEX1.x works, the conversion will freeze up the server. You'll have to let it run until it's done. Then things should work.

**Comment by Mikgreg** [comment]
Nothing is stopping the conversion, I tried it again today on a blank server with nothing configured/installed.

I should be in the owner group, but again its only converting *some* users.
http://i.imgur.com/3ByEjsc.png

The conversion finishes, but doesnt show everyone.

**Comment by Mikgreg** [comment]
Any info on this? Kinda needing  a working mysql db soon :( Would a lot of users being in the file prevent it from working? I've been able to convert an almost-empty file fine, but this big one is refusing.

**Comment by Traxity** [comment]
Not sure, but id use  the almost empty file (is this for PVP)

**Comment by Mikgreg** [comment]
The smaller file is a test file..

**Comment by Traxity** [comment]
Oh, ill check my My SQL db

**Comment by Traxity** [comment]
Is it ported properly mike?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
