### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PiratesDawn** [PEXPlugins/PermissionsEx#2207]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/0199caa0067be69d0954)
01.11 13:47:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
01.11 13:47:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
01.11 13:47:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
01.11 13:47:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
01.11 13:47:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
01.11 13:47:35 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
01.11 13:47:35 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
01.11 13:47:35 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
01.11 13:47:35 [Server] INFO java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
01.11 13:47:35 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/vl88p. Full error:

**Comment by zml2008** [comment]
You're using the wrong PEX version for your server version. Update.
