### ISSUE TITLE
CacheBuilder not found

### ISSUE THREAD

**Issue by RWCraft** [PEXPlugins/PermissionsEx#2210]
### Description ###

Booted up my server and pex didn't load
### Detailed Information ###

[Is available here](https://gist.github.com/21b545044117e2d0da92)

**Comment by MeMyselfMC** [comment]
Same issue here, occurred after restarting all my back-end servers to update a couple of plugins including WorldEdit and Multiverse-Core.

**Comment by zml2008** [comment]
You're running 1.22.x, which is only for 1.7.x versions of MC, on a 1.8 server. Update PEX to the latest version...

**Comment by MeMyselfMC** [comment]
@zml2008 It's happening to me with v1.23.3 though.
