### ISSUE TITLE
Get * Permission just with OP

### ISSUE THREAD

**Issue by PyroGameZ** [PEXPlugins/PermissionsEx#2211]
I´ve found a new bug and hope, that it get fixed. Cause if you have OP you can use everything in PEX, just entering the Command in a CommandBlock. Can you surround the Command with as example that?
"if(!(sender instanceof BlockCommandSender))"

I hope you fix/make that.

Great Thanks
PyroGameZ :D

**Comment by zml2008** [comment]
Don't give op to people you don't trust.
