### ISSUE TITLE
Pex eror

### ISSUE THREAD

**Issue by jaconah** [PEXPlugins/PermissionsEx#2212]
Not fully sure what happend, it was working just fine then i restarted the server to update a few plugins and when ever my friend got back on this came up in conlse

 Full error:
05.11 14:27:42 [Server] INFO java.lang.RuntimeException: java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:121)
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:165)
05.11 14:27:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
05.11 14:27:42 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
05.11 14:27:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
05.11 14:27:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628)
05.11 14:27:42 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404)
05.11 14:27:42 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368)
05.11 14:27:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
05.11 14:27:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
05.11 14:27:42 [Server] INFO at java.lang.Thread.run(Thread.java:745)
05.11 14:27:42 [Server] INFO Caused by: java.lang.RuntimeException: Default user group is not defined. Please select one using the "default: true" property
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.getDefaultGroup(FileBackend.java:138)
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:295)
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.PermissionManager.getDefaultGroup(PermissionManager.java:284)
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.bukkit.commands.GroupCommands.groupDefaultCheck(GroupCommands.java:660)
05.11 14:27:42 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.11 14:27:42 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05.11 14:27:42 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05.11 14:27:42 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497)
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.commands.CommandsManager$CommandBinding.call(CommandsManager.java:252)
05.11 14:27:42 [Server] INFO at ru.tehkode.permissions.commands.CommandsManager.execute(CommandsManager.java:114)
05.11 14:27:42 [Server] INFO ... 10 more

**Comment by slkjoy** [comment]
It looks like the default user group got un-set somehow.

**Comment by jaconah** [comment]
It is still set in the file though

**Comment by jaconah** [comment]
see right here 
"
  user:
    options:
      prefix: '&8&l[&fUser&8&l]&r'
      default: true
    permissions:
"

and what is the current most stable version of pex

**Comment by slkjoy** [comment]
I’m just another user, not part of the dev team. I read the error messages and saw the message about the default user group not defined.

I can only make suggestions until the dev responds - you are free to ignore of course.

Since you mentioned that you had installed several plugins since PEX last worked without errors, I would investigate whether one of those plugins conflicts with PEX somehow, or is over-riding PEX configuration settings. You could also try re-installing PEX and make sure you have the latest version for your server version. That’s just what I would try next. Best of luck!

**Comment by zml2008** [comment]
@jaconah You're using an ancient version of PEX, and your permissions file has the new format to specify the default group. Update to the most recent version of PEX for your MC version.

**Comment by jaconah** [comment]
The new version of pex just crashes
