### ISSUE TITLE
Issue with PermissionsEx

### ISSUE THREAD

**Issue by YoloxPanda** [PEXPlugins/PermissionsEx#2214]
### Description ###
PermissionsEx wont load on startup.

### Detailed Information ###
[03:34:45 INFO]: PermissionsEx version 1.22.9

Stack trace -> (https://gist.github.com/YoloxPanda/8a41bb56ef52790833dc/)

**Comment by zml2008** [comment]
You're using the wrong version of PermissionsEx for 1.8 servers.

**Comment by YoloxPanda** [comment]
Thank you so much! :)
