### ISSUE TITLE
Plugin Error since switching with new hosts.

### ISSUE THREAD

**Issue by ReaverRapier** [PEXPlugins/PermissionsEx#2217]
Hello, my server has recently encounter this new plugin problem with PEX since we switched hosts. Before switching, it never showed anything of this. After and a day later, it began to show errors with the plugin not enabling and preventing everyone on the server (besides OPs) to not be able to do anything.

08.11 10:34:18 [Server] INFO at java.lang.Thread.run(Thread.java:745)
08.11 10:34:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
08.11 10:34:18 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
08.11 10:34:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
08.11 10:34:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
08.11 10:34:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
08.11 10:34:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
08.11 10:34:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
08.11 10:34:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
08.11 10:34:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
08.11 10:34:18 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
08.11 10:34:18 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
08.11 10:34:18 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
08.11 10:34:18 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
08.11 10:34:18 [Server] INFO java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
08.11 10:34:18 [Server] INFO [10:34:18 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/v8BwC. Full error:

**Comment by zml2008** [comment]
Update PEX
