### ISSUE TITLE
User permissions are removed too early in PlayerQuitEvent, causing lag.

### ISSUE THREAD

**Issue by ItsHarry** [PEXPlugins/PermissionsEx#2221]
User permissions are currently removed using PlayerQuitEvent(priority = NORMAL) in the PermissionsEx.PlayerEventsListener class.

This causes permissions to have to be re-loaded if other plugins call Player.hasPermission() in PlayerQuitEvent using any priority that is higher or equal to NORMAL. Many plugins including NoCheatPlus and some of my own plugins do this, leading the server to be blocked for an unnecessary time every time a player logs off.

The fix is changing the priority of the PlayerQuitEvent in PermissionsEx.PlayerEventsListener to HIGHEST or even MONITOR.

**Comment by zml2008** [comment]
Thanks for giving such a detailed suggestion! When I have time I'll add this -- have you tested the fix locally at all?

**Comment by ItsHarry** [comment]
I haven't done very detailed testing, all I did was change the priority to HIGHEST and compile that, which seemed to work fine.

The one thing I can think of that needs to be looked into if you decide to use MONITOR is making sure it is called before the one in SuperpermsListener, the one that removes the permission attachment.

**Comment by ItsHarry** [comment]
I've got it running on HIGHEST priority for about three days now since my last reply, seems to be working just fine.

**Comment by zml2008** [comment]
This is still relevant for the Spigot version of PEX 2.0, so I've fixed it there. Backporting will happen as I have time.
