### ISSUE TITLE
SQL not importing users

### ISSUE THREAD

**Issue by Mikgreg** [PEXPlugins/PermissionsEx#2222]
Continuation from this issue:
https://github.com/PEXPlugins/PermissionsEx/issues/2199

Nothing is stopping the conversion, I tried it again today on a blank server with nothing configured/installed.

I should be in the owner group, but again its only converting some users.
http://i.imgur.com/3ByEjsc.png

The conversion finishes, but doesnt show everyone.

**Comment by zml2008** [comment]
Let's keep this in the previous issue.
