### ISSUE TITLE
PEX not work

### ISSUE THREAD

**Issue by yair1212** [PEXPlugins/PermissionsEx#2223]
the plugin is not work for me i use all  method and i see all the videos and its steal not work
what i need to do????

(https://gist.github.com/ceeeaa70565dd75d07e5)

**Comment by yair1212** [comment]
and the full erorr is (17:02:49 java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
17:02:49 	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
17:02:49 	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
17:02:49 	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163)
17:02:49 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
17:02:49 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
17:02:49 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
17:02:49 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
17:02:49 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
17:02:49 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
17:02:49 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
17:02:49 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
17:02:49 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
17:02:49 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
17:02:50 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
17:02:50 	at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
When was the last time you updated your Java?
