### ISSUE TITLE
PEX 1.23.3 Group Bug on Craftbukit 1.8.8

### ISSUE THREAD

**Issue by craigbrian** [PEXPlugins/PermissionsEx#2224]
When adding permissions to Pex that are close to other groups they are added to the wrong one for example
/pex group B add prisonprofessional.sellall.B
/pex group D add prisonprofessional.sellall.D
/pex group M add prisonprofessional.sellall.M
/pex group O add prisonprofessional.sellall.O
Permission "prisonprofessional.sellall.B" added to group "Builder"!
Permission "prisonprofessional.sellall.D" added to group "Default"!
Permission "prisonprofessional.sellall.M" added to group "Manager"!
Permission "prisonprofessional.sellall.O" added to group "Owner"!

/pex group B add prisonprofessional.rank.B
/pex group D add prisonprofessional.rank.D
/pex group M add prisonprofessional.rank.M
/pex group O add pprisonprofessional.rank.O
Permission "prisonprofessional.rank.B" added to group "Builder"!
Permission "prisonprofessional.rank.D" added to group "Default"!
Permission "prisonprofessional.rank.M" added to group "Manager"!
Permission "prisonprofessional.rank.O" added to group "Owner"!

These all need to bed added manually in the permissions now and sometimes it can be very frustrating especially when people don't space the permissions correctly and it crashes the entire permissions file.

Also these never appear in console only in game it will say when they are added to a group.
Group Manager never did this. and we were force to switch to PEX for plugin permission issues and corruption to group files. Is it possible this can be fixed by Thursday for PEX 1.7.10 and 1.8?

**Comment by zml2008** [comment]
This is due to the fact that old PEX tried to do async updating without retrofitting a lot of the commands and API to be aware of it, so some value tearing would occur. This should be cleared up in PEX2
