### ISSUE TITLE
error with mysql...

### ISSUE THREAD

**Issue by Freakyfelix** [PEXPlugins/PermissionsEx#2227]
### Description ###

hello  , i cant use mysql with pex. I did it like in tutorials, with config edit and /pex import file. but if my server is starting I get this error : http://hastebin.com/omedegakeg.coffee

But what is wrong with "prefix"?

thanks for help! <3

### Detailed Information ###

[Is available here](https://gist.github.com/96640a72363061eda03e)

**Comment by Freakyfelix** [comment]
No idea?^^

**Comment by zml2008** [comment]
Delete your MySQL tables and start over from the beginning. Seems like you started with an older version of PEX that had some issues with importing.

**Comment by Freakyfelix** [comment]
I already tried this many times, still this error. I'm using Pex 1.23.3

**Comment by Freakyfelix** [comment]
please help.

**Comment by Freakyfelix** [comment]
??

**Comment by Freakyfelix** [comment]
....

**Comment by Freakyfelix** [comment]
hello???
