### ISSUE TITLE
[Sponge] Could not pass PlayerLoggedInEvent to SpongePlugin

### ISSUE THREAD

**Issue by minequery** [PEXPlugins/PermissionsEx#2228]
Updated to latest sponge as of today: Sponge 1.8-1568-2.1-DEV-828

Permissions are not working after updating.

On startup:
http://pastebin.com/sYL4qXbV

On playerlogin:
http://pastebin.com/3qYCmH34

**Comment by zml2008** [comment]
This should be fixed with build 94 on ci.yawk.at -- it just required a rebuild.
