### ISSUE TITLE
ERROR WITH PEX

### ISSUE THREAD

**Issue by orionweblab** [PEXPlugins/PermissionsEx#2230]
PLEASE HELP
Log:
9:09:23 AM [ERROR] [PermissionsEx] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2Fc074a38817c161b44cbc%29%0A. Full error:
9:09:23 AM java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
9:09:23 AM at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
9:09:23 AM at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
9:09:23 AM at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
9:09:23 AM at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
9:09:23 AM at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
9:09:23 AM at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
9:09:23 AM at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:338)
9:09:23 AM at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:311)
9:09:23 AM at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394)
9:09:23 AM at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362)
9:09:23 AM at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317)
9:09:23 AM at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190)
9:09:23 AM at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:477)
9:09:23 AM at java.lang.Thread.run(Unknown Source)

[Is available here](https://gist.github.com/c074a38817c161b44cbc)

**Comment by zml2008** [comment]
You're running PEX 1.22.x on a 1.8 server. Update.
