### ISSUE TITLE
PEX 2.0 Case sensitive user name returns incorrect information

### ISSUE THREAD

**Issue by Nutmegan** [PEXPlugins/PermissionsEx#2232]
Version Details
spongeforge-1.8-1568-2.1-DEV-833.jar
forge 1568
PEX 2.0 build #49

When entering the command, 
/pex user Nutmegan info

The returned value is:
Information for user Nutmegan

Nothing else. However, if I enter the same command with user name in all lower case the returned value is:
Information for user  ---UUID here---/Nutmegan
Options:
  Global:
    name=Nutmegan
Parents:
  Global:
    group: guest
    group: srmod

It seems somewhere the code is looking for user as all lower case.

---

Possibly a related issue...
The first time a user joins, if you modify the permissions via user name commands a record will be created for the user under their name but with no UUID recorded. If they log out and back in, a second record with the user name and UUID will get created and will not be associated to the first entry. Allowing the user to log out and back in before making modifications prevents the disassociated records from happening. It seemed entering the user information with all lower case also prevented this.

**Comment by zml2008** [comment]
Currently uuids are only looked up for users who have already logged in. I'm working on some commands changes that will allow new uuid lookups to happen without freezing the game.

The case-sensitivity issue will need some more looking into.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
