### ISSUE TITLE
MySql change

### ISSUE THREAD

**Issue by MatteCarra** [PEXPlugins/PermissionsEx#2234]
I think that MySql would be better if you move rank number from table "permissions", because a bungee server can want to have the same rank on every server for every player but not equal permissions!

**Comment by zml2008** [comment]
1) Sharing some but not all tables across servers is not a supported way of providing multiserver support
2) Ranks are in their own table in PEX 2.0 (once SQL is implemented they will be at least)
3) There is a server-tag system in PEX 2.0 that allows certain permissions assignments to be restricted by server, meaning you can share the same tables across all your servers
4) There will also be a more featureful multibackend, which will allow you to have data from multiple sources (like multiple sets of tables, or file and database) combined when looking up permissions in a supported manner.
