### ISSUE TITLE
Losing timed permissions after relog

### ISSUE THREAD

**Issue by Pixiio** [PEXPlugins/PermissionsEx#2236]
Hi. When a user with a timed permission relogs the permission is removed from the user. Is this a bug? Or is there any way to change this?

Spigot 1.8.8. 
PermissionsEX v1.23.3.

Thanks in advance.
Pixiio

**Comment by zml2008** [comment]
This is by design. In PEX 1.x, timed permissions are only stored in-memory. Timed groups are stored in files.

This will change in PEX2 -- any permissions data will be able to be timed, not just inheritance.
