### ISSUE TITLE
User group adding

### ISSUE THREAD

**Issue by Orenthion** [PEXPlugins/PermissionsEx#2240]
Currently when using the commands `/pex user <user> group add <group>` and  `/pex group <group> user add <user>`, the group is added to the top of the list, which causes problems. It would be nice if it were added to the bottom of the already added groups, to follow group precedence.

If the above isn't possible because there is another reason why its automatically added to the top, it would be nice to have groups ordered based on ladder rank, that way ranks with higher precedence will be read first.

**Comment by Stormbow** [comment]
I'm betting that you don't know about weight values.  Am I right?  ;)

**Comment by Orenthion** [comment]
Ah thank you! I can't believe I missed that in the documentation. All set now.
