### ISSUE TITLE
I cannot get Permissions Ex to work

### ISSUE THREAD

**Issue by ChazRead** [PEXPlugins/PermissionsEx#2241]
This is what my console comes up with every time:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder; at ru.tehkode.permissions.RegExpMatcher.(RegExpMatcher.java:17) at ru.tehkode.permissions.PermissionManager.(PermissionManager.java:58) at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:163) at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) at java.lang.Thread.run(Unknown Source)

**Comment by Stormbow** [comment]
I believe this is a matter of your Guava needing to be updated.

**Comment by zml2008** [comment]
update PEX to the latest version
