### ISSUE TITLE
Big problem with PEX

### ISSUE THREAD

**Issue by xavikrac1** [PEXPlugins/PermissionsEx#2248]
Hello i have a BIG problem with Pex, i am 1 month trying to resolve this and nothing :/ i pay 50€ for the man that resolve this. I have a similar problem to this: https://github.com/PEXPlugins/PermissionsEx/issues/2125
I have all minigame synced with mysql, and all good, but when i go to give admin to a users, he recive the rank in the lobby2 that we are, but if he go to lobby4, he haven´t got the rank, and is posible that if he reconnect to lobby4 he have the rank, or if he go to the lobby1, he have the rank at the first time. Is very rare, i tried all, changing the mysql server and all... please HELP. 50€ for repair this.

**Comment by Stormbow** [comment]
**Note:** Xavikrac1 is not interested in using NetEvents which is a likely solution to his problem.
