### ISSUE TITLE
por que no puedo poner permissionEX en mi server network

### ISSUE THREAD

**Issue by TheM85** [PEXPlugins/PermissionsEx#2249]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/848b10034db484c174c3)

**Comment by TheM85** [comment]
Porfavor ayudenme D:

**Comment by zml2008** [comment]
You're using 1.7.2 -- a super old version of MC. PEX requires at least 1.7.5 -- though preferably 1.8.

(y en español, pero no puedo hablar bien español)
No puedes usar Minecraft 1.7.2 con los versiones nuevos de PEX. Necesitas usar MC 1.7.5+ (pero prefiero 1.8+).
