### ISSUE TITLE
Can not build with PEX as maven dependency

### ISSUE THREAD

**Issue by Trojaner25** [PEXPlugins/PermissionsEx#2250]
```
Failed to collect dependencies at ru.tehkode:PermissionsEx:jar:1.23 -> 
net.gravitydevelopment.updater:updater:jar:LATEST: Failed to read artifact descriptor for 
net.gravitydevelopment.updater:updater:jar:LATEST: Failed to resolve version for 
net.gravitydevelopment.updater:updater:jar:LATEST: Could not find metadata 
net.gravitydevelopment.updater:updater/maven-metadata.xml
```

Pom:
https://github.com/Static-Interface/ReallifePlugin/blob/master/pom.xml

Full build log:
http://hastebin.com/cetizomocu.tex

**Comment by zml2008** [comment]
1) Build against Vault
2) If you can't build against Vault, then make sure you have the PEX repo (https://pex-repo.aoeu.xyz) in your pom.

**Comment by zml2008** [comment]
Further update: I've manually deployed Updater to PEX's maven repository so if you really need to use PEX this should build properly now.

**Comment by Trojaner25** [comment]
thx
