### ISSUE TITLE
Mysql quirk

### ISSUE THREAD

**Issue by s32ialx** [PEXPlugins/PermissionsEx#2251]
Hey it's me again with another Mysql quirk,

This one I'm not sure if you did this intentionally or not but your table design for 'Permissions' you have 
'world' and 'value' flags set that they must not be null (for when manually entering entries via 3rd party programs like Navicat)

Why I'm unsure of this is because when you run a command lets say for instance

in game / console
>/pex group default add chatex.allowchat

>/pex group Admin set rank 1

it enters the entry just fine, but if I'm adding a db entry by hand 
those to example are null in the area's that you have marked as must not be null

id |   name |  type |         permission | world | value 
---|----------|--------|----------------------|--------|--------
5 |  default |      0 | chatex.allowchat |   null |    null
6 |   Admin |      0 |                    rank |   null |        1

but when I submit a new entry that was not generated ingame it says 'field world does not have a default value' lol I can work around it by putting a 0 and then submitting that than removing the 0 and resubmitting the entry... lol.

**Comment by s32ialx** [comment]
Setting the default value to empty string alleviates this issue

**Comment by zml2008** [comment]
Yeah, we use empty string instead of null in a lot of places -- I'm not sure why anymore, probably because nulls are weird in SQL
