### ISSUE TITLE
PEX sponge doesn't work

### ISSUE THREAD

**Issue by Likton** [PEXPlugins/PermissionsEx#2255]
Hi! Me again ! :)

I'm trying to run clear your plugin on my sponge server. It's seems to work, but I've tried to modify the file permissionsex.conf to have the permssions on a sql database, but it seems to crash the plugin.

My permissions.conf file:
http://puu.sh/lTPnw/1700e8132e.png

Furthermore, when I remove the lines I've added, the /pex cmd seems to be locked
http://puu.sh/lTPQc/4810adf30a.png

**Comment by zml2008** [comment]
SQL is not implemented yet -- and that issue you're getting is because you need to update PEX -- it should be fixed once you use the latest builds of both PEX and Sponge.
