### ISSUE TITLE
Just a small problem with a permission.

### ISSUE THREAD

**Issue by xElitaa** [PEXPlugins/PermissionsEx#2256]
Okay, so my friend is running a server with the latest PEX for 1.8, and most permissions are working fine. But we can't figure out how adding /entitydata to a permissions works. Everything we have tried so far won't work, including:
Minecraft.commands.entitydata
Commands.entitydata
and Essentials.entitydata

What prefix for .entitydata will allow it to be added to a group?

Thanks

**Comment by zml2008** [comment]
Depends on which plugin is offering `/entitydata`. Run `/pex toggle debug` to have permissions queries output to the console.
