### ISSUE TITLE
PEX MySQL userdata

### ISSUE THREAD

**Issue by InterStena** [PEXPlugins/PermissionsEx#2257]
Hello! I'm using pex with mysql backend on multiple servers (multiple permissions tables like "server1_permissions", "server2_permissions"). I want to create a single table for all users inheritance (like global_usersinheritance)? The problem is that PEX storing userdata and group inheritance in one table (pex_inheritance). Can I store my group data in different tables and my userdata in a single table?

**Comment by zml2008** [comment]
No. PEX2 will have more complete multi-backend support which will allow you to store data separately and already has support for setting server-specific data (but does not support SQL yet).

**Comment by Someone-NEW** [comment]
Dont forget to SQL support  ;)

**Comment by QUIQUELHAPPY** [comment]
Hi.
How do we integrate that? I didn't find any page on the wiki...
