### ISSUE TITLE
Trying to remove a default permission

### ISSUE THREAD

**Issue by mjcrafter100** [PEXPlugins/PermissionsEx#2259]
I am trying to remove players access to
crackshot.buy.all
to no avail. please help, I have tried everything ;-;

**Comment by Stormbow** [comment]
You'll need to post a Pastebin link to your permissions.yml file, and include much more specific information about the problem such as which user has access to the permission node and which group they are in when they //should not// have access to the permission node.

**Comment by Stormbow** [comment]
No response in more than 7 days. Issue must be resolved.
