### ISSUE TITLE
Timed permission Suggestion!

### ISSUE THREAD

**Issue by Someone-NEW** [PEXPlugins/PermissionsEx#2260]
No great solution in this tread find.

I have a suggestion to make better timed permissions and groups make separate timed.yml for using that, only for timed things or use like .JSON file for that options and saved this type of data. Than make so the server owner can use option UUID set to true or false when use to true will plugin use a UUID system when false will use a normal user names system and add option for convert betwen UUID/offline player names in this file timed.yml to. This will be used to store that timed data here to. Than make so that permissions and commands will not be changed, only plugin will write some more usefull data for easy handle, for example when Server owner use this command: pex user "player" timed add essentials.fly 14400 (this is from my voteRoulete plugin for fly 4 Hours) thta plugin will store mutch more data in that store file like for example: - the beginning: 16:23h PM 16.12.2015 / - expires: 20:23h PM 16.12.2015 this is example how will be look in that stored files and plugin will read this when will be server restarted or start again and when will some date expired will be removed from list when is not expired will be automaticaly enabled again and use this timed function from that timed.yml file. This muss be make so, for all like groups or only for permissions but when player with rank have already fly permission from their group in permissions.yml they will have this timed from timed.yml removed but not from the group rank in permissions.yml and when we use a timed group for example Voter this will be removed from timed but will not be removed rank VIP from permissions.yml file that they already have, so player still have that rank to with all permissions from there. Ok this is my explanation for easy and more secure and configurable to make this things, but test first this will be awesome. I hope your programmers will lokup this suggestion and report me when they will do this? please mak a ticket for that suggestion or somehow i dont know using github im never used it. this to make will be raly awesome plese tell me some nem and god news from programmers thak you all for your work about that plugin. Guys this plugin for perms is the best and i hope will be soon fixed this, thanks Sorry for bad English im Slovenian.

And I see someone are already done with this? here: https://www.spigotmc.org/resources/permissiontimer.4792/ but is for Paid i cant use that so only for info i dont know how it works.

Merry Christmas and Happy New Year 2016!

**Comment by Someone-NEW** [comment]
I have ONLINE server so this is for bungee ar normal server like me tha i have only one server but need timed permission to work thanks

**Comment by Someone-NEW** [comment]
What version is that plugin to http://azminecraft.info/permissionsex-plugin/ test this and no work to. :(

**Comment by EvilOlaf** [comment]
You should not get your plugins from unofficial sources. They may have been modified to contain bad code or stuff.
Get your plugins from spigotmc.org or dev.bukkit.org or from Jenkins CI if a developer tells you to do so.

**Comment by Someone-NEW** [comment]
A ok you mean about that from link? ok i use it on test server but i will removed it thaks

**Comment by Someone-NEW** [comment]
Ohh nothing work all about timed is crap for now sorry but unusefull

**Comment by Someone-NEW** [comment]
Welcome again i test PermissionsEx v1.23.4 and the Timed permissions not work again that one is hard needed by me and other but not work i test this one /pex user MyName timed add essentials.god 14400
and when i leave server and join again i lose permission for that /god command using on /vote awards for example so when will be this fixed?
I suggest you make this to be separated stored like a groups but we need separate for only some permissions with groups to. Thank you. i Use Spigot 1.8.8 java 8

**Comment by EvilOlaf** [comment]
This is actually not a bug. Timed permission on a user are not persistent which means that you lose them on disconnect. 
To work around this 'issue'  create a new user group which only contains the permission node what you want to give a user for a limited time. 
Them you add this user for a specific time to this group. 

Pex user playername group add yourtimedgroup '' 3600

This will grant the player playername all permission from the group yourgroupname in all worlds for one hour. These permissions are now persistent and will be tracked through disconnects.

**Comment by Someone-NEW** [comment]
"create a new user group" This one i have tested alon time ago and is 100% stupid to do this in that way so when using this i have a lot problems with other ranks that not have some permissions in this case is a bug. Another thing we realy need separate only for Timed permissions this is the only one what we need to be fixed maybe not save in memore but save to file think about that maybe.
When people give a fly permission for 1 hour and when disconect and rejoin again muss have this permission WITHOUT any Groups added. Muss work for all ranked players and Default ranked players without losing other permissions when player have a some rank.
Please fixing this one will be helfull. We use Prefixes suffixes and so one tags and i dont want to change any prefix when some ranked player has voted ..............
thank you again for work about this.

**Comment by EvilOlaf** [comment]
Why should you get issues with your existing groups? As written the user will be added to this group as a secondary group, not as primary. That is why you see `add` and not `set` in the command above. 
If your secondary groups do not have set pre- or suffixes they should not be overruled also.

Anyway, version 1.x from PermissionsEX would probably not receive any features updates or fixes like this one as a functional workaround exists. So if you want to have this fixed/working your way you like you need to wait for PEX 2.0 to be released. @zml2008 might answer this further.

**Comment by Someone-NEW** [comment]
Yea i am already do this before and then with a many players issues i deleted this timed groups thing and i use only timed permissiond is bad but i have no choice while not working by me. Only when wil work saved timed permissions only this will be helped. Thank you for your response.
I think Timed permissions is not god choice to be saved in memory muss be saved on file like a groups but separated file for this and working toghether with timed groups, this is my suggestion when you all can do that so. Thanks all.

**Comment by RAZERMC** [comment]
I second this post please save the temporary permissions to file or mysql like the groups like i want to set a temporary permission to last a day but i have to do some maintenance and have to restart the server the users loose their temporary permission instantly. Now about the work around this is not full proof it causes conflicts with permissions. Please add file or mysql backend saving for temporary permissions it will help us a lot

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
