### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by captincreeper1** [PEXPlugins/PermissionsEx#2262]
Ok i am trying to install permissionsex on sponge 1.8 and cannot i have created the files and gives me a bunch of errors whenever i type a command when it is installed then fine when it is not installed please help.

Error:

19.12 15:27:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2952f4e7(success)
19.12 15:27:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@53c2ce60(success)
19.12 15:27:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4102932e(success)
19.12 15:27:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@5dc8ac69(success)
19.12 15:27:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@59bfca9b(success)
19.12 15:27:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@13d9134(success)
19.12 15:27:04 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6e8d329f(success)
19.12 15:27:03 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@3dfb2e9c(success)
19.12 15:27:02 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
19.12 15:27:02 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
19.12 15:27:02 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
19.12 15:27:02 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
19.12 15:27:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
19.12 15:27:02 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:84) [ih.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) [rj.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) [rj.class:?]
19.12 15:27:02 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [cl.class:?]
19.12 15:27:02 [Server] INFO at org.spongepowered.api.command.SimpleCommandManager.process(SimpleCommandManager.java:249) [SimpleCommandManager.class:1.8-1577-2.1-DEV-0]
19.12 15:27:02 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:334) ~[SimpleDispatcher.class:1.8-1577-2.1-DEV-0]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.sponge.PEXSpongeCommand.process(PEXSpongeCommand.java:43) ~[PEXSpongeCommand.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.util.command.CommandSpec.process(CommandSpec.java:166) ~[CommandSpec.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.util.command.CommandSpec.getUsage(CommandSpec.java:238) ~[CommandSpec.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.util.command.args.GenericArguments$OptionalCommandElement.getUsage(GenericArguments.java:746) ~[GenericArguments$OptionalCommandElement.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.util.command.args.GenericArguments$FirstParsingCommandElement.getUsage(GenericArguments.java:637) ~[GenericArguments$FirstParsingCommandElement.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.util.command.ChildCommands$ChildCommandElement.getUsage(ChildCommands.java:130) ~[ChildCommands$ChildCommandElement.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.sponge.SpongeMessageFormatter.combined(SpongeMessageFormatter.java:46) ~[SpongeMessageFormatter.class:?]
19.12 15:27:02 [Server] INFO at ninja.leaping.permissionsex.sponge.SpongeMessageFormatter.combined(SpongeMessageFormatter.java:149) ~[SpongeMessageFormatter.class:?]
19.12 15:27:02 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.text.Texts.builder()Lorg/spongepowered/api/text/TextBuilder$Literal;
19.12 15:27:02 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'pex help' for source EntityPlayerMP['TwistedCreeperYT'/39, l='world', x=216.70, y=70.00, z=246.72]: org.spongepowered.api.text.Texts.builder()Lorg/spongepowered/api/text/TextBuilder$Literal;
19.12 15:27:01 [Multicraft] Waiting for log file...
19.12 15:27:01 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@12eb3f40(success)
19.12 15:27:01 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@20197cfa(success)
19.12 15:27:00 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@300f77d1(success)
19.12 15:27:00 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@9cb74e2(success)
19.12 15:27:00 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4513962c(success)
19.12 15:26:56 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@47a5c3db(success)
19.12 15:26:56 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2ff2ee7e(success)
19.12 15:26:53 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1a336c06(success)
19.12 15:26:53 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@3bdfe500(success)
19.12 15:26:52 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@653f1ad(success)
19.12 15:26:52 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@7659f8ad(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@77ddefb6(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1e807f2b(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@ee51499(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1f84d30a(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@113a42d7(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@65f3b0e1(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@3105236(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1c4e307c(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@63d6bc58(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@798749ef(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@52ae9b6c(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6be7b8d3(success)
19.12 15:26:48 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6ad6b38(success)
19.12 15:26:46 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6e38059d(success)
19.12 15:26:46 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1693f9cb(success)
19.12 15:26:46 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@3c6ac93(success)
19.12 15:26:46 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@7d9559e8(success)
19.12 15:26:46 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@300713d8(success)
19.12 15:26:41 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@7f4be07e(success)
19.12 15:26:40 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@25b8091f(success)
19.12 15:26:40 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2aa9de02(success)
19.12 15:26:38 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2870c004(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@43aec657(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6844c600(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@370e81f7(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4faf9864(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2c0a4107(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1f3e3831(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@53616ecf(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@34f0a988(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@3f324a82(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@3ee1cd11(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@5c65f4d0(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@873eb0f(success)
19.12 15:26:36 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@32fbeaaf(success)
19.12 15:26:35 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@18108891(success)
19.12 15:26:31 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6c33f2c9(success)
19.12 15:26:31 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4fc27d96(success)
19.12 15:26:25 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@303ceb99(success)
19.12 15:26:24 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@63e93c24(success)
19.12 15:26:23 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@b9b5333(success)
19.12 15:26:23 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4a45d98a(success)
19.12 15:26:23 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@5e739fb4(success)
19.12 15:26:23 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@71b3d817(success)
19.12 15:26:18 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@562dda21(success)
19.12 15:26:18 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@48d1063(success)
19.12 15:26:18 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@264fe8f5(success)
19.12 15:26:18 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6d0d89e1(success)
19.12 15:26:17 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@d82be01(success)
19.12 15:26:17 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@5774c104(success)
19.12 15:26:17 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2ab3f02a(success)
19.12 15:26:17 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4eadb68e(success)
19.12 15:26:17 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@8045da9(success)
19.12 15:26:17 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@13c6b75b(success)
19.12 15:26:15 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4a88400e(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@365f3026(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@44933a6c(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@11d63a61(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@5e4c3c39(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2050c2dc(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@1afdad8a(success)
19.12 15:26:11 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@31e1677b(success)
19.12 15:26:10 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@20b42ac3(success)
19.12 15:26:08 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@527b2f10(success)
19.12 15:26:08 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@47b38060(success)
19.12 15:26:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@28eb4e18(success)
19.12 15:26:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@7381a958(success)
19.12 15:26:07 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2368291a(success)
19.12 15:26:03 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@36219bcb(success)
19.12 15:26:03 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@6fd08968(success)
19.12 15:26:02 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2b359d6d(success)
19.12 15:26:02 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@51e8735c(success)
19.12 15:26:02 [Server] Server thread/WARN [io.netty.channel.ChannelOutboundBuffer]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@4e50520e(success)

Error in chat when type any command:

http://imgur.com/n2KxGcY

**Comment by zml2008** [comment]
Update to the latest builds of PEX and Sponge.
