### ISSUE TITLE
Doing 'pex user d group set X' crashes the server

### ISSUE THREAD

**Issue by cuddylier** [PEXPlugins/PermissionsEx#2265]
Hi

All players are able to do 'pex user d group set X' even if they weren't given the permission to do so, works across multiple servers so nothing I've specifically done wrong, it crashes the server if repeatedly done.

**Comment by TWSSYesterday** [comment]
Can confirm this.

**Comment by TWSSYesterday** [comment]
Using latest Spigot + latest PermissionsEx.

**Comment by Someone-NEW** [comment]
Block for firs command /pex for usin it ingame only from console. But this need to be fixed.

**Comment by zml2008** [comment]
Fixed in 1.23.x git. A release will be pushed at some point.

**Comment by Johandrex** [comment]
So how do we download 1.23.x? I can't find it here "https://github.com/PEXPlugins/PermissionsEx/releases"
