### ISSUE TITLE
PermissionsEx TIMED permissions

### ISSUE THREAD

**Issue by jellebleyaert** [PEXPlugins/PermissionsEx#2267]
Hi all

For some reason, the timed permissions go away after restart
Any fix?

Kind regards

**Comment by zml2008** [comment]
Intentional -- timed permissions are not saved. Only timed groups are. This will probably change for PEX2.0, but for 1.x this is expected behavior

**Comment by Someone-NEW** [comment]
ok PEX2 is not in end and is not for download but in pex1 all timed are crap i test a groups but is realy bad i remove all timed things dont use it we wait update than we can use that but now is impossible thaks
