### ISSUE TITLE
Permissions aren't being read

### ISSUE THREAD

**Issue by SirYod** [PEXPlugins/PermissionsEx#2268]
As the title suggests, the server isn't recognising the permissions.yml and "Gives up". I'm currently in the process of backing up the file and resetting the plugin to reinstall just in case that's the issue.
Full Log: http://pastebin.com/mPZdfLRv
Please let me know if more information is needed, this server isn't mine but the owner is more than happy for me to modify the files etc.

**Comment by zml2008** [comment]
Well it doesn't help that your configuration is set up to use an SQL database (which is having its own issues -- but unrelated to your permissions.yml issues).
