### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tr008567** [PEXPlugins/PermissionsEx#2269]
### Description ###
see my erro on start
[Insert description of issue here]

22.12 20:34:07 [Disconnect] User AXLDOUGLASgnr has disconnected, reason: unknown
22.12 20:34:07 [Server] INFO list
22.12 20:33:32 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
22.12 20:33:32 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
22.12 20:33:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
22.12 20:33:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:321)
22.12 20:33:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:364)
22.12 20:33:32 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:556)
22.12 20:33:32 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:573)
22.12 20:33:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
22.12 20:33:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
22.12 20:33:32 [Server] INFO at net.skycraftmc.PluginManager.PluginManagerPlugin.onCommand(PluginManagerPlugin.java:208)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
22.12 20:33:32 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:106)
22.12 20:33:32 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:57)
22.12 20:33:32 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:488)
22.12 20:33:32 [Server] INFO java.lang.NullPointerException
22.12 20:33:32 [Server] SEVERE Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F4f7818b8746ddcad7f4e%29%0A. Full error:
22.12 20:33:32 [Server] INFO PermissionsEx 1.20.2 loaded successfully!
22.12 20:33:32 [Server] INFO WEPIF: Using the Bukkit Permissions API.
22.12 20:33:32 [Server] INFO ... 19 more
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
22.12 20:33:32 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606)
22.12 20:33:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22.12 20:33:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
22.12 20:33:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22.12 20:33:32 [Server] INFO at com.earth2me.essentials.EssentialsPluginListener.onPluginDisable(EssentialsPluginListener.java:42)
22.12 20:33:32 [Server] INFO at com.earth2me.essentials.perm.PermissionsHandler.checkPermissions(PermissionsHandler.java:109)
22.12 20:33:32 [Server] INFO at com.earth2me.essentials.perm.PermissionsExHandler.<init>(PermissionsExHandler.java:17)
22.12 20:33:32 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:203)
22.12 20:33:32 [Server] INFO Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
22.12 20:33:32 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
22.12 20:33:32 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
22.12 20:33:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
22.12 20:33:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:321)
22.12 20:33:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:364)
22.12 20:33:32 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:556)
22.12 20:33:32 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:573)
22.12 20:33:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
22.12 20:33:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
22.12 20:33:32 [Server] INFO at net.skycraftmc.PluginManager.PluginManagerPlugin.onCommand(PluginManagerPlugin.java:208)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
22.12 20:33:32 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:135)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:416)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
22.12 20:33:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
22.12 20:33:32 [Server] INFO org.bukkit.event.EventException
22.12 20:33:32 [Server] SEVERE Could not pass event PluginDisableEvent to Essentials v2.11.1
22.12 20:33:32 [Server] INFO Essentials: Using PermissionsEx based permissions.
### Detailed Information ###

[Is available here](https://gist.github.com/4f7818b8746ddcad7f4e)

**Comment by zml2008** [comment]
We don't support ancient versions of MC and PEX. Update to 1.7 or 1.8 and PEX 1.22.x or 1.23.x (respectively)
