### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'XXX' doesn't exist in engine

### ISSUE THREAD

**Issue by Snipershotmaster** [PEXPlugins/PermissionsEx#2271]
1:08:40 PM [INFO] [PermissionsEx] Enabling PermissionsEx v1.23.3
1:08:40 PM [INFO] [PermissionsEx] Initializing sql backend
1:08:40 PM [WARN] [AutoSaveWorld] Plugin PermissionsEx attempted to establish connection socket://192.168.1.99:5876 in main server thread
1:08:40 PM [WARN] [AutoSaveWorld] Plugin PermissionsEx attempted to establish connection socket://192.168.1.99:5876 in main server thread
1:08:40 PM [INFO] [PermissionsEx] Successfully connected to SQL database
1:08:40 PM [INFO] [PermissionsEx] Deploying default database scheme
1:08:40 PM [WARN] [AutoSaveWorld] Plugin PermissionsEx attempted to establish connection socket://192.168.1.99:5876 in main server thread
1:08:40 PM [ERROR] [PermissionsEx]
1:08:40 PM ========== UNABLE TO LOAD PERMISSIONS BACKEND =========
1:08:40 PM Your configuration must be fixed before PEX will enable
1:08:40 PM Details: Deploying of default data failed. Please initialize database manually using mysql.sql
1:08:40 PM =======================================================
1:08:40 PM ru.tehkode.permissions.exceptions.PermissionBackendException: Deploying of default data failed. Please initialize database manually using mysql.sql
1:08:40 PM at ru.tehkode.permissions.backends.sql.SQLBackend.deployTables(SQLBackend.java:426) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:191) ~[PermissionsEx.jar:?]
1:08:40 PM at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
1:08:40 PM at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
1:08:40 PM at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
1:08:40 PM at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_51]
1:08:40 PM at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67) ~[PermissionsEx.jar:?]
1:08:40 PM at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175) [PermissionsEx.jar:?]
1:08:40 PM at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:40 PM at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:40 PM at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:40 PM at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:40 PM at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:41 PM at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:41 PM at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:41 PM at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:41 PM at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:41 PM at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:41 PM at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
1:08:42 PM Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'permissionsex.pex_permissions_skyblock' doesn't exist in engine
1:08:42 PM at ru.tehkode.permissions.backends.sql.SQLBackend.setSchemaVersion(SQLBackend.java:222) ~[PermissionsEx.jar:?]
1:08:42 PM at ru.tehkode.permissions.backends.sql.SQLBackend.deployTables(SQLBackend.java:424) ~[PermissionsEx.jar:?]
1:08:42 PM ... 23 more
1:08:42 PM Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'permissionsex.pex_permissions_skyblock' doesn't exist in engine
1:08:42 PM at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
1:08:42 PM at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
1:08:42 PM at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
1:08:42 PM at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_51]
1:08:42 PM at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[PermissionsEx.jar:?]
1:08:42 PM at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[PermissionsEx.jar:?]
1:08:42 PM at ru.tehkode.permissions.backends.sql.SQLBackend.setSchemaVersion(SQLBackend.java:219) ~[PermissionsEx.jar:?]
1:08:42 PM at ru.tehkode.permissions.backends.sql.SQLBackend.deployTables(SQLBackend.java:424) ~[PermissionsEx.jar:?]
1:08:42 PM ... 23 more
1:08:42 PM [INFO] [PermissionsEx] Disabling PermissionsEx v1.23.3
1:08:42 PM [INFO] WEPIF: Using the Bukkit Permissions API.
1:08:42 PM [INFO] [Lockette] Disabled link to plugin PermissionsEx, version 1.23.3
1:08:42 PM [INFO] Essentials: Using PermissionsEx based permissions.
1:08:42 PM [ERROR] Could not pass event PluginDisableEvent to Essentials vTeamCity
1:08:42 PM org.bukkit.event.EventException
1:08:42 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:358) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:279) [PermissionsEx.jar:?]
1:08:42 PM at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:42 PM at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
1:08:42 PM Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
1:08:42 PM at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405) ~[?:?]
1:08:42 PM at com.earth2me.essentials.perm.PermissionsExHandler.<init>(PermissionsExHandler.java:17) ~[?:?]
1:08:42 PM at com.earth2me.essentials.perm.PermissionsHandler.checkPermissions(PermissionsHandler.java:121) ~[?:?]
1:08:42 PM at com.earth2me.essentials.EssentialsPluginListener.onPluginDisable(EssentialsPluginListener.java:48) ~[?:?]
1:08:42 PM at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
1:08:43 PM at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
1:08:43 PM at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
1:08:43 PM at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
1:08:43 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
1:08:43 PM ... 16 more
1:08:43 PM [INFO] WEPIF: Using the Bukkit Permissions API.

I know this is an error more within MySQL, but I've tried to remove the entire database and creating a new one. However it doesn't help, Permissionsex makes the new tables but still doesn't startup properly and throws this error. Im out of my wits with this problem.

**Comment by Snipershotmaster** [comment]
Config incase you need it

multiserver:
  use-netevents: false
permissions:
  debug: true
  allowOps: false
  user-add-groups-last: true
  log-players: true
  createUserRecords: true
  backend: sql
  informplayers:
    changes: true
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      type: sql
      uri: mysql://xxx:3306/PermissionsEx
      user: xxx
      password: xxx
      aliases:
        permissions: pex_permissions_skyblock
        permissions_inheritance: pex_inheritance
        permissions_entity: pex_entity_skyblock
updater: false
alwaysUpdate: false

**Comment by CzEMC** [comment]
What Database structure are you using? InnoDB should be used for pex.

If you have InnoDB on your pex database, then try dropping the current table and let pex regenerate it. **Of course, backup your data!**

**Comment by Snipershotmaster** [comment]
Server version: 10.1.9-MariaDB - mariadb.org binary distribution It would be that. But however I have already solved it :P.
