### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by bukkit188** [PEXPlugins/PermissionsEx#2272]
Please update for CraftBukkit, Spigot 1.8.8 soon. Thanks

**Comment by OlikTrolik** [comment]
22:16:24 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/vEVYf. Full error:

**Comment by zml2008** [comment]
Already is updated for 1.8.8 -- 1.23.x is for 1.8.x, and 1.22.x is for 1.7.10

@OlikTrolik you're running the 1.8 version of PEX on a 1.7 server. Not going to work well. Update it. Also, don't take over other people's issues -- your problem is unrelated.
