### ISSUE TITLE
Group being overridden when using group add

### ISSUE THREAD

**Issue by Nentify** [PEXPlugins/PermissionsEx#2274]
When I use /pex user <user> group add <group>, the user's group is being overwritten like 'set' would if they're in the default group.

For example:

user-1 is in group-a

/pex user user-1 group add group-b

user-1 is only in group-b

user-1 should be in both group-a and group-b

If I do /pex user user-1 group set group-a (default group) first, this doesn't happen however.

createUserRecords is also true in the config, so not sure why this is happening.

**Comment by zml2008** [comment]
This is how default groups work in PEX -- if a user has no groups the list of default groups is their groups. Once a group is added to a user, that group replaces the default groups. This allows the default group to be changed without having to modify every user. You could work around this by having group-b inherit from group-a.

In PEX2, this works differently -- default groups are automatically appended at the end of every inheritance hierarchy so every user will inherit from the default subject without having it listed in their inheritance.

**Comment by Nentify** [comment]
This isn't how it used to work. createUserRecords used to make it so you can use add without it overwriting. I use it to add users to a voter or premium group in addition to their primary group. Is it possible for this to work again? It worked when PEX had lag issues and I switched to zPerms at the time.

**Comment by zml2008** [comment]
Yeah -- I think I might've changed that when I was cleaning up the backend system a bit a while ago. That should be a pretty easy fix.

**Comment by Nentify** [comment]
Will this be soon?
