### ISSUE TITLE
(Suggestion) PermissionsEx update suggestion

### ISSUE THREAD

**Issue by timothydavidhart** [PEXPlugins/PermissionsEx#2275]
I was wondering if a language.yml file could be added to PEX so people can translate PEX for them selves since not everyone is English etc  and it would be nice to change up the looks also :)

**Comment by zml2008** [comment]
In 2.0 we have full localization support -- any language can get a translation file. What we're working on is getting a nice interface to submit translations like crowdin or transifex set up.

 However, it is not practical to change all of PEX1.x to support localizations at this time.
