### ISSUE TITLE
Pex high timings

### ISSUE THREAD

**Issue by SecretlyJealous** [PEXPlugins/PermissionsEx#2285]
![untitled](https://cloud.githubusercontent.com/assets/10485646/12072067/1366b950-b0c6-11e5-805f-e4b11a5d518d.png)
This was taken when my creative server had 450 players online.

**Comment by zml2008** [comment]
Yeah, logins are expensive. Not really able to optimize much more in 1.x. 2.0 will be faster, but that's still a little ways off.

Your best bet is to avoid doing too many runtime permissions changes.
