### ISSUE TITLE
Sharing the SQl Database

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2286]
I now need to know how to share the same database with multi servers since I can't seem to get the second one to load the perms, but it connected to the SQL database????????

OK I figured out how to get SQL to work, just need to understand how it syncs? I update a rank on first server I created SQL with and rest of server update , If I change someones rank on any other server it never updates till I use reload command.

I also decided to use cron jobs to run pex reload every ten minutes, thanks for the lack of help

**Comment by CzEMC** [comment]
Pex will only get permissions from the SQL database if the following happens:

It will get player permissions when the player joins
It will get the group permissions when the server restarts, or a "/pex reload" is issued.

I guess you answered your own question.

Closes #2286

**Comment by Ironic8b498** [comment]
yes I figured out  way to make it work, but I guess it was over kill since it should update when they log into server.. I will test that and remove cron jobs since they may not be needed
