### ISSUE TITLE
Helpp! plis

### ISSUE THREAD

**Issue by pegelio** [PEXPlugins/PermissionsEx#2289]
(Spanish)

me dice [PermissionsEx] Error occurred with PermissionsEx! porfavor ayuda! quiero jugar con rango en mi server porfavor

**Comment by CzEMC** [comment]
Sorry that I don't speak your native language, but if you can understand English,

For the community to know your problem you need to give more information. posting your latest.log or the permissionsEx pre-made error file would allow us to diagnose your problem.

**Comment by zml2008** [comment]
(No hablo bién español, pero pruebo decir algo)

Necesitas copiar el problema completa, no solo el primero mensage -- hay un link que puedes copiar aqui que tenga más informacion.

---
or in english:

You need to copy the whole error, not just the first message -- there is a link you can copy here that has more information.

**Comment by zml2008** [comment]
No response after 20 days, closing.
