### ISSUE TITLE
Default groups not working

### ISSUE THREAD

**Issue by TypicalDarkness** [PEXPlugins/PermissionsEx#2292]
I used /pex system default parent add Default
But when new players join they don't get added to that group

**Comment by CzEMC** [comment]
What are you trying to accomplish? Setting a default group or making so a player is apart of the default group and another group?

If you answered yes to the first one, try the command, "/pex set default group Default"

Without quotes

**Comment by zml2008** [comment]
This is on Sponge -- the default handling changed a little while ago so the command is now `/pex default user parent add Default`
