### ISSUE TITLE
permissionsex not loading the permmissions file right

### ISSUE THREAD

**Issue by lightning21games** [PEXPlugins/PermissionsEx#2295]
Ok here is the error.

ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367) ~[PermissionsEx.jar:?]
09.01 13:23:24 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392) ~[PermissionsEx.jar:?]
09.01 13:23:24 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
09.01 13:23:24 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
09.01 13:23:24 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
09.01 13:23:24 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
09.01 13:23:24 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:120) ~[PermissionsEx.jar:?]
09.01 13:23:24 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:321) ~[PermissionsEx.jar:?]
09.01 13:23:24 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
09.01 13:23:24 [Server] INFO =======================================================
09.01 13:23:24 [Server] INFO Details: Error loading permissions file!
09.01 13:23:24 [Server] INFO Your configuration must be fixed before PEX will enable
09.01 13:23:24 [Server] INFO ========== UNABLE TO LOAD PERMISSIONS BACKEND =========
09.01 13:23:24 [Server] INFO Initializing file backend
09.01 13:23:24 [Server] INFO Enabling PermissionsEx v1.22.7-SNAPSHOT

My server is in offline mode because it uses bungee cord. That is working fine but in my hub server I can't get ant permissions plugin to work. I use Spigot 1.8.7 (BT:41). If i need to download a different jar or plugin version please let me know.

**Comment by Stormbow** [comment]
OFFLINE mode is not supported by PEX.  Never will be.
