### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by zerowave321** [PEXPlugins/PermissionsEx#2300]
whats wrong with this please help! i know that this isnt a serious issue but please help idk whats wrong with it.
groups:
  Guest:
    options:
     default: true
	 prefix: '&7[Guest]&f '
    permissions:
    - modifyworld.*
  Moderator:
    options:
	 prefix: '&9[Moderator]&f '
    permissions:
	- modifyworld.*
    - essentials.fly
    - trail.*
    - essentials.kick
    - essentials.jails.*
    - essentials.mute.*
    - essentials.socialspy
    - essentials.tempban.*
    - essentials.tp.*
    - essentials.time
    - essentials.heal
    - essentials.god	
  VIP:
    options:
	 prefix: '&6[VIP]&f '
    permissions:
	- modifyworld.*
	- essentials.kick
	- trail.*
	- essentials.mute
  Owner:
    options:
	 prefix: '&3[Owner]&4 '
    permissions:
	- '*'
  Builder:
    options:
	 prefix: '&1[Builder]&f '
    permissions:
	- essentials.*
	- trail.*
	- worldedit.*
schema-version: 1
  users:
    zerowave321:
      group:
	    - Owner
    DailyFix:
      group:
	    - Builder
    spotnyk:
      group:
	    - Builder
    Elemental_Terra:
      group:
	    - Builder

**Comment by zerowave321** [comment]
ok i dont seem to be able to show the spaces :/

**Comment by zerowave321** [comment]
ok heres the document 
[ex.txt](https://github.com/PEXPlugins/PermissionsEx/files/95965/ex.txt)

**Comment by Stormbow** [comment]
Do not use the tab key in your file.  You have used it 21 times in that ex.txt file.
