### ISSUE TITLE
getPerrmissionManager().getGroups() replacement?

### ISSUE THREAD

**Issue by Horrgs** [PEXPlugins/PermissionsEx#2302]
For some reason, it's deprecated. And I also can't seem to find this method, or many others, on the GitHub. There is getGroups(String groupName) but I don't understand the use of that.

**Comment by zml2008** [comment]
getParents(). And it's getParents(String worldName);

master is version 2.0, a complete rewrite. Check the 1.23.x branch for the older PEX.

**Comment by Horrgs** [comment]
Any way of doing that without doing getUser(String name)? I want to get all groups on the server.
