### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by zerowave321** [PEXPlugins/PermissionsEx#2304]
when i do /plugins the plugin is red and i dont know how to fix it

**Comment by Stormbow** [comment]
When PEX shows up red in the plugins list, it means there is one or more errors in the permissions.yml file.  See [this example](http://pastebin.com/8ZSHxauG) and make sure your file follows the same formatting.  Run your file through the [Online Yaml Parser](http://yaml-online-parser.appspot.com/) to find additional errors.
