### ISSUE TITLE
Timed permissions added to a group, removed by restart.

### ISSUE THREAD

**Issue by bingoberra** [PEXPlugins/PermissionsEx#2305]
Hello.
My issue is this.

Every time I put a player in a group for a limited time with the command:
pex user {name} group add fly "" 3600

This will put the player into the fly group for 1 hour. But, if the server restarts during this time the person will be removed from this group!

We sometimes give out a full week of fly on our server and in this case we have to start it every restart.

Specs:
Spigot 1.8.7
Java 7
Pex Version 1.23.3

How can I fix this?

**Comment by CzEMC** [comment]
Because pex stores it's temporary groups in memory, this can't be accomplished. 

Another possible fix could be that you can get a plugin to use vault API or issue a console command to remove said player from group after 3600 seconds, and save the remaining time in a file if the server stops.

**Comment by CzEMC** [comment]
close #2305

**Comment by zml2008** [comment]
Timed permissions are the only ones stored in memory -- timed groups should be written to the file. My only guess is that a file save is not yet complete when you restart the server? -- Check the permissions file to see whether or not the `group-fly-until` option is set on the user.

**Comment by bingoberra** [comment]
I add myself to the group.
![Picture 1](https://i.gyazo.com/4b86bdc60e87a809ae3634fbbc425ab5.png)

I go to the file to check!
![Picture 1](https://i.gyazo.com/1e9d51ae11ba2217aabeda087f2c3da7.png)
It's there!

**Comment by bingoberra** [comment]
I'm actually still in the group after the restart. 

The title is wrong. 
What I actually meant was when I add a timed permission to a group it's removed after a restart.

**Comment by Stormbow** [comment]
Edited the title for you.

**Comment by zml2008** [comment]
That's expected behavior -- timed permissions are in-memory only -- only timed groups are stored, so you may want to make a timed container group that will better meet your needs.
