### ISSUE TITLE
Permissions not sticking in the PEX File.

### ISSUE THREAD

**Issue by mikelefebvre** [PEXPlugins/PermissionsEx#2306]
Whenever i run a Pex command to add a permission to a player, i find it can take 2 times for it to appear on the player. Also adding timed permissions seem to clear on a player rejoin. Im not sure if this is a problem on my end or not. 

We are running a 
Windows Server
Spigot

**Comment by bingoberra** [comment]
Not the second "issue". I can confirm the timed permissions set by "pex user notch timed add" is removed on relog.

**Comment by CzEMC** [comment]
In order for us, community and developers, to fix the problem, we would need more info on your problem.

Exact spigot build, permissionsEx build, installed plugins, does /pex reload fix anything, etc...

Log file would be helpful in some cases as well.

**Comment by Stormbow** [comment]
I am going to bet on this being a McMyAdmin server host.  They are frequently responsible for this sort of issue.

Am I right?  Is this a McMyAdmin server host?

**Comment by Stormbow** [comment]
It doesn't look like @mikelefebvre needs help anymore...
