### ISSUE TITLE
Colorcode prefix not working.

### ISSUE THREAD

**Issue by fallatus** [PEXPlugins/PermissionsEx#2308]
I have tested a couple of configurations but I can't seem to get colorcodes to work with the newest sponge version. I have used the exact same .json file as in a version earlier where it still worked.
Then I have deleted the whole permissions.json file so the server created a new one upon start.
All I did then was entering the following command:

/pex user Bob option prefix &7[&5Test&7]

But the user "Bob" still has no colored prefix ingame.
All rights I set for the user seem to work.

The JSON permissions file:
http://pastebin.com/dzjf30Ln

The mods/plugins:
forge-1.8.9-11.15.1.1722-universal
spongeforge-1.8.9-1722-3.1.0-BETA-1104
PermissionsEx-Sponge (PermissionsEx v2.0 [API 3.0])

**Comment by zml2008** [comment]
You need a chat plugin to apply the prefixes

**Comment by fallatus** [comment]
Oh thats my bad, sorry to have bother you.
Thanks for the info!
