### ISSUE TITLE
Username (no uuid) mode.

### ISSUE THREAD

**Issue by sgdc3** [PEXPlugins/PermissionsEx#2309]
That would be a nice enhancement for offline mode servers.

**Comment by CzEMC** [comment]
Pex doesn't support users with no official minecraft uuids. (AKA, not-bungeed offline servers)

Why would we need this feature anyways? The newer versions of permissionsEx is for 1.7 and 1.8 which use the UUID system.

**Comment by sgdc3** [comment]
> Pex doesn't support users with no official minecraft uuids.
:/ So you don't want to support 52% of servers? (http://mcstats.org/global/)
> Why would we need this feature anyways? The newer versions of permissionsEx is for 1.7 and 1.8 which use the UUID system.
I prefer to give permissions to static usernames for many reasons.
I own a bungee network but uuids of offline players aren't resolved correctly between the servers.
(I've already turned on "bungeecord" and "ip_foward" feature on every server.)

**Comment by Stormbow** [comment]
No.  PEX does not support hacked clients and pirated versions of Minecraft.

**Comment by zml2008** [comment]
Also remember that 52% includes bungee servers -- so that's not an accurate statistic.

**Comment by sgdc3** [comment]
Lol, ok pour people.... keep developing this dying plugin. ;)

**Comment by Stormbow** [comment]
sgdc3 being an asshole, comment deleted.  Topic locked.
