### ISSUE TITLE
PEX permissions not working even when OPed

### ISSUE THREAD

**Issue by Dmitchell94** [PEXPlugins/PermissionsEx#2310]
Hi I am Op on my server but when i install PEX and set up some basic permissions it tells me i cant use the commands for ops even if i add the permissions to me

**Comment by CzEMC** [comment]
What permission nodes are you adding and what are you trying to accomplish? By default, ops don't have the permission to edit pex.

**Comment by Stormbow** [comment]
OP is for Vanilla servers which do not use mods or plugins at all.  Using OP on modded servers can (and will) result in server owners thinking that things are set up correctly on the server when they actually are not.  (I see this very often on the PEX forums.)

Don't use OP.

**Comment by Dmitchell94** [comment]
I am not sure you understand the problem and I probally have not named this correctly. Let me explain. The problem is that once i add PEX even if i give myself the permissions it does not work, even as an op it tells me i have not permissions. I have given myself the node to change game modes and i can not. even as op i can not change gamemode.

**Comment by Stormbow** [comment]
Is PEX coming up red in the plugins list in-game?

Let's see your permissions.yml file and your startup log.

**Comment by Dmitchell94** [comment]
Pex comes up green,

Permissions.json: http://pastebin.com/rBt9WivZ

Startup log:  To Large working on it

**Comment by Stormbow** [comment]
Damn.  Sponge issue.  Zml will have to handle this.  I haven't gotten into Sponge at all yet.

**Comment by Dmitchell94** [comment]
lol no worries

**Comment by i9hdkill** [comment]
Your sponge version is the latest, but I couldn't find the version number of pex. 
Did you install the latest from the jenkins? At least Build 107

**Comment by zml2008** [comment]
PEX for Sponge completely replaces the `op` system (in fact any Sponge permissions plugin will) -- so op or deop won't do anything. What your issue looks like thouch is that you have your user in by name, when PEX2 only uses UUIDs -- just work by UUID, or join and leave the server once before setting up your user data in the console.
