### ISSUE TITLE
1.5.2

### ISSUE THREAD

**Issue by AlienHunter501** [PEXPlugins/PermissionsEx#2313]
could you please make a version for 1.5.2 for my server its modded

**Comment by decontamin4t0R** [comment]
maybe just use some older version.?

**Comment by AlienHunter501** [comment]
If I give you my server stuff cud I do it for me

**Comment by decontamin4t0R** [comment]
try this: http://dev.bukkit.org/bukkit-plugins/permissionsex/files/22-permissions-ex-v1-20-2/

**Comment by zml2008** [comment]
No. We do not support versions of PEX or MC that are multiple years out of date. Get a better modpack.
