### ISSUE TITLE
Clean permission node dump - Sponge version, build 108

### ISSUE THREAD

**Issue by paleym** [PEXPlugins/PermissionsEx#2316]
Hello,

Did pex debug and then /help, then copied the log and cut it down to the node list, would it be possible to have pex create a file (maybe in the config) that lists out all registered permission nodes nicely?  Took way too long to get all the nodes the way I did it!

Thanks!

**Comment by zml2008** [comment]
Not really -- there's no way to get all registered permissions nodes in Sponge (that's actually used by plugins -- the registry exists in Sponge but is currently unused) -- so for the most part your best bet is to look at each plugin's documentation.

**Comment by paleym** [comment]
Can we then get an updated list of commands / nodes for permissionsex?  I have worked out most of the commands, but for nodes, even the /pex debug didnt list all of them?

It only listed debug, reload, and import
