### ISSUE TITLE
Group setting problem.

### ISSUE THREAD

**Issue by DeadlyForest** [PEXPlugins/PermissionsEx#2317]
I used the command to make my friend into one of my groups that I made (Admin), and in chat it said that he got put in the group, but he doesn't have any of the permissions that the group has, what am I doing wrong?

**Comment by Someone-NEW** [comment]
/pex user "userName" group set Admin

Your group admin for all permissions you can add this "*" like so:
` Admin:
    options:
      rank: '200'
      build: true
      prefix: '&cAdmin'
      suffix: ''
      default: false
    permissions:
    - essentials.fly
    - '*'`
This is only for example

**Comment by DeadlyForest** [comment]
I have already customized my admin group, and in chat it even says that the person that I set in Admin became part of the group, but they cant go into creative mode, etc. This is what my permissions file looks like. 

groups:
  Player:
    options:
      prefix: '&7[Player]&f'
      default: 'true'
      rank: '1000'
    worlds:
      world:
        options:
          default: 'true'
    permissions:
    - herochat.pm
    - herochat.speak.*
    - herochat.speak.G
    - herochat.speak.global
    - herochat.leave.*
    - herochat.join.*
  Owner:
    options:
      rank: '1'
      prefix: '&4[Owner]&f'
  StaffCadet:
    permissions:
    - herochat.pm
    - herochat.create
    - herochat.remove.
    - bm.command.warn
    - bm.command.tempmute
    - bm.command.report
    - bm.command.alts
    - bm.command.banlist
    - bm.command.bminfo
    - bm.command.notes.online
    - bm.command.notes
    - bm.command.addnote
  Mod:
    permissions:
    - herochat.speak.*
    - herochat.leave.*
    - herochat.join.*
    - herochat.join
    - herochat.emote
    - herochat.pm
    - herochat.mute
    - herochat.mod
    - herochat.save
    - herochat.create
    - -bm.command.delete
    - -bm.command.sync
    - -bm.command.nlkick
    - -bm.command.dwarn
    - -bm.command.muteip
    - -bm.command.unbanip
    - ddddd
    - -bm.command.banip
    - -bm.command.mute
    - -bm.command.unban
    - -bm.command.ban
    - bm.command.*
    options:
      rank: '100'
      prefix: '&0(&1Mod&0)&7'
  Admin:
    permissions:
    - bukkit.command.*
    - herochat.*
    - bm.commands.*
    options:
      rank: '10'
    worlds:
      Towny_Server:
        permissions:
        - holograms.*
  Builder:
    permissions:
    - bukkit.command.gamemode
    - herochat.speak.*
    - herochat.pm
    - herochat.leave.*
    - herochat.join.*
    - worldedit.*
    - modifyworld.*
    - bm.command.report
  staffcadeter:
    permissions:
    - herochat.pm
schema-version: 1
users:
  e8d37718-f675-4f72-b562-f7f688c992f5:
    options:
      name: DeadlyForest
    group:
    - Owner
    permissions:
    - '*'
  0a2fbf10-44a2-4325-aea2-caf122225aee:
    group:
    - Admin
    options:
      name: FrostSlayer
    worlds:
      Towny_server:
        group:
        - Admin
  <user:
    worlds:
      '[world]':
        group:
        - <group>

**Comment by Someone-NEW** [comment]
Give Owner Group this permission **- '*'** but witch plugins you have? Essentials when is si give admin custom permissions like for gamemode from bukkit and Essentials but you can add permissions **- '*'** this mean that have all permissions on server, but you can add only **essentials.gamemode** permissions or you can add this one to like **bukkit.command.gamemode** You can give him a

**Comment by DeadlyForest** [comment]
yeah, this is the edited perms file, thanks for the help. I will try to test this out today.

groups:
  Player:
    options:
      prefix: '&7[Player]&f'
      default: 'true'
      rank: '1000'
    worlds:
      world:
        options:
          default: 'true'
    permissions:
    - essentials.tptoggle
    - essentials.tpahere
    - essentials.realname
    - essentials.msg
    - essentials.mail.send
    - essentials.mail
    - essentials.helpop
    - essentials.pay
    - essentials.afk.auto
    - essentials.balance
    - essentials.sethome.multiple.Player
    - essentials.sethome
    - essentials.home
    - essentials.tpaccept
    - essentials.tpa
    - essentials.delhome
    - essentials.spawn
    - herochat.pm
    - herochat.speak.*
    - herochat.leave.*
    - herochat.join.*
  Owner:
    options:
      rank: '1'
      prefix: '&4[Owner]&f'
  StaffCadet:
    permissions:
    - essentials.helpop.receive
    - essentials.sethome.multiple.StaffCadet  
    - herochat.create
    - herochat.remove.
    - bm.command.warn
    - bm.command.tempmute
    - bm.command.report
    - bm.command.alts
    - bm.command.banlist
    - bm.command.bminfo
    - bm.command.notes.online
    - bm.command.notes
    - bm.command.addnote
  Mod:
    permissions:
    - essentials.helpop.receive
    - essentials.fly
    - herochat.speak.*
    - herochat.leave.*
    - herochat.join.*
    - herochat.join
    - herochat.emote
    - herochat.pm
    - herochat.mute
    - herochat.mod
    - herochat.save
    - herochat.create
    - -bm.command.delete
    - -bm.command.sync
    - -bm.command.nlkick
    - -bm.command.dwarn
    - -bm.command.muteip
    - -bm.command.unbanip
    - -bm.command.banip
    - -bm.command.mute
    - -bm.command.unban
    - -bm.command.ban
    - bm.command.*
    options:
      rank: '100'
      prefix: '&0(&1Mod&0)&7'
  Admin:
    permissions:
    - bukkit.command.*
    - herochat.*
    - bm.commands.*
    - essentials.*
    options:
      rank: '10'
    worlds:
      Towny_Server:
        permissions:
        - holograms.*
  Builder:
    permissions:
    - bukkit.command.gamemode
    - herochat.speak.*
    - herochat.pm
    - herochat.leave.*
    - herochat.join.*
    - worldedit.*
    - modifyworld.*
    - bm.command.report
  staffcadeter:
    permissions:
    - herochat.pm
schema-version: 1
users:
  e8d37718-f675-4f72-b562-f7f688c992f5:
    options:
      name: DeadlyForest
    group:
    - Owner
    permissions:
    - '*'
  0a2fbf10-44a2-4325-aea2-caf122225aee:
    group:
    - Admin
    options:
      name: FrostSlayer
    worlds:
      Towny_server:
        group:
        - Admin
  <user:
    worlds:
      '[world]':
        group:
        - <group>

**Comment by Someone-NEW** [comment]
Use this online parser to be sure you are make all correct http://yaml-online-parser.appspot.com/
on first look i think you have a many things wrong itd test it

**Comment by DeadlyForest** [comment]
Thank you so much, that online parser helped sooo much, everything is set up, and this topic can be closed. Again, **thank you SO much**.
