### ISSUE TITLE
How to make prefix only based off of pex.

### ISSUE THREAD

**Issue by DeadlyForest** [PEXPlugins/PermissionsEx#2321]
I removed essentials chat and all other chat plugins but the chat prefixes are all weird, the format is as is in the picture.

I want the prefix to not have the [world][g] [world] part on it, and want it to look like this: "&4[Owner]DeadlyForest&f"

How do I do this?

![capture](https://cloud.githubusercontent.com/assets/16531704/12870823/510bab7e-cd24-11e5-94cf-e0a3348ed9f8.PNG)

**Comment by zml2008** [comment]
PEX doesn't do anything with chat -- ths is another chat plugin.
