### ISSUE TITLE
Admin after NameChange in Default group

### ISSUE THREAD

**Issue by logtainment** [PEXPlugins/PermissionsEx#2322]
Hey,
I have an Issue. When I change my Name in Minecraft, my Admin is not there and I'm in the Default group.
I use Spigot 1.8.8 and BungeeCord. The Server is running on online-mode= false .
How can I fix this?

**Comment by zml2008** [comment]
Update to a version of PEX that uses UUIDs, and convert your user database -- check the wiki to see how.
