### ISSUE TITLE
Inheritance 

### ISSUE THREAD

**Issue by GarrettPlayMinecraft** [PEXPlugins/PermissionsEx#2323]
Example: My rank Partner has /kit partner and My rank angle has /kit angle, I have angle inheritance set as partner, I want all the commands partner has in the angle group BUT  I don't want /kit partner in the angle group. How can I fix this easily?

**Comment by zml2008** [comment]
mark the kit permission as not inheritable maybe? (this is done by setting the permission as `'#some.perm'` rather than `'some.perm'`)

**Comment by GarrettPlayMinecraft** [comment]
I have no  clue were that is

**Comment by zml2008** [comment]
In your permissions file, change your kit permission for partner I guess?

**Comment by GarrettPlayMinecraft** [comment]
I will put it a different way, 
(List from Lowest rank to highest) 
Default *No Kits*
Contributor *Kits*
Partner *Kits*
Savior *Kits*
Angle *Kits*
Guardian *Kits*

Contributor inherits from the default rank, Contributor has access to /kit Contributor (Rank Works Right)
The next rank Partner Inherits from Contributor and has /kit Partner (The Issue Is That Since The Rank Inherits From Contributor the rank also gets /kit Contributor)
The Next rank Savior inherits from Partner and has /kit Savior (The Issue Is That Since The Rank Inherits From Partner the rank Gets /kit Partner, Since the rank partner is Inheriting from contributor the rank also gets /kit contributor, I ONLY WANT /KIT SAVIOR FOR THE RANK THOUGH) 
*The Rest Of The Ranks Have The Same Type Of Problem* 
(Please Say What FILE to look in when helping and make sure to tell me if I should be in Pex  at times and essentials (My kit plugin) at times if needed)

**Comment by GarrettPlayMinecraft** [comment]
?

**Comment by CzEMC** [comment]
We understand your problem. Instead of giving partner the direct permission node (kit.partner) give partner the non-inheritable permission node.

Basically:
Instead of "/pex group partner add kit.partner"
Do: "/pex group partner add #kit.partner"

The "#" makes it so pex won't allow that permission node to be inheritable to other groups.
