### ISSUE TITLE
Remove permission/group world 

### ISSUE THREAD

**Issue by Johandrex** [PEXPlugins/PermissionsEx#2328]
Hello, yesterday I accidently added these world permissions/groups which I'm unable to remove from some of my servers since they're using MySql. I'd be greatful if you could advise me on how to remove the permissions/groups with commands. (I know they won't make a difference but I want to keep everything clean and fresh)

```  Mod:
    options:
      default: false
      weight: '550'
    permissions:
    - chatcontrol.notify.ad
    - chatcontrol.notify.swear
    inheritance:
    - global
#Want this down below removed
    worlds:
      spectator.use.spectate:
        permissions: []
      spectator.use.inventory:
        permissions: []
      spectator.use.teleport:
        permissions: []
```

**Comment by Stormbow** [comment]
@zml2008 : I couldn't find any commands about this in the existing PEX documentation or in the older commands lists I'd collected in-game.  We [http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/permissions-help/88404-remove-permission-group-world/](took a shot) at **/pex world <world> delete** but that didn't work out.

**Comment by Johandrex** [comment]
Strange, is it fixable?

**Comment by zml2008** [comment]
For MySQL, I don't think there is any registry of worlds -- the worlds are just stored with the permission/option or inheritance rows, so these are probably just in your permissions file.

PEX2 is better about cleaning up empty context segments, so even on a file backend this wouldn't happen.
