### ISSUE TITLE
Multiple prefix support

### ISSUE THREAD

**Issue by The-creeper-cow** [PEXPlugins/PermissionsEx#2329]
Hallo i really love PEX but i think it misses mutliple prefix support like for example you have the ranks Donor and Mod both groups have a prefix set it would be cool if they merged like [Donor] [Mod] <name> if this is possible and you would want to do this i would be very happy

have a nice day

**Comment by Stormbow** [comment]
PEX itself doesn't put the prefixes, groups, worlds, etc. into chat.  Those are all displayed in chat by chat mangement plugins.  You'd have to talk to one of those authors to get the functionality you're looking for.
