### ISSUE TITLE
pex commands not working in game

### ISSUE THREAD

**Issue by NaerenVastir** [PEXPlugins/PermissionsEx#2330]
ok so i've been researching for most of the day now but i have not been able to find a solution to my problem. first i'll give what details i know.

The server service i use is mcpro hosting, is compatible with sponge and loads pex without errors.

using mc version 1.8.9 with the latest version of forge and sponge

when i log into the game and try to use the pex commands, it says i do not have permission to use that command. when i go into the server console to use the commands it says it works fine for example i put in " pex group GM def true "  and i get the lind that i set the default permission to 1 for group GM in global context. then i add my username into the group with " pex user Naeren parent add group GM " and i get the response Added parent group GM for user Naeren in Global context. however when i am in game, i still cannot use any of the pex commands for editing or creating new groups, and my permissions dont seem to update at all as i dont get access to the other commands i should have in that case. i have tried numerous different suggestions posted in the replies to the main thread and the issues page, but i have had no luck. i would greatly appreciate it if someone could help me out with this.

**Comment by zml2008** [comment]
Run `/pex user Naeren delete`, and then recreate the user using your UUID -- currently the username is what the account is stored by, rather than the UUID that PEX and MC use internally.
