### ISSUE TITLE
PermissionsEx Returning with Error when modifying Permissions.yml

### ISSUE THREAD

**Issue by Arm64Fedora** [PEXPlugins/PermissionsEx#2331]
Hi I'm trying to make a server using PermissionsEx running 1.7.2 due to outdated mods not being for the latest bukkit version. 

When editing permissions.yml in any way from the default without a mistake it always comes up with this error, even if I copy/paste from a already existing Permissions.yml file, pretty much any modification to it makes the errors apear. 

My permissions.yml if you want to look at it yourself: http://pastebin.com/TQY505vC
I'm using build 1.21 for 1.7.2.

Error Message: 

 . Full error:
12:42:43 PM java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
12:42:43 PM at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:266)
12:42:43 PM at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:226)
12:42:43 PM at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:689)
12:42:43 PM at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:671)
12:42:43 PM at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:747)
12:42:43 PM at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:72)
12:42:43 PM at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:157)
12:42:43 PM at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:218)
12:42:43 PM at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
12:42:43 PM at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:384)
12:42:43 PM at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:298)
12:42:43 PM at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:280)
12:42:43 PM at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342)
12:42:43 PM at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319)
12:42:43 PM at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275)
12:42:43 PM at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175)
12:42:43 PM at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424)
12:42:43 PM at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)
12:42:43 PM Caused by: java.lang.reflect.InvocationTargetException
12:42:43 PM at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12:42:43 PM at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
12:42:43 PM at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:42:43 PM at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
12:42:43 PM at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:251)
12:42:43 PM ... 17 more
12:42:43 PM Caused by: ru.tehkode.permissions.exceptions.PermissionBackendException: Error loading permissions file!
12:42:43 PM at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:261)
12:42:43 PM at ru.tehkode.permissions.backends.file.FileBackend.<init>(FileBackend.java:71)
12:42:43 PM ... 22 more
12:42:43 PM Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
12:42:43 PM in "<string>", line 3, column 12:
12:42:43 PM default: true
12:42:43 PM ^
12:42:43 PM at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
12:42:43 PM at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:44)
12:42:43 PM at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149)
12:42:43 PM at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:114)
12:42:43 PM at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:24)
12:42:43 PM at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:251)
12:42:43 PM ... 23 more
12:42:43 PM Caused by: mapping values are not allowed here
12:42:43 PM in "<string>", line 3, column 12:
12:42:43 PM default: true
12:42:43 PM ^
12:42:43 PM at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:733)
12:42:43 PM at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:305)
12:42:43 PM at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
12:42:43 PM at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:563)
12:42:43 PM at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
12:42:43 PM at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
12:42:43 PM at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
12:42:43 PM at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
12:42:43 PM at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
12:42:43 PM at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
12:42:43 PM at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
12:42:43 PM at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
12:42:43 PM at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
12:42:43 PM at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
12:42:43 PM ... 28 more

**Comment by Stormbow** [comment]
I corrected multiple errors in your file: missing colons, missing spaces, too much indentation for one group.

http://pastebin.com/TEhCLrTp
