### ISSUE TITLE
MySQL Backend: user groups not synced

### ISSUE THREAD

**Issue by saiismad** [PEXPlugins/PermissionsEx#2332]
So I have setup PEX to use the mysql backend on multiple servers.. They all connect and authenticate with the sql database But when I promote a player in one server that players rank is not changed in the other servers even though pex is installed on all servers and they all are using the same database. Obviously the username and password I have censored but in the real configs they are correct and authenticates fine.

Here is my config if it helps:

```
permissions:
  backend: sql
  backends:
    sql:
      uri: mysql://10.0.88.6/permissionsex
      user: <censored>
      password: <censored>
      type: sql
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
multiserver:
  use-netevents: false
updater: true
alwaysUpdate: true
```

**Comment by Stormbow** [comment]
Are you also using [NetEvents](http://dev.bukkit.org/bukkit-plugins/netevents/) to pass the info to the other servers?

**Comment by saiismad** [comment]
@Stormbow 

Can you link me to some real documentation on this plugin? i.e How it works and how to configure it? I have read through the server configuration wiki (https://github.com/zml2008/netevents/wiki/Server-Configuration)
But when the server starts netevents spits out an error: "Error while connecting to remote servers. Address already in use."

I have searched for tutorials and better documentation but cannot find any..

**Comment by zml2008** [comment]
Are you trying to have NetEvents run on the sever port? iirc that error message occurs when you try to have more that one thing bind to the same port.
