### ISSUE TITLE
Group add overwrites current group(s)

### ISSUE THREAD

**Issue by EvilOlaf** [PEXPlugins/PermissionsEx#2335]
Using PEX 1.23.4
Spigot 1.8.8

When I do `pex user aplayernamehere group add anyothergroup` and then check the player by using `pex user aplayernamehere` it shows the added group only.

Then I used `pex user aplayernamehere group set default` to restore the original situation.
Next I used `pex user aplayernamehere group add` twice to add this player to two other groups. Then the added groups as well as the original group showing up correctly.

I checked the `permissions.yml` file by hand and the default group was not shown on the users groups.

**Comment by zml2008** [comment]
This is expected behavior in 1.x -- the default group is not actually stored as a group for the user.

**Comment by EvilOlaf** [comment]
So basically `group add` has the same effect as `group set` when trying to add a 2nd group?

**Comment by zml2008** [comment]
It has the same effect if the player only has the default groups, because of how the default group is handled in 1.x added at runtime if the user has no groups in the permissions file).

**Comment by EvilOlaf** [comment]
I am not sure if there is a misunderstanding but maybe `default` was a bad example for the default player group. This could be any group name.
So the player was assigned to a group - lets call it `newbie` this time - then I tried to add the user to a 2nd and 3rd group.
