### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Typhome** [PEXPlugins/PermissionsEx#2341]
Hello,
I have one problem, so I'd like to know if is possible to configure it.
Let's take an example: Player A has VIP rank. I'll add VIP+ to player A, then player A will have VIP and VIP+ ranks, but prefix shows as VIP. VIP+ is higher than VIP, so it should show VIP+ not VIP.
Like.. it should show player rank (prefix) which has higher integer.
default 1
VIP 2
VIP+ 3
Elite 4
Helper 5
Moderator 6
Administrator 7

**Comment by BlackRavenMC** [comment]
Use /pex group <group> weight [weight] commnad. Lower weight value has more priority than a group with a higher value.

**Comment by FunnyMannyMC** [comment]
lele, rip prica

**Comment by Typhome** [comment]
BlackRavenMC, thank you, I didn't notice this weight command in Commands page.
