### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by BlackRavenMC** [PEXPlugins/PermissionsEx#2342]
When I try to import MySQL backend back to file backend I get this error:
http://pastebin.com/tcF3Xq4g

Config.yml:

> multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      uri: mysql://********/********
      user: ********
      password: ********
      aliases:
        permissions: server_permissions
        permissions_inheritance: server_inheritance
        permissions_entity: server_entity
      type: sql
updater: true
alwaysUpdate: false

**Comment by Stormbow** [comment]
Why would you post it in the PEX tickets when it says "Please report this to http://www.spigotmc.org/"?

Did you follow the [Migrating Between Backends](https://github.com/PEXPlugins/PermissionsEx/wiki/Migration-and-UUIDs#migrating-between-backends) documentation?

**Comment by BlackRavenMC** [comment]
Yes and I even tried in Minecraft 1.9 and did not worked.

**Comment by zml2008** [comment]
You've set the watchdog timeout too low -- you need to change that in the server.properties.
