### ISSUE TITLE
Issue with group regex.

### ISSUE THREAD

**Issue by Cilicou** [PEXPlugins/PermissionsEx#2349]
Hi,
I'm trying to limit usage of a lot of moded crops (harvestcraft) and i started doing them one by one (- -modifyworld.items.use.4133.on.block.?*) then looked at the regex part of the wiki and found out that normaly I could use something like "- -modifyworld.items.use.(4130-4190).on.block.?*" to cover all the crops.

Sadly it doesn't work. If I add them one by one or with the "or" regex (- -modifyworld.items.use.(4130|4131..etc).on.block.?*) then it works.

Here's my exact permissions and config files:
Thks in advance for the help :)

[permissions.txt](https://github.com/PEXPlugins/PermissionsEx/files/165626/permissions.txt)
[config.txt](https://github.com/PEXPlugins/PermissionsEx/files/165627/config.txt)

**Comment by Cilicou** [comment]
OOOH BTW .. i'm using PermissionsEx 1.22.10.

**Comment by zml2008** [comment]
The range regex has unfortunately had to be removed because UUIDs also contain the `-` character surrounded by numbers, which resulted in very long ranges in some cases (basically crashing the server whenever certain users logged in). I am exploring ways to bring it back in PEX 2.0.
