### ISSUE TITLE
Gradle Peer not Authenticated

### ISSUE THREAD

**Issue by Vediovus** [PEXPlugins/PermissionsEx#2351]
repositories {
    mavenCentral()
    maven {
        url "https://pex-repo.aoeu.xyz"
    }
}

dependencies {
    compile 'ru.tehkode:PermissionsEx:1.23'
}

      > Could not get resource 'https://pex-repo.aoeu.xyz/ru/tehkode/PermissionsEx/1.23/PermissionsEx-1.23.pom'.
         > Could not GET 'https://pex-repo.aoeu.xyz/ru/tehkode/PermissionsEx/1.23/PermissionsEx-1.23.pom'.
            > peer not authenticated

The let's encrypt cert that is used on the repo server + forcing to use https throws this exception. Any suggestions?

**Comment by zml2008** [comment]
Fix your java certificate store to include the appropriate root certificates.
