### ISSUE TITLE
BUG: pex user "name" toggle debug

### ISSUE THREAD

**Issue by RustyDagger** [PEXPlugins/PermissionsEx#2356]
I used to use this a lot when bug testing plugins but as of late soemthing seems to of changed now when used it only seems to print the first check it does to console any following checks are not printed. In my case I always see a worldguard chat permission. nothing else from any plugin despite not being an OP or any thing else like that the debug mode is just not showing all the information I know it used to be spammy but now its useless.

**Comment by zml2008** [comment]
Unfortunately due to major performance issues this feature had to be removed from the Bukkit permissions handler. Only global debug mode is supported (`/pex toggle debug`)
