### ISSUE TITLE
[2.x] Remove Parent Command Alias "-" Not Recognized

### ISSUE THREAD

**Issue by Favorlock** [PEXPlugins/PermissionsEx#2357]
After looking through the code it looks like "pex user Favorlock parents - group admin" should work, but for some reason it does not recognize the minus alias, yet it recognizes the plus alias adding a group.

**Comment by zml2008** [comment]
Yeah, the - is interpreted as a flag -- the flag parsing code probably just needs to ignore an isolated `-` rather than trying to extract it as a flag.
