### ISSUE TITLE
perform automatic commands after timed group expires

### ISSUE THREAD

**Issue by Kixot14** [PEXPlugins/PermissionsEx#2358]
Can manager of this project add something like option in config, under that option user be able to specify a list of commands for some groups. After group finished, this commands will automatically perform on player.
**Very important** to add feature of targeting by %marker% in this commands list.

For example: Group VIP have perms to set custom fly flag on their region, but after group VIP finished, i want to automatically removed this flag. So in this list i should specifi
command **- rg flag %region.marker% fly none**.
 %region.marker% just must be replaced by region name of player, whose group is expires.

Or enother example: Group Creative have perm to use /gm 1. Group is finished, but player still with GM1 mod. So to **automatic-perform-list** for Creative group i should add
command** - gm %player.marker% 0**.
%player.marker% must be replaced with name of this player (from Creative group).

**Comment by Kixot14** [comment]
**%Essentials.homepoint.marker%** will be great to!

**Comment by zml2008** [comment]
This is outside of the scope of PEX -- another plugin can hook into PEX 1.x or 2.x's events (not yet completed in 2.x/dev version's case) and provide this functionality. I would not be surprised if a plugin exists for this (probably one of the ranking plugins).
