### ISSUE TITLE
Feature: Command which enables more permissions/commands

### ISSUE THREAD

**Issue by HMlol** [PEXPlugins/PermissionsEx#2359]
Like the title says, it would be very useful if a command would be added which would enable more permissions, like an admin command which would make it able to ban or kick people when their command is turned on and which will turn that ability off if the same command is done again...

For instance:

/mod on --> Turns your ability to ban/kick/fly as a moderator on (with permissions.mod node)
/mod off --> Turns your ability to ban/kick/fly as a moderator off (with permissions.mod node)

Maybe with an extra shout out going to the other admins with a text like:

[player] is now active as Moderator!

and 

[player] is now inactive as Moderator!

...which you can turn on and off in a config.

Just wondering if this is possible to implement, because this would make it really easy to track what your moderators do.

**Comment by zml2008** [comment]
On March 18, 2016 9:37:58 AM PDT, Harm <notifications@github.com> wrote:
>Like the title says, it would be very useful if a command would be
>added which would enable more permissions, like an admin command which
>would make it able to ban or kick people when their command is turned
>on and which will turn that ability off if the same command is done
>again...
>
>For instance:
>
>/mod on --> Turns your ability to ban/kick/fly as a moderator on (with
>permissions.mod node)
>/mod off --> Turns your ability to ban/kick/fly as a moderator off
>(with permissions.mod node)
>
>Maybe with an extra shout out going to the other admins with a text
>like:
>
>[player] is now active as Moderator!
>
>and 
>
>[player] is now inactive as Moderator!
>
>...which you can turn on and off in a config.
>
>
>Just wondering if this is possible to implement, because this would
>make it really easy to track what your moderators do.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PEXPlugins/PermissionsEx/issues/2359

This is entirely out of the scope of pex.
