### ISSUE TITLE
group add behaves like group set on default players

### ISSUE THREAD

**Issue by lasercar** [PEXPlugins/PermissionsEx#2364]
When used on newly joined players (or after doing pex user delete), `/pex user <user> group add` replaces the default group as if it were `/pex user <user> group set`. This only happens the first time, then it works normally if adding further groups. If I `/pex user <user> group set default` first, the group add works normally and keeps the default group as it's supposed to.

**Comment by Stormbow** [comment]
PEX doesn't show the default group in the users list, so it looks like they have no group when they join, and then using group add shows only the added group when the users is actually in both groups.  If you [test their permissions](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2), you should find that they're getting permissions from both groups.
