### ISSUE TITLE
Permissions EX files keeps resetting

### ISSUE THREAD

**Issue by bryanpark428** [PEXPlugins/PermissionsEx#2366]
I made groups and permissions to each group in the .json file but when i restart the server, the files keeps resetting when i restart the server. and when i try to do commands for PEX within the game, but it wouldn't let me do "/pex group admin create" either.

**Comment by zml2008** [comment]
Run `/pex reload` to refresh the permissions file while the game is running.

`/pex group <name> create` is not a command -- a group is created automatically once data is added to it (so just start setting permissions)
