### ISSUE TITLE
i can't create groups, too many arguments!

### ISSUE THREAD

**Issue by zokenx** [PEXPlugins/PermissionsEx#2367]
Hi, I can't create groups, I get the error too many arguments, I have the latest version of spongeforge, pex, and forge, Help pls
![screenshot_10](https://cloud.githubusercontent.com/assets/18005784/13951788/ba61f12c-f011-11e5-82f6-eefc97782444.png)

**Comment by Levvy055** [comment]
I got the same problem

**Comment by EmanYm** [comment]
This issue was closed almost a year ago.  if you're having a simular issue you should really start a new ticket.
It would help if you provide Minecraft version, server jar (sponge, spigot, bukkit, whatever) and PEX version.
