### ISSUE TITLE
help with code

### ISSUE THREAD

**Issue by Dimatert9** [PEXPlugins/PermissionsEx#2368]
Hello. How i can get all player groups, and get group with highest priority, and set this group.

Player has this groups
- vip
- gl
- mvpp

In config i have
vip: 1
vipp: 2
mvp3
mvp: 4
gl: 5

How i can remove all player groups and set group with highest priority(gl)?
I have this code
http://pastebin.com/N1A6gSXc
and http://pastebin.com/WWCjCBvj (when i join, plugin send message "asd1")
But this code dont work. Can you help me?

**Comment by zml2008** [comment]
You declare the targetPrior variable inside the loop, so it's reset each iteration
