### ISSUE TITLE
Prefixes Not Working

### ISSUE THREAD

**Issue by Bdcollins111** [PEXPlugins/PermissionsEx#2369]
Hi, Im having trouble with group prefixes in PermissionsEx
even after I check that I am in group admin and that group admin has a prefix (both recognized when I check with /pex group admin and /pex user ItzOgSheep) it still does not show up when talking in chat. If this is an issue with the most recent version of PEx please let me know. Thanks always,
bdcollins111

**Comment by Stormbow** [comment]
You need a chat management plugin to get prefixes and suffixes displayed in-game.

Check out the [Prefix/Suffix Guide](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/?unread) for more information.
