### ISSUE TITLE
Users not being added to Groups

### ISSUE THREAD

**Issue by barringtonluke98** [PEXPlugins/PermissionsEx#2373]
Can someone tell me why my server wont add people to the pex groups? https://drive.google.com/folderview?id=0B798mKoSIJDJcGlDWEEzRkxGZGs&usp=sharing

**Comment by zml2008** [comment]
Because you configured something wrong? Provide more information (well, make the haystack smaller).

**Comment by barringtonluke98** [comment]
Here is the permissions file itself


On Wed, Mar 30, 2016 at 4:10 PM, zml <notifications@github.com> wrote:

> Because you configured something wrong? Provide more information (well,
> make the haystack smaller).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PEXPlugins/PermissionsEx/issues/2373#issuecomment-203677087>
>



-- 
*Luke Troendly Barrington*

**Comment by Stormbow** [comment]
What group are users not being added to?

Are you using a command to give users one group or more than one group?

What command exactly are you typing?
