### ISSUE TITLE
ISSUE when triyng to configure permissions

### ISSUE THREAD

**Issue by mauerizo-DownyCraft** [PEXPlugins/PermissionsEx#2376]
hello, i am having problem with the permissionsEx, first when i replace any archive it tells me the next message "Permissions manager is not accesable, Is the PermissionEx plugin enabled? " i will attach the screenshot
![2016-03-30_01 09 35](https://cloud.githubusercontent.com/assets/18174499/14153077/9cfacd44-f673-11e5-9105-54f63a26f310.png)

then, i try just to copy the config file and the permissions file(one that is configurated) to the files that i have on the server´s ´plugins files, also i will attach the files

here are the archives that the permissionsEx generate for default

this is the permissions file(default)

groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
schema-version: 1

this is the config file (default)

multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false

and this is the configured permissions file

groups:
  Miembro:
    prefix: '&7[&2downycraftero&7]&7 '
    default: true
    permissions:
    - modifyworld.*
    - chatmanager.chat.global.*
    - plotme.use.add
    - plotme.use.remove
    - MyPet.Permissions.UseExtendedPermissions
    - MyPet.user.command.capturehelper
    - MyPet.user.command.release
    - MyPet.behaviour.*
    - MyPet.user.command.respawn
    - MyPet.user.command.name
    - MyPet.user.command.name.color
    - MyPet.user.leash.*
    - MyPet.custom.skilltree.*
    - essentials.kits.iniciado
    - plotme.use.protect
    - plotme.limit.1
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.tp
    - plotme.use.home
    - plotme.use.info
    - essentials.spawn
    - essentials.help
    - essentials.kit
    - essentials.sethome
    - essentials.home
    - essentials.delhome
    - essentials.warp
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp.list
    - essentials.back
    - essentials.msg
    - essentials.pay
    - essentials.sell
    - essentials.list
    - essentials.rules
    - essentials.helpop
    - plotme.use
    - ultimatearena.player
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.motd
    options:
      rank: '900'
  Guerrero:
    inheritance:
    - Miembro
    permissions:
    - modifyworld.*
    - chatmanager.chat.global
    - essentials.signs.use.free
    - MyPet.behaviour.*
    - plotme.use.auto
    - MyPet.user.command.capturehelper
    - MyPet.user.command.release
    - MyPet.user.command.respawn
    - MyPet.user.command.name
    - MyPet.Permissions.UseExtendedPermissions
    - MyPet.user.command.name.color
    - MyPet.user.leash.*
    - MyPet.custom.skilltree.*
    - essentials.kit
    - plotme.limit.3
    - essentials.signs.use.warp
    - essentials.motd
    - essentials.kits.guerrero
    - essentials.kits.Guerrero
    options:
      rank: '890'
      prefix: '&7[&2Downy&4PvP&7]'
  VIP:
    prefix: '&7[&6VIP&7]&7 '
    inheritance:
    - Guerrero
    permissions:
    - essentials.enderchest
    - MyPet.user.command.capturehelper
    - MyPet.user.command.release
    - MyPet.user.command.respawn
    - essentials.socialspy.others
    - MyPet.user.command.name
    - MyPet.behaviour.*
    - MyPet.user.command.name.color
    - MyPet.user.leash.*
    - MyPet.custom.skilltree.*
    - essentials.chat.color
    - modifyworld.*
    - essentials.repair
    - chatmanager.chat.global
    - plotme.use
    - essentials.fly
    - essentials.kit
    - plotme.limit.6
    - essentials.kits.Vip
    - essentials.kits.vip
    options:
      rank: '800'
  VIP_ORO:
    prefix: '&7[&eVIP_ORO&7]&7'
    inheritance:
    - VIP
    permissions:
    - essentials.hat
    - MyPet.user.command.capturehelper
    - MyPet.user.command.release
    - MyPet.user.command.respawn
    - MyPet.user.command.name
    - MyPet.user.command.name.color
    - MyPet.behaviour.*
    - essentials.invsee
    - MyPet.user.leash.*
    - plotme.limit.*
    - essentials.gamemode
    - MyPet.custom.skilltree.*
    - essentials.heal
    - essentials.kit
    - essentials.kits.viporo
    options:
      rank: '600'
  Moderador:
    prefix: '&7[&1Moderador&7]&7 '
    inheritance:
    - VIP
    permissions:
    - essentials.gamemode
    - essentials.exp
    - essentials.give
    - MyPet.user.command.capturehelper
    - MyPet.user.command.release
    - MyPet.user.command.respawn
    - MyPet.user.command.name
    - MyPet.user.command.name.color
    - MyPet.user.leash.<MyPet-Type>
    - MyPet.custom.skilltree.*
    - essentials.set
    - essentials.fly.*
    - essentials.kick
    - essentials.ban
    - plotme.use
    - modifyworld.mobtarget.*
    - modifyworld.mobtarget.*
    - modifyworld.*
    - chatmanager.chat.global
    - chatmanager.chat.color
    - chatmanager.chat.magic
    - chatmanager.chat.bold
    - chatmanager.chat.strikethrough
    - chatmanager.chat.underline
    - chatmanager.chat.italic
    - chatmanager.override.ranged
    - essentials.enderchest.others
    - essentials.tp
    - essentials.tp.others
    - essentials.tphere
    - essentials.time
    - essentials.time.set
    - essentials.killall
    - essentials.signs.use.free
    - essentials.vanish
    - essentials.signs.use.warp
    - essentials.motd
    options:
      rank: '100'
  Admin:
    prefix: '&7[&4Admin&7]&7 '
    inheritance:
    - Moderador
    permissions:
    - essentials.vanish
    - essentials.banip
    - essetnials.unbanip
    - essentials.spawnmob.*
    - essentials.killall
    - essentials.enderchest.others
    - essentials.modify
    - essentials.jails
    - essentials.deljail
    - essentials.invsee
    - essentials.invsee.modify
    - essentials.burn
    - essentials.clearinventory.others
    - essentials.ignore
    - essentials.afk
    - essentials.speed
    - essentials.enchant
    - essentials.gamemode.others
    - essentials.time
    - essentials.time.set
    - essentials.fly.others
    - essentials.bigtree
    - ChestShop.shop.*
    - ChestShop.admin
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.motd
    options:
      rank: '2'
  OWNER:
    prefix: '&7[&b&lOWNER&7]&7 '
    permissions:
    - '*'
    options:
      rank: '1'

if i replace the permissions file the permissions doesnt work (prefix) and also any player that doesnt have OP have the normal player permissions, just if there no were plugin instaled

i have the 1.9.2 spigot version (spigot-1.9.2-20160330a.jar)

i dont know if you need all this information, but just in case you needed, i put it here.  

i wish you can solve the problem D: i have benn trying for 3 days, without lucky. so if you can solutionate my issue i will be bery happy :D thankyou for your help

**Comment by zml2008** [comment]
There was probably an error in your permissions file -- check for errors on server startup and make sure your permissions file passes validation on http://yaml-online-parser.appspot.com

**Comment by mauerizo-DownyCraft** [comment]
how do i check it in your link? i paste it and then what? thank you
