### ISSUE TITLE
PermissionsEx with EssentialsX?

### ISSUE THREAD

**Issue by mauerizo-DownyCraft** [PEXPlugins/PermissionsEx#2377]
hello, i got a spigot server, and the essentials from bukkit doesnt work on it, so i try to use the essentialsX but when i try to put PermissionEx the prefixes arent displayed, help pls

**Comment by Stormbow** [comment]
The [EssentialsXChat.jar](https://ci.drtshock.net/job/EssentialsX/) and [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) plugin are required in order for prefixes and suffixes to be displayed on your server.  See the [Basic Prefix / Suffix Tutorial](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/) for more information on this issue.
