### ISSUE TITLE
PermissionsEx Lag Join

### ISSUE THREAD

**Issue by WonderWizard** [PEXPlugins/PermissionsEx#2379]
Hey

When a player join the server and massive lag will happen can't even chat or do command.

And player took pretty huge delay to join server and it delayed the lag pretty long. But when Admin with /op join the server it took only 2-4 seconds.

We tried by removing PermissionsEx then ask a player to relog and the lag is gone the problem may be PermissionsEx but we have no clue how to fix it, we even reset all players from Pex Groups but nothing changed.

Server Info:
- Minecraft-worlds hosting 6GB Ram
- Plugins (56): ColoredSigns, SimpleBroadcast, PluginManager, Lockette, SuperTrails, TitleWelcomeMessage, VoxelSniper, CreeperHeal, Tablist, MoreHearts, ChatColor, CoreProtect, WorldEdit, Essentials, ClearLag, CrackShot, Frame_Protector, Votifier, Multiverse-Core, ProtocolLib, ServerMotd, EssentialsChat, PermissionsEx, EffectLib, mcMMO, Vault, ChairStairs, MassiveCore, EnjinMinecraftPlugin, WELoader, CreativeGates, HolographicDisplays, KillerMoney, Marriage, WorldGuard, Brewery, PermissionsExTabColors, Multiverse-Inventories, PhatLoots, ServerSigns, VoteLink, SimpleVoteListener, EssentialsSpawn, MagicSpells, RPG_Items, ScoreboardStats, Citizens, Bankcraft, Shopkeepers, EchoPet, SafeBank, NovaGuilds, Sentry, MythicMobs, Quests, MoreItems
- Timings http://www.spigotmc.org/go/timings?url=15581714

**Comment by zml2008** [comment]
> Total: 0.142s (Ticks: 25) - Sample Time: 1.24s

You need to run timings for longer to get any useful data.

SQL or file backend? Try running a WarmRoast profile to see what parts of the server are taking a long time as well.

**Comment by WonderWizard** [comment]
Here Timings: https://timings.spigotmc.org/?url=15593235

**Comment by WonderWizard** [comment]
Here Timings 200 seconds

https://timings.spigotmc.org/?url=15591733

**Comment by Adondriel** [comment]
This generally happens when you have too many users, and are using flatfile storage. That is why im switching from bperms.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
