### ISSUE TITLE
Group´s options not working

### ISSUE THREAD

**Issue by mark22padre** [PEXPlugins/PermissionsEx#2380]
When I set the build option to true or the prefix/suffix it isn´t working. I only have pex and essentialsX installes on 1.9.2 and I can´t build or interact and the prefixes aren´t displayed.

**Comment by Stormbow** [comment]
```build: true``` is a function of EssentialsAntibuild.  If you don't have EssentialsAntibuild.jar in your server's plugins folder, this options setting is unnecessary and won't have any affect on your server if you do add it to a group.  See the [Minecraft & PEX Troubleshooting Guide](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/) for more about both issues.

In a similar manner, the [EssentialsChat.jar](https://ci.drtshock.net/job/EssentialsX/) and [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) are required in order for prefixes and suffixes to be displayed on your server.  See the [Basic Prefix / Suffix Tutorial](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/) for more information on this issue.
