### ISSUE TITLE
Allow filtering for debug

### ISSUE THREAD

**Issue by bloodmc** [PEXPlugins/PermissionsEx#2382]
Currently, whenever I turn on debug there is a good chance it will cause my server to lag as well as spam my logs with a ton of output that I may not need. It would be nice to be able to provide a filter by providing a prefix to use during debug. For example, if I want to figure out what perms are being blocked in griefprevention I would type

'/pex debug griefprevention'

Any permission node that contains this word would be logged in debug and everything else would be filtered out.

**Comment by Stormbow** [comment]
Turn on debug mode only for one person at a time.  [Debug Guide here](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2).

**Comment by zml2008** [comment]
This is a pex2.0 issue I asked blood to open -- since per-subject debug mode is not used as much, this is something I'm trying.

**Comment by zml2008** [comment]
I believe I added this but it got mixed in with SQL changes. The command to toggle debug mode with a filter is `/pex debug [filter]`
