### ISSUE TITLE
1.23.x branch repo's broken again...

### ISSUE THREAD

**Issue by Sycholic** [PEXPlugins/PermissionsEx#2388]
Full log here >> http://pastebin.com/L9cc7LH5

------------------------------------------------------------------------
Building PermissionsEx 1.23.5-SNAPSHOT
------------------------------------------------------------------------
Downloading: http://pex-repo.aoeu.xyz/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml

Could not transfer metadata org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): peer not authenticated
Failure to transfer org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): peer not authenticated
Downloading: http://pex-repo.aoeu.xyz/com/zachsthings/netevents/1.1-SNAPSHOT/maven-metadata.xml

Could not transfer metadata com.zachsthings:netevents:1.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): peer not authenticated
Failure to transfer com.zachsthings:netevents:1.1-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.zachsthings:netevents:1.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): peer not authenticated
Downloading: http://pex-repo.aoeu.xyz/com/zachsthings/netevents/1.1-SNAPSHOT/netevents-1.1-SNAPSHOT.pom

Downloading: http://pex-repo.aoeu.xyz/net/gravitydevelopment/updater/updater/maven-metadata.xml

Could not transfer metadata net.gravitydevelopment.updater:updater/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): peer not authenticated

Failed to execute goal on project PermissionsEx: Could not resolve dependencies for project ru.tehkode:PermissionsEx:jar:1.23.5-SNAPSHOT: Failed to collect dependencies for [org.bukkit:bukkit:jar:1.8.8-R0.1-SNAPSHOT (provided), org.yaml:snakeyaml:jar:1.9 (provided), com.zachsthings:netevents:jar:1.1-SNAPSHOT (provided), junit:junit-dep:jar:4.10 (test), commons-dbcp:commons-dbcp:jar:1.4 (compile), net.gravitydevelopment.updater:updater:jar:LATEST (compile), com.mojang:AccountsClient:jar:unspecified (compile)]: Failed to read artifact descriptor for com.zachsthings:netevents:jar:1.1-SNAPSHOT: Could not transfer artifact com.zachsthings:netevents:pom:1.1-SNAPSHOT from/to pex-repo (http://pex-repo.aoeu.xyz): peer not authenticated -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by Sycholic** [comment]
seems to be something to do with java and certs if this is really an issue not just for me not sure.  Win7. java8.77 maven 3.3.9 git 2.8.0 and netbeans 8.02

**Comment by zml2008** [comment]
Yeah, this is an issue with your java setup -- seems to be having issues with SSL certs. This works fine for me on Arch with openjdk, so you're kinda on your own here, especially if it works fine in your browser (go to https://pex-repo.aoeu.xyz to see).

**Comment by Sycholic** [comment]
maybe I'll try openjdk.  someone else on spigot tried it out also had no issues. meh PKIX issues.

**Comment by Sycholic** [comment]
found the issue apparently java JDK8 for windows does not support certs from Let's Encrypt

this could be possible issue for others in windows so documenting how solved this
since we should have git... in gitbash running as admin password default for your keystore unless you changed it is 'changeit'

curl --get https://letsencrypt.org/certs/isrgrootx1.pem --output isrgrootx1.pem
curl --get https://letsencrypt.org/certs/letsencryptauthorityx1.der --output letsencryptauthorityx1.der
keytool -trustcacerts -keystore $JAVA_HOME/jdk1.8.0_77/jre/lib/security/cacerts -storepass changeit -noprompt -importcert -alias isrgrootx1 -file ~/isrgrootx1.pem
keytool -trustcacerts -keystore 'c:/program files/java/jdk1.8.0_77/jre/lib/security/cacerts' -storepass changeit -noprompt -importcert -alias isrgrootx1 -file ~/isrgrootx1.pem

soon as I did that had no problems at all.... hope this might be of help to anyone else later.
