### ISSUE TITLE
Configuration must be fixed before PEX will enable?

### ISSUE THREAD

**Issue by TheOtakuJames** [PEXPlugins/PermissionsEx#2389]
Hi there,

I have been helping a friend set up their server, as I have my own, but PEX has refused to work. When the server loads, this problem has been appearing: http://pastebin.com/FyV0pPxf

Here's her permissions.yml: http://pastebin.com/jGg5gee3

I have the exact same verson as her (1.23.4) on my server, and it works perfectly fine. I have also been through her permissions.yml and made the syntax the same as mine. We even tried re-installing the plugin. 

How can this error be fixed?

~James

**Comment by zml2008** [comment]
As it says in the error, you have a syntax error in your permissions.yml. The group trusted (line 227) is improperly indented. There may be more errors, so you can check on http://yaml-online-parser.appspot.com.

**Comment by TheOtakuJames** [comment]
I put it through that, changed 1 thing and it says there are no errors. As soon as I paste the fixed version into the configs, it removes the space before "groups" and says the exact same error...
