### ISSUE TITLE
[FEATURE] Multi-server permissions

### ISSUE THREAD

**Issue by DoNotSpamPls** [PEXPlugins/PermissionsEx#2390]
Let me explain the feature. For example you have 3 servers - Survival, Creative and Hub - connected with BungeeCord (all of them are hooked up with a single MySQL database). But for example, I want to give people /give in Creative, but not In Survival. It would be nice to have that sort of feature in PEX (correct me if feature already exists)

**Comment by philip-ulrich** [comment]
You can do this with per world permissions and world inheritance. Per world currently isn't working in 1.9 though. Additionally, you have to do a /pex reload on each server after the change.. It's kind of implemented and kind of not.

**Comment by dracnis** [comment]
I'm here for the same idea so ... i explain :
Currently I have some servers and that's work with grade and group's sames databases for each servers but different permission's database for each kind of server ( bedwar, mobarena, ... ).
So what's the problem ?
If I want add global perm ( like new group prefix ) I must change it on every server.
Already tried the philip'ulrich's idea who's the opposite of mine.
And now what's the problem ?
Like he said "Per world currently isn't working in 1.9 though. Additionally, you have to do a /pex reload on each server after the change.." when we have only 1 world per server that's the only problem but when we have 5 worlds in a server we need to add 5 times permissions per server :/
My idea ?
Add a 4's table database like a "global database" like this we put each kind of server with 3 sames tables ( rank, group and global_permission ) and a personal permission's file.
Can also add a scheduler to reload global database each 10 minutes ( can edit in config file )
If you could that's will be great :)
Thanks.

**Comment by philip-ulrich** [comment]
@dracnis you don't have to do the permission adding 5 times. Just do world inheritance and send them all to a parent world where you have the permissions. 

I can't speak for the devs, but it seems like they are leaving 1.x to die and solely working on 2.0. If you are trying to get them to implement new things into 1.x, I don't think they are going to do it. 

I just switched to PowerfulPerms and it meets all my needs perfectly. You might consider looking into that.

**Comment by zml2008** [comment]
Yeah, 2.0 supports per-server permissions (and it would be way more complicated to implement per-server permissions on 1.x since it's not designed around anything but per-world permissions). Additionally, 2.0 is very close to having SQL support (as in it's implemented but performance tweaks are still in progress), so we're getting pretty close to 1.x users being able to do everything they want to in 2.x.

**Comment by DoNotSpamPls** [comment]
@zml2008 How do I download PEX 2.0?

**Comment by zml2008** [comment]
From https://ci.yawk.at/job/PermissionsEx -- keep in mind the command structure is entirely different and documentation is a bit limited at this point though.

**Comment by DoNotSpamPls** [comment]
Where is the documentation?

**Comment by zml2008** [comment]
https://github.com/PEXPlugins/PermissionsEx/tree/master/doc

**Comment by DoNotSpamPls** [comment]
Sorry for the many questions, but how do I connect the plugin with MySQL?

**Comment by zml2008** [comment]
That's not yet implemented in 2.0 (and is in fact what I am working on
right now (aka each time you ask a question I switch away from finishing
up the implementation))

**Comment by DoNotSpamPls** [comment]
Oh, sorry :(. I will wait
