### ISSUE TITLE
Failed to read artifact descriptor for ru.tehkode.PermissionEx 1.23

### ISSUE THREAD

**Issue by elraro** [PEXPlugins/PermissionsEx#2397]
Hello.

Im trying to use PermissionEx with Maven, but i get always this error...

Failed to read artifact descriptor for ru.tehkode.PermissionEx 1.23

		<repository>
			<id>PermissionEx-repo</id>
			<url>https://pex-repo.aoeu.xyz</url>
		</repository>

		
		<dependency>
			<groupId>ru.tehkode</groupId>
			<artifactId>PermissionsEx</artifactId>
			<version>1.23.1</version>
		</dependency>

Im doing something wrong?

**Comment by zml2008** [comment]
That looks fine -- your jvm setup is probably broken and isn't properly accepting SSL certificates from LetsEncrypt.
