### ISSUE TITLE
2 UUID

### ISSUE THREAD

**Issue by MisterQuatsch** [PEXPlugins/PermissionsEx#2398]
Hey, when i try to do the mysql connection i get 2 diffrend uuid´s on difrend servers:
http://prntscr.com/avleda

**Comment by zml2008** [comment]
On April 22, 2016 1:22:25 PM PDT, MisterQuatsch <notifications@github.com> wrote:
>Hey, when i try to do the mysql connection i get 2 diffrend uuid´s on
>difrend servers:
>http://prntscr.com/avleda
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PEXPlugins/PermissionsEx/issues/2398

Online mode and offline mode uuids are different.

**Comment by MisterQuatsch** [comment]
How can i fix it?
I run a Bungeecord network and so i can only use Offline mode and only the bug is online mode.

**Comment by zml2008** [comment]
You have to have ip-forwarding enabled properly on both client and server -- take a look at the bungee docs.
