### ISSUE TITLE
Warps, Kits, and Portals [HELP]

### ISSUE THREAD

**Issue by Atomosie** [PEXPlugins/PermissionsEx#2401]
I found a problem where I have all the correct permissions for my multiverse portals, essentials (kits), and essentials (warps). All it says in the console is:

28.04 23:20:06 [Server] INFO §cAtomosie §4was denied access to command.

Except for multiverse portals. That just doesn't work at all unless you're operator.

This is my permissions file:

groups:
  default:
    options:
      default: true
    permissions:
        - modifyworld.*
        - essentials.balance
        - essentials.balancetop
        - essentials.pay
        - essentials.pay.multiple
        - essentials.sell
        - essentials.worth
        - essentials.afk.auto
        - essentials.getpos
        - essentials.help
        - essentials.ignore
        - essentials.itemdb
        - essentials.list
        - essentials.mail
        - essentials.mail.send
        - essentials.me
        - essentials.motd
        - essentials.msg
        - essentials.realname
        - essentials.recipe
        - essentials.rules
        - essentials.seen
        - essentials.suicide
        - essentials.ping
        - essentials.spawn
        - essentials.delhome
        - essentials.home
        - essentials.home.bed
        - essentials.sethome.bed
        - essentials.sethome
        - essentials.tpa
        - essentials.tpaccept
        - essentials.tpahere
        - essentials.tpdeny
        - essentials.warp
        - essentials.warp.list
        - essentials.warp.Help
        - essentials.warp.PvP
        - essentials.warp.Market
        - essentials.warp.Wild
        - essentials.signs.create.mail
        - essentials.signs.create.trade
        - essentials.signs.create.warp
        - essentials.signs.use.balance
        - essentials.signs.use.buy
        - essentials.signs.use.disposal
        - essentials.signs.use.enchant
        - essentials.signs.use.free
        - essentials.signs.use.heal
        - essentials.signs.use.info
        - essentials.signs.use.kit
        - essentials.signs.use.mail
        - essentials.signs.use.repair
        - essentials.signs.use.sell
        - essentials.signs.use.spawnmob
        - essentials.signs.use.trade
        - essentials.signs.use.warp
        - griefprevention.lava
        - griefprevention.claims
        - griefprevention.createclaims
        - multiverse.access.*
        - multiverse.portal.access.*
        - essentials.kits
        - essentials.kits.Starter
        - essentials.kits.Claims
schema-version: 1

Thank you.

**Comment by Atomosie** [comment]
*bump*

**Comment by Stormbow** [comment]
Are you using Minecraft 1.9 and PEX 1.23.4?

Add inheritance: [] to your group.  PEX will then (likely) function correctly.

**Comment by Atomosie** [comment]
Thanks, I'll look into that

**Comment by Atomosie** [comment]
Sorry, but one last thing. Portals still don't work. No error message.

**Comment by zml2008** [comment]
We have no involvement with your portals plugin -- talk to them to check what the issue is (and you can run `/pex toggle debug` to see which permissions are being checked (logged to the console)).

**Comment by Atomosie** [comment]
Ok, I just got a different portals plugin, and it seems to work. Thanks for all the help.
