### ISSUE TITLE
Don't know how to configure per-world groups

### ISSUE THREAD

**Issue by SmokingTrooper** [PEXPlugins/PermissionsEx#2402]
Hi, as you saw in the title i don't know how to configure per-world groups.
Can someone pls help me?!

Thanks!

- Sammie Kool

**Comment by Stormbow** [comment]
Sorry for the slow reply.  I don't watch these tickets as much as I watch [the forums](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/).

Start by reading the [Multiworld Documentation](https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#pex-multiworld), and take a look at [this example]9http://pastebin.com/ieyQU7w8) to see how multiworld settings are listed in the permissions.yml file.

**Comment by SmokingTrooper** [comment]
Sorry for still having this open, I already know how to do this but there is something wrong and I think you are the best man to know what's going on. Here is the link: https://bukkit.org/threads/permissionsex-stopped-working-after-restart.417116/#post-3370301

Can you please help me?

- Sammie Kool

**Comment by Stormbow** [comment]
Ahhhh!  Looks like you've used the tab key in your file.  YAML (.yml) files don't like the tab key.  You'll need to replace any and all tab key uses with plain spaces.  If you use [Notepad++]9http://notepad-plus-plus.org/), you can see where the tab key has been used because they come up as red arrows pointing to the right in your file.

**Comment by Stormbow** [comment]
After you make that correction, copy your file to [Pastebin](http://pastebin.com) and post the link to it in this thread.

**Comment by SmokingTrooper** [comment]
I already know the problem. at the end of the permissions.yml was a tab

**Comment by Stormbow** [comment]
Excellent.
