### ISSUE TITLE
PermissionEx not working HELP 

### ISSUE THREAD

**Issue by CreepersDoCraft** [PEXPlugins/PermissionsEx#2403]
Hi i have been using permissions ex for about a year now and i started a new server now in 1.9.2 and for some reason none of my perms are working and its not adding new players to the permissions.yml is there a 1.9.2 version or is it my permissions.yml

Here is my permissions.yml

groups:
  guest:
    options:
      default: true
    permissions:
    - modifyworld.*
    - essentials.mail
    - essentials.mail.send
    - essentials.mail.sendall
    - multiverse.core.spawn.set
    - craftconomy.currency.info
    - craftconomy.bank.list
    - craftconomy.bank.withdraw
    - craftconomy.bank.balance
    - craftconomy.bank.create
    - craftconomy.money.log.others
    - craftconomy.money.log
    - craftconomy.money.top
    - craftconomy.money.pay
    - craftconomy.money.balance.others
    - craftconomy.money.balance
    - easywarp.sign.use
  VIP:
    inheritance:
    - guest
    options:
      default: false
    permissions:
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick.magic
    - essentials.msg.magic
    - essentials.msg.format
    - essentials.msg.color
schema-version: 1
users: {}

**Comment by Stormbow** [comment]
As of PEX 1.23.4 and Minecraft 1.9, all groups must have an inheritance section.  See line 19 of [this example]9http://pastebin.com/8ZSHxauG) to see how you give a group this needed section when they don't actually inherit from other groups.

Post again in this thread if the above correction does not resolve your problem(s).

**Comment by CreepersDoCraft** [comment]
it didnt help it wont add people do my guest group here

groups:
  guest:
    options:
      default: true
    permissions:
    - essentials.help
    - modifyworld.*
    - essentials.mail
    - essentials.mail.send
    - essentials.mail.sendall
    - multiverse.core.spawn.set
    - craftconomy.currency.info
    - craftconomy.bank.list
    - craftconomy.bank.withdraw
    - craftconomy.bank.balance
    - craftconomy.bank.create
    - craftconomy.money.log.others
    - craftconomy.money.log
    - craftconomy.money.top
    - craftconomy.money.pay
    - craftconomy.money.balance.others
    - craftconomy.money.balance
    - easywarp.warp.*
    - easywarp.warp.factions
    - easywarp.warp.hub
    - shop.buy
    - shop.sell
    - shop.tab.*
    - multiverse.core.spawn.self
  VIP:
    inheritance:
    - guest
    options:
      default: false
    permissions:
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick.magic
    - essentials.msg.magic
    - essentials.msg.format
    - essentials.msg.color
    - shop.enchantments
    - essentials.heal
  Mod:
    inheritance:
    - guest
    options:
      default: 'false'
      build: 'true'
      prefix: 'Mod '
      suffix: ' the Scary'
    permissions:
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.notify
    - essentials.broadcast
    
    schema-version: 1
users:
  79bbc761-565d-4ca4-8ae2-5c081273b568:
    group:
    - guest
    options:
      name: drogongirl1738
  5d6bfdef-f6f7-4372-a266-669895067715:
    group:
    - VIP
    options:
      name: CreepersDoCraft

**Comment by Stormbow** [comment]
You didn't do what I told you to do.  Do that and then copy your file to [Pastebin](http://pastebin.com).  Do not edit anything out of the file before posting it to Pastebin.
