### ISSUE TITLE
https://github.com/piaolingwuyu/supper/blob/master/supper1/index.html

### ISSUE THREAD

**Issue by piaolingwuyu** [PEXPlugins/PermissionsEx#2407]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/a156d5ced853bffe9144)

**Comment by Stormbow** [comment]
Never use vTeamCity versions of Essentials.  They're all problematic.

**Comment by zml2008** [comment]
You're using the 1.8 updates of PEX and Essentials provided by Spigot on a 1.7.9 server. Also we only support official releases -- the spigot updates were only temporary and have been replaced by our own 1.22.x releases.
