### ISSUE TITLE
The command: /pex doesn't work

### ISSUE THREAD

**Issue by Atomosie** [PEXPlugins/PermissionsEx#2408]
As in the title, the /pex command doesn't work. I tried to use it in console, I redownloaded permissionsex, created a new usergroup called: owner that has all the permissions for /pex.

**This is my permissions file (config afterwards):**
[permissions.yml](https://www.dropbox.com/s/0emhpuk4vcr21l2/permissions.yml?dl=0)

**config file:**

[config.yml](https://www.dropbox.com/s/lfav8d0x270kttp/config.yml?dl=0)

If you could help in any way, that would be very appreciated.

**Comment by Stormbow** [comment]
Your file is indented incorrectly.  Use [this file](http://pastebin.com/gg4cct1F) instead.

**Comment by Atomosie** [comment]
Thank's so much. You have saved meh!

**Comment by Stormbow** [comment]
You're welcome. :)
