### ISSUE TITLE
Comand_block issue

### ISSUE THREAD

**Issue by dino147** [PEXPlugins/PermissionsEx#2409]
I've found a bug,if a player writes in command_block : /permissionex:promote @p he will be promoted without having the permission .

**Comment by dino147** [comment]
And other commands................./pex user @p prefix .........../pex user @p group add....
Could you solve this ?

**Comment by Stormbow** [comment]
This is why Minecraft itself tells you not to give commandblocks to just anyone on a server.

**Comment by zml2008** [comment]
Yeah, command blocks run all commands with all by design -- nothing we can do about it in Bukkit.

Sponge allows assigning permissions to command blocks however, which would allow you to be more granular in how you allow users to use command blocks.
