### ISSUE TITLE
User not in ladder!

### ISSUE THREAD

**Issue by polarstenman** [PEXPlugins/PermissionsEx#2413]
I have been trying many many different things and commands but nothing is working as far as groups or prefixes.
Plugin List:
Vault
Chatmanager
Permissionsex

V 1.7.9

![permssions](https://cloud.githubusercontent.com/assets/19374184/15274859/e2d1be96-1a8a-11e6-9356-9edc99edbf8b.png)

**Comment by Stormbow** [comment]
1. ChatManager is not supported.

2. Your permissions.yml file must follow [the example](http://pastebin.com/8ZSHxauG).  (Your indentation is wrong.)
