### ISSUE TITLE
PermissionsEx 1.23.4 not working

### ISSUE THREAD

**Issue by Raff64spr** [PEXPlugins/PermissionsEx#2414]
Hi,
When i start my server all the plugins works but if i try to do /pex nothing happens.
Plugin List:
![pluginslist](https://cloud.githubusercontent.com/assets/16598984/15274874/b23cb12c-1abd-11e6-8882-345006c02da8.PNG)

Sorry for bad english but im italian

**Comment by Stormbow** [comment]
You permissions.yml file must follow [the example](http://pastebin.com/8ZSHxauG).
