### ISSUE TITLE
[Feature Request] Multiple Groups/Prefixes

### ISSUE THREAD

**Issue by jsnbrown1989** [PEXPlugins/PermissionsEx#2416]
It may be a bit late for feature requests but I have recently converted from GM from 1.7.10 to PermissionsEx and so far things are going good. I appreciate the hard work you put into your plugin! 

One thing I have ALWAYS wanted for the old GM and now am wishing for with PEX is the ability to add multiple permission ranks to a user. It feels like it might be not very complex to add but this is me, a non programmer, on this side of the plugin.. Idk . 

So, in a bit more detail. 

In your config, it would just list the permissions like normal but if you do a certain command, it could compound two separate permission groups. 

The only issue to consider is priorities. With this, could always add an option to add a priority to the rank in the config. Or.. Make it more granular and make it per permission.

**Comment by Stormbow** [comment]
This sort of thing is handled by the Chat Management plugin you're using on your server, not by PEX.  PEX only provides a convenient place to store a custom prefix and suffix for a group.  PEX doesn't actually do any of the displaying of these in-game.  I'd recommend this to whomever may be in charge of the chat plugin I used on my server.

**Comment by Stormbow** [comment]
After re-reading that, it looks like you're also asking for a feature to add a bulk number of permissions to a group with a single command.  If that's true, it's something @zml2008 would have to respond to.

**Comment by jsnbrown1989** [comment]
It could in theory definitely be handled via a chat management plugin and I had thought about that but it's really more of a permission based thing. 

I guess I'm looking for it to be possible to add more than one group onto one player and making all prefixes visible in chat with priorities on permissions. 

A lot of that is reliant on the permission plugin rather than the chat plugin since there would be a decent number of backend gears that need to be moving. 

Idk. Apparently this isn't as heavily sought after as I thought it was as it appears this is the first request for it. I do think that the feature would be enjoyed though by PEX's user base esp since it is such a powerful permission plugin. Adding something like this would be a killer new feature for Sponge based PEX.

**Comment by zml2008** [comment]
I'm pretty sure what you're talking about has been supported basically the entire time PEX has existed. Any user and any group can inherit from multiple groups. However, multiple prefixes has to be handled by a chat plugin -- Simple-Prefix handles this (just remember to enable Vault and multiple prefix support).

**Comment by Stormbow** [comment]
@jsnbrown1989 : Don't forget there's already weight values in the current system too, though these also won't enable multiple prefix/suffix use.

**Comment by jsnbrown1989** [comment]
Thank you guys for your assistance with researching this out then. I know you guys could have just closed this without an after thought. Really is great of you guys. Since I will be running a sponge server and I do not see a version or related plugin of the suggested chat plugin already existing. It looks like it's off to see if I can get a custom one created. 

Thanks again!
