### ISSUE TITLE
Questions about mysql storage

### ISSUE THREAD

**Issue by Gerolmed** [PEXPlugins/PermissionsEx#2417]
I have a bungeecord server but due to problems with bungeeperms i would like to have permissionsex (i put it on every server). Thats why i wanted to know that if I connect with mysql does it store the players with the their ranks so that if someone gets a rank in the lobbyserver he gets the rank on all server or do i have to change stuff in the code?

**Comment by zml2008** [comment]
Yes, when PEX is connected to a SQL database all information is stored in the database, available to share across servers.
