### ISSUE TITLE
SQL Backend Error

### ISSUE THREAD

**Issue by tricky538** [PEXPlugins/PermissionsEx#2420]
I changed my backend to SQL and restarted the server but it whent back to file and it now only works when the server is active and i manually set the backend to sql with "pex backend sql". It doenst go to SQL automatically on startup. What to do?!

**Comment by zml2008** [comment]
Running that command only changes the backend for the current server run. For a permanent change, you have to edit the config.yml to change the active backend.

**Comment by tricky538** [comment]
I changed it in de config but when restarting the node it adds the file at the bottom of the backend under the sql backend and doesnt follow the sql backend
