### ISSUE TITLE
Prefix not showing!!!

### ISSUE THREAD

**Issue by ItsTuffy** [PEXPlugins/PermissionsEx#2426]
Hi, when i started my server with the Essentials plugins, and also permissionsEX, i set up my groups and everything, the prefix didnt work, its annoying and bothering to me. If there is a fix please let me know at [email removed, respond in issue tracker]. Thank you!

**Comment by zml2008** [comment]
1. Is EssentialsChat installed
2. Are you either on 1.7.10 or using EssentialsX?
3. Pastebin your permissions config

**Comment by Stormbow** [comment]
Also, if you're using EssentialsChat or EssentialsXChat, you will need Vault installed too.

**Comment by Stormbow** [comment]
This issue appears to be resolved.
