### ISSUE TITLE
Pex 1 Use

### ISSUE THREAD

**Issue by iJDuhb** [PEXPlugins/PermissionsEx#2428]
This sorta isn't a issue but can you have a one time use permission like give the permission then it will remove after 1 use? but you can make more uses if you give the perm again you get other use...

**Comment by Stormbow** [comment]
PermissionsEx has "timed permissions", which can be used for a set amount of time (typically specificed in seconds).

For example, Stormbow could have /fly for 600 seconds (10 minutes), and later get /fly for another 10 minutes.  I believe the 2nd timed permission will also overwrite the previous timed permission, when used for the same command/permission node, so if the first 10 minutes were not used up entirely, the remainder would be lost when the 2nd set of 10 minutes is obtained.

The command to give a user a timed permission node is: 
`/pex user <user> timed add <permission> [lifetime] [world]
    Add timed <permissions> to <user> for [lifetime] seconds in [world]`

*NOTE:* PEX itself doesn't have any form of automation to give users permissions or commands.  You'll need to find another plugin that handles those sorts of functions.

**Comment by Stormbow** [comment]
It appears that timed permissions were good enough for what he wanted.
