### ISSUE TITLE
PermissionsEX Group Prefixes Not Working

### ISSUE THREAD

**Issue by CurseGraphics** [PEXPlugins/PermissionsEx#2431]
i was previously using Essentials Chat and PEX at the same time which worked fine apart from that we wasn't able to use /nick to change our names in the chat but would change them in the tab list, i then switched to ChatManager and PEX which allows /nick in the chat and tab list but seems to be stopping PEX from adding the group prefix before our names, Is there a way to fix this issue?

PermissionsEX > config.yml : http://pastebin.com/ahhRwb1Y
PermissionsEX > permissions.yml : http://pastebin.com/Rztvjxzd
ChatManager > config.yml : http://pastebin.com/Bbgqceya

we have more groups but they are all layed out the exact same just different perms so im sure if one works the rest would too.

Any help is greatly appreciated <3

**Comment by Stormbow** [comment]
ChatManager is not supported by PEX.  You will need a different chat management plugin such as EssentialsChat or EssentialsXChat (both of which also require Vault).

As for the /nick command not working, use [Debug Mode](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2) and I'm pretty sure you'll see why it's not working.  If you don't understand the output you get from [Debug Mode](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2), copy the output to [Pastebin](http://pastebin.com) and post the link in this thread and I'll take a look.

**Comment by CurseGraphics** [comment]
once i switched back to EssentialsChat it worked , i dont know how but it did lol sorry for time wasting but thanks for your help :)

**Comment by Stormbow** [comment]
You're welcome. :)
