### ISSUE TITLE
Unable to Use In-Game Commands

### ISSUE THREAD

**Issue by heckabecca** [PEXPlugins/PermissionsEx#2432]
I have no idea why I'm unable to use in-game permission commands as an op. I've tried finding a fix but haven't had any luck. Is there something I'm missing here?

Ops should be able to do in-game PEX commands...

**Comment by Stormbow** [comment]
Copy your permissions.yml file to [Pastebin](http://pastebin.com), post the link in this thread, and I'll take a look.

Also, I need to know what version of Minecraft and PEX are you running.

**Comment by Stormbow** [comment]
PS - Never use OP.  OP is for servers which have no plugins at all and can make a server which does have plugins think things are programmed correctly when they really aren't.

**Comment by zml2008** [comment]
Yeah, by default PEX ignores op status for its own commands, so if you haven't configured permissions at all it is expected that you won't be able to do anything ingame. PEX's initial configuration has to be done through the console.

**Comment by heckabecca** [comment]
http://pastebin.com/321CGHs9

No worries, no one is opped but me.

When I was hosting the server on my own computer, I had no issues using PEX commands as OP in-game. But when I switched and started hosting my server elsewhere, all the sudden when Opped in-game, I'm unable to perform PEX commands except through the console. I know I can add certain permissions to just myself and solve this but....I need it so OPs can perform in-game commands.

**Comment by Stormbow** [comment]
PS - Never use OP. OP is for servers which have no plugins at all and can make a server which does have plugins think things are programmed correctly when they really aren't.

**Comment by Stormbow** [comment]
You didn't tell me your Minecraft and PEX version info.

**Comment by Stormbow** [comment]
Changed my mind and deleted my posts.  I'm staying out of this one.

**Comment by Stormbow** [comment]
Looks like Heckabecca doesn't need any more help here.  No comments in the past 10 days.
