### ISSUE TITLE
unable to use any pex commands

### ISSUE THREAD

**Issue by popcorn9499** [PEXPlugins/PermissionsEx#2434]
Im running the pex 2.0 snapshot on my spigot 1.9.2 server and i noticed that i cant run any of the commands that i should use to set permissions.
I try to use any commands and i get this http://imgur.com/snG7P53

Im unsure whats wrong i just started using pex and havent changed anything from the defualt configurations.

**Comment by zml2008** [comment]
PEX2 uses an entirely different command structure. If you want to use it, learn the new commands at https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md. Otherwise, downgrade to 1.23.4

**Comment by popcorn9499** [comment]
ok i didnt get all of that i didnt know that link so i look at it it seems to be working fine. thanks
