### ISSUE TITLE
Pex Issue / ranking up via buycraft

### ISSUE THREAD

**Issue by Cobwebster** [PEXPlugins/PermissionsEx#2435]
Hey Storm,

I have a setup with buycraft and pex. When people donate it successfully says they got put into a group but they dont?

This is the command we use, i use it on my other server and it works fine.. 

pex user {user} group set stone

idk if its because i have 3 worlds? when i use the same command in-game it works fine.

**Comment by Stormbow** [comment]
You've received the following reply from cobwebster:

        Subject:
            Pex support

        Message:
        -------------------------------------------------------------------
        lol nvm, {name}
        -------------------------------------------------------------------
