### ISSUE TITLE
Timed Permissions disappear if the user disconnects

### ISSUE THREAD

**Issue by Kirstiana** [PEXPlugins/PermissionsEx#2437]
Hi there!

I wanted to grant my players a timed permission, but I found if they get disconnected from the server for any reason, like internet issues, and they come back on the server, they no longer have their permission. This is an issue if my players pay in-game currency to use a permission for a hour and they have to disconnect for any reason, their money would have gone to waste :(

Thank you for the great plugin! I've used it for a long long time :D

**Comment by zml2008** [comment]
This is how timed permissions are designed -- they are in-memory only and just last the session. If you want timed permissions that are saved, those have to be given using timed groups which are persistent.

**Comment by Kirstiana** [comment]
Ohhhh I see. Thank you so much for the quick response!! :D
