### ISSUE TITLE
Group Manager

### ISSUE THREAD

**Issue by Anciency** [PEXPlugins/PermissionsEx#2438]
Hello,

I'm making a server, but new players cant use warp and other plugins...
So i want to add a group manager where i can change the permissions in it. 

But i cant find working groups for 1.9.4?
Can you guys help me with one?

Thx!

**Comment by Stormbow** [comment]
GroupManager is not supported on this website.  (GroupManager and PermissionsEx are both permissions management plugins and conflict with each other.  You should only be using one or the other.)

If you want to dump GroupManager and use PermissionsEx, you can take a look at the [official PEX forums](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/) and you'll find a multitude of guides and posts to help you get started.  I also check these forums several times throughout the day to see if anyone needs help with their permissions.yml files and errors they encounter.

**Comment by janrchr** [comment]
depending on which plugin you have whit warp .. you should just add it to the group and have it inherit further up the ranks

**Comment by Stormbow** [comment]
@janrchr : Wrong. See previous post.

**Comment by janrchr** [comment]
no im not wrong just misunderstanding me.. or i misunderstand something here.

Because you add it to the group like

groups:
   Member:
      permissions:
         - essentials.warps

and if im not mistaken that a group whit member premission to warp from essentials, into permissionsEX. (Proably not set up right)

But i you right using groupmanager plugin whit premissionEX plugin is stupid.

**Comment by Stormbow** [comment]
Deleted irrelevant post.  None of what @janrchr is saying will work as GroupManager and PEX can not be used at the same time, and GroupManager is not supported by PEX.

**Comment by Anciency** [comment]
Okey, but is there no easy fix for give players warp or myhome permissions?

**Comment by janrchr** [comment]
amacing .. then i can do something in permissionex other cant using group inside it.. wow im good! :D

**Comment by janrchr** [comment]
@Anciency you need to know the permission in which the command is from and add that permission to the group.

using
/pex group <group> add <permission>

**Comment by Anciency** [comment]
Yes i know, but when i was testing PEX, the prefix and shit wsnt working? Can you help me trought skype or something?

Skype : Frieza.glenn

**Comment by Stormbow** [comment]
Since you're not listening to my instructions and instead choosing to listen to someone that is not handling the issue correctly, I am locking this thread.
