### ISSUE TITLE
User permissions data being saved within the group permissions file

### ISSUE THREAD

**Issue by DeusNinja** [PEXPlugins/PermissionsEx#2441]
Is there a way to have the user data save separately from the group permissions data?
Currently have over 80k user data in my permissions.yml . 

/pex users cleanup <group> [threshold] 
has been crashing my server.

Here's my watchdog dump http://pastebin.com/cbP1QJh8

The server becomes unresponsive when I run the command, I'm not really sure what my options are at this point to remove the extra users as the purge option seems not to work for me. I'll create a new server from scratch and generate some users to test purge on it.

**Comment by zml2008** [comment]
There's a multi-backend in 1.x that might match your usecase, but that backend is currently undocumented and unsupported so you'd be on your own.

You could also try bumping up the watchdog timeout so that it doesn't kill the server, since cleanup just takes a really long time.

**Comment by DeusNinja** [comment]
Thank you for the reply, sorry it took me some time to get back to this, is there anywhere I can find info on how to split the file with multi-backend? I'm not really sure where to begin with any of this, ended up purging my permissions file after it reached 300 thousand lines. Thankfully my ranks are based off of ontime which users were able to use to automatically reclaim their ranks.
