### ISSUE TITLE
Error with VPS 

### ISSUE THREAD

**Issue by javiersureda** [PEXPlugins/PermissionsEx#2442]
Hello,
I have an VPS with Ubuntu 15.10 XFCE (64 bits) with servers, and I get this error:
http://pastebin.com/xHKfEDq9

**Comment by zml2008** [comment]
Your jvm setup is probably incorrect -- something with the certificate store maybe? This is beyond our ability to help you however -- it's tied quite closely into your OS setup, not PEX.
