### ISSUE TITLE
[Sponge] Usage of HTML-like Colors too long

### ISSUE THREAD

**Issue by AnZaNaMa** [PEXPlugins/PermissionsEx#2443]
In your tutorial on making classes, it shows you using colors like:
`<color name='grey'>Words Here</color>`
Honestly this usage of coloring seems over complicated, because if I wanted to make a prefix like:
[Member] and i wanted the brackets to be grey and the text to be yellow, i would have to use:
`/pex group member option prefix "<color name='grey'>[</color>><color name='yellow'>Member</color><color name='grey'>]</color>`
This is way too long to fit into a single chat message if you're using commands to configure the plugin (which is strongly suggested) and it is way too tedious to use all the time. Is there an alternative to this that I don't know about or is it just this complicated to format prefixes?

**Comment by AnZaNaMa** [comment]
okay looks like I can just use regular color codes. I don't know why the tutorial shows colors like that. Those don't even work...

**Comment by AnZaNaMa** [comment]
I'm thinking maybe that was an attempt at making the github page show the color.

**Comment by zml2008** [comment]
What color scheme used depends on the chat plugin. The tutorial uses long-form xml formatting, which some chat plugins use (This format can be shortened -- I believe it's specified in the Sponge documentation somewhere) -- for example `<c n='grey'>Text</c>`. Others use legacy formatting codes.
