### ISSUE TITLE
Timed Permissions don't stay to a user after disconnect

### ISSUE THREAD

**Issue by starwarsfreak219** [PEXPlugins/PermissionsEx#2445]
I have seen that there were posts about this and seen that it is done through groups, but there is a problem when I do it through groups. I am currently developing a Prison server and run into the issue where the timed group(for donators) will overlap the default group(For A-Free) and thus changing their prefix. I would switch to timed permissions but there is a problem when using the timed permissions, it won't stick to the user after disconnect. I don't think it makes sense that you have this set up for the timed groups to stay after disconnect, but not for the timed permissions, which makes it a lot harder to figure out a way that will make it so it doesn't do that. Do you think you guys could add a way for timed permissions to stay to a user for the time period in which is stated in the command? Would make things a lot easier. Thanks!

**Comment by Stormbow** [comment]
If a user is a member of more than one group, you need to specify a weight value for all of the groups involved so the user will retain the prefix that you want them to have.  Also, keep in mind that most chat management plugins that put the prefixes into chat will not allow more than one group's prefix/suffix to be displayed.  PEX has no control over this.

As for timed permissions, @zml2008 has already commented on this in ticket #2437 6 days ago.

**Comment by starwarsfreak219** [comment]
I am aware that you can't put multiple prefix's in chat formatting plugins... I guess I will have to learn the weight system... :P

**Comment by zml2008** [comment]
I believe the plugin Simple-Prefix can support multiple prefixes -- though this may not be what you want.

**Comment by starwarsfreak219** [comment]
I don't need any plugin for multiple prefixes... :P, right now I am trying to figure out the weight system, it seems to not be taking in the permissions with my staff ranks to the players in that group. I have my weight for group owner set as 200 and my group A set as 100, it doesn't seem to be inheriting the permissions for group owner...

**Comment by starwarsfreak219** [comment]
Hmmm, Weights seem a bit broken, it seems that it rather inherit some of the permissions(like permissions.*) but leave out the rest(bukkit.command.plugins) and the negated groups(for AnimatedNames, DeluxeChat, & DeluxeJoin)... it sets it up for H instead of having it for Owner, shouldn't some of the Owner commands override the default commands? My groups seem to have broke... Just tested a few things and it seems that the permissions are overridden by the default group...
