### ISSUE TITLE
Group Weights override certain groups permissions

### ISSUE THREAD

**Issue by starwarsfreak219** [PEXPlugins/PermissionsEx#2447]
I have ran into the issue where group weights would override group permissions, I am currently developing a Prison server and have A rank set as 100 and Owner rank set as 200, but the Owner groups permissions are overridden by the A groups permissions making it so that the group Owner is practically invisible. I want the Owner group to be able to play along with the rankups, but it doesn't work since not all permissions are inherited from the Owner group. Say A group has a permission from AnimatedNames(animatednames.group.default, -animatednames,group.Owner), and Owner group has permissions from AnimatedNames(-animatednames.group.default, animatednames.group.Owner), the A group overrides the owner group so then it shows up as A instead of what the owner looks like. I do have them in both groups, but A Overrides the Owners permissions.

**Comment by Stormbow** [comment]
"Weight" values don't have anything to do with permissions, it's all about prefix/suffix.

Show me your permissions.yml file.

**Comment by starwarsfreak219** [comment]
Hmm, that's odd, I found a different solution, but if weight values aren't supposed to do anything with permissions, I think that this is a bug... since they did override permissions, I had some negated permissions in the A group, but had the Owner group have the permissions but aren't negated, for instance, if A group has -bukkit.command.plugins and Owner group has bukkit.command.plugins, it will instead take the -bukkit.command.plugins... I did test it with taking out the ranking system(I was going to use this to promote staff), but still did the same thing...

**Comment by starwarsfreak219** [comment]
I will see if I can make a config that did the same issue tomorrow...
I a busy atm... sorry.

**Comment by Stormbow** [comment]
Ahhhhh!  Vanilla permissions.  These can not be reliably controlled on a Minecraft server that uses plugins.  Read more [right here](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/86945-problems-with-vanilla-permissions/).

**Comment by starwarsfreak219** [comment]
I dont think animatednames are vanilla permission. :P I will have the permissions file later today.

**Comment by Stormbow** [comment]
All of the others that you mentioned are, however. :P

**Comment by Stormbow** [comment]
Is it "later today" yet?

**Comment by starwarsfreak219** [comment]
Oops, forgot to make one, let me make one right now.

**Comment by Stormbow** [comment]
Is it "right now" yet?
