### ISSUE TITLE
My plugin get group -> pex get uuid -> big delay 4-6k ms

### ISSUE THREAD

**Issue by DardBrinza** [PEXPlugins/PermissionsEx#2448]
Hi, i have a problem. PEX has a big delay. Check my MassiveLag log:

http://dl2.joxi.net/drive/2016/06/26/0002/2579/178707/07/fa5469bac9.png
http://dl2.joxi.net/drive/2016/06/26/0002/2579/178707/07/003d37db13.png
http://dl2.joxi.net/drive/2016/06/26/0002/2579/178707/07/8ea5f5ab9b.png

Delays also sometimes occur when entering '/pex user player' and other PEX commands.
I have about ~6000 users with different groups. (in permissions.yml, no mysql)

Latest pex, latest 1.8.8 spigot.

**Comment by zml2008** [comment]
Yeah, this is pretty much a limitation of Craftbukkit. You'll also want to make sure that DardDonate looks up players in PEX by UUID rather than username since that can take a network request to resolve.
