### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by natkemon** [PEXPlugins/PermissionsEx#2451]
Hello.

With my donor ranks, they dont seem to be inherting and or receiving any of the permissions designated. I've tested it with the /kit permission nodes and in game it says it is invalid. Have i followed the format correctly?

http://pastebin.com/JWDwtkKm

**Comment by Stormbow** [comment]
Pretty close.  If you're using Minecraft 1.9 or higher, you need to do as you see [on Line 19 right here](http://pastebin.com/8ZSHxauG) to give all of your groups an inheritance if they're not inheriting from a group.  (In your case, this needs to be done for the "islander" and "owner" groups.)

**Comment by Stormbow** [comment]
I'm guessing this is resolved then?
