### ISSUE TITLE
[PEX 2.0] [Sponge] Deleting group

### ISSUE THREAD

**Issue by Boss-Demon** [PEXPlugins/PermissionsEx#2452]
How to delete groups? When I type "/pex group members del" nothing happens,the chat says nothing.
The latest version PEX 2.0.
The latest version of Sponge.
In addition to PEX nothing installed.
Minecraft version 1.8.9

**Comment by Tyloonie** [comment]
Dude? Isn't it /pex group members remove 

:)

**Comment by KokuaOp** [comment]
Dudes  https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Command-Equivalency.md

**Comment by AdrianT01** [comment]
Getting the same issue here as well. /pex group members remove or /pex group members del doesn't work. In fact, I can't delete any group I don't want.

**Comment by KillzyazMadness** [comment]
I'm having the same issue that I cannot remove any groups that I don't want. Did anyone workout a solution for this?

**Comment by KokuaOp** [comment]
No one worked it out for me but what I did was just took PEX off and put it
on again and it wiped them out.  I have put on the PEX forums a step by
step instructions of how I did it all and it has worked fine.  I had to
read and readfind out what I have.  If you don't mind the tedious step by
step example I give I think it will help you.  At one point I did find out
from the PEX guy (can't think of his name right now) that it doesn't matter
if you have a group you don't want.  It was so vague though I had to just
take PEX off and put it on again.  Sorry I just saw this now.  I know how
frustrating it is not to get support and as far as I'm concerned he has to
do better with support than he is doing.  Let me know if you find my help
on the forum if not I'll look it up for you and send it to you.  Mind you
it is just basic without permissions but I can get you that too.

**Comment by ryantheleach** [comment]
I can reproduce this on 2.0-SNAPSHOT-b141.

I followed the pex tutorial.

Did ``/pex group VIP delete`` and the group was deleted, the file was saved.

``/pex group VIP info`` shows VIP info still

``/pex reload``

``/pex group VIP info`` shows that the group no longer exists.

**Comment by Stormbow** [comment]
@ryantheleach That is working as intended.

**Comment by ryantheleach** [comment]
This is incredibly surprising behaviour. I would have thought that the changes would have taken effect immediately?

**Comment by Stormbow** [comment]
That's how PEX has worked since at least 1.4.2 when I first used it.

**Comment by ryantheleach** [comment]
But the changes wern't made to the file, they were done via commands.

Surprising behaviour may as well equal bugs when dealing with the amount of invalid tickets that you do.
