### ISSUE TITLE
[1.9.4] Equivalent to OP?

### ISSUE THREAD

**Issue by AnZaNaMa** [PEXPlugins/PermissionsEx#2455]
So I see that PermissionsEx overrides the entire OP system in 1.9.4 (which is an idea I can get behind). However, I'm using this mod in tandem with the Better Questing mod. To be able to edit quests, it requires a player to be an operator, so I'm wondering if there's a way to give a player OP still since pex blocks it and it doesn't have a way to tell the mod the player has all permissions.

**Comment by zml2008** [comment]
You can go use the MC op commands using the `/minecraft:` prefix, which will add players to the server's ops list. However, it might make sense for the Better Questing mod to integrate with Sponge's permissions API (relatively simple -- if sponge is installed and you have a MC `EntityPlayerMP` object, you can just cast it -- so `((Player) mcPly).hasPermission("my.permission");` will tell the plugin whether or not a player has a certain permission.
