### ISSUE TITLE
[PEX Sponge] crash when loading world with build 132

### ISSUE THREAD

**Issue by NecroMandy** [PEXPlugins/PermissionsEx#2456]
Hi there, 

When using the latest build of PermissionsEx for Sponge (build 132) it runs into an error. The log is below, it points out errors with the other mods/plugins, however I am 100% certain its just to do with the 132 build as it all works fine with build 131. 
[Log for PEX 132.txt](https://github.com/PEXPlugins/PermissionsEx/files/344850/Log.for.PEX.132.txt)

**Comment by zml2008** [comment]
Builds 132+ are only for Sponge 1.9 and above (using API 5 snapshots).
