### ISSUE TITLE
[PEX Sponge build 131] Default rank being wiped on restart 

### ISSUE THREAD

**Issue by NecroMandy** [PEXPlugins/PermissionsEx#2457]
Hi there, 

I am running into a rather annoying issue with PEX Build 131 where upon restarting the server the default rank is being reset. The other ranks are still all set up and nothing changes with them. 

Here is a log but I am not sure if it will point to anything :/
[Log for PEX 131.txt](https://github.com/PEXPlugins/PermissionsEx/files/344860/Log.for.PEX.131.txt)

**Comment by Stormbow** [comment]
Already responded to in your double post #2456 .

**Comment by NecroMandy** [comment]
Well this is for build 131, which (as far as i can tell from the change logs) is prior to the update to API 5.0 and is for the correct versions that I am using on my server. So I am a little confused as to why your closing this issue unless your just no longer planning on supporting 1.8.9 versions at all???

My previous post was in regards to 132, which I had tried using hoping it may contain a fix. I hadn't realized at the time that it had upgraded to API 5.0. 

In the meantime I am having to enter an extremely long list of commands manually to re-enter all the permissions every time I restart my server for updates.

**Comment by zml2008** [comment]
Yeah, different issue

**Comment by zml2008** [comment]
Try using https://minions.aoeu.xyz/zml/pex-api4.jar -- It's a build of PEX with the latest changes but for API 4.x

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
