### ISSUE TITLE
About pex sql Groups and permission

### ISSUE THREAD

**Issue by coolinoss** [PEXPlugins/PermissionsEx#2458]
i have two different servers with same Groups but each server has his group permission
when i set the backend to mysql in the config in both server
the Rank are working but 
i dont have per server permission li lost server 1 permission in server2

**Comment by coolinoss** [comment]
bump

**Comment by Stormbow** [comment]
Don't bump tickets.  (Your bump has been deleted.)

Your ticket was already the most recent and the top of the list on the tickets page.

**Comment by zml2008** [comment]
Sharing only some tables but not all across servers is not supported and if you run into issues you're on your own. In 2.0 you can use server tags to set permissions per-server if you want this feature.
