### ISSUE TITLE
Pex 2.0 Suggestion!

### ISSUE THREAD

**Issue by ChimpGamer** [PEXPlugins/PermissionsEx#2459]
When you connect PEX with MySQL you can set the Server. so what i mean is if you got multiple server you can set that permission for that group on that server. Like Bugeeperms https://www.spigotmc.org/resources/bungeeperms.25/ (Inactive)
That would be very helpful

**Comment by zml2008** [comment]
In PEX 2 it is possible to set per-server permissions with the server-tags context. The documentation is currently WIP -- currently [here](https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Subject.md#contexts), so let me know if that's too confusing and I'll try to expand on it more.
