### ISSUE TITLE
http://www.muno.pw

### ISSUE THREAD

**Issue by cjhm5200** [PEXPlugins/PermissionsEx#2460]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/a156d5ced853bffe9144)

**Comment by zml2008** [comment]
You're using an ancient version of MC with a very temporary build of PEX you shouldn't be using anymore, that was *specifically* created for the 1.8 update. You really thought that would work?

Get the latest 1.22.x build from BukkitDev, or update your MC and get the latest 1.23.x build.
