### ISSUE TITLE
Feature: save-default-group in config.yml

### ISSUE THREAD

**Issue by Tyloonie** [PEXPlugins/PermissionsEx#2467]
As explained in my other issue (https://github.com/PEXPlugins/PermissionsEx/issues/2464)...

It would be awesome if you could add a feature to the config.yml that allows PEX to save all user groups - even if the person is in the group chosen as default. This exampled is a very handy feature on Prison servers.

**Comment by zml2008** [comment]
Ok, I've pushed a commit that adds this option. Test it using the build at https://minions.aoeu.xyz/zml/pex-1.23.5-dev-savedefgroup.jar and let me know how it works.

**Comment by Tyloonie** [comment]
Hey! I tested it out, and so far it seems like the option hasn't really changed anything.

`multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: true
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
  save-default-group: true
updater: true
alwaysUpdate: false
`
`users:
  0ce4e7f1-87bd-42d8-82cf-d0a05fd0fbb5:
    permissions:
    - permissions.*
    group: []
    options:
      name: Tyloonie`

Hmmmm....

**Comment by Tyloonie** [comment]
I tried just logging in and out, restarting the server a few times... Stil only the [].

**Comment by Tyloonie** [comment]
Hi zml, as far as I can see, nothing is really happening.

**Comment by Tyloonie** [comment]
So far it seems to work quite well. Still testing though... Will let you know if anything is wrong.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
