### ISSUE TITLE
Sponge plugin not working error.

### ISSUE THREAD

**Issue by fluffyfisheh** [PEXPlugins/PermissionsEx#2468]
FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded Im using spongeforge and I have been trying to get a working PEX hope to hear from you soon.

**Comment by zml2008** [comment]
You still haven't pasted the full error including stacktrace like I asked you to in IRC.

**Comment by fluffyfisheh** [comment]
not sure what you mean by that sorry D:

**Comment by fluffyfisheh** [comment]
thats all the error says XD

**Comment by zml2008** [comment]
before that line there's a big indented thing. that's part of the error. The message you pasted is forge detecting that an error occurred in the past and stopping.

**Comment by fluffyfisheh** [comment]
15.07 14:37:47 [Server] Server thread/INFO [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded. 15.07 14:37:47 [Server] Server thread/INFO [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by fluffyfisheh** [comment]
im on mc prohosting there isent realy an indented thing XD

**Comment by fluffyfisheh** [comment]
basicly it crashes right as the server spawn point is being loaded

**Comment by fluffyfisheh** [comment]
15.07 14:59:21 [Server] INFO Caused by: java.lang.AbstractMethodError: ninja.leaping.permissionsex.sponge.PermissionsExPlugin.getDefaultData()Lorg/spongepowered/api/service/permission/SubjectData;

**Comment by fluffyfisheh** [comment]
15.07 15:05:31 [Server] Server thread/INFO [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded. 15.07 15:05:31 [Server] Server thread/INFO [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded. 15.07 15:05:31 [Server] Server thread/INFO [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Closed. 15.07 15:05:31 [Server] Server thread/INFO [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Close initiated...
that might be better

**Comment by fluffyfisheh** [comment]
i also have pixlemon on the server

**Comment by fluffyfisheh** [comment]
and the essential cmds

**Comment by zml2008** [comment]
Ok, that's the beginning part of the error, which is enough in this case. Builds after 131 are for 1.9 and above only.
