### ISSUE TITLE
Group "A" already exists just because a group that starts with an A exists

### ISSUE THREAD

**Issue by MADS0LADEN** [PEXPlugins/PermissionsEx#2469]
It says that the group "A" already exists, but thats wrong.
I think its because that it has conflicts with the group "Administrator".
![image](https://cloud.githubusercontent.com/assets/4103363/16889582/cad19554-4ae7-11e6-8c4d-8561b4c0cd0e.png)
also, no errors in console.

**Comment by Stormbow** [comment]
Have you tried using apostrophes around the group name when you enter the command?

**Comment by MADS0LADEN** [comment]
Yes, i did it in the example

**Comment by Stormbow** [comment]
What "example"?

**Comment by MADS0LADEN** [comment]
the photo at in the main comment

**Comment by Stormbow** [comment]
That shows an error, not //exactly// what the command was that you typed.

**Comment by MADS0LADEN** [comment]
i did not include the command i typed, no.
but im now sayng that i used " around the command.

**Comment by Stormbow** [comment]
That is a quotation mark.  Try apostrophes. 'word'

**Comment by Stormbow** [comment]
It's been a day since the last post.  Problem solved?

**Comment by MADS0LADEN** [comment]
Nope, 'A' just creates a group named 'A' with the apostrophes.
