### ISSUE TITLE
Can a specific world have a different default rank?

### ISSUE THREAD

**Issue by mylesk23** [PEXPlugins/PermissionsEx#2470]
I want to know if there is a way to still keep a normal global default rank but at the same time have a world have a different default rank? I've tried to do so but am not sure if this would be the correct code:
`  F:
    prefix: '&f[&cF&f]'
    permissions:
    - essentials.warps.f
    worlds:
      Prison:
        default: true`

**Comment by Stormbow** [comment]
World-specific groups may be a function of PEX 2.0 (don't quote me on that; I have no experience with that version), but they're definitely not part of PEX 1.x versions.

Users are members of groups, not members of worlds.  Keep in mind that with global and [multiworld permissions](http://pastebin.com/ieyQU7w8), you can completely control who can do what on which world.

**Comment by mylesk23** [comment]
Thanks!

**Comment by zml2008** [comment]
I think it might actually be possibly to set a group as default in only one world. While a group itself is global, the data within it can be restricted by world. You'd want to just set the default option to true in the appropriate world.

**Comment by Stormbow** [comment]
I thought
{{{
  options:
    default: true
}}}

was not allowed in multiworld settings.

**Comment by Stormbow** [comment]
Isn't the setting 
```
options:
  default: true
```
only for groups?

That can't be put under the `worlds:` section of a group, can it?

**Comment by Stormbow** [comment]
Isn't the setting 
```
options:
  default: true
```
only for groups?

That can't be put under the `worlds:` section of a group, can it @zml2008 (for PEX 1.x or 2.x)?

```
    worlds:
      FirstWorld:
        options:
          default: true
        permissions:
        - modifyworld.*
      SecondWorld:
        permissions:
        - modifyworld.*
```

I thought what he was asking for was "everyone on the server is in the group 'xxxxxxxx', but on the world 'Prison', everyone is in the group 'yyyyyyy'."
