### ISSUE TITLE
PEX Prefixes Not Working

### ISSUE THREAD

**Issue by konapuppy** [PEXPlugins/PermissionsEx#2472]
Ok, so I'll do /pex group owner prefix &9&l[&b&lOwner&9&l] and it will say that the prefix for owner was set to that. But then, when I type in chat, there's no prefix. Please help, I want to go public, but without prefixes, I can't.

Also, I'm set as owner.

![2016-07-16_12 37 19](https://cloud.githubusercontent.com/assets/20464171/16896787/a8495d26-4b52-11e6-8778-99587a3646ad.png)
![2016-07-16_12 37 53](https://cloud.githubusercontent.com/assets/20464171/16896788/ab30aea4-4b52-11e6-9a2b-f4a561d2db6a.png)
![2016-07-16_12 38 04](https://cloud.githubusercontent.com/assets/20464171/16896790/b03a914e-4b52-11e6-8bc9-7dc2a31ecf50.png)
![2016-07-16_12 38 45](https://cloud.githubusercontent.com/assets/20464171/16896791/b48500ae-4b52-11e6-9194-dc1a14d8b10b.png)

My IGN is KonaTheBaconator.

**Comment by Stormbow** [comment]
Ensure that you do have a chat management plugin installed.

Most people use Spigot as their server wrapper, and the most common chat management plugin for Spigot is from [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/), called [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/).  EssentialsXChat also requires [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) to be installed.

**Comment by konapuppy** [comment]
Thanks! But... I use CraftBukkit, is there any problems?

**Comment by Stormbow** [comment]
That'll depend on which chat management plugin you're using.  The plugins based on "ChatManager" (ChatManager, ChatManager+, ChatEx, and others) won't work with PEX.  You'll need to test the chat plugins and read the documentation about them to see if it's based on ChatManager.

**Comment by konapuppy** [comment]
GEEZ! That sure was quick! I don't know if this will help, but these are my Pugins (14): CoreProtect, WorldEdit, Citizens, Playtime, Essentials, ColoredTab, ColoredChat, PermissionsEx, PlotSquared, notnt, Marriage, Multiverse-Core, EnjinMinecraftPlugin, HolographicDisplays

Thanks for the info BTW! I'm going to go try it out!

**Comment by Stormbow** [comment]
What version is your server?

**Comment by konapuppy** [comment]
1.8.8 CraftBukkit

**Comment by konapuppy** [comment]
Do you think I should install EssentialsChat?

**Comment by Stormbow** [comment]
Ah, ok.  So you're just barely outside the window to use "EssentialsChat".  You could always try it, but reports have indicated it didn't work past "1.8".

**Comment by Stormbow** [comment]
http://dev.bukkit.org/bukkit-plugins/essentials/ <--- Only use official download sources, of course.

**Comment by Stormbow** [comment]
EssentialsChat comes in that .zip file.  Be sure to also install [Vault](http://dev.bukkit.org/bukkit-plugins/vault/).

**Comment by konapuppy** [comment]
Makes sense! I've tried with EssentialsChat before but it never worked!

**Comment by konapuppy** [comment]
Also, if I we're to become 1.10, does that mean I need all new plugins?

**Comment by Stormbow** [comment]
Yep.  Most of the time, even changing from 1.2.3 to 1.2.4 (which is called a minor update) can lead to plugins not working correctly, so all plugins should be tested if you update the server.

**Comment by Stormbow** [comment]
(1.2.3 to 1.3.0 is called a major update.)

**Comment by Stormbow** [comment]
Once you get EssentialsChat installed, read the Prefix/Suffix Guide that I wrote [over in the PEX forums](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/?unread).

**Comment by konapuppy** [comment]
Thank you so much! If I can't get it to work, should I PM you? Because I think you're going to lock the thread. ;-;

**Comment by konapuppy** [comment]
If I already have essentials downloaded, should I just install vault? Or is EssentialsChat a whole diffrent thing?

**Comment by konapuppy** [comment]
![2016-07-17_08 39 34](https://cloud.githubusercontent.com/assets/20464171/16901482/1e630280-4bfa-11e6-9152-0c3cff110299.png)

**Comment by Stormbow** [comment]
I won't lock a thread unless someone's rude to me or the PEX programmer.

Definitely install Vault, then see how the plugins list looks.

**Comment by konapuppy** [comment]
In the screenshot I just posted, there's a list of my plugins after /reload do I need to restart the server from console?

**Comment by Stormbow** [comment]
Keep in mind, of course, that "Essentials" for Craftbukkit was discontinued at version 1.8 of Minecraft.

**Comment by Stormbow** [comment]
The `/reload` command can crash your server, so it's better to just shut the server down and restart it.  (Reload crashes the server after about 3-4 uses.)

**Comment by Stormbow** [comment]
Typically when a plugin's name comes up red, there's an error in their config.yml files.

**Comment by konapuppy** [comment]
;-; I'm not a dev, and this is my first ever server.

**Comment by Stormbow** [comment]
We all started in the same place you are now.  ;-)

**Comment by konapuppy** [comment]
Um, I don't remember tutorials with a config like this:

############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI.
# If you receive an error when Essentials loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe)
#   - Text with symbols is enclosed in single or double quotation marks

# If you have problems join the Essentials help support channel: http://tiny.cc/EssentialsChat

############################################################
# +------------------------------------------------------+ #
# |                 Essentials (Global)                  | #
# +------------------------------------------------------+ #
############################################################

# A color code between 0-9 or a-f. Set to 'none' to disable.
ops-name-color: '4'

# The character(s) to prefix all nicknames, so that you know they are not true usernames.
nickname-prefix: '~'

# The maximum length allowed in nicknames. The nickname prefix is included in this.
max-nick-length: 15

# Disable this if you have any other plugin, that modifies the displayname of a user.
change-displayname: true

# When this option is enabled, the (tab) player list will be updated with the displayname.
# The value of change-displayname (above) has to be true.
#change-playerlist: true

# When EssentialsChat.jar isn't used, force essentials to add the prefix and suffix from permission plugins to displayname.
# This setting is ignored if EssentialsChat.jar is used, and defaults to 'true'.
# The value of change-displayname (above) has to be true.
# Do not edit this setting unless you know what you are doing!
#add-prefix-suffix: false

# If the teleport destination is unsafe, should players be teleported to the nearest safe location?
# If this is set to true, Essentials will attempt to teleport players close to the intended destination.
# If this is set to false, attempted teleports to unsafe locations will be cancelled with a warning.
teleport-safety: true

# This forcefully disables teleport safety checks without a warning if attempting to teleport to unsafe locations.
# teleport-safety and this option need to be set to true to force teleportation to dangerous locations.
force-disable-teleport-safety: false

# The delay, in seconds, required between /home, /tp, etc.
teleport-cooldown: 0

# The delay, in seconds, before a user actually teleports.  If the user moves or gets attacked in this timeframe, the teleport never occurs.
teleport-delay: 0

# The delay, in seconds, a player can't be attacked by other players after they have been teleported by a command.
# This will also prevent the player attacking other players.
teleport-invulnerability: 4

# The delay, in seconds, required between /heal or /feed attempts.
heal-cooldown: 60

# Near Radius
# The default radius with /near
# Used to use chat radius but we are going to make it separate.
near-radius: 200

# What to prevent from /item and /give.
# e.g item-spawn-blacklist: 10,11,46
item-spawn-blacklist:

# Set this to true if you want permission based item spawn rules.
# Note: The blacklist above will be ignored then.
# Example permissions (these go in your permissions manager):
#  - essentials.itemspawn.item-all
#  - essentials.itemspawn.item-[itemname]
#  - essentials.itemspawn.item-[itemid]
#  - essentials.give.item-all
#  - essentials.give.item-[itemname]
#  - essentials.give.item-[itemid]
#  - essentials.unlimited.item-all
#  - essentials.unlimited.item-[itemname]
#  - essentials.unlimited.item-[itemid]
#  - essentials.unlimited.item-bucket # Unlimited liquid placing
#
# For more information, visit http://wiki.ess3.net/wiki/Command_Reference/ICheat#Item.2FGive
permission-based-item-spawn: false

# Mob limit on the /spawnmob command per execution.
spawnmob-limit: 10

# Shall we notify users when using /lightning?
warn-on-smite: true

# Shall we drop items instead of adding to inventory if the target inventory is full?
drop-items-if-full: false

# Essentials Mail Notification
# Should we notify players if they have no new mail?
notify-no-new-mail: true

# The motd and rules are now configured in the files motd.txt and rules.txt.

# When a command conflicts with another plugin, by default, Essentials will try to force the OTHER plugin to take priority.
# Commands in this list, will tell Essentials to 'not give up' the command to other plugins.
# In this state, which plugin 'wins' appears to be almost random.
#
# If you have two plugin with the same command and you wish to force Essentials to take over, you need an alias.
# To force essentials to take 'god' alias 'god' to 'egod'.
# See http://wiki.bukkit.org/Commands.yml#aliases for more information.

overridden-commands:
#  - god
#  - info

# Disabling commands here will prevent Essentials handling the command, this will not affect command conflicts.
# You should not have to disable commands used in other plugins, they will automatically get priority.
# See http://wiki.bukkit.org/Commands.yml#aliases to map commands to other plugins.
disabled-commands:
#  - nick
#  - clear

# These commands will be shown to players with socialSpy enabled.
# You can add commands from other plugins you may want to track or
# remove commands that are used for something you dont want to spy on.
# Set - '*' in order to listen on all possible commands.
socialspy-commands:
  - msg
  - w
  - r
  - mail
  - m
  - t
  - whisper
  - emsg
  - tell
  - er
  - reply
  - ereply
  - email
  - action
  - describe
  - eme
  - eaction
  - edescribe
  - etell
  - ewhisper
  - pm

# Mute Commands
# These commands will be disabled when a player is muted.
# Use '*' to disable every command.
# Essentials already disabled Essentials messaging commands by default.
# It only cars about the root command, not args after that (it sees /f chat the same as /f)
mute-commands:
  - f
  - kittycannon
 # - '*'

# If you do not wish to use a permission system, you can define a list of 'player perms' below.
# This list has no effect if you are using a supported permissions system.
# If you are using an unsupported permissions system, simply delete this section.
# Whitelist the commands and permissions you wish to give players by default (everything else is op only).
# These are the permissions without the "essentials." part.
player-commands:
  - afk
  - afk.auto
  - back
  - back.ondeath
  - balance
  - balance.others
  - balancetop
  - build
  - chat.color
  - chat.format
  - chat.shout
  - chat.question
  - clearinventory
  - compass
  - depth
  - delhome
  - getpos
  - geoip.show
  - help
  - helpop
  - home
  - home.others
  - ignore
  - info
  - itemdb
  - kit
  - kits.tools
  - list
  - mail
  - mail.send
  - me
  - motd
  - msg
  - msg.color
  - nick
  - near
  - pay
  - ping
  - protect
  - r
  - rules
  - realname
  - seen
  - sell
  - sethome
  - setxmpp
  - signs.create.protection
  - signs.create.trade
  - signs.break.protection
  - signs.break.trade
  - signs.use.balance
  - signs.use.buy
  - signs.use.disposal
  - signs.use.enchant
  - signs.use.free
  - signs.use.gamemode
  - signs.use.heal
  - signs.use.info
  - signs.use.kit
  - signs.use.mail
  - signs.use.protection
  - signs.use.repair
  - signs.use.sell
  - signs.use.time
  - signs.use.trade
  - signs.use.warp
  - signs.use.weather
  - spawn
  - suicide
  - time
  - tpa
  - tpaccept
  - tpahere
  - tpdeny
  - warp
  - warp.list
  - world
  - worth
  - xmpp

# Note: All items MUST be followed by a quantity!
# All kit names should be lower case, and will be treated as lower in permissions/costs.
# Syntax: - itemID[:DataValue/Durability] Amount [Enchantment:Level].. [itemmeta:value]...
# For Item Meta information visit http://wiki.ess3.net/wiki/Item_Meta
# 'delay' refers to the cooldown between how often you can use each kit, measured in seconds.
# Set delay to -1 for a one time kit.
# For more information, visit http://wiki.ess3.net/wiki/Kits
kits:
  tools:
    delay: 10
    items:
      - 272 1
      - 273 1
      - 274 1
      - 275 1
  dtools:
    delay: 600
    items:
      - 278 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
      - 277 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
      - 298 1 color:255,255,255 name:Top_Hat lore:Good_day,_Good_day
      - 279:780 1
  notch:
    delay: 6000
    items:
      - 397:3 1 player:Notch
  color:
    delay: 6000
    items:
      - 387 1 title:&4Book_&9o_&6Colors author:KHobbits lore:Ingame_color_codes book:Colors
  firework:
    delay: 6000
    items:
      - 401 1 name:Angry_Creeper color:red fade:green type:creeper power:1
      - 401 1 name:StarryNight color:yellow,orange fade:blue type:star effect:trail,twinkle power:1
      - 401 2 name:SolarWind color:yellow,orange fade:red shape:large effect:twinkle color:yellow,orange fade:red shape:ball effect:trail color:red,purple fade:pink shape:star effect:trail power:1

# Essentials Sign Control
# See http://wiki.ess3.net/wiki/Sign_Tutorial for instructions on how to use these.
# To enable signs, remove # symbol. To disable all signs, comment/remove each sign.
# Essentials colored sign support will be enabled when any sign types are enabled.
# Color is not an actual sign, it's for enabling using color codes on signs, when the correct permissions are given.

enabledSigns:
  #- color
  #- balance
  #- buy
  #- sell
  #- trade
  #- free
  #- disposal
  #- warp
  #- kit
  #- mail
  #- enchant
  #- gamemode
  #- heal
  #- info
  #- spawnmob
  #- repair
  #- time
  #- weather

# How many times per second can Essentials signs be interacted with per player.
# Values should be between 1-20, 20 being virtually no lag protection.
# Lower numbers will reduce the possibility of lag, but may annoy players.
sign-use-per-second: 4

# Backup runs a batch/bash command while saving is disabled.
backup:
  # Interval in minutes.
  interval: 30
  # Unless you add a valid backup command or script here, this feature will be useless.
  # Use 'save-all' to simply force regular world saving without backup.
  #command: 'rdiff-backup World1 backups/World1'

# Set this true to enable permission per warp.
per-warp-permission: false

# Sort output of /list command by groups.
# You can hide and merge the groups displayed in /list by defining the desired behaviour here.
# Detailed instructions and examples can be found on the wiki: http://wiki.ess3.net/wiki/List
list:
    # To merge groups, list the groups you wish to merge
    #Staff: owner admin moderator
    Admins: owner admin
    # To limit groups, set a max user limit
    #builder: 20
    # To hide groups, set the group as hidden
    #default: hidden
    # Uncomment the line below to simply list all players with no grouping
    #Players: '*'

# More output to the console.
debug: false

# Set the locale for all messages.
# If you don't set this, the default locale of the server will be used.
# For example, to set language to English, set locale to en, to use the file "messages_en.properties".
# Don't forget to remove the # in front of the line.
# For more information, visit http://wiki.ess3.net/wiki/Locale
#locale: en

# Turn off god mode when people leave the server.
remove-god-on-disconnect: false

# Auto-AFK
# After this timeout in seconds, the user will be set as AFK.
# This feature requires the player to have essentials.afk.auto node.
# Set to -1 for no timeout.
auto-afk: 300

# Auto-AFK Kick
# After this timeout in seconds, the user will be kicked from the server.
# essentials.afk.kickexempt node overrides this feature.
# Set to -1 for no timeout.
auto-afk-kick: -1

# Set this to true, if you want to freeze the player, if the player is AFK.
# Other players or monsters can't push the player out of AFK mode then.
# This will also enable temporary god mode for the AFK player.
# The player has to use the command /afk to leave the AFK mode.
freeze-afk-players: false

# When the player is AFK, should he be able to pickup items?
# Enable this, when you don't want people idling in mob traps.
disable-item-pickup-while-afk: false

# This setting controls if a player is marked as active on interaction.
# When this setting is false, the player would need to manually un-AFK using the /afk command.
cancel-afk-on-interact: true

# Should we automatically remove afk status when a player moves?
# Player will be removed from AFK on chat/command regardless of this setting.
# Disable this to reduce server lag.
cancel-afk-on-move: true

# You can disable the death messages of Minecraft here.
death-messages: true

# Should players with permissions be able to join and part silently?
# You can control this with essentials.silentjoin and essentials.silentquit permissions if it is enabled.
# In addition, people with essentials.silentjoin.vanish will be vanished on join.
allow-silent-join-quit: false

# You can set a custom join message here, set to "none" to disable.
# You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
custom-join-message: "none"

# You can set a custom quit message here, set to "none" to disable.
# You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
custom-quit-message: "none"

# Add worlds to this list, if you want to automatically disable god mode there.
no-god-in-worlds:
#  - world_nether

# Set to true to enable per-world permissions for teleporting between worlds with essentials commands.
# This applies to /world, /back, /tp[a|o][here|all], but not warps.
# Give someone permission to teleport to a world with essentials.worlds.<worldname>
# This does not affect the /home command, there is a separate toggle below for this.
world-teleport-permissions: false

# The number of items given if the quantity parameter is left out in /item or /give.
# If this number is below 1, the maximum stack size size is given. If over-sized stacks.
# are not enabled, any number higher than the maximum stack size results in more than one stack.
default-stack-size: -1

# Over-sized stacks are stacks that ignore the normal max stack size.
# They can be obtained using /give and /item, if the player has essentials.oversizedstacks permission.
# How many items should be in an over-sized stack?
oversized-stacksize: 64

# Allow repair of enchanted weapons and armor.
# If you set this to false, you can still allow it for certain players using the permission.
# essentials.repair.enchanted
repair-enchanted: true

# Allow 'unsafe' enchantments in kits and item spawning.
# Warning: Mixing and overleveling some enchantments can cause issues with clients, servers and plugins.
unsafe-enchantments: false

#Do you want Essentials to keep track of previous location for /back in the teleport listener?
#If you set this to true any plugin that uses teleport will have the previous location registered.
register-back-in-listener: false

#Delay to wait before people can cause attack damage after logging in.
login-attack-delay: 5

#Set the max fly speed, values range from 0.1 to 1.0
max-fly-speed: 0.8

#Set the max walk speed, values range from 0.1 to 1.0
max-walk-speed: 0.8

#Set the maximum amount of mail that can be sent within a minute.
mails-per-minute: 1000

# Set the maximum time /tempban can be used for in seconds.
# Set to -1 to disable, and essentials.tempban.unlimited can be used to override.
max-tempban-time: -1

############################################################
# +------------------------------------------------------+ #
# |                   EssentialsHome                     | #
# +------------------------------------------------------+ #
############################################################

# Allows people to set their bed at daytime.
update-bed-at-daytime: true

# Set to true to enable per-world permissions for using homes to teleport between worlds.
# This applies to the /home only.
# Give someone permission to teleport to a world with essentials.worlds.<worldname>
world-home-permissions: false

# Allow players to have multiple homes.
# Players need essentials.sethome.multiple before they can have more than 1 home.
# You can set the default number of multiple homes using the 'default' rank below.
# To remove the home limit entirely, give people 'essentials.sethome.multiple.unlimited'.
# To grant different home amounts to different people, you need to define a 'home-rank' below.
# Create the 'home-rank' below, and give the matching permission: essentials.sethome.multiple.<home-rank>
# For more information, visit http://wiki.ess3.net/wiki/Multihome
sethome-multiple:
  default: 3
  vip: 5
  staff: 10

# In this example someone with 'essentials.sethome.multiple' and 'essentials.sethome.multiple.vip' will have 5 homes.
# Remember, they MUST have both permission nodes in order to be able to set multiple homes.

# Set the timeout, in seconds for players to accept a tpa before the request is cancelled.
# Set to 0 for no timeout.
tpa-accept-cancellation: 120

############################################################
# +------------------------------------------------------+ #
# |                   EssentialsEco                      | #
# +------------------------------------------------------+ #
############################################################

# For more information, visit http://wiki.ess3.net/wiki/Essentials_Economy

# Defines the balance with which new players begin. Defaults to 0.
starting-balance: 0

# worth-# defines the value of an item when it is sold to the server via /sell.
# These are now defined in worth.yml

# Defines the cost to use the given commands PER USE.
# Some commands like /repair have sub-costs, check the wiki for more information.
command-costs:
  # /example costs $1000 PER USE
  #example: 1000
  # /kit tools costs $1500 PER USE
  #kit-tools: 1500

# Set this to a currency symbol you want to use.
# Remember, if you want to use special characters in this document, 
# such as accented letters, you MUST save the file as UTF-8, not ANSI.
currency-symbol: '$'

# Set the maximum amount of money a player can have.
# The amount is always limited to 10 trillion because of the limitations of a java double.
max-money: 10000000000000

# Set the minimum amount of money a player can have (must be above the negative of max-money).
# Setting this to 0, will disable overdrafts/loans completely.  Users need 'essentials.eco.loan' perm to go below 0.
min-money: -10000

# Enable this to log all interactions with trade/buy/sell signs and sell command.
economy-log-enabled: false

# Use this option to force superperms-based permissions handler regardless of detected installed perms plugin.
# This is useful if you want superperms-based permissions (with wildcards) for custom permissions plugins.
# Default is false. 
use-bukkit-permissions: false

############################################################
# +------------------------------------------------------+ #
# |                   EssentialsHelp                     | #
# +------------------------------------------------------+ #
############################################################

# Show other plugins commands in help.
non-ess-in-help: true

# Hide plugins which do not give a permission.
# You can override a true value here for a single plugin by adding a permission to a user/group.
# The individual permission is: essentials.help.<plugin>, anyone with essentials.* or '*' will see all help regardless.
# You can use negative permissions to remove access to just a single plugins help if the following is enabled.
hide-permissionless-help: true

############################################################
# +------------------------------------------------------+ #
# |                   EssentialsChat                     | #
# +------------------------------------------------------+ #
############################################################

# This section requires the EssentialsChat.jar to work.

chat:

  # If EssentialsChat is installed, this will define how far a player's voice travels, in blocks.  Set to 0 to make all chat global.
  # Note that users with the "essentials.chat.spy" permission will hear everything, regardless of this setting.
  # Users with essentials.chat.shout can override this by prefixing text with an exclamation mark (!)
  # Users with essentials.chat.question can override this by prefixing text with a question mark (?)
  # You can add command costs for shout/question by adding chat-shout and chat-question to the command costs section."
  radius: 0

  # Chat formatting can be done in two ways, you can either define a standard format for all chat.
  # Or you can give a group specific chat format, to give some extra variation.
  # For more information of chat formatting, check out the wiki: http://wiki.ess3.net/wiki/Chat_Formatting

  format: '<{DISPLAYNAME}> {MESSAGE}'
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'

  group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'

  # If you are using group formats make sure to remove the '#' to allow the setting to be read.

############################################################
# +------------------------------------------------------+ #
# |                 EssentialsProtect                    | #
# +------------------------------------------------------+ #
############################################################

# This section requires the EssentialsProtect.jar to work.

protect:

  # General physics/behavior modifications.
  prevent:
    lava-flow: false
    water-flow: false
    water-bucket-flow: false
    fire-spread: true
    lava-fire-spread: true
    flint-fire: false
    lightning-fire-spread: true
    portal-creation: false
    tnt-explosion: false
    tnt-playerdamage: false
    tnt-minecart-explosion: false
    tnt-minecart-playerdamage: false
    fireball-explosion: false
    fireball-fire: false
    fireball-playerdamage: false
    witherskull-explosion: false
    witherskull-playerdamage: false
    wither-spawnexplosion: false
    wither-blockreplace: false
    creeper-explosion: false
    creeper-playerdamage: false
    creeper-blockdamage: false
    enderdragon-blockdamage: true
    enderman-pickup: false
    villager-death: false
    # Monsters won't follow players.
    # permission essentials.protect.entitytarget.bypass disables this.
    entitytarget: false
    # Prevent the spawning of creatures.
    spawn:
      creeper: false
      skeleton: false
      spider: false
      giant: false
      zombie: false
      slime: false
      ghast: false
      pig_zombie: false
      enderman: false
      cave_spider: false
      silverfish: false
      blaze: false
      magma_cube: false
      ender_dragon: false
      pig: false
      sheep: false
      cow: false
      chicken: false
      squid: false
      wolf: false
      mushroom_cow: false
      snowman: false
      ocelot: false
      iron_golem: false
      villager: false
      wither: false
      bat: false
      witch: false
      horse: false

  # Maximum height the creeper should explode. -1 allows them to explode everywhere.
  # Set prevent.creeper-explosion to true, if you want to disable creeper explosions.
  creeper:
    max-height: -1

  # Disable various default physics and behaviors.
  disable:
    # Should fall damage be disabled?
    fall: false

    # Users with the essentials.protect.pvp permission will still be able to attack each other if this is set to true.
    # They will be unable to attack users without that same permission node.
    pvp: false

    # Should drowning damage be disabled?
    # (Split into two behaviors; generally, you want both set to the same value.)
    drown: false
    suffocate: false

    # Should damage via lava be disabled?  Items that fall into lava will still burn to a crisp. ;)
    lavadmg: false

    # Should arrow damage be disabled?
    projectiles: false

    # This will disable damage from touching cacti.
    contactdmg: false

    # Burn, baby, burn!  Should fire damage be disabled?
    firedmg: false

    # Should the damage after hit by a lightning be disabled?
    lightning: false

    # Should Wither damage be disabled?
    wither: false

    # Disable weather options?
    weather:
      storm: false
      thunder: false
      lightning: false

############################################################
# +------------------------------------------------------+ #
# |                EssentialsAntiBuild                   | #
# +------------------------------------------------------+ #
############################################################

  # This section requires the EssentialsAntiBuild.jar to work.

  # Disable various default physics and behaviors
  # For more information, visit http://wiki.ess3.net/wiki/AntiBuild

    # Should people with build: false in permissions be allowed to build?
    # Set true to disable building for those people.
    # Setting to false means EssentialsAntiBuild will never prevent you from building.
    build: true

    # Should people with build: false in permissions be allowed to use items?
    # Set true to disable using for those people.
    # Setting to false means EssentialsAntiBuild will never prevent you from using items.
    use: true

    # Should we tell people they are not allowed to build?
    warn-on-build-disallow: true

  # For which block types would you like to be alerted?
  # You can find a list of IDs in plugins/Essentials/items.csv after loading Essentials for the first time.
  # 10 = lava :: 11 = still lava :: 46 = TNT :: 327 = lava bucket
  alert:
    on-placement: 10,11,46,327
    on-use: 327
    on-break:

  blacklist:

    # Which blocks should people be prevented from placing?
    placement: 10,11,46,327

    # Which items should people be prevented from using?
    usage: 327

    # Which blocks should people be prevented from breaking?
    break:

    # Which blocks should not be pushed by pistons?
    piston:

    # Which blocks should not be dispensed by dispensers
    dispenser:

############################################################
# +------------------------------------------------------+ #
# |            Essentials Spawn / New Players            | #
# +------------------------------------------------------+ #
############################################################

# This section requires essentialsspawn.jar to work.

newbies:
  # Should we announce to the server when someone logs in for the first time?
  # If so, use this format, replacing {DISPLAYNAME} with the player name.
  # If not, set to ''
  #announce-format: ''
  announce-format: '&dWelcome {DISPLAYNAME}&d to the server!'

  # When we spawn for the first time, which spawnpoint do we use?
  # Set to "none" if you want to use the spawn point of the world.
  spawnpoint: newbies

  # Do we want to give users anything on first join? Set to '' to disable
  # This kit will be given regardless of cost and permissions, and will not trigger the kit delay.
  #kit: ''
  kit: tools

# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: high

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

# End of file <-- No seriously, you're done with configuration.

**Comment by konapuppy** [comment]
Um, I don't really know how to find if there's something wrong. ;-;

**Comment by Stormbow** [comment]
Try to remember where you've changed things in the file.  Look through those areas to make sure you didn't type something incorrectly.

Copy the file to your desktop, let the server make the file brand new, then open both files and compare them to find out where the errors may be.

**Comment by konapuppy** [comment]
TBH, I've never even been in a config file until now..

**Comment by Stormbow** [comment]
Read the prefix guide I linked above to find out how to get prefixes showing.

**Comment by konapuppy** [comment]
But the plugins are red. Does it still work?

**Comment by Stormbow** [comment]
Oh, they're still red?  Not working then.  It may be like I originally suspected, that 1.7.9/1.8 Essentials doesn't work on your server.

**Comment by Stormbow** [comment]
You may have to make the change to using Spigot instead of Craftbukkit.  :-[

**Comment by konapuppy** [comment]
Do I need all new plugins?

**Comment by Stormbow** [comment]
Not if you switch to using Spigot 1.8.8; the only thing you'd need to replace would be Essentials to EssentialsX (linked above) and EssentialsChat to EssentialsXChat (also linked above).

**Comment by konapuppy** [comment]
Ok! 😀

**Comment by Stormbow** [comment]
As for setting up a Spigot server, lots of guides and YouTube videos for that stuff, so you won't need me for that.  (And that's a good thing, since I've never actually set up a Spigot server myself.)

You can reply to this thread if you have any PEX issues or questions, I'll get an email and I'll get back to ya as soon as I can.

(Don't let the "Ticket closed" fool you.  You can still post here.  That's just so the PEX author doesn't have to worry about reading all the junk we've been through so far.)

**Comment by ZaosDaOne** [comment]
I need help i have EssentialsChat i have tons of group and permissions yet when i set someone as the group no prefix is shown a prefix is only shown when you set it on that person which creates a entire new group.
I have PEX and essentialschat please

**Comment by Stormbow** [comment]
Essentials help is [over here](https://www.spigotmc.org/resources/essentialsx.9089/).

**Comment by ZaosDaOne** [comment]
that doesnt help At All im not even using essentialsx
