### ISSUE TITLE
player named "newplayer"

### ISSUE THREAD

**Issue by meoso** [PEXPlugins/PermissionsEx#2473]
Is there a special case for a player named "newplayer"?  I run an offline server, and if i login with uername "newplayer", pex sort of works (i finally got it to assign the default group correctly), but the user still has permissions for fly and heal and who knows what else. i tried another random username "another" and permissions/group worked properly as expected.  i was forced to ban the username "newplayer".  If i ever go open to the internet, I'm concerned with some random username getting superuser/op rights.

**Comment by Stormbow** [comment]
Offline servers are not supported by PEX.
