### ISSUE TITLE
Nothing works for 1.23.4

### ISSUE THREAD

**Issue by rradt2001** [PEXPlugins/PermissionsEx#2475]
Okay, so I just got this and am a bit of a noob. But nothing works, the console can't even do commands.
I do have this code that should have fixed it, but apparently it won't.
```
users:
rradt2001:
permissions:
        bukkit.command.op.give: true
        bukkit.command.op.take: true
        *: true
        *.*: true

  calebjedimaster:
      permissions:
        bukkit.command.op.give: true
        bukkit.command.op.take: true
        *: true
        *.*: true
```
Please help, because we can't make groups without the commands.

**Comment by rradt2001** [comment]
Note: console works now. But we made groups with those permissions, assigned ourselves to them and we still can't do anything /pex related

**Comment by Stormbow** [comment]
You're attempting to use GroupManager permission setups in the PermissionsEx plugin.

Follow [this example](http://pastebin.com/8ZSHxauG).

**Comment by rradt2001** [comment]
Oh sorry. . . xD

**Comment by rradt2001** [comment]
Actually, we did use that example, and put our names in it as owner. Still didn't work . . . we couldn't do any pex commands except for just /pex

**Comment by zml2008** [comment]
Well if you want more help you could pastebin your whole permissions file. The segment you pasted in your original issue is the wrong data structure as Stormbow mentioned, and also has a ton of syntax errors that would cause PEX to fail to load it at all.

**Comment by rradt2001** [comment]
... well we could try to put it back to that, would this be the right code?
`groups:
  Guest:
    options:
      default: 'true'             # As of Minecraft 1.7.9, all of these options need to be under the options: section.
      build: 'true'               # If you DON'T use one or more of these settings, its line can be deleted entirely.
      prefix: 'Guest '            # But if you DO use any of these, they MUST be under options: or PEX won't work.
      suffix: ' the Visitor'
      rank: '1000'
      rank-ladder: Main
      weight: '5'
    permissions:
    - modifyworld.*
    - essentials.kit
    - essentials.kits.guest
    - permission.node.one
    - permission.node.two
    - permission.node.three
    - permission.node.four
    inheritance: []                # As of Minecraft 1.9, every group MUST have an inheritance or PEX won't work.
  Member:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Member '
      suffix: ' the Regular'
      rank: '900'
      rank-ladder: Main
      weight: '4'
    inheritance:
    - Guest
    permissions:
    - essentials.kits.member
    - -essentials.kits.guest
    - permission.node.give
    - permission.node.six
    - permission.node.seven
    - permission.node.eight
  Mod:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Mod '
      suffix: ' the Scary'
      rank: '200'
      rank-ladder: Main
      weight: '3'
    inheritance:
    - Member
    permissions:
    - essentials.kits.mod
    - -essentials.kits.member
    - permission.node.nine
    - permission.node.ten
    - permission.node.eleven
    - permission.node.twelve
  Admin:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Admin '
      suffix: ' the Benevolent'
      rank: '100'
      rank-ladder: Main
      weight: '2'
    inheritance:
    - Mod
    permissions:
    - essentials.kits.admin
    - -essentials.kits.mod
    - permission.node.thirteen
    - permission.node.fourteen
    - permission.node.fifteen
    - permission.node.sixteen
  Owner:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Owner '
      suffix: ' the Almighty'
      rank: '1'
      rank-ladder: Main
      weight: '1'
    inheritance:
    - Admin
    permissions:
    - -negated.nodes.go.above.wildcards
    - -vanish.silentjoin                    # Important to negate for Vanish type plugins!
    - '*'
schema-version: 1
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: rradt2001
    group:
    - Owner
    permissions:
    - permissions.*
name:calebjedimaster
    group:
    - Owner
    permissions:
    - permissions.*`
We will have to change is back to this, and get PEX again, jedimaster deleted it. . . I will get him to reinstall it and put this code in. If it's a good code that is.

**Comment by Stormbow** [comment]
If your server is running in offline mode (server.properties file, online-mode: false, which A LOT of people are trying to do this past week), know that PEX does not support offline mode.

When you run the server in online-mode: true, your UUIDs will be added to the users list.

**Comment by rradt2001** [comment]
Okay

**Comment by Stormbow** [comment]
I'll check back in with you later to see how things are going.

**Comment by rradt2001** [comment]
Apparently, this was all because he put this in the wrong yml folder. Works now, thanks for the assistance!

**Comment by Stormbow** [comment]
You're welcome.
