### ISSUE TITLE
[PEX 2.0/SpongeForge/MC 1.8.9] Commands not working ?

### ISSUE THREAD

**Issue by Abandonnn** [PEXPlugins/PermissionsEx#2476]
## Server Information and Plugin Versions

I'm in a bit of a pickle here, and I am not sure how to move on.

I installed **PEX** (**build 131**) for **SpongeForge** (version **1.8.9-1890-4.2.0-BETA-1564**) sometime yesterday for my **Pixelmon** (version **1.8.9-4.2.7**) server, and since then I have been working on permission nodes and groups.

**Upon starting my server, it did generated a config folder**:

```
ninja.leaping.permissionsex
```

**Inside this folder, two files were generated**:

```
ninja.leaping.permissionsex.conf
permissions.mv.db
```
- **The contents inside of the** `ninja.leaping.permissionsex` **file are as follows**:

```

# The list of backends able to be selected
backends {
    default {
        prefix=pex
        type=sql
        url="jdbc:h2:permissions"
    }
    default-file {
        # Place file entries in alphabetical order
        alphabetize-entries=false
        file="permissions.json"
        type=file
    }
}
# Whether to log permissions checks being performed
debug=false
default-backend=default-file
# Tags that apply to this server (which match with permissions blocks restricted by server-tag contexts
server-tags=[]
version=0
```
- **Nothing was generated inside of the** `permissions.mv.db` **file-- it was blank**.
## The Issue

Simply put- _most_ of the PEX commands listed on the wiki here are not working:

> https://github.com/PEXPlugins/PermissionsEx/wiki/Commands

I have tried to run commands such as **/pex group Owner create** both in-game and via my console, but to no luck whatsoever. It gives me the following error with most commands I try to run:

> Usage: /pex [debug|reload|import|ranking|[--context|--contexts|-c] [-transient] subject permission-default|delete|options|info|permission|parents|[-transient] subject-type list [filter]]
> Too many arguments!

I of course was able to use the permission nodes and groups I created via `permissions.json`, but it is still pretty frustrating that half of the PEX commands fail to work.

I'm hoping someone has some sort of information and or solution to this problem, as it is preventing me from continuing on with the creation of my server at the moment.

Cheers,
Abandon

**Comment by Stormbow** [comment]
I'm going to bet on that being because all of those commands are for PEX 1.x and you're running 2.x, but @zml2008 will be able to tell you more.

**Comment by zml2008** [comment]
Yeah, documentation for 2.0 is available from https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md (and other pages in that folder). It's a bit sparse at the moment, but the additions I've made are at the moment a bit different since some changes are in progress that add more configurability.

**Comment by Abandonnn** [comment]
Thank you both for the replies!

I have read over the  documentation for PEX2 a few times now and I am at least starting to learn some of the new commands and such. I do have a couple a questions for you however, if you don't mind.

Regarding future updates, do you plan on making some sort of table for commands, alongside exactly what it is they do (similar to the one you've made for PEX1)-- or better yet, do you have one now that's being updated over time ? This brings me to my next question.

The `` /promote`` and `` /demote`` commands. I think I've figured out how to use these properly- what I've been typing is `` /promote user Abandon`` and it'll rank me up as I intended it to.

The issue I'm having with that is this though: is there a way to  specify which rank ladder you want to promote or demote a user in ? I don't get a popup message for each command I execute, so I'm not always 100% sure.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.

**Comment by BurkenDev** [comment]
LuckPerms isn't as good as PEX and pex is still going strong in 2021, so no need to switch when it's still working like it should. No one needs to develop anything,

**Comment by Aberdeener** [comment]
https://www.urbandictionary.com/define.php?term=Necroposting
