### ISSUE TITLE
unknown Error Message 

### ISSUE THREAD

**Issue by Darelius** [PEXPlugins/PermissionsEx#2477]
After i have used the commands in the console on this "tutorial"
https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md

I recieve this error message when adding
following code:
/pex rank default add group default

[11:31:52] [pool-2-thread-3/INFO]: Error (JdbcBatchUpdateException) occurred while performing command task! Please see console for details: Eindeutiger Index oder Primärschlüssel verletzt: "CONSTRAINT_INDEX_B ON PUBLIC.PEX_RANK_LADDERS(NAME, SUBJECT) VALUES ('default', 4, 7)"
Unique index or primary key violation: "CONSTRAINT_INDEX_B ON PUBLIC.PEX_RANK_LADDERS(NAME, SUBJECT) VALUES ('default', 4, 7)"; SQL statement:
INSERT INTO pex_rank_ladders (`name`, `subject`) VALUES (?, ?) [23505-192]

When inserting
/pex rank default add group member

i recieve this:
[11:35:32] [pool-2-thread-4/INFO]: Error (JdbcBatchUpdateException) occurred while performing command task! Please see console for details: Eindeutiger Index oder Primärschlüssel verletzt: "CONSTRAINT_INDEX_B ON PUBLIC.PEX_RANK_LADDERS(NAME, SUBJECT) VALUES ('default', 5, 11)"
Unique index or primary key violation: "CONSTRAINT_INDEX_B ON PUBLIC.PEX_RANK_LADDERS(NAME, SUBJECT) VALUES ('default', 5, 11)"; SQL statement:
INSERT INTO pex_rank_ladders (`name`, `subject`) VALUES (?, ?) [23505-192]

So what can i do now?

...DX

P.S.: Im a pure beginner with minecraft "server" technology, so please dont bump me ;)

**Comment by zml2008** [comment]
Ok my guess here is that a group appears in your rank ladder twice -- I'm going to take a look at how that works and see if it can be resolved.

**Comment by Darelius** [comment]
So its not "my" fault that im too stupid to configure it?

**Comment by zml2008** [comment]
Well adding a group that already exists should either move it to the end or give an error message, not cause trouble with the SQL backend, so it's PEX's problem to solve.

Also the documentation is pretty sparse, so it's it's pretty easy to get lost on 2.x (though more documentation is happening as I have time to write it/people want to contribute)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
