### ISSUE TITLE
PEX site hacked?

### ISSUE THREAD

**Issue by Stormbow** [PEXPlugins/PermissionsEx#2479]
The following message appears on the PEX bukkit page and [forums](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/).

```
This project has an abnormal status: Changes required.
Please review your plugins.
```

I received the following PM from `Ilario422`:
```


SITE HACKED BY 3ch0s3c

Hello, very important, if you go to some of Bukkit plugin pages: 'Essentials'
'PermissionsEx' and 'Iconomy' You'll notice a strange thing! THE SITE OF A
CERTAIN WAS HACKED : 3ch0s3c
In Of These Pages Plugin We find Signs Of:

PermissionsEx

Overview Files Images Tickets Pages Repositories Subscriptions

TopBanner

Follow => https://www.twitter.com/3ch0s3c Fuck the System

Pwned by -> 3ch0s3c

Fuck the System

Pwned by -> 3ch0s3c -

Take Measures Continues To Hack Your Pages Bukkit

Who Writes There is Ilario422

Goodbye and been WARNED
```

All of the downloads are gone from the [Files](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/) page.

**Comment by Stormbow** [comment]
I am going to be out of town this weekend, returning July 25th or 26th.

**Comment by Stormbow** [comment]
I've sent a ticket in to the Moderators of Bukkit.org, but I don't know if they'll be able to do anything about all the missing downloads.****

**Comment by zml2008** [comment]
Ok, thanks for letting me know -- folks have been pinging me on IRC all morning and I got the email from Curse too. I responded to Ilario422's forum post with the same message as well, with the response: 

> Yeah, I've been made aware of this from uh quite a few people, and have been working to restore things. The front page has been restored, and the files will be soon.

> This looks like it was only a defacing of the front page and files, since no compromised jars have been uploaded -- the hacker just deleted all recent versions of PEX and replaced the description. That means that there's no way the hackers could directly affect individual servers, just cause some annoyance to us.

> It looks like they got in by using credentials from an account of an inactive developer. To prevent that from happening in the future, all inactive developers have been removed from the project, I've changed my curse account password, and I'm going to ask Stormbow to change his account password.


**So yeah, make sure to change your passwords, turn on 2-factor authentication on GitHub, and let's hope this happens again**

I'll poke the BukkitDev folks on IRC too.

**Comment by Stormbow** [comment]
Looks like Bukkit is working on reverting them:

```
Hello Stormbow,

I am working on reverting the hacked accounts at the moment and will be resetting your project shortly.

Thanks, Zeldo
```

**Comment by zml2008** [comment]
Great, that saves some effort.

**Comment by Stormbow** [comment]
Do you want me to delete the "hacked" post from the PEX forums?

(Changing my passwords now.)

**Comment by zml2008** [comment]
Once the project is restored, yeah, but leave it until then in case anyone gets confused about there being no files.

**Comment by Stormbow** [comment]
The files are back.

Shall we go with the "Stop making stupid people famous!" approach and delete all related posts now?

**Comment by Stormbow** [comment]
PS - I reported his Twitter and Facebook accounts for the hacking.  Hopefully he'll lose both of those accounts.  heh

**Comment by zml2008** [comment]
Yeah, seems good to get rid of the mentions.
