### ISSUE TITLE
misconfigured Auto Update system

### ISSUE THREAD

**Issue by OrangeK** [PEXPlugins/PermissionsEx#2481]
[copied from terminal]

[15:02:41 WARN]: [PermissionsEx] The author of this plugin ([t3hk0d3, zml]) has misconfigured their Auto Update system
[15:02:41 WARN]: [PermissionsEx] File versions should follow the format 'PluginName vVERSION'
[15:02:41 WARN]: [PermissionsEx] Please notify the author of this error.

**Comment by Stormbow** [comment]
Which version of PEX are you referring to?

**Comment by OrangeK** [comment]
v1.23.4

**Comment by Stormbow** [comment]
Try downloading the file again.  It may have been corrupted during download.

If downloading the file brand new doesn't resolve the problem, Pastebin your config.yml file and your latest.log (or copy everything from the moment the server starts until text stops printing to the console) into your reply to this post.

**Comment by zml2008** [comment]
My guess is that this has something to do with all of the files being erased earlier on today, and the fact that the last file was given a nonconforming name. It shouldn't be an issue now that files have been restored.
