### ISSUE TITLE
I disconnect from the server when I type in chat

### ISSUE THREAD

**Issue by hotcody147** [PEXPlugins/PermissionsEx#2482]
So I just installed PEX for my 1.7.10 minecraft server. (Its a custom moded server) and I set my self to the Owner group. I made a permission.yml along time ago for a server I developed. Can anyone help me fix this problem Im having.

**Comment by hotcody147** [comment]
So I reinstalled my minecraft server and installed every mod with it
what version of pex do I run with a 1.7.10 Thermos Server?

**Comment by zml2008** [comment]
We don't support Cauldron since it adds a lot more complexity over normal bukkit and nobody on the team is experienced with a lot of its intricacies  -- good luck.
