### ISSUE TITLE
pex lifetime in seconds for user!

### ISSUE THREAD

**Issue by vanthoi** [PEXPlugins/PermissionsEx#2483]
Iuser /pex user <user> timed add <permission> <lifetime in seconds> [world]
If the player is leaving the game. Then log back in, the permission have lost added. It is wise exist anymore!

**Comment by Stormbow** [comment]
Correct.  Timed abilities are temporary.  These might be stored long-term in PEX 2.0 but won't be getting long-term storage in PEX 1.x versions.
