### ISSUE TITLE
Data missing?

### ISSUE THREAD

**Issue by Darelius** [PEXPlugins/PermissionsEx#2484]
Again me ;)
Normally the "permissions" were stored somewhere in a file, that i cen see and change with notepad..
But i didnt found any file, so how is the information stored (for ranks , membergroups etc) and how i can see/change them except the console?

...DX

**Comment by Stormbow** [comment]
Plugins folder → PermissionsEx folder → permissions.yml file.

If the file is not being created, check your console log for errors.  You may have to re-download the PermissionsEx.jar file and replace the one in your plugins folder.  (File corruption during download can lead to no permissions.yml file being generated.)

**Comment by zml2008** [comment]
Also, as of recent builds of 2.x, the default is to store permissions in a H2 database, in which case you have to edit permissions using commands.

**Comment by Darelius** [comment]
And how i can "open" this "h2" database, because there is no "yml"-File anymore only a db-file..
With normal "noteüpad"-variants its only mixed chars...

**Comment by Stormbow** [comment]
"... in a H2 database, in which case you have to edit permissions using commands."

You can't edit the database without using the PEX commands.  (Documentation not fully evolved yet. [See here](https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md) for what's available.)
