### ISSUE TITLE
How Do I Give Admins Permissions To Use PEX

### ISSUE THREAD

**Issue by konapuppy** [PEXPlugins/PermissionsEx#2485]
I'm stupid. ;-;

I've done this command before, but now I forgot it. ;-; 

How do you give somebody permission to use PEX? When one of my staff members, (Op-ed,) uses a PEX command, and all it says is something like, "insufficient permissions" etc.

I know it's a command you have to use in console and it's something like,

/pex Admin [user] *

or

/pex [user] Admin *

All I know, is that it's something like that. ;-;

Sorry for the trouble. ;-;

@Stormbow you're very helpful I would love it for you to come. <3

**Comment by zml2008** [comment]
1.x or 2.x?

**Comment by konapuppy** [comment]
Erm, as in plugin versions?

**Comment by zml2008** [comment]
yeah, which version of PEX

**Comment by konapuppy** [comment]
PermissionsEx-1.23.2.jar

**Comment by zml2008** [comment]
Ok, so first of all update to the latest version. 

On 1.x, what you usually do is create a group with all perms then add the user to that, so that would be

1. `/pex group admin add *`
2. `/pex user <name> group set admin`

**Comment by konapuppy** [comment]
Thanks!

**Comment by konapuppy** [comment]
Thanks!
