### ISSUE TITLE
Conflit with Factions and PEX

### ISSUE THREAD

**Issue by BigMrBad** [PEXPlugins/PermissionsEx#2486]
Sorry my bad Englhish, I'm Brasilian.

Apparently Factions has a conflict with PermissionEx, and by what appears to be a conflict with tags. If I put the Factions and LegendChat, it works fine, but when I put the PermissionEx gives a strange error. I tried to move the code Factions but not resolved.

Log: http://hastebin.com/lorebuweko.coffee

**Comment by zml2008** [comment]
You're running a version of PEX that is multiple years out of date (also on a very outdated server). You should go through and update everything, but PEX needs to be at least at 1.23.4 to work.
