### ISSUE TITLE
Future Feature to add

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2491]
If you have not done this already would like to see a way to use weights per world, or a way to do this, I'm running older software that is not suppose to run on a bungee server and if weights for ranks could be set  per world I would be able to set a rank ladder 1 on a world to the dominate ranks then rank ladder 2 since rank ladder 2  is not used on that world.  On another world rank ladder 2 be more dominate the rank ladder 1

**Comment by zml2008** [comment]
A more flexible weight system is coming to PermissionsEx 2. Also, PEX 2 already has a feature to limit permissions by server, with the `server-tag` context.
