### ISSUE TITLE
Pex 2.0 Sponge 

### ISSUE THREAD

**Issue by hammikb** [PEXPlugins/PermissionsEx#2493]
Does the sponge version of pex not generate a permission.json or is it just in a different place

spongeforge-1.10.2-2026-5.0.0-BETA-1622
PermissionEx Build #136

**Comment by zml2008** [comment]
The default backend is a H2 database, stored in permissionsex.mv.db.

**Comment by hammikb** [comment]
zml2008 is there any way to edit it
