### ISSUE TITLE
The updater could not find any files for the project id 31279

### ISSUE THREAD

**Issue by DelboyDylan** [PEXPlugins/PermissionsEx#2495]
The following message is currently appearing in the server log.

[13:24:03] [Thread-8/WARN]: [PermissionsEx] The updater could not find any files for the project id 31279

**Comment by jeanmarin** [comment]
Same here

**Comment by zml2008** [comment]
This was an issue after the PEX downloads page was vandalized, but should be fine now.

**Comment by Sketaful** [comment]
Is this supposed to have been an issue connected to the site and not the plugin? 
Cause I get the exact same error on 1.11 now.

**Comment by krustymk** [comment]
Im getting it on 1.11 also

**Comment by Stormbow** [comment]
If you're using PEX 1.x, this message is because PEX 1.x is no longer being updated (per zml).

This error message does no harm to the server and PEX 1.23.4 works perfectly on 1.11 servers so far as I have seen.

**Comment by rwmtiger** [comment]
but the error should be fixed even if it harmless

**Comment by Stormbow** [comment]
Bukkit is currently all fubar, so nothing can be done about it.
