### ISSUE TITLE
PermissionEx for Sponge Api 5 doesn't start

### ISSUE THREAD

**Issue by MatteCarra** [PEXPlugins/PermissionsEx#2499]
I'm running SpongeForge 1.10.2.
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-fc96f10
    SpongeForge: 1.10.2-2043-5.0.0-BETA-1638
    Minecraft Forge: 12.18.1.2043

These are the exception on first start: http://pastebin.com/Zis03x6S

I'm using https://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/lastSuccessfulBuild/artifact/permissionsex-sponge/target/permissionsex-sponge-2.0-SNAPSHOT-shaded.jar

**Comment by zml2008** [comment]
Hm, could you pastebin your ninja.leaping.permissionsex.conf? Also, looks like FoxGuard and FoxCore are not updated for API 5 yet, which is why you're getting errors from them.

**Comment by MatteCarra** [comment]
It was the first launch.
Here you are config file: http://pastebin.com/6kDZ4bnB
I have updated FoxGuard and FoxCore.
Thank you very much!

**Comment by zml2008** [comment]
Ok, that's really weird. Try deleting the permissions.mv.db file in the config folder, and if that doesn't work I'll look into the issue more.

**Comment by MatteCarra** [comment]
I have problem with all plugins using h2 database driver.
What did I do wrong?

**Comment by zml2008** [comment]
Something? Nothing? "problem" is not very specific.

**Comment by MatteCarra** [comment]
You are rigth hahaha. Sorry
It says org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement

**Comment by MatteCarra** [comment]
In any case problem with your plugins seems to be different.

> Caused by: ninja.leaping.permissionsex.exception.PermissionsLoadingException: Error initializing tables in SQL database!

> Caused by: org.h2.jdbc.JdbcBatchUpdateException: Table "PEX_CONTEXT_INHERITANCE" not found; SQL statement:
> CREATE INDEX ON `pex_context_inheritance` (`parent_key`, `parent_value`) [42102-192]

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
