### ISSUE TITLE
why's the commands not async?

### ISSUE THREAD

**Issue by MADS0LADEN** [PEXPlugins/PermissionsEx#2501]
if you type "/pex user A" then it lags the server because it sends all the players that starts with A.
wouldn't it fix the lag if commands were async?

**Comment by zml2008** [comment]
yes, but making the commands async is complicated, requires the rest of the plugin to be thread-safe, and requires any part of the server PEX touches to be thread-safe as well. Handling this well is a major part of the PEX 2.x redesign.
