### ISSUE TITLE
Essentials: Lag Notice - Slow Permissions System (PermissionsEx) Response.

### ISSUE THREAD

**Issue by Jacob4Redstone** [PEXPlugins/PermissionsEx#2503]
Hi, my server crashed today, and after it open again, it begin to spam whit this:

Essentials: Lag Notice - Slow Permissions System (PermissionsEx) Response
 
Im running: PermissionsEx v1.23.4.

Thanks for any respons.

**Comment by Stormbow** [comment]
Performance issue tickets are only being accepted for the new Sponge architecture, [per zml](https://github.com/PEXPlugins/PermissionsEx/issues/1824#issuecomment-94110813).  Sorry.
