### ISSUE TITLE
FEATURE REQUEST: Separate Group file and Users file

### ISSUE THREAD

**Issue by RAZERMC** [PEXPlugins/PermissionsEx#2504]
If you separate the saving of group file and user file specifically in MySQL this will enable MULTI SERVER SUPPORT 
Example table in mysql database table

factionsgroups
survivalgroups
prisongroups
pex_entities
pex_inheritance
pex_users

so when i setup the alias of database name in the config i can have factions pex look into the factionsgroup for the group permission and is saved in the pex_users 
This feature will enable per server groups and a global player database 
The possibilities of this feature is vast. So please think about this thanks 

Your plugin is awesome!

**Comment by Stormbow** [comment]
Already asked for many, many, many times.  It won't be getting added to PEX 1.x buy may make it into PEX 2.x for Sponge/Forge servers.
