### ISSUE TITLE
PEX SQL Not updating

### ISSUE THREAD

**Issue by MeRocks2000** [PEXPlugins/PermissionsEx#2506]
Hi Pex Dev,
I am having an issue with updating my SQL databases. 
My setup:  I currently have 4 servers + 1 proxy all connected through Bungeecord and Spigot on a dedicated server that have been running for 2-3 years.  On my proxy, I have mySQL installed.  In the databases I have a Pex Table that all my servers are connected to.  When I go onto one of my servers to do a mass pex file edit, when I attempt to re-import my file, it says all the correct messages, but my file doesn't import to my database. There are no errors in the console.  If you need any other info let me know!

Thanks!
MeRocks

**Comment by Stormbow** [comment]
Which version of PEX are you running?

**Comment by MeRocks2000** [comment]
I am running version 1.23.4 and Spigot 1.9.4.

**Comment by MeRocks2000** [comment]
So, I saw your post about the incompatibility.  Are there any 1.9 versions that Pex 1.23.4 is compatible with?

Thanks for your help!
MeRocks

**Comment by MeRocks2000** [comment]
Hello?  I have a public server that isn't working properly due to Pex, can you please respond to my above question?

MeRocks

**Comment by Stormbow** [comment]
Unfortunately, SQL, Bungee, and most of this situation is beyond my knowledgebase, so I can't be of much help with those sorts of issues.

You'll have to wait for @zml2008 to get some free time to look into this.  Sorry.

**Comment by MeRocks2000** [comment]
Okay.  Thanks!

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
