### ISSUE TITLE
Pex not starting and crashing my server

### ISSUE THREAD

**Issue by xion87** [PEXPlugins/PermissionsEx#2507]
my full log, using 1.8.9 and spongeforge 1722 
mods: pixelmon 4.2.7, worldedit 1.8.9.6.1.1, griefprevention 1.8.9 2.0.0.5.9
Startup log where it end with a crash
http://hastebin.com/itesahugos.vbs

**Comment by Stormbow** [comment]
I don't think PEX 2.x is for old Minecraft servers.  Zml will have more information for you.

**Comment by zml2008** [comment]
The issue here is that you're running a massively outdated version of sponge. Run the latest sponge and the version of forge listed there.

**Comment by xion87** [comment]
I cant use a new sponge version because i am using pixelmon (that is stable and only compatile with 1722 forge, yes there are some "beta version"  that use a more recent spongeforge. So there is no way for use pex with this version?
