### ISSUE TITLE
Help with automatically giving rank

### ISSUE THREAD

**Issue by maggie10619** [PEXPlugins/PermissionsEx#2510]
I need help on how to get it to automatically give someone a rank when they join so they will have simple commands such as set home. Can you help please? Thanks.
-Maggie

**Comment by Stormbow** [comment]
You can give those permissions to the one group on the server which has the `options:` setting of `default: true`.

To automatically promote users, you'll need to find a different, additional plugin to run alongside PermissionsEx (such as [AutoRank](http://dev.bukkit.org/bukkit-plugins/autorank/)) as PEX itself has no form of automation or chat management included.
