### ISSUE TITLE
Unable to remove player from group

### ISSUE THREAD

**Issue by BlackBeltPanda** [PEXPlugins/PermissionsEx#2511]
**PermissionsEx version: 1.23.4
Spigot version: Paper 1.10.2 Build 819
Using MySQL permission database**

Using the command "/pex user {user} group remove {group}", I'm unable to remove a player from a group when they have multiple groups in all worlds.

For example, PlayerA has "VIP" and "VIP+" in all worlds, "VIP" in World1, and "VIP+" in World2.
Using the above command to remove the player from the "VIP" group doesn't work. Even specifying all worlds by appending " *" to the end of the command has no effect.

The console outputs "User {UUID/PlayerName} removed from group {group}!" but they remain in the group for all worlds.

**Comment by Stormbow** [comment]
Have you tried the command `/pex user <user> group remove <group> [world]`?

**Comment by BlackBeltPanda** [comment]
Yes, it works when I specify a specific world, but when I tried "/pex user PlayerA group remove VIP *" it didn't remove the group they had set globally. Meaning, after specifying the world as World1, they no longer have VIP in World1 but they still have VIP globally.

**Comment by Stormbow** [comment]
I don't think I'm understanding the issue.

**Comment by zml2008** [comment]
If you add a group to a specific world (or worlds -- even if you individually add it to all worlds), you have to remove it from that world. If you add a group globally, you have to remove it globally. Removing it from the wrong place won't do anything.

**Comment by BlackBeltPanda** [comment]
Right, that's what I'm trying to do.
If they have VIP in World1, and I remove VIP from the player in World1, it works.
If they have VIP globally, and I remove VIP from the player globally, it doesn't work.

Here's an example with ranks and a player from my server:
Before running the command, they have "Jonin" globally: https://i.gyazo.com/df98c4b65ec5be19cb3bd8939fab7585.png
I tried without specifying a world: https://i.gyazo.com/ba503f38261b36c62afa173e532a4adb.png
I tried specifying all worlds: https://i.gyazo.com/bcffa3fedc49d16ca40c4b2f405ca694.png
Both times it output this message: https://i.gyazo.com/3140914fa26ac9f209c591dd4154348e.png
Afterwards, the player still has the "Jonin" group globally: https://i.gyazo.com/f5cd6cdad88c13c37b1ed1d4fc985531.png

**Comment by knightsoflol** [comment]
/pex user (players name) add group  (group name)
this can be used to move players from one rank to another without many problems.

**Comment by BlackBeltPanda** [comment]
Setting their group isn't feasible in this situation since the commands are run automatically and many of my players are in multiple groups.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
