### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by joao100101** [PEXPlugins/PermissionsEx#2515]
I found this problem in my server: http://hastebin.com/didesizaga.coffee   when I start my server it happens
info: 
Using version: PermissionsEx 1.20.2 
Server version: 1.5.2
Jar: Spigot 1.5.2

please help me!

**Comment by zml2008** [comment]
Step 1: Stop using a version of PEX and MC that is multiple years old. We don't support anything older than 1.7.10/PEX 1.22.10 or 1.8.9/PEX 1.23.4

**Comment by joao100101** [comment]
i  like older versions u.u
