### ISSUE TITLE
is co_block import?

### ISSUE THREAD

**Issue by Wearwolfy** [PEXPlugins/PermissionsEx#2523]
Hey i managed to see what is the problem. The database is VERY huge. there is only one table co_block that i can't export with phpmyadmin because its 2 big? Is co_block important? Do i need it?

**Comment by zml2008** [comment]
Saw the BukkitDev issue thread -- can't tell you much without you actually giving details about your setup. Make sure you copy *all* your data over -- not all of it might be attached to PEX, but the tables that do are important.

Also make sure both your servers have been in online mode -- offline mode uuids are different and not supported.

**Comment by SlimaKCoder** [comment]
Table co_block has been created by CoreProtect. You can disable block logging in your CoreProtect config. It have nothing to do with PEX. To export big database to file you can use Linux OS command on machine with MySQL installed: mysqldump

**Comment by zml2008** [comment]
Thanks @SlimaKCoder
