### ISSUE TITLE
Mod perms not working

### ISSUE THREAD

**Issue by fcpwiz** [PEXPlugins/PermissionsEx#2525]
Hi,

For some reason, a certain rank/group's perms don't work (moderator), but other groups do. Moderators can't access the /ban, /kick, or /socialspy commands even though those perms are in the file. Take a look at the permissions:

https://gist.github.com/fcpwiz/0a1439fc0d3f49a2965d1014c101b38f#file-gistfile1-txt-L107-L127

**Comment by Stormbow** [comment]
• Vanilla Permissions have [issues](https://dev.bukkit.org/bukkit-plugins/permissionsex/forum/86945-problems-with-vanilla-permissions/#p1) and can't be trusted to function correctly.  There's nothing PEX can do to fix those.

• What did [Debug Mode](https://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2) tell you about the other permissions?

**Comment by fcpwiz** [comment]
@Stormbow 

```
11:36:44 PM CONSOLE: [INFO] Debug mode for user 12bf7dab-3e52-4a78-8077-bbd6d8579810/fcpwiz enabled!
11:36:50 PM PermissionsEx: User 12bf7dab-3e52-4a78-8077-bbd6d8579810 checked for "worldguard.region.bypass.world", no permission found
11:36:50 PM CONSOLE: [INFO] fcpwiz issued server command: /ban
11:36:50 PM CONSOLE: [INFO] cfcpwiz 4was denied access to command.
```

So I added `worldguard.region.bypass.world`, reloaded PEX, still couldn't do /ban, tried debug mode and got: `PermissionsEx: User 12bf7dab-3e52-4a78-8077-bbd6d8579810 checked for "worldguard.region.bypass.world", "worldguard.region.bypass.world" found`

**Comment by Stormbow** [comment]
Did you update the group to using Essentials' ban?

**Comment by fcpwiz** [comment]
@Stormbow Yes, here's the new file:

https://gist.github.com/fcpwiz/5ba58b74add6a00d3d7eb73ce76365d3#file-gistfile1-txt-L107-L125

**Comment by Stormbow** [comment]
Group doesn't have `essentials.ban` which gives access to the slash command `/ban`.

**Comment by fcpwiz** [comment]
It has `essentials.ban.*`. Should it be changed to `essentials.ban`?

**Comment by Stormbow** [comment]
You need both if you want to do everything related to banning.  (Except banip, of course, since it's also its own node.)

**Comment by fcpwiz** [comment]
Ah so changing `essentials.ban.*` to `essentials.ban` worked! So `essentials.ban` is for `/ban` while `essentials.ban.*` allows the other slash ban commands?

**Comment by Stormbow** [comment]
Yep.  Like I said. ;)

**Comment by fcpwiz** [comment]
Thank you!

**Comment by Stormbow** [comment]
You're welcome. :)
