### ISSUE TITLE
Auto Ranks

### ISSUE THREAD

**Issue by Chris4418** [PEXPlugins/PermissionsEx#2526]
this is not an issue, but im curious to know if PEX has an Auto rank feature. I have a forums page which runs on Enjin, they have a plugin that hooks the Server and Forums together which enables many many features. one of which syncs the server ranks to the forums and vice versa, but for the sync to correctly work, i would like to know if there is a chance that this plugin allows for auto ranking. So if a player buys a rank, or i promote a Moderator to Admin, or Derank players on the Forums that PermissionsEx hooks on to Enjins or other Plugins like EnjinMinecraftPlugin and auto ranks or deranks players depending on what is on the Forums?

**Comment by Stormbow** [comment]
Nope.

[AutoRank](http://dev.bukkit.org/bukkit-plugins/autorank/) does.
