### ISSUE TITLE
PermissionsEx not executing Permissions

### ISSUE THREAD

**Issue by 2000nor** [PEXPlugins/PermissionsEx#2527]
Hello, I use to use PEX in version 1.6 up to 1.7.* but then i stopped for a while and decided to start a new server (Versions 1.8 -1.9) and I'm having a lot of trouble with PEX. The problem is... The plugin itself is working, it I can use all the PEX commands and everything, but the problem i have is... The server is not using the PEX permissions, it's using the default server permissions. I went into the comfig.yml of the server and changed the ' permissions-file: permissions.yml' to '  permissions-file: /plugins/PermissionsEx/permissions.yml'. To see if it would work. But it still doesnt. 

And whenever a player joins the server, They are not added to the default PEX group, their names dont even add to the list of users in PEX permissions.yml. 

I tried using different versions of bukkit - spigot, and different versions of the plugin. I tried many variations, and none seemed to work.

please help - Nor

**Comment by Stormbow** [comment]
Are you getting any errors in the console?  ([Pastebin](http://pastebin.com) your startup log, from the moment the server starts until text stops printing to the console.)

Use the default config.yml file.  Virtually no one ever needs to change anything in that file.  If you've made any changes at all to it, delete the file entirely and PEX will create it anew.  Then run the server to get the console log requested above.

**Comment by Stormbow** [comment]
I guess this problem is resolved.  No response for more than 5 days.
