### ISSUE TITLE
PEX: Prefixes not working

### ISSUE THREAD

**Issue by HewwoCraziness** [PEXPlugins/PermissionsEx#2528]
Prefixes are not working!

Here are the plugins:
![plugins](https://cloud.githubusercontent.com/assets/13814809/17907636/d8b448fc-694a-11e6-918a-62a61e184450.png)

Here is the permissions.yml file:
http://pastebin.com/AKnZCGj4

Thanks,

HewwoCraziness

**Comment by Stormbow** [comment]
You need a chat management plugin before prefixes/suffixes will display in-game.  (Most people run Spigot servers, use Essentials, and thus use EssentialsXChat (with Vault dependency).
