### ISSUE TITLE
pex command not logging on console

### ISSUE THREAD

**Issue by DaveDevil** [PEXPlugins/PermissionsEx#2532]
Hello,

I am using latest version of Pex in a 1.10 server.

I tried to search but I did not find an answer...

I have the group Admin, and a staff in this group is OP so he can use commandblocks, but can't directly use Pex.

If this Admin uses a commandblock and insert the command: "pex user playername group set Founder" then he is able to set himself to Founder group, and that's ok...

but the command isn't being logged in the console!!!

other commands like chat, teleports, give or any other command executed by commandblocks are logged in the console, but the group set no!

**Comment by zml2008** [comment]
This is not a PEX issue --- there is a feature planned for increased logging, but logging commands to console is a Sponge/Spigot/MC server thing, not a PEX thing.
