### ISSUE TITLE
Permissionsex permissions-default": 0 give all OP permission

### ISSUE THREAD

**Issue by xion87** [PEXPlugins/PermissionsEx#2534]
Hi i just tried to configure pex and grief prevention, but as in tutorial you suggest to use "permissions-default": 0" for the default group, well all players are able to use tp and all op commands, gamemode and more, i solved the issue by using permissions-default": -1, but it break griefpreventions...
Minecraft 1.8.9/forge 1890
Mods used: EssentialCmds-1.8.9-8.1.14-universal, griefprevention-1.8.9-2.0.0.69, pex-api4, pixelmon-4.3.0-beta5, spongeforge-1.8.9-1890-4.2.0-BETA-165, worldedit-sponge-mc1.8.9-6.1.4-SNAPSHOT-dist
My permission yml file: http://hastebin.com/hugopumovu.apache

**Comment by ryantheleach** [comment]
@xion87 to fix your file have you tried removing that line completely?

**Comment by xion87** [comment]
Already fixed by puting "permissions-default": 0 on griefprevention flag, thank you :)

**Comment by zml2008** [comment]
@bloodmc might take a look into this -- I'm not exactly sure what's going on here (and the permissions file link expired or something), but it seems to be dealt with for now.
