### ISSUE TITLE
[Critical Problem SQL] Database is not updated after deleting of a offline user

### ISSUE THREAD

**Issue by WhattElse** [PEXPlugins/PermissionsEx#2535]
_Hey !_

As indicated in the title, I possess a real problem with the update of the database.

When I delete a group of a user `/pex user <PlayerName> group remove <GroupName>` in the database, it is not updated, and if I wish to show these data on a Website or quite different platform, this was impossible! Would you be kind enough to find a solution ?

**Thank you very much in advance for your answer!**
_WhattElse_

**Comment by WhattElse** [comment]
@zml2008 You can help us ?

**Comment by zml2008** [comment]
That command should work, and is probably an issue with your setup considering the 1.23.x and 1.22.x codebases have been in use for years without similar issues being noticed.
