### ISSUE TITLE
Users with a mix of different permission nodes.

### ISSUE THREAD

**Issue by DataPools** [PEXPlugins/PermissionsEx#2536]
I have users in the default group with a mix of different permissions (On a per-player basis). I just switched over from a different permission plugin. What do I need to do to have these players and their permissions be saved?

Should I have createUserRecords and log-player both true?

**Comment by Stormbow** [comment]
For the most part, you'll just convert the permission nodes from your old permissions manager to PermissionsEx's format.  (This typically has to be done manually, though you could likely use Find-and-Replace features in Notepad, etc. to do this more quickly.)

You can see an example of how permissions should be laid out [right here](http://pastebin.com/8ZSHxauG).  (Be sure to follow all of the formatting styles:  indentation, spacing, apostrophe use, putting things in the right sections/order, etc.)

**Comment by DataPools** [comment]
User/group converting is already completed. Every user belongs to the default group and in addition has a mix of different permission nodes. 

Will they be saved correctly with PermissionsEx?

**Comment by Stormbow** [comment]
Yep.  They should all be fine with the default config.yml file in place.

**Comment by DataPools** [comment]
They all seem to work fine. So any change with a user-specific permission will be saved correctly?

**Comment by Stormbow** [comment]
Yep yep.

**Comment by DataPools** [comment]
Ok thank you very much.

**Comment by Stormbow** [comment]
`pex user Stormbow add permissions.*`

Use that with your name to give yourself full access to all of the PEX commands, no matter which group you're in.  (Good for troubleshooting and setting up the server.)

**Comment by Stormbow** [comment]
You're welcome. :)
