### ISSUE TITLE
[1.10.2 Sponge PEX2] Error with Promote and Demote

### ISSUE THREAD

**Issue by mister-man** [PEXPlugins/PermissionsEx#2539]
Hallo together,

I gave the permission:

			"permissions.manage": 1,
			"permissions.manage.membership": 1,
                        "permissions.user.promote.default": 1,
                        "permissions.user.demote.default": 1

but my Moderator can't promote or demote on default ladder:
       "schema-version": 4,
        "rank-ladders": {
        "default": [
            "group:default",
            "group:member"
        ]

Output in Chat: "You do not have the permission to use these command".

**Comment by mister-man** [comment]
Hallo again,

I tested it in serveral versions, but always get the output "permission denied..."

Is there a way to debug with permission must given to use a command? Or is these a bug?

**Comment by zml2008** [comment]
Use the command `/pex debug` to toggle debug mode. The permissions checked are different in PEX2.0.
