### ISSUE TITLE
Help with format

### ISSUE THREAD

**Issue by Mineleague** [PEXPlugins/PermissionsEx#2545]
Hello there. Sorry to bother you, but do you think you can do the job of converting the permissions below to .JSON as I don't know how to? Thanks, Mineleague
     PERMS: 

  "nucleus.afk.base": 1,
        "nucleus.back.targets.death": 1,
        "nucleus.back.targets.portal": 1,
        "nucleus.back.targets.teleport": 1,
        "nucleus.time.base": 1,
        "nucleus.home.base": 1,
        "nucleus.home.list.base": 1,
        "nucleus.home.set.base": 1,
        "nucleus.ignore.base": 1,
        "nucleus.info.base": 1,
        "nucleus.motd.base": 1,
        "nucleus.motd.login": 1,
        "nucleus.mail.base": 1,
        "nucleus.mail.send.base": 1,
        "nucleus.helpop.base": 1,
        "nucleus.message.base": 1,
        "nucleus.message.selectors": 1,
        "nucleus.suicide.base": 1,
        "nucleus.realname.base": 1,
        "nucleus.list.base": 1,
        "nucleus.rules.base": 1,
        "nucleus.itembuy.base": 1,
        "nucleus.itemsell.base": 1,
        "nucleus.firstspawn.base": 1,
        "nucleus.spawn.base": 1,
        "nucleus.teleport.tpa.base": 1,
        "nucleus.teleport.tpa.selectors": 1,
        "nucleus.teleport.tpaccept.base": 1,
        "nucleus.teleport.tpdeny.base": 1,
        "nucleus.teleport.tptoggle.base": 1,
        "nucleus.warp.base": 1,
        "nucleus.warp.list.base": 1,
        "griefprevention.claim.*": 1,

**Comment by zml2008** [comment]
No, add them with ingame commands (and .* permissions don't mean anything -- giving `griefprevention.claim` is the same now as what `griefprevention.claim` and `griefprevention.claim.*` combined used to be.
