### ISSUE TITLE
I Need help with PermissionsEX

### ISSUE THREAD

**Issue by Denny7m** [PEXPlugins/PermissionsEx#2546]
If players on my server break something it will say "You cant use (The block)"
I cant figure out. i have my ranks all set up: 
![image](https://cloud.githubusercontent.com/assets/22265702/18611562/4cce7b4e-7d3d-11e6-9a72-59fc92aaee11.png)

**Comment by zml2008** [comment]
There's probably a plugin blocking block breaks. Run `/pex toggle debug` and see what's being checked.
