### ISSUE TITLE
PEX JOIN LAG HELP

### ISSUE THREAD

**Issue by TheRonDee** [PEXPlugins/PermissionsEx#2548]
I'm making a server and I'm using PEX as the permissions plugin. Every time someone joins that is in a group with perms, the server lags for everyone until the person is loaded in completely. I've seen many servers fix this problem and I would like to know as well how to fix it.

**Comment by zml2008** [comment]
> I've seen many servers fix this problem and I would like to know as well how to fix it.
me too, that's why PEX 2 exists -- to fix the problems in PEX 1 that make this lag pretty unavoidable.

**Comment by TheRonDee** [comment]
Is PEX 2 available for 1.8.8? Also, can I get the link for the download?

**Comment by TheRonDee** [comment]
I got the plugin, but it seems like all the commands have been changed, can you provide a link with all the commands and what they do?
