### ISSUE TITLE
Can I disable a command without permission related to it with this plugin?

### ISSUE THREAD

**Issue by leetom** [PEXPlugins/PermissionsEx#2550]
Can I disable a command that don't have a permission related to it (like /register from LoginSecurity) ?

**Comment by Stormbow** [comment]
Generally, no.  If a plugin doesn't use permission nodes, its commands and features are open to everyone.

**Comment by zml2008** [comment]
For the most part, that's accurate.

However, for commands added by Forge mods in the Sponge version of PEX, the permission `<modid>.command.<commandname>` is assigned unless the command has its own permission checking logic.
