### ISSUE TITLE
[1.10.2 / Sponge / PEX Build #142] MySQl Dosnt work

### ISSUE THREAD

**Issue by mister-man** [PEXPlugins/PermissionsEx#2552]
Hallo together,

the last few days, I tried to get pex work with mysql. But there are only pex 1 tutorials and a wiki. So I tried  it by myself, but it seems that nothings works.

I neet pex with sql for my bungeecort environment.

Thanks

**Comment by mister-man** [comment]
Okay, it seems it isnt a bug its only a missing Documentation.

Pex Mysql:

    mysql {
        prefix=pex
        type=sql
        url="jdbc:mysql://<host ip>/<table>?user=<user>&password=<password>"
    }
default-backend=mysql

Now it works

Thnaks

**Comment by phit** [comment]
thank you, I've been looking for this everywhere!

**Comment by mister-man** [comment]
@phit

Have fun with it :)

**Comment by Gamofinn** [comment]
Where do I put this?

**Comment by Stormbow** [comment]
`1.`  Don't hijack other people's tickets.  Begin your own ticket.

`2.` Where do you put what?
