### ISSUE TITLE
the default group loses its permissions

### ISSUE THREAD

**Issue by essentiial** [PEXPlugins/PermissionsEx#2556]
Hello,

Sometimes, for reasons that I never really understood the group by default loses all permissions that I added the last 2 years (I have not seen if other groups were losing permissions).
I added or removed suffix but no worries they do not disappear.

Example: I have two UHC lobby and the number 1 were worries that permissions and looking in the logs I saw this for the number 1: http://pastebin.com/x4HpZeXa (Deploying default database scheme, scheme Database Deploying full.)

It was just enough to make /Pex reload and worries this rule ..

PS : The problem is not regular, it will appear a time occasionally. I use version 1.23.4

**Comment by Tom7653** [comment]
Having the same issue, did you find any fix for it?

**Comment by essentiial** [comment]
hello, no I just delete sql backup or other sql files. I noticed that when the problem appeared the plugin load a schematic by default and I do not know where

**Comment by essentiial** [comment]
Some help ?
 @Tom7653 if you want, after restart the server just force command /pex reload

**Comment by Stormbow** [comment]
When a server is restarted, there is no need to `/pex reload`.  The permissions are already freshly loaded by the restart.

**Comment by essentiial** [comment]
Stormbow
No, sometimes the default group loses its permissions and need to reload

**Comment by Stormbow** [comment]
A restart is where all permissions and all plugin config files are unloaded from memory and reloaded fresh.  There is no need to reload them after they have been reloaded.
