### ISSUE TITLE
NoSuchMethodError on Sponge 1.8.9-1890-4.2.0-BETA-1762

### ISSUE THREAD

**Issue by ryantheleach** [PEXPlugins/PermissionsEx#2558]
Using Pex "2.0.0-Snapshot"

https://gist.github.com/ryantheleach/cf27ffb4ff1dc54d0ac7360ef30f2816

Not sure what version of pex the server owner was running, just that it was made for "api4"

**Comment by zml2008** [comment]
This is the enjin plugin trying to hook directly into PEX, using something that isn't compatible with the version of PEX the server owner is trying to use. Talk to the enjin plugin devs about the issue, and make sure the server owner is running the latest api4 version of PEX from the forum thread.

**Comment by ryantheleach** [comment]
Thanks for the response.
