### ISSUE TITLE
prefix qui ne marche pas

### ISSUE THREAD

**Issue by Superlami** [PEXPlugins/PermissionsEx#2559]
J'ai tout bien écris dans le fichier "permisisons" de PermissionsEX et les permissions ont l'air de marcher mais le prefix je crois ne marche pas.... J'ai bien marqué "prefix: '&7[Joueur]&7'" pour le grade joueur par exemple mais le prefix n'est pas marqué quand je parle... Est-ce que j'ai mal écris ce prefix ?

**Comment by Stormbow** [comment]
Plus que probablement, vous ne disposez pas d'un plug-in de gestion de chat installé sur votre serveur. Gardez à l'esprit que les plugins comme Chatex et ChatManager ne sont pas pris en charge par PEX parce qu'ils sont tous basés sur le plugin ChatManager original et sont tous mal programmés par une multitude d'auteurs.

**Comment by Superlami** [comment]
J'ai téléchargé ChatManager depuis ce lien : https://github.com/PEXPlugins/ChatManager , j'ai cliqué sur "clone or download", puis sur "download zip" puis j'ai mis le fichier (non zip) dans mon WebFTP dans plugin, j'ai redémarré le serveur et quand je parle, il n'y a toujours pas le prefix...

**Comment by Stormbow** [comment]
Vous ne pouvez pas utiliser ce plugin avec PermissionsEx.

**Comment by Superlami** [comment]
Alors lequel ?

**Comment by Superlami** [comment]
Ah en fait je crois que même les permissions ne marchent pas

**Comment by Superlami** [comment]
pourtant dans la console, quand je me change de groupe ça me met bien "user group set" ou quelque chose comme ça

**Comment by Superlami** [comment]
qu'est-ce qui peut s'être passé ?

**Comment by Stormbow** [comment]
Vous avez programmé votre fichier permissions.yml incorrectement. Voir [cet exemple](http://pastebin.com/8ZSHxauG).

**Comment by Superlami** [comment]
j'ai copié sur ce modèle mais ça  ne marche toujours pas... voilà exactement ce que j'ai écris 




groups:
  Joueur:
    options:
      default: 'true'            
      build: 'false'               
      prefix: '&7[Joueur]&7 '
      rank: '1000'
      rank-ladder: Main
      weight: '1000'
    permissions:
    - modifyworld.*
    - essentials.kit
    - essentials.kits.guest
    - permission.node.one
    - permission.node.two
    - permission.node.three
    - permission.node.four
    inheritance: []               
  Ami:
    options:
      default: 'false'
      build: 'true'
      prefix: '&b[Ami]&b '
      rank: '900'
      rank-ladder: Main
      weight: '900'
    inheritance:
    - Joueur
    permissions:
    - -essentials.kits.guest
    - essentials.kits.member
    - permission.node.give
    - permission.node.six
    - permission.node.seven
    - permission.node.eight
  Moderateur:
    options:
      default: 'false'
      build: 'false'
      prefix: '&1[Moderateur]&1 '
      rank: '200'
      rank-ladder: Main
      weight: '200'
    inheritance:
    - Ami
    permissions:
    - -essentials.kits.member
    - essentials.kits.mod
    - permission.node.nine
    - permission.node.ten
    - permission.node.eleven
    - permission.node.twelve
  Co-fondateur:
    options:
      default: 'false'
      build: 'true'
      prefix: '&4[Co-fondateur]&4 '
      rank: '100'
      rank-ladder: Main
      weight: '100'
    inheritance:
    - Moderateur
    permissions:
    - -essentials.kits.mod
    - essentials.kits.admin
    - permission.node.thirteen
    - permission.node.fourteen
    - permission.node.fifteen
    - permission.node.sixteen
  Fondateur:
    options:
      default: 'false'
      build: 'true'
      prefix: '&4[Fondateur]&4 '
      rank: '1'
      rank-ladder: Main
      weight: '1'
    inheritance:                           
    - Co-fondateur                           
    permissions:
    - -negated.nodes.go.above.wildcards
    - -vanish.silentjoin                   
    - '*'                                 
schema-version: 1
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: Superlami
    group:
    - Fondateur
    permissions:
    - permissions.*






Il y a des fautes ici ? Dites le si vous ne voulez pas regarder trop précisément.

**Comment by Superlami** [comment]
Là ça a mal copié je vous remets le vrai texte :

**Comment by Superlami** [comment]
groups:
  Joueur:
    options:
      default: 'true'            
      build: 'false'               
      prefix: '&7[Joueur]&7 '
      rank: '1000'
      rank-ladder: Main
      weight: '1000'
    permissions:
    - modifyworld.*
    - essentials.kit
    - essentials.kits.guest
    - permission.node.one
    - permission.node.two
    - permission.node.three
    - permission.node.four
    inheritance: []               
  Ami:
    options:
      default: 'false'
      build: 'true'
      prefix: '&b[Ami]&b '
      rank: '900'
      rank-ladder: Main
      weight: '900'
    inheritance:
    - Joueur
    permissions:
    - -essentials.kits.guest
    - essentials.kits.member
    - permission.node.give
    - permission.node.six
    - permission.node.seven
    - permission.node.eight
  Moderateur:
    options:
      default: 'false'
      build: 'false'
      prefix: '&1[Moderateur]&1 '
      rank: '200'
      rank-ladder: Main
      weight: '200'
    inheritance:
    - Ami
    permissions:
    - -essentials.kits.member
    - essentials.kits.mod
    - permission.node.nine
    - permission.node.ten
    - permission.node.eleven
    - permission.node.twelve
  Co-fondateur:
    options:
      default: 'false'
      build: 'true'
      prefix: '&4[Co-fondateur]&4 '
      rank: '100'
      rank-ladder: Main
      weight: '100'
    inheritance:
    - Moderateur
    permissions:
    - -essentials.kits.mod
    - essentials.kits.admin
    - permission.node.thirteen
    - permission.node.fourteen
    - permission.node.fifteen
    - permission.node.sixteen
  Fondateur:
    options:
      default: 'false'
      build: 'true'
      prefix: '&4[Fondateur]&4 '
      rank: '1'
      rank-ladder: Main
      weight: '1'
    inheritance:                           
    - Co-fondateur
    permissions:
    - -negated.nodes.go.above.wildcards
    - -vanish.silentjoin                   
    - '*'                                 
schema-version: 1
users:
  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: Superlami
    group:
    - Fondateur
    permissions:
    - permissions.*

**Comment by Superlami** [comment]
Je ne sais pas pourquoi mais ça ne veut pas tout bien copier (donc tout ce qui n'a pas marché c'est les espaces entre les lignes qui n'y sont pas et dans les permissions de Co-fondateur j'ai bien mis le '*' et dites  le juste si vous ne voulez pas regarder ce que j'ai écris....

**Comment by Stormbow** [comment]
Vous ne l'avez pas personnaliser le fichier exemple que je vous ai donné des autorisations applicables à votre serveur, si bien sûr rien ne fonctionne.

**Comment by Superlami** [comment]
c'est à dire je dois mettre les "#" ?

**Comment by Superlami** [comment]
Mais sinon j'ai suivi l'exemple à la lettre, j'ai juste changé ce qu'il fallait (à part les permissions, je le ferai à la fin)

**Comment by Stormbow** [comment]
Je parle de nœuds d'autorisation ther. Vous ne disposez pas de tous les nœuds d'autorisation qui sont spécifiques aux plugins de votre serveur dans le fichier permissions.yml que vous avez collé ici, si bien sûr rien ne fonctionne comme vous attendre à ce qu'il devrait. Les "#" commentaires dans l'exemple ne doivent pas être dans votre dossier, et ne fera pas mal quoi que ce soit si elles sont en elle; ils expliquent simplement comment les choses doivent être faites pour que le fichier fonctionnera correctement.
