### ISSUE TITLE
Question with pex2.0

### ISSUE THREAD

**Issue by weltandmelt** [PEXPlugins/PermissionsEx#2562]
I am wondering if there is away to allow ops, mainly because the owner and my self would need permission for every thing, and also it says theres conversion from bucket, would i just have to input my old one into the new permissions.json?

**Comment by zml2008** [comment]
Set the permissions file to your old permissions.yml (in the permissionsex.conf file), and the file will be automatically converted.

**Comment by weltandmelt** [comment]
ok, thanks.
