### ISSUE TITLE
Not able to do anything. Pex2.0

### ISSUE THREAD

**Issue by weltandmelt** [PEXPlugins/PermissionsEx#2566]
http://pastebin.com/jCy6Rmm9 here is the .json. my rank and the owners rank cant do anything now, i thought i had it originaly for him and i to have all perms '*' but its not working now, i orriginaly accidently set the owner rank and server manager rank to be default by accident, and then when i changed it we have no permissions.

**Comment by zml2008** [comment]
Read the 2.0 getting started guide. The permission default (the `def` command) is not whether the group is default, it's what the value for any unset permission should be. That means that if the default in 2.x is true, it's equivalent to what `*` used to do in 1.x (`*` has no meaning in 2.x)

**Comment by weltandmelt** [comment]
ok thanks

**Comment by weltandmelt** [comment]
i get confused with the commands, i like editing files and configs more. and still havent gotten to pex2.0's it did fix it.
