### ISSUE TITLE
Pex with Bungeeperms

### ISSUE THREAD

**Issue by Jack166** [PEXPlugins/PermissionsEx#2569]
Hello, (Bad English)
I have a Bungeecord server, but is there a permission to assign a group to a player without typing in a command? So I can add that permission to my Bungeeperms permission folder. I can use MySQL, but I want that players with a rank can fly in the lobby but not in games. Otherwise I neef to type in every server the command to assign a player to a group, but when there is a permission (ex: permissionsex.group.(groupname)) the player Will be directory assigned of have the perms of that group.

Thx,
Jack

**Comment by LemonLight** [comment]
Hi Jack, (I can speak French/Spanish/English)

By my side, I'm using mysql and it works perfectly. The only thing I do is that I put permissions per worlds. The lobby servers has in general only one world. So, to permit the VIP (for examples) to fly in lobby, I use this : 

VIP:
    inheritance:
    - Citoyen                                                               # They have all "Citoyen"'s permissions
    options:
      rank: 996
    permissions:
    - essentials.me
    - essentials.hat
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.magic
    - essentials.joinfullserver
    worlds:
      lobby_world:                                                        # But on this world, they can fly
        permissions:
        - essentials.fly
        - doublejump.use
        - nocheatplus.checks.moving.creativefly

Regards,
:)

**Comment by Stormbow** [comment]
OP has never responded.  Case closed, I guess.
