### ISSUE TITLE
[Improvement] Show message which permission is missed

### ISSUE THREAD

**Issue by yololetsplay** [PEXPlugins/PermissionsEx#2570]
Hey there :]
If now an user do not have permission, it just says no permission.
Can u add the following:
"Missing permission my.command.test" if enter an command and you do not have the permission.

Greetz,
yololetsplay

**Comment by Stormbow** [comment]
This isn't necessary.  You have [Debug Mode](https://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2) to show you all of the missing permissions.

**Comment by yololetsplay** [comment]
Well, the debug mode does not give an output, if I enable debug mode for an player.
Btw. the thread is outdated and from bukkit, the right command is /pex debug USER now.

**Comment by zml2008** [comment]
The permission denied message is controlled by plugins checking permissions, not by PEX. The per-user debug mode was disabled in 1.x and does not exist in 2.x. In 2.x, debug mode can filter by the content of the permission being checked though.
