### ISSUE TITLE
How to remove Prefix from everybody?

### ISSUE THREAD

**Issue by Darkfield** [PEXPlugins/PermissionsEx#2571]
Hello,

```
for(PermissionUser pu : PermissionsEx.getPermissionManager().getUsers()){
                    pu.setPrefix(null, null);
}
```

Doesn't work, why?

[PermissionsEx] version [1.23.4]
Spigot 1.8.9 with protocolhack.

**Comment by zml2008** [comment]
The prefix was set from a group maybe? You have to change groups too.

**Comment by Darkfield** [comment]
It works now, but server crashes if I run it twice. What's the problem? Btw how to remove all users from different groups? But leave their suffix and own permissions.

**Comment by Darkfield** [comment]
[16:18:04 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[16:18:34 WARN]: [PermissionsEx] All backend tasks not completed after 30 seconds, waiting 2 minutes.
