### ISSUE TITLE
/pex wont work

### ISSUE THREAD

**Issue by ewm2000** [PEXPlugins/PermissionsEx#2576]
I have the latest of the sponge builds and the /pex command or any pex command for that matter wont work

**Comment by zml2008** [comment]
Define "won't work". What happens when you try?

**Comment by ewm2000** [comment]
When I type /pex it says command not recognized as if the plugin wasn't installed.  But when i do /sponge plugins it shows up and its green showing that its active. The console even shows it starting up. If need be I can get the logs.

**Comment by LemonLight** [comment]
Does your file as the correct rights ? I mean chmod and chown

chmod 771 your_pex.jar
chown user:group your_pex.jar
The user/groups used has to be the same one that starts the server

**Comment by ewm2000** [comment]
Whenever i upload perms get done automatically and this has never been a problem before. It only started happening recently.

**Comment by ewm2000** [comment]
I verified and all file permissions are correct and I have done what was stated here
chmod 771 your_pex.jar
chown user:group your_pex.jar
The user/groups used has to be the same one that starts the server

and still same problem
