### ISSUE TITLE
API prefix colors??

### ISSUE THREAD

**Issue by Robpizza** [PEXPlugins/PermissionsEx#2585]
So i use the API in my plugin but now i have a problem..

`PermissionUser user = PermissionsEx.getUser(player);
			String prefix = user.getPrefix();
			event.setJoinMessage("" + ChatColor.BLUE + ChatColor.BOLD + "Welcome back " + prefix + ChatColor.WHITE + player.getName());`

this is my code. 
this is what i get ingame ;l

![7f5bbc85d0d04b56970202b38a7dcaa3](https://cloud.githubusercontent.com/assets/12848142/20458965/dceea1a8-aeb2-11e6-8c3c-413f41391751.png)

Thanks for your help!

Yours sincerely,

Robpizza

**Comment by Robpizza** [comment]
Nobody know how to fix this ;l?

**Comment by zml2008** [comment]
& is not the chat color character, § is. Most chat plugins just convert automatically, yours would have to as well.

**Comment by Robpizza** [comment]
Thanks ill try this one 👍
