### ISSUE TITLE
Timed permissions are not saving

### ISSUE THREAD

**Issue by cloakfox** [PEXPlugins/PermissionsEx#2587]
Pex version: Latest
This server is running Paper version git-Paper-819 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

The issue:
My players can unlock certain titles (temporary) by spending points on them.
This is the command I run:
/pex user %player% timed add deluxetags.tag.Superman 1209600 world
The 1209600 stands for 2 weeks in seconds.

The issue how ever is that when the player logs out. And joins back, his permission is gone.
I have tried running /pex reload right after the "/pex user %player% timed add deluxetags.tag.Superman 1209600 world" command to see if that helps, but it didnt.

PermissionsEx folder (Inludes config.yml and permissions.yml):
http://www.mediafire.com/file/e0if5fo9ge9hc5t/PermissionsEx.zip

Website: www.mcfoxcraft.com
IP: mcfoxcraft.com
Gamemode having the issues: /creative
Skype: cloakfox (From The Netherlands)

Plugins on creative: 
Plugins (59): PlaceholderAPI, Vehicles, PlugMan, ParticleTrails, BetterChairs, ChatReaction, UnglitchMe, DeluxeTags, VoxelSniper, CraftiRedstone, FoxcraftVP, WelcomeWarpSigns, BossShop, ads, HideStream, AsyncWorldEditInjector, WorldEdit, ClearLag, AutoMessage, ChatControl, BuycraftX, Votifier, BannerBoard, ProtocolLib, NoCheatPlus, LibsDisguises, Famous, Foxstats, AsyncWorldEdit, FoxVehiclesRemoval, PermissionsEx, FeatherBoard, GAListener, CommandScheduler, Vault, ProtocolSupport, Lift, XenSync, HolographicDisplays, PlotSquared, WorldGuard, CommunityBridge, VoxelSniperRegions, boosCooldowns, PlayerHeads, EasyColorChat, Essentials, MarriageMaster, LiteBans, WhatIsIt, EssentialsChat, EchoPet, RedstoneClockPreventer2, MiniaturePets, EssentialsAntiBuild, EssentialsSpawn, TitleManager, GAListenerTitles, AdPoints

Thanks,

Cloakfox

**Comment by zml2008** [comment]
This is by design. Timed permissions are transient. If you want something that is persisted to the permissions file, use timed groups, assigning a group with a single permission.
