### ISSUE TITLE
Too Many Arguments? 

### ISSUE THREAD

**Issue by Reckz** [PEXPlugins/PermissionsEx#2588]
Server thread/INFO Usage: /pex [debug|reload|import|ranking|[--context|--contexts|-c] [-transient] subject permission-default|delete|options|info|permission|parents|[-transient] subject-type list [filter]]
27.11 15:22:45 [Server] Server thread/INFO Too many arguments!
27.11 15:22:45 [Server] Server thread/INFO [nucleus]: Server ran the command: /pex group Admin create

Why would it say that for the simple pex command?

**Comment by zml2008** [comment]
The error messages are generally wrong at the moment -- this one is happening because `create` is not a command that exists. Just like you could do in 1.x, you can just act like any user or group you want to edit already exists and PEX will create them as necessary.
