### ISSUE TITLE
Autorank integration

### ISSUE THREAD

**Issue by Lammendam** [PEXPlugins/PermissionsEx#2590]
Hi.

I using an auto-ranking plugin that calls Autorank. The ranks and groups are properly configured. I need to "freeze" ranking groups on second place of player's group list 'cause I have parallel group type for donators, admins, moderators. It's a primary group.

How can I freeze the primary group on first place of list even if Autorank tries to move ranking (second) group on first place instead primary group?

**Comment by Lammendam** [comment]
My suggestion: please, add to command
pex user <user> group add <group> 
the required parameter that handles position  where to add the specific group in player group list, such as:
pex user <user> group add <group>  <up | down> 
Or doing that optional, when player not entered a position parameter plugin will add specified group using parameter from config, that already exist.

**Comment by Stormbow** [comment]
You should be using weight values and ladders.
