### ISSUE TITLE
Permission Failure of some sort...

### ISSUE THREAD

**Issue by KyuubiFox** [PEXPlugins/PermissionsEx#2593]
http://prntscr.com/ddxf0s
Im using version 1.23.4
on spigot 1.10.2
for some reason when i add permissions they dont always work. 
I added 1 permission server times manually and it didnt work until i added through command.
there was no difference in the way i added except the position i added was at the end of that groups permissions list. pex added it to the front of the line.
On a second occasion i noticed a few permissions i added manually recently, just disappeared. figuring i probably just messed up when i was re-uploading the file or something. well when i added the permissions back via command this time (screenshot above) its now telling me that i dont have permission and that the permission is null when using check. these permissions are correct and you can confirm for youself here.
https://www.spigotmc.org/resources/withdraw-advanced.8465/
Thats my story... heres my permissions file.
http://hastebin.com/sisiwanitu.php

**Comment by Stormbow** [comment]
Your file follows an outdated format from many years ago.  Follow [this example](http://pastebin.com/8ZSHxauG) and it'll be fine.

**Comment by KyuubiFox** [comment]
you didnt use worlds in that permissions example does it still exist?

**Comment by Stormbow** [comment]
The main problem is actually just your options settings and having an inheritance in ever group.  (The very first group in your file, for example, has no inheritance and 'build: true' outside of the 'options:' section.)

**Comment by Stormbow** [comment]
It also appears that you are trying to run a server with the server.properties file set to online-mode: false  (or you just have a lot of users that haven't been on the server since Minecraft 1.7.9 I think it was, when UUIDs were first added).  PEX won't function with that setting.  If you're attempting to run a Bungee server and someone told you that "must" be false, I'd head to the Bungee forums and find out how to set up the server then.  (I personally have no experience with it, but it's been an issue to others in the past.)

**Comment by Stormbow** [comment]
And you're missing the schema-version: line, which goes above the "users:" section.

**Comment by KyuubiFox** [comment]
if i leave online-mode false is that gonna hurt anything majorly because if i remember correctly when you change that it tends to mess with the uuid's of players and that will really kill my players islands on skyblock like it has done before

**Comment by KyuubiFox** [comment]
there also were a bunch of other issues i found while going through the file i went through and fixed them and changed the layout to match what that pastebin of yours had bad it seems some of it just reverted back i had schem version before users and now it got forced back down to the bottom.  i put the build: true inside the options and it moved under the permissions but above the world permissions. http://hastebin.com/oreruyatev.php

**Comment by Stormbow** [comment]
For as long as online-mode=false is in the server.properties file, PEX will not function properly as offline servers are not supported by PEX.

Depending on your server host (which seems to be one of the problematic ones), you will have to stop the server entirely for changes in the permissions.yml file to actually get applied to the server.  To minimize downtime, copy the entire permissions.yml file that's on the server to your desktop, make the changes required, save the file, stop the server, upload the file (replacing the existing file), and start the server again.

**Comment by KyuubiFox** [comment]
ive never had to do that

**Comment by Stormbow** [comment]
You're welcome to go talk to the people at Bungee on how to setup your server then.
