### ISSUE TITLE
Not Workin

### ISSUE THREAD

**Issue by JustEmrePvP** [PEXPlugins/PermissionsEx#2594]
Is my script not right? I need a answer right away beacuse im opening a server and it didn:T work.
Here is the script:

groups:
  Default
    default: true
    build: true
    prefix: '&7[Silver]&f'
    permissions
    - essentials.help
    - modifyworld.chat
    - modifyworld.*
    - essentials.spawn
  GoldNova
    build: true
    inheritance:
    - Default
    prefix: '&e[Gold Nova]&f'
    permissions:
    - essentials.repair
    - essentials.ignore
  Supreme:
    build: true
    inheritance:
    - Default
    prefix: '&b[Supreme Master]&7'
    suffix: '&7'
    permissions:
    - essentials.feed
    - essentials.hat
    - essentials.ignore
    - essentials.repair
    - essentials.back
  Global:
    build: true
    inheritance:
    - Default
    prefix: '&1[GlobalElite]&7'
    suffix: '&7'
    permissions:
    - essentials.repair
    - essentials.heal
    - essentials.ignore
    - essentials.feed
    - essentials.back
    - essentials.hat
  Moderator:
    build: true
    inheritance:
    - Default
    prefix: '&b[Moderator]&7'
    suffix: '&7'
    permissions:
    - essentials.repair
    - essentials.heal
    - essentials.fly
    - essentials.kick
    - essentials.mute
    - essentials.vanish
  Admin:
    build: true
    inheritance:
    - Moderator
    prefix: '&d[&cAdmin&4]&e'
    suffix: '&7'
    permissions: 
    - essentials.gamemode
    - essentials.ban
    - essentials.unban
    - essentials.ipban
    - essentials.unipban 
    - essentials.pardon
    - essentials.enchant
  CoOwner:
    build:true
    inheritance:
    - Admin
    prefix: '&c[CoOwner]&e'
    suffix: '&b'
    permissions:
    - '*'
  Owner:
    build:true
    inheritance:
    - Admin
    prefix: '&l&4[Owner]&e&l'
    suffix: '&b'
    permissions:
    - '*'

**Comment by Stormbow** [comment]
Compare your file to [this example](http://pastebin.com/8ZSHxauG).  You'll see you have many things in the wrong place, such as no `options:` section at all and missing inheritances, as well as missing colons after your group names and improper empty permission sets.  It should be `permissions: []` not permissions: and the next line - ''.

**Comment by Stormbow** [comment]
After you fix all of the basic formatting problems, [Parse your file](https://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=3) to see what other errors you may have made.

**Comment by JustEmrePvP** [comment]
Thank you but can you send me the 1.8 version of this example? Thanks.

**Comment by Stormbow** [comment]
Same example, minus the part about the `default: true` group (Guest, in the example) being required to have an inheritance.

**Comment by Stormbow** [comment]
I'm guessing this is resolved.
