### ISSUE TITLE
Subgroups

### ISSUE THREAD

**Issue by Loonyy** [PEXPlugins/PermissionsEx#2595]
Hey, I've transferred from GroupManager to PermissionsEx and one feature in GroupManager that I used was Subgroups. 

Subgroups was basically like inherit. Players can be in a group but inherit the permissions of another group. I'm not sure how to do this with PermissionsEx; I tried the `/pex user Loonyy group add Helper` but that either seems to put me in the Helper group or add the group to me but give me the Helper prefix, it's a little unreliable.

Any help?

**Comment by Stormbow** [comment]
See [this example](http://pastebin.com/8ZSHxauG) first.

If Stormbow joined the server and was promoted to the group named "Member", and "Member" inherits permissions from the group named "Guest" (which Stormbow was in originally as a new person on the server; lines 29 and 30), Stormbow gains all of the permissions of both groups.  Stormbow wouldn't need to actually be a member of both groups.

Is that was you're asking about?

**Comment by Loonyy** [comment]
No, but thank you for the reply.

I already have group inherits set up correctly. I'm wanting player-group inherits. 
I need player group inherits because if I hire a player as Moderator, and they donate for the highest rank (Emperor) with lots of permissions in that Emperor group, I want their main rank to continue to be Moderator but I want that player to inherit the Emperor rank so they still have access to Emperor commands and permissions. Does that make sense?

**Comment by Loonyy** [comment]
Basically;
A player can be in multiple groups at once but only one specific groups' prefix shows up.

**Comment by Stormbow** [comment]
That's accomplished with group add and weight values.  See the example I linked above.

**Comment by Stormbow** [comment]
"Loonyy" would start in the "Guest" group of that example.  If you wanted them to also be an Admin, you'd type `/pex user Loonyy group add Admin` and they'd now be a member of 2 groups.

**Comment by Loonyy** [comment]
I've just setup all the ranks and weights for each group and the wrong prefix for groups on users are showing up still. I am using the latest version of PEX but I'm on Spigot 1.11

**Comment by Stormbow** [comment]
Copy your full permissions.yml file to [Pastebin](http://pastebin.com) for me to look at.

**Comment by Loonyy** [comment]
Here you go:
http://pastebin.com/VBRSc1EN

**Comment by Stormbow** [comment]
Which user is getting the wrong prefix?  Which prefix should they be getting?

**Comment by Loonyy** [comment]
Every group I've tried it with, it doesn't work.

I've mainly been doing it with my staff ranks and donation ranks, here's some examples:
Moderator and Emperor.
Architect and Defender.
Helper and Knight.

**Comment by Loonyy** [comment]
Also, when I use the PEX command in game to check the weight and rank, it's all listed as normal.

**Comment by Stormbow** [comment]
Many, many problems in that file that I can see so far:

• Groups should not have the same rank values.

• Groups should not have the same weight values.

• All of your `option:` sections are not indented properly.

• All of your `permissions:` sections are indented too far.

• All of your weight values are backwards.  Owner should be `1` and whichever single group has `default: true` should be the highest number, typically `1000`.

**Comment by Loonyy** [comment]
Brb while I /suicide because I now have to fix all this

- Thanks for the support :)

**Comment by Stormbow** [comment]
You're welcome.  Let me know— after you've gotten it all fixed —if you run into other problems.

**Comment by Stormbow** [comment]
(You can still reply here.  It's just not on the 'open' tickets list now.)

**Comment by Loonyy** [comment]
I fixed the issues in the config; 
The issue I can see right now is that Emperor is overriding all other groups, meaning if I add someone the Moderator group and Emperor, the Emperor prefix will show.

Here's my Permissions file:
http://pastebin.com/tdgVAgES

**Comment by Stormbow** [comment]
In the server.properties file on the server, is online-mode set to true?

**Comment by Loonyy** [comment]
Yes it is.

**Comment by Stormbow** [comment]
Are there any error messages at all in the startup log?

**Comment by Loonyy** [comment]
Nope, no errors.

**Comment by Stormbow** [comment]
Show me the full file, including all of the user information.  Upload it to [Dropbox](https://www.dropbox.com/) or something if it's too long to paste.

**Comment by Stormbow** [comment]
Nevermind.  I see the problem.

      weight: ‘500'

is not encapsulated in apostrophes.

    weight: '500'

**Comment by Loonyy** [comment]
Sigh. Longest sigh of my life. /suicide x10.

Thanks for all the helper, mind answering one more question?
Is there a way to easily add someone a prefix from two groups without doing it manually?
So I can just give someone the prefix from builder and helper rank so it would look like:
[Builder] [Helper] Loonyy

**Comment by Stormbow** [comment]
That, unfortunately, would be entirely up to whatever chat management plugin you use.

Personally, I've always stayed away from double and long prefixes displayed in-game because they clutter up chat too much, so I'm not 100% sure on how to do it.  I know others have done it, but I don't know how and haven't done it myself.

**Comment by Stormbow** [comment]
My [Prefix/Suffix Guide]9https://dev.bukkit.org/bukkit-plugins/permissionsex/forum/69856-basic-prefix-suffix-tutorial/) only details setting up one prefix.

**Comment by Loonyy** [comment]
Yeah me too, it's only for double staff members (Helper and Builder) - although I might use suffix instead. 

Thanks for all your help :)

**Comment by Stormbow** [comment]
You're welcome. :)  Have fun.
