### ISSUE TITLE
[Suggestion] Option to split rank and user permissions into seperate flatfiles

### ISSUE THREAD

**Issue by AussieWarGod** [PEXPlugins/PermissionsEx#2597]
Not sure how hard it would be but this would be invaluable to our large server networks where we have 40+ servers and editing permissions currently has to be done via a synchronization command which doesn't always work (one of the servers might be mid-restart). 

It would be much easier to manually edit the rank flat file and upload it to all the servers at once without having to do surgery on each individual file to retain user ranks.

Thanks for your time

**Comment by zml2008** [comment]
A multi-backend that allows splitting permissions into different data stores (multiple files, file and sql, separate sql, etc) is in development for pex2
