### ISSUE TITLE
[Suggestion] Vanilla OP permission node

### ISSUE THREAD

**Issue by AussieWarGod** [PEXPlugins/PermissionsEx#2598]
Would it be possible to add a node to give a rank OP permissions per vanilla minecraft or allow the /op command to be used?

We have mods such as minetweaker and at least 2 others who's commands require vanilla OP permissions to run commands or interact with admin functionalities. (one example is a vault that will instakill anyone unless they are the owner or an OP) 

A workaround for those of you who have not found it yet and are looking is to run /minecraft:op <player> to give OP to that person (or yourself)

Just looking to make things a bit easier and allow you to integrate vanilla OP perms the way you would like them rather than them being bypassed by OP.

Thanks for your time.

**Comment by zml2008** [comment]
Any change to vanilla op functionality is done in Sponge -- PEX doesn't touch server internals. Sponge already has functionality to redirect command op checks to use permissions instead, and beyond that mod developers should be encouraged to use the forge permissions API (which Sponge plans to act as a bridge for between the forge API and sponge permissions plugins).
