### ISSUE TITLE
PeX version

### ISSUE THREAD

**Issue by needwalter** [PEXPlugins/PermissionsEx#2601]
hi , i would like to know what version should i use with spigot 1.11 to update my server?
i was using a version that work with 1.9.4 , is the plugins is up to date ?
Could you give me the last version ?

Thanks you very much !

walt'

**Comment by Stormbow** [comment]
[PermissionsEx 1.23.4](https://dev.bukkit.org/projects/permissionsex/files/909154) will work on 1.11 servers.
