### ISSUE TITLE
[Feature request] Cross server permissions

### ISSUE THREAD

**Issue by AussieWarGod** [PEXPlugins/PermissionsEx#2602]
This is just a concept, but imagine being able to manage all permissions from a single server on a network with pex.

The idea would be to have pex push and pull from a database where all ranks, users and other information is stored. 
I imagine there are a few ways this could be done and i am willing to provide more ideas if you think this is a good idea.

We use a plugin called synx for all our cross server plugins that you could integrate this with.

Let me know what you think and i can fill out the idea a bit more if you like it.

Thanks for your time.

**Comment by Haarolean** [comment]
Why can't you do the same with sql backend?

**Comment by SwiftSwamp** [comment]
I believe he's suggesting this;
One database to house all players ranks / permissions so that's shared and changing it on one server will update it on all.
Then each server has the flat file to manage groups for different permissions for each group for each different server.

**Comment by theJ3H** [comment]
This is already possible by adding a specific permission to each group globally and than using bukkit's permissions.yml (http://wiki.bukkit.org/Permissions.yml) to add per-server permissions to each group.
Not the most elegant solution, but it works..

**Comment by Stormbow** [comment]
@theJ3H : None of that is for PermissionsEx.  That is the permissions.yml file in the root directory and unrelated to PEX.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
