### ISSUE TITLE
Removing second player group

### ISSUE THREAD

**Issue by Lammendam** [PEXPlugins/PermissionsEx#2603]
Player have two groups in the list. When player do a re-login on server, his second group is disappear from his group list each time when he login. No matter which way using to add/set player's groups (manually in permissions,yml, via command or by 3rd-party plugins e.g. Autorank), result is same.
PEX 1.23.4
Spigot 1.11

**Comment by Stormbow** [comment]
If you are using Timed groups or permissions, I think they always disappear when the player logs out.

**Comment by Lammendam** [comment]
Ain't used timed groups or perms. Tested on clean server without other plugins, just add/set player's group.

**Comment by Lammendam** [comment]
Yes, I've fixed this by disabling permission check in authme config. All works fine.

**Comment by Stormbow** [comment]
Good to know it wasn't a PEX problem.
