### ISSUE TITLE
pex doesn't work

### ISSUE THREAD

**Issue by xahmedxx** [PEXPlugins/PermissionsEx#2604]
when a new player log in to my server it doesn't add him to the default group.
prefixes doesn't work.

this is my permissions file:

groups:
  Member:
    Options:
      default:true
    permissions:
    - modifyworld.*
    - authme.player.login
    - authme.player.changepassword
    - authme.player.email.add
    - authme.player.email.recover
    - authme.player.register
    - chestcommands.command.open
    - chestcommands.open.example.yml
    - hubthat.spawn
    - hubthat.hub
    - hubthat.gotoworld
    - hubthat.nohubdelay
    - hubthat.nospawndelay
    - plots.auto
    - essentials.heal.cooldown.bypass
    - essentials.balance
    - essentials.pay
    - essentials.ignore
    - essentials.msg
    - essentials.realname
    - essentials.ban.notify
    - essentials.kick.notify
    - essentials.mute.notify
    - chatex.allowchat
    inheritance: []
  Youtuber:
    Options:
      prefix:'&fYou&4Tuber:&7  '
    permissions:
    - essentials.hat
    - essentials.heal.cooldown.bypass
    - essentials.nick
    - essentials.nick.color
    - chatex.allowchat
    inheritance: []
  Vip:
    Options: 
      prefix:'&bVIP:&c  '
    permissions:
    - essentials.hat
    - essentials.heal.cooldown.bypass
    - essentials.nick
    - essentials.nick.color
    - chatex.allowchat
    inheritance: []
  Legend:
    Options:
      prefix:'&9&lLEGEND:&1  '
    permissions:
    - essentials.fly
    - essentials.fly.safelogin
    - essentials.hat
    - essentials.heal.cooldown.bypass
    - essentials.workbench
    - essentials.msg.color
    - essentials.nick
    - essentials.nick.color
    - essentials.clearinventory
    - chatex.allowchat
    inheritance: []
  Builder:
    Options:
      prefix:'&a&lBUILDER:&a  '
    permissions:
    - essentials.hat
    - essentials.fly
    - essentials.fly.safelogin
    - essentials.heal.cooldown.bypass
    - essentials.msg.color
    - essentials.nick
    - essentials.nick.color
    - essentials.clearinventory
    - chatex.allowchat
    inheritance: []
  MOD:
    Options:
      prefix:'&6&nMOD:&e&l  '
    permissions:
    - essentials.fly
    - essentials.fly.safelogin
    - essentials.god
    - essentials.hat
    - essentials.heal
    - essentials.heal.cooldown.bypass
    - essentials.heal.others
    - essentials.speed
    - essentials.speed.fly
    - essentials.speed.walk
    - essentials.workbench
    - essentials.afk
    - essentials.afk.auto
    - essentials.chat.ignoreexempt
    - essentials.msg.color
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.ban
    - essentials.ban.exempt
    - essentials.clearinventory
    - essentials.kick
    - essentials.kick.exempt
    - essentials.mute
    - essentials.mute.exempt
    - chatex.allowchat
    inheritance: []
  Owner:
    options:
      prefix:'&4&lOwner:&4  '
    permissions:
    - '*'
    inheritance: []
schema-version: 1
users:
  4ec7f16e-7fb6-36de-9811-758677d84416:
    group:
    - Owner
    options:
      name: abu_ali
      last-login-time: '1481828286'
      last-logout-time: '1481828275'

help me please.. :)

**Comment by Stormbow** [comment]
It's `default: true` not `default:true`.  Add a space in there.

**Comment by xahmedxx** [comment]
ok thx

**Comment by xahmedxx** [comment]
but what about the prefixes they doesn't work

**Comment by Stormbow** [comment]
To get those working, you need a chat management plugin.

Since almost everyone uses [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/), they use [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) which goes with it— and [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) is a dependency of EssentialsXChat, so you'd need that too.

**Comment by xahmedxx** [comment]
i downloaded essentialsxchat but it still doesn't work
another thing to say is when i add a prefix to the default group the whole plugin stops

**Comment by Stormbow** [comment]
You haven't set up EssentialsXChat correctly— and you're on your own with that since the Bukkit website deleted all of my Guides —and you made a mistake in your permissions.yml file when you added the prefix.

**Comment by xahmedxx** [comment]
i looked up essentials chat tutorial and i did it correctly but it still not working.
and it still doesn't add players to the default group even after i added the space.
please help.

**Comment by Stormbow** [comment]
In your server.properties file, what is the current `online-mode` setting?

**Comment by xahmedxx** [comment]
its offline

**Comment by Stormbow** [comment]
`online-mode: false`?  That would be why the server doesn't work.

PEX does not support offline servers.

**Comment by xahmedxx** [comment]
is there any way to make support offline servers?

**Comment by Stormbow** [comment]
Nope.  Since offline servers are typically used by people playing on hacked/illegal copies of Minecraft, PEX will never support them.
