### ISSUE TITLE
Please add shortened commands:

### ISSUE THREAD

**Issue by Tzzzt123** [PEXPlugins/PermissionsEx#2605]
I would love to have shortened command because /pex --- ... ___  is kinda difficult and makes the setup difficult. I already made them with my alias plugin but it would be awesome to have them implemented in future pex versions as it makes fixing/setting up permissions much easier.
If the devs need my suggestions for the commands i can put my alias pex part in pastebin.
Thanks alot. Tzzzt123

**Comment by zml2008** [comment]
clarity > conciseness -- server admins can create aliases for the commands they use most frequently.
