### ISSUE TITLE
Please Help Me !

### ISSUE THREAD

**Issue by falahater** [PEXPlugins/PermissionsEx#2606]
Hi reader,

I've been using PermissionEx for minecraft 1.8, all setup and work, players join and can use commands, prefix works, but after a restart the server breaks and permissionex no longer works, no permissions are granted to default players and prefixes Disappear!

Need help

Thank you!

**Comment by Stormbow** [comment]
Any errors in the console log?

**Comment by Stormbow** [comment]
Hmmm...  Must not be a problem anymore.

**Comment by Stormbow** [comment]
@falahater has not responded.  Ticket closed.
