### ISSUE TITLE
Where can  I download Pex 2.0 for Spigot

### ISSUE THREAD

**Issue by KingTux2** [PEXPlugins/PermissionsEx#2608]
I want to know where I can download Pex 2.0 for Spigot.

**Comment by pavog** [comment]
I do not think that it is released yet but you can download the sourcecode and compile it.

**Comment by KingTux2** [comment]
OK, I will. thx for the help.

**Comment by pavog** [comment]
Btw I found the server where you can download the artifacts:
http://pex-repo.aoeu.xyz/ninja/leaping/permissionsex/

**Comment by zml2008** [comment]
Looks solved
