### ISSUE TITLE
Invalid Plugin Description

### ISSUE THREAD

**Issue by RealmShift** [PEXPlugins/PermissionsEx#2610]
Every second time I start up my server, the compiler casts an InvalidPluginException with the specific error Invalid Plugin Description. I don't understand why this is happening, but I can't edit this and don't know what to do. I've tried a couple different versions of PEX for Spigot 1.8, but it keeps saying the plugin's description is invalid on the second startup. It also mentions something about an error trying to unzip a file, I'm assuming it is referring to the plugin files. I'm running Spigot 1.8.8 with Java SDK 1.8, and config file should be set up correctly. Any help would be appreciated.

**Comment by zml2008** [comment]
Sounds like a problem on your server -- PEX isn't doing anything new on our side, so somehow the files on your disk are being corrupted.

**Comment by RealmShift** [comment]
Yeah, it would make sense. Might try using a different Spigot file or removing some old files. Thanks.
