### ISSUE TITLE
pex disappearing when /reload, /reboot, /stop or /restart

### ISSUE THREAD

**Issue by wm5000** [PEXPlugins/PermissionsEx#2611]
Whenever I add a new plugin, I usually do /rl (short for reload). Same thing happens for the rest of the commands said in the title. Every time after I do one of the commands in the title, the same thing happens. What I do is I now drag and drop the file into the plugins folder. Then another reload, it'll show up. It's starting to annoy me as well as the players.

**Comment by Stormbow** [comment]
Which version of Minecraft and PEX are you using?

**Comment by wm5000** [comment]
Minecraft - 1.8.8
Pex - Tried all 1.8 versions, still does it

**Comment by Stormbow** [comment]
Show me your console log.

**Comment by wm5000** [comment]
I've figured it out.
1. I changed from pex minecraft version to 1.11, and 1.8 was disappearing because of the other chat plugins I use. Such as TagsGUI, ItemHover, DeatMessages.

**Comment by MeninoDuu** [comment]
Someone help me when I close and I open the server Pex some stops working Somebody help me

**Comment by Stormbow** [comment]
Don't hijack other people's threads.  You already have your own ticket posted.
