### ISSUE TITLE
Console ERROR

### ISSUE THREAD

**Issue by iAxyy** [PEXPlugins/PermissionsEx#2613]
Version I use: Paperspigot 1.7/1.8

ERROR:
20.12 21:38:28 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
20.12 21:38:28 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:924)
20.12 21:38:28 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1087)
20.12 21:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:773)
20.12 21:38:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
20.12 21:38:28 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
20.12 21:38:28 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:308)
20.12 21:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.reload(CraftServer.java:875)
20.12 21:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:399)
20.12 21:38:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:481)
20.12 21:38:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
20.12 21:38:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
20.12 21:38:28 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
20.12 21:38:28 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:158)
20.12 21:38:28 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:60)
20.12 21:38:28 [Server] INFO at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
20.12 21:38:28 [Server] INFO java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;

**Comment by zml2008** [comment]
You're using a 1.8+ build of PEX on a 1.7 server. Use PEX 1.22.x instead.
