### ISSUE TITLE
Pex disappearing when restarting server or date

### ISSUE THREAD

**Issue by MeninoDuu** [PEXPlugins/PermissionsEx#2614]
Someone help me I put the pex on my server 1.8 ai when I close the server I open it disappears

**Comment by Stormbow** [comment]
Show me your console log.

**Comment by MeninoDuu** [comment]
as well?

**Comment by Stormbow** [comment]
Copying stuff to Pastebin is typically how things are shared in the Minecraft community.  Since you seemed extremely new to Minecraft servers, I figured I should mention Pastebin in my previous post.

**Comment by MeninoDuu** [comment]
Could you send me a tutorial on how I put the files there? Because I do not know

**Comment by Stormbow** [comment]
You don't know how to copy and paste text?

**Comment by MeninoDuu** [comment]
Yes I know

**Comment by Stormbow** [comment]
Copy the text from your server console and paste it into Pastebin.  After you click "Create a New Paste" at the bottom of the screen, you will see your paste with its own link at the very top of your browser, in the address bar.  Copy that address and paste it into this thread.

**Comment by MeninoDuu** [comment]
http://pastebin.com/D3UHwGKg

**Comment by Stormbow** [comment]
`[21:03:24 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!`

PermissionsEx does not support servers running in offline mode.  You will need to change the server.properties file setting to `online-mode: true` before PEX will function properly and then I can help you more.

**Comment by MeninoDuu** [comment]
But if I put online-mode I do not have original minecraft

**Comment by Stormbow** [comment]
Sorry.  I can't help you with that.  PEX doesn't support hacked/illegal copies of the Minecraft client or servers.
