### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by sourj** [PEXPlugins/PermissionsEx#2615]
console: http://pastebin.com/jkVtUZxz
permissions.yml http://pastebin.com/iGDYs35R

im using the example and no prefix or permissions are working correctly any ideas? 
thank you in advance i appreciate your help and time<3

**Comment by Stormbow** [comment]
For prefixes/suffixes to display in-game, you need a chat management plugin.

It looks like your'e using Spigot, so if you're also already using [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/), grab [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) and [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) to handle your prefixes/suffixes.

**Comment by sourj** [comment]
Ok I'll do this asap (tonight) and update this thread with the result thank
you for your time . I don't think I have essentials xchat I have vault

**Comment by Stormbow** [comment]
Be sure you have both.  EssentialsXChat needs Vault or it won't function properly.

**Comment by sourj** [comment]
I have venturechat thought I didn't need essential chat . And I don't see
any errors in my permissions.yml I'll check for essentialsxchat asap thank
you

**Comment by Stormbow** [comment]
If you're using VentureChat, you wouldn't need EssentialsXChat.  (You may still need Vault, read up on VentureChat.  And if VentureChat is based on ChatManager— which has fractured into hundreds of chat plugins—it won't be supported by PEX because of all those fractures.)  You'd just have to set up VentureChat correctly.

**Comment by sourj** [comment]
problem solved thanks

**Comment by Stormbow** [comment]
You're welcome.  Thanks for posting back.
