### ISSUE TITLE
Pex MySQL each server has its own prefix and permissions

### ISSUE THREAD

**Issue by KingTux2** [PEXPlugins/PermissionsEx#2616]
Is it possible for with Pex MySQL for each server to have a different prefix and permissions for the same rank X

**Comment by Stormbow** [comment]
Not in 1.x versions of PEX.  Possibly in 2.x, but you'll need @zml2008 to chime in about that...

**Comment by KingTux2** [comment]
OK, yes please explain this to me.

**Comment by zml2008** [comment]
Yeah, PEX 2.x supports the `server-tag` context, but SQL support in 2.x still has a few nasty isues so it's not yet recommended.
