### ISSUE TITLE
Disable Update?

### ISSUE THREAD

**Issue by Kyuhunter** [PEXPlugins/PermissionsEx#2617]
Is there a way to disable the update? It works fine with 1.23.2, but when it updates it stops working.

**Comment by Stormbow** [comment]
Do you have the same problem with PEX 1.23.4?

**Comment by Kyuhunter** [comment]
As it seems.. no. The Reason i didn't try, is because the server is on 1.8.1 and this version is not listed on the download. Thanks.

**Comment by Stormbow** [comment]
Yeah; that's just because the Bukkit/Curse site is pretty crappy.  PEX 1.23.4 is good all the way from 1.8 through 1.11 so far.

**Comment by Stormbow** [comment]
You're welcome?
