### ISSUE TITLE
Maven not supported any more?

### ISSUE THREAD

**Issue by LousyLynx** [PEXPlugins/PermissionsEx#2618]
Hello, I am trying to make a plugin that uses PEX, but it is somewhat hard because the maven is still at version 1.23.2-SNAPSHOT, and I cannot get the latest features. In the wiki, it also says to use the 1.22 version(Just thought I would point that out). I am also using gradle, and having something that told me how to set it up with that would be great. And finally, when using gradle(Using the 1.23.2-SNAPSHOT version), I was getting an error that it could not find the bukkit maven.

**Comment by zml2008** [comment]
Use vault
