### ISSUE TITLE
[MC1.8.9]PermissionsEx[v2.0_API4]

### ISSUE THREAD

**Issue by EmanYm** [PEXPlugins/PermissionsEx#2619]
Greetings!

I know PEX2 is still in (heavy) development, and I know documentation is not at the top of the priority pile at this time.  I was just wondering if exists a solid resource with a full list of commands and PEX permissions listed anywhere that is easy to find.
I'm working on a SpongeForge ([MC1.8.9]SpongeForge[v4.2.0β1762_Forge1890]) setup, and so far, all of the information I've have found for PermissionsEx is for PEX1.X, API5, spigot, Bukket, or a combination of the above.  I'm sure I'm not alone in asking for something to be put in solid font (obviously with change as development continues).

I'm looking for something along the lines of
-a breakdown of each "/pex < section >" and the options that follow for each
-proper syntax order for each option (not the jumbled mess I get in the chat that I can't understand when something is not entered right)
-explanation of how the rank ladder works (what order do I need to create groups, and how do they inherit nodes from lower ladder rungs)

I realize this is a large request to find time to handle, but it would honestly make the lives of many server administration a little easier.

**Comment by EmanYm** [comment]
So no suggestions on any of this?

**Comment by Stormbow** [comment]
I'm not familiar with 2.x yet, so you'll need @zml2008 to answer here.

**Comment by zml2008** [comment]
Take a look at the ore page for PEX, which links to an issue explaining command usage.
