### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by alexdaraptor** [PEXPlugins/PermissionsEx#2620]
Ok, I think I have all my permissions sorted out, however there is one user (cueteepie) who is unable to break blocks unless she has Operator. I think I got them mostly sorted out, and members aren't able to do much, but I have her set as an Administrator, yet I have a few default/members that are able to break blocks.

[permissions.txt](https://github.com/PEXPlugins/PermissionsEx/files/671066/permissions.txt)
[config.txt](https://github.com/PEXPlugins/PermissionsEx/files/671067/config.txt)

i think I uploaded these okay, but if not, just tell me, and we can work it out.

**Comment by zml2008** [comment]
do you have some protection plugin that blocks building unless the user has a certain permission or the `build` option set to `true`? Or are people trying to build in the server spawn protection area -- which on bukkit/spigot is restricted to people with op only.
