### ISSUE TITLE
Server HELP

### ISSUE THREAD

**Issue by RaveGraph** [PEXPlugins/PermissionsEx#2621]
I am having a problem with my permissionEx plugin the problem is that i set all the permissions and ranks (as i think) but still Pex ignoring them here is the permissions file.
[Pex.txt](https://github.com/PEXPlugins/PermissionsEx/files/671093/Pex.txt)

**Comment by EmanYm** [comment]
They might want to know the version of Minecraft (1.8.9, 1.10.2, etc), the server jar (Spiggot, Bukkit, Sponge) and PEX version (1.X, 2.X)
Including this information will help determine the best course of action to fixing the problem.

**Comment by RaveGraph** [comment]
yes i have a 1.2.5 server that runs tekkit classic

**Comment by zml2008** [comment]
lol we don't support a server running a MC version that's [4 and a half years old](http://minecraft.gamepedia.com/1.2.5) update or fix your own problems.

**Comment by RaveGraph** [comment]
Wtf dude calm down

Στις 5 Ιαν 2017 5:50 π.μ., ο χρήστης "zml" <notifications@github.com>
έγραψε:

**Comment by Stormbow** [comment]
I fixed your comment for you, @RaveGraph.

You're welcome.
