### ISSUE TITLE
Pex won't do anything.

### ISSUE THREAD

**Issue by P0Pss** [PEXPlugins/PermissionsEx#2622]
My permissionsex is red in /plugins. No clue why

**Comment by Stormbow** [comment]
That's always because there are errors in the permissions file.

**Comment by P0Pss** [comment]
Hence why I closed it...

**Comment by Stormbow** [comment]
And since you didn't have the common courtesy to mention that you figured out what the problem was, I had to clarify it for all future generations who will Google "PEX is red" and end up at this thread.
