### ISSUE TITLE
PEX not saving user data at all!!!!!!!

### ISSUE THREAD

**Issue by Allstarpro24** [PEXPlugins/PermissionsEx#2623]
Permissionsex is not saving user data for some reason. No matter what I do, pex does not save users in the permissions.yml .It's just blank at the bottom.  I tried turning on CreateUserRecords, but that doesn't help. Here's my config. I'm on spigot 1.11 and i'm using the latest pex.

multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: true
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false

**Comment by Stormbow** [comment]
I would bet on the server being run in offline mode, which is not supported by PEX.
