### ISSUE TITLE
URGENT PROBLEM: My Pex isn't working and when i do /pl the Plugin is in red 

### ISSUE THREAD

**Issue by BenzixMC** [PEXPlugins/PermissionsEx#2624]
Hi, can anyone fix this? here is My Pex perms file and also when i do /pl on my server the plugin is red see for your self my server ip is: benzixnetwork.mcpro.co anyways here is my perms file please :)
[permissions .txt](https://github.com/PEXPlugins/PermissionsEx/files/673960/permissions.txt)
![2016-12-27_05 23 41](https://cloud.githubusercontent.com/assets/24790799/21497674/af7ebc76-cbf4-11e6-8216-750996711877.png)

**Comment by Stormbow** [comment]
Make your file look like [this example](http://pastebin.com/8ZSHxauG) as far as the layout is concerned.  You can give it your own group names and all that other stuff, but make sure every section is as you see it here for indentation and the order that things are listed in your file.

**Comment by BenzixMC** [comment]
Okay, Thanks

**Comment by BenzixMC** [comment]
Should i copy & paste everything in the Example then put it in my Permissions.yml folder?

**Comment by Stormbow** [comment]
You can either copy that entire thing, and customize it with your own information from your file, or just move things around in your file to make it look like that example.

You can leave out all the comments, all of the # and words to the right of them.

**Comment by BenzixMC** [comment]
Okay thanks for your Help i will tell you if there any more problems :)

**Comment by Stormbow** [comment]
The important thing is to get all the `options:` settings under the `options:` section, an inheritance section in every group, and all of the indentation correct.

**Comment by Stormbow** [comment]
(Be sure not to use the tab key!)

**Comment by BenzixMC** [comment]
Okay!

**Comment by BenzixMC** [comment]
should i use &(colorcode) for the prefixs and suffixs?

**Comment by BenzixMC** [comment]
when i do /pl the plugin is still red after i did what you told me it still wont work :( here is my perms file (updated) 
[Pexperms.txt](https://github.com/PEXPlugins/PermissionsEx/files/674077/Pexperms.txt)

**Comment by Stormbow** [comment]
Double-check your spacing.  The permissions of the first group, for example, are not indented far enough.

You can get a program called [`Notead++`](http://notepad-plus-plus.org/) if you need help really seeing the indentation and spacing clearly.

**Comment by Stormbow** [comment]
Line 33 of your file, the inheritance of the "Player" group, should be `inheritance: []` not `inheritance: [Player]`.

**Comment by BenzixMC** [comment]
Okay thanks can you edit the txt file i sent you because i am not good at spacing if not thats fine

**Comment by Stormbow** [comment]
I'll fix it all.  Consider it a late Christmas present. ;)

Give me a few minutes...

**Comment by BenzixMC** [comment]
Thank you so Much!! i am very grateful. Also Merry Christmas to you too! i will give you a shoutout on my Youtube Channel (i have 650 Subs :P)

**Comment by Stormbow** [comment]
You probably want `build: true` in the "Player" group so they can actually build— BUT! —it's important to know that setting only applies to the server if you're using EssentialsAntibuild or EssentialsXAntiBuild.  If you don't have either of those jar files on the server (typically because people use Modifyworld to control who can do what), that setting won't do anything no matter what it's set to, and you can delete that line from all of the groups on your server.

Next, you don't need to give the "Owner" group a permission node for `echopet.pet.cow` because the next line of their permissions gives them absolutely every single permission node on the server, including potentially many nodes they don't want (like `vanish.silentjoin` shown in the example, for servers that use the plugin called VanishNoPacket.  You only want to negate permissions above that global wildcard `- '*'`, and be careful not to make anyone else on your server an owner or they could destroy everything on the server.

Almost done fixing the file...

**Comment by BenzixMC** [comment]
Ok i will btw my server is Creative plots so i don't think build true or false will matter

**Comment by Stormbow** [comment]
There ya go— try this one out:
[permissions.txt](https://github.com/PEXPlugins/PermissionsEx/files/674090/permissions.txt)

And after you join your server for the first time, be sure to type these 2 commands into the console:

`pex user Stormbow delete`
`pex user YourMinecraftNameHere add permissions.*`

The first one removes me from the file; the second one gives you access to PEX commands no matter which group you are in.  Then you can move yourself around to different groups on the server to test and set things up.

**Comment by BenzixMC** [comment]
Okay thanks a Million dude!

**Comment by Stormbow** [comment]
Let me know how it goes.

Once it's functional, we can close this ticket.

**Comment by BenzixMC** [comment]
Okay

**Comment by BenzixMC** [comment]
How do i add Players to Groups (In game)

**Comment by Stormbow** [comment]
The players will automatically be added to the `default: true` group, which you have set to be the "Player" group.  From there, you can promote or demote them to other groups, or add other groups to the character.

Check out the [PEX Wiki](https://github.com/PEXPlugins/PermissionsEx/wiki) for all of the commands and what they can do.

I'd give you a link to a beautiful post I made for the commands, but the Bukkit website changed, all the amazing guides I posted there were deleted without warning, and we still haven't gotten them back yet.

**Comment by BenzixMC** [comment]
Okay :) thanks for all your help i will close the ticket now :)

**Comment by Stormbow** [comment]
You're welcome. :) Have fun.

**Comment by BenzixMC** [comment]
one problem, when players join and i do /pex user USERNAME group add GROUPNAME plots they still cant do the permissions i setup and when they first join like they cant do /p auto for example

**Comment by Stormbow** [comment]
I responded to your other ticket,  #2625.
