### ISSUE TITLE
Can anyone help me setup PlotSquared Perms? 

### ISSUE THREAD

**Issue by BenzixMC** [PEXPlugins/PermissionsEx#2625]
Can anyone help? i put PlotSquared Permissions in my permissions.yml  but players in the group cant do the plot commands (e.g /p auto /p h /p claim) please help!
[perms.txt](https://github.com/PEXPlugins/PermissionsEx/files/674189/perms.txt)

**Comment by Stormbow** [comment]
You haven't learned how to use the PlotsSquared plugin correctly.

See their [Commands and Permissions documentation](https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions) for more information.
