### ISSUE TITLE
PermissionsEX deny commands

### ISSUE THREAD

**Issue by prodigyrick** [PEXPlugins/PermissionsEx#2627]
I try 
- -worldedit.version

and every default player can still use worldedit version and any other worldedit or region command there is. I have tried all day to get this to work.
I have no other permissions plugin installed, including essentials.
Everything else works it seems but denying a user access to a command.

**Comment by Stormbow** [comment]
Does the server.properties file have `online-mode: true`?

Show me the full, unedited permissions.yml file.

**Comment by prodigyrick** [comment]
Online is true.
and
http://pastebin.com/TmHGfBCX

**Comment by Stormbow** [comment]
PEX does not support `online-mode=false` and that would be why PEX isn't functioning properly at that time of testing...

The fatal errors I see in your pex file:

* I don't know where people are getting their example file for PEX nowadays, but I wish that source would explode and disappear off the internet.  The `schema-version:` line belongs above the `users:` section.

* If you're running Minecraft 1.9 or higher, every group _must_ have an inheritance section.  Currently, your "Admin" and "default" groups do not.  See line 19 [right here](http://pastebin.com/8ZSHxauG) to give them empty inheritances.

Once these 2 errors are corrected, PEX should function properly unless the server is still trying to run in offline mode (`online-mode=false`).

**Comment by Stormbow** [comment]
Looks like this issue is closed.
