### ISSUE TITLE
Automating Rank Priority

### ISSUE THREAD

**Issue by evanpierceunm** [PEXPlugins/PermissionsEx#2633]
I've recently been working on allowing users to buy ranks or get them from crates and have run into an issue. It seems I am unable to set a group to take precedence over another group.

The issue really comes when a staff rank gets a rank upgrade. My member ladder tree inherits permissions from previous groups as users rank up so there is no problem. I want staff, however, to be able to gain perms from additional ranks while keeping their staff title. I understand PEX reads from top to bottom.

Here is an example user with ranks setup in the correct way:

> group:
>     - moderator
>     - warrior
>     options:
>       name: FreedomWaffle

Moderator will take precedence and the display name will show correctly. However, if I use the command _/pex user FreedomWaffle group add immortal_ the staff chat tag is lost. Here is the example user after running that command:

> group:
>     - immortal
>     - moderator
>     - warrior
>     options:
>       name: FreedomWaffle

As you can see, immortal is at the top of the list, therefore taking precedence over moderator.

I use DeluxeChat so chat format is added with the folowg permission node:
_chatformat.<format>_

I've tried negating the permission node of all chat groups on the normal ladder but the last added group still takes precedence. Is there any way to reorder a user's groups with commands so it can be automated?

**Comment by Stormbow** [comment]
You need to give each group a "weight", as you see in [this example](http://pastebin.com/8ZSHxauG).

**Comment by Stormbow** [comment]
Looks like this issue is closed.
