### ISSUE TITLE
Pex just not working for some reason

### ISSUE THREAD

**Issue by Warfen1** [PEXPlugins/PermissionsEx#2634]
Started using pex was working perfecting fine but now it's not working and when i do /pl its in red. I haven't added any other plugins either. 1.10.2 spigot and using most recent version

**Comment by Warfen1** [comment]
1.10.2 spigot server btw

**Comment by Warfen1** [comment]
solved just a user error with config file... lol. what happened was i had a permission as -essentials instead of - essentials

**Comment by Stormbow** [comment]
Thanks for the update and I'm glad you got it figured out. :)
