### ISSUE TITLE
Persistence of timed permissions

### ISSUE THREAD

**Issue by DiggyWig** [PEXPlugins/PermissionsEx#2641]
This has been an issue for a while now but I haven't seen it mentioned on here, players loose all timed permissions when the server restarts regardless of remaining time etc. 

Going way back this wasn't the case (I honestly can't remember when it broke) and it would be great if this could be fixed as it's such a useful feature, atm though it's severely limited in application by this bug.

**Comment by Stormbow** [comment]
I believe this is fixed in the 1.23.4 version of PEX, or it is being addressed in PEX 2.x onward.

@zml2008 can tell you more about that, after he sees this ticket.

**Comment by zml2008** [comment]
Design decision in 1.x -- use timed groups that just assign permissions if you want them to be saved

**Comment by DiggyWig** [comment]
Ah ok, thanks for the fast response! 
It might be an idea to add a little note to the wiki, just to clarify that timed groups are persistent and timed permissions aren't, I noticed a lot of other people confused about this when I googled it :)
