### ISSUE TITLE
Prefix via vault chat

### ISSUE THREAD

**Issue by CypriotMerks** [PEXPlugins/PermissionsEx#2644]
When setting the prefix via Vault Chat (api v1.6) it creates a separate node within the userdata for the prefix, rather than editing the PEX node already existing. Because of this, Vault then goes off of that node instead of the PEX node for the prefix.

**Comment by JamieSinn** [comment]
Can confirm this.

**Comment by Stormbow** [comment]
Which version of PEX are you referring to?

**Comment by Stormbow** [comment]
Ok.  @zml2008 will be along here eventually to talk more about it.

**Comment by zml2008** [comment]
What do you mean 'separate node in the userdata'? PEX has stored prefix and suffix as options for the past few years, so this seems like expected behavior.

**Comment by CypriotMerks** [comment]
249aa71b-078f-4211-868c-13a3ae1b5a02:
    permissions:
    - '*'
    options:
      name: CypriotMerkz
      prefix: '&f[test] '

What it suppose to look like ^

  249aa71b-078f-4211-868c-13a3ae1b5a02:
    permissions:
    - '*'
    options:
      name: CypriotMerkz
      prefix: '&f[test] '
    worlds:
      skybrock:
        options:
          prefix: '[test2] '

**Comment by zml2008** [comment]
Are you setting the prefix in a specific world? That looks like what I'd expect if you have one prefix set globally then set a prefix for a world (where the `world` parameter is not `null`).

**Comment by JamieSinn** [comment]
No, I was using vault's chat system and setting the prefix via SetPlayerPrefix no world args given. 
May be part of vault, where they set the world to the one the player is currently in.

**Comment by zml2008** [comment]
Yeah, it looks like vault defaults to setting in the current world rather than globally. To get the appropriate behaviour you should explicitly pass `null` to the `world` parameter (and possibly open an issue on the VaultAPI repo asking about this issue).
