### ISSUE TITLE
PEX and world aliases

### ISSUE THREAD

**Issue by frizzbee30** [PEXPlugins/PermissionsEx#2645]
Hi, I am keen to move over to PEX, and run a multiworld server. ALL is configured, and we are moving over from group manager.

However there is one issue I am struggling to find a way around. We unfortunately have a 'legacy' naming of our survival world of 'Survival World' (no underscore), with a lot of plugins referencing it as you can imagine.

PEX  1.2.34 recognises it amongst the other worlds and assigns the correct group etc, which is great

However, any command to select the world, as PEX doesn't see a 'default' world as group manager does, causes real issues.

Moving a player to another group with set world eg Survival Map throws an error

survival is seen as a different world

survival_map  (as we have with Multiverse Core as an alias), is seen as a different world and not recognised (ie the default rank is assigned)

We give permissions, ranks and all sorts with group manager in the survival world, but I am totally stumped how to select it with PEX?

I hope you can help.

Thanks in advance

**Comment by frizzbee30** [comment]
resolved with adding "Survival Map " hope it helps someone else with the same issue

**Comment by zml2008** [comment]
PEX doesn't have a default world because setting permissions/options/parents without a world sets them in all worlds -- you can do that instead. If you still need world-specific things, there is also world inheritance that allows one world to get permissions set in another -- see the wiki for details.
