### ISSUE TITLE
Users losing all permissions upon change in permissions

### ISSUE THREAD

**Issue by Noble1xCarter** [PEXPlugins/PermissionsEx#2646]
Whenever something concerning a player's rank is changed, they seem to lose all permissions (or at least ModifyWorld permissions) until they relog or the server restarts. Changes include changing the rank of or de-opping the user. Has been occurring since ~1.10.

**Comment by Stormbow** [comment]
What plugin is being used to change the users' ranks?

Have you discussed this issue with that plugin's authors?

**Comment by Noble1xCarter** [comment]
PEX is the only plugin that we use to change permissions. I went ahead and did some experimenting by removing/adding different plugins to find that not all perms are being lost, just all ModifyWorld permissions (including chat), leaving players with not being able to do much.

I went ahead and replaced ModifyWorld with EssX Anti-Build and that seems to be working better. That being said, player permissions still aren't properly updating until the server restarts or the player relogs. That being said, the problem isn't as bad as it was before. I couldn't replicate the issue with LuckPerms (in replacement of PEX, although I much prefer PEX).

**Comment by Stormbow** [comment]
What are all of the plugins being used on the server?

**Comment by Stormbow** [comment]
Problem must be solved.  You're welcome. :)

**Comment by Noble1xCarter** [comment]
I'm currently using:

 CleanroomGenerator, CoreProtect, dynmap, WorldEdit, ClearLag, PermissionsEx, mcMMO, Vault, WorldGuard, Multiverse-Core, Essentials, EssentialsChat, EssentialsAntiBuild, CompatNoCheatPlus, CraftBook, PerWorldInventory, LWC, EssentialsSpawn, NoCheatPlus.
