### ISSUE TITLE
[Feature Request] Rank Ladder Switching

### ISSUE THREAD

**Issue by harrypotter529** [PEXPlugins/PermissionsEx#2647]
I would like to request the ability to switch a user from a group in one rank ladder, to a group in another rank ladder with the same rank.

For example; if I have two rank ladders **LadderA** and **LadderB**, and each has 4 groups with these ranks:
### LadderA
10 - _GroupA1_
20 - _GroupA2_
30 - _GroupA3_
40 - _GroupA4_
### LadderB
10 - _GroupB1_
20 - _GroupB2_
30 - _GroupB3_
40 - _GroupB4_

Now let's say that I have a user _User5_ who is in the group _GroupA3_. This means that the user is in a group with a rank of 30. I can promote and demote _User5_, however only within **LadderA**. I would like the ability to switch this user into a group in another ladder with the same rank; in this case, group _GroupB3_ in **LadderB**, with a rank of 30.
I might use a command like this:
`/pex user User5 rank-ladder LadderB`
Where `/pex user User5` means that the command affects User5, not the group they are in.
Where `rank-ladder` shows that we are switching the user to another rank ladder.
Where `LadderB` is simply the name of the ladder the user is being switched to.

If the user is not currently part of a rank ladder, or any specified rank ladder does not exist, or the specified rank ladder does not have a group within it with a rank which matches the rank that the user currently has, then the command simply returns an error message.

This command would greatly simplify many things for me, if possible. Thank you for taking the time to read it.

**Comment by Stormbow** [comment]
The command already exists.

`/pex user <user> group set <group> [world]`
`/pex user User5 group set GroupB3`

**Comment by harrypotter529** [comment]
The idea was more, if you want to automate it. Let's say a user has a certain rank on your server, but there are different types of the same rank, and you want them to be able to use a command block to switch to a different type, without changing their rank. If you have a command block that sets someone to GroupB3, and they were in GroupA4, then they lose permissions that they had before.

**Comment by Stormbow** [comment]
You'd need a different plugin for that.  PEX doesn't handle any automation.
