### ISSUE TITLE
PEX 2.0

### ISSUE THREAD

**Issue by DaedalusPrime97** [PEXPlugins/PermissionsEx#2648]
When will PEX 2.0 be released, and what is the latest stable build from PEX?
Because to be honest, its a serious mess with the versions, Version 2.0 Development build is having errors with dynmap-2.3 or 2.4 which caused me to lose all of the permissions..... But I have a backup. So what is the latest stable build from PEX?

**Comment by zml2008** [comment]
Development builds of 2.0 are relatively stable (and if you get the actual plugin version the build number is included) -- I haven't heard of any issues where people lose all their permissions. If you're actually having issues with that, then it'd be useful to try to track that down -- so provide version information for everything and the steps you can take to reproduce the issue.

**Comment by DaedalusPrime97** [comment]
Thank you for the information, I'll try that to help you :)

**Comment by zml2008** [comment]
No, the way PEX2.0 structures its data means that yaml is even more confusing than it was in 1.x.
