### ISSUE TITLE
Prefix Issues

### ISSUE THREAD

**Issue by XantiFuchs** [PEXPlugins/PermissionsEx#2650]
Hey i was upgrading Pex on 1.11 for my server and now it won't give me a prefix.
i'm using EssentialsXChat 2.0.1

**Comment by Stormbow** [comment]
Be sure you've actually set up the EssentialsXChat config.yml file correctly and you have the Vault.jar installed in your plugins folder too. I can't link you to a guide on EssentialsXChat configuration anymore because the Bukkit website changed without warning and they deleted the forums that I had all the PEX guides posted in. I'm sure Google and YouTube can help you with that though.

**Comment by XantiFuchs** [comment]
Also installed Vault because its an essentials plugin and i allready configurated the chat config.
Also it worked with the old Version of PEX but not with the new one.

**Comment by Stormbow** [comment]
Ok, start at the top then.

Is the server running in online mode?

Are there errors in the console log?  (Show me the log.)

Is the EssentialsXChat config.yml file setup correctly?  (Show me the file.)

**Comment by XantiFuchs** [comment]
Because of all that i just went back to the old version and there it workes fine
even though it is 1.7.9 version of pex

**Comment by XantiFuchs** [comment]
I can't tell you why but: i just upgraded to t he 1.11 version so Pex 1.23.4 and now it works before that it didn't

**Comment by XantiFuchs** [comment]
Anyhow here is the things you need same things i used before wich didn't work:
Yes its on online mode
No no log
Screenshot: http://i.imgur.com/m5wY6n0.png
Configs: http://pastebin.com/Zm7nU9Fi

Like i said same things i used before that didn't worked now it works dunno why

**Comment by Stormbow** [comment]
From the tiny piece of the config files you showed me, I can't see the other section of the file which has 3 lines that have to do with displaying prefixes.  They're up near the beginning of the file.

Find the following lines in your file and remove the hashtags at the front of each line:  http://pastebin.com/wNFF0Xc8

**Comment by thesheriff1** [comment]
Hi im also having the same problem

**Comment by thesheriff1** [comment]
Hi im also having the same problem

**Comment by Stormbow** [comment]
@thesheriff1 : You'll need to be more specific than that.

**Comment by Stormbow** [comment]
If you are still having problems, @thesheriff1, please open your own ticket.

Since @XantiFuchs has not responded in 20 days, I am considering this resolved and closing the ticket.
