### ISSUE TITLE
Inheritance dosen't work at all

### ISSUE THREAD

**Issue by Kwright02** [PEXPlugins/PermissionsEx#2651]
When I try to set group's inheritence it doesn't register that it has been set.
Yes, the group names are correct
Yes, I tried reloading
Yes, I tried re-instaling PEX
Yes, I tried reading the wiki
Yes, I tried asking other people that use the plugin
No, It doesn't work at all what so ever under any circumstance

**Comment by Stormbow** [comment]
Is the server running in online mode?  (The server.properties file must have `online-mode=true`.)

Show us your permissions.yml file.

**Comment by Kwright02** [comment]
I discovered the issue, the permissions file bukkit adds had stuff in it for some reason. I just removed that file and it fixed it.

**Comment by Stormbow** [comment]
That's the first time I ever heard that.

I'm glad you got it working.  ;)
