### ISSUE TITLE
Pex on MySQL

### ISSUE THREAD

**Issue by lastyoda** [PEXPlugins/PermissionsEx#2652]
Hi, everytime I want to change my pex to sql
(Backend: file --> sql) my pex breaks down. Am I doing something wrong or is it just a glitch?
Thanks for helping

**Comment by lastyoda** [comment]
Hello?

**Comment by lastyoda** [comment]
Thanks for the reply! Great ;-;

**Comment by zml2008** [comment]
if you dont have enough patience to wait for a response (so far less than a day after posting) i dont have enough patience to respond.
