### ISSUE TITLE
User handle group lifetime

### ISSUE THREAD

**Issue by yololetsplay** [PEXPlugins/PermissionsEx#2654]
Can u setup an possibility like permission lifetime for users group lifetime?

E.g. "player123" is in the group "testers". The leader of "testers" wants that "player123" get's an temporary lifetime in the group.

I think about clan-members test phase, sub-benefits.

Hope it's easy to integrate ;]

Greetz,
Hannes

**Comment by Stormbow** [comment]
This is already possible.

`pex user <user> group add <group> [world] [lifetime]`

**Comment by yololetsplay** [comment]
Sadly it doesn't work :/
I have all permissions. Tried `/pex user yololetsplay group add tester "" 3600`.
Using the sponge version of the plugin, is that the problem, like it's another command?

I get "Too many arguments!".

Greetz,
Hannes

**Comment by zml2008** [comment]
PEX 2.0 doesn't currently have support for timed permissions.

**Comment by yololetsplay** [comment]
Can u add this soon? ;]

**Comment by Stormbow** [comment]
Ahhhh!  Another person trying to get help without telling us their version, and me assuming 1.x was the question.

**Comment by yololetsplay** [comment]
Well, using your newest build of https://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/ : P

Sry, didn't knowed there are more then just for sponge.
