### ISSUE TITLE
PEX commands not working at all

### ISSUE THREAD

**Issue by nacjm** [PEXPlugins/PermissionsEx#2655]
Hey, 

I am trying to follow the tutorial using the commands but all commands except pex debug result in a too many arguments error. I can't even send a group creation command.

Please help.

--

NN

**Comment by nacjm** [comment]
Welp after trying to create group admin step by step over and over again and copy and pasting it 3 times over with the same error. I try the illogical and copy and paste it exactly one more time.
and it works.

still have no clue why it just decided to work after trying the same thing again and again, giving up, working on something else, then running it one more time.
I will close this you can reopen it if it seems i'm missing something

**Comment by Stormbow** [comment]
Without telling us which commands— exactly —that you were using, we couldn't help.  ;)

**Comment by nacjm** [comment]
pex group failed with that error
pex user failed also
i tried all the commands in the tutorial and none worked except pex debug until i gave up and then tried copy and pasting exactly what was there for creating the admin group, which i had typed out manually 3 times before and it worked

**Comment by Stormbow** [comment]
What did you copy and paste?  Show me that text.

**Comment by nacjm** [comment]
/pex group admin def true
then i added myself to the group with no errors copy and pasting /pex user <name> parent add group admin
and replacing name with my minecraft name

**Comment by Stormbow** [comment]
PEX 2.x?

**Comment by nacjm** [comment]
yes im on sponge

**Comment by Stormbow** [comment]
OK.  @zml2008 will have to take a look at this stuff.  I handle 1.x issues.
