### ISSUE TITLE
Can someone edit my config so there are multiple permissions for different worlds?

### ISSUE THREAD

**Issue by Benzix123** [PEXPlugins/PermissionsEx#2656]
Hi, i was wondering if someone could edit my config and make it so i can add permissions for 2 more worlds the worlds would be world and Survival the main world is plots basically i just need someone to make like 2 new permission sections for 2 certain worlds called world and Survival thanks! 
[permissions.txt](https://github.com/PEXPlugins/PermissionsEx/files/720090/permissions.txt)

**Comment by Stormbow** [comment]
The documentation on Multiworld settings can be found [here](https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#pex-multiworld).

In case you haven't figured it out yet (and accidentally closed your ticket without mentioning that you solved your problem), you'll find what you're after [right here](http://pastebin.com/3SuLAhMc).  (Link will be active for 1 month from today.)

I also corrected some minor issues in your users section and a critical error of the `schema-version: 1` line being in the wrong place.
