### ISSUE TITLE
Simply Doesn't Work

### ISSUE THREAD

**Issue by t0rched** [PEXPlugins/PermissionsEx#2657]
I am using SpongeForge 1.10.2 latest stable, and this is the only plugin I have. I can see the command with /pex and adding groups/permissions appears to work, however does nothing. 

I have tried the usual old permission formates IE "*" or "permissionsex.*" however neither work. 

Is there a global all permissions wildcard for this version of PEX? 

What am I missing? My user is in the only group, and that group has "*": 1 on its permissions.

**Comment by zml2008** [comment]
Read the tutorial linked to on the Ore page.

**Comment by t0rched** [comment]
I have. Followed it to the tee. Thrice.

**Comment by zml2008** [comment]
Clearly you haven't because you're using the `*` node.

**Comment by t0rched** [comment]
That node is mentioned nowhere on that page. Or any page linked to it. What am I missing.

**Comment by t0rched** [comment]
I assume this is the page you refer to. Yet it makes NO mention of wildcard permissions. So instead of being an asshole, how about you just let me know whats going on?

https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md

**Comment by Stormbow** [comment]
Go fuck yourself, dickhead.

**Comment by Stormbow** [comment]
@t0rched : Go fuck yourself, dickhead.

You don't talk that way to people who are providing products/services to you for free.

Any future threads you post on this board will be deleted without comment.

The nerve of some people... SMDH
