### ISSUE TITLE
[PEX 2.x] No Wildcard Permission(?)

### ISSUE THREAD

**Issue by t0rched** [PEXPlugins/PermissionsEx#2659]
After reading the documentation THOROUGHLY I cannot figure out how to provide the old "*" wildcard permission. 

I have read the walk through now and most supporting documentation twice. 

What am I missing. Please stop removing my issues. That's kinda lame and anti-productive.

**Comment by Stormbow** [comment]
Considering your other thread was regarding PEX 2.x, I'm going to assume you're also talking about 2.x in this (incomplete, inarticulate) thread.

@zml2008 will have to comment about wildcards.

**Comment by zml2008** [comment]
The documentation clearly states how to set the default permission value on a subject (user or group). Not my problem you can't read (or figure out you can comment on an existing issue even if it's closed).
