### ISSUE TITLE
Documentation Incomplete

### ISSUE THREAD

**Issue by t0rched** [PEXPlugins/PermissionsEx#2660]
The documentation is awfully incomplete. For instance the main referenced page, https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md, has links at the bottom for further reading, that go nowhere. 

No to mention the content is just wrong. IE, "On first launch, configurations will be created in the config/ninja.leaping.permissionsex folder for Sponge, and plugins/PermissionsEx for Bukkit. 1.x", which is 100% inaccurate. 

When directing people to this documentation, it would be nice if it were actually complete and accurate.

**Comment by Stormbow** [comment]
As PEX 2.x has not been officially released yet— it's still in development —the documentation is also not fully released yet.
