### ISSUE TITLE
PEX permissions not working

### ISSUE THREAD

**Issue by Phantasmie** [PEXPlugins/PermissionsEx#2664]
For some reason, my perms file just won't work. No matter what permissions I have set, all the ranks have the same amount of perms. And the prefixes just straight up don't work at all. I have essentials, adminfun, deadbolt, and pex installed as plugins so far. I'll paste my perms file below if anyone would be willing to help. 

] Edit by Stormbow: Moved pex file contents to Pastebin: http://pastebin.com/ppM92HpU [

**Comment by Stormbow** [comment]
As of Minecraft 1.9, every group _must_ have an inheritance section, even if it is not inheriting from another group.  I fixed this in your "Member" group.

You also added a blank space before and after the wildcard `- '*'` node in the "Owner" group.  I have removed both of those blank spaces and the group should now have **_every single permission node_** possible on the server.  (This includes all of the permission nodes you do not yet know that the group does not want.)  When you discover a permission node that you _do not_ want the group to have, it will need to be negated _above_ the wildcard, as you see in [this example](http://pastebin.com/8ZSHxauG) on line 86 and 87.

PEX should now function correctly using this for the file: [http://pastebin.com/g3sqzjmj](http://pastebin.com/g3sqzjmj).

Keep in mind that you have **_many_** permission nodes in your file that are not real permission nodes as far as I can tell.  Nodes like `essentials.toggledownfall`, `essentials.night`, `essentials.day` and `essentials.r` are not listed in the [Essentials Permission Nodes List](http://wiki.ess3.net/wiki/Command_Reference/Perm) and will not do anything in-game.  Check your file for these and more non-existent permission nodes, and remove them from the file to save space and prevent confusion.

One other problem you are likely to run into is that none of the [Vanilla Permissions](http://wiki.bukkit.org/Vanilla_permissions) can be reliably controlled, going as far back as Minecraft 1.7.2 (at the very least).  If 2 people are running exactly identical servers, it is very possible that one server _can_ fully control those permissions and the other can't.  You will have to test all of those permissions for every group which you give them out to.

**Comment by Phantasmie** [comment]
Nothing seems to have changed at all. I still only have the same 3 pages of commands, regardless of the permissions tree I'm in. However I noticed that when I use /pex user Phantamsie it lists me as being a non-ranked Member not Owner. I'm not sure if this is how it's supposed to look or not. Am I using the wrong command to assign a user to a group? I'm using '/pex user <name> set group <groupname>'.

'UUID/Phantasmie' is a member of:
[XX:XX:XX INFO]:    Member (not ranked)
[XX:XX:XX INFO]: Phantasmie's permissions:
[XX:XX:XX INFO]: (blank for some reason)
[XX:XX:XX INFO]: Phantasmie's options:
[XX:XX:XX INFO]:   name = "Phantasmie"
[XX:XX:XX INFO]:   group = "Owner"

**Comment by zml2008** [comment]
It's `group set` not `set group`

**Comment by Phantasmie** [comment]
Oh wow. Yeah that was the problem. Thanks guys!

**Comment by Stormbow** [comment]
You're welcome. :)
