### ISSUE TITLE
Default rank not working

### ISSUE THREAD

**Issue by yepidoodles** [PEXPlugins/PermissionsEx#2665]
Using latest 1.10.2 Sponge API 5

I've set my default rank as default using the option, but when new players join, they don't have any permission or rank. Also I'm using Enjin to auto add ranks but the ranks aren't been automaticly given to players, I'm having to do everything by hand. Any help would be greatly appreciated.

Thanks

- Alice

**Comment by zml2008** [comment]
"using the option" what does this mean?
Also, I'm unsure what Enjin's integration with Sponge does to auto add ranks, but you'd probably want to check out support with Enjin since that's one of their features not PEX's

**Comment by yepidoodles** [comment]
`/pex group default option set default`

And I figured out the Enjin thing, that's now N/A

**Comment by Cylizion** [comment]
I'm getting this issue now.
