### ISSUE TITLE
my ranks doesnt work

### ISSUE THREAD

**Issue by timanttikuutio** [PEXPlugins/PermissionsEx#2668]
could someone check my permission.yml

http://pastebin.com/hkxKAgZq

**Comment by Stormbow** [comment]
• You were missing inheritance section in some of your groups; I added those for you.

• You had used the tab key on a blank line in the file; I remove both of those for you.

• You had one non-existent permission node— `generic.moderator.permissions` —in the file; I removed that for you.  (I researched it first.  It came from an example of the permissions.yml file in the PEX wiki.  It won't break anything to leave it in the file, it just makes the file longer and doesn't actually grant any permissions, so I removed it.)

• You repeated many permission nodes in each group, and those groups were inheriting from each other; I removed all the repeated nodes, shortening your file from over 500 lines down to 234 lines.  (Double check that the unique permissions you want each group to have are still there.  I'm 95% sure I only deleted repetitive nodes.)

♦ As a bonus, I added the permission node `permissions.*` to the only person on the server who was listed as the Owner.  This gives that user (iMooshy) the ability to use all of the PEX commands, no matter which group they're in while the server is being set up and tested.

You can find the resulting permissions.yml file [right here](http://pastebin.com/tYdQmfp0).

**Comment by Stormbow** [comment]
Give that file a test and let me know how it works out for you.

If it's good, you can close this ticket. :)

**Comment by Stormbow** [comment]
Is this problem resolved?

**Comment by Stormbow** [comment]
You're welcome. :)
