### ISSUE TITLE
How do you have specific commands for a permission?

### ISSUE THREAD

**Issue by MiningNoobYT** [PEXPlugins/PermissionsEx#2671]
For example with /heal, I tried /pex group test (my group name) add /heal, and that didn't work. Then I tried /pex group test add heal, which also didn't work. I also tried /pex group test add essentials.heal, and that just gave the group permission to all of the Essentials plugin. What do I type to get that specific command to work for that group (and not just /heal, for any command)

**Comment by Stormbow** [comment]
Check out the [PEX wiki](https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup) for documentation on how to use the commands with PEX.
