### ISSUE TITLE
Pex plugin wont work

### ISSUE THREAD

**Issue by WubbleZumz** [PEXPlugins/PermissionsEx#2674]
When I try to do /pex, or anything relating to pex nothing pops up. It's not even saying do /help for help... I have the clean 1.7.10 version founded on bukkit. Please help.

**Comment by Stormbow** [comment]
#Brief Troubleshooting Guide

Which version of Minecraft are you running?

Which version of PermissionsEx are you running?

Are there any errors in the console log?  (If yes, copy the log to [Pastebin](http://pastebin.com) and leave the link in this thread.)

Is the server running in online mode?  (The server.properties file must have `online-mode=true`.)

Does your permissions.yml file follow [this example](http://pastebin.com/8ZSHxauG)?  (The indentation must all be correct; option settings must all be in the options section; every group must have an inheritance; see line 19 if a group isn't inheriting permissions from another group; the `schema-version: 1` line must be above the `users:` section; you must not use the tab key anywhere in your file.)

**Comment by WubbleZumz** [comment]
1) 1.7.9 ( I have tried a lot more and its just the same!) (It says 1.22.6 when doing /pex thats the only command that works)

2) Yes, but I do not think they are related. Here you go: http://pastebin.com/hSXfpG0r

3) Yes it is, and here's proof: https://gyazo.com/c7ace166979b2a4757a9651ba8e2f664

4)
 groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
  Owner:
    permissions:
    - '*'
    options:
      prefix: '&7&l[&4&lOwner&7&l]'
    worlds:
      '&4':
        options:
          prefix: '&7&l[&4&lOwner&7&l]'
schema-version: 1
users:
  299907a1-e157-44ff-9983-cecf2c2822a6:
    group:
    - Owner
    options:
      name: WhatsYoutube
  jmic:
    group:
    - Owner

**Comment by Stormbow** [comment]
Download PEX 1.22.10 [here](https://dev.bukkit.org/projects/permissionsex/files/909152).

I would need to see the whole console log to really be able to tell if any errors were important.

Your permissions.yml file is slightly messed up, with 1 additional space at the beginning of the file (before `groups:`) and with incorrect multiworld settings in the "Owner" group.

It also appears that the user named "jmic" is attempting to connect to the server in offline mode.  PEX does not support offline mode servers or clients, and PEX will never function correctly for either of those things (even if other users are connecting in online mode).

Try [this file](http://pastebin.com/rUcMzu7z) for your permissions.  If the server is running in online mode and "jmic" has a paid copy of Minecraft, their user information will be re-added to the file the next time they log in, and you can put them back in the "Owner" group.

**Comment by Stormbow** [comment]
Must be solved.  You're welcome. :)
