### ISSUE TITLE
Keep old prefix.

### ISSUE THREAD

**Issue by Carbonawk** [PEXPlugins/PermissionsEx#2675]
Hi there,

Let me explain my situation.

Like many servers, I got a donation page & staff.
If a staff member would donate. They would get a new rank with the following command.

"pex user [username] group add [newrank]"

But the issue with this is that their prefix will be changed to the last added ranks and they won't appear as staff anymore.
Is there any workaround for this?

Something like subgroups?

Thanks!
Carbonawk

**Comment by Stormbow** [comment]
Add a `weight:` option to each of your groups.

See [this example](http://pastebin.com/8ZSHxauG) for proper weight values.

**Comment by Carbonawk** [comment]
aah of course. This worked perfectly.

Thanks!

**Comment by Stormbow** [comment]
You're welcome. :)
