### ISSUE TITLE
Prefixes not working

### ISSUE THREAD

**Issue by EnderCraft123** [PEXPlugins/PermissionsEx#2677]
hi
i just downloaded PermissionsEX Plugin to my server
and all permissions working well
But the prefixes not working
and this is the permissions string
groups:
  Member:
    options:
      default: true
      rank: '7'
      prefix: '&0[&eMember&0]'
      weight: '1'
    permissions:
    - modifyworld.*

**Comment by Stormbow** [comment]
Be sure your file follows [this example](http://pastebin.com/8ZSHxauG).

Be sure you have a chat management plugin on the server.  (Most people run Spigot servers, so they use EssentialsX for all of the basic permissions, and EssentialsXChat (plus Vault) handles their prefixes.

**Comment by Stormbow** [comment]
I'm guessing this problem is resolved since the OP has not responded in more than a week.
