### ISSUE TITLE
Doesn't check for ladder permissions making it impossible to allow certain groups to only promote on specific ladders.

### ISSUE THREAD

**Issue by blubberdiblub** [PEXPlugins/PermissionsEx#2678]
SpongeForge: 1.11.2-2226-6.0.0-BETA-2114
PermissionsEx v2.0-SNAPSHOT-b147

I would like to assign permissions to groups to be able to promote along specific ladders, but not others.

For instance, moderators would be allowed to promote along the default ladder and admins would be allowed to promote along the moderator ladder (in addition to the default ladder). Moderators mustn't be able to promote along the moderator ladder.

However, currently it only checks for these permissions when promoting:

    [12:40:03] [Server thread/INFO] [permissionsex]: Permission permissionsex.promote.user.<uid> checked in ...
    [12:40:03] [Server thread/INFO] [permissionsex]: Permission permissionsex.promote.own checked in ...

Analogously for demoting:

    [12:41:51] [Server thread/INFO] [permissionsex]: Permission permissionsex.demote.user.<uid> checked in ...
    [12:41:51] [Server thread/INFO] [permissionsex]: Permission permissionsex.demote.own checked in ...

I'd like it to check named ladder permission namespaces, too. Checks for something like **`permissionsex.promote.ladder.<laddername>`** and **`permissionsex.demote.ladder.<laddername>`**, respectively, or similar would be nice.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
