### ISSUE TITLE
Pex Help

### ISSUE THREAD

**Issue by Lion048** [PEXPlugins/PermissionsEx#2679]
I need help with pex prefixes. If you can help me go to ...

] Edit by Stormbow: Server address removed [.

**Comment by Stormbow** [comment]
If you need help, post what you need help with as specifically as possible and I'll help you as best as I can.

I don't visit servers unless I absolutely have to, and advertising your server isn't allowed here unless it's absolutely necessary.

**Comment by Stormbow** [comment]
If your prefixes are not working:

• Do you have a chat management plugin on the server?  If yes, which one are you using?

**Comment by Lion048** [comment]
I use Essentials Chat

**Comment by Stormbow** [comment]
Are you using "EssentialsChat" or "EssentialsXChat"?  ("EssentialsChat" was discontinued at Minecraft 1.8, so it's important to be very specific here.)

Do you have [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) installed?  (It's required for either EssentialsChat or EssentialsXChat to function properly.)

**Comment by Lion048** [comment]
I use EssentialsChat-2.x-SNAPSHOT

**Comment by Stormbow** [comment]
Ok, so you're using "EssentialsChat".

What version of Minecraft are you running?

**Comment by Lion048** [comment]
1.8

**Comment by Stormbow** [comment]
Do you have Vault installed on the server?

**Comment by Lion048** [comment]
And I do /pex group Owner prefix &f[&bOwner&f] but then when i type in chat it says [default] in front of my name

**Comment by Stormbow** [comment]
Have you edited the config.yml file inside the Essentials folder?

**Comment by Lion048** [comment]
No I don't

**Comment by Lion048** [comment]
Yes I did

**Comment by Stormbow** [comment]
Ok, you will need to install Vault.

Do that, test the server, and let me know how it went. :)

**Comment by Lion048** [comment]
Ok

**Comment by Stormbow** [comment]
(The link to Vault is up above.)

**Comment by Lion048** [comment]
Ok now I have the Owner thing but 2 of them

**Comment by Lion048** [comment]
I only want 1

**Comment by Stormbow** [comment]
Check the config.yml file in the Essentials folder.  Make sure it's set to only display one.

If you're using the Multiverse plugin on the server, look inside that config file too because Multiverse also has chat management features which it shouldn't really have.

**Comment by Lion048** [comment]
It is set to Owner: '&c[{GROUP}]&r {DISPLAYNAME}&7:&c &b{MESSAGE}'

**Comment by Lion048** [comment]
And I don't have Multiverse

**Comment by Stormbow** [comment]
Ahhhh!  That's why.

In EssentialsChat, the `{DISPLAYNAME}` variable is your Prefix+Username+Suffix combined.

To correct the double group, you can either remove `{GROUP}` or remove the prefixes that you have defined inside the permissions.yml file.

**Comment by Lion048** [comment]
Oh ok

**Comment by Lion048** [comment]
And

**Comment by Lion048** [comment]
How do I make a space between the prefix and my Username?

**Comment by Lion048** [comment]
Oh wait, I took the {GROUP} out and saved it and restarted my server and it still has it 2 Owner's

**Comment by Stormbow** [comment]
If you're using the config.yml:
> GroupNameHere: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'

If you're using the permissions.yml file:
>prefix: 'GroupNameHere '
(notice the space after GroupNameHere.)

**Comment by Stormbow** [comment]
> Oh wait, I took the {GROUP} out and saved it and restarted my server and it still has it 2 Owners.

Be sure to stop the server and start it again.  The "restart" functionality of most servers isn't all it's cracked up to be.

**Comment by Lion048** [comment]
Ok

**Comment by Stormbow** [comment]
In your case, being a 1.8 server, you can use the commands `/ess reload` and `/pex reload` to get these 2 particular plugins to reload.  It's a bit faster than stopping and starting the server.

**Comment by Lion048** [comment]
Ok but I got the 2 Owner's to go way but the space, didn't show up

**Comment by Stormbow** [comment]
> Ok but I got the 2 Owner's to go way but the space, didn't show up

How did you add the space in?

**Comment by Lion048** [comment]
groups:
  Owner:
    options:
      prefix: '&f[&bOwner&f]'
    worlds:
      '&a''':
        options:
          prefix: '''&f[&bOwner&f]'
      '&a':
        options:
          prefix: '&f[&bOwner&f] '
  members: {}
  defoault: {}
schema-version: 1
users:
  eb8c6eec-539d-48ca-a768-91f31f78a0a3:
    permissions:
    - '*'
    group:
    - Owner
    options:
      name: Lion048SB
I added the space for the 3rd "prefix"

**Comment by Stormbow** [comment]
All of that `&a` stuff needs to be removed.  Those are incorrect multiworld settings.  Only the group itself gets a prefix setting.

**Comment by Stormbow** [comment]
>  Owner:
    options:
      default: false
      prefix: '&f[&bOwner&f] '
    permissions:
    - '*'

**Comment by Lion048** [comment]
When does the 2nd &a end?

**Comment by Lion048** [comment]
Do I get rid of everything and paste that in?

**Comment by Stormbow** [comment]
Hereya go— start from [this file example](http://pastebin.com/Qf5keFWQ).

You can see the _complete_ file example, [right here](http://pastebin.com/8ZSHxauG), if you want to see all the possible settings and a handful of groups pre-made.  You can even use this example as the starting point for your server; the notes about Minecraft 1.9 can be ignored.

**Comment by Lion048** [comment]
So I would paste the 1st one?

**Comment by Stormbow** [comment]
I corrected a typo in http://pastebin.com/Qf5keFWQ.

Yes, copy that one and paste it into your permissions.yml file.  Save the file.  Then type `pex reload` into your server console.

**Comment by Lion048** [comment]
ok let me try it.

**Comment by Lion048** [comment]
Ok it said "Erorr loading permissions file!"

**Comment by Stormbow** [comment]
Woops.  The typo got you.

Reload this page: http://pastebin.com/Qf5keFWQ  Copy that example.  Paste it into your file.  `pex reload` into the console.

**Comment by Lion048** [comment]
ok

**Comment by Lion048** [comment]
Ok it worked but when I make a new group, do I put a space?

**Comment by Stormbow** [comment]
Yep.

**Comment by Stormbow** [comment]
Just like you see in the "Guest" group I made for you.

**Comment by Lion048** [comment]
Yes

**Comment by Lion048** [comment]
Ok

**Comment by Lion048** [comment]
This isn't about pex but do you know how to set the server spawnpoint?

**Comment by Stormbow** [comment]
One final note:

If you add permissions to that Guest group by editing the permissions.yml file directly, be sure to delete the brackets (the [ ] ) to the right of `permissions:`.  Those are just a placeholder until real permissions get added to a group.

**Comment by Stormbow** [comment]
> This isn't about pex but do you know how to set the server spawnpoint?

Since you're using Essentials, you have access to the `/setspawn` command.  Type that in-game and you'll see what the options are for it. :)

**Comment by Lion048** [comment]
Ok thanks

**Comment by Lion048** [comment]
Wait, iy say unknown command

**Comment by Lion048** [comment]
It*

**Comment by Stormbow** [comment]
What did you type, exactly?

`/setspawn`

is the in-game command.

`setspawn`

can't be used in the console as far as I know.

**Comment by Lion048** [comment]
I typed it exactly

**Comment by Stormbow** [comment]
You typed this in-game:

`/setspawn`

and you were told it's not a command?

**Comment by Lion048** [comment]
Its said "Unknown command. Type "/help" for help.

**Comment by Stormbow** [comment]
Do you have the main Essentials.jar file installed on the server?

**Comment by Lion048** [comment]
Yes

**Comment by Stormbow** [comment]
Can you show me a screenshot of your plugins directory?

**Comment by Lion048** [comment]
Sure

**Comment by Lion048** [comment]
[http://imgur.com/gallery/FeMFL](url)

**Comment by Stormbow** [comment]
> http://imgur.com/gallery/FeMFL

Page not found.

**Comment by Lion048** [comment]
I can click on it

**Comment by Lion048** [comment]
![capture](https://cloud.githubusercontent.com/assets/24209846/22631845/f968d988-ebd0-11e6-8e5d-047ababc883e.PNG)

**Comment by Stormbow** [comment]
You have the "EssentialsX" .jar file on your server.  You're literally using "EssentialsX" and not "Essentials" as I had originally thought.

Are you running a Spigot server?

**Comment by Lion048** [comment]
CraftBukkit 1.8 @ Java 8

**Comment by Stormbow** [comment]
That may be part of the problem.  You're using the Spigot server versions of Essentials ("EssentialsX") on a non-spigot ("Bukkit") server.

As you can see on [this page](https://dev.bukkit.org/projects/essentials), there's no _official_ 1.8+ Bukkit or Essentials download.

**Comment by Lion048** [comment]
I don't download plugins

**Comment by Lion048** [comment]
I use a online hoster

**Comment by Stormbow** [comment]
Yeah.  The server host is supplying you with what is essentially an obsolete server wrapper ("Bukkit").

Do they have an option to give you a Spigot server?

**Comment by Lion048** [comment]
Yes

**Comment by Lion048** [comment]
If I do that will my Bukkit Plugins not work?

**Comment by Stormbow** [comment]
Spigot is actually kind of like a child of Bukkit; they're kind of genetically related.

Since Bukkit is Spigot's daddy (they use the same basic genetics, or programming code), Spigot is "backward compatible" to Bukkit plugins and virtually all of the "Bukkit" plugins can be used on "Spigot" servers.

**Comment by Lion048** [comment]
Ok

**Comment by Stormbow** [comment]
You can even run a Spigot 1.8 server, if you're very dedicated to running that _specific_ version of Minecraft.

Minecraft is currently up to 1.11.2 and PEX 1.23.4 (which you're using) works with that version also.

**Comment by Lion048** [comment]
Will it work with version 1.8 of Minecraft?

**Comment by Lion048** [comment]
Will it work for 1.9?

**Comment by Stormbow** [comment]
Yep.  The only important thing to know about 1.9 and later is that PEX needs an inheritance section in every group.  That's when Line 19 of [this example](http://pastebin.com/8ZSHxauG) for PEX comes into consideration.

**Comment by Lion048** [comment]
Will every thing work if I stay with 1.8?

**Comment by Stormbow** [comment]
Well, as we're seeing so far, you're not getting access to the Essentials command `/setspawn`, so a switch to Spigot appears to be a good idea for you— especially since you're right on the very edge of that "no official downloads" issue we talked about a little, earlier..

**Comment by Lion048** [comment]
I'm just trying to avoid later versions because I don't understand the inheritance part

**Comment by Stormbow** [comment]
Inheritance is actually quite simple.  Let's take a look at [my example file](http://pastebin.com/8ZSHxauG) and I'll explain it to you.

In the above example, we see that the "Guest" group has a permission node called `modifyworld.*` (line 12) that lets them do everything there is in the game, thanks to the plugin called [Modifyworld](http://dev.bukkit.org/bukkit-plugins/modifyworld/).  The members of the "Guest" group can move, talk, craft items, pick up items, carry items, hold items, use items on other items/blocks, and interact with everything in the game.

Now, let's look at the "Member" group.  Since the "Member" group has an inheritance set to "Guest" (lines 29 and 30), the "Member" group users also get that `modifyworld.*` permission node that the "Guest" group has, and all of the other permission nodes that "Guest" gets.

If a group (Guest) has something that the other group (Member) does not want or that we don't want them to have, we use something called a "negation" to remove that permission.  For example, since we _do not_ want "Member" group users to have access to the "Guest" group's kit, we _negate_ that permission at the top of the "Member" group's permission section (line 32) and we give the "Member" group users their own special kit— `essentials.kits.member` —on line 33.

There are also actually commands to do all of this stuff while being in-game, but it's typically easier and faster to enter all of this information directly into the permissions.yml file "manually", like you and I have done with previous changes we made to your file.

**Comment by Stormbow** [comment]
Does all of that make sense to you?  Do you understand inheritances a little better?

They're not so scary, are they?  :)

**Comment by Lion048** [comment]
Would it do the inheritances automatically? Or would I have to put it in manually?

**Comment by Stormbow** [comment]
You would have to define them.

**Comment by Lion048** [comment]
Oh because I am not too good at doing that type of stuff

**Comment by Stormbow** [comment]
You've come this far in learning how to run a Minecraft server; don't stop learning now. :)

**Comment by Lion048** [comment]
I just need a guide line to go off of

**Comment by Stormbow** [comment]
You have the example link above and [this post](https://github.com/PEXPlugins/PermissionsEx/issues/2679#issuecomment-277571089).  (And, of course, you can always ask me questions here.)

**Comment by Stormbow** [comment]
I used to have much better guides for just about everything related to PEX 1.x, but since the Bukkit website was reorganized without warning and they disconnected/deleted all of the plugin forums, all of those posts are missing in action now.

**Comment by Lion048** [comment]
Do you have to have a suffix?

**Comment by Stormbow** [comment]
Nope.  Any of the "options" settings can be blank/empty.

`suffix: ''`

(2 apostrophes, right next to each other, with no space in-between.)

**Comment by Stormbow** [comment]
I only included the Suffix in the example so people could see where to add that extra blank space (like the one that you and I fixed for you earlier).

**Comment by Lion048** [comment]
Can I use that but just change a couple of the settings to fit me?

**Comment by Stormbow** [comment]
Absolutely.

I highly recommend deleting all of the _fake_ permission nodes that I put in there— the `permission.node.one` type stuff.

**Comment by Lion048** [comment]
Ok

**Comment by Lion048** [comment]
Thank you!

**Comment by Stormbow** [comment]
Would you like to see that example customized to what we have for your server so far?

**Comment by Lion048** [comment]
Sure

**Comment by Stormbow** [comment]
Here ya go!  http://pastebin.com/eWnaiiq3

**Comment by Stormbow** [comment]
That file is a perfect starting point for you, on a 1.9 and higher server. :)

**Comment by Stormbow** [comment]
(On a 1.7.9 through 1.11.2 server, really.)

**Comment by Lion048** [comment]
Ok I just converted to a Spigot 1.9 server

**Comment by Stormbow** [comment]
Are you using the above starting file I made for ya?

**Comment by Lion048** [comment]
And 1 more thing

**Comment by Lion048** [comment]
Yes I am

**Comment by Lion048** [comment]
What command do I do to give the player a permission not a group?

**Comment by Stormbow** [comment]
> What command do I do to give the player a permission not a group?

`pex user <user> add <permission>`

`pex user Stormbow add permission.node.goes.here `

**Comment by Lion048** [comment]
Ok so I did /pex user [name] add nick and they can do /nick but when I do /pex user [name] add fly
or /pex user [name] add god then they still can't use /god  or /fly which I can do because I have OP

**Comment by Stormbow** [comment]
Normally, I advise against giving users permission nodes, since those can confuse people about the group permissions working correctly.

The only node I always advise giving to someone is the node for access to all of the PEX commands.  (I gave you that node— `permissions.*` —in the example file.  So if you move yourself to the Guest group, for example, to test things out from a "player" perspective instead of an "Owner" viewpoint, you will still have access to all the PEX commands and can move back to your own group easily.)

**Comment by Stormbow** [comment]
> Ok so I did /pex user [name] add nick and they can do /nick but when I do /pex user [name] add fly
or /pex user [name] add god then they still can't use /god or /fly which I can do because I have OP

Be sure you're actually giving out _real_ permission nodes.  You can look at the [Essentials Permission Nodes List](http://wiki.ess3.net/wiki/Command_Reference/Perm) (which EssentialsX also uses) to get the correct nodes.

**Comment by Stormbow** [comment]
> I have OP

Avoid using OP because it's actually intended for servers which do not use any plugins at all.  (Those are called "Vanilla servers".)  Using OP can make you think you have your server programmed correctly when you actually do not.

**Comment by Stormbow** [comment]
What you're accessing are the "[Vanilla Permissions](http://wiki.bukkit.org/Vanilla_permissions)", granted to you by being a member of the "Owner" group that has access to all permission nodes on the server.  These "Vanilla Permissions" can't be reliably controlled by PermissionsEx, so you need to test them extremely thoroughly if you give them out on your server.

**Comment by Lion048** [comment]
Ok My console tells me Essentials failed to load

**Comment by Lion048** [comment]
and the chat wont owrk and no commands will work

**Comment by Stormbow** [comment]
Ok, show me the full console log from the moment you start the server through the point where the server has finished loading and you see a message similar to "Done!" printed on the screen.

**Comment by Lion048** [comment]
How?

**Comment by Stormbow** [comment]
You should be able to copy all of the text and paste it to Pastebin, then leave the Pastebin link here for me to see.

**Comment by Lion048** [comment]
[](url)
http://pastebin.com/XatpAHgY

**Comment by Stormbow** [comment]
You made a mistake while making changes to the permissions.yml file.

Show me that file.

**Comment by Lion048** [comment]
Guest:
    options:
      default: 'true'
      build: 'true'
      prefix: 'Guest '
      suffix: ''
      rank: '1000'
      rank-ladder: Main
      weight: '1000'
    inheritance: []
    permissions:
    - modifyworld.*
    - essentials.kit
    - essentials.kits.guest
  Owner:
    options:
      default: 'false'
      build: 'true'
      prefix: '&f[&bOwner&f] '
      suffix: ''
      rank: '1'
      rank-ladder: Main
      weight: '1'
    inheritance: []
    permissions:
    - '*'
schema-version: 1
users:
  eb8c6eec-539d-48ca-a768-91f31f78a0a3:
    options:
      name: Lion048SB
    group:
    - Owner
    permissions:
    - permissions.*

**Comment by Stormbow** [comment]
Is that the most recent version of your permissions.yml file?  The console log you showed me said that there is an error on line 28 "schema-version" and that's on line 27 of the permissions.yml file you just pasted (plus, the file you just pasted has no errors at all).

**Comment by Lion048** [comment]
Yes that is the most recent

**Comment by Stormbow** [comment]
The console log shows me that there is an error in that file.

The [YAML Parser](http://yaml-online-parser.appspot.com/) shows me that there are no errors in that file.

When I open your file in Notepad++, there is no error either.

Try copying your entire permissions.yml file to Pastebin and leave me that link.  Maybe something is being lost in the formatting by pasting it in as a comment here.

**Comment by Lion048** [comment]
[http://pastebin.com/ZwpkHg2K](url)

**Comment by Stormbow** [comment]
Page not found.  I don't know what's up with my browser(s) today...

**Comment by Stormbow** [comment]
Try sending me a different link.

**Comment by Lion048** [comment]
OK I'll put it in

**Comment by Stormbow** [comment]
I don't know why it was deleted from your file. :P 

It was there [in the first example I gave you](https://github.com/PEXPlugins/PermissionsEx/issues/2679#issuecomment-277572695) for your 1.9+ server...

**Comment by Lion048** [comment]
It still doesnt work

**Comment by Stormbow** [comment]
Any errors in the console?

What _exactly_ is not working?

**Comment by Lion048** [comment]
Ok I got it to work I just re downloaded Essentials

**Comment by Lion048** [comment]
And 1 more thing

**Comment by Stormbow** [comment]
Ok.  Everything working as you expect it to work?

**Comment by Lion048** [comment]
With essentials, how do I do the thing its like /pex promote or something

**Comment by Stormbow** [comment]
If Stormbow is a member of the group "Guest" and you want to make them a member of the group "Member", you would type:

`/pex user Stormbow group set Member`

or 

`/pex promote Stormbow Main`

You can see all of the PEX commands [right here](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands).

**Comment by Stormbow** [comment]
Don't forget to test out the `/setspawn` command (that didn't work earlier) now that you're updated.

**Comment by Lion048** [comment]
The /setspawn didn't work. Do you know any other plugins that have that?

**Comment by Stormbow** [comment]
What is the exact error message that is shown to you in-game?

That command is functional as far back as 1.7.2 servers, at least.

**Comment by Lion048** [comment]
It says Unknown Command

**Comment by Stormbow** [comment]
Ok, time to use PEX debug mode.

Type this into the console:

`pex user Lion048SB toggle debug`

then go back to Minecraft and type

`/setspawn`

then go back to the console and type 

`pex user Lion048SB toggle debug`

then copy everything that was printed in the console between the 2 times you typed the toggle command and paste it to Pastebin; leave me the link.

**Comment by Lion048** [comment]
ok

**Comment by Lion048** [comment]
http://pastebin.com/RQSmBP3a

**Comment by Stormbow** [comment]
Did you change your server to offline mode or something?  PEX is not checking for permissions at all in that console log.

**Comment by Lion048** [comment]
no

**Comment by Stormbow** [comment]
The only other thing I can think of is that the AdminEssentials plugin is interfering with the command.

That plugin isn't actually needed, unless it does something that the 400+ permission nodes of EssentialsX doesn't do...  Does it?  If no, remove it from the server.  If yes, what does it do that EssentialsX doesn't do?

**Comment by Lion048** [comment]
I uninstalled that 1 when I upgraded to 1.9

**Comment by Lion048** [comment]
But do you know any other plugins that let you change the server spawn

**Comment by Stormbow** [comment]
EssentialsX is supposed to.

What's the server address?  I'll come in and have a look.

**Comment by Lion048** [comment]
lioncraft.myserver.gs

**Comment by Lion048** [comment]
![capture](https://cloud.githubusercontent.com/assets/24209846/22634736/658139c6-ebea-11e6-9114-97f04d3a13e6.PNG)

**Comment by Stormbow** [comment]
First things first, stop the server completely.

Then download these files:

* [EssentialsX-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.0.1.jar)
* [EssentialsXChat-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/EssentialsChat/target/EssentialsXChat-2.0.1.jar)
* [EssentialsXProtect-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/EssentialsProtect/target/EssentialsXProtect-2.0.1.jar)
* [EssentialsXSpawn-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/EssentialsSpawn/target/EssentialsXSpawn-2.0.1.jar)

Once you have all of those downloaded, upload them (one at a time, to be safe) to your server's "plugins" folder.

After they are all uploaded, start the server and post in this thread to let me know the server is running.

**Comment by Lion048** [comment]
its up

**Comment by Stormbow** [comment]
Server is up and running.  :)

Post again if you run into any other PEX issues or questions.

**Comment by Lion048** [comment]
Ok I have another question

**Comment by Stormbow** [comment]
Go for it.

**Comment by Lion048** [comment]
Can I have 2 prefixes for 1 player?

**Comment by Stormbow** [comment]
Not with EssentialsXChat.  And I'm not familiar with any plugins that do that.

**Comment by Lion048** [comment]
Ok

**Comment by Lion048** [comment]
1 more thing

**Comment by Lion048** [comment]
Can you assign a prefix to just 1 player without making a group?

**Comment by Stormbow** [comment]
`pex user <user> prefix [newprefix]`

`pex user Stormbow prefix PEXGuru`

I'm not sure how they're displayed in-game, either with EssentialsXChat or with any other chat plugins, so you'd have to test that out.

**Comment by Lion048** [comment]
OK I will

**Comment by Lion048** [comment]
And How do I remove permissions from somebody?

**Comment by Stormbow** [comment]
`pex user Stormbow remove permission.node`

You can see all of the PEX commands [right here](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands).

**Comment by Lion048** [comment]
Wait

**Comment by Lion048** [comment]
Does the Rank in permissions.yml mean if I put the guest at Rank: 2 then if I do /pex promote [name] Main will they get Owner cuz Owner is Rank: 1

**Comment by Lion048** [comment]
I found a issue in my console
[http://pastebin.com/yzNwd5HL](url)

**Comment by Stormbow** [comment]
> Does the Rank in permissions.yml mean if I put the guest at Rank: 2 then if I do /pex promote [name] Main will they get Owner cuz Owner is Rank: 1

Correct.  Typically, Guest would be 1000, Member would be 900, Moderator would be 800, Admin would be 100, and Owner would be 1.  The promote command would move the user 1 group "up" the ladder, to the next "lower" numbered rank.  If you use the command over and over on the same person, they would move from 1000 → 900 → 800 → 100 → 1.  The same is true of the demote command, but in the other direction: 1 → 100 → 800 → 900 → 1000.

> I found a issue in my console
http://pastebin.com/yzNwd5HL

Check the formatting and indentation of your permissions.yml file very carefully.  There is an error somewhere, probably around line 32 and the "Owner" group.

**Comment by Lion048** [comment]
People who join my server can't break blocks

**Comment by Stormbow** [comment]
Be sure the server.properties file has `spawn-protection=0`.  Anything higher than that is the radius from the /setspawn location that no one can do anything on the server.

**Comment by Lion048** [comment]
IS weight the same as Rank? And does it go straight to 100 from 800?

**Comment by Lion048** [comment]
Can I make a new rank ladder and how?

**Comment by Stormbow** [comment]
> Is weight the same as Rank? And does it go straight to 100 from 800?

• "Weight" determines which group's prefix is more important to display in chat and is important for users who are in more than 1 group at the same time.

• "Rank" determines which order the groups go in when it comes to using commands such as /promote and /demote and is important only if these 2 commands are being used on the server.

> Can I make a new rank ladder and how?

The easiest way to do this is to copy a group from [this example file](http://pastebin.com/8ZSHxauG) and customize it to fit the new ladder you're creating.  Assign the group a rank-ladder name which is different than all of the other rank-ladder names used on your server.  Then customize everything else for the group to fit your needs.

**Comment by Lion048** [comment]
I have another issue with Pex, in my permissions.yml I have the group "Guest" set to have the permission "essentials.balance" but when someone does /balance then it says that they don't have permissions to issue the command and I tried restarting the server and it doesn't help

**Comment by Stormbow** [comment]
Use PEX Debug Mode to find out which permission the group is missing:

1. Type `pex user Stormbow toggle debug` into the console to turn debug mode for Stormbow on.

2. Have Stormbow type /balance.

3. Type `pex user Stormbow toggle debug` into the console to turn debug mode for Stormbow off.

4. Look in the console to find the permission which Stormbow's group(s) does not have.

5. Add the missing permission to the group.

6. Re-test the server.

**Comment by Lion048** [comment]
Ok Thanks

**Comment by Stormbow** [comment]
You're welcome.  Post here again if you run have continuing or additional PEX problems.
