### ISSUE TITLE
what PEX version support 1.8?

### ISSUE THREAD

**Issue by wtfkzyzh** [PEXPlugins/PermissionsEx#2683]
https://paste.ubuntu.com/23954368
1.8 use v1.23.3 and v1.23 error occurred

**Comment by Stormbow** [comment]
To the best of my knowledge, 1.23.4 works on 1.8 servers.  Just make sure your Java is updated.

**Comment by Stormbow** [comment]
@zml2008 can either confirm or deny this.

**Comment by wtfkzyzh** [comment]
@Stormbow I don't think is java issue,same java other 1.8 server use 1.23.3 error occurred less likelihood

**Comment by BannerGames** [comment]
In my server work the last version after I validate the permissions.yml

**Comment by ExplosiveNight** [comment]
I use 1.23.4 on my 1.8.8 server and it works fine.

**Comment by Stormbow** [comment]
It appears this issue is resolved since @wtfkzyzh hasn't replied since February 9th.
