### ISSUE TITLE
Error at boot-up trying to upgrade to PEX 2.0

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2684]
I tried to update my server from PEX 1.x to PEX 2.0 and I get two errors at bootup and PEX 2.0 is not running. Hes my whole log of the bootup:

[log.txt](https://github.com/PEXPlugins/PermissionsEx/files/763750/log.txt)

**Comment by Ironic8b498** [comment]
I have tried build 146 still don't convert anything or even load. If I delete the PermissionsEx folder it loads fine, just get set my player as OP or admin. If I have to rebuild my perms that's fine I was going to go over the whole thing to make work better, get rid or redundant perms and make sure perms are in the correct group and assigned to correct world.

**Comment by Stormbow** [comment]
> [23:32:48] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

As long as you're getting this error, PEX will not function correctly as offline mode is not supported.

If you're using Bungeecord to connect multiple servers, you need to go to their documentation and find out how to set the server up correctly for that offline mode requirement.
