### ISSUE TITLE
Keeping staff and donor ranks seperate

### ISSUE THREAD

**Issue by DataPools** [PEXPlugins/PermissionsEx#2686]
I'm fairly new to pex. How would I keep donor ranks and staff ranks seperate?

I'm trying to have staff be able to have donor ranks. If I set a non-donor to a staff group, the permissions of staff should be added to them. However, I do not want the permissions of a donor to be overwritten, if they happen to be added to a staff group. 

How do I make sure the staff group doesn't overwrite the donor's permissions, while also not giving staff permissions to non-donors that become part of a staff group?

**Comment by Stormbow** [comment]
Terminology is important, in this case.  If you _set_ a user to a group, they are a member of only that one group.  If you _add_ a user to a group, they are a member of more than one group.

The following command removes the user named "Stormbow" from his previous group, and puts him into the group named "Staff":

`/pex user Stormbow group set Staff`

The following command keeps the user named "Stormbow" in his previous group, and adds him into the group named "Staff":

`/pex user Stormbow group add Staff`

You can read more of the [PEX commands](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands) on the PEX wiki.

**Comment by DataPools** [comment]
Thank you!

**Comment by Stormbow** [comment]
You're welcome. :)
