### ISSUE TITLE
MySQL trouble

### ISSUE THREAD

**Issue by Lammendam** [PEXPlugins/PermissionsEx#2688]
I've configured my MySQL backend for PEX, but when I try to change backend file using
`pex backend sql`
plugin returns this errors: http://pastebin.com/YMjnVQt4
Using PEX 1.23.4, plugin configuration here: http://pastebin.com/EAn2fzdN
I suppose that i should use another prefix for 
`uri: mysql://31.28.170.123/cs_perms`
but i'm not sure..

**Comment by frizzbee30** [comment]
Hi, your format is correct for the URL, (although I personally wouldn't post username/IP  :)   )

Do you currently have any other plugin db's running with these settings? I may be wrong, but it looks like the db server is just rejecting the connection attempt?

**Comment by Lammendam** [comment]
> Hi, your format is correct for the URL, (although I personally wouldn't post username/IP :) )
Don't worry, i can change this.
> Do you currently have any other plugin db's running with these settings? I may be wrong, but it looks like the db server is just rejecting the connection attempt?
Yeah, i use this settings for authme database.
You suggest to change username/db name? Unfortunately, i've tried this, but result is same.

**Comment by Lammendam** [comment]
Is there any solution?
