### ISSUE TITLE
Prefix permission

### ISSUE THREAD

**Issue by ErkePannekake** [PEXPlugins/PermissionsEx#2689]
how can i let a player set their own prefix but not others i have tried 
permissions.manage.users.prefix.<user>
permissions.manage.users.prefix.self.NAME
permissions.manage.users.prefix.self
permissions.manage.users.prefix.ErkSterk  -  This works but you can only change ErkSterks name :(
please tell me if im doing wrong, if not plz add a option for it ;)
And BTW this is probably wrong section but couldnt find the right place to ask for help lol.

**Comment by Stormbow** [comment]
> how can i let a player set their own prefix but not others i have tried

You answered your own question:

> permissions.manage.users.prefix.ErkSterk - This works but you can only change ErkSterks name

**Comment by ErkePannekake** [comment]
Not really since if that group has that permission only erksterk can change his name and others can change erksterks but other players cant change their name :/

**Comment by Stormbow** [comment]
You give the permission to the player, not to the group.  ;)

**Comment by ErkePannekake** [comment]
I want the group to be able to change their own prefix not a single player or a specific one

**Comment by Stormbow** [comment]
You want a group of potentially hundreds of players to all have the same prefix because they're in the same group, and you want _all_ of those players to be able to change the prefix any time they want?

Then you give the permission node to the group.

I'm starting to think I don't understand what the actual problem is.

**Comment by ErkePannekake** [comment]
I want every player in a group to change only their own prefix using /pex user <name> prefix <prefix> 
the permission permissions.manage.users.prefix.ErkSterk would only let ErkSterks name to bew changed but i want it to be like: permissions.manage.users.prefix.<getexecutors players name> is this possible or do i need to make it myself?

**Comment by Stormbow** [comment]
Ok, you understand that there are 2 prefixes possible, right?  There is a player prefix which is applied only to a single player and a group prefix which is applied to absolutely everyone in that group.

Anyone with permission to change a player prefix is changing the prefix for only that one player.  I told you how to do this [right here](https://github.com/PEXPlugins/PermissionsEx/issues/2689#issuecomment-279199854).

Anyone with permission to change a group prefix is changing the group prefix for absolutely everyone in that group.  I told you how to do this [right here](https://github.com/PEXPlugins/PermissionsEx/issues/2689#issuecomment-280101761).

Am I not understanding the problem you're having?

**Comment by ErkePannekake** [comment]
i want All players in a group to only change their own Prefix, if i ad Pex.manage,users.prefix.ErkSterk all players in that group wil be able to change ErkSterks name, but i want to let all players in the group to ONLY change their own prefix like adding an option like pex.manage.users.prefix.SELF and self means the command executor

**Comment by Stormbow** [comment]
I have correctly resolved this "problem" twice.

Ticket is closed.

**Comment by ErkePannekake** [comment]
StormBow, i dont want to giva a group permission to change the whole groups, and i do not want the whole grouå to be able to change a specific players name, i want EVERYONE i the group to ONLY change THEIR OWN prefix.

**Comment by Stormbow** [comment]
As I told you— there are only 2 prefixes in Minecraft: group and player.  You either grant permission to change the group prefix or you grant permission to change the player prefix.

This ticket is not locked since you're as dumb as a rock.
