### ISSUE TITLE
SQL Error on 1 server

### ISSUE THREAD

**Issue by svh1998** [PEXPlugins/PermissionsEx#2693]
I am using Permission EX on multiple servers with the same config, but only on 1 server doesn't work. This is my error: 

`14.02 14:23:44 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:186)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:192)
14.02 14:23:44 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14.02 14:23:44 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
14.02 14:23:44 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
14.02 14:23:44 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:606)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:693)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:67)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
14.02 14:23:44 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
14.02 14:23:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
14.02 14:23:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
14.02 14:23:44 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
14.02 14:23:44 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
14.02 14:23:44 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:750)
14.02 14:23:44 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:540)
14.02 14:23:44 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
14.02 14:23:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
14.02 14:23:44 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
14.02 14:23:44 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636)
14.02 14:23:44 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
14.02 14:23:44 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
14.02 14:23:44 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
14.02 14:23:44 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
14.02 14:23:44 [Server] INFO at java.lang.Thread.run(Thread.java:745)
14.02 14:23:44 [Server] INFO Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
14.02 14:23:44 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14.02 14:23:44 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
14.02 14:23:44 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
14.02 14:23:44 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.Util.getInstance(Util.java:408)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
14.02 14:23:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
14.02 14:23:44 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
14.02 14:23:44 [Server] INFO at ru.tehkode.libs.org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
14.02 14:23:44 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:161)
14.02 14:23:44 [Server] INFO ... 29 more
`

**Comment by Stormbow** [comment]
> Unknown column 'prefix' in 'field list'

I believe this typically means you have the `schema-version: 1` line in the database twice.

**Comment by svh1998** [comment]
In the database or in the config? I cant find that line in database

**Comment by Stormbow** [comment]
Typically, a server will start out using a file [like this](http://pastebin.com/8ZSHxauG), but customized to their own server of course, and then import that into the database.  That puts the schema version line into the database.

**Comment by svh1998** [comment]
We have a bungeecord server and on all the servers we have the same [config](http://pastebin.com/UAP7BQ6v) and [permissions](http://pastebin.com/W1aCXcFA) file. We are using the permissons on all our servers. Is there something wrong in the files? The default place for saving permissions is set to SQL database.

**Comment by Stormbow** [comment]
Well, unfortunately, that's where my ability to help with this problem ends.  I don't know SQL and I've never used Bungeecord.

You'll need to wait for Zml to reply here.  (He's the actual PEX programmer.)

**Comment by zml2008** [comment]
Make sure you're using the latest/same version of PEX on all the servers -- the database schema changes between versions.

**Comment by svh1998** [comment]
We are using the latest version on all the servers, I had already download PEX again and reinstalled it, but it doesn't work.

**Comment by svh1998** [comment]
All our servers are using PEX 1.23.4

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
