### ISSUE TITLE
Permisssions not working no matter how they are set or what permissions jar is used

### ISSUE THREAD

**Issue by jpoblocki77** [PEXPlugins/PermissionsEx#2695]
I am running a 1.7.10 THERMOS server. I am having a issue with no one on the server being abnle to chat in local it just crashes them back to the server select screen and the cannot use chests doors or place boxes or use swords.

I am running the pack called the 1.7.10 pack with thermos and using the plugins
Clearlagg Creeperheal Essentials Essentials antib7uild essentials chat essentials protect essentials spawn world border and pex.

It seems no matter how many times i set thier group it doesnt work they are unable to do anything including building or chatting.  If anyone tries to chat in loa.
here is my current permissions file

default
groups:
default:
permissions:
- bukkit.broadcast
- bukkit.broadcast.user
- bukkit.command.save.perform
- bukkit.command.teleport
- bukkit.command.tell
- bukkit.command.time.add
- bukkit.command.time.set
- bukkit.command.toggledownfall
- essentials.fly
- essentials.mail
- essentials.mail.send
- essentials.sethome
- essentials.sethome.bed
- essentials.sethome.multiple
- essentials.sethome.multiple.unlimited
- essentials.tp
- essentials.tp.others
- modifyworld *
groups: []

I get this error that says your not allowed to build here or your not allowed to use what ever item it is. I would like for my players to be able to chat and set multiple homes but no matter what i do it doesnt seem to work. Any help would be great. Hope to hear from someone that can tell me what i am doing wrong.

**Comment by jpoblocki77** [comment]
I am running a 1.7.10 THERMOS server. I am having a issue with no one on the server being abnle to chat in local it just crashes them back to the server select screen and the cannot use chests doors or place boxes or use swords.

I am running the pack called the 1.7.10 pack with thermos and using the plugins
Clearlagg Creeperheal Essentials Essentials antib7uild essentials chat essentials protect essentials spawn world border and pex.

It seems no matter how many times i set thier group it doesnt work they are unable to do anything including building or chatting.  If anyone tries to chat in loa.
here is my current permissions file

default
groups:
default:
permissions:
- bukkit.broadcast
- bukkit.broadcast.user
- bukkit.command.save.perform
- bukkit.command.teleport
- bukkit.command.tell
- bukkit.command.time.add
- bukkit.command.time.set
- bukkit.command.toggledownfall
- essentials.fly
- essentials.mail
- essentials.mail.send
- essentials.sethome
- essentials.sethome.bed
- essentials.sethome.multiple
- essentials.sethome.multiple.unlimited
- essentials.tp
- essentials.tp.others
- modifyworld *
groups: []

I get this error that says your not allowed to build here or your not allowed to use what ever item it is. I would like for my players to be able to chat and set multiple homes but no matter what i do it doesnt seem to work. Any help would be great. Hope to hear from someone that can tell me what i am doing wrong.

**Comment by Stormbow** [comment]
Check the server.properties file and make sure the `spawn-protection` setting is at 0.

Your permissions.yml file should follow [this example].  (It appears you have 2 `groups:` sections, which is bad formatting.)

And finally, if you're using Essentials, you may also have the Essentials plugin's "AntiBuild" plugin installed too.  If you do, make sure you have `build: true` in each group's `options:` section, as shown in the example linked above.

Let me know if that helped fix your problem.

**Comment by Stormbow** [comment]
No response in more than 7 days. Issue must be resolved.
