### ISSUE TITLE
Pex - Code doesnt work

### ISSUE THREAD

**Issue by Bastiaan1200** [PEXPlugins/PermissionsEx#2697]
When i join my server i dont have access to pex.
Why doesnt this work?!

**] Edit by Stormbow: Removed permissions.yml text since it was deformed. [**

Please comment if you know why.

Thanks!
Bastiaan

**Comment by Stormbow** [comment]
For Minecraft 1.9 and later, your permissions.yml file should follow [this example](http://pastebin.com/8ZSHxauG) as far as the indentation goes and where everything should be placed.  Your post showed everything left-aligned, not properly indented.  (I deleted that wall of text.  Post your files to Pastebin like I did to preserve any formatting.)

Once you get the indentation correct, test the server and let me know if you need additional PEX help.

**Comment by Stormbow** [comment]
No response in more than 7 days. Issue must be resolved.
