### ISSUE TITLE
Question about how inheritance works

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2698]
OK, since I have not been able to get PEX 2.0 to work I thought maybe I can fix things with PermissionsEx-1.23.4 to give me more time to work on PEX 2.0. 

My questions; If I have a group called lobby in default ladder, and a group called recruit is survival ladder can the recruit group inherit the perms from lobby? I think they can but I don't want to make major changes to have to roll them back.

**Comment by Stormbow** [comment]
>My questions: If I have a group called lobby in default ladder, and a group called recruit is survival ladder can the recruit group inherit the perms from lobby? I think they can but I don't want to make major changes to have to roll them back.

Yes, they can.

**Comment by Ironic8b498** [comment]
thanks, I guess I have some major changes to my perms to work on this weekend, is there a command to copy all perms from one rank to another?

**Comment by Stormbow** [comment]
You can actually open the permissions.yml file in Notepad ([Notepad++](http://notepad-plus-plus.org/) is better) and edit it.  That's by far the fastest way to make changes to the file.

- Open file.
- Change the inheritance value of a group.
- Save the file.
- Close the file.
- Type `/pex reload` in-game type or `pex reload` into the console.

Boom. Done.

PEX Commands can be found [right here](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands), if you want to do it the long way.

**Comment by Ironic8b498** [comment]
I use SQL, so if I import SQL to flat file edit flat file then import flat file to SQL. my notes for some reason say to drop the table in the SQL before I import flat to SQL, do I have to do that? If not when I import I believe the perms I remove from a group will not be removed.

**Comment by Stormbow** [comment]
SQL was completely unnecessary and didn't show any sort of improvements on my server, so I abandoned using it within a few months, and that was many years ago now.

You'll need @zml2008 to handle this ticket since SQL is involved.

**Comment by Ironic8b498** [comment]
I edited my flat file, dropped the three table in my SQL and imported the flat file into the SQL, couldn't wait the days it takes to get answers

**Comment by Stormbow** [comment]
I'm sorry.  I didn't know we were here to serve you, master.

**Comment by Stormbow** [comment]
PS -  Go fuck yourself.

**Comment by Stormbow** [comment]
I told you it was a simple fix and how to do it.

**Comment by Stormbow** [comment]
Ungrateful bastard.
