### ISSUE TITLE
Cannot connect to MySQL

### ISSUE THREAD

**Issue by Gamofinn** [PEXPlugins/PermissionsEx#2701]
Hi,
I am trying to set up MySQL for my bungee cord servers but whenever I try to connect it it says:
```
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Unable to connect to SQL database
=======================================================

```
I am using a host called Scalacube and they provide a MySQL service and I have manged to use it with other plugins but they set out the MySQL config differently 
I have tried lots of different URLs but nothing will work.
Here is my config.yml:

multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      uri: mysql://**********.scalacube.net/pex
      user: root
      password: *************
      type: sql
updater: true
alwaysUpdate: false

**Comment by Gamofinn** [comment]
Sorry, found out what the issue was. I needed to include the port in the uri!

**Comment by Stormbow** [comment]
I'm glad you were able to figure it out. :)
