### ISSUE TITLE
Prefix and Suffix

### ISSUE THREAD

**Issue by Loonyy** [PEXPlugins/PermissionsEx#2704]
Is there any way to make someone have the prefix of one group, but the suffix of another?

**Comment by Stormbow** [comment]
Unfortunately, if there is a plugin which does that, I have never known of its use.  You would have to read the documentation of whichever chat management plugin you were going to use to see if it's possible.  PEX itself doesn't do any chat management; it simply provides a place to store that information, and the chat management plugin(s) apply that information to in-game chat.

**Comment by Loonyy** [comment]
Ah, that sucks.

I'm wanting to have users be in multiple groups; one of the groups will be a donation group and display a prefix and one of the groups will be what they earn from ranking up in creative, which is basically a ranking system. So basically:
[DonationRank] Loonyy [Rank]:

Can't really find a way to do this :/

**Comment by Stormbow** [comment]
The only chat plugin I'm personally experienced with, EssentialsXChat for example, would allow you to display a user's group prefix, the username, and the user's suffix.  That would technically do what you're asking for, but it would mean manually assigning every user with a suffix.  (An ugly solution to the problem, I'd say.)

**Comment by Stormbow** [comment]
You could also make what I call "blank groups" which are literally empty groups with nothing more than an inheritance and option settings in them.

For example, "Donator" is the first level of the donator ranks.  You give all the donator permissions to that group, you give that group a prefix and suffix that applies to the [Rank] suffix you wanted.  For every new [Rank] suffix that you want people to be able to level up through, you create a new group, give it the new [Rank] suffix, but the old [Donator] prefix, and have the group inherit from the original [Donator] group.

Does that make sense?

**Comment by Stormbow** [comment]
Example file: http://pastebin.com/drkbvHQ4

**Comment by Loonyy** [comment]
Well that wouldn't work if I've got multiple donation ranks with different prefixes would it?

**Comment by Loonyy** [comment]
Also, being a donation doesn't give you rank 1; ranks are based on gameplay - if you move onto the next plot level you get the new rank.

**Comment by Stormbow** [comment]
I think you confused me on your concept.

Can you give me much more specific and complete group names?

**Comment by Stormbow** [comment]
I was under the impression you wanted:

`[GroupAPrefix] [Username] [GroupBPrefix]: words they said in chat.`

**Comment by Loonyy** [comment]
Sure!

**Ranking System**
It's a creative server, we have 6 plot worlds. You create your build, mark it for review and if it's good enough you'll be ranked up to the next world with bigger plots and a new suffix.
Ranking you up gives you access to enter the next world and gives you more commands.

**Rank 1**
The name is Gold
**Rank 2**
The name is Platnium
**Rank 3**
Diamond

These aren't the donation ranks, but I'm creating each prefix with a group.
When somebody donates, they get a prefix and get put in the group:
**Donation Ranks (Example)**
- Squire
- Jester
- Knight

So what I'm wanting:
I'm wanting to be able to put someone in the Knight group, and the Platinum group and their chat would look something like:
**(Knight) Loonyy (Platnium):** Hey guys it's me!
Or of course, if they're a Squire and in the diamond group:
**(Squire) Loonyy (Diamond):** YoYo!

Does that make sense?
So, they can be in two groups, and have one prefix, one suffix from different groups.

**Comment by Stormbow** [comment]
> It doesn't have to be suffix either, I'd be fine if I could allow two prefixes from two groups in the chat.

This, I'm 100% certain that PEX and/or EssentialsXChat can not do.

Give me a few more minutes to think about the previous setup and I'll see if I can come up with a functional solution that isn't too ugly...

**Comment by Loonyy** [comment]
Thank you!

**Comment by Loonyy** [comment]
Unless, I get a developer to make a lite ranking system that just adds a suffix onto players through commands?

**Comment by Stormbow** [comment]
OK, first things first, let's pretend that before making it to these ranks, everyone is already in "Member", and that we want these ranks to also be able to do the stuff that "Member" can do.

Next, look at [this example](http://pastebin.com/Ab7K1kW1).

Let's say Stormbow is a member of "Member" (not shown in the file above), and becomes a "Jester".  We want Stormbow in the bottom-most rank of "Jester", so we _set_ Stormbow into the "Jester" ladder by putting him in the first group on the "Jester" ladder, which is called "JesterGold" internally:

`pex user Stormbow group set JesterGold`

Now, when Stormbow talks in chat, it looks like this:

`[Jester] Stormbow [Gold]: words he said in chat.`

To advance Stormbow from Gold to Platinum, we use the promote command:

`pex promote Stormbow Jester`

Now, Stormbow's chat looks like this:

`[Jester] Stormbow [Platinum]: words`

Promote stormbow again with `pex promote Stormbow Jester` and he now talks like this:

`[Jester] Stormbow [Diamond]: words`

If Stormbow was to become a "Squire", we would set him into the bottom-most "Squire" rank, on the "Squire" ladder the same way we set him into the "Jester" ladder:

`pex user Stormbow group set SquireGold`

And his chat would look like this:

`[Squire] Stormbow [Gold]: words`

Based on the example file linked above, all of the "Squire" ladder's groups would have all of the permissions of "SquireGold", and then you could potentially assign specific bonus permissions to the higher ranks (Platinum and Diamond) and remove the lower ranks permissions, to keep things specific to each group _if_ you wanted to.

Does that make sense?

**Comment by Stormbow** [comment]
We use 3 ladders: "Jester", "Squire", and "Knight".

Then we give each of those ladders 3 groups: LADDERGold, LADDERPlatinum, and LADDERDiamond.

**Comment by Loonyy** [comment]
But then, if someone donates and it adds them to their group it would then remove their ladder and I'd have to manually put someone into each group, so that solution isn't very efficient :/

**Comment by Stormbow** [comment]
(And I just noticed I put the numbers in the groups backwards.)

SquireGold should be 513, SquirePlatinum should be 512, and SquireDiamond should be 511.

**Comment by Stormbow** [comment]
> But then, if someone donates and it adds them to their group it would then remove their ladder and I'd have to manually put someone into each group, so that solution isn't very efficient :/

You mean you want someone in SquireGold and JesterGold?

**Comment by Loonyy** [comment]
If someone's Diamond, and they donate for Knight it's going to remove their diamond group.

**Comment by Stormbow** [comment]
Yeah...  I don't understand which of these things you want to be groups.

**Comment by Stormbow** [comment]
Your example said Squire, Jester, and Knight were the ranks/groups and leveling up was Gold, Platinum, Diamond.  That's what the example I created gave you.

**Comment by Loonyy** [comment]
Yes I know, except someone ranks up without donating.. If they get ranked up and haven't donated, they'll just be:
**(Member) Loonyy (Diamond): **hey
However, when they donate it's putting them in the group they donating for, thus removing them from the previous rank group. Do you understand what I mean?

**Comment by Stormbow** [comment]
No; the "Member" group wouldn't have a [Diamond] as a suffix.

**Comment by Loonyy** [comment]
But that's my point, I need any rank to be able to get any suffix.

**Comment by Loonyy** [comment]
I think I'm going to try and do it through other plugins, but thank you for all the help!

**Comment by Stormbow** [comment]
Have a look at [this updated example](http://pastebin.com/qJ4CxNbw), including a "Guest" and "Member" group.

Here, someone who has never been on the server before will become a "Guest" member automatically.  This group could be limited on what they could do, if you desire.  Once the person has proven they're not just on the server to grief, you promote them to "Member" using `pex promote Stormbow Members`.  Their chat will look like this:

`[Guest] Stormbow: words`
`[Member] Stormbow: words`

**Comment by Stormbow** [comment]
> But that's my point, I need any rank to be able to get any suffix.

This is not possible with any chat plugins, and has to be handled specifically with permissions.

**Comment by Stormbow** [comment]
Yeah.  Sorry.  I can't help you when you don't give me all the relevant information, can't articulate what you actually want to happen, and you keep changing the way you want things to work.
