### ISSUE TITLE
Command /pex user <user> doesn't show permissions list for the <user>

### ISSUE THREAD

**Issue by WyRe** [PEXPlugins/PermissionsEx#2707]
I've tried like owner, with all permissions enabled, and doesn't work even, that's the output for any user:

![captura de pantalla de 2017-02-23 02-13-47](https://cloud.githubusercontent.com/assets/4059108/23240569/76dc7320-f96e-11e6-8a6c-8a3469d6600b.png)

That's my server setup:

![captura de pantalla de 2017-02-23 02-21-21](https://cloud.githubusercontent.com/assets/4059108/23240640/d231fef2-f96e-11e6-9c45-1cd9c3c6d114.png)

**Comment by Stormbow** [comment]
I've never needed or used that command, so I don't remember what it's supposed to do.  If I wanted to see anyone's permissions, I just look in the file.  It's easier.  ;-)

You'll need zml to give you details.

**Comment by WyRe** [comment]
What zml do yo refer? And ... It's not for server managing, I was thinking more about moderation or permission check, I mean, if a basic user ask to a moderator what permissions he has, the moderator should be able to check them and notify the user. 

Of course when I manage my server I see the permissions and groups inside .yml file but operators/moderators doesn't have got that possibility.

**Comment by Stormbow** [comment]
The user can type /help and see all the commands available to them.  The "permissions" are not likely to make any sense or be any help to them.

**Comment by WyRe** [comment]
I was referring to permissions what a particular user has got. Eventually one moderator could want to check what permissions has a particular user o a particular group.

**Comment by Stormbow** [comment]
And as I said, most users will not understand anything if you tell them "You have permission.node.whatever." because that does not tell the user anything about the commands associated with that permission node.  Nodes are strictly admin-side information and commands are user-side information.

That's all I can tell you, regardless of whether you accept that information or not.

**Comment by WyRe** [comment]
Ok, anyway I've thought would be a implemented feature intentionally that is not working properly. 

Thank you for the aclaration.
