### ISSUE TITLE
FileNotFound

### ISSUE THREAD

**Issue by TimoCrafter** [PEXPlugins/PermissionsEx#2708]
Hello,
I am currently experimenting a bit. When I copy the first lines from Bukkit, I always get a very strange error:

`            ConfigurationLoader<ConfigurationNode> configLoader = YAMLConfigurationLoader.builder()
                    .setFile(new File(directory, "config.yml"))
                    .setFlowStyle(DumperOptions.FlowStyle.BLOCK)
                    .build();
            directory.mkdirs();
            manager = new PermissionsEx(FilePermissionsExConfiguration.fromLoader(configLoader), new BungeeImplementationInterface());
`

So this is my code, and I always get this error:

09:36:59 [SEVERE] java.nio.file.NoSuchFileException: /home/minecraft/bungeecord/plugins/PermissionsEX/1487925419816config.yml.tmp
09:36:59 [SEVERE]     at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
09:36:59 [SEVERE]     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
09:36:59 [SEVERE]     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
09:36:59 [SEVERE]     at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
09:36:59 [SEVERE]     at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
09:36:59 [SEVERE]     at java.nio.file.Files.newOutputStream(Files.java:216)
09:36:59 [SEVERE]     at java.nio.file.Files.newBufferedWriter(Files.java:2860)
09:36:59 [SEVERE]     at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.loader.AtomicFiles.createAtomicBufferedWriter(AtomicFiles.java:55)
09:36:59 [SEVERE]     at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.loader.AtomicFiles.lambda$createAtomicWriterFactory$0(AtomicFiles.java:38)
09:36:59 [SEVERE]     at ninja.leaping.permissionsex.libs.ninja-leaping-configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:184)
09:36:59 [SEVERE]     at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.load(FilePermissionsExConfiguration.java:94)
09:36:59 [SEVERE]     at ninja.leaping.permissionsex.config.FilePermissionsExConfiguration.fromLoader(FilePermissionsExConfiguration.java:84)
09:36:59 [SEVERE]     at at.TimoCraft.BungeePEX.BungeePEX.makeInstances(BungeePEX.java:98)
09:36:59 [SEVERE]     at at.TimoCraft.BungeePEX.BungeePEX.onEnable(BungeePEX.java:80)
09:36:59 [SEVERE]     at bungeepluginmanager.PluginUtils.loadPlugin(PluginUtils.java:136)
09:36:59 [SEVERE]     at bungeepluginmanager.Commands.execute(Commands.java:51)
09:36:59 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
09:36:59 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
09:36:59 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
09:36:59 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

I know that you are not responsible for my code, but even though, it would be great if you could help me. Thanks, kind regards,
Timo

**Comment by TnTGamesTV** [comment]
I`'m not sure about it, but is _/home/minecraft/bungeecord/plugins/PermissionsEX/1487925419816config.yml.tmp_ even a real path? Because, if you look at the stack trace, it sais "NoSuchFileException", which means that this file does not exist. I would suggest changing your code or the file and to create a new Path with `Path path = FileSystems.getDefault().getPath("YourPathHere")` and then to check with `Files.exists(path)`, which returns a boolean, if the file exists. Obviously, you could check by hand, but if the file only exists at runtime it's better to check with code.

~TnTGames

**Comment by TimoCrafter** [comment]
no this path exists. Just the file does not exist.

**Comment by TimoCrafter** [comment]
Oh no wtf its PemissionsEx not PermissionsEX :P
Thanks, working now.

**Comment by zml2008** [comment]
yeah, the folder the file is in has to exist for saving to work

**Comment by TimoCrafter** [comment]
@zml please have a look on my other issue! Pex bukkit does not work at all... (also the official from the jenkins)
