### ISSUE TITLE
Same prefix as parent

### ISSUE THREAD

**Issue by AnonymousHitman** [PEXPlugins/PermissionsEx#2711]
To make it easier to word, wen i do the command to make a group have the same permissions as another group the group that I want to have the same permission keeps the parents prefix.

**Comment by Stormbow** [comment]
I don't understand what you are trying to say at all.

**Comment by AnonymousHitman** [comment]
Okay. I have a rank called ice and a rank called default. I make the ice inheriance from default. Once I do that, ice has the same permissions as default but ice has the same prefix as default

**Comment by Stormbow** [comment]
Show me your full permissions.yml file.  (Copy it to [Pastebin](http://pastebin.com) and leave the link here.)

Prefixes are not inheritable, so there must be something else going on in your files and configs.

**Comment by Stormbow** [comment]
No response in 7 days.  Issue must be resolved.

**Comment by AnonymousHitman** [comment]
I resolved that error but now I have another error. My players have access to /plugins. They dont have the permission node. http://pastebin.com/WE0xZQPx

**Comment by Stormbow** [comment]
OK.  Responded to #2722.  Post over there for that issue.  This thread is done.
