### ISSUE TITLE
PEX 2.0 API help needed

### ISSUE THREAD

**Issue by xorinzor** [PEXPlugins/PermissionsEx#2712]
It looks like the API of PermissionsEx 2  is completely different from PermissionsEx 1, and with no documentation available I'm pretty much stuck as of right now.

Can't find where to start with in eclipse by browsing the methods either, is an API even implemented yet?

What do I need to call in order to get access to the permissions manager?

**Comment by Stormbow** [comment]
Correct.  PEX 2.x is still in development.  Zml can tell you more about the API and programming aspects.

**Comment by xorinzor** [comment]
That'd be great, since we have to use PEX 2.0 for compatibility with Sponge, and there don't seem to be any Sync Plugins for Sponge (to update a member rank when registered on a website).

So I planned to make my own, but for that it would be useful to know how to get started with the current build haha :)

**Comment by zml2008** [comment]
Use the Sponge permissions API. PEX2.0 currently does not have any exposed API.

**Comment by xorinzor** [comment]
yeah that's not an option, I guess I'll just have to run the commands then.
