### ISSUE TITLE
Change no perm message

### ISSUE THREAD

**Issue by djtb2924** [PEXPlugins/PermissionsEx#2714]
How i can change the no permission message ?

**Comment by Stormbow** [comment]
That's not customizeable in PEX 1.x and I don't know if it's customizable in PEX 2.x which is still in development.  (I suspect it is not.)

**Comment by zml2008** [comment]
It's not -- the no permission message is chosen by each plugin. PEX just gives the plugin a yes or no when asked, and the plugin uses that to determine what to do and what messages to send.

**Comment by Stormbow** [comment]
Ahhh!  That's right.  Now I remember you saying that before.  Sorry for making you repeat yourself.  :X
