### ISSUE TITLE
Bug /pex user <pseudo> timed add <permissions> <world>

### ISSUE THREAD

**Issue by FyFou57** [PEXPlugins/PermissionsEx#2718]
FR
Bonjour, je ne peux pas ajouter une permission temporairement à un joueur avec la commande timed add, après avoir fait la commande le joueur reçois la commande, cependant rien n'est afficher dans le fichier des permissions ou nul par d'autres, je n'ai aucune erreurs dans les logs, et si je met un permission à un joueur pendant 30 jours, il l'aura sauf après un redémarrage ou il ne l'aura plus comme si je ne l'avais pas ajouté

EN
Hello, I can not temporarily add a permission to a player with the command timed add, after making the command the player gets the command, however nothing is displayed in the permissions file or null by others I I have no errors in the logs, and if I give a permission to a player for 30 days, it will have it except after a restart or it will no longer have it as if I had not added it

**Comment by FyFou57** [comment]
I use spigot 1.7.10

**Comment by FyFou57** [comment]
problème toujours d'actualité, impossible de mettre temporairement une permissoin à un joueur !

Problem always topical, impossible to temporarily put a permissoin to a player!

**Comment by Stormbow** [comment]
> https://github.com/PEXPlugins/PermissionsEx/issues/2029#issuecomment-105055949

Per zml, "Timed permissions are intentionally transient. What you are probably looking for are timed groups -- those are stored but expire after a certain amount of time as well."

**Comment by FyFou57** [comment]
non je souhaite mettre une commande temporairement à un joueur, exemple si je veux donner la permission '/kit exemple' pendant 30 jours à un joueur je dois faire /pex user <user> timed add essentials.kits.exemple 2592000 world .
Hors, ceci ne fonctionne pas (en 1.7.10)


No I would like to put a command temporarily to a player, example if I want to give '/ kit example' permission for 30 days to a player I need to do /pex user <user> timed add essentials.kits.exemple 2592000 world
Off, this does not work (in 1.7.10)

**Comment by Stormbow** [comment]
Correct.

You'll have to put `essentials.kits.example` in a group with no other settings, and temporarily add that group to the player.

`pex user Stormbow group add Temporary 2592000 world`

**Comment by FyFou57** [comment]
le plugin n'aura pas de problème si  un joueur est dans plusieurs groupes ?

The plugin will have no problem if a player is in several groups?

**Comment by Stormbow** [comment]
No problem. :)
