### ISSUE TITLE
Can't find a permission.

### ISSUE THREAD

**Issue by Carbonawk** [PEXPlugins/PermissionsEx#2720]
Keeping it short. 

I can't find the permission for the command "/pex group <groupname> rank "10""
Any help is appreciated.

**Comment by Stormbow** [comment]
If this is a PEX 1.x question, you'd be looking for `permissions.groups.rank.<group>` and the command is actually `pex group <group> rank <number>`.  (Found using `pex user Stormbow toggle debug` on my 1.7.2 server.)

For the purposes of setting up and testing servers, I always advise server owners to give themselves (and no one else, ever) full access to _all_ of the PEX commands with `pex user <user> add permissions.*` e.g., `pex user Stormbow add permissions.*`.  This way a server owner can move themselves around to any group and get the feel of the group as if they were a true member of it while setting up and troubleshooting any issues.

**Comment by Carbonawk** [comment]
Thank you, that's exactly what I need to know.

**Comment by Stormbow** [comment]
You're welcome.
