### ISSUE TITLE
Groups have access to /plugins but they dont have the perm

### ISSUE THREAD

**Issue by AnonymousHitman** [PEXPlugins/PermissionsEx#2722]
My players have access to /plugins. They dont have the permission node. http://pastebin.com/WE0xZQPx

**Comment by Stormbow** [comment]
Which version of Minecraft and PEX are you running?

**Comment by AnonymousHitman** [comment]
minecraft version is 1.8.8 and the plugin version is 1.23.4, and every player that does have all perms still has access to /plugins

**Comment by Stormbow** [comment]
You can _try_ negating the [Vanilla Permissions](http://bukkit.gamepedia.com/Vanilla_permissions), but they are _extremely_ random to control. (2 people running the exact same server may have different results.)

`pex group <group> add -bukkit.command.plugins`

Test the above command on your group(s).  If it works— great!  If it doesn't work, use Debug Mode:

1. Type `pex user Stormbow toggle debug` into the console to turn Debug Mode on.
2. Have Stormbow type `/plugins` in-game.
3. Type `pex user Stormbow toggle debug` into the console to turn Debug Mode off.
4. Look through the console output to find out which permission node(s) are giving Stormbow access to the /plugins command.
5. Negate those permission nodes with `pex group <group> add -permission.node.name`.

**Comment by AnonymousHitman** [comment]
Do u need to join my server for debug mode?

**Comment by AnonymousHitman** [comment]
nevermind thanks the first command worked

**Comment by Stormbow** [comment]
> Do u need to join my server for debug mode?

You would (obviously) use your Minecraft name.

> nevermind thanks the first command worked

Issue solved?
