### ISSUE TITLE
Player primary rank removed

### ISSUE THREAD

**Issue by Waffles2112** [PEXPlugins/PermissionsEx#2725]
I own a prison server and there appears to be a rank glitch where i remove their world specific rank and give them their new rank using the world selector
Once i do this/this happens, their primary/non-world specific rank dissapears/get removed from the rank.
Its only fixed when i give them their primary rank back.
This is a huge problem as i cant constantly give people their primary rank back once they become removed from it upon the world specific rankup.

**Comment by Stormbow** [comment]
Can you give me a specific example with a specific user, specific groups to which they are a member, and the exact commands being used in the order they are being used?

**Comment by Waffles2112** [comment]
for example
FireyJelly apart of group Default, and in a world specific group called PrisonD4
when they go to rankup to PrisonD3
it executes /pex user FireyJelly group remove PrisonD4 Prison
and then it executes /pex user FireyJelly group add PrisonD3 Prison
to remove them from that group in the world 'Prison' and add the new rank in the same world 'Prison'
once this occures, FireyJelly is then removed from group Default aswell
Thereby leaving him only in PrisonD3 in Prison
but removed from group Default in all worlds
(The order the commands were used are the correct and exact order they are being used)

**Comment by Stormbow** [comment]
> **it** executes /pex user FireyJelly group remove PrisonD4 Prison

What exactly is "it"?  PEX has no automated tasks at all.

Which exact permission node in the "Default" group is "FireJelly" no longer able to access after being removed from "PrisonD4"?

Why are these groups not inheriting the "Default" groups permissions?

**Comment by Waffles2112** [comment]
It refers to the server, or rather upon a signclick (via ServerSigns) that removes them from PrisonD4 and adds them to PrisonD3
The adding to PrisonD3 is delayed as to not execute first

FireyJelly becomes completly removed from the group upon an inspection via /Pex user FireyJelly
this is also visualy indicated from the lack of all chat/username formating that the group designates to FireyJelly or all users under that group for that matter

And that's because when I do this it removes the Prison rank's suffix, and also, if FireyJelly were of a donor or other rank on the Default ladder and this occurred, I wouldnt be able to have the Prison ranks inheriting from those other ranks on the Default ladder as it would give Default ranked players donor/higher ranked permissions

(Keep in mind that I used FireyJelly as a basic example of the problem, but this happens with everyone on any group of the Default ladder, but is only fixed once I re-add them back to their primary/default ladder'd group)

**Comment by Stormbow** [comment]
You didn't show me your permissions.yml file.  I cannot magically summon your server hierarchy into my own brain.  Show me the file.  :P

> /Pex user FireyJelly

PEX typically will not display whichever group is `default; true`.  PEX knows that a user with no group listed is in the `default: true` group.

Without a specific missing permission node, I can't verify that the user is actually removed from the `default; true` group.

The "PrisonD4" suffix _should_ be removed from someone who is no longer in that group.

It sounds to me like ServerSigns is not executing the correct commands to change user groups.

**Comment by Waffles2112** [comment]
i have a strong feeling that the problem is a lack in understanding the issue
ill try bPermissions but ty for whatever u do

**Comment by Stormbow** [comment]
Yeah, that happens when someone says "I need help with X" and they refuse to show you their information— as if their server setup was the only one of its kind in the entire history of Minecraft's 50 million servers.

`*nod nod*`
