### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mickedplay** [PEXPlugins/PermissionsEx#2727]
This happend while trying to join the server while it's reloading:
http://pastebin.com/QUQmTsRm

Spigot version: 1.11.2-R0.1
PEX version: 1.23.4

**Comment by Stormbow** [comment]
Sorry, I haven't seen that one before so you'll need @zml2008 to reply here.

**Comment by zml2008** [comment]
Define reloading.
If this is with `\reload`, don't use `\reload` -- It's known to cause problems like this.
