### ISSUE TITLE
Ranks colors

### ISSUE THREAD

**Issue by MineServidorCraft** [PEXPlugins/PermissionsEx#2728]
Hi, i created a post with a error with Essencials and TownyChat where they create conflict. One dev of Towny tell me that i can create Names with colors ranks with PEX, but he cant help me. I don't really know how edit this to work like i want. I give you the post about chats colors for you read and tell me what i can do.
Thanx anyway.

Chat Colors Ranks: https://github.com/LlmDl/Towny/issues/2570

**Comment by Stormbow** [comment]
You don't need 2 tickets for 1 problem.

**Comment by Stormbow** [comment]
_**Official PEX guru here.**_
###### _(Not the programmer.)_

PEX doesn't have any chat management programming built into it.  PEX only provides a place to store the prefix and suffix for groups and players.  It's up to a chat management plugin to display that information in-game.

Personally, I have always used EssentialsChat and EssentialsXChat (when "EssentialsChat" was discontinued at Minecraft 1.8) to display prefixes and suffixes in-game.  Both of these plugins require the Vault plugin to be installed on the server before they will function correctly.

All of the standard [Color Codes](http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes) and [Formatting Codes](http://minecraft.gamepedia.com/Formatting_codes) can be used in the EssentialsXChat config.yml file.  Just replace the "section sign" (§) with an ampersand (&).  I can only assume these codes are also usable within the Towny plugin's config files.

**Comment by Stormbow** [comment]
Not a PEX issue after all.  It's all about formatting and color codes in TownyChat.
