### ISSUE TITLE
Only UIDD without names

### ISSUE THREAD

**Issue by JavituRec** [PEXPlugins/PermissionsEx#2731]
Hi,

I have two bungee cords instances, 1 is offline mode and 1 is online mode. I need that permissionex work only with uiid offline and online. Because my users can join from offline mode or online mode with same account then they have the rank in both proxies. If permissionex only work with uidd then this will be fix because they can same name but will be different uidd one for offline and other for online.

All the best. :)

**Comment by Stormbow** [comment]
You will need to read the Bungeecord doctumentation to figure out how to run offline mode servers.  PEX, on its own, does not allow offline mode servers.
