### ISSUE TITLE
groups prefixes and per world things

### ISSUE THREAD

**Issue by PipinellaPlays** [PEXPlugins/PermissionsEx#2732]
Hi,
I'm frustrated, tired and I cant possibly figure it out myself anymore and i do not know what is the problem or what am i doing wrong.

ok so i have server that has multiple worlds, i need to set different groups per world say, when a player is in survival world he would be default group called "member" but when he is in the world mines he would be in group called A and i needed those two groups to be default (automatically joins the member upon joining server)

i read in forums that you cannot set groups per world, so i said maybe set  different preffixes per world 
but nothing is working i have deleted the whole file started from 0 and nothing my member can do things they have all the permissions but not me the owner i have tried multiple times /pex user MYUSERNAME group set Owner and nothing,

i need you guys help i have 2 survival worlds 1 creative and 1 prison mine and i need to have different "ranks" preffixes or what ever they are called per world this is what i got so far
[http://pastebin.com/2rjfhvLy](http://pastebin.com/2rjfhvLy)
      
i need groups from A-Z each group to have the ability to rank up to the next letter, i have a rank up pluging that does that i just need to give the permission.node to the default group. help please

**Comment by Stormbow** [comment]
First and foremost, follow [this example](http://pastebin.com/8ZSHxauG) to get the correct basic formatting for your file.

Next, take a look at [these 2 example groups](http://pastebin.com/ieyQU7w8) to see how you would format their multiworld permissions.

There is one command to assign permissions to a groups:

`pex group <group> add <permission.node> [world]`

If you were to type `pex group Guest add modifyworld.*` into the server console, you would give the "Guest" group access to everything the "Modifyworld" plugin can do, on all worlds the server has.

If you were to type `pex group Guest add modifyworld.* Survival` into the server console, you would give the "Guest" group access to everything the "Modifyworld" plugin can do, but only on the world named "Survival".

Unfortunately, PEX 1.x does not support per-world default groups or per-world prefixes.  The per-world default groups may be possible in PEX 2.x versions, which are still in development.  All prefixes/suffixes are handled by your choice of chat management plugins; PEX does not do any chat management and only gives you a place to store prefixes/suffixes so your choice of chat management plugin can pulls from that location to display the prefixes/suffixes in-game.  (Note: Chat Manager and ChatEx plugins may not be fully compatible with PEX.)

**Comment by Stormbow** [comment]
Issue must be resolved.  OP hasn't responded in more than 7 days.
