### ISSUE TITLE
getting Permission Groups for Sponge

### ISSUE THREAD

**Issue by Nafi-SFT** [PEXPlugins/PermissionsEx#2737]
How do you get a specific player's permission group. I'm familiar with spigot's implementation which is:
`PermissionUser player = PermissionsEx.getUser(targetPlayer)`
`player.getGroups()`
but I'm unsure with Sponge. Is there a similar implementation for sponge? And if so, where can I find more documentation about it. 

Thanks

**Comment by zml2008** [comment]
Use Sponge's Permissions API -- It's documented in Sponge's documentation.

Generally, what you'd do is something like:

```java

public List<Subject> getGroups(Subject user) {
    final PermissionService serv = this.service; // pre-collected variable
    return user.getParents().stream()
        .filter(subj -> subj.getContainingCollection().equals(serv.getGroupsGollection()))
        .collect(Collectors.toList());
}
```
