### ISSUE TITLE
I do not have permission to do /pex

### ISSUE THREAD

**Issue by HeffaiDK** [PEXPlugins/PermissionsEx#2741]
I cant do /pex 
I am op
It saids: sorry, you do not have enough permissions

Please help!

**Comment by Stormbow** [comment]
Which version of Minecraft and PEX are you attempting to use?

Are there error messages in the startup log? (Copy the startup log to [Pastebin ](http://pastebin.com)and leave the link here.)

Show me your permissions.yml file.  (Copy it to Pastebin, leave the link here.)

**Comment by HeffaiDK** [comment]
I found out why! 
But thank you

**Comment by Stormbow** [comment]
What was the solution?

**Comment by HeffaiDK** [comment]
It was in the config you have to allow op commands.

**Comment by Stormbow** [comment]
[¯\_(ツ)_/¯](https://github.com/PEXPlugins/PermissionsEx/issues/2741#issuecomment-289204959)
