### ISSUE TITLE
Error with Permissions (Bukkit)

### ISSUE THREAD

**Issue by Zodwin** [PEXPlugins/PermissionsEx#2742]
I have a Bukkit server, and I just installed Permissions. I tried to follow the guide to set up the permissions, but when I started up  my server I got this:

[12:19:11 ERROR]: [PermissionsEx]
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Error loading permissions file!
=======================================================
Caused by: org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
 in 'string', line 22, column 16:
          prefix: '&0[&4M&cO&4D&0]&r '
                   ^
expected alphabetic or numeric character, but found [(91)
 in 'string', line 22, column 18:
          prefix: '&0[&4M&cO&4D&0]&r '
                     ^

[12:19:11 INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4

**] Edit by Stormbow: Removed most of the error log, unnecessary stuff. [**

This is my permissions file:

**] Edit by Stormbow: Moved permissons.yml file contents to [Pastebin](http://pastebin.com/gfyLPJm0). [**

EDIT: Just realized that when I copied and pasted my permissions file it doesn't show the spacing. I'm not sure how to fix that though.

**Comment by Stormbow** [comment]
Your permissions.yml file does not follow [this example](http://pastebin.com/8ZSHxauG).

Once your file follows that example, test the server again and post here if you're experiencing continuing PEX problems.

**Comment by Zodwin** [comment]
I have tried to model my file after that example now (I have never really done this before, so sorry about the confusion), and I still have an error loading the permission file. This is it now:

groups:
  Member:
    options:
      default: 'true'
      build: 'true'
      prefix: 'Member '
      suffix: ''
      rank: '900'
      rank-ladder: Main
      weight: '900'
    inheritance: []
    permissions:
    -modifyworld.*
    -nicknames.nick.self
    -iDisguise.help
    -iDisguise.undisguise
    -iDisguise.mob.chicken
    -iDisguise.mob.cow
    -iDisguise.mob.llama
    -iDisguise.mob.pig
    -iDisguise.mob.rabbit
    -iDisguise.mob.sheep
    -redprotect.user
    -redprotect.own.tp
    -clearchat.clearmychat
  Mod:
    options:
      default: 'false'
      build: 'true'
      prefix: 'Mod '
      suffix: ' the Scary'
      rank: '200'
      rank-ladder: Main
      weight: '200'
    inheritance:
    - Member
    permissions:
    -iDisguise.mob.creeper
  Admin:
    options:
      default: 'false'
      build: 'true'
      prefix: '&0[&4M&cO&4D&0]&r '
      suffix: ' the Awesome'
      rank: '100'
      rank-ladder: Main
      weight: '100'
    inheritance:
    - Mod
    permissions:
    -permissions.*
    -nicknames.nick
    -nicknames.lookup
    -iDisguise.help
    -iDisguise.*
    -redprotect.*
    -clearchat.*
  Owner:
    options:
      default: 'false'
      build: 'true'
      prefix: '&0(&8D&7R&8A&7G&8O&7N&0)&r '
      suffix: ' the Almighty'
      rank: '1'
      rank-ladder: Main
      weight: '1'
    inheritance:        
    - Admin
    permissions:
    -permissions.*
    -nicknames.nick
    -nicknames.lookup
    -iDisguise.help
    -iDisguise.*
    -clm.admin
    -redprotect.*
    -clearchat.*
    -'*'
schema-version: 1
users:
  Zodwin:
    group:
    - Owner
    permissions:
    -permissions.*
    -nicknames.nick
    -nicknames.lookup
    -iDisguise.help
    -iDisguise.*
    -clm.admin
    -redprotect.*
    -clearchat.*
  WyrmWizard:
    group:
    - Admin
    permissions:
    -permissions.*
    -nicknames.nick
    -nicknames.lookup
    -iDisguise.help
    -iDisguise.*
    -redprotect.*
    -clearchat.*
  QueenDragonling:
    group:
    - Admin
    permissions:
    -permissions.*
    -nicknames.nick
    -nicknames.lookup
    -iDisguise.help
    -iDisguise.*
    -redprotect.*
    -clearchat.*
  JediWolfBook:
    group:
    - Admin
    permissions:
    -permissions.*
    -nicknames.nick
    -nicknames.lookup
    -iDisguise.help
    -iDisguise.*
    -redprotect.*
    -clearchat.*

Some things I thought might be causing the problem:
-Do I have options and then name section under users? I have a nickname plugin installed and was not sure if that would mess up the nicknames

**Comment by Stormbow** [comment]
Your permission nodes are still wrong.  It's not

`-permission.node`

It is 

`- permission.node`

**Comment by Zodwin** [comment]
The plugin now loads up correctly. Do I have to have a different plugin installed to allow chat prefixes/suffixes to show up in chat?

**Comment by Stormbow** [comment]
Yep.  You need a chat management plugin.

Since almost everyone runs [Spigot](https://www.spigotmc.org/) servers, they use [EssentialsX](http://ci.drtshock.net/job/essentialsx/) for the basic server commands, and [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) handles their chat management features (prefixes, suffixes, chat coloring).

**Comment by Zodwin** [comment]
Should I switch to a Spigot server, or would I be able to run those same plugins on my Bukkit server?

**Comment by Stormbow** [comment]
Technically, "Bukkit" (and "CraftBukkit") was discontinued at Minecraft 1.8 because one of the contributors was a total dickhead and claimed copyright infringement against everyone else on the project for using the code he contributed.  Some people are updating it, but I can't testify to them being any good at it since I don't use them, so I can't technically recommend using either "Bukkit" or "Craftbukkit".

Spigot, on the other hand, is created by a group that has taken precautions against the copyright bullshit that the other author pulled on Bukkit, so I expect it will be around and updated properly for a very long time.  I'm also running Spigot on my 1.11.2 server, so I can say it works properly.

The choice of server wrapper (which is what "Bukkit", "Craftbukkit", "Spigot", and others are called) is entirely up to you...

**Comment by Zodwin** [comment]
Could I use the same Permissions jar file and permissions file that I already have if I switch to Spigot? Or would I have to rewrite them?

**Comment by Stormbow** [comment]
You can keep those if you use Spigot.

**Comment by Zodwin** [comment]
Ok thanks! Gonna go ahead and close the thread now (and switch to Spigot)

**Comment by Stormbow** [comment]
You will want to make sure any plugins you're using are compatible with Spigot.  (The EssentialsX I linked to you is too, of course.)

You're welcome.  Have fun!

**Comment by Stormbow** [comment]
You can find all the Spigot-specific plugins [right here](https://www.spigotmc.org/resources/).
