### ISSUE TITLE
My PEX Isn't working.

### ISSUE THREAD

**Issue by GrassyPlayz** [PEXPlugins/PermissionsEx#2744]
Hello!

I've just made my new server with a couple plugins.

For some reason, when I do /plugins, it shows PEX yet it's in red, and /pex does not work.

If someone could help, it'd be greatly appreciated.

Plugins: DeathMessagesPrime
PermissionsEx [In red]
Oldschoolkill
ChatCo
Random_Spawn
NetherRoofProtect

It's an Anarchy server if you're wondering the type of server.

Image of the red PEX - http://imgur.com/a/4QiIW

Here's the server log from when I turn on the server - directly from "latest.log" - http://pastebin.com/yx3Lf3Df

The "config.yml" file - http://pastebin.com/bpm7JwAy

The "permissions.yml" file - http://pastebin.com/5vJYZsXr

And there you go. If anyone knows how to fix this issue, please let me know.

Thanks Alot,

~Grassy

EDIT -- Found out the issue; the "- bukkit.command.tps" was preventing it from working somehow. If someone is able to show me how to add "/tps" to non-opped users, it'd be greatly appreciated.

**Comment by Stormbow** [comment]
PEX typically shows up in red when there is an error (or more) in the permissions.yml file.

PEX found an error in your file:

> Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
> in 'string', line 1, column 1:
>    groups:
>    ^
>expected <block end>, but found BlockEntry
> in 'string', line 7, column 1:
>    - bukkit.command.tps
>    ^

but there is no error showing in the permissions.yml file you linked here.  Did the file change somewhere between the tile the log recorded the error and you pasted it?

Be sure you're only using the permissions.yml file that is inside the plugins\PermissionsEx folder.  The permissions.yml file in your server's root directory should not have anything at all within it.  (If yours does, delete the contents, save the file, and close it.)

**Comment by GrassyPlayz** [comment]
So, I seemed to have kinda figured it out.
The "- bukkit,command.tps" is what seems to be creating the errors.
I removed it, and it worked fine.

But I still want the default user to have access to "/tps".

Any tips?

**Comment by Stormbow** [comment]
Actually...  `bukkit.command.tps` is not a real permission node, and /tps is not an accociated "Vanilla" command.  (You can see all the "Vanilla Permissions" [right here](http://bukkit.gamepedia.com/CraftBukkit_Commands).

What did you expect that node and command to be?

**Comment by GrassyPlayz** [comment]
I wanted /tps, and it showed me this : https://www.spigotmc.org/wiki/spigot-commands/
If you look, the second one is "/tps" with "bukkit.command.tps"

I'm new to PermissionsEx and Spigot, if you could show me how to properly "mount" that it'd be greatly appreciated.
Thanks!

**Comment by Stormbow** [comment]
Oh!  I didn't see Spigot when I first looked at the console log.

That command is actually not information that normal players on a server ever really need to see— and I'd bet 99% of them have no idea what a "timing" is.  It's an admin command to track how much your server is lagging.  If you want to give that out, more power to ya I guess, but it's not usually a player command.

Try this— type `pex group default add bukkit.command.tps` into the console to add the node to the group via command.  Then type `pex reload` into the console to reload the PEX plugin.  After that, stop the server fully, and start it again to see if you get the error you got originally.

**Comment by GrassyPlayz** [comment]
Wow! Many thanks to you.
Really appreciate it, man
Thanks for the support!

**Comment by Stormbow** [comment]
You're welcome.  Let me know if that command works in-game (`/tps` while in-game).  If it works, you or I can close the ticket.

**Comment by GrassyPlayz** [comment]
Tried it in game, works perfectly!
You can close it, not sure how to close it (lol).
Thanks again, have a nice day/night!

**Comment by Stormbow** [comment]
You're welcome. :)  Have fun!
