### ISSUE TITLE
My PEX wont work...

### ISSUE THREAD

**Issue by N3ther** [PEXPlugins/PermissionsEx#2745]
Basically, everytime I do any PEX command, nothing happens. How do I fix this?

**Comment by Stormbow** [comment]
Start by looking through your server console for error messages when you start the server.

You probably have errors in your permissions.yml file.

Which version of Minecraft and PEX are you running?

**Comment by N3ther** [comment]
I think I found the problem in my console, I don't have vault installed, so I'm doing that now

**Comment by N3ther** [comment]
Ok, now whenever I do /pex, it just shows the PEX version...

**Comment by Stormbow** [comment]
You should be getting the entire PEX commands list when you type `pex` into the console or `/pex` in-game.

**Comment by Stormbow** [comment]
Problems solved?

**Comment by Stormbow** [comment]
No replies from OP in almost a week.  Case closed.
