### ISSUE TITLE
Accidentally did something to my name and now i cant fix it....

### ISSUE THREAD

**Issue by gumguy99** [PEXPlugins/PermissionsEx#2746]
Here is what my name looks like now.. I also tried to undo it using the suffix and prefix thing but that didn't help
https://gyazo.com/1611088a4ab043a3ef582de15ced8da2
Here is server log

**] Edit by Stormbow: Removed server log / wall of text / train wreck. [**

**Comment by Stormbow** [comment]
Copy your server log and permissions.yml file to [Pastebin ](http://pastebin.com)and leave links to each in this thread.

**Comment by gumguy99** [comment]
http://pastebin.com/8W2FjZQD

**Comment by gumguy99** [comment]
sorry... here is the right one

http://pastebin.com/CQpw28b9

**Comment by Stormbow** [comment]
Which version of Minecraft and PEX are you running?

**Comment by gumguy99** [comment]
Minecraft version 1.11.2
Pex Version 1.23.4

**Comment by Stormbow** [comment]
Try [this file](http://pastebin.com/8Ur5jy6s).

I corrected all of the mistakes I saw since the file was pretty small.

**Comment by Stormbow** [comment]
Errors I found:

• The `schema-version: 1` line was in the wrong place.

• All groups had `options:` settings outside of the `options:` section.

♦ Your groups inherit from a group named "Guest" which does not exist on the server, but I didn't remove that group from your inheritances (in case you planned on adding it to the server).

**Comment by Stormbow** [comment]
One error I missed and didn't fix:

• Line 41 (in the file I provided): `towny.wild.block.[block id].*` is not a real permission node.  You'd need to replace `[block id]` with an actual block id number.

**Comment by gumguy99** [comment]
NVM i fixed it thank you though

**Comment by Stormbow** [comment]
All good now?  You can close the ticket under this area you type in.
