### ISSUE TITLE
How does PEX handle UUID

### ISSUE THREAD

**Issue by WyRe** [PEXPlugins/PermissionsEx#2747]
I would like automate the registration process to add my wordpress database users automatically to PEX mysql database, Should I generate all certain rows in three tables? Or just would be necessary add in a specific row and PEX will automatize the user group inclusion and will generate the rest of rows in other two tables? 

I case of I need generate all rows ... To get UUID should I extract it from usercache.json using .js script?

Thank you so much.

**Comment by zml2008** [comment]
You have to add all three rows. Remember that the database format can change with version updates too, so make sure you check you are doing things correctly after each PEX update.

Get UUIDs using mojang's API -- there are lots of examples on the internet for how to use this API.
