### ISSUE TITLE
Group add/del/set permission nodes

### ISSUE THREAD

**Issue by WyRe** [PEXPlugins/PermissionsEx#2749]
I think the commands

- `pex user <user> group add <group> [world] [lifetime]`
- `pex user <user> group remove <group> [world]`
- `pex user <user> group set <group> [world]`

Should be managed by different permission nodes, or at least `add`/`remove` should be different node of `set`. I'm using an invitation system so my _citizens_ users can set new people in _Citizens_ group, but in this way also they can remove them, that could be problematic if the citizens fight between them. My idea is what _citizens_ can add their friends if they enter the server for first time but a moderator intervention be required to remove the user from _citizens_ group.

One way what I've thought to workaround the issue is create _visitor_ group and use `promote`/`demote` commands but that's much more messy to people, who should performance several commands.

What do you think? thank you for the interest.

**Comment by WyRe** [comment]
I've just discovered the flag default to groups.

**Comment by WyRe** [comment]
It's still valid, because _citizens_ cannot promote to _citizens_ the people in _visitors_ default group.

**Comment by Stormbow** [comment]
This has already been suggested multiple times and is on the list of things @zml2008 might do if he gets bored.

**Comment by WyRe** [comment]
@Stormbow what do you recommend me to manage this?

**Comment by Stormbow** [comment]
The very blunt answer is: Don't give out admin-level commands to non-admins.

You're actually better off using plugins like AutoRank to let users promote themselves without having any access to PEX commands.  AutoRank will let users see what they need to do to be promoted to the next rank and they can use an AutoRank command to accomplish their own promotion once they qualify.

**Comment by Stormbow** [comment]
You can choose from an almost limitless number and variety of requirements for the user to be promoted.

For example, I required users to have played on the server for a month, voted 30 times, and they had to own a stack of gold blocks (which they could acquire in multiple ways— like mining, nether farming, buying gold nuggest/ingots/blocks from the admin shop) to promote themselves to "Noble" (where they could then own land and start their own town) on my server.

**Comment by WyRe** [comment]
@Stormbow thank you so much :)

**Comment by Stormbow** [comment]
You're welcome.  :)  Have fun with it!
