### ISSUE TITLE
Why not updated?

### ISSUE THREAD

**Issue by SourcePowered** [PEXPlugins/PermissionsEx#2750]
Why has it not been updated for so long?

**Comment by EmanYm** [comment]
I'd put the answer at school, employment or life being priority.

**Comment by Stormbow** [comment]
What is not updated?

PEX 1.23.4 works on 1.11.2 servers.

**Comment by SourcePowered** [comment]
@Stormbow I'm using Sponge...

**Comment by Stormbow** [comment]
Why?

**Comment by zml2008** [comment]
Because I haven't had time to work on it. If you want changes, we accept pull requests.
