### ISSUE TITLE
Negate Perms

### ISSUE THREAD

**Issue by Sunboyz21** [PEXPlugins/PermissionsEx#2752]
So Stormbow fixed my Permissions.yml file and everything works.

However, I'm wondering, is the proper way to negate a permission this; 

`- -maxbans.immune`
or this; 
`- - maxbans.immune`

Basically, Is it with a space after the second - or not.

Thanks,
Sunboyz
(PS, Stormbow yes I did put the negations in front of the global wildcards this time :p)

**Comment by Stormbow** [comment]
Super Stormbow to the rescue!  :D 

`- -maxbans.immune` is correct.

**Comment by Sunboyz21** [comment]
Thanks!
