### ISSUE TITLE
Entering in permissions exactly how the guides says to, but nothing works

### ISSUE THREAD

**Issue by Aperture-Turret** [PEXPlugins/PermissionsEx#2753]
Hey guys, I'm entering in commands exactly how your guide at https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup says I should, but no matter what I do the permissions I set have no effect and nobody is allowed to do anything.

This is what my permissions file looks like: 

https://pastebin.com/bwDYpeR9

I've tried two different accounts, a user group, and the default group, but none of those permissions I set have any effect.

What am I doing wrong? Thanks

**Comment by zml2008** [comment]
Is your server in online mode? Make sure you are using online mode UUIDs with an online mode server.
