### ISSUE TITLE
Certain Pex group not working please help

### ISSUE THREAD

**Issue by gumguy99** [PEXPlugins/PermissionsEx#2755]
The only problem I'm having is that my group Valued can't do any of the commands listed in permissions.

**] Edit by Stormbow: Moved permissions.yml file contents to Pastebin: https://pastebin.com/1qGdQtCG [**

Here is everything.  I would really appreciate if someone could help me out.

**Comment by Stormbow** [comment]
Three major problems found and corrected for you:

• The permissions.yml file was out of order; the `schema-version: 1` line was after the `users:` section.  (It should come before.)

• Many groups' `options:` settings were in the wrong place. (`build: true`, for example, goes under the `options:` section tag for each group; that setting is actually only used for EssentialsAntiBuild / EssentialsXAntiBuild plugin.)

• Two groups were missing the `inheritance:` section that's required in every group from Minecraft 1.9 onward.

I fixed all of these for you in this file: https://pastebin.com/5242Uc8Q

You can see an example of a more complete permissions.yml file [right here](https://pastebin.com/8ZSHxauG).

**Comment by Stormbow** [comment]
You may want to reconsider the group name "Shiny+" (and use ShinyPlus) because some plugins will not recognize the + symbol and won't be able to find that group on the server.  You can keep the prefix as "Shiny+"; that won't bother anything as far as I'm aware.

**Comment by gumguy99** [comment]
Thank You, I only have one problem left I'm sure you're familiar with the plugin essentials and most of its plugin nodes. The only problem I'm having now is the /extinguish every time I try it in The Valued pex group it doesn't seem to work. It gives me a message like "are you sure you're permitted to do this or are you sure you're in the right mode." I'm not quite sure how to fix this problem and if you could help me on that I would be grateful. Also, thank you for answering all of my previous questions I really appreciate It :)

**Comment by Stormbow** [comment]
> "are you sure you're permitted to do this or are you sure you're in the right mode."

I think this is a WorldEdit error caused by incorrect permissions.  You can check it out using [PEX's Debug Mode](https://pastebin.com/vhcWR2yK).

**Comment by Stormbow** [comment]
No reply from OP in more than 7 days.  Issue must be resolved.
