### ISSUE TITLE
How to Actually Integrate with PEX

### ISSUE THREAD

**Issue by Jimmeh94** [PEXPlugins/PermissionsEx#2758]
Hey there!

I'm trying to add PermissionsEx to my plugin. I've managed to find the correct Maven repo and dependency through messing around on Jenkins, however, I now can't figure out how to get an instance of PermissionsEx. I can see that the "Wiki/Integrate with PEX" is definitely outdated and can't seem to find another tutorial. The only thing I need to do is promote players to groups, so any suggestions here would be greatly appreciated!

Thanks! :D

**Comment by smartin1018** [comment]
Same Issue, the Wiki is running Spigot 1.6.4 and will not build for me. Any 1.10/1.11 versions?

**Comment by Jimmeh94** [comment]
Well, I need to get this done so since all I need to do is run a command to promote players and such, I'm just doing "Bukkit.getServer().dispatchCommand()" that way I don't actually need this API. Hope that can help you!

**Comment by smartin1018** [comment]
Nope, I need their identifiers

**Comment by zml2008** [comment]
Use Vault

**Comment by smartin1018** [comment]
Vault doesn't provide a way to get a permissionuser, last time I checked. Mind updating the wiki?
