### ISSUE TITLE
Not a problem, but a GREAT idea!

### ISSUE THREAD

**Issue by PsychoThePsycho** [PEXPlugins/PermissionsEx#2759]
conbining mysql and file.
Allowing some perms to be shered trough sql, while some are for each server.^
Lets say i want the same prefix on all servers: MySql
i want perm1 for rank1 on server 1, but not on server 2: file

Hope you can find a way to do this :)

**Comment by EmanYm** [comment]
Wouldn't it be easier to have something like "rank1-1" for server 1 and "rank1-2" for server 2?  That way you can change the nodes in each group separate on each server.

I have nodes for 20+ mod/plugin set for three servers in one database.  Players can have the same "rank" on each server, but only have access to fly on server 2, and worldedit on server 3.

This is just how I handled the problem.  Someone else might have another suggestion.

**Comment by zml2008** [comment]
This is supported in PEX 1.x with the multi backend, and in PEX 2.x with server-tag contexts.
