### ISSUE TITLE
Is there any way to avoid autocomplete?

### ISSUE THREAD

**Issue by Stormbow** [PEXPlugins/PermissionsEx#2762]
#2757 is the most recent iteration of this problem.

Minecraft 1.11.2 and PEX 1.23.4

**tl;dr:** A server has groups named "Assistant" and "Administrator".  When issuing the command `pex group "A" create`, the server gives an autocomplete related error message and the group named "A" is not created.

Is there any way to avoid this?

**Comment by zml2008** [comment]
If you want to provide an exact group name, use the prefix `#` in front of the name in the commands (https://github.com/PEXPlugins/PermissionsEx/blob/1.23.x/src/main/java/ru/tehkode/permissions/bukkit/commands/PermissionsCommand.java#L153) and autocomplete won't be performed

**Comment by Stormbow** [comment]
Would that mean `pex group #A create` or `pex group "#A" create'`?
