### ISSUE TITLE
Players cannot /spawn

### ISSUE THREAD

**Issue by AceAI2** [PEXPlugins/PermissionsEx#2764]
https://pastebin.com/g38PuCz1 This is my permissionsEx permission.yml config ,
Players have the essentials.spawn and i added randomly essentials.spawn.self just to make sure they have it , but players still cant do /spawn for some reason , Ive tried removing the spawn.self , still no change , tried rewriting, still no change , no clue whats going on , would love some help , Thanks!

**Comment by Stormbow** [comment]
Which plugin is handling your spawn feature?

♦ EssentialsX?  Then you'll need [EssentialsXSpawn](http://ci.drtshock.net/job/essentialsx/) installed on the server.  (This website is currently down, so if you need this file, you'll have to keep trying the website until it comes back online.)

♦ That weird "Spigot Essentials" mess?  Then you'll need [EssentialsSpawn-2.x-SNAPSHOT.jar](https://hub.spigotmc.org/jenkins/job/spigot-essentials/).

♦ Something else? Check their documentation to determine the actual permission node that's needed.

If you have the correct plugins installed and the correct permission nodes assigned, check out [PEX Debug Mode](https://pastebin.com/vhcWR2yK) to find out what other plugin(s) may be interfering with the command.

**Comment by AceAI2** [comment]
Thank you so much , once again storm :) Used HubThat and thought i should just use the normal node. lol.
Thanks!

**Comment by Stormbow** [comment]
You're welcome. :)
