### ISSUE TITLE
Pex user "Nme" add *   doesn't work please help.

### ISSUE THREAD

**Issue by Apperation** [PEXPlugins/PermissionsEx#2765]
Pex user NAME add *  doesn't work please help me I need my ranks up and ranning

**Comment by Stormbow** [comment]
> Pex user NAME add * doesn't work please help me I need my ranks up and ranning

`pex user Stormbow add *` just worked for me on my 1.11.2 Spigot server using PEX 1.23.4.

----

Which version of Minecraft are you using?

What server wrapper are you using?  (Spigot, etc.)

Are there any errors in the console when you start the server?  (Show me the log; copy it to [Pastebin](http://pastebin.com); leave the link in this thread.)

Where are you typing "`Pex user NAME add *`?  (Are you typing it exactly like that?)

Show me your current permissions.yml file.  (Copy it to [Pastebin](http://pastebin.com); leave the link in this thread.)

**Comment by Apperation** [comment]
Im typing it in console and it shows no errors its just blank,I'll do the
rest now

**Comment by Stormbow** [comment]
I updated my [previous comment](https://github.com/PEXPlugins/PermissionsEx/issues/2765#issuecomment-294322949) with more details.  Don't miss those.

**Comment by Apperation** [comment]
I'm using Servermine

**Comment by Stormbow** [comment]
> I'm using Servermine**r**

That's a server host.  That information isn't actually relevant at the moment. :)

**Comment by Apperation** [comment]
Sorry I'm new to the whole server thing, I just followed the guids on every
pkugin but I'm struggling =/

**Comment by Stormbow** [comment]
No problem.  Just start out small and then build up to having all the plugins you want after you get used to the setting up the very basic plugins (which are usually PEX and EssentialsX for people running Spigot servers).

**Comment by Apperation** [comment]
Yeah,but I cant use pex if I cant set my account up with the perms,I did
everything I'm so tired xD

**Comment by Stormbow** [comment]
Take a nap, come back to it later.  ;)

**Comment by Apperation** [comment]
Do you have steam or a means for me to message you more socially for help
if thats ok?

On 16 Apr 2017 1:19 AM, "Stormbow" <notifications@github.com> wrote:

Take a nap, come back to it later. ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PEXPlugins/PermissionsEx/issues/2765#issuecomment-294323432>,
or mute the thread

**Comment by Stormbow** [comment]
At the bottom of each email you're getting, there's a link to view your ticket on Github.  That's the best place to post comments and get more help with PEX.

On rare occasions, I have a Discord voice chat server to use and help people, and I'll sometimes visit their servers to help them get stuff fixed.

**Comment by Apperation** [comment]
Oh ok cool,thanks for the help sorry for bothering you xD

**Comment by Stormbow** [comment]
No bother. :)  That's what I'm here for.

**Comment by Stormbow** [comment]
You can still post here.  I just closed it so it's not on the open tickets list.  (I'll still get emails when you comment here.)

**Comment by Apperation** [comment]
Thanks a lot man I really appreciate it

**Comment by Apperation** [comment]
Hey man sorry to bother you again but I tried everything is there maybe a
way for you to help me with pex, my pex user Name add * doesn't work no
matter what I do...

**Comment by Stormbow** [comment]
No bother.  ;)

What **_exactly_** are you typing?

**Comment by Apperation** [comment]
Well I need to add my account so I'm typing  in console pex user Myname add
*

**Comment by Stormbow** [comment]
Which version of PermissionsEx are you using?

**Comment by Apperation** [comment]
Latest version

**Comment by Stormbow** [comment]
You need to be very specific when you answer questions while you're trying to get help.

For example, `pex user MyName add *` is not the same as `pex user Stormbow add *` when I tell someone what command I am typing into the game.

Also, saying "Latest version" doesn't actually tell me which version you're using because your server host may be giving you a file that is not actually the "latest version".  When you start your console, text should be printed to the screen there that will tell you the version you're running if you can't see it on the actual plugin file name.

**Comment by Apperation** [comment]
Ok the command to give a user all the permissions isn't working /pex user
Name add *
And I'm running PermissionsEx version 1.11

**Comment by Stormbow** [comment]
Your Minecraft name is "Name"?  I don't think so.  ;)

**Comment by Stormbow** [comment]
Also, PEX doesn't have a "version 1.11".

**Comment by Apperation** [comment]
Ik I'm just entering name to show you where my names goes

**Comment by Apperation** [comment]
It shows I'm running version 1.11, what version should I be running then?

**Comment by Stormbow** [comment]
I'm starting to think you're just screwing with me now.

You seriously can't tell the difference between a Minecraft version and a plugin version?

**Comment by Stormbow** [comment]
You are literally taking a number from one line of the console and the word PermissionsEx from a different line of the console and somehow attributing that number to be the version of PEX that you're using.

I have no idea how that's humanly possible, so you must be screwing with me.  (You know April 1st is the only day in April for pranks, right?)

**Comment by Apperation** [comment]
Sorry to have bothered you, I'm dead serious btw I'm probably just a retard
goodbye and thanks for the help again
