### ISSUE TITLE
PermissionsEx Problems

### ISSUE THREAD

**Issue by Luddy92423** [PEXPlugins/PermissionsEx#2769]
So, I have been working for hours and hours for the past 7 months on trying to configure PermissionsEx ranks, and I cant seem to be able to ever get prefixes to work. They have worked in the past, but not anymore. Help would be greatly appreciated. Here is what my permissions.yml folder looks like:

**] Edit by Stormbow: Moved permissions.yml to [Pastebin](https://pastebin.com/A0K0MMDW). [**

**Comment by Stormbow** [comment]
_(You don't have to lie about how long you've been trying to get PEX working.)_  ;-)

First and foremost, your permissions.yml file should follow this example as to where everything (i.e., the "options" like `build: true`, the prefixes, etc.) goes in each group's listing and where the `schema-version: 1` line goes.  As of Minecraft 1.9, all of this formatting and placement is mandatory.

Next up, the display of prefixes and suffixes in-game is actually handled by a chat management plugin, not PermissionsEx.   PEX only gives server owners a place to define these variables.

Since most people are running [Spigot servers](https://www.spigotmc.org/) these days, and using [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) to handle all of the basic Admin commands, they would also use [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) (plus [Vault](http://dev.bukkit.org/bukkit-plugins/vault/), which is a dependency of EssentialsXChat) to handle their prefixes and suffixes.

If you still need help after reading the above, copy your server startup log— that's everything printed on the server console from the moment the server starts, through the point where text stops printing on the screen and you see a message similar to "Done!" printed on the screen —to [Pastebin](http://pastebin.com) and I can help you out some more.

**Comment by Stormbow** [comment]
Missing link added to "this example": https://pastebin.com/8ZSHxauG

**Comment by Luddy92423** [comment]
Okay. First, thanks for getting the prefixes right with the file on Pastebin (I wasn't able to do that). Next, I am fairly sure the actual ranks/permissions are working because of what the users can do in-game. (My server is in 1.11.2). I did hear about something like EssentialsXChat is associated with prefixes and suffixes. Now I was wondering if you could help me find the directory of those files (because it is probably like one setting) because I might not even have it. I couldn't find it under essentials (in plugins). If this may help, here is my startup log (I know there are some random plugin issues to fix as well): https://pastebin.com/qBhfBBGh
Thanks in advance!
(P.S. I wasn't lying, just didn't work on in every day :D)

**Comment by Stormbow** [comment]
No sweat. :)

The EssentialsXChat config.yml file is in the plugins\Essentials folder, and you'll be looking to make your file match [these sections](https://pastebin.com/eHCCcNuY) that I cut out of my file.  (Do something similar for the 2nd section, to suit your server best, of course.)

It's important to note that "Essentials v2.0.1-b370" (line 27 of your console log) doesn't actually include the "EssentialsXChat-2.0.1.jar" file found [right here](https://ci.drtshock.net/job/essentialsx/).  You'll have to download that part separately.  You already have Vault, so all you'll need to do after the download is hit that config.yml mentioned above with your custom settings.

**Comment by Luddy92423** [comment]
I now am having some weird issues.... I downloaded essentialsxchat and put it in the plugins folder and ran my server, now all of essentials doesn't work. I did, however look at my config.yml file in essentials and there was nothing about chat and it is only around 350 lines long, and I couldn't find anything. Here is my config.yml file.
https://pastebin.com/y4S06dxG

**Comment by Stormbow** [comment]
Stop the server, delete that plugins\Essentials\config.yml file, then start the server and the server will make a new one.  Check the new file to see if you've got the correct innards.

**Comment by Stormbow** [comment]
Has anything changed recently in your plugins\PermissionsEx\permissions.yml file?

**Comment by Luddy92423** [comment]
Let me see and I'm deleting the file right now....

**Comment by Luddy92423** [comment]
My permissions file has not changed.

**Comment by Luddy92423** [comment]
Woah, the config.yml file is very different! It was like this a long time ago. Okay, I will try troubleshooting with the tips you gave me! Thanks!

**Comment by Stormbow** [comment]
You're welcome.

What **exactly** was not working in the PEX permissions?

**Comment by Luddy92423** [comment]
I am troubleshooting as we speak, but do you mean what is not working after I downloaded chat or as of like a week ago?

**Comment by Stormbow** [comment]
[Right here](https://github.com/PEXPlugins/PermissionsEx/issues/2769#issuecomment-296445499) you said "all of PEX doesn't work".

**Comment by Luddy92423** [comment]
Oh yeah the plugin was red in /pl

**Comment by Stormbow** [comment]
OK.  That means there's an error in the permissions.yml file.  Pastebin that for me and I can look for the problem.

**Comment by Luddy92423** [comment]
But it started happening right when I loaded my server after I downloaded essentials chat. I finished troubleshooting issues... lemme test my server out.

**Comment by Luddy92423** [comment]
Here is my permissions.yml file:
https://pastebin.com/89B4T3NT

**Comment by Stormbow** [comment]
Oh yeah.  LOTS of errors.  Give me a couple minutes to list them all.

**Comment by Luddy92423** [comment]
Oh shoot

**Comment by Luddy92423** [comment]
Also, I was wondering if this part (groupformats) of my essentials file is right?

  group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'
  
  group-formats:
     Guest: '[&7{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Legendary: '[&7{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Mod: '[&c{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Admin: '[&4{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Owner: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Grand Owner: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Co-Owner: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Dev: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Dev-co: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'

**Comment by Luddy92423** [comment]
Also, I was wondering if this part of my group formats in essentials config.yml is right?

  group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'
  
  group-formats:
     Guest: '[&7{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Legendary: '[&7{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Mod: '[&c{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Admin: '[&4{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Owner: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Grand Owner: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Co-Owner: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Dev: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'
     Dev-co: '[&5{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'

**Comment by Luddy92423** [comment]
Is this essentials group formats part right? https://pastebin.com/CsWWVjZj

**Comment by Stormbow** [comment]
Corrected permissions.yml file: https://pastebin.com/GVpfPBE2

Corrected EssentialsXChat file: https://pastebin.com/UX1GhyCP

Take a very close look at the permissions.yml file for very important changes that I made.

• The `schema-version: 1` line should be before the `users:` section, so I moved that.

• All of the groups' `options:` sections were missing, so I added those.

• The "Guest" group was missing an `inheritance:` section, so I added that.

• Several groups and sections were missing colons, so I added those.

• There was a blank line in the file, so I removed that.

• Most of the `users:` section entries had data that has no effect at all, so I removed that.

• You changed the group name "Moderator" to "Mod" (when you configured the chat prefixes), so I changed the permissions file to reflect that change.

• Group names like "Grand Owner" and "Co-Owner" and "Co-Dev" won't be recognized as actual groups on the server by some plugins and/or some features of popular plugins, so I renamed all of those.  (I also renamed them for the users that belonged to them.)

There may be other errors that I quickly fixed too, stuff I forgot while I was writing this comment.

----

**IMPORTANT NOTE:** You have about 10 people on your server that have the "global wildcard" (see line 69 of the permissions file to see what that is) which allows them to delete the entire permissions file and do other catastrophic things to the server.  This is an **_extremely_** bad idea unless all these people are people you know in real life, trust extremely, and you can go over to their house and _kick their ass_ if they delete your server.

----

**Comment by Stormbow** [comment]
About half of the stuff I corrected for you (above) was "fatal error" stuff that would prevent PEX from working.

**Comment by Luddy92423** [comment]
Ok. I just finished what you said... loading server

**Comment by Stormbow** [comment]
Oh, by the way, the reason I removed the `[&7{GROUP}&r]` type code from your EssentialsXChat configuration was because `{DISPLAYNAME}` = Prefix + Username + Suffix all added together.  So, the way you had it, `Guest: '[&7{GROUP}&r] {DISPLAYNAME}&r: {MESSAGE}'` would chat like this:

    [Guest] [Guest] Stormbow: words

**Comment by Stormbow** [comment]
All good?

**Comment by Luddy92423** [comment]
Thank you! It works now! Except.... I know some people on my server, is there a way I can op someone without the - '*' "global wildcard" thing? And the ranks are working :)

**Comment by Stormbow** [comment]
OP is actually intended for "Vanilla" servers that don't use any plugins at all.  The best you can do with plugins is to assign the specific permission nodes that you want your Admins and Mods to have.

Or, at the very least, negate access to the PermissionsEx plugin completely.  For example:

```
  Dev:
    options:
      build: true
      prefix: '&4[Dev]'
      suffix: '&b'
    inheritance: []
    permissions:
    - -permissions.*
    - '*'
```

The command is `/pex group <group> add -permissions.*`.  Be sure the negation is at the top of the list for the group.  (And that's easier to accomplish by opening the file in Notepad or `Notepad++` and just typing it in, with the correct indentation.)

If you don't know all the people in any other groups, remove PEX access from them too.

Typically, I will give PEX access directly to _people_ who I know need it on a server— `pex user Stormbow add permissions.*`.  No groups _actually_ need it, and it's actually somewhat counterproductive to give it to a group— if you move yourself out of "GrandOwner" to "Guest" to test something, you've just lost access to PEX because it was "GrandOwner" that had access, not you specifically.

**Comment by Stormbow** [comment]
You can still reply here and I'll still get emails about comments here.  I'm just going to close the ticket to take it off the open tickets list.

**Comment by Luddy92423** [comment]
So, doing - -permissions.* negates access fully to any in-game commands
that could potentially mess up the file?

**Comment by Stormbow** [comment]
Yep.

The global wildcard `- '*'` gives the group _absolutely every permission node_ on the server, and the negation `- -permissions.*` removes access to anything related to PermissionsEx.  That way, no one can use the PEX Commands that can remove groups (`pex group Guest delete`, for example), essentially destroying the whole server by removing all the groups.

**Comment by Luddy92423** [comment]
Okay! Thanks... now that I know that, I think everything is good, and
I can successful customize my rank prefixes to my liking. :)

**Comment by Stormbow** [comment]
You're welcome.  Have fun!
