### ISSUE TITLE
Permissions not Working

### ISSUE THREAD

**Issue by Techno3600** [PEXPlugins/PermissionsEx#2772]
Hey guys,

Sorry to bother you but when I promote myself to the next rank it does not give me any perms, do plugins have to have PEX support or something?
[Here is my config](https://pastebin.com/NUkdn6U4). As you can see MODs have staff.* commands yet when I promote myself to MOD and restart the server I don't seem to get any new permissions. **Also**, the owners don't get anymore permissions than a Member does even though it has the all might * on it.
**AND** it seems that I can't click a button or a lever even though they are not on TNT
**And I can't break blocks at all**

**Comment by Stormbow** [comment]
Your permissions.yml file should follow [this example](https://pastebin.com/8ZSHxauG) as far as where all of the options go and how everything should be indented.

• You're missing a `groups:` section heading.  This invalidates your entire file and makes PEX not work at all.

• What you have on line 2 should be included after the `options:` section— which you have on line 11 —just like the way you have `rank;` on line 12.  This sort of error has been known to cause PEX to malfunction.

• As of Minecraft 1.9, every group _must_ have an `inheritance;` section.  Your "Member" group doesn't have one and you can add an "empty" inheritance to it by looking at line 19 of the example file I linked for you above.

Pay very close attention to the order of permission nodes and how to use the "global wildcard" that you have on line 27 of your file.  That node gives the group absolutely everything, and no other nodes need to be listed for that group.  You'd only need to _negate_ permissions that you _do not_ want the group to have, and those negations would go _above_ the wildcard the same way as you see in the example listed above.

As far as the inability to interact with anything on the server, check the server.properties file and ensure that `spawn-protection=0` there.  It's set to 16 by default (on a Spigot Minecraft 1.11.2 server).  That's the number of squares outward from the spawn point on the server that no one can do anything.  I've seen people set this to 2000, for who-knows-what reason.

After making all the above corrections, test the server and let me know if you run into any other PEX problems.

**Comment by Techno3600** [comment]
[So is this right?](https://pastebin.com/wi2TEX3d)
If it doesn't bother you it would bench if you cold correct it for me.

Thanks
Anand

**Comment by Stormbow** [comment]
Very close.  Add 2 spaces at the front of lines 17 and 27.

**Comment by Techno3600** [comment]
Hey I just have one more problem.

I can't seem to get my tab names to update with the prefixes in chat. I have my nickname limit set 25, the update-display (or whatever it is) true, and ignoring colors is set to true. Do you know why the display name is still not updating with my prefixes?

Thanks
Techno3600

**Comment by Stormbow** [comment]
Unfortunately, those are Essentials-specific issues that I can't really help you with because I've never (ever— in all the years I've been playing with Minecraft) looked at the tab player list for with any amount of regularity.  I'd even go so far as to say I've hit tab to see the player list 3 times total in my life in Minecraft.  I've always used /who and /list on any servers I was playing on.

You may be able to get help with that on the [official EssentialsX plugin's webpage](https://www.spigotmc.org/resources/essentialsx.9089/).
