### ISSUE TITLE
Prefixes Are Not Working

### ISSUE THREAD

**Issue by Techno3600** [PEXPlugins/PermissionsEx#2774]
Hello,

This is the classic 'my prefixes aren't working", is there a plugin depedenndcy to make the prefixes work, I used the PEX commands to add the prefix so there is no config issue. Prefixes just don't work.
Know whats wrong?

Thanks
Techno3600

PS. Thanks for the permissions help it is working and I am very happy. Thanks again for helping!

**Comment by Stormbow** [comment]
You don't have to open a new ticket every time you have something to add.  ;-)  (This is your 3rd ticket.  keep all comments in one ticket please.)

#2771 is your main ticket.
