### ISSUE TITLE
[in Russian] Help, bug

### ISSUE THREAD

**Issue by QQall** [PEXPlugins/PermissionsEx#2776]
I do not know English well, I ask help
The server starts to lag strongly when it happens

/pex toggle debug
[PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized
[PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized
[PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized
[PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized
[PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized
[PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized

Help me,  How to fix it?

**Comment by Stormbow** [comment]
Debug mode for 1 person, not the entire server.

https://pastebin.com/vhcWR2yK

**Comment by QQall** [comment]
img, console http://imgur.com/a/QKMEi

**Comment by Stormbow** [comment]
What language?

**Comment by QQall** [comment]
Russian :C

**Comment by QQall** [comment]
Help me, please (

**Comment by Stormbow** [comment]
ОК. В чем проблема?

**Comment by QQall** [comment]
Проблема такая.
Сервер работает себе спокойно, после чего когда определенный игрок выходит с игры проходит какое то время и начинается это в pex debug, то что скидывал выше. В итоге идёт забивка озу полностью и сервер начинает лагать. Обычно это происходит с группами DELUXE, HELPER пытался найти причину так и не смог, пересобирал сборки и плагины. Когда этот игрок заходит проблема пропадает, но стоит ему выйти проблема опять появляется. Вот и решил сюда написать может вы сможете мне помочь.

**Comment by Stormbow** [comment]
I'll try.  Show me your permissions.yml file.

What version of Minecraft are you using?

**Comment by Stormbow** [comment]
Я попробую. Покажите мне ваш файл permissions.yml.

Какую версию Minecraft вы используете?

**Comment by QQall** [comment]
Minecraft 1.7.10, я использую mysql

**Comment by Stormbow** [comment]
ACK! Я не могу помочь с SQL. Мне нужно увидеть файл, чтобы узнать, где программирование пошло не так.

**Comment by QQall** [comment]
Я могу вам отправить mysql dump pex, пойдёт ?

**Comment by Stormbow** [comment]
Скачайте этот файл. Смотрите, если вы получите ту же проблему.

Https://dev.bukkit.org/projects/permissionsex/files/909154

**Comment by QQall** [comment]
А он подойдет под UUID игроков и 1.7.10 ?

**Comment by Stormbow** [comment]
> Я могу вам отправить mysql dump pex, пойдёт ?

Можешь попробовать.

**Comment by Stormbow** [comment]
> Я могу вам отправить mysql dump pex, пойдёт ?

Скопируйте его в [Pastebin](http://pastebin.com).

**Comment by QQall** [comment]
DUMP: https://pastebin.com/X7iwfNQk

**Comment by Stormbow** [comment]
Minecraft 1.7.10 - это почти 3 года. : P Почему вы не обновляетесь до 1.11.2?

**Comment by QQall** [comment]
Еще не вышли нужные моды под эту версию :C

**Comment by Stormbow** [comment]
Неа. Свалка не то, чем я могу помочь. Мне нужно увидеть файл.

**Comment by Stormbow** [comment]
Режим отладки не должен включаться автоматически, а сам PEX не имеет никаких функций автоматизации, поэтому PEX не вызывает режим отладки для включения.

Какие еще плагины у вас есть на сервере?

**Comment by QQall** [comment]
Это все плагины: http://imgur.com/a/VIly4
Режим отладки включал я, да бы не мог найти причину лагов а после того как увидел в отладке данную проблему понял что PEX уходит в цикл а почему не пойму.

**Comment by Stormbow** [comment]
Режим отладки = выяснить, какие разрешения у группы или пользователя нет. Режим отладки не указывает причину задержки.

Пользователей на сервере делают огромные фермы мобов за железо, золото, добычу мусора?

**Comment by QQall** [comment]
Нет, ферм нету, проблема в том что когда в дебаге я вижу ту ошибку когда идет полный спам той ошибкой память сервера забивается и он лагает

**Comment by QQall** [comment]
Получается так, я вижу что сервер лагает, ввожу в консоль pex toggle debug, вижу там спам [PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized, после чего я удаляю этот uuid и сервер перестает лагать. Вот вся проблема, почему он начинает спамить этим ?

**Comment by Stormbow** [comment]
Вы не должны использовать эту команду:

/ Pex toggle debug

Вы должны использовать эту команду:

/ Pex пользователь Stormbow toggle debug

В соответствии с этой процедурой: https://pastebin.com/vhcWR2yK

(Возможно, вам придется перейти в [Google Translate](https://translate.google.com/?hl=ru), чтобы перевести процедуру.)

> Получается так, я вижу что сервер лагает, ввожу в консоль pex toggle debug, вижу там спам [PermisstionsEx] User 9b9910bbb-46eb-398c-b013-cfd5538ee6e9 initialized, после чего я удаляю этот uuid и сервер перестает лагать. Вот вся проблема, почему он начинает спамить этим ?

Я не знаю, откуда пришел UUID 9b9910bbb-46eb-398c-b013-cfd5538ee6e9. PEX не придумывает.

**Comment by Stormbow** [comment]
Если бы я мог увидеть файл permissions.yml, возможно, я мог бы узнать, откуда пришел UUID. Вам нужно было бы перенести сервер из SQL в файл, чтобы я мог увидеть файл.

https://github.com/PEXPlugins/PermissionsEx/wiki/Migration-and-UUIDs + [Google Translate](https://translate.google.com/?hl=ru).

**Comment by QQall** [comment]
Как я могу mysql переенсти в yml ?

**Comment by Stormbow** [comment]
https://github.com/PEXPlugins/PermissionsEx/wiki/Migration-and-UUIDs + [Google Translate](https://translate.google.com/?hl=ru).

**Comment by QQall** [comment]
/pex import <oldbackend>
<oldbackend> - что нужно сюда прописывать ? sql ?

**Comment by Stormbow** [comment]
Я думаю так. Я вообще не разбираюсь в SQL. Я не использовал SQL более 5 лет.

**Comment by QQall** [comment]
а в backend: - нужно прописать yml ?

**Comment by Stormbow** [comment]
Я думаю так.

**Comment by QQall** [comment]
Сейчас попробую

**Comment by Stormbow** [comment]
ОК

**Comment by QQall** [comment]
Я сделал как вы просили, куда отправить ?

**Comment by QQall** [comment]
вот держите https://pastebin.com/BygC2wYv

**Comment by Stormbow** [comment]
Возможно, я нашел проблему. UUID 9b9910bb-46eb-398c-b013-cfd5538ee6e9:

```
  9b9910bb-46eb-398c-b013-cfd5538ee6e9:
    options:
      name: Vorkuta
      group-deluxe-until: '0'
      prefix: '&7[&dDELUXE&7]&b'
    group:
    - deluxe
```

Не имеет длительности для группы deluxe.

---

Когда вы полностью удаляете пользовательскую информацию (все строки с 289 по 295), переходите обратно на SQL, а затем возвращаетесь к серверу для получения новой пользовательской информации, есть ли у вас такая же проблема с задержкой?

**Comment by QQall** [comment]
А как мне сделать бесконечную длительность тогда ?
Не совсем понял вас

**Comment by Stormbow** [comment]
Только один пользователь не имеет определенной продолжительности, так что отсутствие времени может быть причиной того, что сервер получает задержку.

Я не вижу никаких проблем с разрешениями каких-либо групп, никаких разрешений или плагинов, которые могли бы сделать цикл сервера и отставание.

----

Чтобы дать бесконечную продолжительность:

`/pex user Stormbow group set deluxe`

**Comment by QQall** [comment]
cпасибо, попробуем

**Comment by Stormbow** [comment]
Когда вы смотрите на команду PEX:

/pex user <user> group add <group> [world] [lifetime]

Вы можете игнорировать `[world]` и `[lifetime]`. Это необязательные данные. Не указывая эти данные, вы включаете все миры и навсегда.

----

Дайте мне знать, как это происходит.   :-)

**Comment by QQall** [comment]
Хорошо, как сделаем и все проверим сообщим

**Comment by Stormbow** [comment]
Ok.  :-)

**Comment by QQall** [comment]
Через пару дней напишу сюда, ибо все пока что хорошо работает

**Comment by Stormbow** [comment]
Фантастика! Я закрою этот билет. (Вы можете оставлять комментарии здесь, и я по-прежнему буду получать их в своем электронном письме.)

Fantastic! I'll close this ticket. (You can leave comments here, and I will still receive them in my email.)

**Comment by QQall** [comment]
Все отлично, спасибо !

**Comment by Stormbow** [comment]
Пожалуйста. Повеселись!
