### ISSUE TITLE
PEX Error after turn on SQL

### ISSUE THREAD

**Issue by Katzenpirat** [PEXPlugins/PermissionsEx#2777]
Hello,

I'll get this error, when I add SQL

01.05 12:30:32 [Server] ERROR Could not load 'plugins/PermissionsEx-1.23.3.jar' in folder 'plugins'
01.05 12:30:32 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
01.05 12:30:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot1-8-8.jar:git-Spigot-db6de12-18fbb24]
01.05 12:30:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot1-8-8.jar:git-Spigot-db6de12-18fbb24]
01.05 12:30:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot1-8-8.jar:git-Spigot-db6de12-18fbb24]
01.05 12:30:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot1-8-8.jar:git-Spigot-db6de12-18fbb24]
01.05 12:30:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot1-8-8.jar:git-Spigot-db6de12-18fbb24]
01.05 12:30:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
01.05 12:30:32 [Server] INFO Caused by: java.util.zip.ZipException: error in opening zip file
01.05 12:30:32 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_131]
01.05 12:30:32 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_131]
01.05 12:30:32 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_131]
01.05 12:30:32 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_131]
01.05 12:30:32 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_131]
01.05 12:30:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot1-8-8.jar:git-Spigot-db6de12-18fbb24]
01.05 12:30:32 [Server] INFO ... 5 more

Config:

```
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      url: mysql://***/perms
      user: perms
      password: ***
      deploy: permissions.sql
      aliases:
        permissions: server_permissions
        permissions_inheritance: server_inheritance
        permissions_entity: server_entity
updater: false
alwaysUpdate: false
```

**] Edit by Stormbow: corrected markdown formatting. [**

**Comment by Stormbow** [comment]
I think the "invalid plugin.yml" error means the file was corrupted when downloading.  Try downloading from this page and test the server; let me know if you get the same error.

**Comment by Katzenpirat** [comment]
Thanks

**Comment by Stormbow** [comment]
You're welcome. :-)  Have fun!
