### ISSUE TITLE
[in German] Egal was ich schreib es geht nicht :|

### ISSUE THREAD

**Issue by AmuArtz** [PEXPlugins/PermissionsEx#2782]
Hallo

Ich bin Dev bei einem Server und habe folgendes problem :  
groups:
  default:
    options:
      default: true
    permissions:
- cmdspy.use
 - nte.spieler
schema-version: 1
 
Egal was ich bei Permissions reinschreibe es funktioniert nicht.Könnte mir jemand den Fehler sagen?
Meine Plugins ; 
Essentials , Voxelsnipers , Plotme , ChatEx , NCP , Stablists
(das waren die wichtigsten)

**Comment by Stormbow** [comment]
Was genau funktioniert das nicht?

**Comment by Stormbow** [comment]
Zeigst du mir die gesamte Datei permissions.yml?

**Comment by Stormbow** [comment]
Die Datei sollte diesem Beispiel von Minecraft 1.7.9 folgen.

**Comment by Stormbow** [comment]
https://pastebin.com/8ZSHxauG

**Comment by Stormbow** [comment]
It appears that @AmuArtz is not going to be replying to this ticket again.  In 2 more days, I'll close it.

**Comment by Stormbow** [comment]
Case closed, I guess.
