### ISSUE TITLE
Server crashing on join / Player time out on connecting

### ISSUE THREAD

**Issue by Suertzz** [PEXPlugins/PermissionsEx#2787]
Hello! 

Randomly the players can not connect to the server and receive the message "time out",
You have to try the connection several times to be able to connect. 

I have the impression that the plugin fails to recover the data and blocks the connection

Some times the server crash randomly, here is the log of the crash:

https://pastebin.com/W548Hdus

Here is my configuration file:

https://pastebin.com/TNqv3rz8

My server is in `1.7.10`

The plugin is in `1.22.10`

It is very random, I have been using your plugin for three years and I never had this problem, if you could help me its would be very nice of you.

PS : I check the database, the server gets to read and write on it without any problems

I apologize for my very bad English

Thanks!

**Comment by Stormbow** [comment]
> [15:29:21] [Spigot Watchdog Thread/ERROR]: Please report this to http://www.spigotmc.org/

What did the people at Spigot tell you when you reported their error message to them?

**Comment by Stormbow** [comment]
No reply in 10 days.  Issue must be resolved.
