### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by GrayForeOne** [PEXPlugins/PermissionsEx#2789]
[PermissionsEx] Error occurred with PermissionsEx!

**Comment by Stormbow** [comment]
Obviously, you need to give us a **_LOT_** more information than that if you want help.

**Comment by Stormbow** [comment]
What's the error?

What version of Minecraft are you running?

What version of PEX are you using?

**Comment by Stormbow** [comment]
No reply in 9 days.  Issue must be resolved.
