### ISSUE TITLE
I'm so confused :|

### ISSUE THREAD

**Issue by QueenKisaki** [PEXPlugins/PermissionsEx#2791]
I have a server with 4 guilds (Earth, Water, Air, and Fire). Players have regular ranks (with prefixes) as seen on the paste. Once they choose a guild they get put into the guild ranks which have suffixes. I don't want those guild groups to be ranked as they may go in and out of those ranks and have nothing to do with ranking up like the other ranks. How do I set priority of regular ranks like Adventurer through Elder to not change in the /list when a player joins the guild groups (Earth, Water, Air, and Fire)? And without having to manually remove a player from that group then back in to reset it?

https://pastebin.com/UDK7F89S

**Comment by Stormbow** [comment]
Are you asking about users who are in 2 groups at the same time?

If so, then you'd want to set "weight" values for all of your groups.  You can see weight values in action [right here](https://pastebin.com/8ZSHxauG).  The lower the value, the more important the group is.  So, in this linked example file, a user in both the "Guest" and "Admin" groups would display only the "Admin" group's prefix/suffix when using EssentialsChat or EssentialsXChat.

**Comment by Stormbow** [comment]
On an unrelated side note, several of your permissions are not real permission nodes as far as I know.  Be sure to assign nodes which are found in your plugins' documentation to avoid any confusion about why certain things don't work.

**Examples:**
• Line 268, 279, 290, 301 (I'm not familiar with any plugins that begin nodes with `group`);
• 260 (the data `<limit>` must be specified);
• Lines 235-240 are all redundant, since the "Owner" group gets absolutely everything from line 241;

Also, be sure to include an `inheritance:` section for your "Adventurer" group.  See line 19 of the example linked above.  To use commands to add the "empty" inheritance section, you'd type 2 commands into the console:
```
    pex group <group> parents add <parents> [world]
    pex group <group> parents remove <parents>

    pex group Adventurer parents add potato
    pex group Adventurer parents remove potato
```

**Comment by QueenKisaki** [comment]
Hmm, I want the Adventurers through Elders to always have priority over the guild groups. The example you have there looks like the weights are equal to the rank? If so, I would have to add the guild groups in the ladder? They'll be using commands to get into the guild groups, is there one that won't change their appearance in the /list in chat?
As for the perms listed there for  lines 268,279,290, and 301 those are for worldguard regions permissions. and thanks for 260 LOL. For 235-240 some plugins required the actual permission to be added individually in order to work so I just added them lol. 
And for the Adventurer with it being the default if it still needs to inherit I can write anything in there?
Thank you SO much for all your help too!

**Comment by Stormbow** [comment]
If a user was in "Adventurer" and "Earth" (for example) and you wanted them to keep the prefix/suffix of "Adventurer", you would simply give "Adventurer" a lower number than "Earth" had.

So, you could give "Adventurer" a `weight: 1500` to coincide with it's `rank: 1500`, and then assign a `weight: 2000` to the "Earth" group so the "Adventurer" group's prefix/suffix is applied.

The "rank" values are actually only used if the /promote and /demote commands are being used, and— as far as I know —a group with no rank value is simply ignored as users are promoted and demoted along the "rank-ladder".  (In your case, I believe the rank-ladder name is "default", by default. heh)

**Comment by Stormbow** [comment]
> And for the Adventurer with it being the default if it still needs to inherit I can write anything in there?

I use "potato" in the commands to show how the commands would give the group an inheritance, and then remove the inheritance, leaving behind the "empty" inheritance section, which PEX requires as of Minecraft 1.9 onward.

If you want to use a text editor to create an "empty" inheritance, just make it look like line 19 from [my example file](https://pastebin.com/8ZSHxauG).

**Comment by QueenKisaki** [comment]
Awesome! Thanks Stormbow :)

**Comment by Stormbow** [comment]
You're welcome.  Feel free to post in this ticket again if you run into any other problems or questions.  Replies will get sent to my email even though the ticket is now closed.  :-)
