### ISSUE TITLE
BungeeCord

### ISSUE THREAD

**Issue by lemoncrafts** [PEXPlugins/PermissionsEx#2794]
I have a server network but when starting up i have this message in my config: 23.05 19:48:07 [Server] WARN [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!     I need it in offline mode other wise they servers dont link. What do i do please help. It does not work since i started using bungeecord.

**Comment by lemoncrafts** [comment]
23.05 19:52:09 [Multicraft] Received start command
23.05 19:52:09 [Multicraft] Loading server properties
23.05 19:52:09 [Multicraft] Starting server!
23.05 19:52:09 [Multicraft] Loaded config for "Craftbukkit 1.11.2 (Auto Update)"
23.05 19:52:10 [Multicraft] JAR file not found, copying from global JAR directory
23.05 19:52:10 [Multicraft] Updating eula.txt file
23.05 19:52:10 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 4015
23.05 19:52:10 [Server] INFO Loading libraries, please wait...
23.05 19:52:15 [Server] INFO Starting minecraft server version 1.11.2
23.05 19:52:15 [Server] INFO Loading properties
23.05 19:52:15 [Server] INFO Default game type: SURVIVAL
23.05 19:52:15 [Server] INFO Generating keypair
23.05 19:52:15 [Server] INFO Starting Minecraft server on 178.32.125.149:25586
23.05 19:52:15 [Server] INFO Using epoll channel type
23.05 19:52:16 [Server] INFO This server is running CraftBukkit version git-Bukkit-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
23.05 19:52:16 [Server] ERROR Could not load 'plugins/PluginBlock.jar' in folder 'plugins'
23.05 19:52:16 [Server] INFO org.bukkit.plugin.UnknownDependencyException: SpigotLib
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:298) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:260) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
23.05 19:52:16 [Server] ERROR Could not load 'plugins/BungeePexBridge.jar' in folder 'plugins'
23.05 19:52:16 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:298) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:260) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
23.05 19:52:16 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO ... 9 more
23.05 19:52:16 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[craftbukkit-1.11.jar:git-Bukkit-6e3cec8]
23.05 19:52:16 [Server] INFO ... 9 more
23.05 19:52:16 [Server] INFO [HiveJumpPads] Loading HiveJumpPads v2.17
23.05 19:52:16 [Server] INFO [PermissionsEx] Loading PermissionsEx v1.23.4
23.05 19:52:16 [Server] WARN [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
23.05 19:52:16 [Server] INFO [StrictlySpawnTP] Loading StrictlySpawnTP v1.7
23.05 19:52:16 [Server] INFO [WorldEdit] Loading WorldEdit v6.1.5;4651611
23.05 19:52:16 [Server] INFO [Essentials] Loading Essentials v2.0.1-b472
23.05 19:52:16 [Server] INFO [EssentialsSpawn] Loading EssentialsSpawn v2.0.1-b472
23.05 19:52:16 [Server] INFO [BungeePortals] Loading BungeePortals v1.2
23.05 19:52:16 [Server] WARN **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
23.05 19:52:16 [Server] WARN The server will make no attempt to authenticate usernames. Beware.
23.05 19:52:16 [Server] WARN While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
23.05 19:52:16 [Server] WARN To change this, set "online-mode" to "true" in the server.properties file.
23.05 19:52:16 [Server] INFO Preparing level "world"
23.05 19:52:16 [Server] INFO Preparing start region for level 0 (Seed: 312420593754277471)
23.05 19:52:17 [Server] INFO Preparing start region for level 1 (Seed: -7931458824760607401)
23.05 19:52:18 [Server] INFO Preparing start region for level 2 (Seed: -7931458824760607401)
23.05 19:52:18 [Server] INFO [HiveJumpPads] Enabling HiveJumpPads v2.17
23.05 19:52:18 [Server] INFO [Hive JumpPads] Hive JumpPads v2.17 developed by Xenedor!
23.05 19:52:18 [Server] INFO [Hive JumpPads] Hive JumpPads Successful loaded!
23.05 19:52:18 [Server] INFO [PermissionsEx] Enabling PermissionsEx v1.23.4
23.05 19:52:18 [Server] INFO [PermissionsEx] Initializing file backend
23.05 19:52:18 [Server] INFO [PermissionsEx] Permissions file successfully reloaded
23.05 19:52:18 [Server] INFO [StrictlySpawnTP] Enabling StrictlySpawnTP v1.7
23.05 19:52:18 [Server] INFO [WorldEdit] Enabling WorldEdit v6.1.5;4651611
23.05 19:52:18 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
23.05 19:52:18 [Server] INFO [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_11_R1 as the Bukkit adapter
23.05 19:52:18 [Server] INFO [Essentials] Enabling Essentials v2.0.1-b472
23.05 19:52:18 [Server] INFO [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
23.05 19:52:18 [Server] INFO [Essentials] Using Reflection based provider as spawn egg provider.
23.05 19:52:18 [Server] INFO [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
23.05 19:52:19 [Server] INFO Using locale en_GB
23.05 19:52:19 [Server] INFO [Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
23.05 19:52:19 [Server] WARN [Essentials] Detected supported permissions plugin PermissionsEx without Vault installed.
23.05 19:52:19 [Server] WARN [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
23.05 19:52:19 [Server] INFO [Essentials] Using superperms-based permissions.
23.05 19:52:19 [Server] INFO [EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b472
23.05 19:52:19 [Server] INFO [BungeePortals] Enabling BungeePortals v1.2
23.05 19:52:19 [Server] INFO [BungeePortals] Metrics initiated!
23.05 19:52:19 [Server] INFO [BungeePortals] Commands registered!
23.05 19:52:19 [Server] INFO [BungeePortals] Events registered!
23.05 19:52:19 [Server] INFO [BungeePortals] Plugin channel registered!
23.05 19:52:19 [Server] INFO [BungeePortals] Configuration file config.yml loaded!
23.05 19:52:19 [Server] INFO [BungeePortals] Configuration file portals.yml loaded!
23.05 19:52:19 [Server] INFO [BungeePortals] Portal data loaded! (0ms)
23.05 19:52:19 [Server] INFO [BungeePortals] Save task started!
23.05 19:52:19 [Server] INFO [BungeePortals] Version 1.2 has been enabled. (6ms)
23.05 19:52:19 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
23.05 19:52:19 [Server] Startup Done (2.900s)! For help, type "help" or "?"

**Comment by Stormbow** [comment]
This is a Bungeecord configuration issue.  You'll need to talk to them about it.  (I've never run a Bungeecord server, so I have no idea what their configs look like.)  [This page]9https://www.spigotmc.org/wiki/bungeecord-installation/#post-installation) might also help.

**Comment by Stormbow** [comment]
PS - Looks like your "PluginBlock" plugin is outdated.

**Comment by lemoncrafts** [comment]
groups:
  Guest:
    default: true
    prefix: '[Guest] '
    build: false
    permissions:
    - essentials.help
    - essentials.rules
    - essentials.motd
    - modifyworld.chat
  Member:
    default: false
    prefix: '&2[&aMember&2]&7 '
    build: true
    permissions:
    - essentials.help
    - essentials.rules
    - essentials.motd
    - essentials.afk
    - essentials.back
    - essentials.back.ondeath
    - essentials.depth
    - essentials.delhome
    - essentials.help
    - essentials.home
    - essentials.kit
    - essentials.kit.tools
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.motd
    - essentials.msg
    - essentials.ping
    - essentials.r
    - essentials.rules
    - essentials.seen
    - essentials.sethome
    - essentials.signs.use.disposal
    - essentials.spawn
    - essentials.suicide
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
  VIP:
    default: false
    prefix: '&6[&eVIP&6]&7 '
    inheritance:
    - Guest
    - Member
    build: true
    permissions:
    - essentials.help
    - essentials.rules
    - essentials.motd
  Mod:
    default: false
    prefix: '&1[&9Mod&1]&f '
    inheritance:
    - VIP
    - Member
    - Guest
    build: true
    permissions:
    - essentials.sethome.multiple.staff
    - essentials.helpop
    - essentials.home.others
    - essentials.nick
    - essentials.warp
    - essentials.warp.list
  Admin:
    default: false
    prefix: '&9[&bAdmin&9]&f '
    inheritance:
    - Mod
    - VIP
    - Member
    - Guest
    build: true
    permissions:
    - essentials.gamemode
    - essentials.give
    - essentials.god
  Owner:
    default: false
    prefix: '&6[&4Owner&6]&f '
    build: true
    permissions:
    - '*'
