### ISSUE TITLE
PEX crashing?

### ISSUE THREAD

**Issue by xMattRA** [PEXPlugins/PermissionsEx#2795]
Hi there!

So I installed PEX version 1.23.3 on my server and it was all good but then I restarted my server and it just stopped working. No commands worked. It didn't come up in /? or /pl. 
Here is my console log. 
https://pastebin.com/MFdpMw9P

Here is the Spigot version I am using.
https://prnt.sc/fbb9gn 

Are you able to help me at all?

**Comment by Stormbow** [comment]
Go [over here](https://dev.bukkit.org/projects/permissionsex/files) and get PEX 1.23.4 for your server.

Stop the server, install this .jar file, delete the old 1.23.3 .jar file, start the server, and see if you get the same error.

**Comment by Stormbow** [comment]
No reply from @xMattRA in 7 days.  Issue must be resolved.
