### ISSUE TITLE
Help fast

### ISSUE THREAD

**Issue by kiraakkira** [PEXPlugins/PermissionsEx#2796]
I created groups : coal , iron , gold etc .. i gave each one some permissions like fly.fly , when i check in console to see what commands each group has it shows them , but when i give myself one of the ranks no commands works and it says you do not have acces to that command . What is happening?pls help me fast

**Comment by Stormbow** [comment]
Permission nodes are directly related to the plugins which give those abilities.  The node `fly.fly` would have to be from a plugin of some sort in order for it to do anything on the server.  As far as I'm aware, `fly.fly` isn't from a plugin, so no users would be able to fly if you give that node to them.
