### ISSUE TITLE
offline mode displays warning message with invalid url

### ISSUE THREAD

**Issue by smmmadden** [PEXPlugins/PermissionsEx#2798]
During the startup of my Spigot 1.11.2 and 1.12 pre-release 5 builds, the logs show this message:
[08:16:19 WARN]: [PermissionsEx] - This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-Bous), UUIDs *may not be stable*!

All my servers are in offline mode and are integrated with BungeeCord server as the proxy.

Two questions:
1. Why is this displaying a url which has absolutely nothing to do with Minecraft or PermissionsEx?
2. Is there something that needs to be in the config.yml besides what I have here?
![image](https://cloud.githubusercontent.com/assets/10309346/26521736/afc5aad8-42bd-11e7-9f63-d7cbf8d6cad2.png)

Each world has the server.properties file loading in offline mode and using the 127.0.0.1 IPs as documented for BungeeCord.  The spigot.yml also has bungeecord: true and everything is working.  Am I missing something?  Thanks -Steve

**Comment by Stormbow** [comment]
Hi Steve,

Unfortunately, I think this is a Bungeecord configuration issue, not a PEX issue.  I've never used Bungeecord myself, so I'll have to refer you over to the [Bungeecord documentation](https://www.spigotmc.org/wiki/bungeecord-installation-mac/) to make sure you've got everything setup correctly.  If you still run into problems, [post a ticket on their hub](https://github.com/SpigotMC/BungeeCord/issues) and they can help you out better than I can.

Storm
PEX Guru
*not the programmer
