### ISSUE TITLE
PEX

### ISSUE THREAD

**Issue by Jade4Life** [PEXPlugins/PermissionsEx#2799]
it says error occured how i can fix it?

**Comment by Stormbow** [comment]
What were you doing just before the error happened and what does the error say?  (Copy it to [Pastebin](http://pastebin.com) and leave the link in this ticket.)

**Comment by Jade4Life** [comment]
It says an error occured and tell here in the github.

**Comment by Stormbow** [comment]
No, I mean, what happened before the error occurred?  Did you hit a tree with an axe?  Did you pick up an xp orb?  etc.

What does the entire error report show?

**Comment by Jade4Life** [comment]
I download the PermissionsEx then when i /pex it says an error occured but
now it's fixed don't worry i just need someone to set up my PermissionsEx
because when i pex user Jonnieg1 group add ADMIN it doesn't work and i have
the FILE can you go on it?

**Comment by Stormbow** [comment]
Can you copy your full permissions.yml file to [Pastebin ](http://pastebin.com) for me to see?

**Comment by Stormbow** [comment]
Ok.  I'm confused.  Problem solved?
