### ISSUE TITLE
Add rank automatic donation

### ISSUE THREAD

**Issue by MineServidorCraft** [PEXPlugins/PermissionsEx#2801]
Hi, I have a problem.
I have a donation option on my server, where we give a special donation rank for 1 month. Some users usually help us a lot with maintenance and every month they donate (picking the donation range). These users usually take the rank before they finish the one they already have and the remaining time they lose it (instead of adding up to 1 month at the time they are left). How can i fix this? (The command I use is "/ pex user" NameUser "group add donation" in buycraft)

**Comment by Stormbow** [comment]
Temporary group or permission times can't be extended, they can only be overwritten.  Your users will have to wait until the previous time has expired before gaining additional time if they don't want to waste any time.
