### ISSUE TITLE
Pex How to MAKE PREFIX'S SHOW ON YOUR SERVER - WORKING

### ISSUE THREAD

**Issue by TopNotchBanter** [PEXPlugins/PermissionsEx#2802]
I have tried tons of different chat managers to get pex to show my prefix's. Like it doest work none of them have! The essentialsxchat doesn't work either.

Please help!

**Comment by Stormbow** [comment]
Since you're running a Spigot server, you'd probably want [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) for more than [400 basic and admin permission nodes](http://wiki.ess3.net/wiki/Command_Reference/Perm) and [Esseentials**X**Chat](http://ci.drtshock.net/job/essentialsx/) (+ Vault) to handle the prefixes/suffixes.

"Essentials"— as opposed to "EssentialsX" —was discontinued at Minecraft 1.8 because the author considered Bukkit to be dead, and someone else took over, adapting it to Spigot.

**Comment by Stormbow** [comment]
Added a link for [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) in previous comment.

This comment ensures you have a clickable link in your email notification of a reply to your ticket.

**Comment by TopNotchBanter** [comment]
I have essentialsx and vault and essentialsx chat 

Still dosen't work tho

**Comment by Stormbow** [comment]
Have you configured everything correctly?

Use [Pastebin](http://pastebin.com) to show me your permissions.yml file and your Essentials\config.yml file.  (2 separate links)

**Comment by TopNotchBanter** [comment]
Pex Permissions: https://pastebin.com/6bs9JRZy

Essentials Config: https://pastebin.com/j4f5a4YB

**Comment by Stormbow** [comment]
Close, @TopNotchBanter .  You sent me your PermissionsEx\config.yml file, not the permissions.yml file.

In your Essentials\config.yml file, you need to make some changes to turn on prefixes/suffixes.  Compare your Essentials\config.yml file to [this excerpt](https://pastebin.com/eHCCcNuY) of the file.  Lines 32, 36, and 42 of your file need to be changed to match lines 10, 14, and 20 of my excerpt.  Then go down to line 526 to 530 of your file, and make it look similar to lines 29 to 41 of my excerpt.  Of course, use your own group names.

After those changes are made and saved, if the server is running, you can type `ess reload` into the console to get the changes applied to the server.  Then talk in chat and see what happens.

Let me know if you need additional assistance with this issue after the test.

**Comment by TopNotchBanter** [comment]
OMGGGGG THANKS MAN YOU DA BEST!

It worked. Seriously thank you. 

May all your dreams be happy :)

**Comment by TopNotchBanter** [comment]
There is one thing though. I am trying to set  My visitor group as default it just says
"Error in command syntax. Check command help"

**Comment by Stormbow** [comment]
> There is one thing though. I am trying to set My visitor group as default it just says "Error in command syntax. Check command help".

The easiest way to set a default group is to open the permissions.yml file with Notepad and give one group the option `default: 'true'` as you see in [this example](https://pastebin.com/8ZSHxauG).

The console command is:
```
pex set default group <group> <value>
pex set default group Guest true
```

**Comment by TopNotchBanter** [comment]
Thanks :) You really helped me out on this if i see people who can't do the prefix's i will link them here. Like this issue page and tell them not to make an issue thing. Only make one if this one doesnt do it for you.

**Comment by Stormbow** [comment]
You're welcome.  Have fun!
