### ISSUE TITLE
Prefixes not showing on Bukkit 1.8.7

### ISSUE THREAD

**Issue by Mesogo** [PEXPlugins/PermissionsEx#2803]
I have gone into the files and even changed the prefixes there, I have tried putting the prefixes on the specific users. The players seem to be moved to the new group, as they are under the group name, but nothing seems to change.

**Comment by TopNotchBanter** [comment]
Yes i am having the same problem.

I have 2 questions though

1. Are you running spigot, bungecord or bukkit?

2. Do you have essentialsx, and essentials x chat?

**Comment by Stormbow** [comment]
Close, @TopNotchBanter .  :)

The better question is actually:  "What chat management plugin are you using, @Mesogo ?"

PEX itself doesn't handle any chat management functions; it only allows you a place to store the prefix/suffix so a chat management plugin can reference it and display it in-game.

**Comment by Mesogo** [comment]
I have solved the problem. I needed a chat manager XD

**Comment by Stormbow** [comment]
Excellent. :-)  Feel free to post here again if you need any other help.
