### ISSUE TITLE
Server permissions file permissions.yml is empty, ignoring it

### ISSUE THREAD

**Issue by Krauser366** [PEXPlugins/PermissionsEx#2807]
Hello, I recently have the error: "Server permissions file permissions.yml is empty, ignoring it", I already configured the Essentials nodes (only) but I cannot set my users on a group, beacuse the Permissions plugin doesn't do it.

The plugins of my server are:
- AutoMessageBroadcaster
- ClearLag
- EssentialsX
- HubThat
- LoginSecurity
- Multiverse-Core
- PlotSquared
- ProtectionStones
- ProtocolLib
- ScoreboardStats
- SkinsRestorer
- Skywars
- Vault
- WorldEdit
- WorldGuard

Here I attach the console info on pastebin:

https://pastebin.com/7XykWpgW

I expect you guys can help me, I have from the monday with this problem and I am done. I already move, edit, replace, delete, redo the permissions.yml from 0, I investiged on Internet from any page and forum, and nothing works. Please, tell me what I'm doing wrong.

And of course, when I type /pl, the PermissionsEX plugin appears on green no in red.

**Comment by Stormbow** [comment]
That line/"error" refers to the permissions.yml file in the root directory and can be safely ignored. :-)  (It's for vanilla servers which use no plugins, and _**only**_ want to control the [Vanilla Permissions](http://wiki.bukkit.org/Vanilla_permissions).)

Your PEX permissions.yml file is inside the PermissionsEx folder.  (PermissionsEx\permissions.yml)

**Comment by Stormbow** [comment]
> I cannot set my users on a group, beacuse the Permissions plugin doesn't do it.

What command are you using to set users into groups?

**Comment by Krauser366** [comment]
Well, I wasn't using any command to set my users on a group, I was making it from the permissions.yml. Then I try with the command /pex user group set. But even the op players and the normal users don't appear with the prefix that is in the file of permissions.

And you say that the info line that appears me in my console, is nothing important (Server permissions file permissions.yml is empty, ignoring it)?

**Comment by Stormbow** [comment]
> Well, I wasn't using any command to set my users on a group, I was making it from the permissions.yml. Then I try with the command /pex user group set. But even the op players and the normal users don't appear with the prefix that is in the file of permissions.

Ah, ok.  Sorry, I misunderstood your first post.

The prefix and suffix are _stored_ in PEX, but actually _displayed in-game_ by a chat management plugin, like EssentialsXChat (if you're running a [Spigot](https://www.spigotmc.org/) server and using [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) + [Vault](http://dev.bukkit.org/bukkit-plugins/vault/), like most people do these days).

> And you say that the info line that appears me in my console, is nothing important (Server permissions file permissions.yml is empty, ignoring it)?

Correct.  :-)  This line doesn't affect anything in any negative way.

**Comment by Stormbow** [comment]
Corrected my [previous post](https://github.com/PEXPlugins/PermissionsEx/issues/2807#issuecomment-305922709); I forgot an important link in the Essentials comment.

**Comment by Krauser366** [comment]
Okay, so I need EssentialsXChat too for that of that way, my prefixes can be shown in game, and can I set the groups to my users freely?

**Comment by Stormbow** [comment]
To be clear, "set the groups to my users freely" is entirely handled by PEX: `/pex user Stormbow group set Owner`.

"display prefixes/suffixes in chat" is handled by EssentialsXChat, in the Essentials folder, config.yml file and you want to change a couple sections in your file to match [this example](https://pastebin.com/eHCCcNuY).

**Comment by Stormbow** [comment]
You're confusing 2 different function.

**Comment by Stormbow** [comment]
No reply in 9 days.  Ticket closed.
