### ISSUE TITLE
I don't know- always bad

### ISSUE THREAD

**Issue by Destiny-Skies** [PEXPlugins/PermissionsEx#2810]
a don't know, what's wrong... i tried to st up Perm.Ex, but when i restart server, it's always broken.. ;_;
[perm.ex.txt](https://github.com/PEXPlugins/PermissionsEx/files/1049511/perm.ex.txt)

**Comment by Stormbow** [comment]
You used the tab key in a lot of the lines.  Don't do that.  ;)

Follow [this example](https://pastebin.com/8ZSHxauG) for indentation, settings, etc.  And be sure every group has an inheritance; if they are not inheriting, give them line 19.

**Comment by Destiny-Skies** [comment]
thx

**Comment by Stormbow** [comment]
You're welcome. :)  Let me know if you need any more help.  (You can reply to this ticket, even though it's closed.)
