### ISSUE TITLE
Are you serious? Best security gap ever!

### ISSUE THREAD

**Issue by KevSlashNull** [PEXPlugins/PermissionsEx#2812]
**Why is /pex config permissions.backends.sql.password even working?!**

**Comment by Stormbow** [comment]
Useful feedback instead of a pointless rant/exclamation would be helpful.

**Comment by zml2008** [comment]
Have you considered not giving the permission to *edit the permissions plugin configuration* to people you don't trust. it's not a security flaw if people you give permission to use the command can use the command.
