### ISSUE TITLE
The default rank removed when you add to another rank!!!???

### ISSUE THREAD

**Issue by aBo0oDGamer** [PEXPlugins/PermissionsEx#2815]
Hello,
i'm working in prison server and i'm using pex for the permission i have made 2 default ranks
player bought rank and wrote (/pex user (name) group add (Group)) the 2 default ranks has been removed!!
why? i want them to stay how can i do that?
And Thanks.

**Comment by Stormbow** [comment]
The `default: 'true'` rank is the group into which all new players to the server are placed.  Thus, you can not have 2 of them.  (And I can't imagine anyone spending money on a server they have never played on before, so having a default rank and a default purchased rank seems improbably necessary anyway.)

**Reminder:**  No special commands, abilities, or powers that give a player an in-game advantage may be sold to players on any Minecraft server as such things are a violation of the [Minecraft Commercial Usage Guidelines](https://account.mojang.com/documents/commercial_guidelines).  Violations of the MCUG may result in your Minecraft account being permanently terminated.

**Comment by aBo0oDGamer** [comment]
Thanks for saying
but i think here you should answer me question if you don't have the answer please don't send anything
@zml2008 can u please help me?

**Comment by Stormbow** [comment]
This ticket has been resolved.

**Comment by Stormbow** [comment]
You want to be an asshole, do it somewhere else.

**Comment by Stormbow** [comment]
If you create another ticket for this question, it will also be closed and locked without reply.

**Comment by zml2008** [comment]
Default ranks in PEX 1.x only apply when a user has no ranks. As soon as you add a rank to a user, the defaults no longer apply. If you want the permissions from your default groups, just make the other groups you have inherit from the default groups.

**Comment by aBo0oDGamer** [comment]
Thaanks for answer me :D
is there another way to fix it? 
i want it to be like added group not inheritance
And thanks

**Comment by aBo0oDGamer** [comment]
sorry but i have another question :D 
as i told u before i'm making prison server 
i have A-Z ranks and the Vip ranks when player want to but a vip rank in any rank from A-Z when i give him the rank (/pex user <user> group add <Group>) sometimes the player get the rank without any problem and  sometimes the is a problem it is:
the VIP Rank come in the permission.yml like this in the player info:
`    group:
    - Lapiz
    - B
    options:
      name: aBo0oDGamer`
and the player cant make rankup like the basic group is the lapiz and the sub group is the B
but when i make it like this:
`    group:
    - B
    - Lapiz
    options:
      name: aBo0oDGamer`
works fine and there is no problems
can you fix the problem please?
and whats about the other problem for the default rank?
sorry i bothered you but please help me 
And Thanks <3

**Comment by aBo0oDGamer** [comment]
Hello!!?
can anyone answer me or tell me anything!
or i have to open another ticket (issue)??

**Comment by aBo0oDGamer** [comment]
Every thing in this issue goes to #2820

**Comment by aBo0oDGamer** [comment]
Sorry @Stormbow but nobody answer me because this ticket is closed so i suppose that i have to open another ticket
can you please just tell me if you can fix the problem or is there a way to fix it or not
if there is no way to fix it tell me please to go find another plugins to this or see what i have to do
And thanks

**Comment by aBo0oDGamer** [comment]
hello guys whats wrong with you !!
i want the answer please D:
