### ISSUE TITLE
Default rank help

### ISSUE THREAD

**Issue by aBo0oDGamer** [PEXPlugins/PermissionsEx#2816]
Hello again,
First i don't know what's wrong stormbow i think he didn't understand my question
Any way i want to know if there is a way to make default rank don't remove if i give users other rank (/pex user name group add groupname) that's it
Sorry if i made you angry @Stormbow 
And thanks again

**Comment by Stormbow** [comment]
That's not what you said at all in the other ticket.  You said you want a default rank and a purchased default rank.

Then you were snotty and rude when I told you how default ranks work.

I won't be helping you with this ticket.  Good luck waiting for an answer.

**Comment by aBo0oDGamer** [comment]
:D whatever you don't have to swearing me,
And Thanks for replaying me without close the ticket or lock it.
Anyway the answer for this ticket in the old ticket #2815

**Comment by Stormbow** [comment]
I don't see any apologies for your rudeness.

Doesn't matter.  I have you blocked now and don't have to see anything you post.
