### ISSUE TITLE
[PEX 2.x] All ranks have Op Permissions, Please help.

### ISSUE THREAD

**Issue by hyper4venom** [PEXPlugins/PermissionsEx#2818]
Hello,
I have a pixelmon server that runs on PEX, and recently I've noticed that all of my ranks have op permissions. You can see why this is a big problem, if everyone had op permissions, the server probably be gone within an hour. Naturally I took a look at the config to see if something has wrong, but I couldn't find anything that would have caused this to happen, and I didn't do anything out of the ordinary, it just randomly appeared a few days ago and Idk how to fix it. Please comment is you have any ideas on what the problem may be, I need the server asap.

**Comment by Stormbow** [comment]
The way PEX is designed, no one has any permissions until they've been given permissions by someone (usually the server Owner or whoever is in charge of setting up permissions).

Show me your permissions.yml file ([Pastebin](http://pastebin.com))and I can take a look at it for a potential cause.

What "op" activities, exactly, is someone (who?  specifically) able to access?

**Comment by hyper4venom** [comment]
I couldn't find permissions.yml, but I'll send permissions.json (https://pastebin.com/bACggWtK). As for what people are able to access, simple answer, everything, I was able to use /stop as a guest on my main account and on an account that had never logged on to the server before.

**Comment by Stormbow** [comment]
Ah, PEX 2.x issue.   Since it's not an official release, you'll have to wait for the programmer to respond here.

**Comment by hyper4venom** [comment]
(seriously tho, I really need the server up soon, people are getting tired of waiting and I can't open up the server until this is fixed. It's been about 2 weeks and they are getting tired of waiting and just moving on to other servers.)

**Comment by Stormbow** [comment]
Don't use PEX 2.x and you don't have to wait for help.

**Comment by zml2008** [comment]
Well of course everyone has all permissions -- that's what you set in the permissions file. You set the default permission for the default group to true (which is equivalent to giving the '*' node to the default group in 1.x). The command to fix this is `/pex default default def 0` (set the permission default of global default subject to 0, i.e. undefined)
