### ISSUE TITLE
Pex Command In BossShop

### ISSUE THREAD

**Issue by Kuroyabumozu** [PEXPlugins/PermissionsEx#2819]
Hello everyone, does anyone knows How to make specify player name on BossShop RewardType ?? Like below.
pex user <player> group add vip * 60s

**Comment by Kuroyabumozu** [comment]
pex user <player> group add vip * 60s

**Comment by Stormbow** [comment]
Sorry, you will have to ask about how to use their plugin on [their plugin's page](https://www.spigotmc.org/threads/bossshop-powerful-and-playerfriendly-chest-gui-shop-menu-plugin.6581/).
