### ISSUE TITLE
The default rank removed when you add to another rank??! + The basic rank and the added rank (Sub Group)

### ISSUE THREAD

**Issue by aBo0oDGamer** [PEXPlugins/PermissionsEx#2820]
Hello,
i have opened an issue before but nobody answer me maybe because the issue is closed so i open this issue.
1. When player join the server for the first time he has the default rank but when the player want to buy a VIP Rank the default rank removed and take the VIP Rank How to make the default rank same as the added rank?
Example:
The default rank is A
and the VIP Rank is Lapiz
player join the server have rank A
the player buy the Lapiz Rank (/pex user (User) Group add Lapiz)
the player have now Lapiz rank without Rank A
i want the player have the both Rank (A and Lapiz) how please?
2. i have A-Z ranks and the Vip ranks when player want to buy a vip rank in any rank from A-Z when i give him the rank (/pex user group add (group)) sometimes the player get the rank without any problem and sometimes there is a problem and the problem is:
the VIP Rank come in the permission.yml like this in the users:
`group: - Lapiz - B options: name: aBo0oDGamer`
and the player cant make rankup like the basic group is the lapiz and the sub group is the B
but when i make it like this:
`group: - B - Lapiz options: name: aBo0oDGamer`
works fine and there is no problems
can you fix the problem please?
sorry i bothered you but please help me
And Thanks <3

**Comment by Stormbow** [comment]
Stop opening new tickets for the same problem.
