### ISSUE TITLE
[PEX] Issues with In-game Groups.

### ISSUE THREAD

**Issue by HighLordAsmodeus** [PEXPlugins/PermissionsEx#2824]
Ok, So I added my Server to Spiggot 1.12 and Downloaded PermissionsEX to it, but for some reason in-game, when you type in chat, It pops up with 2 groups in your name, and I dont know why.

11.06 16:23:13 [Server] INFO *[Owner]* *[Owner]*Mawldir: Test

Can someone please tell me how to fix this?

**Comment by Stormbow** [comment]
This is a matter of an improperly configured chat management plugin.  Essentials and EssentialsX, for example, both use `{group} {displayname}` as part of their setup, and the `{displayname}` variable is a combination of the prefix+username+suffix, combined.  So when you define a prefix in PEX, you typically get the result you're seeing.  To fix this, look inside your Essentials\config.yml file, down around line 250 or so, and remove the `{group}` variable.  (See [this example](https://pastebin.com/eHCCcNuY) for more details.)

**Comment by Stormbow** [comment]
Close enough to a week with no response.  Case closed, I guess.
