### ISSUE TITLE
I don't know how to use your plugin, and I'm extremely rude.

### ISSUE THREAD

**Issue by kristall000** [PEXPlugins/PermissionsEx#2828]
ok. console. pex user "user" and what? Too many arguments????

**Comment by Stormbow** [comment]
What _exactly_ are you typing and where are you typing it?  (In-game or in the console?)

**Comment by zml2008** [comment]
What are you trying to do even? If you give no useful information, we can give you no useful answer.

**Comment by Stormbow** [comment]
I don't think we'll be hearing from this person again.  Case closed?
