### ISSUE TITLE
How it works XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:

### ISSUE THREAD

**Issue by Pantiak** [PEXPlugins/PermissionsEx#2829]
How it works XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX: ?
I'm having problems assigning a group. I wrote this

XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
    options:
      name: Pantiak3
    group:
    - teh

But no matter how much the player re-enters the game, this group is not assigned to him
[permissions.yml.txt](https://github.com/PEXPlugins/PermissionsEx/files/1078871/permissions.yml.txt)

As I understood "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:" This is the place where the UUID of the player should automatically be inserted. But it will not work if "online-mode = false" is disabled. correctly ? If it is correct, is it possible to circumvent it?

**Comment by Stormbow** [comment]
Delete lines 44 through 48.  The [example](https://pastebin.com/8ZSHxauG) you probably got that from uses the XXXXXX as a placeholder for a real UUID (which you have on line 37).

**Comment by Stormbow** [comment]
Problem solved?

**Comment by Pantiak** [comment]
Yes, thank you very much

**Comment by Stormbow** [comment]
Excellent!
