### ISSUE TITLE
Prefix Issue

### ISSUE THREAD

**Issue by xX1bumblebee1Xx** [PEXPlugins/PermissionsEx#2835]
When I give a user the Member and Donator group they get the Novice prefix and I cannot find out how to give them the Member one over the Novice one.

Permissions.yml: https://pastebin.com/qdiYpNpW

**Comment by Stormbow** [comment]
Which chat management plugin are you using?

**Comment by xX1bumblebee1Xx** [comment]
DeluxeChat: https://pastebin.com/4dieupN3

**Comment by Stormbow** [comment]
Ack.  I've never used DeluxeChat, so I'm not familiar with its settings and configuration at all.  I'll see what I can figure out...

Show me your completely permissions.yml file please, and give me a username that's being problematic.

**Comment by xX1bumblebee1Xx** [comment]
Alright, Thanks. https://pastebin.com/ADrFURRc Username: BumbleBeee_

**Comment by Stormbow** [comment]
Try adding a "Novice" template to the DeluxeChat config file.  Let me know if that fixes the problem.

**Comment by Stormbow** [comment]
I don't know if DeluxeChat is case-sensitive, so "donator" in PEX may not be "Donator" in DeluxeChat.  Try to keep these all the same, across all of the plugins that you use.

**Comment by Stormbow** [comment]
You do have all the "weight" (PEX) and "priority" (DeluxeChat) correct, so "Donator" should be getting displayed in-game.

**Comment by xX1bumblebee1Xx** [comment]
Maybe I didn't explain it right, The Donator suffix is showing, But the problem is that when I am the group Member it still shows the Novice prefix, e.g: http://i.imgur.com/Rgaw6fY.png

**Comment by Stormbow** [comment]
Try giving the Donator group an empty prefix.  `prefix: '&r'

This seems to be a new problem, recently.  #2834 had the opposite issue.

**Comment by xX1bumblebee1Xx** [comment]
That is removing the Novice prefix completely, instead of replacing it with whatever the player is ranked as(Member in this case). When I removed the inheritance it works fine, but then none of the permissions will get inherited.

**Comment by Stormbow** [comment]
So you want [Member Prefix] Username [Donator Suffix]?

Unfortunately, PEX itself doesn't handle any chat management features, such as displaying the prefix & suffix of one group, nor displaying the prefix/suffix of one group and the suffix/prefix of another group— you'd have to look at the different chat management plugins to find one with those types of features.  PEX just gives users a place to store the prefix/suffix, then the chat management plugins can draw from that data to display it in-game.

**Comment by xX1bumblebee1Xx** [comment]
Yep thats what I'm looking for :P I didn't know if was a pex problem or what, Thanks anyway.

**Comment by Stormbow** [comment]
You're welcome.  Good luck on the hunt!  :-)
