### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by harm27** [PEXPlugins/PermissionsEx#2837]
I am currently setting up a Spigot 1.12 server and i want to use PermissionsEx, but what can i use the best?

Is there a 1.x build compatible with 1.12 and the best choice? 
Or can i better use a 2.x build compatible with 1.12?

And is PermissionsEx 2.x still compatible with Vault?
Or can i better replace calls from my own plugins to Vault with calls to an API from PermissionsEx 2.x?

**Comment by Stormbow** [comment]
Since this ticket contains programming topics, you'll have to wait for @zml2008 to reply.

**Comment by Stormbow** [comment]
And, for what it's worth, PEX 1.23.4 works on Minecraft 1.12, according to the servers I've talked to lately.

PEX 2.x is still in development— no official releases yet —so I haven't used it at all and can't answer anything about it.  As you can see on our tickets page, there are a lot of tickets for PEX 2.x and SQL issues that I can't answer.  Those all need zml to reply as he's the only one around with experience in both.

**Comment by harm27** [comment]
Okay, thanks for the info. Then i will use pex 1.x for now.

**Comment by zml2008** [comment]
As a further note, Vault is and will always be the preferred API for working with PEX on Bukkit/Spigot -- PEX is generally not guaranteed to have a stable API, especially with the 2.0 release not finalized. However, we maintain our own Vault hooks in 2.x so those will remain compatible.

**Comment by harm27** [comment]
Thanks @zml2008 for that note.
