### ISSUE TITLE
PEX Group before Prefix

### ISSUE THREAD

**Issue by ItzFiLiP** [PEXPlugins/PermissionsEx#2840]
Hello! I have a problem. Everything was fine untill I changed my group name to ''Admin'' (before it was ''admin'').
I want that first letter to be ''big'' because of the Scoreboard, estetic.
And when I do that, there is (in chat) [Admin] before prefix I put!

It's so annoying and I can't get rid of it, please help!
It's like: [Admin]Admin ItzFiLiP  (this Admin is my prefix).

If I change it to ''admin'', it doesn't show.
Thanks!

**Comment by Stormbow** [comment]
The display of prefixes in-game is handled by a chat management plugin; PEX just gives you a place to store the information.

Which chat plugin are you using?

**Comment by ItzFiLiP** [comment]
I'm using Essentials and there isn't {group} in config file.

**Comment by Stormbow** [comment]
Can you show me what is being displayed in-game, your config.yml file, and your permissions.yml file?

([Pastebin](http://pastebin.com) for the 2 files, screenshot or text for the in-game display.)

**Comment by Stormbow** [comment]
No response in 7 days.  Ticket closed.

(You can still reply here, if you ever reply.)

**Comment by ItzFiLiP** [comment]
Ohh, I'm so sorry, I forgot to tell that I solved the problem. The trick to
not show rank (group) was to put first letter caps wherever I put name of
rank)
Dana 5. 7. 2017. 21:17 osoba "Stormbow" <notifications@github.com> napisala
je:
