### ISSUE TITLE
[1.12] Can't set players group with PEX

### ISSUE THREAD

**Issue by Scythix** [PEXPlugins/PermissionsEx#2842]
So just recently when I try to do /pex user (name) group set (groupname) I get an error from the console. I will list my plugins and the error I get below:

Plugins:
AutoMessage
AutoRank
ClearLag
DeluxeJoin
Essentials
Lockette
NoCheatPlus
PermissionsEx
Plugman
RandomCoords
Statz
Supertrails
TimeVote
Towny
Vault
Votifier
VotingPlugin
WorldEdit
WorldGuard
IDisguise

Here's the error:
22.06 22:37:14 [Server] WARN Unexpected exception while parsing console command "pex user Scythix_ group set helper"
22.06 22:37:14 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'pex' in plugin PermissionsEx v1.23.4
22.06 22:37:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
22.06 22:37:14 [Server] INFO Caused by: java.lang.IllegalAccessError: tried to access method ru.tehkode.permissions.bukkit.ErrorReport$Builder.<init>(Ljava/lang/String;Ljava/lang/Throwable;Lru/tehkode/permissions/bukkit/ErrorReport$1;)V from class ru.tehkode.permissions.bukkit.ErrorReport
22.06 22:37:14 [Server] INFO at ru.tehkode.permissions.bukkit.ErrorReport.builder(ErrorReport.java:334) ~[?:?]
22.06 22:37:14 [Server] INFO at ru.tehkode.permissions.bukkit.ErrorReport.withException(ErrorReport.java:217) ~[?:?]
22.06 22:37:14 [Server] INFO at ru.tehkode.permissions.bukkit.ErrorReport.handleError(ErrorReport.java:202) ~[?:?]
22.06 22:37:14 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onCommand(PermissionsEx.java:328) ~[?:?]
22.06 22:37:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
22.06 22:37:14 [Server] INFO ... 8 more

Using pex 1.23.4
Thanks

**Comment by Stormbow** [comment]
@zml2008 will have to respond to this one.

**Comment by beautifulpoison** [comment]
It seems as though the plugin needs to be updated to support 1.12 cause I am also having this issue.

**Comment by Scythix** [comment]
I reverted the server back to 1.11 for the time being and everything works great. Hope the pex team is working on support for 1.12.

**Comment by beautifulpoison** [comment]
Yeah myself too, I don't need it right now but will in a few weeks. I really don't want to have to use another plugin. Scary seeing that this plugin hasn't been updated for over a year :(

**Comment by Stormbow** [comment]
Unfortunately for you guys, these 2 servers appear to be the only servers having issues that aren't obviously related to the AnimatedScoreboard plugin being badly programmed.  And both of the 1.12 servers that I have played on recently have reported that PEX 1.23.4 works with no problems.

**Comment by beautifulpoison** [comment]
Interesting. Thanks for the information, I'm having a developer of my own look into it shortly. If he figures anything out I'll keep it posted here.

**Comment by beautifulpoison** [comment]
Alright so my awesome developer figured it out. Seems to be an issue with the PermissionsEx folder.

Copy anything you got in that folder and delete it. Restart your server and replace the file back and it will work like new :)

**Comment by Stormbow** [comment]
As a computer science guy for over 30 years... that doesn't sound like it would actually do anything.

**Comment by Stormbow** [comment]
But if your stuff is working now, good!

**Comment by Stormbow** [comment]
Case closed?

**Comment by beautifulpoison** [comment]
Apparently there was some sort of error with the file. Not 100% sure. 

I would see if @Scythix is still having issues first, and if this helped them as well!

**Comment by Stormbow** [comment]
He reverted back to 1.11, so I'll close the ticket.  (People can still post here.)

**Comment by Scythix** [comment]
Alright, sorry for not following up. I changed the server to 1.12 for shits and giggles the other day and the plugin seemed to work fine. I'm a bit weary of it happening again so i'll stay in 1.11 until (if) it's updated for 1.12. Thanks for your guys's help.
