### ISSUE TITLE
Problems with default groups

### ISSUE THREAD

**Issue by MerakiMc** [PEXPlugins/PermissionsEx#2843]
Permissions: http://paste.thezomg.com/22489/82653961/
PEX Version: 1.23.4

Players dont seem to be given any group at all?

**Comment by Stormbow** [comment]
You're using a very, very old example to create your permissions.yml file.

Follow [this example](https://pastebin.com/8ZSHxauG) if you're attempting to run a server from Minecraft 1.7.9 thru 1.12.

**Comment by Stormbow** [comment]
Problem solved?

**Comment by Stormbow** [comment]
No reply in more than 7 days.  Case closed.
