### ISSUE TITLE
PEX per world permissions not working

### ISSUE THREAD

**Issue by 01Andi** [PEXPlugins/PermissionsEx#2848]
Hello everyone

I'm trying to use PEX for setting up some per world permissions but only the normal permissions work. Tho ones specified for a single world don't work.

My permissions.yml file:

**] Edit by Stormbow: Moved permissions.yml file contents to Pastebin: https://pastebin.com/5envpFBk [**

**Comment by Stormbow** [comment]
Check out my [Multiworld Example](https://pastebin.com/ieyQU7w8).  You're missing inheritance sections in all of your groups.  This can cause PEX to malfunction on Minecraft 1.9+ servers.

In your unedited post, you had the line `schema-version: 1` near the end of the file.  This line needs to come _before_ the `users:` section, as shown in the example above.  This error can cause PEX to malfunction in Minecraft 1.6.4+ servers.

Also, be sure you're using the latest version of PEX (1.23.4) found on [this page](https://dev.bukkit.org/projects/permissionsex/files).

Once you have the above errors corrected, use [PEX Debug Mode](https://pastebin.com/vhcWR2yK) to find out which permission node(s) are missing from your setup.

**Comment by 01Andi** [comment]
I'm going to test your solutions this evening. It's a MC 1.8 server.
Anyway i'm going to try it with both of your solutions.

Thank you very much for your fast answer.

**Comment by 01Andi** [comment]
@Stormbow 
Now my config.yml looks like this, but it's still not working.
https://pastebin.com/TKsCgqxX

**Comment by Stormbow** [comment]
Did you use [PEX Debug Mode](https://pastebin.com/vhcWR2yK) to see what was missing?

**Comment by Stormbow** [comment]
You still haven't told me _exactly_ what is not working.

**Comment by 01Andi** [comment]
The best example is the /gamemode command. If I want to allow it for a specific world, ot doesn't work. If I set the same permission node to the global permissions, it works. This is the same for every permission specified only for one or two worlds.
In the debug mode I see, that every permission specified in the "worlds" section doesn't work.
So:
global perms work but the world specific ones don't.

**Comment by Stormbow** [comment]
Now we're getting somewhere.  ;-)

In one case/group/world— bauarbeiter > Lobby —you misspelled "essentials", so the node wouldn't grant access to the /gamemode command in that instance.  (The node actually wouldn't do _anything_, positive or negative, as I mention in the next paragraph.)

Next, we look at the [Multiverse permission nodes](https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O-Permissions) and compare those to the nodes that you've negated and we find out that `mv.bypass`.anything doesn't exist, so none of those negated nodes or granted nodes would do anything at all on the server, especially not allowing (or disallowing) the use of the /gamemode command.  They simply have no effect at all, positive or negative; they just make the file longer.  (I think what you may have been attempting to do was [bypass Worldguard](http://wiki.sk89q.com/wiki/WorldGuard/Permissions), which has a real permission node.)

If you would use the PEX Debug Mode that I mentioned twice— three times, as of this comment ;-) —you'd get server console output that tells you, in detail, which permission nodes are being checked for the user when they attempt to use the (`essentials.gamemode`) /gamemode command.  And then, when a permission node is prevents the /gamemode command from functioning, you'd see that node mentioned in the server output also.  You add that node to the group and then the group can— usually, most likfely —use the /gamemode command.  And if they can't, Debug Mode would tell you what else is preventing the command.

**Comment by Stormbow** [comment]
If you have any problems interpreting the Debug Mode output, Pastebin it for me and I can tell you what to give the group. :-)

**Comment by Stormbow** [comment]
No response in almost 7 days. Ticket closed.

(You can still reply here, if you ever reply.)
