### ISSUE TITLE
Inheritance not working

### ISSUE THREAD

**Issue by JBaadargo** [PEXPlugins/PermissionsEx#2849]
I've just updated my server to 1.12, and I'm having problems with PermissionsEx inheritance for essentials. It only appears to be for essentials though, everything else seems fine. For example, one of my Trusted members can use /fly, but I (owner rank) can not, even though it appears I should be able to. I'm unsure exactly if it's pex or essentials that is the issue, so I'm posting this on both pages in hopes of an answer. Below is my permissions.

https://pastebin.com/7SWQXjqx

**Comment by Stormbow** [comment]
The problem is likely in the group "Mod".  "Mod" inherits from "TMod", which does not exist, so the `essentials.fly` permission node never makes its way up the chain to the "Owner" group.

**Comment by JBaadargo** [comment]
Crap, completely overlooked that. Updating the server at 1AM isn't the best idea. Thanks for that buddy, feel really dumb now.

**Comment by Stormbow** [comment]
You're welcome. Come on back if you need help with anything else. :-)
