### ISSUE TITLE
Back-end working on some but not all 

### ISSUE THREAD

**Issue by tmoflash** [PEXPlugins/PermissionsEx#2850]
I have multiple servers all connected to MySQL and all work except one server and I do not know why.

I have deleted server, built back, removed plugins, add back plugins. It connects to the database, but the perms do not come through.

I do not understand why it is only partially working. Any suggestions I should check?

```
multiserver:
  use-netevents: true
permissions:
  backend: sql
  backends:
    sql:
      uri: mysql://ip.of.the.server/database
      user: username
      password: password
      type: sql
  basedir: plugins/PermissionsEx
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  informplayers:
    changes: false
updater: false
alwaysUpdate: false
```

**] Edit by Stormbow: Added code tags around config.yml file contents. [**

**Comment by Stormbow** [comment]
Unfortunately, I haven't used SQL in about 5 years or so and have forgotten the little I learned when I used it for that single month on my Minecraft server, so you'll have to wait for @zml2008 (the PEX programmer) to reply to this ticket.

**Comment by davewolax** [comment]
Will they update PEX for 1.12 and newer versions? will it be supported?

**Comment by Stormbow** [comment]
PEX 1.23.4 works on Minecraft 1.12 servers.

**Comment by Stormbow** [comment]
PS - Don't hijack people's tickets to ask off-topic questions.  ;-)

**Comment by Travja** [comment]
Can I get an update on this ticket. I have the same issue.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
