### ISSUE TITLE
 Permission.yml does not work

### ISSUE THREAD

**Issue by Jonaswitze** [PEXPlugins/PermissionsEx#2853]
Hello,
I have my permissions written in the file but PermissionsEx is displayed at /pl red.
Can someone help me?
Jonas

The Permmission.yml: https://pastebin.com/8ejrL5qL

**Comment by Stormbow** [comment]
Line 82 and 83, 129 and 130: The correct permission node would be `- '*'` to give the group _every_ permission node on the server.  (This can result in your server being destroyed if the wrong person gets into such a group or gets access to this permission node.)

**Comment by Stormbow** [comment]
After the above correction, the file parses cleanly, but there may be more PEX-specific errors.  I'm looking for those now.

**Comment by Stormbow** [comment]
It looks like line 4 is the only other error.  Change it to `permissions: []` to have an "empty" permissions section, so PEX won't choke on it.

**Comment by RBM-GITHUB** [comment]
The YAML isn't valid syntax. I corrected the syntax but not the meaning.

https://pastebin.com/NbTP1keU

**Comment by Stormbow** [comment]
@RBM-GITHUB : Wrong.

**Comment by RBM-GITHUB** [comment]
@Stormbow explain

**Comment by Stormbow** [comment]
> explain

Quotation marks are never used in PEX.  Apostrophes are.

**Comment by Stormbow** [comment]
And you got the global wildcards wrong.

**Comment by Jonaswitze** [comment]
Thanks, it works again. It was on the "- *".

**Comment by RBM-GITHUB** [comment]
Well, seems the issue has been resolved anyway. Thanks for letting me know.

**Comment by Stormbow** [comment]
> Thanks, it works again. It was on the "- *".

You're welcome. :-)  Come on back if you run into any other issues.

**Comment by Jonaswitze** [comment]
With pleasure

**Comment by Stormbow** [comment]
> Well, seems the issue has been resolved anyway. Thanks for letting me know.

You're welcome.  (And I do appreciate your interest in helping others!)
