### ISSUE TITLE
default group not being assigned

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2854]
I have tried to fix my issue with "/pex set default group <group> <world>" So I ran /pex set default group lobby lobby and I get in chat "Group "lobby" is no loner default in world 'null'" when I check if there is a default group set for lobby the list is blank. I'm attempting this on Spigot 1.12 with pex 1.12.4

**Comment by Stormbow** [comment]
The easy solution: open the permissions.yml file in Notepad (['Notepad++'](http://notepad-plus-plus.org/) is better) and make sure only one group has `default: 'true'` in their `options:` section as you see in [this example](https://pastebin.com/8ZSHxauG).  (The other groups don't need `default: 'false'` in them.)

The [PEX Command](https://pastebin.com/Kd269wd7) is actually `/pex set default group <group> <value>` (`/pex set default group GroupNameHere true`.  Then open the permissions.yml file in Notepad anyway to make sure the data is displayed in there correctly.  (heh)

**Comment by Ironic8b498** [comment]
I forgot to mention I'm using SQL, the command worked great. I updated my file fr commands to pex just in case I make mistake and remove default group again. Thanks

**Comment by Stormbow** [comment]
On the positive side, "fake" stuff in the file won't have any sort of effect on the server at all— neither positive or negative effects aside from making the file longer —so I'd bet the same is true when using SQL.  PEX _may_ be delayed in finding other information it's looking for in a group, but we're talking about single-digit milliseconds of a delay— and to give you something to compare it to, your brain takes 150 milliseconds to respond to a trigger of any kind, from seeing something, to wanting to say something, to even being surprised by something, so PEX (actually, the computer) is still handling operations for your server extremely fast.

As long as you don't have dozens or hundreds of "fake" things in the file/SQL database, it won't impact the server in a negative way.  (It's just something us neat freaks don't like to see, in which case we'd migrate to file, clean it up, delete the database, and migrate to database again.)

You're welcome. :-)  If you have any other issues, you can still post here after I close this ticket.
