### ISSUE TITLE
PEX not loading.

### ISSUE THREAD

**Issue by bencethegreat** [PEXPlugins/PermissionsEx#2855]
Whenever I try to start PEX, it comes up with an error that I need vault, even though I have it installed. 

Console output:
https://pastebin.com/NL2HpkuP
Config:
https://pastebin.com/vj29qX2K

**Comment by Stormbow** [comment]
The error says there's a problem with the formatting and syntax of the permissions.yml file.  Show me that file and I can tell you what all the errors are.

**Comment by Stormbow** [comment]
No response from @bencethegreat in 8 days.  The problem must be solved.
