### ISSUE TITLE
PEX Not showing prefixes/not limiting or enforcing permissions

### ISSUE THREAD

**Issue by BigLDP** [PEXPlugins/PermissionsEx#2859]
Hello, I recently installed only the pex plugin. I could not download the essentials plugins being they are unsupported for 1.12. I was trying to add and enforce permissions with no prevail. I also was trying to add prefixes, but again, no prevail. Is there a fix for this?

**Comment by BigLDP** [comment]
nevermind, was able to download https://hub.spigotmc.org/jenkins/job/spigot-essentials/lastBuild/ and it worked.

**Comment by Stormbow** [comment]
Glad to see you figured it out. :)

[Right here](https://pastebin.com/eHCCcNuY) you'll find a short guide to help you get [EssentialsChat](https://hub.spigotmc.org/jenkins/job/spigot-essentials/lastBuild/)/[EssentialsXChat](https://ci.drtshock.net/job/essentialsx/) (+ [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) in both cases) setup correctly to display your prefixes/suffixes in-game.

**Comment by Stormbow** [comment]
Did you get all your permissions issues resolved too?

**Comment by Stormbow** [comment]
No reply from @BigLDP in more than 7 days.  All problems must be resolved.
