### ISSUE TITLE
Having Issues...

### ISSUE THREAD

**Issue by nods0123** [PEXPlugins/PermissionsEx#2860]
I am having an issue. *Nah duh.*
I have my Builders as a suffix only, and all my normal ranks as a prefix, the parents for Builder is the normal rank, and the rest of the ranks go from the normal rank as well. So, whenever I set someone to Builder, they get the normal prefix, even if they have another rank.

**Comment by Stormbow** [comment]
You could try using `weight:` values ([example](https://pastebin.com/8ZSHxauG)) to force your chat management plugin to show the prefix you want.

If you're trying to get the prefix of one group and the suffix of another, you will need to look for a chat management plugin which can handle such a thing.  (To the best of my knowledge, EssentialsChat/EssentialsXChat does not, and that's the only chat management plugin I've ever used, personally.)

**Comment by Stormbow** [comment]
No response from @nods0123 in more than 7 days.  I guess the problem is resolved.
