### ISSUE TITLE
Prefixes Not Showing Making ME RLY MAD

### ISSUE THREAD

**Issue by 269Grimawewsome** [PEXPlugins/PermissionsEx#2863]
Hey So I been working on my mc server and whenever I restart it the prefixes are gone this just started today plz help I'm very sad

**Comment by 269Grimawewsome** [comment]
groups:
  Owner:
    options:
      prefix: '&6&lOwner'
    permissions:
    - essentials.gmc
  Co-Owner:
    options:
    build: true
    interact: true
      prefix: '&5&lCo-Owner'
    permissions:
    - essentials.gmc
    - SpawnJoin.use.warpothers
    - SpawnJoin.use.lobbies
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.home
    - plotme.use.list
    - plotme.use.info
    - plotme.use.biome
    - plotme.use.biome
    - plotme.use.clear
    - plotme.use.dispose
    - plotme.use.done
    - plotme.use.deny
    - plotme.use.undeny
    - plotme.use.buy
    - plotme.use.sell
    - plotme.use.auction
    - plotme.use.reset
    - plotme.use.middle
    - plotme.use.add
    - plotme.use.remove
    - plotme.use.protect
    - plotme.use.name
    - plotme.use.like
    - plotme.limit.#
    - modifyworld.blocks.destroy.*
    - modifyworld.blocks.place.*
    - modifyworld.blocks.interact.dispenser
    - modifyworld.blocks.interact.chest
    - modifyworld.blocks.interact.furnace
    - modifyworld.blocks.interact.burning_furnace
    - modifyworld.blocks.interact.jukebox
  Mod:
    options:
    build: true
    interact: true
      prefix: '&7&l[Mod]'
    permissions:
    - essentials.gmc
    - SpawnJoin.use.warpothers
    - essentials.tempban
    - essentials.fly
    - essentials.mute
    - essentials.ban
    - SpawnJoin.use.lobbies
    - essentials.mute
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.home
    - plotme.use.list
    - plotme.use.info
    - plotme.use.biome
    - plotme.use.biome
    - plotme.use.clear
    - plotme.use.dispose
    - plotme.use.done
    - plotme.use.deny
    - plotme.use.undeny
    - plotme.use.buy
    - plotme.use.sell
    - plotme.use.auction
    - plotme.use.reset
    - plotme.use.middle
    - plotme.use.add
    - plotme.use.remove
    - plotme.use.protect
    - plotme.use.name
    - plotme.use.like
    - plotme.limit.#
    - modifyworld.blocks.destroy.*
    - modifyworld.blocks.place.*
    - modifyworld.blocks.interact.dispenser
    - modifyworld.blocks.interact.chest
    - modifyworld.blocks.interact.furnace
    - modifyworld.blocks.interact.burning_furnace
    - modifyworld.blocks.interact.jukebox
  Youtuber:
    options:
    build: true
    interact: true
      prefix: '&6&l[YT]'
    permissions:
    - essentials.gmc
    - music.radio
    - SpawnJoin.use.warpothers
    - essentials.fly
    - SpawnJoin.use.warp.minigames
    - SpawnJoin.use.warp.kitpvp
    - SpawnJoin.use.lobbies
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.home
    - plotme.use.list
    - plotme.use.info
    - plotme.use.biome
    - plotme.use.biome
    - plotme.use.clear
    - plotme.use.dispose
    - plotme.use.done
    - plotme.use.deny
    - plotme.use.undeny
    - plotme.use.buy
    - plotme.use.sell
    - plotme.use.auction
    - plotme.use.reset
    - plotme.use.middle
    - plotme.use.add
    - plotme.use.remove
    - plotme.use.protect
    - plotme.use.name
    - plotme.use.like
    - plotme.limit.#
    - modifyworld.blocks.interact.*
  Awesome:
    options:
    build: true
    interact: true
      prefix: '&dAwesome'
      default: 'false'
    permissions:
    - essentials.gmc
    - SpawnJoin.use.warpothers
    - SpawnJoin.use.kitpvp
    - SpawnJoin.use.minigames
    - SpawnJoin.use.lobbies
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.home
    - plotme.use.list
    - plotme.use.info
    - plotme.use.biome
    - plotme.use.biome
    - plotme.use.clear
    - plotme.use.dispose
    - plotme.use.done
    - plotme.use.deny
    - plotme.use.undeny
    - plotme.use.buy
    - plotme.use.sell
    - plotme.use.auction
    - plotme.use.reset
    - plotme.use.middle
    - plotme.use.add
    - plotme.use.remove
    - plotme.use.protect
    - plotme.use.name
    - plotme.use.like
    - plotme.limit.#
    - modifyworld.blocks.destroy.*
    - modifyworld.blocks.place.*
    - modifyworld.blocks.interact.dispenser
    - modifyworld.blocks.interact.chest
    - modifyworld.blocks.interact.furnace
    - modifyworld.blocks.interact.burning_furnace
    - modifyworld.blocks.interact.jukebox
  2ndOwner:
    options:
    build: true
    interact: true
      prefix: '&2&l2ndOwner'
    permissions:
    - essentials.gmc
    - SpawnJoin.use.warpothers
  defalut:
    options:
    build: true
    interact: true
    permissions:
    - SpawnJoin.use.warpothers
    - simplekitpvp.inv.donator
    - modifyworld.blocks.destroy.*
    - modifyworld.blocks.place.*
    - modifyworld.blocks.interact.dispenser
    - modifyworld.blocks.interact.chest
    - modifyworld.blocks.interact.furnace
    - modifyworld.blocks.interact.burning_furnace
    - modifyworld.blocks.interact.jukebox
    - modifyworld.blocks.interact.*
    - SpawnJoin.use.warpothers
    - SpawnJoin.use.kitpvp
    - SpawnJoin.use.minigames
    - SpawnJoin.use.lobbies
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.home
    - plotme.use.list
    - plotme.use.info
    - plotme.use.biome
    - plotme.use.biome
    - plotme.use.clear
    - plotme.use.dispose
    - plotme.use.done
    - plotme.use.deny
    - plotme.use.undeny
    - plotme.use.buy
    - plotme.use.sell
    - plotme.use.auction
    - plotme.use.reset
    - plotme.use.middle
    - plotme.use.add
    - plotme.use.remove
    - plotme.use.protect
    - plotme.use.name
    - plotme.use.like
    - plotme.limit.#
  Admin:
    permissions:
    - '*'
    - modifyworld.blocks.destroy.*
    - modifyworld.blocks.place.*
    - modifyworld.blocks.interact.dispenser
    - modifyworld.blocks.interact.chest
    - modifyworld.blocks.interact.furnace
    - modifyworld.blocks.interact.burning_furnace
    - modifyworld.blocks.interact.jukebox
    - essentials.gmc
    options:
      prefix: '&b&l[Admin]'
schema-version: 1
users:
  e73dab75-82ba-44dc-b30f-80547022b9fa:
    permissions:
    - '*'
    - SpawnJoin.use.editspawn
    group:
    - default
    options:
      group: default
      name: 269Grimawesome
    worlds:
      Owner:
        permissions: []
  c5aed2d0-73ba-4986-9ce6-144066aa5c82:
    group:
    - Admin
    options:
      name: Kirby_YT
    permissions:
    - (
  39b6e8d2-d1ac-4890-b336-a0f74d3269cd:
    group:
    - Creator
    - Owner
    options:
      name: zaydenxm
    worlds:
      default:
        options:
          group: set
      Creator:
        permissions:
        - group
    permissions:
    - Creator
  ea869c94-8268-4e64-b9e8-e5fac6158e66:
    group:
    - Co-Owner
    permissions: []
    options:
      name: 3toisyou
  db1572c0-f9f8-496f-9e2d-7c8d256a1ecb:
    group:
    - Admin
    options:
      name: XxTunaPlayzxX
    permissions: []
  8374f2c6-6d47-4643-a4af-8a74d79c87c6:
    group:
    - Co-Owner
    options:
      name: AcaiciaHogan
    permissions: []
  f4ea444c-5b38-49f6-a5f6-4e0d64223bc6:
    options:
      name: 29planets
    group:
    - Youtuber
  zaydenyt:
    permissions:
    - '*'
  26c6f379-8559-468c-905a-de1038f7cb5e:
    group:
    - Admin
    options:
      name: Reveals
  c3c13195-a2a8-4008-bfbd-3713168fcd39:
    group:
    - Admin
    options:
      name: TokyoDev
  90508b2e-79c5-4e66-b2cb-7ead173b1a33:
    group:
    - Admin
    options:
      name: WholeGrainBread
    permissions: []
  f93d8122-a3a7-4bcf-8e82-61ae144571f2:
    group:
    - Youtuber
    options:
      name: 29planets_Laguna
  ba637ade-d867-44f7-821f-2859bb71878b:
    group:
    - Mod
    options:
      name: BennG89
  307bcc13-e09c-4d22-b49c-d100ca9e0b07:
    group:
    - Admin
    options:
      name: Cat_Loves_Cats
  269grimawsome:
    permissions:
    - '*'''
    group:
    - 2ndOwner
    - '0'
  5ae6a31f-b9e8-4838-b3c1-b69a312807e1:
    group:
    - Admin
    options:
      name: KinkinNW
    permissions: []
  8fa28c7d-9893-3825-b4ea-2b39cda91bc5:
    permissions:
    - '*'
    options:
      name: 269Grimawesome
  86868ade-c446-33ba-81fe-7bfd06191ee2:
    group: []
  94f635ff-3596-30e9-bc1e-a60ae4c9a134:
    group:
    - '0'
  kiby_yt:
    group:
    - Admin
  d16e4827-a318-4284-8df3-a73948993ec5:
    group:
    - Admin
    options:
      name: Jinkeys
  c079b5f7-a03f-43a5-9150-85de1af87def:
    group:
    - Admin
    options:
      name: kiwi8vjd
  1cf6d0c3-5f2a-4930-9963-c65ff11eea7b:
    group:
    - Admin
    options:
      name: Kernfrps
    permissions:
    - '*'
  269grimaweome:
    permissions:
    - '*'
  1d4070ad-e41b-4ad7-a6d7-088c15ab0073:
    group:
    - admin
    options:
      name: xXSeikoStormXx

**Comment by 269Grimawewsome** [comment]
also when I do /pex nothing happends

**Comment by Stormbow** [comment]
For Minecraft 1.9 and higher, follow [this example](https://pastebin.com/8ZSHxauG) for the formatting of your file.

• Co-Owner should be CoOwner, otherwise certain very popular plugins will not recognize it as a group on the server when some features of those plugins are used.  Also, a "Co-Owner" and "2ndOwner" are literally the same thing.  You may want to combine those groups to shorten your file.

• `essentials.gmc` is not a real permission node.  Check the [Essentials Permission Nodes list](http://wiki.ess3.net/wiki/Command_Reference/Perm) to ensure you're giving out real permissions.

• Since your file is formatted incorrectly, the "Owner" group can't do anything at all on the server.  The group has no inheritance and no permissions.  (It can't even use `/pex`.)

• Your user list has a lot of messed up stuff in it.  Double-check it to clean out the bad stuff.  (It's mostly a lot of really badly typed commands that put stuff that does nothing in the users' info.)

♦ Don't give out `- '*'` to people unless you absolutely trust them with your life because it gives them access to absolutely _everything_ on the server, including permission nodes they don't actually want and the _permission to delete everything on the server_.

----

After making all the above corrections, test the server and let me know if you need any additional help.

If the test shows that everything is fine, you can close the ticket below.  :-)

**Comment by 269Grimawewsome** [comment]
Hey So I cleaned Out the File But same Problem Still /pex douse not work

**Comment by 269Grimawewsome** [comment]
also ranks are still gone

**Comment by 269Grimawewsome** [comment]
I baked up the sever to yesterday and it worked but once when I restarted the server is like pex was never on the server

**Comment by Stormbow** [comment]
Show me your updated permissions.yml file.  Post it on [Pastebin ](https://pastebin.com)and leave the link in this thread.

**Comment by 269Grimawewsome** [comment]
https://pastebin.com/8kmpVeWb KEEP THE 2NDOWNER RANK

**Comment by Stormbow** [comment]
You didn't fix anything that I mentioned in my first post, about the formatting.

**Comment by 269Grimawewsome** [comment]
yes I did

**Comment by 269Grimawewsome** [comment]
well It lest I did the best I could

**Comment by Stormbow** [comment]
Look at the example that I linked for you and the latest file you linked for me.  Your options aren't under an options section or anything.

**Comment by 269Grimawewsome** [comment]
??

**Comment by 269Grimawewsome** [comment]
ok well I'm new at this stuff and I have adhd so I like think I do stuff but I dont

**Comment by Stormbow** [comment]
OK, well, you can download the example I made and customize that for your server.

**Comment by Stormbow** [comment]
After you get a working permissions file, you can fix the prefixes issue.

**Comment by 269Grimawewsome** [comment]
so I need to add all the permisons
again

**Comment by 269Grimawewsome** [comment]
...

**Comment by 269Grimawewsome** [comment]
Oh no

**Comment by 269Grimawewsome** [comment]
I'm going to die

**Comment by 269Grimawewsome** [comment]
uhhh

**Comment by Stormbow** [comment]
Stop spamming.

**Comment by 269Grimawewsome** [comment]
??/

**Comment by Stormbow** [comment]
You either want the server fixed, or you don't.  And since you don't want to fix the file according to the example I gave you, there's nothing else I can help you with here.
