### ISSUE TITLE
HOW DO I LOCK A CONVERSATION

### ISSUE THREAD

**Issue by 269Grimawewsome** [PEXPlugins/PermissionsEx#2865]
Help

**Comment by 269Grimawewsome** [comment]
zge5g5

**Comment by 269Grimawewsome** [comment]
et44ete

**Comment by 269Grimawewsome** [comment]
et4ete

**Comment by Stormbow** [comment]
Quit spamming, asshole.

**Comment by zml2008** [comment]
fun fact it's very possible to ban people from opening issues on a project

**Comment by Stormbow** [comment]
![thumbs up](https://t3.ftcdn.net/jpg/00/74/77/64/240_F_74776414_58VZoryp5C2Qmt2EoYFyN266ljQOcu2Y.jpg)

I reported him to Github, now looking forward to him getting banned entirely.
