### ISSUE TITLE
Anyone who enters my server has the title [Owner] and I dont know how to change it.

### ISSUE THREAD

**Issue by GregHippo302** [PEXPlugins/PermissionsEx#2866]

**Comment by Stormbow** [comment]
Which chat management plugin are you using?

**Comment by GregHippo302** [comment]
@Stormbow PermissionsEX

**Comment by Stormbow** [comment]
PEX doesn't handle chat; it just gives you a place to store the prefix/suffix.

You'd need something like EssentialsXChat to get them displayed in-game.

**Comment by GregHippo302** [comment]
I have ChatEx

**Comment by GregHippo302** [comment]
PEX and ChatEx

**Comment by Stormbow** [comment]
As far as I'm aware, most versions of ChatEx aren't compatible with PEX.  You can look through their config file to see how chat is being displayed, and change that stuff around to see if you can get it displaying prefixes correctly.  I have seen only one time that ChatEx did work on a PEX server.  I'd bet 99% of the Minecraft world uses EssentialsChat (Mc 1.8 and older) or EssentialsXChat (Mc 1.8.1 and newer).

**Comment by GregHippo302** [comment]
ok so should I uninstall ChatEx and install EssentialsXChat instead. (1.12 server)

**Comment by Stormbow** [comment]
If you're running a Spigot server, you could run EssentialsX (the base component of EssentialsXChat), and be sure to install Vault (a dependency for EssentialsXChat).

**Comment by GregHippo302** [comment]
I'm using bukkit

**Comment by Stormbow** [comment]
Well...  Bukkit/Craftbukkit was officially discontinued at 1.8 also, because one of the authors claimed copyright infringement against the others on the team and shut the whole thing down.  (What an ass!)  So I'm not entirely sure what version of Essentials you _should_ use.

You can try [this bunch of files](https://hub.spigotmc.org/jenkins/job/spigot-essentials/), taking only the ones you plan to use.  It says it's "Spigot Essentials", but that's the only stuff I saw work on a "bukkit" server.

**Comment by Stormbow** [comment]
The same Vault dependency applies there, too.

**Comment by Stormbow** [comment]
(The EssentialsXChat page is [right here](http://ci.drtshock.net/job/essentialsx/), and looks similar.)

**Comment by GregHippo302** [comment]
well I'm using an MCProhoasting server and it says I'm using CraftBukkit

**Comment by GregHippo302** [comment]
ok il check out that page

**Comment by Stormbow** [comment]
> it says I'm using CraftBukkit

Yeah.  I have no idea where they downloaded that though, since the website (bukkit) doesn't even have downloads for it anymore.

**Comment by GregHippo302** [comment]
ok

**Comment by Stormbow** [comment]
You'll find [this excerpt](https://pastebin.com/eHCCcNuY) of the Essentials\config.yml file to be helpful too.  It'll show you how to get the file setup correctly for prefixes.

**Comment by Stormbow** [comment]
Once you get all that stuff together, let me know if you need any additional help with it.

If everything's fine, you can close the ticket below. :-)

**Comment by GregHippo302** [comment]
Ok thank you so much.

**Comment by Stormbow** [comment]
You're welcome. :-)
