### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by tamedkek** [PEXPlugins/PermissionsEx#2873]
```
Caused by: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 1, column 1:
    groups: {}
    ^
expected <block end>, but found BlockMappingStart
 in 'string', line 2, column 3:
      ninja:
      ^
```

```
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 1, column 1:
    groups: {}
    ^
expected <block end>, but found BlockMappingStart
 in 'string', line 2, column 3:
      ninja:
      ^
```

**] Edit by Stormbow: highlighted the actual errors. [**

**Comment by NightPotato** [comment]
Is the config file a fresh one?

**Comment by Stormbow** [comment]
Your permissions.yml file contains errors.  Pastebin that for me and I can tell you specifically how to fix it.

**Comment by tamedkek** [comment]
https://pastebin.com/yJiQKP2F

**Comment by Stormbow** [comment]
Line 1: remove the curly braces.  `{ and }`

**Comment by Stormbow** [comment]
Make sure all of your indentation and formatting matches [the example](https://pastebin.com/8ZSHxauG).

**Comment by tamedkek** [comment]
next

**Comment by Stormbow** [comment]
Next, show me your corrected permissions.yml file.

**Comment by tamedkek** [comment]
groups: 
  ninja:
    options:
      prefix:'&0[ninja&0] &r '
       permitions:
    - essentals.kit.ninja
   PvP:
    options:
      prefix:' [pvp]  
       permitions:
    - essentals.kit.PvP
   tank:
   options:
      prefix: ' &1[TANK&1] &r '
       permitions:
    - essentals.kit.TANK
   phoenix:
    options:
      prefix:'&6[phoenix&6] &r '
       permitions:
    - essentals.kit.phoenix
    schema-version: 1
users:
  0be58318-b94a-4530-a35e-a1639af3f954:
    group:
    - owner
    options:
      name: Tamed_taco_pap
      group: tank


ITS NOT LONG

**Comment by Stormbow** [comment]
So what was the deal with you and your friend accusing me of stealing everyone's server because of the [example file](https://pastebin.com/8ZSHxauG), anyway?

**Comment by Stormbow** [comment]
The indentation of your file is still wrong and you spelled permissions wrong everywhere.

**Comment by Stormbow** [comment]
Download the example file I linked for you, and count the spaces at the front of each line.  Be sure to use spaces and not the tab key.

**Comment by Stormbow** [comment]
Everything working ok now?

**Comment by Stormbow** [comment]
No reply in more than 7 days.  Issues must be resolved.
