### ISSUE TITLE
PermissionEx with Mysql

### ISSUE THREAD

**Issue by fredclever44** [PEXPlugins/PermissionsEx#2876]
I connected Permission Ex with a mysql server. 

Imported the permission file and everything is working.
But when I'm going to add a player in the main lobby to a rank the rank is not added all other servers.
heres my config on the lobby server and my config on the subservers.

Lobby:
`permissions:
  backend: sql
  backends:
    sql:
      uri: mysql://localhost/permissionex
      user: minecraft
      password: 
      type: sql
  debug: false
  allowOps: false
  user-add-groups-last: true
  log-players: false
  createUserRecords: true
  informplayers:
    changes: true
  basedir: plugins/PermissionsEx
multiserver:
  use-netevents: true
updater: true
alwaysUpdate: false
`
Subserver:
`permissions:
  backend: sql
  backends:
    sql:
      uri: mysql://localhost/permissionex
      user: minecraft
      password: 
      type: sql
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players:  false
  createUserRecords: false
  informplayers:
    changes:  false
  basedir: plugins/PermissionsEx
multiserver:
  use-netevents: true
updater: true
alwaysUpdate: false
`

I am searching a long time for that problem already, and I hope I can find help here

**Comment by Stormbow** [comment]
Unfortunately, SQL issues have to wait for @zml2008 to respond because I haven't used SQL in a very, very long time and have forgotten most of what I used for the single month that I used SQL on a server.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
