### ISSUE TITLE
Pex Error !!! ;_;

### ISSUE THREAD

**Issue by PirataGu** [PEXPlugins/PermissionsEx#2878]
My pex is not work ... Why ? Can u Help Me ????
![2017-07-19_00 04 34](https://user-images.githubusercontent.com/30275479/28344889-1b99bd2c-6c16-11e7-9bfd-4b69e375a8f2.png)

**Comment by Stormbow** [comment]
Your permissions.yml file contains one or more errors.

Copy your file to [Pastebin](http://pastebin.com), leave the link in this thread, and I can help you find them.

**Comment by PirataGu** [comment]
https://pastebin.com/7LXNfjZr -> my config.yml

**Comment by PirataGu** [comment]
https://pastebin.com/wPanXsaz ->  permissions.yml

**Comment by Stormbow** [comment]
Fixed: https://pastebin.com/q7ML6EF9

**Comment by PirataGu** [comment]
tks . 
But inst show the Preffix...
![2017-07-19_13 04 33](https://user-images.githubusercontent.com/30275479/28368160-e4c370fa-6c82-11e7-9d4f-08162d68972c.png)

**Comment by PirataGu** [comment]
tks!

**Comment by Stormbow** [comment]
You're welcome. :)
