### ISSUE TITLE
Are you dead?

### ISSUE THREAD

**Issue by pocakking** [PEXPlugins/PermissionsEx#2879]
Basically the title.

**Comment by zml2008** [comment]
no just sleeping

**Comment by Stormbow** [comment]
I'm not here.  If I get back before I see me, be sure to tell me to wait for me.

**Comment by pocakking** [comment]
Oh ok.

**Comment by pocakking** [comment]
Is the plugin abandoned?

**Comment by Stormbow** [comment]
10,000,000 downloads and counting.

I would say" "No, it's not abandoned."
