### ISSUE TITLE
Minecraft - Server Issue?

### ISSUE THREAD

**Issue by TexorYT** [PEXPlugins/PermissionsEx#2882]
Ummm.... Ok,
So This Is Very Odd And No Well-Seen.
I Dont Know What This Does/Mean, But Ok?
I Looked In The Console And It Says This:

Issue >> https://gyazo.com/35e56420fb5b8d15a6738a2e482d6c3c
Sooo, What Do I Do Here?

**Comment by Stormbow** [comment]
That's a Spigot Build Tools related message.  Spigot wants you to run the [Build Tools procedure](https://www.spigotmc.org/wiki/buildtools/#running-buildtools) again to get an updated Spigot.jar file.

Unrelated to PermissionsEx.

**Comment by Stormbow** [comment]
Try to keep all your comments in one ticket please.  I'm already helping you in #2881 .

**Comment by TexorYT** [comment]
ok. im new to github so thx
