### ISSUE TITLE
Isnt Work

### ISSUE THREAD

**Issue by PirataGu** [PEXPlugins/PermissionsEx#2886]
My Pex isnt working ... the Preffix/suffix doesnt appear... My pex stop in the rank "Principe" but should stop in the rank "Deus".
When I'm testing 1 of these ranks I do deop and says that I do not have permissions to the commands I marked in Permissions.yml ...

Permissions.yml -> https://pastebin.com/z7PKJAHW
Config -> https://pastebin.com/VEmXBqQF

And can you help me with something else? I wanted when a new person entered my server to receive the rank "Aldeao" (NewCommer), which is not happening because the player is left with no Perms

**Comment by Stormbow** [comment]
The permissions.yml file parses cleanly, so something else is interfering with PermissionsEx.

Show me your console log (on [Pastebin](http://pastebin.com), of course) from the moment you start the server through the point where text stops printing to the screen and you see a message similar to "Done!".

**Comment by Stormbow** [comment]
On an unrelated note, your `rank:` values are backwards.  "Newcomer" would be a high number and "Deus" would be a low number.

Also, `essentials.warp.[warpname]` needs to be a specific warp name, like `essentials.warp.market` or `essentials.warp.fishing`.

**Comment by Stormbow** [comment]
You spelled `options:` wrong in 6 groups.  There's no zero in the word "options".  :-P

----

On an unrelated note, your `rank:` values are backwards.  "Newcomer" would be a high number and "Deus" would be a low number.

Also, `essentials.warp.[warpname]` needs to be a specific warp name, like `essentials.warp.market` or `essentials.warp.fishing`.

**Comment by Stormbow** [comment]
Also, the kit nodes must be pluralized: `essentials.kits.vicepresidente`.  Only the slash command node is singular: `essentials.kit`.

**Comment by Stormbow** [comment]
Also, Minecraft 1.9 and higher requires that every group has an inheritance section.  See [this example](https://pastebin.com/8ZSHxauG) for how to give each group an inheritance.

**Comment by Stormbow** [comment]
You spelled `options:` wrong in 6 groups.  There's no zero in the word "options".  :-P

----

On an unrelated note:

• Your `rank:` values are backwards.  "Newcomer" would be a high number and "Deus" would be a low number.

• Also, `essentials.warp.[warpname]` needs to be a pluralized and a have a specific warp name, like `essentials.warps.market` or `essentials.warps.fishing`.  The node you have— `essentials.warp.[warpname]` —is not a real node.

• Also, the kit nodes must be pluralized: `essentials.kits.vicepresidente`.  Only the slash command node is singular: `essentials.kit`.

• Also, Minecraft 1.9 and higher requires that every group has an inheritance section.  See [this example](https://pastebin.com/8ZSHxauG) for how to give each group an inheritance.

• Also, lines 645 and 646 of your file need to be deleted.  They aren't part of PEX and don't contain any information.

**Comment by Stormbow** [comment]
Once all of the above issues have been addressed, test the server and let me know if you need additional help.

**Comment by PirataGu** [comment]
Check Please ._.
https://pastebin.com/a8xSQkQg

**Comment by PirataGu** [comment]
The /kit , /warp and /money doesnt work

**Comment by Stormbow** [comment]
• Your `rank:` values are backwards.  "Newcomer" would be 16 and "Deus" would be 1.

• `essentials.kits` is wrong.  `essentials.kit` is right.  `essentials.kit.Lord` is wrong.  `essentials.kits.Lord` is right.

• Minecraft 1.9 and higher requires that every group has an inheritance section.  See [this example](https://pastebin.com/8ZSHxauG) for how to give each group an inheritance.  All groups need inheritance.

**Comment by PirataGu** [comment]
Ah now I realize!

**Comment by Stormbow** [comment]
Additional comments added to my previous post.  Read them closely.

**Comment by PirataGu** [comment]
Okay. Tomorrow I'll try to do this because it's late already.

**Comment by Stormbow** [comment]
Ok.

**Comment by PirataGu** [comment]
It's all working! Minus the Prefixes / Suffixes

**Comment by Stormbow** [comment]
Those are handled by a chat management plugin.  Since you're using Essentials, you'll probably want EssentialsChat, in which case [this guide](https://pastebin.com/eHCCcNuY) will help you.

**Comment by PirataGu** [comment]
Its All Working !!! Tks !!

**Comment by Stormbow** [comment]
You're welcome. :-) Have fun!
