### ISSUE TITLE
PEX won't allow group changing?

### ISSUE THREAD

**Issue by MooshroomStatus** [PEXPlugins/PermissionsEx#2888]
I'm having an issue with PEX. I just started using it for the first time. I created multiple groups successfully (i.e. the standard: Owner, Moderator, Helper, etc.). I switched myself into Owner of course. Afterwards, I tried switching to Moderator to test the prefixes and was still set as owner. I then tried to switch to default and the chat still said owner. Help?

**Comment by MooshroomStatus** [comment]
Edit:
Nevermind. I realized my name wasn't changing due to variable issues in the essentials config itself.

**Comment by MooshroomStatus** [comment]
Another Edit:
ok, so now I'm very confused. I'm able to switch back and forth between groups now, but for some reason Owner and Helper say:
Owner [Owner]
Helper [Helper]
but default and Moderator read:
[Default]
[Moderator]
Everything is formatted exactly the same in the files. I don't understand why 2 of my ranks repeat the beginning but the other 2 don't? Help?

**Comment by Stormbow** [comment]
Show me your config.yml for Essentials and your permissions.yml for PEX.

**Comment by Stormbow** [comment]
No response from @MooshroomStatus in 7 days.  I guess this issue is resolved.
