### ISSUE TITLE
Switching to mandatory 2FA on the PEXPlugins organization starting 3 August

### ISSUE THREAD

**Issue by zml2008** [PEXPlugins/PermissionsEx#2889]
@Stormbow @t3hk0d3 this is for you (though I imagine t3hk0d3 would not be affected much either way)

Since we've had some issues with people defacing PEX's web presence in the past, it seems reasonable to take precautions to prevent any unauthorized modification of the PEX repository. One of these precautions is requiring 2FA for every contributor, which I will do in one week from today on **August 3rd**. Currently I am the only person with this enabled, but once I enforce 2FA for the organization you two **will be removed from the GH organization** unless you have enabled 2FA. I use a Yubikey for this, but the phone apps or any U2F dongle will work just as well. Let me know if there are any questions on getting this enabled.

**Comment by Stormbow** [comment]
2FA now enabled here!

Good call and thanks for the head's up.
