### ISSUE TITLE
my tags of PEX not work [MC bukkit 1.8.8]

### ISSUE THREAD

**Issue by RomeuDM** [PEXPlugins/PermissionsEx#2895]
I've done everything to solve this problem but nothing works, the prefix that I set does not stop in my group, example I'm in the group Admin and my prefix is ​​in the Usuario group
here my permissions
https://pastebin.com/VHcyLD42

**Comment by Stormbow** [comment]
Unfortunately, the prefixes are displayed in-game by a chat management plugin, not PEX.  PEX just gives you a place to store the information.

Which chat management plugin are you using?  I may be able to help you get it configured correctly.

**Comment by RomeuDM** [comment]
I do not know if it has a problem, but I'm using the essentials chat management here is the essentials link and its setup, thanks for the attention.

https://pastebin.com/pef8CfVf
https://dev.bukkit.org/projects/permissionsex

**Comment by Stormbow** [comment]
Ok, cool.  EssentialsChat I can help with more than other chat plugins.

Check out [this piece](https://pastebin.com/eHCCcNuY) of the Essentials\config.yml file.  This stuff will be found around lines 32 (for the top half of this link) and 532 (for the bottom half of this link) inside your file.  Change these parts in your file to look like the stuff you see in these example sections.

**Comment by Stormbow** [comment]
Is everything working now?

**Comment by Stormbow** [comment]
No reply from @RomeuDM in 7 days.  I guess this issue is resolved.
