### ISSUE TITLE
[SQL][Ubuntu] Mysql 5.7.19 issue

### ISSUE THREAD

**Issue by juanruiz85** [PEXPlugins/PermissionsEx#2896]
I can not connect to my mysql server, I was using the mysql 5.5 and worked without issues but I updated my computer and installed ubuntu 17.04 and now I can not install the old version of mysql and the new one does not let me connect

here the error 
```
[04:48:36] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
--
[04:48:36] [Server thread/INFO]: [PermissionsEx] Initializing sql backend
[04:48:36] [Server thread/ERROR]: [PermissionsEx]
========== UNABLE TO LOAD PERMISSIONS BACKEND =========
Your configuration must be fixed before PEX will enable
Details: Unable to connect to SQL database
=======================================================
ru.tehkode.permissions.exceptions.PermissionBackendException: Unable to connect to SQL database

**Caused  by:  com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException:  Client does not support authentication protocol requested by server;  consider upgrading MySQL client**

[04:48:36] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
```
thank you

**Comment by Stormbow** [comment]
Since this is an SQL issue, you'll need to wait for @zml2008 to reply.  He has much more experience with SQL than I have.  (Also, I have no experience at all with Ubuntu; he may have some.)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
