### ISSUE TITLE
Players Not Being Able To Use Warps?

### ISSUE THREAD

**Issue by TexorYT** [PEXPlugins/PermissionsEx#2899]
Hi. This Is A Very Strange Issue. Whenever I de-op Myself Or Bring My Friends On My Server, it’s impossible to use /warp OR /warps. I Want To Fix This To Specific Warps. EX: 
1. /warp playerlounge (able to do ✔️)  
2. /warp adminlounge (unable to do ❌)

Please Help Me.
PS: here are the nodes I used: - essentials.warp.crates
essentials.warp.spawn (etc)
PSS: I’m typing this on my phone and not my pc. Therefor I don’t know what exact nodes I used.

If Anyone Requests the PEX permissions.yml file I will show it.

**] Edit by Stormbow: Corrected typo. :-)  [**

**Comment by TexorYT** [comment]
“I want to Fox this to specific Warps”
Fix* not fox lol

**Comment by Stormbow** [comment]
Ok, show me the permissions.yml file please.

**Comment by Stormbow** [comment]
Is this another ticket where I don't hear from you for 3-5 days at a time?  LOL

**Comment by TexorYT** [comment]
Srry :( didn’t know I troubled u that much ;(

**Comment by Stormbow** [comment]
No trouble.  I'm just teasing you.  :-)

I'm here whenever ya need me. :-)

**Comment by TexorYT** [comment]
groups:
  default:
    options:
      default: true
    inheritance: []
    permissions:
    - essentials.warp.*
    - essentials.warp.list
    - essentials.kit
    - essentials.kits.*
    - essentials.msg
    - essentials.ping
    - essentials.warp.*
    - essentials.warp.cratekeys
    - essentials.warp.crates
    - essentials.warp.diamonds
    - essentials.warp.duel
    - essentials.warp.help
    - essentials.warp.house
    - essentials.warp.minerals
    - essentials.warp.portals
    - essentials.warp.spawn
    - essentials.warp.sspawn
  VIP:
    options:
      default: false
    inheritance:
    - default
    permissions:
    - essentials.enchant.*
    - essentials.ptime
    - essentials.repair
    - essentials.me
    - essentials.nick.*
    - essentials.warp.*
    - essentials.warp.*
    - essentials.warp.cratekeys
    - essentials.warp.crates
    - essentials.warp.diamonds
    - essentials.warp.duel
    - essentials.warp.help
    - essentials.warp.house
    - essentials.warp.minerals
    - essentials.warp.portals
    - essentials.warp.spawn
    - essentials.warp.sspawn
  MVP:
    options:
      default: false
    inheritance:
    - VIP
    permissions:
    - essentials.msg.color  
    - essentials.seen.*
    - essentials.clearinventory
    - essentials.enderchest.*
    - essentials.getpos
    - essentials.warp.*
    - essentials.warp.*
    - essentials.warp.cratekeys
    - essentials.warp.crates
    - essentials.warp.diamonds
    - essentials.warp.duel
    - essentials.warp.help
    - essentials.warp.house
    - essentials.warp.minerals
    - essentials.warp.portals
    - essentials.warp.spawn
    - essentials.warp.sspawn
  Admin:
    options:
      default: false
    inheritance:
    - MVP
    permissions:
    - essentials.ban
    - essentials.ban.exempt
    - essentials.banip
    - essentials.burn
    - essentials.clearinventory
    - essentials.clearinventory.others
    - essentials.ext
    - essentials.gc
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.exempt.notify
    - essentials.ping
    - essentials.mute
    - essentials.mute.exempt
    - essentials.mute.notify
    - essentials.tempban
    - essentials.ban.notify
    - essentials.vanish
    - essentials.vanish.effect
    - essentials.vanish.interact
    - essentials.vanish.see
    - essentials.vanish.pvp
    - essentials.warp.*
    - essentials.warp.*
    - essentials.warp.cratekeys
    - essentials.warp.crates
    - essentials.warp.diamonds
    - essentials.warp.duel
    - essentials.warp.help
    - essentials.warp.house
    - essentials.warp.minerals
    - essentials.warp.portals
    - essentials.warp.spawn
    - essentials.warp.sspawn
schema-version: 1
users:

**Comment by TexorYT** [comment]
oops
srry ment to paste github link

**Comment by Stormbow** [comment]
OK, that's an easy fix.  You just got he permission nodes wrong.

`essentials.warp` gives you access to the `/warp` slash command.

`essentials.warp.*` doesn't give you anything.

**Comment by TexorYT** [comment]
soo, ho do i fix this?

**Comment by Stormbow** [comment]
Delete everything in the file that says `essentials.warp.*` and make it `essentials.warp`.

**Comment by TexorYT** [comment]
Do I ad that extra period?
essentials.warp.
(After warp there is a period)

**Comment by Stormbow** [comment]
The end of a sentence always has a period.  :P  

The permission node `essentials.warp` inside the gray box does not have a period at the end of it.

**Comment by TexorYT** [comment]
Like This? >> https://pastebin.com/N2i7eJ7Y

**Comment by Stormbow** [comment]
I seriously think you're just screwing around with me now.

Look at the [Essentials Permissions List](http://wiki.ess3.net/wiki/Command_Reference/Perm).  Do you see `essentials.warp.*` on there?  No.  Remove it from your file entirely, everywhere.

The correct node is `essentials.warp` to give players access to the /warp command.

**Comment by Stormbow** [comment]
You know the correct node.  You know how to put permissions in your file.

This ticket is resolved.

**Comment by TexorYT** [comment]
*sigh* it’s not working

**Comment by Stormbow** [comment]
Ok. Give me about 30 minutes.  I'll rewrite your file for you.  :-)

**Comment by Stormbow** [comment]
OK, use [this](https://pastebin.com/Wm0WLr1Z) as your permissions.yml file.

**Comment by TexorYT** [comment]
Thx

**Comment by TexorYT** [comment]
But there is some warps on there I don’t want players to use. How to fix this?

**Comment by Stormbow** [comment]
Delete those permissions from the group(s).
