### ISSUE TITLE
Bungee?

### ISSUE THREAD

**Issue by Loonyy** [PEXPlugins/PermissionsEx#2903]
Hey, can you use this plugin for Bungee to have ranks connected on all servers? If so, can you just transfer all your files from a spigot server?

**Comment by Stormbow** [comment]
**Can you use PEX for Bungeecord servers?**  Absolutely.  Unfortunately, you'll need to read the [Bungeecord documentation](https://www.spigotmc.org/wiki/bungeecord/) to figure out how to set up their form of server network.  I've never set one up myself.

**Comment by Loonyy** [comment]
I already have a Bungee server set up haha, it's if PermissionsEx supports it or not. If it does support it, I'm wondering if I can just transfer the files from my normal Spigot server onto a Bungee server.

**Comment by Loonyy** [comment]
If the file creation and such is the same for Bungee version as it is for Spigot, then it should be fine.

**Comment by Stormbow** [comment]
Yep.  PEX is PEX, no matter where you're using it.  ;-)

**Comment by Loonyy** [comment]
One more question; can I place PEX in the Bungee server or does it need to be on each Spigot server?

**Comment by Stormbow** [comment]
I have no idea how to setup a Bungeecord server since I've never set one up.

I can, fortunately, give you a direct link to the Bungeecord Setup Instructions, found [here](https://www.bisecthosting.com/clients/knowledgebase/29/How-to-setup-BungeeCord.html) and [here](https://www.spigotmc.org/wiki/bungeecord-installation/).

**Comment by Loonyy** [comment]
..I'm not trying to setup Bungee, I've already set it up. What I'm asking is about PermissionsEx and if it's compatible to place on a BungeeCord server and if I should do that instead of placing it on each individual server.

**Comment by Stormbow** [comment]
Oh.  I already [answered that](https://github.com/PEXPlugins/PermissionsEx/issues/2903#issuecomment-319484265).  ;-)

**Comment by Loonyy** [comment]
... you really don't know anything about what I'm asking lmao

**Comment by Loonyy** [comment]
Nevermind!

**Comment by Stormbow** [comment]
Does PEX work on Bungeecord servers?

Yes.

It's not my fault if you're inarticulate and trying to ask something else.  Quit being a rude ass.
