### ISSUE TITLE
"You do not have acess to that command" Error PEX

### ISSUE THREAD

**Issue by BolsaFamiliaBR** [PEXPlugins/PermissionsEx#2904]
*I'm sorry if have any errors in English, I'm Brazilian and I'm not good in English.*

   I having a issue that is realy bugging me, my permissions file have a lot of groups, my issue is about "default" group and "F" group (the groups "B C D and E" have the same permissions of default) and the F group I want to add 4 new permissions nodes
`
  - essentials.warps.MinaF
  - essentials.sell
  - essentials.worth
  - essentials.kits.RankF`

    And when i try use a command in F group i get this error message in the minecraft chat:
    "You do not have acess to that command"
     
    And in the console to:
    [Server] INFO BolsaFamiliaBR was denied access to command.

   (Default rank is all right)

   Permissions.yml: https://pastebin.com/aQTx6h3E

**Comment by Stormbow** [comment]
Be sure to give yourself direct access to PermissionsEx commands.  Type this into the console (but use your Minecraft name):
```
    pex user Stormbow add permissions.*
```

See if that fixes your error message. :-)

**Comment by BolsaFamiliaBR** [comment]
it's not that, the player can't use any command like:

/warp
/spawn
/kits
etc

If the player are in the default group (or B C D E) he can
but if he are in the F group he can't type any command

**Comment by Stormbow** [comment]
Oh!  I thought you were trying to use PEX Commands to add permissions to groups, and didn't have access.

Looking at your permissions.yml file, I can see the problem now— the file format is outdated, has blank lines in it (line 59), and you're only showing me part of the file (missing the `schema-version: 1` line and `users:` section.

Use [this example](https://pastebin.com/8ZSHxauG) as the starting point to make your server file.  :-)

Be sure to use the [Essentials Permission Nodes List](http://wiki.ess3.net/wiki/Command_Reference/Perm) to make sure you have the correct nodes distributed.

**Comment by Stormbow** [comment]
Once your file is using the updated format, share it with me again if you still have problems.

**Comment by BolsaFamiliaBR** [comment]
Ok...

I wrote a new form of the "F" group, see:

  _F:
    build: true
    prefix: '&4[&eRank F &f- &6Soldado II&4]&f> '
    Permissions:
    - essentials.sell
    - essentials.worth
    - essentials.warps.MinaF
    - essentials.kits.RankF
    inheritance:
    - default_  

now i can type commands like /spawn, /warp, but i have a new issue, the new commands don't work (warp minaf, kit rankf, sell, worth)

the nodes are all right, now i just want to provide the players that are in the "F" group the new permissions

**Comment by Stormbow** [comment]
Corrected:

```
  F:
    options:
      build: true
      prefix: '&4[&eRank F &f- &6Soldado II&4]&f> '
    inheritance:
    - default
    Permissions:
    - essentials.sell
    - essentials.worth
    - essentials.warp
    - essentials.warps.MinaF
    - essentials.kit
    - essentials.kits.RankF
```

**Comment by BolsaFamiliaBR** [comment]
Did not work, i put this and try add permissions in console

like that:
pex group F add essentials.warps.minaf

and work! did have any problem doing this?

**Comment by Stormbow** [comment]
Desculpa. Diga isso em português?

**Comment by BolsaFamiliaBR** [comment]
Inicialmente o que você mandou acima não funcionou;
então eu coloquei o que você mandou e coloquei as permissões pelo console

Escrevendo isso no console:
**pex group F add essentials.warps.minaf**

E funcionou (Quando eu adicionei manualmente pelo console e agora jogadores no grupo de permissões "F" podem usar os comandos que eu queria (/warp minaf, /kit rankf, /sell, /worth)

**Comment by Stormbow** [comment]
Não. Você também pode fazer isso. :-) A maioria das pessoas apenas edita o arquivo no Bloco de Notas, como fizemos inicialmente, mas editar o arquivo usando os [Comandos PEX](https://pastebin.com/Kd269wd7) no console também é bom. :-)

**Comment by BolsaFamiliaBR** [comment]
Thank you ;)

**Comment by Stormbow** [comment]
You're welcome. :)
