### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Valkarm** [PEXPlugins/PermissionsEx#2906]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/2d2cb837c5f5f39d81a5cfdec4afeeb6)
.

**Comment by Stormbow** [comment]
You need to give one group a setting of "default: true".  This is for the group into which all users are placed when they first join the server.  Then the error you're receiving will stop. :-)

**Comment by Stormbow** [comment]
```
/pex group <group> set <option> <value>
/pex group Gracz set default true
```

**Comment by Valkarm** [comment]
How to do it?

**Comment by Valkarm** [comment]
I've already done this and still is:
groups:
  Gracz:
    permissions:
    - essentials.tpa
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.sklep
    - essentials.warps.bunnge
    - essentials.warps.craft
    - essentials.warps.Enchant
    - essentials.warps.mieso
    - essentials.warps.balon
    - essentials.warps.klata
    - essentials.warps.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.kits.drewno
    - essentials.kits.start
    - funnyguilds.player
    - essentials.home
    - essentials.helpop
    - essentials.spawn
    - essentials.msg
    - essentials.tpdeny
    - essentials.kit
    - essentials.tpaccept
    - drop_old.stone
    - karolekdrop.executors.stone
    - karolekdrop.diament
    - buffshop.cmd
    options:
      default: 'true'

**Comment by Stormbow** [comment]
When you start the server, copy all of the text printed on the server console and paste it on [Pastebin](http://pastebin.com).  Leave the link created by Pastebin in this thread.

**Comment by Valkarm** [comment]
https://pastebin.com/g1ByGchX

**Comment by Stormbow** [comment]
I don't want to see the error, I want to see the entire server console log.

**Comment by Valkarm** [comment]
https://pastebin.com/bSNLBmJp

**Comment by Stormbow** [comment]
[20:20:59] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

PermissionsEx will never function correctly in offline mode unless you're running a Bungeecord server network.  (And you don't have Bungeecord installed on your server.)

You will need to change the server.properties file setting `online-mode=false` to `online-mode=true`.

**Comment by Valkarm** [comment]
Already

**Comment by Stormbow** [comment]
Jeśli nie zmienisz tego ustawienia w pliku, PermissionsEx nigdy nie będzie działał na Twoim serwerze. Jeśli nie zmienisz tego i kłamesz, że zmieniłeś to, mimo że to co robimy, aplikacje PermissionsEx nadal nie działają na Twoim serwerze.

**Comment by Valkarm** [comment]
I did, but now I can not get on the server because it says: Access: token can not be null or empty.

**Comment by Stormbow** [comment]
http://www.minecraftforum.net/forums/support/server-support/1886258-access-token-cannot-be-null-or-empty

**Comment by Stormbow** [comment]
Seems like you need to reinstall Minecraft or migrate your account to the new system.

**Comment by Stormbow** [comment]
That's not a PEX issue though, sorry.

**Comment by Valkarm** [comment]
It's online mode

**Comment by Stormbow** [comment]
The token error can only be fixed by uninstalling Minecraft and reinstalling it, or by logging into the [Minecraft website](https://minecraft.net) and going through their [migrate process](https://account.mojang.com/migrate).  I can't do anything about that here.

**Comment by Stormbow** [comment]
After you get your Minecraft client fixed, feel free to come back if you need additional help with PermissionsEx.  :-)
