### ISSUE TITLE
permissions.yml not working and i dont know why?

### ISSUE THREAD

**Issue by blockoboyo** [PEXPlugins/PermissionsEx#2907]
I completely restarted my permissions.yml file today, I did this so i could restart my ranking process.
It worked fine before, but now it doesnt work at all? Please help me figure out why this is happening?

The following is my permissions.yml:

https://pastebin.com/HbQCm8qF

**Comment by Stormbow** [comment]
• Line 107: You forgot the apostrophe at the end of the `prefix:`.

• Line 116: You forgot the colon after `rank`.

No other sytax errors after that, so the file should work.  Give it a test after those 2 corrections and let me know if you need additional help.  :-)

**Comment by blockoboyo** [comment]
Thank You so much! This really helped! :D

**Comment by Stormbow** [comment]
You're welcome. :-)

Come on back if you run into any other PEX problems.  :-)  Until then— have fun!
