### ISSUE TITLE
Players Can Break Blocks?

### ISSUE THREAD

**Issue by TexorYT** [PEXPlugins/PermissionsEx#2908]
Hi (Stormbow). Earlier today I told my friends to get on my server. I was making a kitpvp server and a creative server. My friends could build and break in their own plot on creative, but could also build and break on kitpvp server? I deop them, and they still could do it. Help?

**] Edit by Stormbow: Corrected the spelling of my name.  You'd think someone with half a dozen tickets and dozens of posts back and forth to me could spell my name right...  :-P  [**

**Comment by Stormbow** [comment]
You need a plugin which prevents people from breaking blocks in specified areas.  Most people use [WorldGuard](https://dev.bukkit.org/projects/worldguard) for this sort of region protection.

It's not a PermissionsEx issue at all.

**Comment by TexorYT** [comment]
1. Sorry auto correct see: storm now 
2. Sorry thought it was a permissions node
3. I have world guard. How to use specific areas?

**Comment by Stormbow** [comment]
I'd start by watching [WorldGuard Tutorial videos](https://www.google.com/search?q=WorldGuard+Minecraft+video&source=lnms&tbm=vid&sa=X&ved=0ahUKEwiz5Ob45rvVAhWq5lQKHezLCUgQ_AUICigB&biw=1600&bih=767)

**Comment by Stormbow** [comment]
and read the [WorldGuard Wiki](http://wiki.sk89q.com/wiki/WorldGuard) for all the little extras you can do.
