### ISSUE TITLE
New players have access to other groups' permissions.

### ISSUE THREAD

**Issue by PirataGu** [PEXPlugins/PermissionsEx#2911]
Yes I'm back!!! XD I found another bug. When I log in with a new account on my server it has permissions to all the Kits and get into regions that other ranks can. I'll make it up. When I log into the Server with a new account I present myself in Group "NewComer" but I have permissions to kits of other groups (NewComer should only have permission for the NewComer kit) and also can enter zones of other ranks (NewComer has a single site Of the group but can enter the zones of other groups). Help me

**Comment by PirataGu** [comment]
https://pastebin.com/KW7ppd2C - CONFIG
https://pastebin.com/46pZDcwZ - Permissions

**Comment by Stormbow** [comment]
What's the server address?

**Comment by PirataGu** [comment]
Do you want to log in to see the bug?

**Comment by PirataGu** [comment]
Does this have private messages?

**Comment by Stormbow** [comment]
Nope.  Just post it here and I'll delete it after I get it.

**Comment by PirataGu** [comment]
Version Bukkit 1.8.7

**Comment by PirataGu** [comment]
EpicMCPT.aternos.me

**Comment by Stormbow** [comment]
Ok, give me a couple minutes to download an extremely outdated client so I can get on the server.  (LOL)

**Comment by Stormbow** [comment]
Ok.  Show me the server.properties file.

**Comment by Stormbow** [comment]
Server is running in offline mode.  This mode is not supported by PEX.

Only Bungeecord servers can use `online-mode=false` in the server.properties file.

**Comment by PirataGu** [comment]
![sem titulo](https://user-images.githubusercontent.com/30275479/28990615-9bf6268a-796e-11e7-9413-140d9ba64146.png)

**Comment by PirataGu** [comment]
Mode Online : Off

**Comment by PirataGu** [comment]
Modo = mode

**Comment by PirataGu** [comment]
From what I realized I'll have to put in active online mode

**Comment by Stormbow** [comment]
That's what I told you.  :-)

**Comment by PirataGu** [comment]
Ok! Tks

**Comment by Stormbow** [comment]
You're welcome. :) Have fun!

**Comment by PirataGu** [comment]
I was Trollado after all here is the Original Mode or Pirate -.- ''

**Comment by Stormbow** [comment]
Sorry.  I don't understand that sentence.

**Comment by PirataGu** [comment]
But what are you trying to say is this way ???? (Only enter original accounts and Mode to only enter pirate and original accounts ??)

**Comment by Stormbow** [comment]
Correct.  Pirate/hack/illegal servers are not supported by PEX.

**Comment by Stormbow** [comment]
Pirate/hack/illegal Minecraft accounts require `onine-mode=false` to join the server.  PEX does not support those.

**Comment by PirataGu** [comment]
;_;

**Comment by Stormbow** [comment]
Buy Minecraft.  No problem.  ;-)

**Comment by PirataGu** [comment]
That's not the problem. I have Original Minecraft. The problem is that I do not think I get fame with my server just for originals.

**Comment by Stormbow** [comment]
You never know until you try.

Screw the pirates.  Make them buy Minecraft too!  ;-)

**Comment by PirataGu** [comment]
There is no other way ??

**Comment by Stormbow** [comment]
Make a Bungeecord server.  I don't know anything about those though, so you'll have to do all the reading for it.
