### ISSUE TITLE
Players can’t get blocks from creative inventory 

### ISSUE THREAD

**Issue by TexorYT** [PEXPlugins/PermissionsEx#2914]
Hi. The title says it all. Don’t even reply stormbow, you didn’t help me at all

**Comment by Stormbow** [comment]
This is not a PermissionsEx issue.  This is a "server is packed with errors and server owner doesn't want to learn how to fix anything" issue.

**Comment by Stormbow** [comment]
If you continue posting tickets here, you will be reported for spamming and trolling.
