### ISSUE TITLE
How to set basic minecraft permissions like `/locate`?

### ISSUE THREAD

**Issue by fnc12** [PEXPlugins/PermissionsEx#2916]
I couldn't find info about this anywhere. How?

**Comment by Stormbow** [comment]
`/locate` is not part of the [Vanilla Permissions List](https://bukkit.gamepedia.com/CraftBukkit_Commands).

Google had this to say about the command:

https://minecraft.gamepedia.com/Commands#locate

https://www.digminecraft.com/game_commands/locate_command.php

**Comment by fnc12** [comment]
Do you mean that there is no way to set an internal minecraft permission to a group inside your plugin config?

**Comment by fnc12** [comment]
`minecraft.command.locate` I found it. One dude in Sponge chat told me.

**Comment by Stormbow** [comment]
> Do you mean that there is no way to set an internal minecraft command's permission to a group inside your plugin config?

Nope.  Just didn't look like Mojang included a node for it since it wasn't in the official wiki.

> minecraft.command.locate I found it. One dude in Sponge chat told me.

Groovy.  :-)  Thanks for the update.
