### ISSUE TITLE
PEX Prefixes wont show

### ISSUE THREAD

**Issue by JoeyGamesX** [PEXPlugins/PermissionsEx#2918]
Any help?

**Comment by Stormbow** [comment]
Prefixes are actually displayed in-game by a chat management plugin.  Since almost everyone uses EssentialsX these days, EssentialsXChat is their chat management plugin.

Which chat management plugin are you using?

**Comment by Stormbow** [comment]
Is this issue resolved, @JoeyGamesX ?

**Comment by Stormbow** [comment]
No reply from @JoeyGamesX in 7 days.  I guess this issue is resolved.
