### ISSUE TITLE
Wazne

### ISSUE THREAD

**Issue by Valkarm** [PEXPlugins/PermissionsEx#2920]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/733c4695a89bae1454b8d06f740fdd94)

**Comment by Stormbow** [comment]
Copy your entire server log to Pastebin for me to see.

**Comment by Stormbow** [comment]
No reply from @Valkarm in almost 7 days.  I guess this issue is resolved.
