### ISSUE TITLE
/pex user shows a different UUID than mcuuid.net

### ISSUE THREAD

**Issue by Metisuneatn** [PEXPlugins/PermissionsEx#2921]
![pexuser](https://user-images.githubusercontent.com/18323712/29125050-ae014486-7ce8-11e7-8f4e-ca87c5d0a6b1.png)

I'm getting this issue where when I do /pex user (name) it pulls up things like this when the player has a different rank and extra perms. This has happened a few times now.

Version 1.12 - going to 1.12.1 soon

**Comment by Stormbow** [comment]
The [mcuuid.net](http://mcuuid.net) website is showing the correct information for my name.

Is "KnowledgeIzPower" your legally purchased Minecraft client username?

**Comment by Metisuneatn** [comment]
That's one of my players. Yes it's his legal purchased name. This has happened for 6 players now. All with legit minecraft accounts

**Comment by Stormbow** [comment]
Ok, let's start at the top.

What version of Minecraft is this happening in?

Which version of PermissionsEx are you using?

What server wrapper are you using?  (Spigot, the Mojang client, PaperSpigot, Craftbukkit, something else?)

Copy your entire permissions.yml file to [Pastebin](http://pastebin.com) for me.

Copy your server log to [Pastebin](http://pastebin.com) for me.  (A 2nd link, not included in the above paste.)

Copy your server.properties file to [Pastebin](http://pastebin.com) for me.  (A 3rd link.)

**Comment by Stormbow** [comment]
Have you resolved this issue, @Metisuneatn ?

**Comment by Metisuneatn** [comment]
Not yet. Out of town on a business trip and won't be able to post files till next week

**Comment by zml2008** [comment]
If your server is in offline mode, even if you are signing in with a real account all your UUIDs will be offline mode UUIDs -- that could be your problem here.

**Comment by Metisuneatn** [comment]
Server is not, nor has ever been, in offline mode.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
