### ISSUE TITLE
Cant connect to local SQL database

### ISSUE THREAD

**Issue by krustymk** [PEXPlugins/PermissionsEx#2922]
Here is the error
https://pastebin.com/m9JcGxRn

Here is the configuration

https://pastebin.com/q8hk1uNW

in place of 'uri: mysql://localhost/PEX'
I have tried
uri: mysql://localhost:3306/PEX
uri: jdbc:mysql://localhost/PEX
uri: jdbc:mysql://localhost:3306/PEX

Database server info

Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.0.31-MariaDB-0ubuntu0.16.04.2 - Ubuntu 16.04
Protocol version: 10
User: myusername@localhost
Server charset: UTF-8 Unicode (utf8)
The PEX database does exist and is up and running
Several other plugins connect to the MySQL server ok with the same credentials.. spent hours trying different things

I

**Comment by Stormbow** [comment]
Sorry; you'll need @zml2008 to answer this one since he has much more experience with SQL and knowledge of SQL.

**Comment by krustymk** [comment]
Tried something different
Downloaded PermissionsEx-1.23.4 again
stopped the server
opened the config file
changed backend from file to sql
restarted the server
stopped the server
opened the config file
updated the newly generated sql database lines to reflect my user/pass
deleted the line with 'permissions.yml' on it (i forget how it started...file: maybe)
restarted the server
connected fine

maybe there is a corrupt/faulty jar floating around out there?

**Comment by krustymk** [comment]
Do not 'pex reload'!!! restart the server
[config.txt](https://github.com/PEXPlugins/PermissionsEx/files/1219625/config.txt)
change extension txt to yml (cant upload yml)
your database user/pass
RESTART the server
pex backend sql
pex import file

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
