### ISSUE TITLE
Does Modifyworld work with 1.12.1

### ISSUE THREAD

**Issue by Dunkledore** [PEXPlugins/PermissionsEx#2931]
I load the jar into my plugins folder and the modifyworld folder is not made?
permissions.yml - https://pastebin.com/NacYWv8J
config.yml - https://pastebin.com/feYi6mXN

**Comment by Stormbow** [comment]
> I load the jar into my plugins folder

Which .jar?  [Modifyworld](https://dev.bukkit.org/projects/modifyworld) is a separate download from PermissionsEx.

**Comment by Dunkledore** [comment]
Hi the one here: https://dev.bukkit.org/projects/modifyworld

**Comment by zml2008** [comment]
That one hasn't been updated for 1.12.x yet.
