### ISSUE TITLE
Problem with certain commands

### ISSUE THREAD

**Issue by SebastienWD** [PEXPlugins/PermissionsEx#2932]
I am trying to give the group member access to the command /craft, /echest and /pv 1,2 and 3. But I can't figure out how to do it. Anyone knows how?

**Comment by Stormbow** [comment]
Do you have a plugin installed on the server which would give users access to those commands?

If yes, the command to give a group access to those commands would be:
```
/pex group <group> add <permission> [world]
     - Adds <permission> to <group> in [world]

/pex user <user> add <permission> [world]
     - Adds <permission> to <user> in [world]
```

You can see all of the PEX 1.23.4 Commands [right here](https://pastebin.com/Kd269wd7).

**Comment by Stormbow** [comment]
No reply from @SebastienWD in more than 7 days.  I guess this problem's solved.
