### ISSUE TITLE
Command '/pex user <name> group add <group>' sometimes replaces primary group

### ISSUE THREAD

**Issue by TerracePalmMC** [PEXPlugins/PermissionsEx#2934]
I've been running into this annoying issue where inputting this command replaces the primary group of my players.

**Comment by zml2008** [comment]
We accept PRs if you'd like to fix it or can convince someone else to fix it

**Comment by TerracePalmMC** [comment]
Well, I was hoping you'd be able to fix it. Have you been able to reproduce this issue?
I can send you my permissions setup if you need, could it have something to do with the group weights?
It's specially annoying since I use Enjin's Minecraft Plugin, for donor ranks, and PEX keeps replacing the primary group with the donor group. What's odd, is that if I then manually run this command with the primary group, it doesn't replace the donor group.

**Comment by zml2008** [comment]
I don't have the time to fix things in PEX anymore, so if you want it fixed someone else is going to have to do it.

**Comment by MisterFixx** [comment]
check in PEX config that user-add-groups-last is set to true, that way when you do pex user <user> group add <group> it will add the group to the bottom of the player's group list, and his primary group stays

**Comment by TerracePalmMC** [comment]
@MisterFixx I ended up switching over to LuckyPerms, but this may very well be the issue. Thanks for your input.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
