### ISSUE TITLE
PemissionsEX stop at the second server start

### ISSUE THREAD

**Issue by JoanPallasYT** [PEXPlugins/PermissionsEx#2943]
I put the PEX in the plugins folder and then I start the server, all ok. When I shutdown the server and then I open this, the PEX don't work. I have installed the v1.23.3 in Spigot 1.8 with 31 more plugins (WorldEdit, ColoredSigns, VoidWorld, PlaceholderAPI, PerWorldPlugins, PlugMan, BlockedCommands, Heads, ProtocolLib, Multiverse-Core, VoidSpawn, WorldGuard, LibsDisguises, RogueParkour, eZProtector, DoubleJumpPlus, Murder, PerWorldTab, NoWeather, Tab, Vault, Essentials, CorpseReborn, ArmorStandTools, GadgetsMenu, Citizens, Shopkeepers, BuyNodes, EssentialsChat, PlayMoreSounds, EssentialsSpawn)

**Comment by zml2008** [comment]
i don't work either
