### ISSUE TITLE
Permanent [Member] Prefix wit Pex

### ISSUE THREAD

**Issue by UglyGawd** [PEXPlugins/PermissionsEx#2948]
Hi, I’ve recently made a Minecraft server and have been having trouble with PermissionsEx. When I make groups such as “Owner” and make a prefix for it, I say hi in the chat but it says [Owner][Member] then my username. If anyone could help me with this problem it would be greatly appreciated. Thank you

**Comment by zml2008** [comment]
That'd be a chat plugin issue, not something PEX would be involved with.
