### ISSUE TITLE
How can i add / arrange multiple prefixes and suffixes

### ISSUE THREAD

**Issue by Wontedyew15** [PEXPlugins/PermissionsEx#2949]
(i'm sorry if this is in the wrong place)
So basically i'm wondering if there is a way to add multiple group prefixes to one persons name. 
for example
---------------------------------------------
Kingwonton
Groups:
- Mod - Prefix = "[Mod]"
- Survivor - Prefix = "[Survivor]"
---------------------------------------------
How would i make it so there name is displayed like this:
[Group 1][Group 2]{playername}:
so it would look like this:
[Mod][Survivor]Kingwonton:

if you can help me thank you! and if i placed this in the wrong place i am sorry 👍

**Comment by zml2008** [comment]
This would be something your chat plugin would need to do -- talk to them.
