### ISSUE TITLE
Can't sort my permissions file

### ISSUE THREAD

**Issue by BlazeBoss3412** [PEXPlugins/PermissionsEx#2952]
What I want to do is be able to have 

#-------------------
#staff
#-------------------

and other sorters like that between my roles so it is easier to understand. But when I add a comment it deletes the comment after a few reloads. The plugin works fine while they are in but for some reason it keeps removing them.

**Comment by zml2008** [comment]
The configuration library we use doesn't preserve comments, so any time PEX saves the configuration file any comments will be deleted. Feel free to make changes to SnakeYaml if you'd like this to work differently.
