### ISSUE TITLE
Bungeecord Permissions Over lapping PermissionsEx permissions

### ISSUE THREAD

**Issue by 420Black** [PEXPlugins/PermissionsEx#2956]
Hey,

I just got a bungeecord server and my PermissionsEx Permissions Are not working... They said that bungeecord permissions Are Over Lapping my PermissionsEx permissions, I don't know how to fix this though... I used to be a co-owner on a server hosted by the same host site, with PermissionsEx and they didn't have this problem....

**Comment by zml2008** [comment]
No clue what they mean either -- Bungee and PEX have two separate permissions systems and PEX does nothing on its own to interface with Bungee. Good luck!
