### ISSUE TITLE
Integrating with PEX Javadoc link isn't work

### ISSUE THREAD

**Issue by YouTiao233** [PEXPlugins/PermissionsEx#2958]
Integrating with PEX Javadoc link isn't work

**Comment by zml2008** [comment]
I don't think we publish javadocs, and that almost certainly won't change. Feel free to host the javadocs yourself.

**Comment by YouTiao233** [comment]
![image](https://user-images.githubusercontent.com/21272351/30623691-bb451094-9d7e-11e7-863c-c49e812ac3ca.png)
I talk is about this one , I want write plugin is Integrate with PEX 
![image](https://user-images.githubusercontent.com/21272351/30623770-61005ad4-9d7f-11e7-954d-6581aee9d531.png)

**Comment by YouTiao233** [comment]
and i dont't know how to use it
![image](https://user-images.githubusercontent.com/21272351/30623911-193dcd8e-9d80-11e7-9683-b33c36859b5a.png)

**Comment by zml2008** [comment]
step one, learn java. step two, use Vault instead, step 3 find help from someone who still actually does things.
