### ISSUE TITLE
1.12.2 compatibility and errors

### ISSUE THREAD

**Issue by JavituRec** [PEXPlugins/PermissionsEx#2960]
Last version of bukkit "PermissionsEx v1.23.4" causes problems with other plugins and does not let users enter, expelling them after the attempt to enter and the latest version [https://ci.yawk.at/view/PermissionsEx/job/PermissionsEx](url) gives this error in console.
[https://hastebin.com/pokudimano.vbs](url)

Server version 1.12.2

All the best.

**Comment by Ironic8b498** [comment]
I have been running PermissionsEx v1.23.4 for a few years and I upgraded to the latest bukkit version as they were released, I'm currently running 1.12.2 and don't have any issues with PEX. Maybe its the other plugin or PEX not being setup right.
