### ISSUE TITLE
Everyone On My Server Is Op

### ISSUE THREAD

**Issue by SweggyDucks** [PEXPlugins/PermissionsEx#2979]
So today I opened my server to the public, and when players joined they were all OP and I don't know what to do. I have gone through the permissions of my lowest tier rank and have found no errors. Any suggestions? 
Here Are My Files: https://pastebin.com/wd5r2wCT

**Comment by zml2008** [comment]
You set the group Admin as a default group -- to undo this, run `/pex default user parent rem group Admin`.
