### ISSUE TITLE
Crash any server

### ISSUE THREAD

**Issue by MisterQuatsch** [PEXPlugins/PermissionsEx#2987]
If a player uses the '/pex promote a a' command he can crash the server.

**Comment by MisterQuatsch** [comment]
If you want I can post example video later.

**Comment by KennethWussmann** [comment]
Already reported in #2923

**Comment by Sandukhan** [comment]
Beside the mental breakdown in that topic.. is there any official fix for that issue yet?

Because i can also confirm this problem. Using permissionsEx 1.34.4 on Spigot 1.12.2

**Comment by MisterQuatsch** [comment]
> Already reported in #2923
Oh I thougt if something like this gets reportet it would get fixed immediately

> Beside the mental breakdown in that topic.. is there any official fix for that issue yet?
>
> Because i can also confirm this problem. Using permissionsEx 1.34.4 on Spigot 1.12.2
Block the Pex Command for everyone who should not use it. For Example with eZBlock or WordGuard.

**Comment by Sandukhan** [comment]
Ya i already block it, but there is no reason why any nomal player without op should be able to use these commands in the first place.

https://pastebin.com/PeiYWmnK

**Comment by MAH1987** [comment]
@Sandukhan  How you Fix this Issue?

**Comment by Sandukhan** [comment]
@MAH1987 
Block all pex related commands with WordGuard or override these via command alias, like with Betteralias.

**Comment by MAH1987** [comment]
Thanks a lot!
We will switch to LuckPerms for the future but your answer help us to protect our current server

**Comment by winofi** [comment]
Workaround by disabling name autocomplete: https://github.com/PEXPlugins/PermissionsEx/pull/2995/files

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
