### ISSUE TITLE
Nothing but "default"

### ISSUE THREAD

**Issue by Cookie12345678** [PEXPlugins/PermissionsEx#3001]
Basically, I can add permissions for every single player and I can create groups, but I can't add people to them. Everyone is default even when the config says otherwise. Prefixes don't work either. I use EssentialsChat and PEX, and have literally tried everything and I'm this close to pulling my hair out so if you can help me, thanks in advance!

**Comment by GoNotCougsWA** [comment]
Essentials chat does work that well. Try using zchat.

**Comment by Cookie12345678** [comment]
THANK YOU SO MUCH
