### ISSUE TITLE
Cannot execute command 'pex' in plugin PermissionsEx v1.23.4 - plugin is disabled.

### ISSUE THREAD

**Issue by jokzyz** [PEXPlugins/PermissionsEx#3022]
I made some changes/fixes to my pex permissions.yml and i restarted the server. When i loaded back in pex had been disabled and i received the following error in my console:

[INFO] ttvjokzyz issued server command: /pex

[ERROR] null

org.bukkit.command.CommandException: Cannot execute command 'pex' in plugin PermissionsEx v1.23.4 - plugin is disabled.

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]

at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

The following is my pex file:
groups:
  default:
    options:
      default: true
      rank: '500'
      rank-ladder: players
      prefix: '&f[&7Default&f] &7'
    permissions:
    - -chatcolor.use-color-codes
    - -bukkit.command.plugins
    - -bukkit.command.reload
    - cratesplus.crate.randcrate
    - cratesplus.crate.kills
    - cratesplus.randcrate
    - cratesplus.crate.vote
    - worldedit.limit.unrestricted
    - chestcommands.open.specialkits.yml
    - chestcommands.open.basickits.yml
    - chestcommands.open.kits.yml
    - essentials.kits.pvp2
    - essentials.warp.list
    - essentials.warp
    - essentials.spawn
    - essentials.mute.notify
    - essentials.kick.notify
    - essentials.rules
    - essentials.msg
    - essentials.motd
    - essentials.mail.send
    - essentials.mail
    - essentials.list
    - essentials.help
    - essentials.helpop
    - essentials.afk.kickexempt
    - essentials.afk.auto
    - essentials.kits.op
    - essentials.kit
    - essentials.kits.pvp
    - essentials.kits.daily
    - essentials.kits
    - chatex.allowchat
    - essentials.kit.op
    - modifyworld.*
  VIP:
    inheritance:
    - default
    options:
      rank: '300'
      rank-ladder: players
      prefix: '&f[&2VIP&f] &2'
    permissions:
    - essentials.kits.vip
    - essentials.enderchest
    - essentials.clearinventory
    - essentials.whois
    - essentials.realname
    - essentials.ptime
    - essentials.feed
  MVP:
    inheritance:
    - VIP
    options:
      rank: '200'
      rank-ladder: players
      prefix: '&f[&3MVP&f] &3'
    permissions:
    - essentials.kits.mvp
    - essentials.tpdeny
    - essentials.tpahere
    - essentials.tpaccept
    - essentials.tpa
    - essentials.seen
    - essentials.nick
    - essentials.near
    - essentials.repair
    - essentials.heal
    - essentials.hat
  Rich:
    inheritance:
    - MVP
    options:
      rank: '100'
      rank-ladder: players
      prefix: '&f[&6Rich&f] &6'
    permissions:
    - essentials.kits.rich
    - essentials.chat.format
    - essentials.chat.colors
    - essentials.tptoggle
    - essentials.back.ondeath
    - essentials.invsee
    - essentials.ext
    - essentials.suicide
    - essentials.nick.format
    - essentials.nick.color
    - essentials.near.maxexempt
    - essentials.msg.format
    - essentials.msg.color
    - essentials.repair.enchanted
    - essentials.repair.all
    - essentials.fly
  Helper:
    inheritance:
    - default
    options:
      rank: '60'
      rank-ladder: staff
      prefix: '&f[&e&lHelper&f] &e'
      permissions:
    - chatcolor.use
    - essentials.chat.url
    - essentials.mute.offline
    - essentials.mute
    - essentials.seen.banreason
    - essentials.hidden
    - essentials.chat.ignoreexempt
  Mod:
    inheritance:
    - Helper
    options:
      rank: '50'
      rank-ladder: staff
      prefix: '&f[&9&lMod&f] &9'
    permissions:
    - essentials.ban
    - essentials.tempban.offline
    - essentials.tempban
    - essentials.ban.notify
    - essentials.fly.safelogin
    - essentials.fly
  SrMod:
    inheritance:
    - Mod
    options:
      rank: '40'
      rank-ladder: staff
      prefix: '&f[&dSrMod&f] &d'
    permissions:
    - essentials.vanish
    - essentials.warps*
    - essentials.warps^
    - essentials.tptoggle
    - essentials.tp.others
    - essentials.tp
    - essentials.unbanip
    - essentials.unban
    - essentials.sudo.exempt
    - essentials.socialspy
    - essentials.enderchest.others
    - essentials.banip
    - essentials.ban.offline
    - essentials.near.others
    - essentials.msg.url
    - essentials.msg.format
    - essentials.msg.color
    - essentials.itemdb
  Admin:
    inheritance:
    - SrMod
    options:
      rank: '30'
      rank-ladder: staff
      prefix: '&f[&cAdmin&f] &c'
    permissions:
    - bukkit.command.reload
    - bukkit.command.plugins
    - chatcolor.change*
    - chatcolor.custom
    - chatcolor.admin
    - essentials.signs*
    - essentials.signs.create.kit
    - essentials.signs.break.kit
    - essentials.signs.break.repair
    - essentials.signs.create.repair
    - essentials.vanish.interact
    - essentials.warp*
    - essentials.setwarp
    - essentials.weather
    - essentials.vanish.see
    - essentials.vanish
    - essentials.lightning.others
    - essentials.invsee.modify
    - essentials.gc
    - essentials.essentials
    - essentials.enderchest.modify
    - essentials.broadcast
    - essentials.msg.multiple
    - essentials.msg.magic
    - essentials.mail.sendall
    - essentials.helpop.recieve
    - essentials.kit.exemptdelay
    - essentials.heal.others
    - essentials.gamemode
    - essentials.fly.others
    - essentials.feed.others
    - essentials.feed.cooldown.bypass
    - essentials.feed
    worlds:
      developer:
        permissions:
        - essentials.vanish.pvp
  Developer:
    inheritance:
    - Admin
    options:
      rank: '10'
      rank-ladder: staff
      prefix: '&f[&4Dev&f] &4'
    permissions:
    - essentials.spawn.others
    - essentials.setspawn
    - essentials.vanish.pvp
    - essentials.sudo
    - essentials.kick
    - essentials.clearinventory.others
    - essentials.backup
    - essentials.seen.ipsearch
    - essentials.powertool.append
    - essentials.powertool
    - essentials.nick.others
    - essentials.afk.others
    - essentials.speed*
    - essentials.skull*
    - essentials.ptime*
    - essentials.kit*
    - essentials.itemspawn*
    - essentials.item*
    - essentials.god
    - essentials.give
    - essentials.gamemode.others
  owner:
    permissions:
    - essentials.*
    options:
      prefix: '&f[&4Owner&f] &4'
      rank: '1'
      rank-ladder: staff
    inheritance:
    - Developer
  PvPGod:
    options:
      prefix: '&f[PvP&cGod&f]'
      rank: '900'
      rank-ladder: titles
schema-version: 1
users:
  e62540e0-6952-4e4c-ae17-b6a34077cd8c:
    group:
    - PvPGod
    - Rich
    - Owner
    options:
      name: ttvjokzyz
      last-login-time: '1565660671'
      last-logout-time: '1565591855'
    permissions:
    - essentials.kits.hulk
    - essentials.kits.speeddemon
    - essentials.kits.pyro
  37e20c7f-9204-4c60-b4ad-7826017d26c3:
    group:
    - VIP
    - Mod
    options:
      name: Xxyo
      last-login-time: '1565572194'
      last-logout-time: '1565572258'
  d38b9c3e-1180-4382-b80e-a2c6d3081f16:
    group:
    - default
    options:
      name: Paiinful
      last-login-time: '1565653865'
      last-logout-time: '1565654900'
    permissions:
    - essentials.kits.hulk
    - essentials.kits.pyro
    - essentials.kits.speeddemon
  ca91e0a3-e766-45ee-8878-549996ce4f1f:
    group:
    - PvPGod
    - VIP
    - Admin
    options:
      name: Sacramentoes
      last-login-time: '1565660162'
      last-logout-time: '1565545612'
    permissions:
    - essentials.kits.hulk
    - essentials.kits.pyro
  a7b2a0dd-2601-422d-9636-3699587e3fa8:
    group:
    - default
    options:
      name: Rudidew
      last-login-time: '1565546648'
      last-logout-time: '1565546625'
  f1b786cb-d035-491c-b54e-29ac49a66fc2:
    group:
    - VIP
    options:
      name: ScribblezB94
      last-login-time: '1565408715'
      last-logout-time: '1565412546'
  fcdc1fb8-27c5-4de9-b0ee-98b9e6970af1:
    group: []
    options:
      name: GiantMidget666
      last-login-time: '1565479852'
      last-logout-time: '1565480188'
  2a591ee1-0a80-41e2-9903-fe512f73f0a6:
    group:
    - Helper
    options:
      name: StinkyFrog
      last-login-time: '1565559329'
      last-logout-time: '1565559628'
    permissions:
    - essentials.kits.speeddemon
  22a511a3-007b-4e00-a672-347aedb278d8:
    group:
    - MVP
    - Rich
    - VIP
    - PvPGod
    - Admin
    options:
      name: _DaddyP_
      last-login-time: '1565616659'
      last-logout-time: '1565617535'
    permissions:
    - essentials.kits.hulk
    - essentials.kits.pyro
    - essentials.kits.speeddemon

I'm not entirely sure how to find where the error is located so could somebody please help?

**Comment by zml2008** [comment]
pex 1.x is no longer supported
