### ISSUE TITLE
Pex Error

### ISSUE THREAD

**Issue by jokzyz** [PEXPlugins/PermissionsEx#3023]
I made some changes/fixes to my pex permissions.yml and i restarted the server. When i loaded back in pex had been disabled and i received the following error in my console:

[https://pastebin.com/grV6dg9G](url)

[https://pastebin.com/muGYmtJV](url)

I'm not entirely sure how to find where the error is located so could somebody please help? All i need is for you to point me to the location of the error

**Comment by zml2008** [comment]
why do you think creating a new issue is going to change anything, if you want to continue using pex 1.x you're on your own.
