### ISSUE TITLE
New server owner in need of help

### ISSUE THREAD

**Issue by Discordeus** [PEXPlugins/PermissionsEx#3025]
I recently got my first server and got this and a few other plugins. It has me registered as a guest on the server, but I'm the owner. How do I change this to allow myself to other commands?

**Comment by TheBlankSky** [comment]
Use LuckPerms :)

**Comment by zml2008** [comment]
luckperms won't cure an unwillingness to read the manual but sure

**Comment by DevinFries** [comment]
Aww no need to be upset, just use luckperms and not a serveraly out-of-date plugin thats barely functional. Sorry if that offended you ;)

**Comment by ghost** [comment]
Aww there's no need for you to be so upset, how do you not know that PermissionsEx is extremely out of date and useless?
