### ISSUE TITLE
Not enough permissions

### ISSUE THREAD

**Issue by Koffki** [PEXPlugins/PermissionsEx#3027]
Hi, I am using permissionsex - 1.23.4 and I am unable to make my self the owner (and I am the owner of the server), I have tried both in console and in game to create an owner group (with nothing in the permissions.yml file), I also tried setting up the groups in the permissions.yml file and still could not get it to work when I had that 'set up'.

I don't know if this would affect the way it works but I am running the server on server pro. I also have other plugin installed I don't know if any of them would affect permissionsex.

**Comment by zml2008** [comment]
The 1.x series is no longer supported, you may have some luck reading the wiki though.
