### ISSUE TITLE
2 prefixes or 2 default groups....

### ISSUE THREAD

**Issue by xXMrMoose** [PEXPlugins/PermissionsEx#3031]
So! I am making a server with a friend and trying to set up multiple worlds. One of the worlds being Hockey related so the default group is "FA" (Free Agent) and then a survival world default group is "Settler" I have no idea how to make it so if you join the other world it changes your Prefix. 
I'd show you what I've got but I don't think it would be any benefit because it's no progress towards the thing I wish to achieve.

**Comment by zml2008** [comment]
You can set default groups per-world, or have one default group with world-specific prefixes and permissions. All the instructions how should be explained in the wiki.
