### ISSUE TITLE
Timed permissions go when player relogs

### ISSUE THREAD

**Issue by JHarris12345** [PEXPlugins/PermissionsEx#3038]
You can add permissions to people for a certain time using:

pex user <user> timed add <permission> <lifetime in seconds>

However, if they relog or server restarts, they lose the permissions. Can you fix this please

**Comment by zml2008** [comment]
This is how timed permissions work in pex 1.x, which is no longer supported. Timed permissions in PEX 2 will have the option to be saved or transient, just like regular permissions.

**Comment by JHarris12345** [comment]
So how do I create the option to be saved?
