### ISSUE TITLE
An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by frankzzyy** [PEXPlugins/PermissionsEx#3039]
I installed the plugin of my server and if  i type anything from pex like : /pex   ; /pex groups
Their always coming the error, and if i type  pex user [name] add * nothing happens

if i  open the config their is nothing its clear... 

Please help

**Comment by zml2008** [comment]
we don't support pex 1.x






---- On Wed, 18 Sep 2019 22:27:47 -0700 notifications@github.com wrote ----



I installed the plugin of my server and if i type anything from pex like : /pex ; /pex groups
Their always coming the error, and if i type pex user [name] add * nothing happens

if i open the config their is nothing its clear...

Please help
