### ISSUE TITLE
People losing temp commands after relogin

### ISSUE THREAD

**Issue by mathiaslk** [PEXPlugins/PermissionsEx#3040]
So, I have an issue, I want to add permissions to people temporarily, like 30 days or something, but when I use " pex user Producting timed add essentials.kits.dealer 86400" they get the kit at first, but if the user relogs, they lose access to it again.

**Comment by zml2008** [comment]
pex 1.x is no longer supported, pex 2.x will allow timed permissions to be given persistently though.
