### ISSUE TITLE
PermissionsEX not working and if i write /pl pex is red

### ISSUE THREAD

**Issue by VladislavKorecky** [PEXPlugins/PermissionsEx#3041]
My permissions not working and if i write /pl pex is red.
Please help!
![problem](https://user-images.githubusercontent.com/55646812/65382796-93c4b900-dd0c-11e9-8423-e71cf4e70cd3.png)
Code:
_groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
    - chatex.allowchat
  helper:
    inheritance:
    - default
    options:
      default: false
      prefix: &l&2[Helper]&f&r
    permissions:
    - commandbook.fly
    - commandbook.kick
    - commandbook.tp
    - commandbook.teleport
    - commandbook.gamemode
  builder:
    inheritance:
    - default
    options:
      default: false
      prefix: &l&2[Builder]&f&r
    permissions:
    - commandbook.fly
    - commandbook.tp
    - commandbook.teleport
    - commandbook.gamemode
    - worldedit.*
  admin:
    inheritance:
    - helper
    options:
      default: false
      prefix: &l&4[Helper]&f&r
    permissions:
    - commandbook.ban
    - commandbook.ipban
    - commandbook.pardon
    - commandbook.whitelist
    - worldedit.*
  owner:
    options:
      default: false
      prefix: &l&1[Owner]&f&r
    permissions:
    - *
schema-version: 1_

**Comment by zml2008** [comment]
pex 1 is no longer supported.
