### ISSUE TITLE
Préfixe

### ISSUE THREAD

**Issue by Raraph84** [PEXPlugins/PermissionsEx#3044]
J'ai ajouté un préfixe à un groupe mais il ne marche pas :
plugins : 
Multiverse-Core-2.5.0, PermissionsEx-1.23.4, worldedit-bukkit-6.1.9, worldguard-bukkit-6.2.2

Fichier Config : 

multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: false
alwaysUpdate: false

Fichier Permission : 

groups:
  default:
    options:
      default: true
      rank: '1000'
  Createur:
    permissions:
    - '*'
    - permissions.*
    options:
      rank: '1'
      suffix: ' &4Le dieu&R'
  Admin:
    permissions:
    - '*'
    - permissions.*
    options:
      rank: '2'
  Developpeur:
    options:
      rank: '3'
    permissions:
    - '*'
  Builder:
    options:
      rank: '4'
  Modo:
    options:
      rank: '5'
  VIP:
    options:
      rank: '100'
schema-version: 1
users:
  0b7d2c7e-39a3-40ec-96d0-84c9f56337ab:
    group:
    - Createur
    permissions:
    - permissions.*
    options:
      name: raraph84

**Comment by zml2008** [comment]
1. PEX v1 isn't supported
2. You need a chat plugin... but point 1 showed you can't read so good luck with that part
