### ISSUE TITLE
i need to know what this value mean in PEX's database

### ISSUE THREAD

**Issue by R98rayan** [PEXPlugins/PermissionsEx#3045]
Hello..
i need to know how to analyze this value in database!
![download](https://user-images.githubusercontent.com/43526297/66056495-df166d00-e53f-11e9-8484-df158389cb50.png)

like how match time it need to expire?

Thank you.

**Comment by zml2008** [comment]
it's seconds since the epoch. timed permissions were a bit funky on 1.23 so good luck?
