### ISSUE TITLE
Add syntax for adding permission nodes without subnodes

### ISSUE THREAD

**Issue by disba1ancer** [PEXPlugins/PermissionsEx#3046]
If permission node "a" have subnodes (e.g.: "a.b", "a.c.d"), it is impossible enable only permission node "a" without subnodes. Currently subnodes may be disabled only in explicit way, that requires specifing all subnodes. If some plugin add support for additionally permissions, this permissions will be not disabled for some users.

**Comment by zml2008** [comment]
That's correct. This is an intentional design choice, which plugins should design their permissions around.

**Comment by disba1ancer** [comment]
Some plugins not support this design by historically reasons, and selecting other permissions plugins is simpler way for them
