### ISSUE TITLE
How to begin?

### ISSUE THREAD

**Issue by Itap88** [PEXPlugins/PermissionsEx#3047]
I had just installed this plugin and I tried to learn how it works on my server. It said I have no permission even if I'm an operator. So I went to learn on the wiki. But I don't understand this level of informatics. I just wanted to create a simple server.

**Comment by Haveyougonemad** [comment]
You need to programme it by edititng plugins/permissionsex/permissions.yml 
You can send me your document. We can open a server

- [ Solved]

**Comment by Itap88** [comment]
That's how the file looks:

groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
schema-version: 1

I really wouldn't mind just one example group with all permissions set.

**Comment by zml2008** [comment]
take a look at the wiki it has all the support you'll get on 1.23

**Comment by zml2008** [comment]
no response, assuming things worked out.
