### ISSUE TITLE
is pex enabled? (is that an error?)

### ISSUE THREAD

**Issue by olilord123** [PEXPlugins/PermissionsEx#3048]
when i add ranks to the pex permissions.yml file and open up the game to log in the game says an internal error occured but when i remove the rank string it works... is this a common issue or do i need to do something? please help

**Comment by zml2008** [comment]
PEX2 has no permissions.yml and PEX1 is not supported, which one are you trying to talk about?

**Comment by olilord123** [comment]
> PEX2 has no permissions.yml and PEX1 is not supported, which one are you trying to talk about?

i belive 1

**Comment by olilord123** [comment]
it has worked before

**Comment by zml2008** [comment]
good luck

**Comment by olilord123** [comment]
ok

**Comment by olilord123** [comment]
what is pex2???

**Comment by zml2008** [comment]
PEX2 is the upcoming major release of PEX that's a rewrite from the ground up to support bukkit/sponge/proxies/fabric as well as have more powerful permissions resolution.
