### ISSUE TITLE
Invalid permissions.yml Help pls

### ISSUE THREAD

**Issue by Haveyougonemad** [PEXPlugins/PermissionsEx#3050]
groups:
  Owner2:
    options:
      default: false
      prefix: '&8&l(&4&lOwner&8&l)&c '
    permissions:
    - '*'
  CoOwner:
    options:
      default: false
      prefix: '&8&l(&5&lCoOwner&8&l)&c '
    permissions:
    - '*'
  Peasant:
    options:
      default: false
      prefix: '&8(&aPeasant&8)&7 '
    permissions:  
    - essentials.tpahere
    - essentials.list
    - essentials.exp
    - essentials.balancetop
    - essentials.sell
    - essentials.sell.hand
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warps.*
    - silkspawners.place.*
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    - ctplus.logout
    - ctplus.check
    - essentials.home
    - essentials.clearinventory
    - essentials.balance
    - essentials.warp.list
    - essentials.warp
    - essentials.tpdeny
    - essentials.tpaaccept
    - essentials.tpa
    - essentials.delhome
    - essentials.sethome.multiple.3
    - essentials.sethome.multiple
    - essentials.sethome
    - essentials.spawn
    - essentials.suicide
    - essentials.seen
    - essentials.rules
    - essentials.msg
    - essentials.ignore
    - essentials.helpop
    - essentials.help
    - essentials.pay
    - essentials.kits.peasant
    - essentials.kit
    - essentials.build
  Duke:
    options:
      default: false
      parents: Peasant
      prefix: '&8(&5Duke&8)&7 '
    inheritance: 
     - Peasent   
    permissions:
    - silkspawners.silkdrop.*
    - essentials.sethome.multiple.5
    - silkspawners.silkdrop.*
    - silkspawners.place.*
    - essentials.feed
    - essentials.warps.*
    - essentials.kits.duke
    - essentials.kits.food
    - playervaults.amount.1
  Count:
    options:
     default: false
      parents: Peasant
      prefix: '&8(&4Count&8)&7 '
    inheritance:
    - Duke  
    permissions:
    - silkspawners.silkdrop.*
    - essentials.sethome.multiple.7
    - essentials.feed
    - essentials.warps.*
    - essentials.kits.count
    - playervaults.amount.2
  Captain:
    options:
      default: false
      prefix: '&8(&2&lCaptain&8)&a '
    inheritance:
    - Baron   
    permissions:
    - silkspawners.silkdrop.*
    - essentials.sethome.multiple.13
    - essentials.nick
    - essentials.afk
    - essentials.nick.color
    - essentials.nick.magic
    - essentials.nick.format
    - essentials.warps.*
    - essentials.repair.all
    - essentials.repair
    - essentials.sell.hand
    - playervaults.kits.captain
    - playervaults.amount.9
    - essentials.heal
    - essentials.feed
  Sir:
    options:
      default: false
      prefix: '&8(&3&lSir&8)&b&l '
    inheritance:
    - Captain
    permissions:
    - essentials.back
    - essentials.workbench
    - silkspawners.silkdrop.*
    - essentials.sethome.multiple.15
    - essentials.afk
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.magic
    - essentials.nick.format
    - essentials.warps.*
    - essentials.fly
    - essentials.feed
    - playervaults.amount.12
    - essentials.repair
    - essentials.repair.all
    - essentials.heal
    - essentials.kits.sir
    - essentials.near
    - essentials.sell.hand
  Helper2:
    options: 
      default: false
      prefix: '&8(&a&lHelper&8)&2 '    
    inheritance:
    - Peasant
    permissions:
    - essentials.afk
    - maxbans.warn
    - maxbans.unmute
    - maxbans.tempmute
    - maxbans.kick
    - silkspawners.silkdrop.*
  JrMod:
    inheritance:
    - Helper
    options:
      default: false
      prefix: '&8(&d&lJrMod&8)&9 '
    permissions:
    - silkspawners.silkdrop.*
    - maxbans.kick
    - maxbans.tempmute
    - maxbans.unwarn
    - maxbans.warn
    - maxbans.mute
    - maxbans.tempban
  SrMod:
    options:
      default: false
      prefix: '&8(&6&lSrMod&8)&9 ' 
    inheritance:   
    - JrMod
    permissions:
    - nocheatplus.notify
    - nocheatplus.command.notify
    - maxbans.notify.silent
    - maxbans.clearchat
    - maxbans.togglechat.bypass
    - maxbans.togglechat
    - maxbans.checkban
    - maxbans.history
    - maxbans.ipban
    - maxbans.banlist
    - maxbans.unban
    - maxbans.kick
    - maxbans.tempban
    - maxbans.unmute
    - maxbans.mute
    - maxbans.ban
    - silkspawners.silkdrop.*
    - essentials.fly
  Admin2:
    options:
      default: false
      prefix: '&8(&c&lAdmin&8) '
    inheritance:  
    - SrMod
    permissions:
    - silkspawners.silkdrop.*
    - essentials.gamemode
    - maxbans.warn
    - maxbans.tempmute
    - maxbans.kick
    - maxbans.ban
    - maxbans.mute
    - maxbans.unmute
    - maxbans.unban
    - maxbans.unbanip
    - maxbans.ipban
    - '*'
  Earl:
    options:
      default: false
      prefix: '&8(&6Earl&8)&7 '
    permissions:
    - silkspawners.silkdrop.*
    - essentials.sethome.multiple.9
    - playervaults.amount.5
    - essentials.warps.*
    - essentials.heal
    - essentials.feed
    - essentials.kits.earl
  Baron:
    options:
      default: false
      prefix: '&8(&bBaron&8)&7 '
    permissions:
    - silkspawners.silkdrop.*
    - essentials.sethome.multiple.11
    - essentials.warps.*
    - essentials.kits.baron
    - playervaults.amount.7
    - essentials.heal
    - essentials.feed
  bypassglobal:
    options:
      default: false
      prefix: '&7(&8User&7) &8 '
    permissions:
    - mutechat.bypass
    - staff.chat
  Owner:
    options:
      default: false
      prefix: '&8&l(&4&lOwner&8&l)&c '
    permissions:
    - nte.owner
    - modifyworld.*
    - '*'
  staffchat:
    options:
      default: false
      prefix: '&7(&8User&7) &8 '
    permissions:
    - staff.chat
    - staff.list
  worldedit:
    options:
      default: false
      prefix: '&7(&8User&7) &8 '
    permissions:
    - worldedit.*
  User:
    options:
      default: true
      prefix: '&7(&8User&7) &8 '
    permissions:
    - modifyworld.*
    - essentials.balance
    - essentials.pay
    - essentials.spawn
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.warp.list
    - essentials.warp
    - essentials.tpdeny
    - essentials.delhome
    - essentials.msg
    - essentials.kit
    - essentials.kits.Usuario
    - essentials.kits.pvp
    - essentials.ping
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.free
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.kit
    - essentials.balancetop
    - esencials.ignore
    - essentials.enderchest
  Vip:
    options:
      default: false
      prefix: '&6&l(&e&lVip&6&l) &8 '
    permissions:
    - modifyworld.*
    - essentials.fly
    - essentials.nick
    - essentials.chat.color
    - essentials.balance
    - essentials.pay
    - essentials.repair
    - essentials.spawn
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.warp.list
    - essentials.warp
    - essentials.kit
    - essentials.tpdeny
    - essentials.kits.pvp
    - essentials.kits.YT
    - essentials.kits.vip
    - essentials.kits.usuario
    - essentials.delhome
    - essentials.msg
    - essentials.kits.Usuario
    - essentials.enderchest
    - essentials.ping
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.free
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.kit
    - essentials.afk.auto
    - essentials.afk
    - essentials.balancetop
    - esencials.ignore
  YT:
    options:
      default: false
      prefix: '&f&lY&c&lT &8 '
    permissions:
    - modifyworld.*
    - essentials.fly
    - essentials.nick
    - essentials.chat.color
    - essentials.balance
    - essentials.pay
    - essentials.repair
    - essentials.spawn
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.warp.list
    - essentials.warp
    - essentials.kit
    - essentials.tpdeny
    - essentials.kits.pvp
    - essentials.kits.YT
    - essentials.kits.usuario
    - essentials.delhome
    - essentials.msg
    - essentials.kits.Usuario
    - essentials.enderchest
    - essentials.ping
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.free
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.kit
    - essentials.afk.auto
    - essentials.afk
    - essentials.balancetop
    - esencials.ignore
  Helper:
    options:
      default: false
      prefix: '&b&lHelper &8 '
    permissions:
    - modifyworld.*
    - ab.warn.perma - /warn
    - ab.warn.temp - /tempwarn
    - ab.warn.undo - /unwarn
    - ab.mute.perma - /mute
    - ab.mute.temp - /tempmute
    - ab.mute.undo - /unmute
    - ab.ipban.perma - /ipban
    - ab.ipban.temp - /tempipban
    - ab.ban.perma - /ban
    - ab.ban.temp - /tempban
    - ab.ban.undo - /unban
    - ab.kick.use - /kick
    - essentials.gamemode
    - essentials.vanish
    - essentials.fly
    - essentials.nick
    - essentials.chat.color
    - essentials.tp
    - essentials.balance
    - essentials.pay
    - essentials.tphere
    - essentials.invsee
    - essentials.signs.use.repair
    - essentials.repair
    - essentials.spawn
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.warp.list
    - essentials.warp
    - essentials.kit
    - essentials.signs.use.free
    - essentials.signs.use.disposal
    - essentials.tpdeny
    - essentials.signs.use.kits
    - essentials.signs.use.buy
    - essentials.signs.use.sell
    - essentials.kits.pvp
    - essentials.kits.YT
    - essentials.kits.vip
    - essentials.delhome
    - essentials.msg
    - essentials.kits.Usuario
    - essentials.baltop
    - essentials.sign.use.kit.pvp
    - essentials.balancetop
  Mod:
    options:
      default: false
      prefix: '&a&lMod &8 '
    permissions:
    - modifyworld.*
    - ab.warn.perma - /warn
    - ab.warn.temp - /tempwarn
    - ab.warn.undo - /unwarn
    - ab.mute.perma - /mute
    - ab.mute.temp - /tempmute
    - ab.mute.undo - /unmute
    - ab.ipban.perma - /ipban
    - ab.ipban.temp - /tempipban
    - ab.ban.perma - /ban
    - ab.ban.temp - /tempban
    - ab.ban.undo - /unban
    - ab.kick.use - /kick
    - essentials.gamemode
    - essentials.vanish
    - essentials.fly
    - essentials.nick
    - essentials.chat.color
    - essentials.tp
    - essentials.balance
    - essentials.pay
    - essentials.tphere
    - essentials.invsee
    - essentials.signs.use.repair
    - essentials.repair
    - essentials.spawn
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.warp.list
    - essentials.warp
    - essentials.kit
    - essentials.signs.use.free
    - essentials.signs.use.disposal
    - essentials.tpdeny
    - essentials.signs.use.kits
    - essentials.signs.use.buy
    - essentials.signs.use.sell
    - essentials.kits.pvp
    - essentials.kits.YT
    - essentials.kits.vip
    - essentials.delhome
    - essentials.msg
    - essentials.kits.Usuario
    - essentials.baltop
    - essentials.sign.use.kit.pvp
    - essentials.balancetop
  Builder:
    options:
      default: false
      prefix: '&9&lBuilder &8 '
    permissions:
    - modifyworld.*
    - '*'
  Admin:
    options:
      default: false
      prefix: '&c&lAdmin &8'
    permissions:
    - '*'
  Dev:
    options:
      default: false
      prefix: '&a&lDeveloper &8 '
    permissions:
    - modifyworld.*
    - '*'   
schema-version: 1

**Comment by zml2008** [comment]
pex 1 is no longer supported

**Comment by Haveyougonemad** [comment]
What do you mean

**Comment by astei** [comment]
PermissionsEx is undergoing a rewrite, and the old PermissionsEx versions (1.x.x) are not supported any more.

Until PermissionsEx 2 is stable, you'll probably want to search for a different permission plugin.
