### ISSUE TITLE
How do I add users to multiple groups but set them a specific prefix

### ISSUE THREAD

**Issue by santafejay** [PEXPlugins/PermissionsEx#3052]
So this is what I'm attempting to accomplish:

Have a user be Moderator and a Paid role at the same time, but have their prefix to be mod (make the higher rank the prefix that is used). I've executed /pex group groupname set rank # but it doesn't affect anything. any tips?

**Comment by Excalium-OG** [comment]
I am also trying to determine how to do this. I use autorank and I want staff members to also be able to autorank through paths, but keep their staff prefix.

'c0493d2c-bbc8-4ddd-a0e6-f3f10d7b881a/Excalium' is a member of:
Wright (rank 103 @ Construction)
Helper (rank 4 @ Staff)
Advanced (rank 150 @ Basic)
Member (rank 151 @ Basic)

So Started as Guest, then Member, then Advanced.
1. Prefix was Advanced
2. I added group Helper
3. Prefix is now Helper
4. I added group Wright
5. Prefix is now Wright

My goal is to add the group Wright (or any other non-staff group), but keep the Helper prefix.
