### ISSUE TITLE
Plugin error on Startup // 1.14.4 Paper

### ISSUE THREAD

**Issue by KarlPro123** [PEXPlugins/PermissionsEx#3054]
The full error can be found here:

https://pastebin.com/5Ue4WJnr

In general I haven't been able to get the latest dev builds working, tried multiple ones and also the newest one from jenkins.

**Comment by md678685** [comment]
Did you modify the default config? The default config doesn't set `default-backend` so it appears you have to uncomment and set that yourself.

**Comment by KarlPro123** [comment]
I'll try and let the plugin generate a new one quickly. I'll inform if it works.

**Comment by KarlPro123** [comment]
Oh indeed it started up when deleting the config! Thanks.
