### ISSUE TITLE
Most permission are not not working

### ISSUE THREAD

**Issue by pikachu99** [PEXPlugins/PermissionsEx#3055]
MC version: 1.14.4
PEX version: 1.23.4
I am having an issue with permission not working. I have setup permission correctly. I had a friend try to figure the issue out but couldn't figure it out. The issue I have with is all perms except bskyblock perms.

default:
    default: true
    permissions:
    - auctionhouse.use
    - auctionhouse.menu
    - auctionhouse.search
    - auctionhouse.help
    - auctionhouse.sell
    - auctionhouse.expired
    - auctionhouse.auctions.2
    - BeastTokens.balance
    - BeastTokens.shop.TokenShop
    - BeastTokens.MobTokenDrop
    - BeastTokens.withdraw
    - minions.player.linkchest
    - minions.player.helpcommand
    - minions.skins.*
    - jetshoppers.default.linkchest
    - jetshoppers.default.hologram
    - BossShop.open.*
    - BossShop.open.command
    - bskyblock.island.*
    - bskyblock.settings.*
    - bskyblock.team.maxsize.3
    - bskyblock.island.maxhomes.1
    - bskyblock.island.range.100
    - chestshop.shop.*
    - citizens.npc.talk
    - essentials.pay
    - essentials.helpop
    - essentials.spawn.*
    - essentials.itemdb
    - essentials.mail.send
    - essentials.mail
    - essentials.kit
    - essentials.tpa
    - essentials.tpdeny
    - essentials.tpahere
    - essentials.tpaccept
    - essentials.sethome
    - essentials.home
    - essentials.delhome
    - essentials.back
    - essentials.ping
    - essentials.seen
    - essentials.msg
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.crates
    - essentials.warps.tutorial
    - essentials.warps.pvp
    - essentials.warps.spawn
    - goldencrates.user
    - signurls.use
    - silkspawners.place.*
    - ultimatekits.use.*
    - ultimatekits.kit.starter
    - mcmmo.ability.*
    - mcmmo.chat.partychat
    - mcmmo.commands.defaults
    - multiverse.access.bskyblock_world
    - multiverse.access.bskyblock_world_nether
    - multiverse.access.bskyblock_world_the_end
    - multiverse.access.spawn

**Comment by md678685** [comment]
PEX 1.23.4 isn't supported here, nor is it supported anywhere else.
