### ISSUE TITLE
How to remove spawn blocking

### ISSUE THREAD

**Issue by stonecollin** [PEXPlugins/PermissionsEx#3057]
Hello, I am wanting to remove spawn where anyone who joins CAN access chests and destroy blocks at spawn. I am mainly using this for friends so the fact that they can't touch stuff right away is annoying. I can't find the command anywhere, please help! Thanks

**Comment by md678685** [comment]
This isn't a PEX feature.

You can disable spawn protection by editing the `server.properties` and changing the `spawn-protection` setting to `0`.

**Comment by zml2008** [comment]
Thanks md!
