### ISSUE TITLE
Where can I see all permission nodes

### ISSUE THREAD

**Issue by Itap88** [PEXPlugins/PermissionsEx#3059]
I'm not sure if it's the right place for this question but I have to ask. I've just made my way through the wiki and I have a problem. I don't know what permissions can be used for commands and world interactions. There are some of them at the wiki but many commands aren't mentioned there. Is there a list of possible permissions somewhere?

**Comment by zml2008** [comment]
There is no full list -- every plugin defines its own permissions, so you have to look at the documentation for each plugin you use.

**Comment by Itap88** [comment]
But there is one thing. What permissions does minecraft vanilla have?

**Comment by zml2008** [comment]
Vanilla minecraft doesn't define any of its own permissions -- depending on which platform you're using either Bukkit or Sponge's documentation will list all the permissions that are used.  You can always run `/pex toggle debug` (1.x) or `/pex debug` (2.x dev builds) to see which permissions are being checked when you try do do things and change settings based on that.

**Comment by Itap88** [comment]
Thank you.

**Comment by patricktsidina** [comment]
And what about all nodes that are directly within permissionsex?
