### ISSUE TITLE
PEX inheritance not working

### ISSUE THREAD

**Issue by RICKASHEYE** [PEXPlugins/PermissionsEx#3061]
checked my permissions.yaml for errors on a YAMLLint checker tool and it said valid and json parse looks good but no such thing as the next rank cant use the inherited ranks commands
https://pastebin.com/MjPbJD86
above is the pastebin link if you want to inspect! thanks!

**Comment by md678685** [comment]
It looks like the indentation in your permissions list is inconsistent - make sure the number of spaces on each permission node line is the same.

Either way, PEX 1.x isn't supported here.

**Comment by zml2008** [comment]
ya, `inheritance` is not an option
