### ISSUE TITLE
PEX Default role wont work

### ISSUE THREAD

**Issue by NotEvenSweating** [PEXPlugins/PermissionsEx#3062]
When i make the default role for my server setup, it doesnt give new players the role, can anyone help? 
Here is my config.yml https://pastebin.com/dUM67aXH
Here is my permissions.yml https://pastebin.com/0JfZnaAk

**Comment by robert-beckley** [comment]
Remove the ' from the default line, so change From `default: 'true'` to `default: true`

**Comment by zml2008** [comment]
PEX 1 is no longer supported, as you were told in the discord
