### ISSUE TITLE
1.12 - PermissionEx Not loading in

### ISSUE THREAD

**Issue by MatthewSKC** [PEXPlugins/PermissionsEx#3063]
Appears RED when I do /plugins (Bukkit)

Using Vault, WorldEdit, WorldGuard, NametagEdit & Essentials

**Comment by robert-beckley** [comment]
Any errors in console on startup?

**Comment by MatthewSKC** [comment]
READ THIS: You are running with the incorrect version of PEX for your MC version. Remember: use 1.22.x for 1.7.9+, and 1.23.x for 1.8.x

However the verision I am using is; PermissionsEx-1.22.10.jar

**Comment by robert-beckley** [comment]
Use version 1.23.4

**Comment by MatthewSKC** [comment]
Thanks! Works like a treat

**Please lock thread**

**Comment by zml2008** [comment]
that's actually impressive... using an even older yet equally unsupported version of the plugin
