### ISSUE TITLE
Permissions Per World NOT WORKING

### ISSUE THREAD

**Issue by Bioniclekolacz** [PEXPlugins/PermissionsEx#3064]
I cannot get permissions to work per world. Here is my permissions.yml: https://pastebin.com/69iKcfUm
Those in the Builder group should be able to use world edit in 2 of the worlds and /god in one of them. However it does not work, nor does it matter what permission node I put there.

**Comment by md678685** [comment]
PEX 1.x is no longer supported. This repository is for PEX 2, which is currently in development.

While PEX 2 is in development, you can switch to [LuckPerms](https://luckperms.github.io).
