### ISSUE TITLE
Error when running on Paper 1.15.1

### ISSUE THREAD

**Issue by viet** [PEXPlugins/PermissionsEx#3068]
I tried to install this new PEX plugin for bukkit/spigot/paper, however, I got this error everytime a player joins. It'd be great if you could help. Thanks!

https://pastebin.com/MYEpYXM9

**Comment by md678685** [comment]
Related: EssentialsX/Essentials#2901

Could you update to the [latest EssentialsX build](https://essentialsx.cf/downloads.html)?

**Comment by zml2008** [comment]
Thanks for the fix md!
