### ISSUE TITLE
Help PermissionsEx

### ISSUE THREAD

**Issue by 4TULL** [PEXPlugins/PermissionsEx#3076]
Hi, I have a problem. I have Donate Holy on the minecraft server. And it’s worth it in permissionsex - essentials.fly
But an ordinary player writes: You do not have access to that command how to fix this error?

**Comment by 4TULL** [comment]
My Pex https://pastebin.com/61Dxi5up

**Comment by zml2008** [comment]
PEX v1 is not supported
