### ISSUE TITLE
Pex don't Work help

### ISSUE THREAD

**Issue by 4TULL** [PEXPlugins/PermissionsEx#3077]
We create a server with a friend, test Privileges, I give him Donat Holy and he writes to you do not have access to that command Here is my Permissions.yml

https://pastebin.com/61Dxi5up Help please :( my config pex https://pastebin.com/MF90E0Rd

**Comment by zml2008** [comment]
As you were told in the previous issue you opened, PEX 1.23 is not supported. Stop asking for help here.
