### ISSUE TITLE
Issue going from the legacy Pex to Pex v2

### ISSUE THREAD

**Issue by ramdon-person** [PEXPlugins/PermissionsEx#3078]
Hi, I am having an issue when going from the legacy Pex to Pex v2. There is an issue with the conversion and I am getting the file "permissions.yml.legacy-backup" instead of permissions.yml.

Thanks,
Ram

**Comment by md678685** [comment]
PEX 2 doesn't use `permissions.yml` - when you update, it should migrate to whichever backend is specified in the config, which is by default `permissions.json` (which you have, according to
[an earlier version of your message](https://user-images.githubusercontent.com/1917406/75462971-02253b80-597d-11ea-8b26-84371ac41078.jpg)).

**Comment by zml2008** [comment]
That's not entirely true -- the schema migration and the file type migration are separate -- but both are automatically performed when loading the file backend. This means that you could theoretically write a yaml file with the v2 schema, or a json file with the v1 schema, and PEX should be able to load either just fine :)

**Comment by zml2008** [comment]
As of 9e4e11b8bc719890c00992347b648c75526f06d6 this issue should be fixed.
