### ISSUE TITLE
Hello, it's for a request

### ISSUE THREAD

**Issue by Link0Darck** [PEXPlugins/PermissionsEx#3084]
Hello it is for a request seen that I prefer your plugin and I don't want to switch to another plugin is it possible to update to 1.15.2 for my server please
Sincerely
Link_Darck
ps: thanks to the creator for this plugin

**Comment by robert-beckley** [comment]
It already works in 1.15.2 just use the latest build.

**Comment by Link0Darck** [comment]
> It already works in 1.15.2 just use the latest build.

Where is she, please?

**Comment by zml2008** [comment]
PEX v1 is no longer supported, for now use LuckPerms

**Comment by Link0Darck** [comment]
> PEX v1 is no longer supported, for now use LuckPerms

Oh no no LuckPerms I've had problems with my permissions and my permissions are linked by MYSQL database please can you put it in 1.15.2

**Comment by zml2008** [comment]
no -- luckperms' discord is available at https://discord.gg/luckperms

**Comment by robert-beckley** [comment]
Bro it works in 1.15.2 just use it 
https://github.com/PEXPlugins/PermissionsEx/releases/tag/STABLE-1.23.4

**Comment by Link0Darck** [comment]
robert-beckley thanks
