### ISSUE TITLE
pex user/group not working anymore in 2.0

### ISSUE THREAD

**Issue by mhelluy** [PEXPlugins/PermissionsEx#3086]
I used to use the 1.x version of the plugin. To use it in 1.15, I installed the 2.x version.
Since I installed it, I cannot use basic commands like pex user or pex group. There are options like "pex callback","pex debug",etc. Do I have the official version ?

**Comment by zml2008** [comment]
PEX v2 has different commands from v1. See https://permissionsex.stellardrift.ca/learning-v2-from-other-plugins-and-v1/command-equivalency (and the rest of the docs) for details.

**Comment by mhelluy** [comment]
Thank you very much !
