### ISSUE TITLE
Integration (code examples out of date)

### ISSUE THREAD

**Issue by Chalwk77** [PEXPlugins/PermissionsEx#3133]
Could someone please update the code examples section within the *Integrating with PEX* category in with Wiki.
https://github.com/PEXPlugins/PermissionsEx/wiki/Integrating-with-PEX

They seem to be out of date.

**Comment by zml2008** [comment]
no, PEX v1 is no longer supported, and PEX v2 does not yet have a stable API. Once a stable API is available, the documentation at https://permissionsex.stellardrift.ca will be updated.

**Comment by Chalwk77** [comment]
OK, with PEX v2, how exactly would I retrieve a user's permissions? (Separate from group permissions)

**Comment by zml2008** [comment]
did you read what i said....?

**Comment by Chalwk77** [comment]
Yes, sir. Of course, I did. 

I understand that V2 is not stable, but I wondered if at the very least there was a way to retrieve this information in its current state. No worries, I will wait until a stable API is available.

Cheers.
