### ISSUE TITLE
Pex prefix broken

### ISSUE THREAD

**Issue by IgnJoinIn** [PEXPlugins/PermissionsEx#3135]
So i have a minehut server and I use pex when i do the prefix

"&7[&aVip&7] that works fine but when i try to add a space between ranks it dosent work

"&7[&aVip&7] "

here is issue https://i.badlion.net/SuA5tMpnYr2y9nCUjJeH3U.png

**Comment by zml2008** [comment]
PermissionsEx v1 is unsupported. Since Minehut has decided to continue distributing the plugin, you should be asking them for support.
