### ISSUE TITLE
[Bug] permissions.manage.membership.builder can be used to delete others' other permissions group

### ISSUE THREAD

**Issue by Chuanwise** [PEXPlugins/PermissionsEx#3140]
User with "permissions.manage.membership.<group>" can delete others' permission groups by "/pex user <user id> group set <group name>".

For example, I have "permissions.manage.membership.builder" in a special world, but I'm just a world owner, no global owner.
I will use command "/pex user <user id> group add <group name>" to give others the permission to build with "/pex user <user id> group add <group name. Members in this group can build in the world>". I haven't access to delete other permissions.
But In fact, I can use command "/pex user <user id> group set <group name>" to set others' permission groups, and it will delete his all other permission group.

**Comment by zml2008** [comment]
PEX v1 is no longer supported.
