### ISSUE TITLE
Hello i have the same issue with too many arguments but i am using plugin named residence on my survival server and if i dont use pex it allows players to break blocks inside residence

### ISSUE THREAD

**Issue by Peanutismo123** [PEXPlugins/PermissionsEx#3145]

**Comment by zml2008** [comment]
Either you're using PEX v1 which is unsupported, or you're using the unstable development builds of PEX v2 which just had commands rewritten to work less badly.

Unfortunately, you seem to have not realized that there is a "description" field where you could give actual information (like what is "the same issue"), so there's not much else to say here.
