### ISSUE TITLE
[1.17[FeatureRequest] Allow interactions with consumables

### ISSUE THREAD

**Issue by c-goldschmidt** [PEXPlugins/PermissionsEx#3227]
The permission `-essentials.build.interact.*` prevents interactions with world objects such as doors, chests and so on. Unfortunately it also prevents the players from using consumables like food and potions. Is there any way to allow the users to use consumables, but keep preventing them vom opening chests and doors?

**Comment by zml2008** [comment]
Please take a moment and read the name of the repository you opened an issue on.
