### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WolffangSorano** [PEXPlugins/PermissionsEx#3246]
My server crashed when I used this plugin and tried to join. Attached is the crash report.
[crash-2023-03-08_10.54.52-server.txt](https://github.com/PEXPlugins/PermissionsEx/files/10924708/crash-2023-03-08_10.54.52-server.txt)

**Comment by zml2008** [comment]
PEX 1.23.x hasn't been supported in years - to get the error you're getting you'd have to be using some sort of unofficial fork. Please use LuckPerms instead.
