### ISSUE TITLE
Promotion Error: User are not in this ladder

### ISSUE THREAD

**Issue by ghost** [PEXPlugins/PermissionsEx#427]
Hello,
First of all want you to know that I know there are two more closed topics on this issue, I read both of them and I still have the same problem. Yes, I'm using /pex promote [username] and I only have one ladder, so it's default. But I still get this error:

[INFO] Promotion error: User are not in this ladder
[SEVERE] Ranking Error (console promotes n3n): User are not in this ladder

Here is my permissions.yml: https://pastee.org/cevff

I'd really appreciate some help. Thanks

**Comment by b0bthed0n** [comment]
idk
