### ISSUE TITLE
[Feature request] Remove/reset prefix with command

### ISSUE THREAD

**Issue by aciidic** [PEXPlugins/PermissionsEx#486]
At the moment you can set a user's prefix with /pex user <user> prefix [newprefix]
And you can get the user's current prefix with /pex user <user> prefix

But there is no way to reset or remove a prefix?
If there is please tell me how :)

**Comment by Skaizdoesmc** [comment]
Hey, I can't use:
	       Bukkit.dispatchCommand(getServer().getConsoleSender(), "pex user " + player.getName() + " prefix """);
Maybe add another way to reset prefixes??.

**Comment by WebmetsHD** [comment]
if you want to reset someones prefix via bukkit
Bukkit.dispatchCommand(getServer().getConsoleSender(), "pex user " + player.getName() + " prefix \"\"")

that will do the trick :)

**Comment by Stormbow** [comment]
A quotation marks = " and an apostrophe = ' and a single quote = ‘. (Notice the angle on the single quote and the straightness of the apostrophe.) If you use single quotes anywhere, PEX will malfunction. If you use apostrophes anywhere, PEX will function correctly, if apostrophes are allowed where you've used them.

**Comment by Hannex321** [comment]
i cant reset it,i've tried watching alot of videos
none work,i really need help

**Comment by Stormbow** [comment]
Sorry, Hannex321, PEX is no longer supported.

**Comment by md678685** [comment]
> Sorry, Hannex321, PEX is no longer supported.

To clarify: PEX 1.x is no longer supported. PEX 2.x is currently under development.

**Comment by Stormbow** [comment]
> 
> > Sorry, Hannex321, PEX is no longer supported.
> To clarify: PEX 1.x is no longer supported. PEX 2.x is currently under development.

It should also be noted that PEX 2.x has been under development for more than 6 years— the 2+ years since I stopped providing the vast majority of support for PEX 1.x and for the 4+ years that I _was_ the vast majority of support for PEX 1.x.

**Comment by zml2008** [comment]
Yes, I stepped away from the project and now I'm back :)
