### ISSUE TITLE
/pex user <user> group add <group> "" 30 -- doesnt work!?

### ISSUE THREAD

**Issue by Bubelbub** [PEXPlugins/PermissionsEx#695]
Hello,

the command doesnt work:
`/pex user <user> group add <group> "" 30`

I would add the group `<group>` to the user `<user>` on all worlds for 30 seconds.

Like this command reference:
https://github.com/PEXPlugins/PermissionsEx/wiki/Commands
`pex user <user> group add <group> [world] [lifetime]`
But doesn't work.

**Comment by R98rayan2** [comment]
> I didn't tested '*' value with yaml, my servers working under MySQL.
> I will look up for this now. Thank you.
> 
> P.S. I've tested current version and I think that you use old build. Latest build works perfectly with command
> 
> /pex user destany group add VIP+ * 23423741
> 
> and it doesn't create subnode worlds.*:
> ![image](https://camo.githubusercontent.com/ed1e2330e8f5bedfcb1efddfe2d5d9d4861970a3/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323639373735342f3237393132342f38643130653236362d393130642d313165322d383666612d3836646332363637613330642e706e67)
> 
> You should fork and build current PEX repository to get correct version or wait some time while authors will do it.
> 
> On the other side the node worlds.* should be correctly dispatched by pex and it is work for developers (or me as patch author).

do you know what is mean the number 1388622157 mean if i want to know the time ?

**Comment by SimSonic** [comment]
> do you know what is mean the number 1388622157 mean if i want to know the time ?

It is unix timestamp, number of seconds from 1 Jan 1970.

**Comment by R98rayan** [comment]
> > do you know what is mean the number 1388622157 mean if i want to know the time ?
> 
> It is unix timestamp, number of seconds from 1 Jan 1970.
> You can convert it [here](https://www.unixtimestamp.com), for example.

Thank You My Friend <3
